import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

import {
  authoredFacadePathSet,
  buildGeneratedArtifactStatus,
  prepareExternalFacadeStorageCatalog,
  renderExpectedGeneratedArtifacts,
  repoRoot,
} from "../porter.mjs";
import {
  buildBundledGeneratedArtifactStatus,
  buildExpectedBundledArtifacts,
  collectBundledArtifactFailures,
  writeBundledGenerated,
} from "../../bundled/generate-bundled.mjs";
import {
  buildExpectedUnicodeArtifacts,
  buildUnicodeGeneratedArtifactStatus,
  buildUnicodeGeneratedArtifactStatusDeep,
  UNICODE_VERSION,
} from "../../unicode/generate-unicode-data.mjs";
import {
  baseConfig,
  fileRecord,
  makePorterTestTemp,
  semanticFunctionDeclaration,
  selectorType,
  snapshotWith,
  unitRecord,
} from "./helpers.mjs";
import {
  semanticBasicType,
  semanticFunctionFixture,
  semanticNamedType,
  semanticTypeFixture,
  writerTypeFixture,
} from "./rendering-semantic-fixtures.mjs";
import {
  finalizeGeneratedFacadeFixtureCatalog,
} from "./external-facade-fixtures.mjs";

test("renderExpectedGeneratedArtifacts embeds deterministic generated metadata", () => {
  const snapshot = snapshotWith([]);
  const artifacts = renderExpectedGeneratedArtifacts(baseConfig, snapshot, finalizeGeneratedFacadeFixtureCatalog(baseConfig, snapshot));
  const scalars = artifacts.get("packages/tsts/src/go/scalars.ts");
  assert.match(scalars, /^\/\/ Code generated by TSTS porter\. DO NOT EDIT\./);
  assert.match(scalars, /\/\/ @tsgo-generated {"schemaVersion":1,"kind":"go-scalars","generator":"porter:facades","sourceRevision":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","path":"go\/scalars\.ts","contentHash":"[a-f0-9]{64}"}/);
  assert.match(scalars, /export type int = number;/);
  assert.match(scalars, /export type ulong = number;/);
  const compat = artifacts.get("packages/tsts/src/go/compat.ts");
  assert.match(compat, /^\/\/ Code generated by TSTS porter\. DO NOT EDIT\./);
  assert.match(compat, /\/\/ @tsgo-generated {"schemaVersion":1,"kind":"go-compat","generator":"porter:facades","sourceRevision":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","path":"go\/compat\.ts","contentHash":"[a-f0-9]{64}"}/);
  assert.match(compat, /export class GoStructMap<K, V> implements Map<K, V>/);
  assert.match(compat, /export function NewGoStructMap<K, V>\(keyDescriptor: GoMapKeyDescriptor<K>\): GoStructMap<K, V>/);
  assert.match(compat, /export function GoStructKey<K, const Values extends readonly unknown\[\]>/);
  assert.match(compat, /export function GoInterfaceKey<K>/);
  assert.match(compat, /export interface GoInterfaceValue<T> \{\s*__tsgoGoReceiver\(\): GoPtr<T>;/);
  assert.match(compat, /readonly identity: symbol/);
  assert.match(compat, /snapshot\(value: K\): K/);
  assert.doesNotMatch(compat, /goStructMapKey|JSON\.stringify|\.Hi\b|\.Lo\b|\.pos\b|\.end\b/);
  assert.doesNotMatch(compat, /goReceiverKey|GoInterfaceAdapter|GoInterfaceTryAssert|GoInterfaceAssert|Object\.defineProperties/);
  assert.match(compat, /export function MakeGoChan<T>\(capacity: number, zeroValue: \(\) => T\): GoChan<T>/);
  assert.match(compat, /export function GoRequireNonNilAfterSuccess<T>/);
  assert.match(compat, /export function GoMapLookup<K, V>/);
  assert.match(compat, /export function GoChanSelect\(cases: readonly GoChanSelectCase\[\]\)/);
  assert.match(compat, /export function GoChanAsReceive<T>\(channel: GoChan<T>\): GoChan<T, "receive">/);
  assert.match(compat, /export function GoChanAsSend<T>\(channel: GoChan<T>\): GoChan<T, "send">/);
  assert.match(compat, /export function GoChanTrySend<T>\(channel: GoChan<T, string>, value: T\): bool/);
  assert.match(compat, /export function GoChanReceive<T>\(channel: GoChan<T, string>, receiver: GoChannelReceiver<T>\): \(\) => void/);
  assert.match(compat, /export function GoChanClose<T>\(channel: GoChan<T, string>\): void/);
});

test("host-native source signatures create only declaration-level facade obligations", () => {
  const packagePath = "example.com/main/internal/native";
  const config = {
    ...baseConfig,
    goModulePath: "example.com/main",
    policies: [
      { match: "internal/native/**", category: "host-native", reason: "Node host boundary" },
      ...baseConfig.policies,
    ],
    externalFacadePolicies: [{
      objectId: "example.com/syscall::type::Handle",
      tsModule: "go/example.com/syscall.ts",
      tsName: "Handle",
      storageStrategy: "generated",
    }],
  };
  const snapshot = snapshotWith([
    fileRecord({
      path: "internal/native/path.go",
      importPath: packagePath,
      imports: [{ path: "example.com/syscall", packageName: "syscall" }],
      units: [unitRecord({
        id: "example.com/main::internal/native/path.go::func::Fail",
        goPath: "internal/native/path.go",
        parameters: [{ names: ["handle"], type: selectorType("syscall", "Handle") }],
        semantic: semanticFunctionDeclaration({
          name: "Fail",
          packagePath,
          parameters: [{ names: ["handle"], type: selectorType("syscall", "Handle") }],
          packages: { syscall: "example.com/syscall" },
        }),
      })],
    }),
  ]);
  snapshot.semantic.dependencyTypeDeclarations = [semanticTypeFixture("example.com/syscall", "Handle", semanticBasicType("uintptr"))];

  const catalog = finalizeGeneratedFacadeFixtureCatalog(config, snapshot);
  assert.ok(
    catalog.artifactFacades(config, snapshot).has("example.com/syscall::type::Handle"),
    "host-native source signatures remain exact facade obligations",
  );
});

test("buildGeneratedArtifactStatus catches missing, stale, orphan, untracked, and invalid generated files", () => {
  const root = makePorterTestTemp("porter-test-");
  try {
    const config = {
      ...baseConfig,
      tsRoot: path.relative(repoRoot, path.join(root, "src")).split(path.sep).join("/"),
      tsFilePolicies: [
        { match: "**/*.test.ts", category: "test-parity", reason: "test parity" },
        ...baseConfig.tsFilePolicies,
      ],
    };
    const snapshot = snapshotWith([]);
    const facades = finalizeGeneratedFacadeFixtureCatalog(config, snapshot);
    const generatedRoot = path.join(root, "src/go");
    mkdirSync(generatedRoot, { recursive: true });
    for (const [relativePath, text] of renderExpectedGeneratedArtifacts(config, snapshot, facades)) {
      const targetPath = path.join(repoRoot, relativePath);
      mkdirSync(path.dirname(targetPath), { recursive: true });
      writeFileSync(targetPath, text);
    }
    let clean = buildGeneratedArtifactStatus(config, snapshot, facades);
    assert.deepEqual(clean, { missing: [], stale: [], orphan: [], untracked: [], invalid: [] });

    const compatArtifact = renderExpectedGeneratedArtifacts(config, snapshot, facades).get(`${config.tsRoot}/go/compat.ts`);
    writeFileSync(path.join(generatedRoot, "hidden.test.ts"), compatArtifact.replace('"path":"go/compat.ts"', '"path":"go/hidden.test.ts"'));
    for (const directory of [".git", "dist", "node_modules"]) {
      mkdirSync(path.join(generatedRoot, directory), { recursive: true });
      writeFileSync(
        path.join(generatedRoot, directory, "hidden.ts"),
        compatArtifact.replace('"path":"go/compat.ts"', `"path":"go/${directory}/hidden.ts"`),
      );
    }
    const forged = buildGeneratedArtifactStatus(config, snapshot, facades);
    assert.deepEqual(forged.invalid.map((issue) => issue.path), [`${config.tsRoot}/go/hidden.test.ts`]);
    assert.deepEqual(forged.orphan.map((issue) => issue.path), [
      `${config.tsRoot}/go/.git/hidden.ts`,
      `${config.tsRoot}/go/dist/hidden.ts`,
      `${config.tsRoot}/go/node_modules/hidden.ts`,
    ]);

    writeFileSync(
      path.join(generatedRoot, "compat.ts"),
      renderExpectedGeneratedArtifacts(config, snapshot, facades).get(`${config.tsRoot}/go/compat.ts`).replace(/\n$/, "\nexport const edited = true;\n"),
    );
    writeFileSync(path.join(generatedRoot, "manual.ts"), "export const manual = true;\n");
    writeFileSync(path.join(generatedRoot, "bad.ts"), "// Code generated by TSTS porter. DO NOT EDIT.\n// @tsgo-generated {bad-json}\n\nexport {}\n");
    const orphan = renderExpectedGeneratedArtifacts(config, snapshot, facades).get(`${config.tsRoot}/go/compat.ts`).replace('"path":"go/compat.ts"', '"path":"go/orphan.ts"');
    writeFileSync(path.join(generatedRoot, "orphan.ts"), orphan);
    rmSync(path.join(generatedRoot, "scalars.ts"), { force: true });

    const broken = buildGeneratedArtifactStatus(config, snapshot, facades);
    assert.equal(broken.missing.length, 1);
    assert.equal(broken.stale.length, 1);
    assert.equal(broken.orphan.length, 4);
    assert.equal(broken.untracked.length, 1);
    assert.equal(broken.invalid.length, 2);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("bundled-generator catches missing, stale, orphan, untracked, and invalid generated files", () => {
  const root = makePorterTestTemp("bundled-test-");
  try {
    const sourceRoot = path.relative(repoRoot, path.join(root, "vendor")).split(path.sep).join("/");
    const tsRoot = path.relative(repoRoot, path.join(root, "src")).split(path.sep).join("/");
    const libSource = path.join(root, "vendor/internal/bundled/libs");
    mkdirSync(libSource, { recursive: true });
    mkdirSync(path.join(root, "src"), { recursive: true });
    writeFileSync(path.join(libSource, "lib.one.d.ts"), "declare const one: 1;\n");
    const config = { ...baseConfig, sourceRoot, tsRoot };

    const missing = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.deepEqual(collectBundledArtifactFailures(missing), ["3 missing bundled artifacts"]);
    assert.equal(writeBundledGenerated(config, "rev"), 3);

    const clean = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.deepEqual(clean, { missing: [], stale: [], orphan: [], untracked: [], invalid: [] });
    const expected = buildExpectedBundledArtifacts(config, "rev");
    assert.match(expected.get(`${tsRoot}/internal/bundled/libs_generated.ts`), /"path":"internal\/bundled\/libs_generated\.ts"/);

    writeFileSync(
      path.join(root, "src/internal/bundled/embed_generated.ts"),
      expected.get(`${tsRoot}/internal/bundled/embed_generated.ts`).replace(/\["libs\/lib\.one\.d\.ts", \d+\]/, '["libs/lib.one.d.ts", 999]'),
    );
    const stale = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.equal(stale.stale.length, 1);

    writeBundledGenerated(config, "rev");
    unlinkSync(path.join(root, "src/internal/bundled/libs/lib.one.d.ts"));
    const missingLib = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.equal(missingLib.missing.length, 1);

    writeBundledGenerated(config, "rev");
    writeFileSync(path.join(root, "src/internal/bundled/libs/extra.d.ts"), "not generated\n");
    const untracked = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.equal(untracked.untracked.length, 1);

    writeBundledGenerated(config, "rev");
    writeFileSync(
      path.join(root, "src/internal/bundled/libs/extra.d.ts"),
      `// Code generated by TSTS bundled generator. DO NOT EDIT.\n// @tsgo-generated {"schemaVersion":1,"kind":"bundled-generated","generator":"porter:bundled","sourceRevision":"rev","path":"internal/bundled/libs/extra.d.ts","contentHash":"${"a".repeat(64)}"}\n\n`,
    );
    const orphan = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.equal(orphan.orphan.length, 1);

    writeBundledGenerated(config, "rev");
    const directOrphanPath = path.join(root, "src/internal/bundled/old_generated.ts");
    writeFileSync(
      directOrphanPath,
      `// Code generated by TSTS bundled generator. DO NOT EDIT.\n// @tsgo-generated {"schemaVersion":1,"kind":"bundled-generated","generator":"porter:bundled","sourceRevision":"rev","path":"internal/bundled/old_generated.ts","contentHash":"${"a".repeat(64)}"}\n\n`,
    );
    const directOrphan = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.deepEqual(directOrphan.orphan.map((issue) => issue.path), [`${tsRoot}/internal/bundled/old_generated.ts`]);
    unlinkSync(directOrphanPath);

    writeBundledGenerated(config, "rev");
    writeFileSync(path.join(root, "src/internal/bundled/libs/extra.d.ts"), "// @tsgo-generated {bad-json}\n");
    const invalid = buildBundledGeneratedArtifactStatus(config, "rev");
    assert.equal(invalid.invalid.length, 1);
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
});

test("unicode-generator classifies every file in its registered generated root", () => {
  const root = makePorterTestTemp("unicode-artifact-test-");
  try {
    const tsRoot = path.relative(repoRoot, path.join(root, "src")).split(path.sep).join("/");
    const generatedRoot = path.join(root, "src/internal/stringutil/generated");
    mkdirSync(generatedRoot, { recursive: true });
    assert.equal(buildUnicodeGeneratedArtifactStatus({ tsRoot }).missing.length, 2);

    for (const name of ["identifier_parts_generated.ts", "js_case_generated.ts"]) {
      const artifactPath = `internal/stringutil/generated/${name}`;
      writeFileSync(path.join(generatedRoot, name), unicodeArtifact(artifactPath, "export {};\n"));
    }
    assert.deepEqual(buildUnicodeGeneratedArtifactStatus({ tsRoot }), { missing: [], stale: [], orphan: [], untracked: [], invalid: [] });

    writeFileSync(path.join(generatedRoot, "obsolete.ts"), unicodeArtifact("internal/stringutil/generated/obsolete.ts", "export {};\n"));
    const orphan = buildUnicodeGeneratedArtifactStatus({ tsRoot });
    assert.deepEqual(orphan.orphan.map((issue) => issue.path), [`${tsRoot}/internal/stringutil/generated/obsolete.ts`]);

    writeFileSync(path.join(generatedRoot, "obsolete.ts"), "export {};\n");
    const untracked = buildUnicodeGeneratedArtifactStatus({ tsRoot });
    assert.deepEqual(untracked.untracked.map((issue) => issue.path), [`${tsRoot}/internal/stringutil/generated/obsolete.ts`]);

    writeFileSync(path.join(generatedRoot, "obsolete.ts"), unicodeArtifact("internal/stringutil/generated/obsolete.ts", "export {};\n", { extra: true }));
    const invalid = buildUnicodeGeneratedArtifactStatus({ tsRoot });
    assert.deepEqual(invalid.invalid.map((issue) => issue.path), [`${tsRoot}/internal/stringutil/generated/obsolete.ts`]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("deep Unicode verification honors the configured TypeScript root", async () => {
  const root = makePorterTestTemp("unicode-deep-test-");
  try {
    const tsRoot = path.relative(repoRoot, path.join(root, "src")).split(path.sep).join("/");
    const expected = await buildExpectedUnicodeArtifacts({ tsRoot });
    assert.deepEqual([...expected.keys()], [
      `${tsRoot}/internal/stringutil/generated/identifier_parts_generated.ts`,
      `${tsRoot}/internal/stringutil/generated/js_case_generated.ts`,
    ]);
    for (const [relativePath, text] of expected) {
      mkdirSync(path.dirname(path.join(repoRoot, relativePath)), { recursive: true });
      writeFileSync(path.join(repoRoot, relativePath), text);
    }
    assert.deepEqual(await buildUnicodeGeneratedArtifactStatusDeep({ tsRoot }), { missing: [], stale: [], orphan: [], untracked: [], invalid: [] });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("facade catalog bootstrap uses bounded authored sources and virtual generated foundations", async () => {
  const root = makePorterTestTemp("porter-test-");
  try {
    const config = authoredWriterConfig(root);
    const snapshot = authoredWriterSnapshot();
    const generatedRoot = path.join(root, "src/go");
    mkdirSync(path.join(root, "src/internal"), { recursive: true });
    mkdirSync(generatedRoot, { recursive: true });
    writeFileSync(path.join(generatedRoot, "io.ts"), `import type { byte, int } from "./scalars.js";
import type { GoError, GoSlice } from "./compat.js";
import type { Token } from "./example.com/native.js";

export interface Writer { Write(value: GoSlice<byte>): [int, GoError]; }
export type WriterToken = Token;
`);
    writeFileSync(path.join(root, "src/internal/unrelated.ts"), 'export { Missing } from "./absent.js";\n');

    assert.equal(existsSync(path.join(generatedRoot, "scalars.ts")), false);
    assert.equal(existsSync(path.join(generatedRoot, "compat.ts")), false);
    const facades = await prepareExternalFacadeStorageCatalog(config, snapshot, repoRoot);

    assert.ok(facades.artifactFacades(config, snapshot).has("io::type::Writer"));
    assert.ok(facades.artifactFacades(config, snapshot).has("example.com/native::type::Token"));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

function unicodeArtifact(artifactPath, body, extra = {}) {
  const metadata = {
    schemaVersion: 1,
    kind: "unicode-generated",
    generator: "porter:unicode",
    sourceRevision: UNICODE_VERSION,
    path: artifactPath,
    contentHash: createHash("sha256").update(body).digest("hex"),
    ...extra,
  };
  return `// Code generated by TSTS unicode generator. DO NOT EDIT.\n// @tsgo-generated ${JSON.stringify(metadata)}\n\n${body}`;
}

test("facade catalog bootstrap fails on missing configured and relative authored sources", async () => {
  const root = makePorterTestTemp("porter-test-");
  try {
    const config = authoredWriterConfig(root);
    const snapshot = authoredWriterSnapshot();
    const generatedRoot = path.join(root, "src/go");
    mkdirSync(generatedRoot, { recursive: true });
    await assert.rejects(
      prepareExternalFacadeStorageCatalog(config, snapshot, repoRoot),
      /configured authored facade module 'go\/io\.ts' is missing/,
    );

    writeFileSync(path.join(generatedRoot, "io.ts"), `import type { WriterOptions } from "./writer-options.js";

export interface Writer { Write(options: WriterOptions): void; }
`);

    await assert.rejects(
      prepareExternalFacadeStorageCatalog(config, snapshot, repoRoot),
      /relative module '\.\/writer-options\.js'.*resolves to missing '.*\/go\/writer-options\.ts'/,
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("authoredFacadeModules require the exact public symbol while remaining excluded from generation", async () => {
  const root = makePorterTestTemp("porter-test-");
  try {
    const config = authoredWriterConfig(root);
    const snapshot = authoredWriterSnapshot();
    const generatedRoot = path.join(root, "src/go");
    mkdirSync(generatedRoot, { recursive: true });
    writeFileSync(path.join(generatedRoot, "io.ts"), "export interface Writer { Write(): void; }\n");
    const facades = await prepareExternalFacadeStorageCatalog(config, snapshot, repoRoot);
    assert.throws(() => facades.artifactFacades({ ...config }, snapshot), /different config or snapshot/);
    assert.throws(() => facades.artifactFacades(config, structuredClone(snapshot)), /different config or snapshot/);
    assert.throws(() => { config.tsRoot = "changed"; }, TypeError);
    assert.throws(() => snapshot.files.push({}), TypeError);

    // The policy resolves "go/io.ts" to a full repo-relative path.
    assert.ok(authoredFacadePathSet(config).has(`${config.tsRoot}/go/io.ts`));

    // io.ts is excluded from the deterministic generated set (porter:facades will not regenerate it).
    const expected = renderExpectedGeneratedArtifacts(config, snapshot, facades);
    assert.ok(!expected.has(`${config.tsRoot}/go/io.ts`));

    for (const [relativePath, text] of expected) {
      const targetPath = path.join(repoRoot, relativePath);
      mkdirSync(path.dirname(targetPath), { recursive: true });
      writeFileSync(targetPath, text);
    }

    // Authored declaration validity belongs to finalized catalog construction, not generated-artifact status.
    writeFileSync(path.join(generatedRoot, "io.ts"), "export const Other = 1;\n");
    await assert.rejects(
      prepareExternalFacadeStorageCatalog(config, snapshot, repoRoot),
      /does not resolve to an indexed type declaration/,
    );
    assert.deepEqual(buildGeneratedArtifactStatus(config, snapshot, facades), { missing: [], stale: [], orphan: [], untracked: [], invalid: [] });

    writeFileSync(path.join(generatedRoot, "io.ts"), "export interface Writer { Write(): void; }\n");
    assert.deepEqual(buildGeneratedArtifactStatus(config, snapshot, facades), { missing: [], stale: [], orphan: [], untracked: [], invalid: [] });

    // An authored module that still carries @tsgo-generated metadata is invalid (never both).
    writeFileSync(
      path.join(generatedRoot, "io.ts"),
      "// Code generated by TSTS porter. DO NOT EDIT.\n// @tsgo-generated {\"schemaVersion\":1,\"kind\":\"go-facade\",\"generator\":\"porter:facades\",\"path\":\"go/io.ts\",\"sourceRevision\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"contentHash\":\"x\"}\n\nexport {}\n",
    );
    const conflicted = buildGeneratedArtifactStatus(config, snapshot, facades);
    assert.equal(conflicted.invalid.length, 1);
    assert.match(conflicted.invalid[0].reason, /Authored facade module must not carry @tsgo-generated/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

function authoredWriterConfig(root) {
  const tsRoot = path.relative(repoRoot, path.join(root, "src")).split(path.sep).join("/");
  return {
    ...baseConfig,
    tsRoot,
    signatureCheck: {
      facadeTemplate: `${tsRoot}/go/{importPath}.ts`,
      modules: {
        compat: `${tsRoot}/go/compat.ts`,
        core: `${tsRoot}/go/scalars.ts`,
      },
    },
    authoredFacadeModules: ["go/io.ts"],
    externalFacadePolicies: [{ objectId: "io::type::Writer", tsModule: "go/io.ts", tsName: "Writer", storageStrategy: "authored" }],
  };
}

function authoredWriterSnapshot() {
  const snapshot = snapshotWith([fileRecord({
    imports: [{ path: "example.com/native" }, { path: "io" }],
    units: [
      unitRecord({
        id: "github.com/microsoft/typescript-go::internal/debug/debug.go::func::Fail",
        parameters: [{ names: ["writer"], type: selectorType("io", "Writer") }],
        semantic: semanticFunctionFixture("github.com/microsoft/typescript-go/internal/debug", "Fail", [
          { name: "writer", type: semanticNamedType("io::type::Writer", "io", "Writer", true) },
        ]),
      }),
      unitRecord({
        id: "github.com/microsoft/typescript-go::internal/debug/debug.go::func::UseToken",
        parameters: [{ names: ["token"], type: selectorType("example.com/native", "Token") }],
        semantic: semanticFunctionFixture("github.com/microsoft/typescript-go/internal/debug", "UseToken", [
          { name: "token", type: semanticNamedType("example.com/native::type::Token", "example.com/native", "Token") },
        ]),
      }),
    ],
  })]);
  snapshot.semantic.dependencyTypeDeclarations = [
    semanticTypeFixture("example.com/native", "Token", semanticBasicType("string")),
    writerTypeFixture(),
  ];
  return snapshot;
}
