/**
 * Type-print utilities (auxiliary to `type-printer.ts`).
 *
 * Ported from Strada `printer.go` (within `checker`) — small helpers
 * used during type-to-string rendering for parens, ellipses, and
 * truncation thresholds.
 */

const DefaultTruncationLength = 100;

/**
 * Truncates a string to `maxLength`, appending an ellipsis.
 */
export function truncate(text: string, maxLength = DefaultTruncationLength): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + "...";
}

/**
 * Returns true when the text would be truncated at the default
 * length.
 */
export function wouldBeTruncated(text: string): boolean {
  return text.length > DefaultTruncationLength;
}

/**
 * Wraps text in parentheses if `condition` is true.
 */
export function parenthesizeIf(text: string, condition: boolean): string {
  return condition ? "(" + text + ")" : text;
}

/**
 * Returns the indentation prefix for a given level.
 */
export function indent(level: number): string {
  return "  ".repeat(Math.max(0, level));
}

/**
 * Joins a list of items with a separator, handling the empty case.
 */
export function joinNonEmpty(items: readonly string[], separator: string): string {
  return items.filter((s) => s.length > 0).join(separator);
}

/**
 * Returns true when a name is "synthetic" — generated by the compiler
 * rather than written by the user (e.g. `__anonymous`, `__type`).
 */
export function isSyntheticName(name: string): boolean {
  return name.startsWith("__");
}

/**
 * Returns the visible (non-synthetic) name of a symbol, falling back
 * to a placeholder when the name is synthetic.
 */
export function getVisibleName(name: string): string {
  return isSyntheticName(name) ? "<anonymous>" : name;
}

/**
 * Escapes a string for JSON-style display.
 */
export function escapeForDisplay(s: string): string {
  return JSON.stringify(s);
}
