Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go d35cc5f485640a41fbbf5a2267e9b11c7a7db4dc.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationEmitPartialNodeReuse.d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [b.d.ts] ////
<<< pinned TS-Go intentionally emits no output for this section >>>
//// [c.d.ts] ////
<<< pinned TS-Go intentionally emits no output for this section >>>
