Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go 515d036f927aba8b468011098e2721335f0e2d00.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationFunctionDeclarations.d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [fnDecl.d.ts] ////
type T = number[];
export declare function fnDeclBasic1(p: (number[] | string[] | [T]) | undefined, rParam: string): void;
export declare function fnDeclBasic2(p: ((n: T) => T) | undefined, rParam: string): void;
export declare function fnDeclBasic3(p: (new () => any) | undefined, rParam: string): void;
export declare function fnDeclBasic4(p: [T] | undefined, rParam: string): void;
export declare function fnDeclBasic5(p: {
    a: T;
} | undefined, rParam: string): void;
export declare function fnDeclBasic6(p: `_${string}` | undefined, rParam: string): void;
export declare function fnDeclBasic7(p: ({
    a?: string;
} & number[]) | undefined, rParam: string): void;
export declare function fnDeclBasic8(p: ((number[] | string[]) | number) | undefined, rParam: string): void;
export declare function fnDeclHasUndefined(p: T | undefined, rParam: string): void;
export declare function fnDeclBad(p: T | undefined, rParam: string): void;
export declare const fnExprOk1: (array: number[] | undefined, rParam: string) => void;
export declare const fnExprOk2: (array: T | undefined, rParam: string) => void;
export declare const fnExprBad: (array: T | undefined, rParam: string) => void;
export declare const arrowOk1: (array: number[] | undefined, rParam: string) => void;
export declare const arrowOk2: (array: T | undefined, rParam: string) => void;
export declare const arrowBad: (array: T | undefined, rParam: string) => void;
export declare const inObjectLiteralFnExprOk1: {
    o: (array: number[] | undefined, rParam: string) => void;
};
export declare const inObjectLiteralFnExprOk2: {
    o: (array: T | undefined, rParam: string) => void;
};
export declare const inObjectLiteralFnExprBad: {
    o: (array: T | undefined, rParam: string) => void;
};
export declare const inObjectLiteralArrowOk1: {
    o: (array: number[] | undefined, rParam: string) => void;
};
export declare const inObjectLiteralArrowOk2: {
    o: (array: T | undefined, rParam: string) => void;
};
export declare const inObjectLiteralArrowBad: {
    o: (array: T | undefined, rParam: string) => void;
};
export declare const inObjectLiteralMethodOk1: {
    o(array?: number[], rParam: string): void;
};
export declare const inObjectLiteralMethodOk2: {
    o(array?: T | undefined, rParam: string): void;
};
export declare const inObjectLiteralMethodBad: {
    o(array?: T, rParam: string): void;
};
export declare class InClassFnExprOk1 {
    o: (array: number[] | undefined, rParam: string) => void;
}
export declare class InClassFnExprOk2 {
    o: (array: T | undefined, rParam: string) => void;
}
export declare class InClassFnExprBad {
    o: (array: T | undefined, rParam: string) => void;
}
export declare class InClassArrowOk1 {
    o: (array: number[] | undefined, rParam: string) => void;
}
export declare class InClassArrowOk2 {
    o: (array: T | undefined, rParam: string) => void;
}
export declare class InClassArrowBad {
    o: (array: T | undefined, rParam: string) => void;
}
export declare class InClassMethodOk1 {
    o(array: number[] | undefined, rParam: string): void;
}
export declare class InClassMethodOk2 {
    o(array: T | undefined, rParam: string): void;
}
export declare class InClassMethodBad {
    o(array: T | undefined, rParam: string): void;
}
declare class Bar {
}
export declare class ClsWithRequiredInitializedParameter {
    private arr;
    private bool;
    constructor(arr: Bar | undefined, bool: boolean);
}
export {};
//// [Diagnostics reported] ////
fnDecl.ts(14,36): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(15,36): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
fnDecl.ts(16,36): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(18,26): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(19,26): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
fnDecl.ts(20,26): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(22,56): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(23,56): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
fnDecl.ts(24,56): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(26,46): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(27,46): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
fnDecl.ts(28,46): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(35,47): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(36,47): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
fnDecl.ts(37,47): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(39,37): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
fnDecl.ts(40,37): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
fnDecl.ts(41,37): error TS9025: Declaration emit for this parameter requires implicitly adding undefined to its type. This is not supported with --isolatedDeclarations.
