Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go 515d036f927aba8b468011098e2721335f0e2d00.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationBasicSyntax(declarationMap=true).d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [class.d.ts.map] ////
{"version":3,"file":"class.d.ts","sourceRoot":"","sources":["class.ts"],"names":[],"mappings":"AACA,qBAAa,GAAG;;IACZ,CAAC,EAAE,MAAM,CAAC;IACV,CAAC,CAAC,EAAE,MAAM,CAAC;IACH,CAAC,EAAE,MAAM,CAAC;IAEX,CAAC,EAAE,MAAM,CAAC;IACjB,SAAS,CAAC,CAAC,EAAE,MAAM,CAAC;IACpB,OAAO,CAAC,CAAC,CAAS;IAClB,CAAC,GAAG,CAAC,EAAE,MAAM,CAAC;CAEjB;AAED,8BAAsB,GAAG;IACrB,QAAQ,CAAC,CAAC,EAAE,MAAM,CAAC;IACnB,QAAQ,CAAC,MAAM,IAAI,IAAI,CAAC;CAC3B"}
//// [namespace.d.ts.map] ////
{"version":3,"file":"namespace.d.ts","sourceRoot":"","sources":["namespace.ts"],"names":[],"mappings":"AAAA,yBAAiB,EAAE,CAAC,CAAC;IACjB,UAAU,QAAQ,CAAC,CAAC;QAChB,MAAa,GAAG;SAAG;KACtB;IACD,MAAM,WAAW,MAAM,CAAC,CAAC;QACrB,MAAM,QAAQ,KAAK,GAAG,QAAQ,CAAC;KAClC;;CACJ"}
