Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go 515d036f927aba8b468011098e2721335f0e2d00.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationComputedPropertyNames.d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [declarationComputedPropertyNames.d.ts] ////
export declare namespace presentNs {
    const a: unique symbol;
}
declare const aliasing: SymbolConstructor;
export type A = {
    [missing]: number;
    [ns.missing]: number;
    [presentNs.a]: number;
    [Symbol.iterator]: number;
    [globalThis.Symbol.toStringTag]: number;
    [aliasing.isConcatSpreadable]: number;
    [1]: number;
    ["2"]: number;
};
export interface B {
    [missing]: number;
    [ns.missing]: number;
    [presentNs.a]: number;
    [Symbol.iterator]: number;
    [globalThis.Symbol.toStringTag]: number;
    [aliasing.isConcatSpreadable]: number;
    [1]: number;
    ["2"]: number;
}
export declare class C {
    [x: number]: number;
    [Symbol.iterator]: number;
    [globalThis.Symbol.toStringTag]: number;
    [1]: number;
    ["2"]: number;
}
export declare const D: {
    [x: string]: number;
    [x: number]: number;
    [presentNs.a]: number;
    [SymbolConstructor.toStringTag]: number;
    1: number;
    "2": number;
};
export {};
//// [Diagnostics reported] ////
declarationComputedPropertyNames.ts(2,18): error TS9010: Variable must have an explicit type annotation with --isolatedDeclarations.
declarationComputedPropertyNames.ts(5,7): error TS9010: Variable must have an explicit type annotation with --isolatedDeclarations.
declarationComputedPropertyNames.ts(13,5): error TS9014: Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.
declarationComputedPropertyNames.ts(17,5): error TS9014: Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.
declarationComputedPropertyNames.ts(18,5): error TS9014: Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.
declarationComputedPropertyNames.ts(27,5): error TS9014: Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.
declarationComputedPropertyNames.ts(31,5): error TS9014: Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.
declarationComputedPropertyNames.ts(32,5): error TS9014: Computed properties must be number or string literals, variables or dotted expressions with --isolatedDeclarations.
declarationComputedPropertyNames.ts(36,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(37,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(38,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(41,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(42,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(45,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(46,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(50,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(51,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(52,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(53,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(54,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(55,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(56,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(59,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
declarationComputedPropertyNames.ts(60,5): error TS9038: Computed property names on class or object literals cannot be inferred with --isolatedDeclarations.
