Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go c78d39e7075b4fc641b12b1f35d905c54cdc13ef.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationRestParameters.d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [v1.d.ts] ////
export declare const v1: (...a: [n: "n", a: "a"]) => {
    /** r rest param */
    a: [n: "n", a: "a"];
};
//// [Diagnostics reported] ////
v2.ts(2,14): error TS2527: The inferred type of 'v2' references an inaccessible 'unique symbol' type. A type annotation is necessary.
v2.ts(2,45): error TS9039: Type containing private name '{
v2.ts(6,8): error TS9039: Type containing private name 'typeof n' can't be used with --isolatedDeclarations.
//// [v2.d.ts] ////
<<< pinned TS-Go intentionally emits no output for this section >>>
