Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go c78d39e7075b4fc641b12b1f35d905c54cdc13ef.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationSingleFileHasErrors.d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [declarationSingleFileHasErrors.d.ts] ////
<<< pinned TS-Go intentionally emits no output for this section >>>
