Generated by tools/tsgo-suite/capture-tsgo-accepted.mjs from pinned TS-Go c78d39e7075b4fc641b12b1f35d905c54cdc13ef.
Do not hand-edit. Sections below replace the same-named sections of the Strada reference
baseline 'declarationCrossFileInferences.d.ts' because pinned TS-Go demonstrably diverges from Strada there.
//// [Diagnostics reported] ////
consumes.ts(3,12): error TS9013: Expression type can't be inferred with --isolatedDeclarations.
exposes.ts(2,14): error TS9010: Variable must have an explicit type annotation with --isolatedDeclarations.
//// [consumes.d.ts] ////
<<< pinned TS-Go intentionally emits no output for this section >>>
//// [exposes.d.ts] ////
<<< pinned TS-Go intentionally emits no output for this section >>>
