/**
 * Strict TS-Go parity gap map for `api`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const apiStrictParityUpstreamModule = "api";
export const apiStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"callbackfs.go","line":1,"text":"package api"},
  {"file":"callbackfs.go","line":3,"text":"import ("},
  {"file":"callbackfs.go","line":4,"text":"\t\"context\""},
  {"file":"callbackfs.go","line":5,"text":"\t\"fmt\""},
  {"file":"callbackfs.go","line":6,"text":"\t\"time\""},
  {"file":"callbackfs.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/json\""},
  {"file":"callbackfs.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"file":"callbackfs.go","line":10,"text":")"},
  {"file":"callbackfs.go","line":19,"text":"type callbackFS struct {"},
  {"file":"callbackfs.go","line":20,"text":"\tbase             vfs.FS"},
  {"file":"callbackfs.go","line":21,"text":"\tenabledCallbacks map[string]bool"},
  {"file":"callbackfs.go","line":24,"text":"\tconn Conn"},
  {"file":"callbackfs.go","line":25,"text":"\tctx  context.Context"},
  {"file":"callbackfs.go","line":26,"text":"}"},
  {"file":"callbackfs.go","line":29,"text":"const ("},
  {"file":"callbackfs.go","line":30,"text":"\tcallbackReadFile             = \"readFile\""},
  {"file":"callbackfs.go","line":31,"text":"\tcallbackFileExists           = \"fileExists\""},
  {"file":"callbackfs.go","line":32,"text":"\tcallbackDirectoryExists      = \"directoryExists\""},
  {"file":"callbackfs.go","line":33,"text":"\tcallbackGetAccessibleEntries = \"getAccessibleEntries\""},
  {"file":"callbackfs.go","line":34,"text":"\tcallbackRealpath             = \"realpath\""},
  {"file":"callbackfs.go","line":35,"text":")"},
  {"file":"callbackfs.go","line":37,"text":"func isCallbackName(name string) bool {"},
  {"file":"callbackfs.go","line":38,"text":"\tswitch name {"},
  {"file":"callbackfs.go","line":39,"text":"\tcase callbackReadFile,"},
  {"file":"callbackfs.go","line":40,"text":"\t\tcallbackFileExists,"},
  {"file":"callbackfs.go","line":41,"text":"\t\tcallbackDirectoryExists,"},
  {"file":"callbackfs.go","line":42,"text":"\t\tcallbackGetAccessibleEntries,"},
  {"file":"callbackfs.go","line":43,"text":"\t\tcallbackRealpath:"},
  {"file":"callbackfs.go","line":44,"text":"\t\treturn true"},
  {"file":"callbackfs.go","line":45,"text":"\tdefault:"},
  {"file":"callbackfs.go","line":46,"text":"\t\treturn false"},
  {"file":"callbackfs.go","line":47,"text":"\t}"},
  {"file":"callbackfs.go","line":48,"text":"}"},
  {"file":"callbackfs.go","line":53,"text":"func newCallbackFS(base vfs.FS, callbacks []string) *callbackFS {"},
  {"file":"callbackfs.go","line":54,"text":"\tenabled := make(map[string]bool, len(callbacks))"},
  {"file":"callbackfs.go","line":55,"text":"\tfor _, cb := range callbacks {"},
  {"file":"callbackfs.go","line":56,"text":"\t\tif !isCallbackName(cb) {"},
  {"file":"callbackfs.go","line":57,"text":"\t\t\tpanic(\"unknown callback name: \" + cb)"},
  {"file":"callbackfs.go","line":58,"text":"\t\t}"},
  {"file":"callbackfs.go","line":59,"text":"\t\tenabled[cb] = true"},
  {"file":"callbackfs.go","line":60,"text":"\t}"},
  {"file":"callbackfs.go","line":61,"text":"\treturn &callbackFS{"},
  {"file":"callbackfs.go","line":62,"text":"\t\tbase:             base,"},
  {"file":"callbackfs.go","line":63,"text":"\t\tenabledCallbacks: enabled,"},
  {"file":"callbackfs.go","line":64,"text":"\t}"},
  {"file":"callbackfs.go","line":65,"text":"}"},
  {"file":"callbackfs.go","line":70,"text":"func (fs *callbackFS) SetConnection(ctx context.Context, conn Conn) {"},
  {"file":"callbackfs.go","line":71,"text":"\tfs.ctx = ctx"},
  {"file":"callbackfs.go","line":72,"text":"\tfs.conn = conn"},
  {"file":"callbackfs.go","line":73,"text":"}"},
  {"file":"callbackfs.go","line":76,"text":"func (fs *callbackFS) isEnabled(name string) bool {"},
  {"file":"callbackfs.go","line":77,"text":"\treturn fs.enabledCallbacks[name]"},
  {"file":"callbackfs.go","line":78,"text":"}"},
  {"file":"callbackfs.go","line":81,"text":"func (fs *callbackFS) call(name string, arg any) ([]byte, error) {"},
  {"file":"callbackfs.go","line":82,"text":"\tif fs.conn == nil {"},
  {"file":"callbackfs.go","line":83,"text":"\t\treturn nil, fmt.Errorf(\"CallbackFS: %s called before connection set\", name)"},
  {"file":"callbackfs.go","line":84,"text":"\t}"},
  {"file":"callbackfs.go","line":86,"text":"\tresult, err := fs.conn.Call(fs.ctx, name, arg)"},
  {"file":"callbackfs.go","line":87,"text":"\tif err != nil {"},
  {"file":"callbackfs.go","line":88,"text":"\t\treturn nil, err"},
  {"file":"callbackfs.go","line":89,"text":"\t}"},
  {"file":"callbackfs.go","line":90,"text":"\treturn result, nil"},
  {"file":"callbackfs.go","line":91,"text":"}"},
  {"file":"callbackfs.go","line":94,"text":"func (fs *callbackFS) UseCaseSensitiveFileNames() bool {"},
  {"file":"callbackfs.go","line":95,"text":"\treturn fs.base.UseCaseSensitiveFileNames()"},
  {"file":"callbackfs.go","line":96,"text":"}"},
  {"file":"callbackfs.go","line":104,"text":"func (fs *callbackFS) ReadFile(path string) (contents string, ok bool) {"},
  {"file":"callbackfs.go","line":105,"text":"\tif fs.isEnabled(callbackReadFile) {"},
  {"file":"callbackfs.go","line":106,"text":"\t\tresult, err := fs.call(callbackReadFile, path)"},
  {"file":"callbackfs.go","line":107,"text":"\t\tif err != nil {"},
  {"file":"callbackfs.go","line":108,"text":"\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":109,"text":"\t\t}"},
  {"file":"callbackfs.go","line":110,"text":"\t\tif len(result) > 0 && string(result) != \"null\" {"},
  {"file":"callbackfs.go","line":111,"text":"\t\t\tvar wrapper struct {"},
  {"file":"callbackfs.go","line":112,"text":"\t\t\t\tContent *string `json:\"content\"`"},
  {"file":"callbackfs.go","line":113,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":114,"text":"\t\t\tif err := json.Unmarshal(result, &wrapper); err != nil {"},
  {"file":"callbackfs.go","line":115,"text":"\t\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":116,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":117,"text":"\t\t\tif wrapper.Content == nil {"},
  {"file":"callbackfs.go","line":118,"text":"\t\t\t\treturn \"\", false"},
  {"file":"callbackfs.go","line":119,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":120,"text":"\t\t\treturn *wrapper.Content, true"},
  {"file":"callbackfs.go","line":121,"text":"\t\t}"},
  {"file":"callbackfs.go","line":122,"text":"\t}"},
  {"file":"callbackfs.go","line":123,"text":"\treturn fs.base.ReadFile(path)"},
  {"file":"callbackfs.go","line":124,"text":"}"},
  {"file":"callbackfs.go","line":127,"text":"func (fs *callbackFS) FileExists(path string) bool {"},
  {"file":"callbackfs.go","line":128,"text":"\tif fs.isEnabled(callbackFileExists) {"},
  {"file":"callbackfs.go","line":129,"text":"\t\tresult, err := fs.call(callbackFileExists, path)"},
  {"file":"callbackfs.go","line":130,"text":"\t\tif err != nil {"},
  {"file":"callbackfs.go","line":131,"text":"\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":132,"text":"\t\t}"},
  {"file":"callbackfs.go","line":133,"text":"\t\tif len(result) > 0 && string(result) != \"null\" {"},
  {"file":"callbackfs.go","line":134,"text":"\t\t\treturn string(result) == \"true\""},
  {"file":"callbackfs.go","line":135,"text":"\t\t}"},
  {"file":"callbackfs.go","line":136,"text":"\t}"},
  {"file":"callbackfs.go","line":137,"text":"\treturn fs.base.FileExists(path)"},
  {"file":"callbackfs.go","line":138,"text":"}"},
  {"file":"callbackfs.go","line":141,"text":"func (fs *callbackFS) DirectoryExists(path string) bool {"},
  {"file":"callbackfs.go","line":142,"text":"\tif fs.isEnabled(callbackDirectoryExists) {"},
  {"file":"callbackfs.go","line":143,"text":"\t\tresult, err := fs.call(callbackDirectoryExists, path)"},
  {"file":"callbackfs.go","line":144,"text":"\t\tif err != nil {"},
  {"file":"callbackfs.go","line":145,"text":"\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":146,"text":"\t\t}"},
  {"file":"callbackfs.go","line":147,"text":"\t\tif len(result) > 0 && string(result) != \"null\" {"},
  {"file":"callbackfs.go","line":148,"text":"\t\t\treturn string(result) == \"true\""},
  {"file":"callbackfs.go","line":149,"text":"\t\t}"},
  {"file":"callbackfs.go","line":150,"text":"\t}"},
  {"file":"callbackfs.go","line":151,"text":"\treturn fs.base.DirectoryExists(path)"},
  {"file":"callbackfs.go","line":152,"text":"}"},
  {"file":"callbackfs.go","line":155,"text":"func (fs *callbackFS) GetAccessibleEntries(path string) vfs.Entries {"},
  {"file":"callbackfs.go","line":156,"text":"\tif fs.isEnabled(callbackGetAccessibleEntries) {"},
  {"file":"callbackfs.go","line":157,"text":"\t\tresult, err := fs.call(callbackGetAccessibleEntries, path)"},
  {"file":"callbackfs.go","line":158,"text":"\t\tif err != nil {"},
  {"file":"callbackfs.go","line":159,"text":"\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":160,"text":"\t\t}"},
  {"file":"callbackfs.go","line":161,"text":"\t\tif len(result) > 0 {"},
  {"file":"callbackfs.go","line":162,"text":"\t\t\tvar rawEntries *struct {"},
  {"file":"callbackfs.go","line":163,"text":"\t\t\t\tFiles       []string `json:\"files\"`"},
  {"file":"callbackfs.go","line":164,"text":"\t\t\t\tDirectories []string `json:\"directories\"`"},
  {"file":"callbackfs.go","line":165,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":166,"text":"\t\t\tif err := json.Unmarshal(result, &rawEntries); err != nil {"},
  {"file":"callbackfs.go","line":167,"text":"\t\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":168,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":169,"text":"\t\t\tif rawEntries != nil {"},
  {"file":"callbackfs.go","line":170,"text":"\t\t\t\treturn vfs.Entries{"},
  {"file":"callbackfs.go","line":171,"text":"\t\t\t\t\tFiles:       rawEntries.Files,"},
  {"file":"callbackfs.go","line":172,"text":"\t\t\t\t\tDirectories: rawEntries.Directories,"},
  {"file":"callbackfs.go","line":173,"text":"\t\t\t\t}"},
  {"file":"callbackfs.go","line":174,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":175,"text":"\t\t}"},
  {"file":"callbackfs.go","line":176,"text":"\t}"},
  {"file":"callbackfs.go","line":177,"text":"\treturn fs.base.GetAccessibleEntries(path)"},
  {"file":"callbackfs.go","line":178,"text":"}"},
  {"file":"callbackfs.go","line":181,"text":"func (fs *callbackFS) Realpath(path string) string {"},
  {"file":"callbackfs.go","line":182,"text":"\tif fs.isEnabled(callbackRealpath) {"},
  {"file":"callbackfs.go","line":183,"text":"\t\tresult, err := fs.call(callbackRealpath, path)"},
  {"file":"callbackfs.go","line":184,"text":"\t\tif err != nil {"},
  {"file":"callbackfs.go","line":185,"text":"\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":186,"text":"\t\t}"},
  {"file":"callbackfs.go","line":187,"text":"\t\tif len(result) > 0 && string(result) != \"null\" {"},
  {"file":"callbackfs.go","line":188,"text":"\t\t\tvar realpath string"},
  {"file":"callbackfs.go","line":189,"text":"\t\t\tif err := json.Unmarshal(result, &realpath); err != nil {"},
  {"file":"callbackfs.go","line":190,"text":"\t\t\t\tpanic(err)"},
  {"file":"callbackfs.go","line":191,"text":"\t\t\t}"},
  {"file":"callbackfs.go","line":192,"text":"\t\t\treturn realpath"},
  {"file":"callbackfs.go","line":193,"text":"\t\t}"},
  {"file":"callbackfs.go","line":194,"text":"\t}"},
  {"file":"callbackfs.go","line":195,"text":"\treturn fs.base.Realpath(path)"},
  {"file":"callbackfs.go","line":196,"text":"}"},
  {"file":"callbackfs.go","line":199,"text":"func (fs *callbackFS) WriteFile(path string, data string) error {"},
  {"file":"callbackfs.go","line":200,"text":"\treturn fs.base.WriteFile(path, data)"},
  {"file":"callbackfs.go","line":201,"text":"}"},
  {"file":"callbackfs.go","line":204,"text":"func (fs *callbackFS) AppendFile(path string, data string) error {"},
  {"file":"callbackfs.go","line":205,"text":"\treturn fs.base.AppendFile(path, data)"},
  {"file":"callbackfs.go","line":206,"text":"}"},
  {"file":"callbackfs.go","line":209,"text":"func (fs *callbackFS) Remove(path string) error {"},
  {"file":"callbackfs.go","line":210,"text":"\treturn fs.base.Remove(path)"},
  {"file":"callbackfs.go","line":211,"text":"}"},
  {"file":"callbackfs.go","line":214,"text":"func (fs *callbackFS) Chtimes(path string, aTime time.Time, mTime time.Time) error {"},
  {"file":"callbackfs.go","line":215,"text":"\treturn fs.base.Chtimes(path, aTime, mTime)"},
  {"file":"callbackfs.go","line":216,"text":"}"},
  {"file":"callbackfs.go","line":219,"text":"func (fs *callbackFS) Stat(path string) vfs.FileInfo {"},
  {"file":"callbackfs.go","line":220,"text":"\treturn fs.base.Stat(path)"},
  {"file":"callbackfs.go","line":221,"text":"}"},
  {"file":"callbackfs.go","line":224,"text":"func (fs *callbackFS) WalkDir(root string, walkFn vfs.WalkDirFunc) error {"},
  {"file":"callbackfs.go","line":225,"text":"\treturn fs.base.WalkDir(root, walkFn)"},
  {"file":"callbackfs.go","line":226,"text":"}"},
  {"file":"conn.go","line":1,"text":"package api"},
  {"file":"conn.go","line":3,"text":"import ("},
  {"file":"conn.go","line":4,"text":"\t\"context\""},
  {"file":"conn.go","line":5,"text":"\t\"errors\""},
  {"file":"conn.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/json\""},
  {"file":"conn.go","line":8,"text":")"},
  {"file":"conn.go","line":10,"text":"var ("},
  {"file":"conn.go","line":11,"text":"\tErrConnClosed     = errors.New(\"api: connection closed\")"},
  {"file":"conn.go","line":12,"text":"\tErrRequestTimeout = errors.New(\"api: request timeout\")"},
  {"file":"conn.go","line":13,"text":")"},
  {"file":"conn.go","line":16,"text":"type Handler interface {"},
  {"file":"conn.go","line":18,"text":"\tHandleRequest(ctx context.Context, method string, params json.Value) (any, error)"},
  {"file":"conn.go","line":20,"text":"\tHandleNotification(ctx context.Context, method string, params json.Value) error"},
  {"file":"conn.go","line":21,"text":"}"},
  {"file":"conn.go","line":24,"text":"type Conn interface {"},
  {"file":"conn.go","line":27,"text":"\tRun(ctx context.Context) error"},
  {"file":"conn.go","line":30,"text":"\tCall(ctx context.Context, method string, params any) (json.Value, error)"},
  {"file":"conn.go","line":33,"text":"\tNotify(ctx context.Context, method string, params any) error"},
  {"file":"conn.go","line":34,"text":"}"},
  {"file":"conn.go","line":37,"text":"func UnmarshalParams[T any](params json.Value) (*T, error) {"},
  {"file":"conn.go","line":38,"text":"\tif len(params) == 0 {"},
  {"file":"conn.go","line":39,"text":"\t\treturn nil, nil"},
  {"file":"conn.go","line":40,"text":"\t}"},
  {"file":"conn.go","line":41,"text":"\tvar v T"},
  {"file":"conn.go","line":42,"text":"\tif err := json.Unmarshal(params, &v); err != nil {"},
  {"file":"conn.go","line":43,"text":"\t\treturn nil, err"},
  {"file":"conn.go","line":44,"text":"\t}"},
  {"file":"conn.go","line":45,"text":"\treturn &v, nil"},
  {"file":"conn.go","line":46,"text":"}"},
  {"file":"conn_async.go","line":1,"text":"package api"},
  {"file":"conn_async.go","line":3,"text":"import ("},
  {"file":"conn_async.go","line":4,"text":"\t\"context\""},
  {"file":"conn_async.go","line":5,"text":"\t\"errors\""},
  {"file":"conn_async.go","line":6,"text":"\t\"fmt\""},
  {"file":"conn_async.go","line":7,"text":"\t\"io\""},
  {"file":"conn_async.go","line":8,"text":"\t\"runtime/debug\""},
  {"file":"conn_async.go","line":9,"text":"\t\"sync\""},
  {"file":"conn_async.go","line":10,"text":"\t\"sync/atomic\""},
  {"file":"conn_async.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/json\""},
  {"file":"conn_async.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/jsonrpc\""},
  {"file":"conn_async.go","line":14,"text":")"},
  {"file":"conn_async.go","line":19,"text":"type AsyncConn struct {"},
  {"file":"conn_async.go","line":20,"text":"\trwc      io.ReadWriteCloser"},
  {"file":"conn_async.go","line":21,"text":"\tprotocol Protocol"},
  {"file":"conn_async.go","line":22,"text":"\thandler  Handler"},
  {"file":"conn_async.go","line":25,"text":"\tseq       atomic.Int64"},
  {"file":"conn_async.go","line":26,"text":"\tpending   map[jsonrpc.ID]chan *Message"},
  {"file":"conn_async.go","line":27,"text":"\tpendingMu sync.Mutex"},
  {"file":"conn_async.go","line":28,"text":"\twriteMu   sync.Mutex"},
  {"file":"conn_async.go","line":29,"text":"}"},
  {"file":"conn_async.go","line":33,"text":"func NewAsyncConn(rwc io.ReadWriteCloser, handler Handler) *AsyncConn {"},
  {"file":"conn_async.go","line":34,"text":"\treturn NewAsyncConnWithProtocol(rwc, NewJSONRPCProtocol(rwc), handler)"},
  {"file":"conn_async.go","line":35,"text":"}"},
  {"file":"conn_async.go","line":38,"text":"func NewAsyncConnWithProtocol(rwc io.ReadWriteCloser, protocol Protocol, handler Handler) *AsyncConn {"},
  {"file":"conn_async.go","line":39,"text":"\treturn &AsyncConn{"},
  {"file":"conn_async.go","line":40,"text":"\t\trwc:      rwc,"},
  {"file":"conn_async.go","line":41,"text":"\t\tprotocol: protocol,"},
  {"file":"conn_async.go","line":42,"text":"\t\thandler:  handler,"},
  {"file":"conn_async.go","line":43,"text":"\t\tpending:  make(map[jsonrpc.ID]chan *Message),"},
  {"file":"conn_async.go","line":44,"text":"\t}"},
  {"file":"conn_async.go","line":45,"text":"}"},
  {"file":"conn_async.go","line":49,"text":"func (c *AsyncConn) Run(ctx context.Context) error {"},
  {"file":"conn_async.go","line":50,"text":"\tfor {"},
  {"file":"conn_async.go","line":51,"text":"\t\tif ctx.Err() != nil {"},
  {"file":"conn_async.go","line":52,"text":"\t\t\treturn ctx.Err()"},
  {"file":"conn_async.go","line":53,"text":"\t\t}"},
  {"file":"conn_async.go","line":55,"text":"\t\tmsg, err := c.protocol.ReadMessage()"},
  {"file":"conn_async.go","line":56,"text":"\t\tif err != nil {"},
  {"file":"conn_async.go","line":57,"text":"\t\t\tif errors.Is(err, io.EOF) {"},
  {"file":"conn_async.go","line":58,"text":"\t\t\t\treturn nil"},
  {"file":"conn_async.go","line":59,"text":"\t\t\t}"},
  {"file":"conn_async.go","line":60,"text":"\t\t\treturn err"},
  {"file":"conn_async.go","line":61,"text":"\t\t}"},
  {"file":"conn_async.go","line":63,"text":"\t\tif msg.IsResponse() {"},
  {"file":"conn_async.go","line":64,"text":"\t\t\tc.handleResponse(msg)"},
  {"file":"conn_async.go","line":65,"text":"\t\t} else if msg.IsRequest() {"},
  {"file":"conn_async.go","line":66,"text":"\t\t\tgo c.handleRequest(ctx, msg)"},
  {"file":"conn_async.go","line":67,"text":"\t\t} else if msg.IsNotification() {"},
  {"file":"conn_async.go","line":68,"text":"\t\t\tgo c.handleNotification(ctx, msg)"},
  {"file":"conn_async.go","line":69,"text":"\t\t}"},
  {"file":"conn_async.go","line":70,"text":"\t}"},
  {"file":"conn_async.go","line":71,"text":"}"},
  {"file":"conn_async.go","line":74,"text":"func (c *AsyncConn) handleResponse(msg *Message) {"},
  {"file":"conn_async.go","line":75,"text":"\tc.pendingMu.Lock()"},
  {"file":"conn_async.go","line":76,"text":"\tch, ok := c.pending[*msg.ID]"},
  {"file":"conn_async.go","line":77,"text":"\tif ok {"},
  {"file":"conn_async.go","line":78,"text":"\t\tdelete(c.pending, *msg.ID)"},
  {"file":"conn_async.go","line":79,"text":"\t}"},
  {"file":"conn_async.go","line":80,"text":"\tc.pendingMu.Unlock()"},
  {"file":"conn_async.go","line":82,"text":"\tif ok {"},
  {"file":"conn_async.go","line":83,"text":"\t\tch <- msg"},
  {"file":"conn_async.go","line":84,"text":"\t\tclose(ch)"},
  {"file":"conn_async.go","line":85,"text":"\t}"},
  {"file":"conn_async.go","line":86,"text":"}"},
  {"file":"conn_async.go","line":89,"text":"func (c *AsyncConn) handleRequest(ctx context.Context, msg *Message) {"},
  {"file":"conn_async.go","line":90,"text":"\tvar result any"},
  {"file":"conn_async.go","line":91,"text":"\tvar err error"},
  {"file":"conn_async.go","line":94,"text":"\tdefer func() {"},
  {"file":"conn_async.go","line":95,"text":"\t\tif r := recover(); r != nil {"},
  {"file":"conn_async.go","line":96,"text":"\t\t\tstack := string(debug.Stack())"},
  {"file":"conn_async.go","line":97,"text":"\t\t\terr = fmt.Errorf(\"panic: %v\\n%s\", r, stack)"},
  {"file":"conn_async.go","line":99,"text":"\t\t\tc.writeMu.Lock()"},
  {"file":"conn_async.go","line":100,"text":"\t\t\twriteErr := c.protocol.WriteError(msg.ID, &jsonrpc.ResponseError{"},
  {"file":"conn_async.go","line":101,"text":"\t\t\t\tCode:    jsonrpc.CodeInternalError,"},
  {"file":"conn_async.go","line":102,"text":"\t\t\t\tMessage: err.Error(),"},
  {"file":"conn_async.go","line":103,"text":"\t\t\t})"},
  {"file":"conn_async.go","line":104,"text":"\t\t\tc.writeMu.Unlock()"},
  {"file":"conn_async.go","line":106,"text":"\t\t\tif writeErr != nil {"},
  {"file":"conn_async.go","line":107,"text":"\t\t\t\tpanic(fmt.Sprintf(\"api: failed to write panic error response: %v (original panic: %v)\", writeErr, r))"},
  {"file":"conn_async.go","line":108,"text":"\t\t\t}"},
  {"file":"conn_async.go","line":109,"text":"\t\t}"},
  {"file":"conn_async.go","line":110,"text":"\t}()"},
  {"file":"conn_async.go","line":112,"text":"\tresult, err = c.handler.HandleRequest(ctx, msg.Method, msg.Params)"},
  {"file":"conn_async.go","line":114,"text":"\tc.writeMu.Lock()"},
  {"file":"conn_async.go","line":115,"text":"\tdefer c.writeMu.Unlock()"},
  {"file":"conn_async.go","line":117,"text":"\tvar writeErr error"},
  {"file":"conn_async.go","line":118,"text":"\tif err != nil {"},
  {"file":"conn_async.go","line":119,"text":"\t\twriteErr = c.protocol.WriteError(msg.ID, &jsonrpc.ResponseError{"},
  {"file":"conn_async.go","line":120,"text":"\t\t\tCode:    jsonrpc.CodeInternalError,"},
  {"file":"conn_async.go","line":121,"text":"\t\t\tMessage: err.Error(),"},
  {"file":"conn_async.go","line":122,"text":"\t\t})"},
  {"file":"conn_async.go","line":123,"text":"\t} else {"},
  {"file":"conn_async.go","line":124,"text":"\t\twriteErr = c.protocol.WriteResponse(msg.ID, result)"},
  {"file":"conn_async.go","line":125,"text":"\t}"},
  {"file":"conn_async.go","line":127,"text":"\tif writeErr != nil {"},
  {"file":"conn_async.go","line":128,"text":"\t\tpanic(fmt.Sprintf(\"api: failed to write response: %v\", writeErr))"},
  {"file":"conn_async.go","line":129,"text":"\t}"},
  {"file":"conn_async.go","line":130,"text":"}"},
  {"file":"conn_async.go","line":133,"text":"func (c *AsyncConn) handleNotification(ctx context.Context, msg *Message) {"},
  {"file":"conn_async.go","line":134,"text":"\t_ = c.handler.HandleNotification(ctx, msg.Method, msg.Params)"},
  {"file":"conn_async.go","line":135,"text":"}"},
  {"file":"conn_async.go","line":138,"text":"func (c *AsyncConn) Call(ctx context.Context, method string, params any) (json.Value, error) {"},
  {"file":"conn_async.go","line":140,"text":"\tid := jsonrpc.NewIDString(fmt.Sprintf(\"api%d\", c.seq.Add(1)))"},
  {"file":"conn_async.go","line":143,"text":"\tresponseChan := make(chan *Message, 1)"},
  {"file":"conn_async.go","line":144,"text":"\tc.pendingMu.Lock()"},
  {"file":"conn_async.go","line":145,"text":"\tc.pending[*id] = responseChan"},
  {"file":"conn_async.go","line":146,"text":"\tc.pendingMu.Unlock()"},
  {"file":"conn_async.go","line":148,"text":"\tdefer func() {"},
  {"file":"conn_async.go","line":149,"text":"\t\tc.pendingMu.Lock()"},
  {"file":"conn_async.go","line":150,"text":"\t\tdefer c.pendingMu.Unlock()"},
  {"file":"conn_async.go","line":151,"text":"\t\tif ch, ok := c.pending[*id]; ok {"},
  {"file":"conn_async.go","line":152,"text":"\t\t\tclose(ch)"},
  {"file":"conn_async.go","line":153,"text":"\t\t\tdelete(c.pending, *id)"},
  {"file":"conn_async.go","line":154,"text":"\t\t}"},
  {"file":"conn_async.go","line":155,"text":"\t}()"},
  {"file":"conn_async.go","line":158,"text":"\tc.writeMu.Lock()"},
  {"file":"conn_async.go","line":159,"text":"\terr := c.protocol.WriteRequest(id, method, params)"},
  {"file":"conn_async.go","line":160,"text":"\tc.writeMu.Unlock()"},
  {"file":"conn_async.go","line":162,"text":"\tif err != nil {"},
  {"file":"conn_async.go","line":163,"text":"\t\treturn nil, err"},
  {"file":"conn_async.go","line":164,"text":"\t}"},
];

export function apiStrictParityLineText(file: string, line: number): string | undefined {
  return apiStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function apiStrictParityFiles(): readonly string[] {
  return [...new Set(apiStrictParitySourceLines.map((entry) => entry.file))].sort();
}
