// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/golang.org/x/sync/errgroup.ts","contentHash":"e4dbd24b8241fe7c5462324c7b32625f04dad677979557504ab20c5a4dc58efc"}

export interface Group {
  readonly __goFacadeName: "golang.org/x/sync/errgroup.Group";
}

export function WithContext(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sync/errgroup.WithContext");
}
