/**
 * Strict TS-Go parity gap map for `binder`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const binderStrictParityUpstreamModule = "binder";
export const binderStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"binder.go","line":1,"text":"package binder"},
  {"file":"binder.go","line":3,"text":"import ("},
  {"file":"binder.go","line":4,"text":"\t\"slices\""},
  {"file":"binder.go","line":5,"text":"\t\"strconv\""},
  {"file":"binder.go","line":6,"text":"\t\"sync\""},
  {"file":"binder.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"binder.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"binder.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"binder.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/debug\""},
  {"file":"binder.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"binder.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"file":"binder.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"binder.go","line":15,"text":")"},
  {"file":"binder.go","line":17,"text":"type ContainerFlags int32"},
  {"file":"binder.go","line":19,"text":"const ("},
  {"file":"binder.go","line":22,"text":"\tContainerFlagsNone ContainerFlags = 0"},
  {"file":"binder.go","line":27,"text":"\tContainerFlagsIsContainer ContainerFlags = 1 << 0"},
  {"file":"binder.go","line":32,"text":"\tContainerFlagsIsBlockScopedContainer ContainerFlags = 1 << 1"},
  {"file":"binder.go","line":35,"text":"\tContainerFlagsIsControlFlowContainer                           ContainerFlags = 1 << 2"},
  {"file":"binder.go","line":36,"text":"\tContainerFlagsIsFunctionLike                                   ContainerFlags = 1 << 3"},
  {"file":"binder.go","line":37,"text":"\tContainerFlagsIsFunctionExpression                             ContainerFlags = 1 << 4"},
  {"file":"binder.go","line":38,"text":"\tContainerFlagsHasLocals                                        ContainerFlags = 1 << 5"},
  {"file":"binder.go","line":39,"text":"\tContainerFlagsIsInterface                                      ContainerFlags = 1 << 6"},
  {"file":"binder.go","line":40,"text":"\tContainerFlagsIsObjectLiteralOrClassExpressionMethodOrAccessor ContainerFlags = 1 << 7"},
  {"file":"binder.go","line":41,"text":"\tContainerFlagsIsThisContainer                                  ContainerFlags = 1 << 8"},
  {"file":"binder.go","line":42,"text":"\tContainerFlagsPropagatesThisKeyword                            ContainerFlags = 1 << 9"},
  {"file":"binder.go","line":43,"text":")"},
  {"file":"binder.go","line":45,"text":"type ExpandoAssignmentInfo struct {"},
  {"file":"binder.go","line":46,"text":"\tnode                *ast.Node"},
  {"file":"binder.go","line":47,"text":"\tcontainer           *ast.Node"},
  {"file":"binder.go","line":48,"text":"\tblockScopeContainer *ast.Node"},
  {"file":"binder.go","line":49,"text":"}"},
  {"file":"binder.go","line":51,"text":"type Binder struct {"},
  {"file":"binder.go","line":52,"text":"\tfile            *ast.SourceFile"},
  {"file":"binder.go","line":53,"text":"\tbindFunc        func(*ast.Node) bool"},
  {"file":"binder.go","line":54,"text":"\tunreachableFlow *ast.FlowNode"},
  {"file":"binder.go","line":56,"text":"\tcontainer               *ast.Node"},
  {"file":"binder.go","line":57,"text":"\tthisContainer           *ast.Node"},
  {"file":"binder.go","line":58,"text":"\tblockScopeContainer     *ast.Node"},
  {"file":"binder.go","line":59,"text":"\tlastContainer           *ast.Node"},
  {"file":"binder.go","line":60,"text":"\tcurrentFlow             *ast.FlowNode"},
  {"file":"binder.go","line":61,"text":"\tcurrentBreakTarget      *ast.FlowLabel"},
  {"file":"binder.go","line":62,"text":"\tcurrentContinueTarget   *ast.FlowLabel"},
  {"file":"binder.go","line":63,"text":"\tcurrentReturnTarget     *ast.FlowLabel"},
  {"file":"binder.go","line":64,"text":"\tcurrentTrueTarget       *ast.FlowLabel"},
  {"file":"binder.go","line":65,"text":"\tcurrentFalseTarget      *ast.FlowLabel"},
  {"file":"binder.go","line":66,"text":"\tcurrentExceptionTarget  *ast.FlowLabel"},
  {"file":"binder.go","line":67,"text":"\tpreSwitchCaseFlow       *ast.FlowNode"},
  {"file":"binder.go","line":68,"text":"\tactiveLabelList         *ActiveLabel"},
  {"file":"binder.go","line":69,"text":"\temitFlags               ast.NodeFlags"},
  {"file":"binder.go","line":70,"text":"\tseenThisKeyword         bool"},
  {"file":"binder.go","line":71,"text":"\thasExplicitReturn       bool"},
  {"file":"binder.go","line":72,"text":"\thasFlowEffects          bool"},
  {"file":"binder.go","line":73,"text":"\tinAssignmentPattern     bool"},
  {"file":"binder.go","line":74,"text":"\tseenParseError          bool"},
  {"file":"binder.go","line":75,"text":"\tsymbolCount             int"},
  {"file":"binder.go","line":76,"text":"\tclassifiableNames       collections.Set[string]"},
  {"file":"binder.go","line":77,"text":"\tnotConstEnumOnlyModules collections.Set[*ast.Symbol]"},
  {"file":"binder.go","line":78,"text":"\tsymbolArena             core.Arena[ast.Symbol]"},
  {"file":"binder.go","line":79,"text":"\tflowNodeArena           core.Arena[ast.FlowNode]"},
  {"file":"binder.go","line":80,"text":"\tflowListArena           core.Arena[ast.FlowList]"},
  {"file":"binder.go","line":81,"text":"\tsingleDeclarationsArena core.Arena[*ast.Node]"},
  {"file":"binder.go","line":82,"text":"\texpandoAssignments      []ExpandoAssignmentInfo"},
  {"file":"binder.go","line":83,"text":"\tnestedCJSExports        []*ast.Node"},
  {"file":"binder.go","line":84,"text":"}"},
  {"file":"binder.go","line":86,"text":"type ActiveLabel struct {"},
  {"file":"binder.go","line":87,"text":"\tnext           *ActiveLabel"},
  {"file":"binder.go","line":88,"text":"\tbreakTarget    *ast.FlowLabel"},
  {"file":"binder.go","line":89,"text":"\tcontinueTarget *ast.FlowLabel"},
  {"file":"binder.go","line":90,"text":"\tname           string"},
  {"file":"binder.go","line":91,"text":"\treferenced     bool"},
  {"file":"binder.go","line":92,"text":"}"},
  {"file":"binder.go","line":94,"text":"func (label *ActiveLabel) BreakTarget() *ast.FlowNode    { return label.breakTarget }"},
  {"file":"binder.go","line":95,"text":"func (label *ActiveLabel) ContinueTarget() *ast.FlowNode { return label.continueTarget }"},
  {"file":"binder.go","line":97,"text":"func BindSourceFile(file *ast.SourceFile) {"},
  {"file":"binder.go","line":100,"text":"\tif !file.IsBound() {"},
  {"file":"binder.go","line":101,"text":"\t\tbindSourceFile(file)"},
  {"file":"binder.go","line":102,"text":"\t}"},
  {"file":"binder.go","line":103,"text":"}"},
  {"file":"binder.go","line":105,"text":"var binderPool = sync.Pool{"},
  {"file":"binder.go","line":106,"text":"\tNew: func() any {"},
  {"file":"binder.go","line":107,"text":"\t\tb := &Binder{}"},
  {"file":"binder.go","line":108,"text":"\t\tb.bindFunc = b.bind // Allocate closure once"},
  {"file":"binder.go","line":109,"text":"\t\treturn b"},
  {"file":"binder.go","line":110,"text":"\t},"},
  {"file":"binder.go","line":111,"text":"}"},
  {"file":"binder.go","line":113,"text":"func getBinder() *Binder {"},
  {"file":"binder.go","line":114,"text":"\treturn binderPool.Get().(*Binder)"},
  {"file":"binder.go","line":115,"text":"}"},
  {"file":"binder.go","line":117,"text":"func putBinder(b *Binder) {"},
  {"file":"binder.go","line":118,"text":"\t*b = Binder{bindFunc: b.bindFunc}"},
  {"file":"binder.go","line":119,"text":"\tbinderPool.Put(b)"},
  {"file":"binder.go","line":120,"text":"}"},
  {"file":"binder.go","line":122,"text":"func bindSourceFile(file *ast.SourceFile) {"},
  {"file":"binder.go","line":123,"text":"\tfile.BindOnce(func() {"},
  {"file":"binder.go","line":124,"text":"\t\tb := getBinder()"},
  {"file":"binder.go","line":125,"text":"\t\tdefer putBinder(b)"},
  {"file":"binder.go","line":126,"text":"\t\tb.file = file"},
  {"file":"binder.go","line":127,"text":"\t\tb.unreachableFlow = b.newFlowNode(ast.FlowFlagsUnreachable)"},
  {"file":"binder.go","line":128,"text":"\t\tb.bind(file.AsNode())"},
  {"file":"binder.go","line":129,"text":"\t\tb.bindDeferredExpandoAssignments()"},
  {"file":"binder.go","line":130,"text":"\t\tfile.SymbolCount = b.symbolCount"},
  {"file":"binder.go","line":131,"text":"\t\tfile.ClassifiableNames = b.classifiableNames"},
  {"file":"binder.go","line":132,"text":"\t\tfile.NestedCJSExports = b.nestedCJSExports"},
  {"file":"binder.go","line":133,"text":"\t})"},
  {"file":"binder.go","line":134,"text":"}"},
  {"file":"binder.go","line":136,"text":"func (b *Binder) newSymbol(flags ast.SymbolFlags, name string) *ast.Symbol {"},
  {"file":"binder.go","line":137,"text":"\tb.symbolCount++"},
  {"file":"binder.go","line":138,"text":"\tresult := b.symbolArena.New()"},
  {"file":"binder.go","line":139,"text":"\tresult.Flags = flags"},
  {"file":"binder.go","line":140,"text":"\tresult.Name = name"},
  {"file":"binder.go","line":141,"text":"\treturn result"},
  {"file":"binder.go","line":142,"text":"}"},
  {"file":"binder.go","line":144,"text":"/**"},
  {"file":"binder.go","line":145,"text":" * Declares a Symbol for the node and adds it to symbols. Reports errors for conflicting identifier names."},
  {"file":"binder.go","line":146,"text":" * @param symbolTable - The symbol table which node will be added to."},
  {"file":"binder.go","line":147,"text":" * @param parent - node's parent declaration."},
  {"file":"binder.go","line":148,"text":" * @param node - The declaration to be added to the symbol table"},
  {"file":"binder.go","line":149,"text":" * @param includes - The SymbolFlags that node has in addition to its declaration type (eg: export, ambient, etc.)"},
  {"file":"binder.go","line":150,"text":" * @param excludes - The flags which node cannot be declared alongside in a symbol table. Used to report forbidden declarations."},
  {"file":"binder.go","line":151,"text":" */"},
  {"file":"binder.go","line":152,"text":"func (b *Binder) declareSymbol(symbolTable ast.SymbolTable, parent *ast.Symbol, node *ast.Node, includes ast.SymbolFlags, excludes ast.SymbolFlags) *ast.Symbol {"},
  {"file":"binder.go","line":153,"text":"\treturn b.declareSymbolEx(symbolTable, parent, node, includes, excludes, false /*isReplaceableByMethod*/, false /*isComputedName*/)"},
  {"file":"binder.go","line":154,"text":"}"},
  {"file":"binder.go","line":156,"text":"func (b *Binder) declareSymbolEx(symbolTable ast.SymbolTable, parent *ast.Symbol, node *ast.Node, includes ast.SymbolFlags, excludes ast.SymbolFlags, isReplaceableByMethod bool, isComputedName bool) *ast.Symbol {"},
  {"file":"binder.go","line":157,"text":"\tdebug.Assert(isComputedName || !ast.HasDynamicName(node))"},
  {"file":"binder.go","line":158,"text":"\tisDefaultExport := ast.HasSyntacticModifier(node, ast.ModifierFlagsDefault) || ast.IsExportSpecifier(node) && ast.ModuleExportNameIsDefault(node.AsExportSpecifier().Name())"},
  {"file":"binder.go","line":160,"text":"\tvar name string"},
  {"file":"binder.go","line":161,"text":"\tswitch {"},
  {"file":"binder.go","line":162,"text":"\tcase isComputedName:"},
  {"file":"binder.go","line":163,"text":"\t\tname = ast.InternalSymbolNameComputed"},
  {"file":"binder.go","line":164,"text":"\tcase isDefaultExport && parent != nil:"},
  {"file":"binder.go","line":165,"text":"\t\tname = ast.InternalSymbolNameDefault"},
  {"file":"binder.go","line":166,"text":"\tdefault:"},
  {"file":"binder.go","line":167,"text":"\t\tname = b.getDeclarationName(node)"},
  {"file":"binder.go","line":168,"text":"\t}"},
  {"file":"binder.go","line":169,"text":"\tvar symbol *ast.Symbol"},
  {"file":"binder.go","line":170,"text":"\tif name == ast.InternalSymbolNameMissing {"},
  {"file":"binder.go","line":171,"text":"\t\tsymbol = b.newSymbol(ast.SymbolFlagsNone, ast.InternalSymbolNameMissing)"},
  {"file":"binder.go","line":172,"text":"\t} else {"},
  {"file":"binder.go","line":196,"text":"\t\tsymbol = symbolTable[name]"},
  {"file":"binder.go","line":197,"text":"\t\tif includes&ast.SymbolFlagsClassifiable != 0 {"},
  {"file":"binder.go","line":198,"text":"\t\t\tb.classifiableNames.Add(name)"},
  {"file":"binder.go","line":199,"text":"\t\t}"},
  {"file":"binder.go","line":200,"text":"\t\tif symbol == nil {"},
  {"file":"binder.go","line":201,"text":"\t\t\tsymbol = b.newSymbol(ast.SymbolFlagsNone, name)"},
  {"file":"binder.go","line":202,"text":"\t\t\tsymbolTable[name] = symbol"},
  {"file":"binder.go","line":203,"text":"\t\t\tif isReplaceableByMethod {"},
  {"file":"binder.go","line":204,"text":"\t\t\t\tsymbol.Flags |= ast.SymbolFlagsReplaceableByMethod"},
  {"file":"binder.go","line":205,"text":"\t\t\t}"},
  {"file":"binder.go","line":206,"text":"\t\t} else if isReplaceableByMethod && symbol.Flags&ast.SymbolFlagsReplaceableByMethod == 0 {"},
  {"file":"binder.go","line":208,"text":"\t\t\treturn symbol"},
  {"file":"binder.go","line":209,"text":"\t\t} else if symbol.Flags&excludes != 0 {"},
  {"file":"binder.go","line":210,"text":"\t\t\tif symbol.Flags&ast.SymbolFlagsReplaceableByMethod != 0 {"},
  {"file":"binder.go","line":213,"text":"\t\t\t\tsymbol = b.newSymbol(ast.SymbolFlagsNone, name)"},
  {"file":"binder.go","line":214,"text":"\t\t\t\tsymbolTable[name] = symbol"},
  {"file":"binder.go","line":215,"text":"\t\t\t} else if !(includes&ast.SymbolFlagsVariable != 0 && symbol.Flags&ast.SymbolFlagsAssignment != 0 ||"},
  {"file":"binder.go","line":216,"text":"\t\t\t\tincludes&ast.SymbolFlagsAssignment != 0 && symbol.Flags&ast.SymbolFlagsVariable != 0) {"},
  {"file":"binder.go","line":220,"text":"\t\t\t\tvar message *diagnostics.Message"},
  {"file":"binder.go","line":221,"text":"\t\t\t\tif symbol.Flags&ast.SymbolFlagsBlockScopedVariable != 0 {"},
  {"file":"binder.go","line":222,"text":"\t\t\t\t\tmessage = diagnostics.Cannot_redeclare_block_scoped_variable_0"},
  {"file":"binder.go","line":223,"text":"\t\t\t\t} else {"},
  {"file":"binder.go","line":224,"text":"\t\t\t\t\tmessage = diagnostics.Duplicate_identifier_0"},
  {"file":"binder.go","line":225,"text":"\t\t\t\t}"},
  {"file":"binder.go","line":226,"text":"\t\t\t\tmessageNeedsName := true"},
  {"file":"binder.go","line":227,"text":"\t\t\t\tif symbol.Flags&ast.SymbolFlagsEnum != 0 || includes&ast.SymbolFlagsEnum != 0 {"},
  {"file":"binder.go","line":228,"text":"\t\t\t\t\tmessage = diagnostics.Enum_declarations_can_only_merge_with_namespace_or_other_enum_declarations"},
  {"file":"binder.go","line":229,"text":"\t\t\t\t\tmessageNeedsName = false"},
  {"file":"binder.go","line":230,"text":"\t\t\t\t}"},
  {"file":"binder.go","line":231,"text":"\t\t\t\tmultipleDefaultExports := false"},
];

export function binderStrictParityLineText(file: string, line: number): string | undefined {
  return binderStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function binderStrictParityFiles(): readonly string[] {
  return [...new Set(binderStrictParitySourceLines.map((entry) => entry.file))].sort();
}
