// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/compress/gzip.ts","contentHash":"ad3d55bf2fcf1697b6f84ac0c5534c92f66e295b4c1f319e6b14fbfc94dddcb6"}

export const BestCompression: unknown = undefined as never;

export function NewReader(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED compress/gzip.NewReader");
}

export function NewWriterLevel(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED compress/gzip.NewWriterLevel");
}
