export type CheckFlags = number;

export const CheckFlags = {
  None: 0,
  Instantiated: 1 << 0,
  SyntheticProperty: 1 << 1,
  SyntheticMethod: 1 << 2,
  Readonly: 1 << 3,
  ReadPartial: 1 << 4,
  WritePartial: 1 << 5,
  HasNonUniformType: 1 << 6,
  HasLiteralType: 1 << 7,
  ContainsPublic: 1 << 8,
  ContainsProtected: 1 << 9,
  ContainsPrivate: 1 << 10,
  ContainsStatic: 1 << 11,
  Late: 1 << 12,
  ReverseMapped: 1 << 13,
  OptionalParameter: 1 << 14,
  RestParameter: 1 << 15,
  DeferredType: 1 << 16,
  HasNeverType: 1 << 17,
  Mapped: 1 << 18,
  StripOptional: 1 << 19,
  Unresolved: 1 << 20,
  IsDiscriminantComputed: 1 << 21,
  IsDiscriminant: 1 << 22,
  IndexSymbol: 1 << 23,
  Synthetic: (1 << 1) | (1 << 2),
  NonUniformAndLiteral: (1 << 6) | (1 << 7),
  Partial: (1 << 4) | (1 << 5),
} as const;
