export const OperatorPrecedence = {
  Comma: 0,
  Spread: 1,
  Yield: 2,
  Assignment: 3,
  Conditional: 4,
  LogicalOR: 5,
  Coalesce: 5,
  LogicalAND: 6,
  BitwiseOR: 7,
  BitwiseXOR: 8,
  BitwiseAND: 9,
  Equality: 10,
  Relational: 11,
  Shift: 12,
  Additive: 13,
  Multiplicative: 14,
  Exponentiation: 15,
  Unary: 16,
  Update: 17,
  LeftHandSide: 18,
  OptionalChain: 19,
  Member: 20,
  Primary: 21,
  Parentheses: 22,
  Lowest: 0,
  Highest: 22,
  DisallowComma: 2,
} as const;

export type OperatorPrecedence = typeof OperatorPrecedence[keyof typeof OperatorPrecedence];
