// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/golang.org/x/text/language.ts","contentHash":"7e4ebff52bda71f0123af2382702896e01f115976741007dda771d76b9efa03b"}

export const English: unknown = undefined as never;

export const Low: unknown = undefined as never;

export function MustParse(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/text/language.MustParse");
}

export function NewMatcher(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/text/language.NewMatcher");
}

export function Parse(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/text/language.Parse");
}

export interface Tag {
  readonly __goFacadeName: "golang.org/x/text/language.Tag";
}

export const Und: unknown = undefined as never;
