import { compareText } from "./deterministic-order.mjs";
import { isActivePortPolicy, policyForUnit } from "./policies.mjs";
import { isSemanticPrimaryUnitKind } from "./unit-kinds.mjs";
import { fail, resolveRepo } from "./runtime.mjs";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

export function buildLargeFileSplitStatus(config, snapshot) {
  const threshold = Number(config.largeFileLineThreshold ?? 5000);
  if (!Number.isInteger(threshold) || threshold < 1) {
    fail("largeFileLineThreshold must be a positive integer");
  }

  const plan = loadLargeFileSplitPlan(config);
  const assignments = new Map();
  const files = [];
  const issues = [];
  const snapshotFiles = new Map((snapshot.files ?? []).map((file) => [file.path, file]));
  const requiredPaths = new Set();

  for (const file of snapshot.files ?? []) {
    const portableUnits = largeLiteralUnitsForFile(config, file, threshold);
    if (portableUnits.length === 0) continue;
    requiredPaths.add(file.path);
    const filePlan = plan.files?.[file.path];
    if (!filePlan) {
      issues.push(splitIssue(file.path, "missing-plan", `Large file has ${file.lineCount} LOC and ${portableUnits.length} portable units, but no semantic split plan.`));
      files.push({
        path: file.path,
        lineCount: file.lineCount,
        portableUnits: portableUnits.length,
        planned: false,
        assigned: 0,
        unassigned: portableUnits.length,
        duplicateAssignments: 0,
        staleDeclarations: 0,
        targetCount: 0,
      });
      continue;
    }
    files.push(validateLargeFilePlan(config, file, portableUnits, filePlan, assignments, issues));
  }

  for (const plannedPath of Object.keys(plan.files ?? {})) {
    const file = snapshotFiles.get(plannedPath);
    if (!file) {
      issues.push(splitIssue(plannedPath, "stale-file", "Split plan references a Go file that does not exist in the current TS-Go snapshot."));
      continue;
    }
    if (!requiredPaths.has(plannedPath)) {
      issues.push(splitIssue(plannedPath, "stale-plan", `Split plan exists for a file that is no longer an active literal-port file over ${threshold} LOC.`));
    }
  }

  return {
    schemaVersion: 1,
    threshold,
    planPath: splitPlanLabel(config),
    requiredFileCount: requiredPaths.size,
    plannedFileCount: Object.keys(plan.files ?? {}).length,
    assignedUnitCount: assignments.size,
    failureCount: issues.length,
    assignments: Object.fromEntries([...assignments.entries()].sort(([left], [right]) => compareText(left, right))),
    files: files.sort((left, right) => compareText(left.path, right.path)),
    issues: issues.sort((left, right) => compareText(`${left.file}:${left.kind}:${left.declaration ?? ""}`, `${right.file}:${right.kind}:${right.declaration ?? ""}`)),
  };
}

export function buildDraftLargeFileSplitPlan(config, snapshot) {
  const threshold = Number(config.largeFileLineThreshold ?? 5000);
  const files = {};
  for (const file of snapshot.files ?? []) {
    const units = largeLiteralUnitsForFile(config, file, threshold);
    if (units.length === 0) continue;
    const targetRoot = defaultLargeFileTargetRoot(config, file.path);
    const groups = new Map();
    for (const unit of units) {
      const target = draftSemanticTargetForUnit(file.path, unit);
      const group = groups.get(target.file) ?? {
        file: target.file,
        description: target.description,
        declarations: [],
      };
      group.declarations.push(splitDeclarationKey(unit));
      groups.set(target.file, group);
    }
    files[file.path] = {
      targetRoot,
      reason: `Semantic split plan for ${file.lineCount} LOC TS-Go file. Generated by porter large-files --write-draft; review group boundaries before large-scale implementation.`,
      targets: [...groups.values()]
        .map((target) => ({
          ...target,
          declarations: target.declarations.sort(compareText),
        }))
        .sort((left, right) => compareText(left.file, right.file)),
    };
  }
  return {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    sourceRevision: snapshot.gitRevision,
    threshold,
    files,
  };
}

export function largeLiteralUnitsForFile(config, file, threshold) {
  if (file.lineCount < threshold) return [];
  return (file.units ?? []).filter((unit) => {
    if (!isSemanticPrimaryUnitKind(unit.kind)) return false;
    const policy = policyForUnit(config, unit, file);
    return policy.category === "literal-port" && isActivePortPolicy(policy);
  });
}

export function defaultLargeFileTargetRoot(config, goPath) {
  return `${config.tsRoot.replace(/\/$/, "")}/${goPath.replace(/\.go$/, "")}`;
}

export function draftSemanticTargetForUnit(goPath, unit) {
  if (goPath === "internal/checker/checker.go") return draftCheckerTarget(unit);
  if (goPath === "internal/parser/parser.go") return draftParserTarget(unit);
  if (goPath === "internal/printer/printer.go") return draftPrinterTarget(unit);
  return { file: "support.ts", description: "General declarations that do not yet have a more specific semantic split." };
}

export function draftCheckerTarget(unit) {
  if (unit.kind !== "method") {
    return { file: "state.ts", description: "Checker state, enums, cache keys, constructors, package constants, and top-level helpers." };
  }
  const name = unit.name ?? "";
  const qualified = unit.qualifiedName ?? "";
  if (/(Diagnostic|Diagnostics|Error|Errors|Grammar|Report|Message|Span|RelatedInfo|Unreachable|Deprecated)/.test(qualified)) {
    return { file: "diagnostics.ts", description: "Checker diagnostics, grammar checks, error construction, and diagnostic attachment." };
  }
  if (/(Flow|Narrow|Narrowing|Truthiness|Falsy|Truthy|Discriminant|ControlFlow|Reachable|Definitely|Predicate)/.test(qualified)) {
    return { file: "flow-narrowing.ts", description: "Control-flow analysis, narrowing, predicates, and definite-state queries." };
  }
  if (/(Signature|Call|Construct|Overload|Candidate|Applicable|Invocation|Argument|Parameter|Arity|ReturnType|RestType|ThisType|JsxSignature)/.test(qualified)) {
    return { file: "signatures.ts", description: "Call, construct, overload, signature, argument, and return-type checking." };
  }
  if (/(Infer|Inference|Instantiation|Instantiate|Mapper|Mapping|Substitution|TypeParameter|Constraint|Variance)/.test(qualified)) {
    return { file: "inference.ts", description: "Generic inference, type parameter constraints, type mappers, instantiation, and variance." };
  }
  if (/(Assignable|Assignment|Related|Relation|Comparable|Compare|Subtype|Supertype|Identity|Identical|Excess|Satisfies)/.test(qualified)) {
    return { file: "relations.ts", description: "Assignability, comparability, relation checks, identity checks, and excess-property logic." };
  }
  if (/(Symbol|Declaration|Name|Member|Property|PropertyAccess|ElementAccess|Index|Lookup|ResolveName|Alias|Export|Import|Scope|Local|Global|Identifier)/.test(qualified)) {
    return { file: "symbols.ts", description: "Symbol lookup, declarations, names, imports/exports, property/member resolution, and identifier checks." };
  }
  if (/(Object|Type|Union|Intersection|Tuple|Array|Literal|Enum|Widen|Apparent|Base|Indexed|Mapped|Conditional|Template|Primitive|StringLike|NumberLike|BooleanLike|BigInt|ESSymbol|Unknown|Never|Any|Void|Null|Undefined)/.test(qualified)) {
    return { file: "types.ts", description: "Type construction, classification, object/union/intersection/tuple types, and apparent/base type operations." };
  }
  if (/(Class|Constructor|Heritage|Interface|Implements|BaseClass|Derived|Abstract|Private|Protected|Public|Static|Override)/.test(qualified)) {
    return { file: "classes.ts", description: "Class, interface, constructor, heritage, visibility, and override semantics." };
  }
  if (/(Module|Namespace|Ambient|External|Augmentation|Import|Export|Package|Global)/.test(qualified)) {
    return { file: "modules.ts", description: "Module, namespace, ambient, package, import/export, and global augmentation checks." };
  }
  if (/(Jsx|JSX|JSDoc|Decorator|TaggedTemplate|TemplateTag)/.test(qualified)) {
    return { file: "jsx-jsdoc-decorators.ts", description: "JSX, JSDoc, decorators, and tagged-template checking." };
  }
  if (/(Expression|Node|SourceFile|Statement|Block|Variable|Function|Arrow|Return|Throw|Switch|For|While|Do|Break|Continue|With|Try|Catch|Binary|Unary|Conditional|Delete|Await|Yield|Access|Literal|Template|ObjectLiteral|ArrayLiteral)/.test(qualified)) {
    return { file: "syntax-checking.ts", description: "Syntax-node checking for expressions, statements, literals, functions, and source files." };
  }
  if (/^(get|set|create|make|add|remove|append|clear|cache|mark|is|has|contains|maybe|try|forEach|visit|walk)/.test(name)) {
    return { file: "support-queries.ts", description: "Shared checker queries, caches, predicates, walkers, and small support operations." };
  }
  return { file: "support.ts", description: "General checker support declarations that remain exact-id tracked and must be reviewed before implementation." };
}

export function draftParserTarget(unit) {
  if (unit.kind !== "method" && unit.kind !== "func") {
    return { file: "state.ts", description: "Parser state, parsing contexts, pools, package constants, and top-level data." };
  }
  const qualified = unit.qualifiedName ?? "";
  if (/(JSDoc|Jsx|JSX)/.test(qualified)) return { file: "jsx-jsdoc.ts", description: "JSX and JSDoc parsing." };
  if (/(Type|Tuple|Union|Intersection|Mapped|Infer|ImportType|TypeParameter|TypeArgument|Heritage|Constraint)/.test(qualified)) return { file: "types.ts", description: "Type syntax parsing and type-list parsing." };
  if (/(Expression|Primary|Member|Call|New|Literal|Template|Binary|Unary|Update|Yield|Await|Arrow|Object|Array|Spread|ElementAccess|PropertyAccess)/.test(qualified)) return { file: "expressions.ts", description: "Expression, literal, template, and binding-element parsing." };
  if (/(Statement|Declaration|SourceFile|Block|Variable|Function|Class|Interface|Enum|Module|Namespace|Import|Export|Switch|For|While|Do|If|Try|Catch|Return|Throw|Break|Continue|With)/.test(qualified)) return { file: "statements-declarations.ts", description: "Statement, declaration, source-file, and module-item parsing." };
  if (/(List|Delimited|Separated|Array|Members|Elements|Clauses|Specifiers|Parameters|Arguments)/.test(qualified)) return { file: "lists.ts", description: "List parsing, delimited lists, parameters, arguments, members, and recovery around list terminators." };
  if (/(Token|Scanner|Scan|Expected|ReScan|LookAhead|Speculation|Context|Trivia|Keyword|Identifier)/.test(qualified)) return { file: "tokens-speculation.ts", description: "Token consumption, scanner coordination, lookahead, speculation, and context flags." };
  if (/(Error|Missing|Diagnostic|Recover|ParseError|Abort)/.test(qualified)) return { file: "errors-recovery.ts", description: "Parser diagnostics, missing nodes, recovery, and parse-error spans." };
  return { file: "support.ts", description: "General parser support declarations that remain exact-id tracked and must be reviewed before implementation." };
}

export function draftPrinterTarget(unit) {
  if (unit.kind !== "method" && unit.kind !== "func") {
    return { file: "state.ts", description: "Printer options, state records, write-kind constants, and construction helpers." };
  }
  const qualified = unit.qualifiedName ?? "";
  if (/(Comment|Trivia|Detached|Directive|Pragma)/.test(qualified)) return { file: "comments.ts", description: "Comment, trivia, detached-comment, directive, and pragma emission." };
  if (/(SourceMap|Source|Line|Position|Span|Range)/.test(qualified)) return { file: "source-maps.ts", description: "Source-map state and source-position emission." };
  if (/(Type|Tuple|Union|Intersection|Mapped|Infer|ImportType|TypeParameter|TypeArgument|Heritage)/.test(qualified)) return { file: "types.ts", description: "Type-node and type-list printing." };
  if (/(Expression|Literal|Template|Binary|Unary|Call|New|Member|PropertyAccess|ElementAccess|Object|Array|Spread|Await|Yield|Arrow)/.test(qualified)) return { file: "expressions.ts", description: "Expression, literal, template, call, member, and operator printing." };
  if (/(Statement|Block|Variable|Function|Class|Interface|Enum|Module|Namespace|Import|Export|Switch|For|While|Do|If|Try|Catch|Return|Throw|Break|Continue|With)/.test(qualified)) return { file: "statements-declarations.ts", description: "Statement, declaration, source-file, and module-item printing." };
  if (/(Write|writer|Emit|Print|Node|List|Children|Separator|Indent|Line|Text|Token|Keyword|Punctuation|Operator)/.test(qualified)) return { file: "emit-core.ts", description: "Core writer, token/list emission, indentation, separators, and node dispatch." };
  return { file: "support.ts", description: "General printer support declarations that remain exact-id tracked and must be reviewed before implementation." };
}

export function validateLargeFilePlan(config, file, units, filePlan, assignments, issues) {
  const targetRoot = normalizeSplitTargetRoot(config, file.path, filePlan.targetRoot);
  const targetDeclarations = new Map();
  const declarationToUnit = new Map(units.map((unit) => [splitDeclarationKey(unit), unit]));
  const assignedInFile = new Map();
  let staleDeclarations = 0;
  let invalidTargets = 0;

  if (!targetRoot) {
    issues.push(splitIssue(file.path, "invalid-target-root", "Split plan must specify a repo-relative targetRoot under the TypeScript source root."));
  }

  for (const [targetIndex, target] of (filePlan.targets ?? []).entries()) {
    const targetPath = splitTargetPath(targetRoot, target);
    if (!targetPath) {
      invalidTargets++;
      issues.push(splitIssue(file.path, "invalid-target", `Target #${targetIndex + 1} must specify file or path.`));
      continue;
    }
    if (isRandomLookingSplitPath(targetPath)) {
      invalidTargets++;
      issues.push(splitIssue(file.path, "random-split-target", `Target '${targetPath}' looks line/chunk based; large files must be split semantically.`));
      continue;
    }
    if (!target.description || String(target.description).trim() === "") {
      invalidTargets++;
      issues.push(splitIssue(file.path, "missing-target-description", `Target '${targetPath}' must document its semantic responsibility.`));
    }

    const targetKey = targetPath;
    const claimed = new Set();
    for (const declaration of target.declarations ?? []) {
      const unit = declarationToUnit.get(declaration);
      if (!unit) {
        staleDeclarations++;
        issues.push(splitIssue(file.path, "stale-declaration", `Split plan references declaration '${declaration}' that does not exist in this Go file.`, declaration, targetPath));
        continue;
      }
      claimed.add(splitDeclarationKey(unit));
    }
    for (const matcher of target.matchers ?? []) {
      for (const unit of units) {
        if (matchesSplitMatcher(unit, matcher)) claimed.add(splitDeclarationKey(unit));
      }
    }
    if (claimed.size === 0) {
      issues.push(splitIssue(file.path, "empty-target", `Target '${targetPath}' claims no declarations.`, undefined, targetPath));
    }
    targetDeclarations.set(targetKey, claimed.size);
    for (const declaration of claimed) {
      const unit = declarationToUnit.get(declaration);
      if (!unit) continue;
      const previous = assignedInFile.get(declaration);
      if (previous && previous !== targetPath) {
        issues.push(splitIssue(file.path, "duplicate-assignment", `Declaration '${declaration}' is claimed by both '${previous}' and '${targetPath}'.`, declaration, targetPath));
        continue;
      }
      assignedInFile.set(declaration, targetPath);
      assignments.set(unit.id, targetPath);
    }
  }

  const unassigned = [];
  for (const unit of units) {
    const key = splitDeclarationKey(unit);
    if (!assignedInFile.has(key)) {
      unassigned.push(key);
      issues.push(splitIssue(file.path, "unassigned-declaration", `Declaration '${key}' is not assigned to any semantic split target.`, key));
    }
  }

  return {
    path: file.path,
    lineCount: file.lineCount,
    portableUnits: units.length,
    planned: true,
    assigned: assignedInFile.size,
    unassigned: unassigned.length,
    duplicateAssignments: issues.filter((issue) => issue.file === file.path && issue.kind === "duplicate-assignment").length,
    staleDeclarations,
    invalidTargets,
    targetCount: (filePlan.targets ?? []).length,
    targetDeclarationCounts: Object.fromEntries([...targetDeclarations.entries()].sort()),
    unassignedDeclarations: unassigned.slice(0, 100),
  };
}

export function loadLargeFileSplitPlan(config) {
  if (config.largeFileSplitPlan) return normalizeLargeFileSplitPlan(config.largeFileSplitPlan);
  const planPath = config.largeFileSplitPlanPath ?? "packages/tsts/porter.large-splits.json";
  const absolutePath = resolveRepo(planPath);
  if (!existsSync(absolutePath)) return { schemaVersion: 1, files: {} };
  try {
    return normalizeLargeFileSplitPlan(JSON.parse(readFileSync(absolutePath, "utf8")));
  } catch (error) {
    fail(`invalid large-file split plan ${planPath}: ${error.message}`);
  }
}

export function normalizeLargeFileSplitPlan(plan) {
  if (!plan || typeof plan !== "object") fail("large-file split plan must be an object");
  if (plan.schemaVersion !== 1) fail("large-file split plan schemaVersion must be 1");
  if (!plan.files || typeof plan.files !== "object" || Array.isArray(plan.files)) {
    fail("large-file split plan must contain a files object keyed by Go source path");
  }
  return plan;
}

export function normalizeSplitTargetRoot(config, sourcePath, targetRoot) {
  if (!targetRoot || typeof targetRoot !== "string") return "";
  const normalized = targetRoot.split(path.sep).join("/").replace(/\/+$/, "");
  if (normalized.startsWith("/") || normalized.includes("..")) return "";
  const tsRoot = config.tsRoot.replace(/\/$/, "");
  if (!normalized.startsWith(`${tsRoot}/`)) return "";
  if (normalized.endsWith(".ts")) return "";
  if (normalized.includes(sourcePath.replace(/\.go$/, ".ts"))) return "";
  return normalized;
}

export function splitTargetPath(targetRoot, target) {
  const raw = target.path ?? (target.file ? `${targetRoot}/${target.file}` : "");
  if (!raw || typeof raw !== "string") return "";
  const normalized = raw.split(path.sep).join("/");
  if (normalized.startsWith("/") || normalized.includes("..") || !normalized.endsWith(".ts")) return "";
  return normalized;
}

export function isRandomLookingSplitPath(targetPath) {
  const basename = path.posix.basename(targetPath, ".ts").toLowerCase();
  return /(?:^|[-_])(part|chunk|slice|lines?)[-_]?\d+$/.test(basename) || /^p\d+$/.test(basename);
}

export function matchesSplitMatcher(unit, matcher) {
  if (!matcher || typeof matcher !== "object") return false;
  if (matcher.kind && unit.kind !== matcher.kind) return false;
  if (matcher.receiver && unit.receiver !== matcher.receiver) return false;
  if (matcher.name && unit.name !== matcher.name) return false;
  if (matcher.qualifiedName && unit.qualifiedName !== matcher.qualifiedName) return false;
  if (matcher.receiverRegex && !new RegExp(matcher.receiverRegex).test(unit.receiver ?? "")) return false;
  if (matcher.nameRegex && !new RegExp(matcher.nameRegex).test(unit.name ?? "")) return false;
  if (matcher.qualifiedNameRegex && !new RegExp(matcher.qualifiedNameRegex).test(unit.qualifiedName ?? "")) return false;
  if (matcher.idRegex && !new RegExp(matcher.idRegex).test(unit.id ?? "")) return false;
  return true;
}

export function splitDeclarationKey(unit) {
  const ordinal = /::#(\d+)$/.exec(unit.id ?? "");
  return `${unit.kind}::${unit.qualifiedName}${ordinal ? `::#${ordinal[1]}` : ""}`;
}

export function splitIssue(file, kind, message, declaration = undefined, target = undefined) {
  return { file, kind, message, declaration, target };
}

export function splitPlanLabel(config) {
  return config.largeFileSplitPlanPath ?? "packages/tsts/porter.large-splits.json";
}

export function verifyLargeFileSplitStatus(splitStatus) {
  if (splitStatus.failureCount > 0) {
    fail(`large-file split plan check failed: ${splitStatus.failureCount} issue(s)`);
  }
  console.log("large-file split plan check passed");
}

export function printLargeFileSplitStatus(config, splitStatus) {
  console.log(`Large-file threshold: ${splitStatus.threshold} LOC`);
  console.log(`Split plan: ${splitStatus.planPath}`);
  console.log(`Required large files: ${splitStatus.requiredFileCount}`);
  console.log(`Planned files: ${splitStatus.plannedFileCount}`);
  console.log(`Assigned units: ${splitStatus.assignedUnitCount}`);
  console.log(`Failures: ${splitStatus.failureCount}`);
  for (const file of splitStatus.files) {
    console.log(`${file.path}: ${file.assigned}/${file.portableUnits} assigned across ${file.targetCount} target(s)`);
  }
  if (splitStatus.issues.length > 0) {
    console.log("First issues:");
    for (const issue of splitStatus.issues.slice(0, 20)) {
      console.log(`- ${issue.file}: ${issue.kind}: ${issue.message}`);
    }
  }
}
