// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/os/signal.ts","contentHash":"d1de98002d808b763ae315c2fdf12df173de3418f665c6e875dbe4e26e23622b"}

export function NotifyContext(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os/signal.NotifyContext");
}
