// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/math/rand.ts","contentHash":"b109b5d0a6d7cf15716fa8ee7c1e30cf4d2a24890d8668bb9f6d1c66aa7db78e"}

export function Int63(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED math/rand.Int63");
}
