// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"d35cc5f485640a41fbbf5a2267e9b11c7a7db4dc","path":"go/golang.org/x/sys/unix.ts","contentHash":"69bb3aaa190e02ed0f61eb785e35499f51a9cc3f5f4beb30c6439a5985eca7ae"}

export const AT_FDCWD: unknown = undefined as never;

export function ByteSliceToString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.ByteSliceToString");
}

export function Close(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Close");
}

export function CloseOnExec(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.CloseOnExec");
}

export interface Dirent {
  readonly __goFacadeName: "golang.org/x/sys/unix.Dirent";
}

export const DT_DIR: unknown = undefined as never;

export const DT_UNKNOWN: unknown = undefined as never;

export const EACCES: unknown = undefined as never;

export const EAGAIN: unknown = undefined as never;

export const EINTR: unknown = undefined as never;

export const EINVAL: unknown = undefined as never;

export const ENOENT: unknown = undefined as never;

export const ENOTDIR: unknown = undefined as never;

export const EOPNOTSUPP: unknown = undefined as never;

export const EV_ADD: unknown = undefined as never;

export const EV_CLEAR: unknown = undefined as never;

export const EV_ENABLE: unknown = undefined as never;

export const EV_ERROR: unknown = undefined as never;

export const EVFILT_READ: unknown = undefined as never;

export const EVFILT_VNODE: unknown = undefined as never;

export const EWOULDBLOCK: unknown = undefined as never;

export const F_GETPATH: unknown = undefined as never;

export const FAN_CLASS_NOTIF: unknown = undefined as never;

export const FAN_CLOEXEC: unknown = undefined as never;

export const FAN_CREATE: unknown = undefined as never;

export const FAN_DELETE: unknown = undefined as never;

export const FAN_DELETE_SELF: unknown = undefined as never;

export const FAN_EVENT_INFO_TYPE_DFID: unknown = undefined as never;

export const FAN_EVENT_INFO_TYPE_DFID_NAME: unknown = undefined as never;

export const FAN_EVENT_INFO_TYPE_NEW_DFID_NAME: unknown = undefined as never;

export const FAN_EVENT_INFO_TYPE_OLD_DFID_NAME: unknown = undefined as never;

export const FAN_EVENT_ON_CHILD: unknown = undefined as never;

export const FAN_MARK_ADD: unknown = undefined as never;

export const FAN_MARK_DONT_FOLLOW: unknown = undefined as never;

export const FAN_MARK_ONLYDIR: unknown = undefined as never;

export const FAN_MARK_REMOVE: unknown = undefined as never;

export const FAN_MODIFY: unknown = undefined as never;

export const FAN_MOVE_SELF: unknown = undefined as never;

export const FAN_MOVED_FROM: unknown = undefined as never;

export const FAN_MOVED_TO: unknown = undefined as never;

export const FAN_NONBLOCK: unknown = undefined as never;

export const FAN_ONDIR: unknown = undefined as never;

export const FAN_Q_OVERFLOW: unknown = undefined as never;

export const FAN_RENAME: unknown = undefined as never;

export const FAN_REPORT_DFID_NAME: unknown = undefined as never;

export const FAN_REPORT_FID: unknown = undefined as never;

export const FANOTIFY_METADATA_VERSION: unknown = undefined as never;

export const FanotifyEventMetadata: unknown = undefined as never;

export function FanotifyInit(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.FanotifyInit");
}

export function FanotifyMark(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.FanotifyMark");
}

export function FcntlInt(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.FcntlInt");
}

export function Fstat(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Fstat");
}

export const IN_CLOEXEC: unknown = undefined as never;

export const IN_CREATE: unknown = undefined as never;

export const IN_DELETE: unknown = undefined as never;

export const IN_DELETE_SELF: unknown = undefined as never;

export const IN_DONT_FOLLOW: unknown = undefined as never;

export const IN_EXCL_UNLINK: unknown = undefined as never;

export const IN_ISDIR: unknown = undefined as never;

export const IN_MODIFY: unknown = undefined as never;

export const IN_MOVE_SELF: unknown = undefined as never;

export const IN_MOVED_FROM: unknown = undefined as never;

export const IN_MOVED_TO: unknown = undefined as never;

export const IN_NONBLOCK: unknown = undefined as never;

export const IN_ONLYDIR: unknown = undefined as never;

export const IN_Q_OVERFLOW: unknown = undefined as never;

export function InotifyAddWatch(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.InotifyAddWatch");
}

export interface InotifyEvent {
  readonly __goFacadeName: "golang.org/x/sys/unix.InotifyEvent";
}

export function InotifyInit1(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.InotifyInit1");
}

export function InotifyRmWatch(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.InotifyRmWatch");
}

export function Kevent(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Kevent");
}

export const Kevent_t: unknown = undefined as never;

export function Kqueue(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Kqueue");
}

export function Lstat(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Lstat");
}

export function NameToHandleAt(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.NameToHandleAt");
}

export const NOTE_ATTRIB: unknown = undefined as never;

export const NOTE_DELETE: unknown = undefined as never;

export const NOTE_EXTEND: unknown = undefined as never;

export const NOTE_RENAME: unknown = undefined as never;

export const NOTE_REVOKE: unknown = undefined as never;

export const NOTE_WRITE: unknown = undefined as never;

export const O_CLOEXEC: unknown = undefined as never;

export const O_DIRECTORY: unknown = undefined as never;

export const O_EVTONLY: unknown = undefined as never;

export const O_NOCTTY: unknown = undefined as never;

export const O_NOFOLLOW: unknown = undefined as never;

export const O_NONBLOCK: unknown = undefined as never;

export const O_PATH: unknown = undefined as never;

export const O_RDONLY: unknown = undefined as never;

export function Open(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Open");
}

export function Openat(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Openat");
}

export const PathMax: unknown = undefined as never;

export function Pipe(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Pipe");
}

export function Pipe2(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Pipe2");
}

export function Poll(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Poll");
}

export const PollFd: unknown = undefined as never;

export const POLLIN: unknown = undefined as never;

export function Read(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Read");
}

export function ReadDirent(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.ReadDirent");
}

export function Readlink(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Readlink");
}

export const S_IFDIR: unknown = undefined as never;

export const S_IFMT: unknown = undefined as never;

export function SetKevent(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.SetKevent");
}

export const SizeofInotifyEvent: unknown = undefined as never;

export function Stat(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Stat");
}

export const Stat_t: unknown = undefined as never;

export function Statfs(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Statfs");
}

export const Statfs_t: unknown = undefined as never;

export function Write(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/sys/unix.Write");
}
