// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"168e7015edf98244febc8f4ae450b673b5d195d7","path":"go/golang.org/x/sys/windows.ts","contentHash":"bedac484f4bb5c8ed05c4ba52b2326ba688f06bd7146e93dffb6cb6f3ce2f66e"}

export interface Handle {
  readonly __goFacadeName: "golang.org/x/sys/windows.Handle";
}
