// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/golang.org/x/sys/windows.ts","contentHash":"410eb3d0d597bbf25abf190be56778163c95665a29514aa77058d1dadea2d40b"}

import type { nuint } from "../../../scalars.js";
import type { GoDefined } from "../../../compat.js";

export type Handle = GoDefined<nuint, "__goDefinedType::golang.org/x/sys/windows::type::Handle::00cb16b15d92c61e2667aeb9706d830a4d42518ec9786aba6508b790e050f935">;
