// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/golang.org/x/sys/windows.ts","contentHash":"ef9863309cf2aa7d46c09492e446eac2f2cfc54b5293b448b0641dc7fd63fb0d"}

import type { nuint } from "../../../scalars.js";

export type Handle = (nuint) & { readonly "__goDefinedType::golang.org/x/sys/windows::type::Handle::00cb16b15d92c61e2667aeb9706d830a4d42518ec9786aba6508b790e050f935": never };
