/**
 * Language-service parity map for TS-Go `ls/lsutil/organizeimports.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const lsLsutilOrganizeImportsUpstreamPath = "ls/lsutil/organizeimports.go";

export const lsLsutilOrganizeImportsDeclarations: readonly UpstreamDeclaration[] = [
  {"line":27,"kind":"func","name":"FilterImportDeclarations"},
  {"line":34,"kind":"func","name":"GetDetectionLists"},
  {"line":58,"kind":"func","name":"getOrganizeImportsOrdinalStringComparer"},
  {"line":65,"kind":"func","name":"getOrganizeImportsUnicodeStringComparer"},
  {"line":155,"kind":"func","name":"getOrganizeImportsLocale"},
  {"line":177,"kind":"func","name":"getOrganizeImportsStringComparer"},
  {"line":186,"kind":"func","name":"getModuleSpecifierExpression"},
  {"line":214,"kind":"func","name":"GetExternalModuleName"},
  {"line":222,"kind":"func","name":"CompareModuleSpecifiers"},
  {"line":234,"kind":"func","name":"compareImportKind"},
  {"line":257,"kind":"func","name":"getImportKindOrder"},
  {"line":285,"kind":"func","name":"CompareImportsOrRequireStatements"},
  {"line":292,"kind":"func","name":"compareImportOrExportSpecifiers"},
  {"line":315,"kind":"func","name":"GetNamedImportSpecifierComparer"},
  {"line":329,"kind":"func","name":"GetImportSpecifierInsertionIndex"},
  {"line":336,"kind":"func","name":"GetImportDeclarationInsertIndex"},
  {"line":343,"kind":"func","name":"GetOrganizeImportsStringComparerWithDetection"},
  {"line":348,"kind":"func","name":"getComparers"},
  {"line":359,"kind":"type","name":"namedImportSortResult"},
  {"line":366,"kind":"func","name":"DetectNamedImportOrganizationBySort"},
  {"line":378,"kind":"func","name":"detectNamedImportOrganizationBySort"},
  {"line":509,"kind":"type","name":"caseSensitivityDetectionResult"},
  {"line":515,"kind":"func","name":"DetectModuleSpecifierCaseBySort"},
  {"line":532,"kind":"func","name":"detectCaseSensitivityBySort"},
  {"line":574,"kind":"func","name":"GetNamedImportSpecifierComparerWithDetection"},
];

export const lsLsutilOrganizeImportsSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package lsutil"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"cmp\""},
  {"line":5,"text":"\t\"math\""},
  {"line":6,"text":"\t\"unicode\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/locale\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"line":13,"text":"\t\"golang.org/x/text/collate\""},
  {"line":14,"text":"\t\"golang.org/x/text/language\""},
  {"line":15,"text":")"},
  {"line":17,"text":"var ("},
  {"line":18,"text":"\tcaseInsensitiveOrganizeImportsComparer = []func(a, b string) int{getOrganizeImportsOrdinalStringComparer(true)}"},
  {"line":19,"text":"\tcaseSensitiveOrganizeImportsComparer   = []func(a, b string) int{getOrganizeImportsOrdinalStringComparer(false)}"},
  {"line":20,"text":"\torganizeImportsComparers               = []func(a, b string) int{"},
  {"line":21,"text":"\t\tcaseInsensitiveOrganizeImportsComparer[0],"},
  {"line":22,"text":"\t\tcaseSensitiveOrganizeImportsComparer[0],"},
  {"line":23,"text":"\t}"},
  {"line":24,"text":")"},
  {"line":27,"text":"func FilterImportDeclarations(statements []*ast.Statement) []*ast.Statement {"},
  {"line":28,"text":"\treturn core.Filter(statements, func(stmt *ast.Statement) bool {"},
  {"line":29,"text":"\t\treturn stmt.Kind == ast.KindImportDeclaration"},
  {"line":30,"text":"\t})"},
  {"line":31,"text":"}"},
  {"line":34,"text":"func GetDetectionLists(preferences UserPreferences) (comparersToTest []func(a, b string) int, typeOrdersToTest []OrganizeImportsTypeOrder) {"},
  {"line":35,"text":"\tif !preferences.OrganizeImportsIgnoreCase.IsUnknown() {"},
  {"line":36,"text":"\t\tignoreCase := preferences.OrganizeImportsIgnoreCase.IsTrue()"},
  {"line":37,"text":"\t\tcomparersToTest = []func(a, b string) int{getOrganizeImportsStringComparer(preferences, ignoreCase)}"},
  {"line":38,"text":"\t} else {"},
  {"line":39,"text":"\t\tcomparersToTest = []func(a, b string) int{"},
  {"line":40,"text":"\t\t\tgetOrganizeImportsStringComparer(preferences, true),"},
  {"line":41,"text":"\t\t\tgetOrganizeImportsStringComparer(preferences, false),"},
  {"line":42,"text":"\t\t}"},
  {"line":43,"text":"\t}"},
  {"line":45,"text":"\tif preferences.OrganizeImportsTypeOrder != OrganizeImportsTypeOrderAuto {"},
  {"line":46,"text":"\t\ttypeOrdersToTest = []OrganizeImportsTypeOrder{preferences.OrganizeImportsTypeOrder}"},
  {"line":47,"text":"\t} else {"},
  {"line":48,"text":"\t\ttypeOrdersToTest = []OrganizeImportsTypeOrder{"},
  {"line":49,"text":"\t\t\tOrganizeImportsTypeOrderLast,"},
  {"line":50,"text":"\t\t\tOrganizeImportsTypeOrderInline,"},
  {"line":51,"text":"\t\t\tOrganizeImportsTypeOrderFirst,"},
  {"line":52,"text":"\t\t}"},
  {"line":53,"text":"\t}"},
  {"line":55,"text":"\treturn comparersToTest, typeOrdersToTest"},
  {"line":56,"text":"}"},
  {"line":58,"text":"func getOrganizeImportsOrdinalStringComparer(ignoreCase bool) func(a, b string) int {"},
  {"line":59,"text":"\tif ignoreCase {"},
  {"line":60,"text":"\t\treturn stringutil.CompareStringsCaseInsensitiveEslintCompatible"},
  {"line":61,"text":"\t}"},
  {"line":62,"text":"\treturn stringutil.CompareStringsCaseSensitive"},
  {"line":63,"text":"}"},
  {"line":65,"text":"func getOrganizeImportsUnicodeStringComparer(ignoreCase bool, preferences UserPreferences) func(a, b string) int {"},
  {"line":66,"text":"\tresolvedLocale := getOrganizeImportsLocale(preferences)"},
  {"line":68,"text":"\tcaseFirst := preferences.OrganizeImportsCaseFirst"},
  {"line":69,"text":"\tnumeric := preferences.OrganizeImportsNumericCollation.IsTrue()"},
  {"line":70,"text":"\taccents := !preferences.OrganizeImportsAccentCollation.IsFalse()"},
  {"line":72,"text":"\ttag, _ := language.Parse(resolvedLocale)"},
  {"line":74,"text":"\tvar opts []collate.Option"},
  {"line":76,"text":"\tif numeric {"},
  {"line":77,"text":"\t\topts = append(opts, collate.Numeric)"},
  {"line":78,"text":"\t}"},
  {"line":80,"text":"\tlooseOpts := append([]collate.Option{}, opts...)"},
  {"line":81,"text":"\tlooseOpts = append(looseOpts, collate.Loose)"},
  {"line":82,"text":"\tlooseCollator := collate.New(tag, looseOpts...)"},
  {"line":84,"text":"\tif !ignoreCase {"},
  {"line":85,"text":"\t\tcaseInsensitiveOpts := append([]collate.Option{}, opts...)"},
  {"line":86,"text":"\t\tcaseInsensitiveOpts = append(caseInsensitiveOpts, collate.IgnoreCase)"},
  {"line":87,"text":"\t\tcaseInsensitiveCollator := collate.New(tag, caseInsensitiveOpts...)"},
  {"line":89,"text":"\t\tfullCollator := collate.New(tag, opts...)"},
  {"line":91,"text":"\t\treturn func(a, b string) int {"},
  {"line":92,"text":"\t\t\tvar primaryCmp int"},
  {"line":93,"text":"\t\t\tif !accents {"},
  {"line":94,"text":"\t\t\t\tprimaryCmp = looseCollator.CompareString(a, b)"},
  {"line":95,"text":"\t\t\t} else {"},
  {"line":96,"text":"\t\t\t\tprimaryCmp = caseInsensitiveCollator.CompareString(a, b)"},
  {"line":97,"text":"\t\t\t}"},
  {"line":98,"text":"\t\t\tif primaryCmp != 0 {"},
  {"line":99,"text":"\t\t\t\treturn primaryCmp"},
  {"line":100,"text":"\t\t\t}"},
  {"line":102,"text":"\t\t\taRunes := []rune(a)"},
  {"line":103,"text":"\t\t\tbRunes := []rune(b)"},
  {"line":104,"text":"\t\t\tminLen := min(len(aRunes), len(bRunes))"},
  {"line":106,"text":"\t\t\tfor i := range minLen {"},
  {"line":107,"text":"\t\t\t\taUpper := unicode.IsUpper(aRunes[i])"},
  {"line":108,"text":"\t\t\t\tbUpper := unicode.IsUpper(bRunes[i])"},
  {"line":109,"text":"\t\t\t\tif aUpper != bUpper {"},
  {"line":110,"text":"\t\t\t\t\tswitch caseFirst {"},
  {"line":111,"text":"\t\t\t\t\tcase OrganizeImportsCaseFirstUpper:"},
  {"line":112,"text":"\t\t\t\t\t\tif aUpper {"},
  {"line":113,"text":"\t\t\t\t\t\t\treturn -1"},
  {"line":114,"text":"\t\t\t\t\t\t}"},
  {"line":115,"text":"\t\t\t\t\t\treturn 1"},
  {"line":116,"text":"\t\t\t\t\tcase OrganizeImportsCaseFirstLower:"},
  {"line":117,"text":"\t\t\t\t\t\tif !aUpper {"},
  {"line":118,"text":"\t\t\t\t\t\t\treturn -1"},
  {"line":119,"text":"\t\t\t\t\t\t}"},
  {"line":120,"text":"\t\t\t\t\t\treturn 1"},
  {"line":121,"text":"\t\t\t\t\tdefault:"},
  {"line":122,"text":"\t\t\t\t\t\tif aUpper {"},
  {"line":123,"text":"\t\t\t\t\t\t\treturn 1"},
  {"line":124,"text":"\t\t\t\t\t\t}"},
  {"line":125,"text":"\t\t\t\t\t\treturn -1"},
  {"line":126,"text":"\t\t\t\t\t}"},
  {"line":127,"text":"\t\t\t\t}"},
  {"line":128,"text":"\t\t\t}"},
  {"line":130,"text":"\t\t\tif !accents {"},
  {"line":131,"text":"\t\t\t\tif len(aRunes) != len(bRunes) {"},
  {"line":132,"text":"\t\t\t\t\treturn len(aRunes) - len(bRunes)"},
  {"line":133,"text":"\t\t\t\t}"},
  {"line":134,"text":"\t\t\t\treturn 0"},
  {"line":135,"text":"\t\t\t}"},
  {"line":137,"text":"\t\t\treturn fullCollator.CompareString(a, b)"},
  {"line":138,"text":"\t\t}"},
  {"line":139,"text":"\t}"},
  {"line":141,"text":"\tif ignoreCase {"},
  {"line":142,"text":"\t\topts = append(opts, collate.IgnoreCase)"},
  {"line":143,"text":"\t\tif !accents {"},
  {"line":144,"text":"\t\t\topts = append(opts, collate.Loose)"},
  {"line":145,"text":"\t\t}"},
  {"line":146,"text":"\t}"},
  {"line":148,"text":"\tcollator := collate.New(tag, opts...)"},
  {"line":150,"text":"\treturn func(a, b string) int {"},
  {"line":151,"text":"\t\treturn collator.CompareString(a, b)"},
  {"line":152,"text":"\t}"},
  {"line":153,"text":"}"},
  {"line":155,"text":"func getOrganizeImportsLocale(preferences UserPreferences) string {"},
  {"line":156,"text":"\tlocaleStr := \"en\""},
  {"line":157,"text":"\tif preferences.OrganizeImportsLocale != \"\" {"},
  {"line":158,"text":"\t\tlocaleStr = preferences.OrganizeImportsLocale"},
  {"line":159,"text":"\t}"},
  {"line":161,"text":"\tif localeStr == \"auto\" {"},
  {"line":162,"text":"\t\tif locale.Default != (locale.Locale{}) {"},
  {"line":163,"text":"\t\t\ttag := language.Tag(locale.Default)"},
  {"line":164,"text":"\t\t\treturn tag.String()"},
  {"line":165,"text":"\t\t}"},
  {"line":166,"text":"\t\treturn \"en\""},
  {"line":167,"text":"\t}"},
  {"line":169,"text":"\tif locale, ok := locale.Parse(localeStr); ok {"},
  {"line":170,"text":"\t\ttag := language.Tag(locale)"},
  {"line":171,"text":"\t\treturn tag.String()"},
  {"line":172,"text":"\t}"},
  {"line":174,"text":"\treturn \"en\""},
  {"line":175,"text":"}"},
  {"line":177,"text":"func getOrganizeImportsStringComparer(preferences UserPreferences, ignoreCase bool) func(a, b string) int {"},
  {"line":178,"text":"\tcollation := preferences.OrganizeImportsCollation"},
  {"line":180,"text":"\tif collation == OrganizeImportsCollationUnicode {"},
  {"line":181,"text":"\t\treturn getOrganizeImportsUnicodeStringComparer(ignoreCase, preferences)"},
  {"line":182,"text":"\t}"},
  {"line":183,"text":"\treturn getOrganizeImportsOrdinalStringComparer(ignoreCase)"},
  {"line":184,"text":"}"},
  {"line":186,"text":"func getModuleSpecifierExpression(declaration *ast.Statement) *ast.Expression {"},
  {"line":187,"text":"\tswitch declaration.Kind {"},
  {"line":188,"text":"\tcase ast.KindImportEqualsDeclaration:"},
  {"line":189,"text":"\t\timportEquals := declaration.AsImportEqualsDeclaration()"},
  {"line":190,"text":"\t\tif importEquals.ModuleReference.Kind == ast.KindExternalModuleReference {"},
  {"line":191,"text":"\t\t\treturn importEquals.ModuleReference.Expression()"},
  {"line":192,"text":"\t\t}"},
  {"line":193,"text":"\t\treturn nil"},
  {"line":194,"text":"\tcase ast.KindImportDeclaration:"},
  {"line":195,"text":"\t\treturn declaration.ModuleSpecifier()"},
  {"line":196,"text":"\tcase ast.KindVariableStatement:"},
  {"line":197,"text":"\t\tdeclarations := declaration.AsVariableStatement().DeclarationList.AsVariableDeclarationList().Declarations.Nodes"},
  {"line":198,"text":"\t\tif len(declarations) > 0 {"},
  {"line":199,"text":"\t\t\tinitializer := declarations[0].Initializer()"},
  {"line":200,"text":"\t\t\tif initializer != nil && initializer.Kind == ast.KindCallExpression {"},
  {"line":201,"text":"\t\t\t\tcallExpr := initializer.AsCallExpression()"},
  {"line":202,"text":"\t\t\t\tif len(callExpr.Arguments.Nodes) > 0 {"},
  {"line":203,"text":"\t\t\t\t\treturn callExpr.Arguments.Nodes[0]"},
  {"line":204,"text":"\t\t\t\t}"},
  {"line":205,"text":"\t\t\t}"},
  {"line":206,"text":"\t\t}"},
  {"line":207,"text":"\t\treturn nil"},
  {"line":208,"text":"\tdefault:"},
  {"line":209,"text":"\t\treturn nil"},
  {"line":210,"text":"\t}"},
  {"line":211,"text":"}"},
  {"line":214,"text":"func GetExternalModuleName(specifier *ast.Expression) string {"},
  {"line":215,"text":"\tif specifier != nil && ast.IsStringLiteralLike(specifier.AsNode()) {"},
  {"line":216,"text":"\t\treturn specifier.Text()"},
  {"line":217,"text":"\t}"},
  {"line":218,"text":"\treturn \"\""},
  {"line":219,"text":"}"},
  {"line":222,"text":"func CompareModuleSpecifiers(m1 *ast.Expression, m2 *ast.Expression, comparer func(a, b string) int) int {"},
  {"line":223,"text":"\tname1 := GetExternalModuleName(m1)"},
  {"line":224,"text":"\tname2 := GetExternalModuleName(m2)"},
  {"line":225,"text":"\tif cmp := core.CompareBooleans(name1 == \"\", name2 == \"\"); cmp != 0 {"},
  {"line":226,"text":"\t\treturn cmp"},
  {"line":227,"text":"\t}"},
  {"line":228,"text":"\tif cmp := core.CompareBooleans(tspath.IsExternalModuleNameRelative(name1), tspath.IsExternalModuleNameRelative(name2)); cmp != 0 {"},
  {"line":229,"text":"\t\treturn cmp"},
  {"line":230,"text":"\t}"},
  {"line":231,"text":"\treturn comparer(name1, name2)"},
  {"line":232,"text":"}"},
  {"line":234,"text":"func compareImportKind(s1 *ast.Statement, s2 *ast.Statement) int {"},
  {"line":235,"text":"\treturn cmp.Compare(getImportKindOrder(s1), getImportKindOrder(s2))"},
  {"line":236,"text":"}"},
  {"line":246,"text":"const ("},
  {"line":247,"text":"\timportKindOrderSideEffect   = 0"},
  {"line":248,"text":"\timportKindOrderTypeOnly     = 1"},
  {"line":249,"text":"\timportKindOrderNamespace    = 2"},
  {"line":250,"text":"\timportKindOrderDefault      = 3"},
  {"line":251,"text":"\timportKindOrderNamed        = 4"},
  {"line":252,"text":"\timportKindOrderImportEquals = 5"},
  {"line":253,"text":"\timportKindOrderRequire      = 6"},
  {"line":254,"text":"\timportKindOrderUnknown      = 7"},
  {"line":255,"text":")"},
  {"line":257,"text":"func getImportKindOrder(s1 *ast.Statement) int {"},
  {"line":258,"text":"\tswitch s1.Kind {"},
  {"line":259,"text":"\tcase ast.KindImportDeclaration:"},
  {"line":260,"text":"\t\timportDecl := s1.AsImportDeclaration()"},
  {"line":261,"text":"\t\tif importDecl.ImportClause == nil {"},
  {"line":262,"text":"\t\t\treturn importKindOrderSideEffect"},
  {"line":263,"text":"\t\t}"},
  {"line":264,"text":"\t\timportClause := importDecl.ImportClause.AsImportClause()"},
  {"line":265,"text":"\t\tif importClause.IsTypeOnly() {"},
  {"line":266,"text":"\t\t\treturn importKindOrderTypeOnly"},
  {"line":267,"text":"\t\t}"},
  {"line":268,"text":"\t\tif importClause.NamedBindings != nil && importClause.NamedBindings.Kind == ast.KindNamespaceImport {"},
  {"line":269,"text":"\t\t\treturn importKindOrderNamespace"},
  {"line":270,"text":"\t\t}"},
  {"line":271,"text":"\t\tif importClause.Name() != nil {"},
  {"line":272,"text":"\t\t\treturn importKindOrderDefault"},
  {"line":273,"text":"\t\t}"},
  {"line":274,"text":"\t\treturn importKindOrderNamed"},
  {"line":275,"text":"\tcase ast.KindImportEqualsDeclaration:"},
  {"line":276,"text":"\t\treturn importKindOrderImportEquals"},
  {"line":277,"text":"\tcase ast.KindVariableStatement:"},
  {"line":278,"text":"\t\treturn importKindOrderRequire"},
  {"line":279,"text":"\tdefault:"},
  {"line":280,"text":"\t\treturn importKindOrderUnknown"},
  {"line":281,"text":"\t}"},
  {"line":282,"text":"}"},
  {"line":285,"text":"func CompareImportsOrRequireStatements(s1 *ast.Statement, s2 *ast.Statement, comparer func(a, b string) int) int {"},
  {"line":286,"text":"\tif cmp := CompareModuleSpecifiers(getModuleSpecifierExpression(s1), getModuleSpecifierExpression(s2), comparer); cmp != 0 {"},
  {"line":287,"text":"\t\treturn cmp"},
  {"line":288,"text":"\t}"},
  {"line":289,"text":"\treturn compareImportKind(s1, s2)"},
  {"line":290,"text":"}"},
  {"line":292,"text":"func compareImportOrExportSpecifiers(s1 *ast.Node, s2 *ast.Node, comparer func(a, b string) int, preferences UserPreferences) int {"},
  {"line":293,"text":"\ttypeOrder := preferences.OrganizeImportsTypeOrder"},
  {"line":295,"text":"\ts1Name := s1.Name().Text()"},
  {"line":296,"text":"\ts2Name := s2.Name().Text()"},
  {"line":298,"text":"\tswitch typeOrder {"},
  {"line":299,"text":"\tcase OrganizeImportsTypeOrderFirst:"},
  {"line":300,"text":"\t\tif cmp := core.CompareBooleans(s2.IsTypeOnly(), s1.IsTypeOnly()); cmp != 0 {"},
  {"line":301,"text":"\t\t\treturn cmp"},
  {"line":302,"text":"\t\t}"},
  {"line":303,"text":"\t\treturn comparer(s1Name, s2Name)"},
  {"line":304,"text":"\tcase OrganizeImportsTypeOrderInline:"},
  {"line":305,"text":"\t\treturn comparer(s1Name, s2Name)"},
  {"line":306,"text":"\tdefault: // OrganizeImportsTypeOrderLast"},
  {"line":307,"text":"\t\tif cmp := core.CompareBooleans(s1.IsTypeOnly(), s2.IsTypeOnly()); cmp != 0 {"},
  {"line":308,"text":"\t\t\treturn cmp"},
  {"line":309,"text":"\t\t}"},
  {"line":310,"text":"\t\treturn comparer(s1Name, s2Name)"},
  {"line":311,"text":"\t}"},
  {"line":312,"text":"}"},
  {"line":315,"text":"func GetNamedImportSpecifierComparer(preferences UserPreferences, comparer func(a, b string) int) func(s1, s2 *ast.Node) int {"},
  {"line":316,"text":"\tif comparer == nil {"},
  {"line":317,"text":"\t\tignoreCase := false"},
  {"line":318,"text":"\t\tif !preferences.OrganizeImportsIgnoreCase.IsUnknown() {"},
  {"line":319,"text":"\t\t\tignoreCase = preferences.OrganizeImportsIgnoreCase.IsTrue()"},
  {"line":320,"text":"\t\t}"},
  {"line":321,"text":"\t\tcomparer = getOrganizeImportsOrdinalStringComparer(ignoreCase)"},
  {"line":322,"text":"\t}"},
  {"line":323,"text":"\treturn func(s1, s2 *ast.Node) int {"},
  {"line":324,"text":"\t\treturn compareImportOrExportSpecifiers(s1, s2, comparer, preferences)"},
  {"line":325,"text":"\t}"},
  {"line":326,"text":"}"},
  {"line":329,"text":"func GetImportSpecifierInsertionIndex(sortedImports []*ast.Node, newImport *ast.Node, comparer func(s1, s2 *ast.Node) int) int {"},
  {"line":330,"text":"\treturn core.FirstResult(core.BinarySearchUniqueFunc(sortedImports, func(mid int, value *ast.Node) int {"},
  {"line":331,"text":"\t\treturn comparer(value, newImport)"},
  {"line":332,"text":"\t}))"},
  {"line":333,"text":"}"},
  {"line":336,"text":"func GetImportDeclarationInsertIndex(sortedImports []*ast.Statement, newImport *ast.Statement, comparer func(a, b *ast.Statement) int) int {"},
  {"line":337,"text":"\treturn core.FirstResult(core.BinarySearchUniqueFunc(sortedImports, func(mid int, value *ast.Statement) int {"},
  {"line":338,"text":"\t\treturn comparer(value, newImport)"},
  {"line":339,"text":"\t}))"},
  {"line":340,"text":"}"},
  {"line":343,"text":"func GetOrganizeImportsStringComparerWithDetection(originalImportDecls []*ast.Statement, preferences UserPreferences) (comparer func(a, b string) int, isSorted bool) {"},
  {"line":344,"text":"\tresult, sorted := DetectModuleSpecifierCaseBySort([][]*ast.Statement{originalImportDecls}, getComparers(preferences))"},
  {"line":345,"text":"\treturn result, sorted"},
  {"line":346,"text":"}"},
  {"line":348,"text":"func getComparers(preferences UserPreferences) []func(a string, b string) int {"},
  {"line":349,"text":"\tswitch preferences.OrganizeImportsIgnoreCase {"},
  {"line":350,"text":"\tcase core.TSTrue:"},
  {"line":351,"text":"\t\treturn caseInsensitiveOrganizeImportsComparer"},
  {"line":352,"text":"\tcase core.TSFalse:"},
  {"line":353,"text":"\t\treturn caseSensitiveOrganizeImportsComparer"},
  {"line":354,"text":"\t}"},
  {"line":356,"text":"\treturn organizeImportsComparers"},
  {"line":357,"text":"}"},
  {"line":359,"text":"type namedImportSortResult struct {"},
  {"line":360,"text":"\tnamedImportComparer func(a, b string) int"},
  {"line":361,"text":"\ttypeOrder           OrganizeImportsTypeOrder"},
  {"line":362,"text":"\tisSorted            bool"},
  {"line":363,"text":"}"},
  {"line":366,"text":"func DetectNamedImportOrganizationBySort("},
  {"line":367,"text":"\toriginalGroups []*ast.Statement,"},
  {"line":368,"text":"\tcomparersToTest []func(a, b string) int,"},
  {"line":369,"text":"\ttypesToTest []OrganizeImportsTypeOrder,"},
  {"line":370,"text":") (comparer func(a, b string) int, typeOrder OrganizeImportsTypeOrder, found bool) {"},
  {"line":371,"text":"\tresult := detectNamedImportOrganizationBySort(originalGroups, comparersToTest, typesToTest)"},
  {"line":372,"text":"\tif result == nil {"},
  {"line":373,"text":"\t\treturn nil, OrganizeImportsTypeOrderLast, false"},
  {"line":374,"text":"\t}"},
  {"line":375,"text":"\treturn result.namedImportComparer, result.typeOrder, true"},
  {"line":376,"text":"}"},
  {"line":378,"text":"func detectNamedImportOrganizationBySort("},
  {"line":379,"text":"\toriginalGroups []*ast.Statement,"},
  {"line":380,"text":"\tcomparersToTest []func(a, b string) int,"},
  {"line":381,"text":"\ttypesToTest []OrganizeImportsTypeOrder,"},
  {"line":382,"text":") *namedImportSortResult {"},
  {"line":383,"text":"\tvar bothNamedImports bool"},
  {"line":384,"text":"\tvar importDeclsWithNamed []*ast.Statement"},
  {"line":386,"text":"\tfor _, imp := range originalGroups {"},
  {"line":387,"text":"\t\tif imp.AsImportDeclaration().ImportClause == nil {"},
  {"line":388,"text":"\t\t\tcontinue"},
  {"line":389,"text":"\t\t}"},
  {"line":390,"text":"\t\tclause := imp.AsImportDeclaration().ImportClause.AsImportClause()"},
  {"line":391,"text":"\t\tif clause.NamedBindings == nil || clause.NamedBindings.Kind != ast.KindNamedImports {"},
  {"line":392,"text":"\t\t\tcontinue"},
  {"line":393,"text":"\t\t}"},
  {"line":394,"text":"\t\tnamedImports := clause.NamedBindings.AsNamedImports()"},
  {"line":395,"text":"\t\tif len(namedImports.Elements.Nodes) == 0 {"},
  {"line":396,"text":"\t\t\tcontinue"},
  {"line":397,"text":"\t\t}"},
  {"line":399,"text":"\t\tif !bothNamedImports {"},
  {"line":400,"text":"\t\t\thasTypeOnly := false"},
  {"line":401,"text":"\t\t\thasRegular := false"},
  {"line":402,"text":"\t\t\tfor _, elem := range namedImports.Elements.Nodes {"},
  {"line":403,"text":"\t\t\t\tif elem.IsTypeOnly() {"},
  {"line":404,"text":"\t\t\t\t\thasTypeOnly = true"},
  {"line":405,"text":"\t\t\t\t} else {"},
  {"line":406,"text":"\t\t\t\t\thasRegular = true"},
  {"line":407,"text":"\t\t\t\t}"},
  {"line":408,"text":"\t\t\t}"},
  {"line":409,"text":"\t\t\tif hasTypeOnly && hasRegular {"},
  {"line":410,"text":"\t\t\t\tbothNamedImports = true"},
  {"line":411,"text":"\t\t\t}"},
  {"line":412,"text":"\t\t}"},
  {"line":414,"text":"\t\timportDeclsWithNamed = append(importDeclsWithNamed, imp)"},
  {"line":415,"text":"\t}"},
  {"line":417,"text":"\tif len(importDeclsWithNamed) == 0 {"},
  {"line":418,"text":"\t\treturn nil"},
  {"line":419,"text":"\t}"},
  {"line":421,"text":"\tnamedImportsByDecl := make([][]*ast.Statement, 0, len(importDeclsWithNamed))"},
  {"line":422,"text":"\tfor _, imp := range importDeclsWithNamed {"},
  {"line":423,"text":"\t\tclause := imp.AsImportDeclaration().ImportClause.AsImportClause()"},
  {"line":424,"text":"\t\tnamedImports := clause.NamedBindings.AsNamedImports()"},
  {"line":425,"text":"\t\tnamedImportsByDecl = append(namedImportsByDecl, namedImports.Elements.Nodes)"},
  {"line":426,"text":"\t}"},
  {"line":428,"text":"\tif !bothNamedImports || len(typesToTest) == 0 {"},
  {"line":429,"text":"\t\tnamesList := make([][]string, len(namedImportsByDecl))"},
  {"line":430,"text":"\t\tfor i, imports := range namedImportsByDecl {"},
  {"line":431,"text":"\t\t\tnames := make([]string, len(imports))"},
  {"line":432,"text":"\t\t\tfor j, imp := range imports {"},
  {"line":433,"text":"\t\t\t\tnames[j] = imp.Name().Text()"},
  {"line":434,"text":"\t\t\t}"},
  {"line":435,"text":"\t\t\tnamesList[i] = names"},
  {"line":436,"text":"\t\t}"},
  {"line":437,"text":"\t\tsortState := detectCaseSensitivityBySort(namesList, comparersToTest)"},
  {"line":438,"text":"\t\ttypeOrder := OrganizeImportsTypeOrderLast"},
  {"line":439,"text":"\t\tif len(typesToTest) == 1 {"},
  {"line":440,"text":"\t\t\ttypeOrder = typesToTest[0]"},
  {"line":441,"text":"\t\t}"},
  {"line":442,"text":"\t\treturn &namedImportSortResult{"},
  {"line":443,"text":"\t\t\tnamedImportComparer: sortState.comparer,"},
  {"line":444,"text":"\t\t\ttypeOrder:           typeOrder,"},
  {"line":445,"text":"\t\t\tisSorted:            sortState.isSorted,"},
  {"line":446,"text":"\t\t}"},
  {"line":447,"text":"\t}"},
  {"line":449,"text":"\tbestDiff := map[OrganizeImportsTypeOrder]int{"},
  {"line":450,"text":"\t\tOrganizeImportsTypeOrderFirst:  math.MaxInt,"},
  {"line":451,"text":"\t\tOrganizeImportsTypeOrderLast:   math.MaxInt,"},
  {"line":452,"text":"\t\tOrganizeImportsTypeOrderInline: math.MaxInt,"},
  {"line":453,"text":"\t}"},
  {"line":454,"text":"\tbestComparer := map[OrganizeImportsTypeOrder]func(a, b string) int{"},
  {"line":455,"text":"\t\tOrganizeImportsTypeOrderFirst:  comparersToTest[0],"},
  {"line":456,"text":"\t\tOrganizeImportsTypeOrderLast:   comparersToTest[0],"},
  {"line":457,"text":"\t\tOrganizeImportsTypeOrderInline: comparersToTest[0],"},
  {"line":458,"text":"\t}"},
  {"line":460,"text":"\tfor _, curComparer := range comparersToTest {"},
  {"line":461,"text":"\t\tcurrDiff := map[OrganizeImportsTypeOrder]int{"},
  {"line":462,"text":"\t\t\tOrganizeImportsTypeOrderFirst:  0,"},
  {"line":463,"text":"\t\t\tOrganizeImportsTypeOrderLast:   0,"},
  {"line":464,"text":"\t\t\tOrganizeImportsTypeOrderInline: 0,"},
  {"line":465,"text":"\t\t}"},
  {"line":467,"text":"\t\tfor _, importDecl := range namedImportsByDecl {"},
  {"line":468,"text":"\t\t\tfor _, typeOrder := range typesToTest {"},
  {"line":469,"text":"\t\t\t\tprefs := UserPreferences{OrganizeImportsTypeOrder: typeOrder}"},
  {"line":470,"text":"\t\t\t\tdiff := measureSortedness(importDecl, func(n1, n2 *ast.Node) int {"},
  {"line":471,"text":"\t\t\t\t\treturn compareImportOrExportSpecifiers(n1, n2, curComparer, prefs)"},
  {"line":472,"text":"\t\t\t\t})"},
  {"line":473,"text":"\t\t\t\tcurrDiff[typeOrder] = currDiff[typeOrder] + diff"},
  {"line":474,"text":"\t\t\t}"},
  {"line":475,"text":"\t\t}"},
  {"line":477,"text":"\t\tfor _, typeOrder := range typesToTest {"},
  {"line":478,"text":"\t\t\tif currDiff[typeOrder] < bestDiff[typeOrder] {"},
  {"line":479,"text":"\t\t\t\tbestDiff[typeOrder] = currDiff[typeOrder]"},
  {"line":480,"text":"\t\t\t\tbestComparer[typeOrder] = curComparer"},
  {"line":481,"text":"\t\t\t}"},
  {"line":482,"text":"\t\t}"},
  {"line":483,"text":"\t}"},
  {"line":485,"text":"\tfor _, bestTypeOrder := range typesToTest {"},
  {"line":486,"text":"\t\tisBest := true"},
  {"line":487,"text":"\t\tfor _, testTypeOrder := range typesToTest {"},
  {"line":488,"text":"\t\t\tif bestDiff[testTypeOrder] < bestDiff[bestTypeOrder] {"},
  {"line":489,"text":"\t\t\t\tisBest = false"},
  {"line":490,"text":"\t\t\t\tbreak"},
  {"line":491,"text":"\t\t\t}"},
  {"line":492,"text":"\t\t}"},
  {"line":493,"text":"\t\tif isBest {"},
  {"line":494,"text":"\t\t\treturn &namedImportSortResult{"},
  {"line":495,"text":"\t\t\t\tnamedImportComparer: bestComparer[bestTypeOrder],"},
  {"line":496,"text":"\t\t\t\ttypeOrder:           bestTypeOrder,"},
  {"line":497,"text":"\t\t\t\tisSorted:            bestDiff[bestTypeOrder] == 0,"},
  {"line":498,"text":"\t\t\t}"},
  {"line":499,"text":"\t\t}"},
  {"line":500,"text":"\t}"},
  {"line":502,"text":"\treturn &namedImportSortResult{"},
  {"line":503,"text":"\t\tnamedImportComparer: bestComparer[OrganizeImportsTypeOrderLast],"},
  {"line":504,"text":"\t\ttypeOrder:           OrganizeImportsTypeOrderLast,"},
  {"line":505,"text":"\t\tisSorted:            bestDiff[OrganizeImportsTypeOrderLast] == 0,"},
  {"line":506,"text":"\t}"},
  {"line":507,"text":"}"},
  {"line":509,"text":"type caseSensitivityDetectionResult struct {"},
  {"line":510,"text":"\tcomparer func(a, b string) int"},
  {"line":511,"text":"\tisSorted bool"},
  {"line":512,"text":"}"},
  {"line":515,"text":"func DetectModuleSpecifierCaseBySort(importDeclsByGroup [][]*ast.Statement, comparersToTest []func(a, b string) int) (comparer func(a, b string) int, isSorted bool) {"},
  {"line":516,"text":"\tmoduleSpecifiersByGroup := make([][]string, 0, len(importDeclsByGroup))"},
  {"line":517,"text":"\tfor _, importGroup := range importDeclsByGroup {"},
  {"line":518,"text":"\t\tmoduleNames := make([]string, 0, len(importGroup))"},
  {"line":519,"text":"\t\tfor _, decl := range importGroup {"},
  {"line":520,"text":"\t\t\tif expr := getModuleSpecifierExpression(decl); expr != nil {"},
  {"line":521,"text":"\t\t\t\tmoduleNames = append(moduleNames, GetExternalModuleName(expr))"},
  {"line":522,"text":"\t\t\t} else {"},
  {"line":523,"text":"\t\t\t\tmoduleNames = append(moduleNames, \"\")"},
  {"line":524,"text":"\t\t\t}"},
  {"line":525,"text":"\t\t}"},
  {"line":526,"text":"\t\tmoduleSpecifiersByGroup = append(moduleSpecifiersByGroup, moduleNames)"},
  {"line":527,"text":"\t}"},
  {"line":528,"text":"\tresult := detectCaseSensitivityBySort(moduleSpecifiersByGroup, comparersToTest)"},
  {"line":529,"text":"\treturn result.comparer, result.isSorted"},
  {"line":530,"text":"}"},
  {"line":532,"text":"func detectCaseSensitivityBySort(originalGroups [][]string, comparersToTest []func(a, b string) int) caseSensitivityDetectionResult {"},
  {"line":533,"text":"\tvar bestComparer func(a, b string) int"},
  {"line":534,"text":"\tbestDiff := math.MaxInt"},
  {"line":536,"text":"\tfor _, curComparer := range comparersToTest {"},
  {"line":537,"text":"\t\tdiffOfCurrentComparer := 0"},
  {"line":539,"text":"\t\tfor _, listToSort := range originalGroups {"},
  {"line":540,"text":"\t\t\tif len(listToSort) <= 1 {"},
  {"line":541,"text":"\t\t\t\tcontinue"},
  {"line":542,"text":"\t\t\t}"},
  {"line":543,"text":"\t\t\tdiff := measureSortedness(listToSort, curComparer)"},
  {"line":544,"text":"\t\t\tdiffOfCurrentComparer += diff"},
  {"line":545,"text":"\t\t}"},
  {"line":547,"text":"\t\tif diffOfCurrentComparer < bestDiff {"},
  {"line":548,"text":"\t\t\tbestDiff = diffOfCurrentComparer"},
  {"line":549,"text":"\t\t\tbestComparer = curComparer"},
  {"line":550,"text":"\t\t}"},
  {"line":551,"text":"\t}"},
  {"line":553,"text":"\tif bestComparer == nil && len(comparersToTest) > 0 {"},
  {"line":554,"text":"\t\tbestComparer = comparersToTest[0]"},
  {"line":555,"text":"\t}"},
  {"line":557,"text":"\treturn caseSensitivityDetectionResult{"},
  {"line":558,"text":"\t\tcomparer: bestComparer,"},
  {"line":559,"text":"\t\tisSorted: bestDiff == 0,"},
  {"line":560,"text":"\t}"},
  {"line":561,"text":"}"},
  {"line":563,"text":"func measureSortedness[T any](arr []T, comparer func(a, b T) int) int {"},
  {"line":564,"text":"\ti := 0"},
  {"line":565,"text":"\tfor j := range len(arr) - 1 {"},
  {"line":566,"text":"\t\tif comparer(arr[j], arr[j+1]) > 0 {"},
  {"line":567,"text":"\t\t\ti++"},
  {"line":568,"text":"\t\t}"},
  {"line":569,"text":"\t}"},
  {"line":570,"text":"\treturn i"},
  {"line":571,"text":"}"},
  {"line":574,"text":"func GetNamedImportSpecifierComparerWithDetection(importDecl *ast.Node, sourceFile *ast.SourceFile, preferences UserPreferences) (specifierComparer func(s1, s2 *ast.Node) int, isSorted core.Tristate) {"},
  {"line":575,"text":"\tcomparersToTest, typeOrdersToTest := GetDetectionLists(preferences)"},
  {"line":577,"text":"\tvar importStmt *ast.Statement"},
  {"line":578,"text":"\tif importDecl.Kind == ast.KindImportDeclaration {"},
  {"line":579,"text":"\t\timportStmt = importDecl"},
  {"line":580,"text":"\t}"},
  {"line":582,"text":"\tspecifierComparer = GetNamedImportSpecifierComparer(preferences, comparersToTest[0])"},
  {"line":583,"text":"\tisSorted = core.TSUnknown"},
  {"line":585,"text":"\tif (preferences.OrganizeImportsIgnoreCase.IsUnknown() || preferences.OrganizeImportsTypeOrder == OrganizeImportsTypeOrderAuto) && importStmt != nil {"},
  {"line":586,"text":"\t\tdetectFromDecl := detectNamedImportOrganizationBySort([]*ast.Statement{importStmt}, comparersToTest, typeOrdersToTest)"},
  {"line":587,"text":"\t\tif detectFromDecl != nil {"},
  {"line":588,"text":"\t\t\tisSorted = core.BoolToTristate(detectFromDecl.isSorted)"},
  {"line":589,"text":"\t\t\tspecifierComparer = GetNamedImportSpecifierComparer("},
  {"line":590,"text":"\t\t\t\tUserPreferences{OrganizeImportsTypeOrder: detectFromDecl.typeOrder},"},
  {"line":591,"text":"\t\t\t\tdetectFromDecl.namedImportComparer,"},
  {"line":592,"text":"\t\t\t)"},
  {"line":593,"text":"\t\t} else if sourceFile != nil {"},
  {"line":594,"text":"\t\t\tallImports := FilterImportDeclarations(sourceFile.Statements.Nodes)"},
  {"line":595,"text":"\t\t\tdetectFromFile := detectNamedImportOrganizationBySort(allImports, comparersToTest, typeOrdersToTest)"},
  {"line":596,"text":"\t\t\tif detectFromFile != nil {"},
  {"line":597,"text":"\t\t\t\tisSorted = core.BoolToTristate(detectFromFile.isSorted)"},
  {"line":598,"text":"\t\t\t\tspecifierComparer = GetNamedImportSpecifierComparer("},
  {"line":599,"text":"\t\t\t\t\tUserPreferences{OrganizeImportsTypeOrder: detectFromFile.typeOrder},"},
  {"line":600,"text":"\t\t\t\t\tdetectFromFile.namedImportComparer,"},
  {"line":601,"text":"\t\t\t\t)"},
  {"line":602,"text":"\t\t\t}"},
  {"line":603,"text":"\t\t}"},
  {"line":604,"text":"\t}"},
  {"line":606,"text":"\treturn specifierComparer, isSorted"},
  {"line":607,"text":"}"},
];

export function findLsLsutilOrganizeImportsDeclaration(name: string): UpstreamDeclaration | undefined {
  return lsLsutilOrganizeImportsDeclarations.find((declaration) => declaration.name === name);
}

export function requireLsLsutilOrganizeImportsDeclaration(name: string): UpstreamDeclaration {
  const declaration = findLsLsutilOrganizeImportsDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function lsLsutilOrganizeImportsLineText(line: number): string | undefined {
  return lsLsutilOrganizeImportsSourceLines.find((entry) => entry.line === line)?.text;
}
