/**
 * Strict TS-Go parity gap map for `testutil`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const testutilStrictParityUpstreamModule = "testutil";
export const testutilStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"autoimporttestutil/fixtures.go","line":1,"text":"package autoimporttestutil"},
  {"file":"autoimporttestutil/fixtures.go","line":3,"text":"import ("},
  {"file":"autoimporttestutil/fixtures.go","line":4,"text":"\t\"fmt\""},
  {"file":"autoimporttestutil/fixtures.go","line":5,"text":"\t\"maps\""},
  {"file":"autoimporttestutil/fixtures.go","line":6,"text":"\t\"slices\""},
  {"file":"autoimporttestutil/fixtures.go","line":7,"text":"\t\"strings\""},
  {"file":"autoimporttestutil/fixtures.go","line":8,"text":"\t\"testing\""},
  {"file":"autoimporttestutil/fixtures.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"file":"autoimporttestutil/fixtures.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"file":"autoimporttestutil/fixtures.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/project\""},
  {"file":"autoimporttestutil/fixtures.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/testutil/projecttestutil\""},
  {"file":"autoimporttestutil/fixtures.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"autoimporttestutil/fixtures.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs/vfstest\""},
  {"file":"autoimporttestutil/fixtures.go","line":16,"text":")"},
  {"file":"autoimporttestutil/fixtures.go","line":19,"text":"type FileHandle struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":20,"text":"\tfileName string"},
  {"file":"autoimporttestutil/fixtures.go","line":21,"text":"\tcontent  string"},
  {"file":"autoimporttestutil/fixtures.go","line":22,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":24,"text":"func (f FileHandle) FileName() string         { return f.fileName }"},
  {"file":"autoimporttestutil/fixtures.go","line":25,"text":"func (f FileHandle) Content() string          { return f.content }"},
  {"file":"autoimporttestutil/fixtures.go","line":26,"text":"func (f FileHandle) URI() lsproto.DocumentUri { return lsconv.FileNameToDocumentURI(f.fileName) }"},
  {"file":"autoimporttestutil/fixtures.go","line":29,"text":"type ProjectFileHandle struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":30,"text":"\tFileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":31,"text":"\texportIdentifier string"},
  {"file":"autoimporttestutil/fixtures.go","line":32,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":35,"text":"type NodeModulesPackageHandle struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":36,"text":"\tName        string"},
  {"file":"autoimporttestutil/fixtures.go","line":37,"text":"\tDirectory   string"},
  {"file":"autoimporttestutil/fixtures.go","line":38,"text":"\tpackageJSON FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":39,"text":"\tdeclaration FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":40,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":42,"text":"func (p NodeModulesPackageHandle) PackageJSONFile() FileHandle { return p.packageJSON }"},
  {"file":"autoimporttestutil/fixtures.go","line":43,"text":"func (p NodeModulesPackageHandle) DeclarationFile() FileHandle { return p.declaration }"},
  {"file":"autoimporttestutil/fixtures.go","line":46,"text":"type MonorepoHandle struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":47,"text":"\troot             string"},
  {"file":"autoimporttestutil/fixtures.go","line":48,"text":"\trootNodeModules  []NodeModulesPackageHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":49,"text":"\trootDependencies []string"},
  {"file":"autoimporttestutil/fixtures.go","line":50,"text":"\tpackages         []ProjectHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":51,"text":"\trootTSConfig     FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":52,"text":"\trootPackageJSON  FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":53,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":55,"text":"func (m MonorepoHandle) Root() string { return m.root }"},
  {"file":"autoimporttestutil/fixtures.go","line":56,"text":"func (m MonorepoHandle) RootNodeModules() []NodeModulesPackageHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":57,"text":"\treturn slices.Clone(m.rootNodeModules)"},
  {"file":"autoimporttestutil/fixtures.go","line":58,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":59,"text":"func (m MonorepoHandle) RootDependencies() []string { return slices.Clone(m.rootDependencies) }"},
  {"file":"autoimporttestutil/fixtures.go","line":60,"text":"func (m MonorepoHandle) Packages() []ProjectHandle  { return slices.Clone(m.packages) }"},
  {"file":"autoimporttestutil/fixtures.go","line":61,"text":"func (m MonorepoHandle) Package(index int) ProjectHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":62,"text":"\tif index < 0 || index >= len(m.packages) {"},
  {"file":"autoimporttestutil/fixtures.go","line":63,"text":"\t\tpanic(fmt.Sprintf(\"package index %d out of range\", index))"},
  {"file":"autoimporttestutil/fixtures.go","line":64,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":65,"text":"\treturn m.packages[index]"},
  {"file":"autoimporttestutil/fixtures.go","line":66,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":67,"text":"func (m MonorepoHandle) RootTSConfig() FileHandle        { return m.rootTSConfig }"},
  {"file":"autoimporttestutil/fixtures.go","line":68,"text":"func (m MonorepoHandle) RootPackageJSONFile() FileHandle { return m.rootPackageJSON }"},
  {"file":"autoimporttestutil/fixtures.go","line":71,"text":"type ProjectHandle struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":72,"text":"\troot         string"},
  {"file":"autoimporttestutil/fixtures.go","line":73,"text":"\tfiles        []ProjectFileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":74,"text":"\ttsconfig     FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":75,"text":"\tpackageJSON  FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":76,"text":"\tnodeModules  []NodeModulesPackageHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":77,"text":"\tdependencies []string"},
  {"file":"autoimporttestutil/fixtures.go","line":78,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":80,"text":"func (p ProjectHandle) Root() string               { return p.root }"},
  {"file":"autoimporttestutil/fixtures.go","line":81,"text":"func (p ProjectHandle) Files() []ProjectFileHandle { return slices.Clone(p.files) }"},
  {"file":"autoimporttestutil/fixtures.go","line":82,"text":"func (p ProjectHandle) File(index int) ProjectFileHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":83,"text":"\tif index < 0 || index >= len(p.files) {"},
  {"file":"autoimporttestutil/fixtures.go","line":84,"text":"\t\tpanic(fmt.Sprintf(\"file index %d out of range\", index))"},
  {"file":"autoimporttestutil/fixtures.go","line":85,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":86,"text":"\treturn p.files[index]"},
  {"file":"autoimporttestutil/fixtures.go","line":87,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":88,"text":"func (p ProjectHandle) TSConfig() FileHandle        { return p.tsconfig }"},
  {"file":"autoimporttestutil/fixtures.go","line":89,"text":"func (p ProjectHandle) PackageJSONFile() FileHandle { return p.packageJSON }"},
  {"file":"autoimporttestutil/fixtures.go","line":90,"text":"func (p ProjectHandle) NodeModules() []NodeModulesPackageHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":91,"text":"\treturn slices.Clone(p.nodeModules)"},
  {"file":"autoimporttestutil/fixtures.go","line":92,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":93,"text":"func (p ProjectHandle) Dependencies() []string { return slices.Clone(p.dependencies) }"},
  {"file":"autoimporttestutil/fixtures.go","line":95,"text":"func (p ProjectHandle) NodeModuleByName(name string) *NodeModulesPackageHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":96,"text":"\tfor i := range p.nodeModules {"},
  {"file":"autoimporttestutil/fixtures.go","line":97,"text":"\t\tif p.nodeModules[i].Name == name {"},
  {"file":"autoimporttestutil/fixtures.go","line":98,"text":"\t\t\treturn &p.nodeModules[i]"},
  {"file":"autoimporttestutil/fixtures.go","line":99,"text":"\t\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":100,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":101,"text":"\treturn nil"},
  {"file":"autoimporttestutil/fixtures.go","line":102,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":105,"text":"type Fixture struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":106,"text":"\tsession  *project.Session"},
  {"file":"autoimporttestutil/fixtures.go","line":107,"text":"\tutils    *projecttestutil.SessionUtils"},
  {"file":"autoimporttestutil/fixtures.go","line":108,"text":"\tprojects []ProjectHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":109,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":111,"text":"func (f *Fixture) Session() *project.Session            { return f.session }"},
  {"file":"autoimporttestutil/fixtures.go","line":112,"text":"func (f *Fixture) Utils() *projecttestutil.SessionUtils { return f.utils }"},
  {"file":"autoimporttestutil/fixtures.go","line":113,"text":"func (f *Fixture) Projects() []ProjectHandle            { return slices.Clone(f.projects) }"},
  {"file":"autoimporttestutil/fixtures.go","line":114,"text":"func (f *Fixture) Project(index int) ProjectHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":115,"text":"\tif index < 0 || index >= len(f.projects) {"},
  {"file":"autoimporttestutil/fixtures.go","line":116,"text":"\t\tpanic(fmt.Sprintf(\"project index %d out of range\", index))"},
  {"file":"autoimporttestutil/fixtures.go","line":117,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":118,"text":"\treturn f.projects[index]"},
  {"file":"autoimporttestutil/fixtures.go","line":119,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":120,"text":"func (f *Fixture) SingleProject() ProjectHandle { return f.Project(0) }"},
  {"file":"autoimporttestutil/fixtures.go","line":123,"text":"type MonorepoFixture struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":124,"text":"\tsession  *project.Session"},
  {"file":"autoimporttestutil/fixtures.go","line":125,"text":"\tutils    *projecttestutil.SessionUtils"},
  {"file":"autoimporttestutil/fixtures.go","line":126,"text":"\tmonorepo MonorepoHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":127,"text":"\textra    []FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":128,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":130,"text":"func (f *MonorepoFixture) Session() *project.Session            { return f.session }"},
  {"file":"autoimporttestutil/fixtures.go","line":131,"text":"func (f *MonorepoFixture) Utils() *projecttestutil.SessionUtils { return f.utils }"},
  {"file":"autoimporttestutil/fixtures.go","line":132,"text":"func (f *MonorepoFixture) Monorepo() MonorepoHandle             { return f.monorepo }"},
  {"file":"autoimporttestutil/fixtures.go","line":133,"text":"func (f *MonorepoFixture) ExtraFiles() []FileHandle             { return slices.Clone(f.extra) }"},
  {"file":"autoimporttestutil/fixtures.go","line":134,"text":"func (f *MonorepoFixture) ExtraFile(path string) FileHandle {"},
  {"file":"autoimporttestutil/fixtures.go","line":135,"text":"\tnormalized := normalizeAbsolutePath(path)"},
  {"file":"autoimporttestutil/fixtures.go","line":136,"text":"\tfor _, handle := range f.extra {"},
  {"file":"autoimporttestutil/fixtures.go","line":137,"text":"\t\tif handle.fileName == normalized {"},
  {"file":"autoimporttestutil/fixtures.go","line":138,"text":"\t\t\treturn handle"},
  {"file":"autoimporttestutil/fixtures.go","line":139,"text":"\t\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":140,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":141,"text":"\tpanic(\"extra file not found: \" + path)"},
  {"file":"autoimporttestutil/fixtures.go","line":142,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":148,"text":"type MonorepoPackageTemplate struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":149,"text":"\tName            string"},
  {"file":"autoimporttestutil/fixtures.go","line":150,"text":"\tNodeModuleNames []string"},
  {"file":"autoimporttestutil/fixtures.go","line":151,"text":"\tDependencyNames []string"},
  {"file":"autoimporttestutil/fixtures.go","line":152,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":159,"text":"type MonorepoSetupConfig struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":160,"text":"\tRoot string"},
  {"file":"autoimporttestutil/fixtures.go","line":161,"text":"\tMonorepoPackageTemplate"},
  {"file":"autoimporttestutil/fixtures.go","line":162,"text":"\tPackages   []MonorepoPackageConfig"},
  {"file":"autoimporttestutil/fixtures.go","line":163,"text":"\tExtraFiles []TextFileSpec"},
  {"file":"autoimporttestutil/fixtures.go","line":164,"text":"\tSymlinks   []SymlinkSpec"},
  {"file":"autoimporttestutil/fixtures.go","line":165,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":167,"text":"type MonorepoPackageConfig struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":168,"text":"\tFileCount int"},
  {"file":"autoimporttestutil/fixtures.go","line":169,"text":"\tMonorepoPackageTemplate"},
  {"file":"autoimporttestutil/fixtures.go","line":170,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":173,"text":"type TextFileSpec struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":174,"text":"\tPath    string"},
  {"file":"autoimporttestutil/fixtures.go","line":175,"text":"\tContent string"},
  {"file":"autoimporttestutil/fixtures.go","line":176,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":179,"text":"type SymlinkSpec struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":180,"text":"\tLink   string // The symlink path"},
  {"file":"autoimporttestutil/fixtures.go","line":181,"text":"\tTarget string // The target path the symlink points to"},
  {"file":"autoimporttestutil/fixtures.go","line":182,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":202,"text":"func SetupMonorepoLifecycleSession(t *testing.T, config MonorepoSetupConfig) *MonorepoFixture {"},
  {"file":"autoimporttestutil/fixtures.go","line":203,"text":"\tt.Helper()"},
  {"file":"autoimporttestutil/fixtures.go","line":204,"text":"\tbuilder := newFileMapBuilder(nil)"},
  {"file":"autoimporttestutil/fixtures.go","line":206,"text":"\tmonorepoRoot := normalizeAbsolutePath(config.Root)"},
  {"file":"autoimporttestutil/fixtures.go","line":207,"text":"\tmonorepoName := config.MonorepoPackageTemplate.Name"},
  {"file":"autoimporttestutil/fixtures.go","line":208,"text":"\tif monorepoName == \"\" {"},
  {"file":"autoimporttestutil/fixtures.go","line":209,"text":"\t\tmonorepoName = \"monorepo\""},
  {"file":"autoimporttestutil/fixtures.go","line":210,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":213,"text":"\trootTSConfigPath := tspath.CombinePaths(monorepoRoot, \"tsconfig.json\")"},
  {"file":"autoimporttestutil/fixtures.go","line":214,"text":"\trootTSConfigContent := \"{\\n  \\\"compilerOptions\\\": {\\n    \\\"module\\\": \\\"esnext\\\",\\n    \\\"target\\\": \\\"esnext\\\",\\n    \\\"strict\\\": true,\\n    \\\"baseUrl\\\": \\\".\\\",\\n    \\\"allowJs\\\": true,\\n    \\\"checkJs\\\": true\\n  }\\n}\\n\""},
  {"file":"autoimporttestutil/fixtures.go","line":215,"text":"\tbuilder.AddTextFile(rootTSConfigPath, rootTSConfigContent)"},
  {"file":"autoimporttestutil/fixtures.go","line":216,"text":"\trootTSConfig := FileHandle{fileName: rootTSConfigPath, content: rootTSConfigContent}"},
  {"file":"autoimporttestutil/fixtures.go","line":219,"text":"\trootNodeModulesDir := tspath.CombinePaths(monorepoRoot, \"node_modules\")"},
  {"file":"autoimporttestutil/fixtures.go","line":220,"text":"\trootNodeModules := builder.AddNodeModulesPackagesWithNames(rootNodeModulesDir, config.NodeModuleNames)"},
  {"file":"autoimporttestutil/fixtures.go","line":223,"text":"\trootDependencies := selectPackagesByName(rootNodeModules, config.DependencyNames)"},
  {"file":"autoimporttestutil/fixtures.go","line":224,"text":"\trootPackageJSON := builder.addRootPackageJSON(monorepoRoot, monorepoName, rootDependencies)"},
  {"file":"autoimporttestutil/fixtures.go","line":225,"text":"\trootDependencyNames := packageNames(rootDependencies)"},
  {"file":"autoimporttestutil/fixtures.go","line":228,"text":"\tpackagesDir := tspath.CombinePaths(monorepoRoot, \"packages\")"},
  {"file":"autoimporttestutil/fixtures.go","line":229,"text":"\tpackageHandles := make([]ProjectHandle, 0, len(config.Packages))"},
  {"file":"autoimporttestutil/fixtures.go","line":230,"text":"\tfor _, pkg := range config.Packages {"},
  {"file":"autoimporttestutil/fixtures.go","line":231,"text":"\t\tpkgDir := tspath.CombinePaths(packagesDir, pkg.Name)"},
  {"file":"autoimporttestutil/fixtures.go","line":232,"text":"\t\tbuilder.AddLocalProject(pkgDir, pkg.FileCount)"},
  {"file":"autoimporttestutil/fixtures.go","line":234,"text":"\t\tvar pkgNodeModules []NodeModulesPackageHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":235,"text":"\t\tif len(pkg.NodeModuleNames) > 0 {"},
  {"file":"autoimporttestutil/fixtures.go","line":236,"text":"\t\t\tpkgNodeModulesDir := tspath.CombinePaths(pkgDir, \"node_modules\")"},
  {"file":"autoimporttestutil/fixtures.go","line":237,"text":"\t\t\tpkgNodeModules = builder.AddNodeModulesPackagesWithNames(pkgNodeModulesDir, pkg.NodeModuleNames)"},
  {"file":"autoimporttestutil/fixtures.go","line":238,"text":"\t\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":240,"text":"\t\tavailableDeps := append(slices.Clone(rootNodeModules), pkgNodeModules...)"},
  {"file":"autoimporttestutil/fixtures.go","line":241,"text":"\t\tselectedDeps := selectPackagesByName(availableDeps, pkg.DependencyNames)"},
  {"file":"autoimporttestutil/fixtures.go","line":242,"text":"\t\tif len(selectedDeps) > 0 {"},
  {"file":"autoimporttestutil/fixtures.go","line":243,"text":"\t\t\tbuilder.AddPackageJSONWithDependenciesNamed(pkgDir, pkg.Name, selectedDeps)"},
  {"file":"autoimporttestutil/fixtures.go","line":244,"text":"\t\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":245,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":248,"text":"\textraHandles := make([]FileHandle, 0, len(config.ExtraFiles))"},
  {"file":"autoimporttestutil/fixtures.go","line":249,"text":"\tfor _, extra := range config.ExtraFiles {"},
  {"file":"autoimporttestutil/fixtures.go","line":250,"text":"\t\tbuilder.AddTextFile(extra.Path, extra.Content)"},
  {"file":"autoimporttestutil/fixtures.go","line":251,"text":"\t\textraHandles = append(extraHandles, FileHandle{fileName: normalizeAbsolutePath(extra.Path), content: extra.Content})"},
  {"file":"autoimporttestutil/fixtures.go","line":252,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":255,"text":"\tfor _, symlink := range config.Symlinks {"},
  {"file":"autoimporttestutil/fixtures.go","line":256,"text":"\t\tbuilder.AddSymlink(symlink.Link, symlink.Target)"},
  {"file":"autoimporttestutil/fixtures.go","line":257,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":260,"text":"\tfor _, pkg := range config.Packages {"},
  {"file":"autoimporttestutil/fixtures.go","line":261,"text":"\t\tpkgDir := tspath.CombinePaths(packagesDir, pkg.Name)"},
  {"file":"autoimporttestutil/fixtures.go","line":262,"text":"\t\tif record, ok := builder.projects[pkgDir]; ok {"},
  {"file":"autoimporttestutil/fixtures.go","line":263,"text":"\t\t\tpackageHandles = append(packageHandles, record.toHandles())"},
  {"file":"autoimporttestutil/fixtures.go","line":264,"text":"\t\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":265,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":267,"text":"\tsession, sessionUtils := projecttestutil.Setup(builder.Files())"},
  {"file":"autoimporttestutil/fixtures.go","line":268,"text":"\tt.Cleanup(session.Close)"},
  {"file":"autoimporttestutil/fixtures.go","line":272,"text":"\tvar rootNodeModulesHandles []NodeModulesPackageHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":273,"text":"\tif rootRecord, ok := builder.projects[monorepoRoot]; ok {"},
  {"file":"autoimporttestutil/fixtures.go","line":274,"text":"\t\trootNodeModulesHandles = rootRecord.nodeModules"},
  {"file":"autoimporttestutil/fixtures.go","line":275,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":277,"text":"\treturn &MonorepoFixture{"},
  {"file":"autoimporttestutil/fixtures.go","line":278,"text":"\t\tsession: session,"},
  {"file":"autoimporttestutil/fixtures.go","line":279,"text":"\t\tutils:   sessionUtils,"},
  {"file":"autoimporttestutil/fixtures.go","line":280,"text":"\t\tmonorepo: MonorepoHandle{"},
  {"file":"autoimporttestutil/fixtures.go","line":281,"text":"\t\t\troot:             monorepoRoot,"},
  {"file":"autoimporttestutil/fixtures.go","line":282,"text":"\t\t\trootNodeModules:  rootNodeModulesHandles,"},
  {"file":"autoimporttestutil/fixtures.go","line":283,"text":"\t\t\trootDependencies: rootDependencyNames,"},
  {"file":"autoimporttestutil/fixtures.go","line":284,"text":"\t\t\tpackages:         packageHandles,"},
  {"file":"autoimporttestutil/fixtures.go","line":285,"text":"\t\t\trootTSConfig:     rootTSConfig,"},
  {"file":"autoimporttestutil/fixtures.go","line":286,"text":"\t\t\trootPackageJSON:  rootPackageJSON,"},
  {"file":"autoimporttestutil/fixtures.go","line":287,"text":"\t\t},"},
  {"file":"autoimporttestutil/fixtures.go","line":288,"text":"\t\textra: extraHandles,"},
  {"file":"autoimporttestutil/fixtures.go","line":289,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":290,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":294,"text":"func SetupLifecycleSession(t *testing.T, projectRoot string, fileCount int) *Fixture {"},
  {"file":"autoimporttestutil/fixtures.go","line":295,"text":"\tt.Helper()"},
  {"file":"autoimporttestutil/fixtures.go","line":296,"text":"\tbuilder := newFileMapBuilder(nil)"},
  {"file":"autoimporttestutil/fixtures.go","line":297,"text":"\tbuilder.AddLocalProject(projectRoot, fileCount)"},
  {"file":"autoimporttestutil/fixtures.go","line":298,"text":"\tnodeModulesDir := tspath.CombinePaths(projectRoot, \"node_modules\")"},
  {"file":"autoimporttestutil/fixtures.go","line":299,"text":"\tdeps := builder.AddNodeModulesPackages(nodeModulesDir, 1)"},
  {"file":"autoimporttestutil/fixtures.go","line":300,"text":"\tbuilder.AddPackageJSONWithDependencies(projectRoot, deps)"},
  {"file":"autoimporttestutil/fixtures.go","line":301,"text":"\tsession, sessionUtils := projecttestutil.Setup(builder.Files())"},
  {"file":"autoimporttestutil/fixtures.go","line":302,"text":"\tt.Cleanup(session.Close)"},
  {"file":"autoimporttestutil/fixtures.go","line":303,"text":"\treturn &Fixture{"},
  {"file":"autoimporttestutil/fixtures.go","line":304,"text":"\t\tsession:  session,"},
  {"file":"autoimporttestutil/fixtures.go","line":305,"text":"\t\tutils:    sessionUtils,"},
  {"file":"autoimporttestutil/fixtures.go","line":306,"text":"\t\tprojects: builder.projectHandles(),"},
  {"file":"autoimporttestutil/fixtures.go","line":307,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":308,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":310,"text":"type fileMapBuilder struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":311,"text":"\tfiles         map[string]any"},
  {"file":"autoimporttestutil/fixtures.go","line":312,"text":"\tnextPackageID int"},
  {"file":"autoimporttestutil/fixtures.go","line":313,"text":"\tnextProjectID int"},
  {"file":"autoimporttestutil/fixtures.go","line":314,"text":"\tprojects      map[string]*projectRecord"},
  {"file":"autoimporttestutil/fixtures.go","line":315,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":317,"text":"type projectRecord struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":318,"text":"\troot         string"},
  {"file":"autoimporttestutil/fixtures.go","line":319,"text":"\tsourceFiles  []projectFile"},
  {"file":"autoimporttestutil/fixtures.go","line":320,"text":"\ttsconfig     FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":321,"text":"\tpackageJSON  *FileHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":322,"text":"\tnodeModules  []NodeModulesPackageHandle"},
  {"file":"autoimporttestutil/fixtures.go","line":323,"text":"\tdependencies []string"},
  {"file":"autoimporttestutil/fixtures.go","line":324,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":326,"text":"type projectFile struct {"},
  {"file":"autoimporttestutil/fixtures.go","line":327,"text":"\tFileName         string"},
  {"file":"autoimporttestutil/fixtures.go","line":328,"text":"\tExportIdentifier string"},
  {"file":"autoimporttestutil/fixtures.go","line":329,"text":"\tContent          string"},
  {"file":"autoimporttestutil/fixtures.go","line":330,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":332,"text":"func newFileMapBuilder(initial map[string]any) *fileMapBuilder {"},
  {"file":"autoimporttestutil/fixtures.go","line":333,"text":"\tb := &fileMapBuilder{"},
  {"file":"autoimporttestutil/fixtures.go","line":334,"text":"\t\tfiles:    make(map[string]any),"},
  {"file":"autoimporttestutil/fixtures.go","line":335,"text":"\t\tprojects: make(map[string]*projectRecord),"},
  {"file":"autoimporttestutil/fixtures.go","line":336,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":337,"text":"\tif len(initial) == 0 {"},
  {"file":"autoimporttestutil/fixtures.go","line":338,"text":"\t\treturn b"},
  {"file":"autoimporttestutil/fixtures.go","line":339,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":340,"text":"\tfor path, content := range initial {"},
  {"file":"autoimporttestutil/fixtures.go","line":341,"text":"\t\tb.files[normalizeAbsolutePath(path)] = content"},
  {"file":"autoimporttestutil/fixtures.go","line":342,"text":"\t}"},
  {"file":"autoimporttestutil/fixtures.go","line":343,"text":"\treturn b"},
  {"file":"autoimporttestutil/fixtures.go","line":344,"text":"}"},
  {"file":"autoimporttestutil/fixtures.go","line":346,"text":"func (b *fileMapBuilder) ensureProjectRecord(root string) *projectRecord {"},
  {"file":"autoimporttestutil/fixtures.go","line":347,"text":"\tif record, ok := b.projects[root]; ok {"},
  {"file":"autoimporttestutil/fixtures.go","line":348,"text":"\t\treturn record"},
];

export function testutilStrictParityLineText(file: string, line: number): string | undefined {
  return testutilStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function testutilStrictParityFiles(): readonly string[] {
  return [...new Set(testutilStrictParitySourceLines.map((entry) => entry.file))].sort();
}
