// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/unicode/utf16.ts","contentHash":"21d4de66f021ba88e7645f379e867020c33435d270ec9883db6a17300adbbde5"}

export function AppendRune(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode/utf16.AppendRune");
}

export function Decode(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode/utf16.Decode");
}

export function RuneLen(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode/utf16.RuneLen");
}
