// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/unicode/utf8.ts","contentHash":"f554f6fce3870f51db8a0b48ef9c0115e14600e5beff4e1936fc2da36caecc75"}

export function DecodeLastRuneInString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode/utf8.DecodeLastRuneInString");
}

export function DecodeRuneInString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode/utf8.DecodeRuneInString");
}

export function RuneCountInString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode/utf8.RuneCountInString");
}

export const RuneError: unknown = undefined as never;

export const RuneSelf: unknown = undefined as never;
