// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/sync/atomic.ts","contentHash":"b9c75d96a4bd4ca08da8856d20cf80bcc62f8cacc27b03a87888957833014471"}

export class Bool {
  readonly __tsgoEmpty?: never;
}

export class Int32 {
  readonly __tsgoEmpty?: never;
}

export class Int64 {
  readonly __tsgoEmpty?: never;
}

export class Uint32 {
  readonly __tsgoEmpty?: never;
}

export class Uint64 {
  readonly __tsgoEmpty?: never;
}
