// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/gotest.tools/v3/assert.ts","contentHash":"cd2daa24d29ea15b8b9a68fb2555cf55bf9c0498a7b69fded9c51336ac1ec50c"}

export function Assert(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.Assert");
}

export function Check(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.Check");
}

export function DeepEqual(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.DeepEqual");
}

export function Equal(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.Equal");
}

export function Error(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.Error");
}

export function ErrorContains(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.ErrorContains");
}

export function NilError(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED gotest.tools/v3/assert.NilError");
}

export interface TestingT {
  readonly __goFacadeName: "gotest.tools/v3/assert.TestingT";
}
