/**
 * Strict TS-Go parity gap map for `project`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const projectStrictParityUpstreamModule = "project";
export const projectStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"api.go","line":1,"text":"package project"},
  {"file":"api.go","line":3,"text":"import ("},
  {"file":"api.go","line":4,"text":"\t\"context\""},
  {"file":"api.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"api.go","line":7,"text":")"},
  {"file":"api.go","line":11,"text":"func (s *Session) APIOpenProject(ctx context.Context, configFileName string, apiFileChanges FileChangeSummary) (*Project, *Snapshot, error) {"},
  {"file":"api.go","line":12,"text":"\ts.snapshotUpdateMu.Lock()"},
  {"file":"api.go","line":13,"text":"\tdefer s.snapshotUpdateMu.Unlock()"},
  {"file":"api.go","line":14,"text":"\ts.cancelScheduledSnapshotUpdate()"},
  {"file":"api.go","line":16,"text":"\tfileChanges, overlays, ataChanges, _ := s.flushChanges(ctx)"},
  {"file":"api.go","line":17,"text":"\tmergeFileChangeSummary(&fileChanges, apiFileChanges)"},
  {"file":"api.go","line":18,"text":"\tnewSnapshot := s.updateSnapshotRef(ctx, overlays, SnapshotChange{"},
  {"file":"api.go","line":19,"text":"\t\tfileChanges: fileChanges,"},
  {"file":"api.go","line":20,"text":"\t\tataChanges:  ataChanges,"},
  {"file":"api.go","line":21,"text":"\t\tapiRequest: &APISnapshotRequest{"},
  {"file":"api.go","line":22,"text":"\t\t\tOpenProjects: collections.NewSetFromItems(configFileName),"},
  {"file":"api.go","line":23,"text":"\t\t},"},
  {"file":"api.go","line":24,"text":"\t})"},
  {"file":"api.go","line":26,"text":"\tif newSnapshot.apiError != nil {"},
  {"file":"api.go","line":27,"text":"\t\treturn nil, newSnapshot, newSnapshot.apiError"},
  {"file":"api.go","line":28,"text":"\t}"},
  {"file":"api.go","line":30,"text":"\tproject := newSnapshot.ProjectCollection.ConfiguredProject(s.toPath(configFileName))"},
  {"file":"api.go","line":31,"text":"\tif project == nil {"},
  {"file":"api.go","line":32,"text":"\t\tpanic(\"OpenProject request returned no error but project not present in snapshot\")"},
  {"file":"api.go","line":33,"text":"\t}"},
  {"file":"api.go","line":35,"text":"\treturn project, newSnapshot, nil"},
  {"file":"api.go","line":36,"text":"}"},
  {"file":"api.go","line":40,"text":"func (s *Session) APIUpdateWithFileChanges(ctx context.Context, apiFileChanges FileChangeSummary) *Snapshot {"},
  {"file":"api.go","line":41,"text":"\ts.snapshotUpdateMu.Lock()"},
  {"file":"api.go","line":42,"text":"\tdefer s.snapshotUpdateMu.Unlock()"},
  {"file":"api.go","line":43,"text":"\ts.cancelScheduledSnapshotUpdate()"},
  {"file":"api.go","line":45,"text":"\tfileChanges, overlays, ataChanges, _ := s.flushChanges(ctx)"},
  {"file":"api.go","line":46,"text":"\tmergeFileChangeSummary(&fileChanges, apiFileChanges)"},
  {"file":"api.go","line":48,"text":"\treturn s.updateSnapshotRef(ctx, overlays, SnapshotChange{"},
  {"file":"api.go","line":49,"text":"\t\tapiRequest:  &APISnapshotRequest{},"},
  {"file":"api.go","line":50,"text":"\t\tfileChanges: fileChanges,"},
  {"file":"api.go","line":51,"text":"\t\tataChanges:  ataChanges,"},
  {"file":"api.go","line":52,"text":"\t})"},
  {"file":"api.go","line":53,"text":"}"},
  {"file":"ata/ata.go","line":1,"text":"package ata"},
  {"file":"ata/ata.go","line":3,"text":"import ("},
  {"file":"ata/ata.go","line":4,"text":"\t\"context\""},
  {"file":"ata/ata.go","line":5,"text":"\t\"errors\""},
  {"file":"ata/ata.go","line":6,"text":"\t\"fmt\""},
  {"file":"ata/ata.go","line":7,"text":"\t\"slices\""},
  {"file":"ata/ata.go","line":8,"text":"\t\"sync\""},
  {"file":"ata/ata.go","line":9,"text":"\t\"sync/atomic\""},
  {"file":"ata/ata.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"ata/ata.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"ata/ata.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/json\""},
  {"file":"ata/ata.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/module\""},
  {"file":"ata/ata.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/project/logging\""},
  {"file":"ata/ata.go","line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/semver\""},
  {"file":"ata/ata.go","line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"ata/ata.go","line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"file":"ata/ata.go","line":19,"text":")"},
  {"file":"ata/ata.go","line":21,"text":"type TypingsInfo struct {"},
  {"file":"ata/ata.go","line":22,"text":"\tTypeAcquisition   *core.TypeAcquisition"},
  {"file":"ata/ata.go","line":23,"text":"\tCompilerOptions   *core.CompilerOptions"},
  {"file":"ata/ata.go","line":24,"text":"\tUnresolvedImports *collections.Set[string]"},
  {"file":"ata/ata.go","line":25,"text":"}"},
  {"file":"ata/ata.go","line":27,"text":"func (ti TypingsInfo) Equals(other TypingsInfo) bool {"},
  {"file":"ata/ata.go","line":28,"text":"\treturn ti.TypeAcquisition.Equals(other.TypeAcquisition) &&"},
  {"file":"ata/ata.go","line":29,"text":"\t\tti.CompilerOptions.GetAllowJS() == other.CompilerOptions.GetAllowJS() &&"},
  {"file":"ata/ata.go","line":30,"text":"\t\tti.UnresolvedImports.Equals(other.UnresolvedImports)"},
  {"file":"ata/ata.go","line":31,"text":"}"},
  {"file":"ata/ata.go","line":33,"text":"type CachedTyping struct {"},
  {"file":"ata/ata.go","line":34,"text":"\tTypingsLocation string"},
  {"file":"ata/ata.go","line":35,"text":"\tVersion         *semver.Version"},
  {"file":"ata/ata.go","line":36,"text":"}"},
  {"file":"ata/ata.go","line":38,"text":"type TypingsInstallerOptions struct {"},
  {"file":"ata/ata.go","line":39,"text":"\tTypingsLocation string"},
  {"file":"ata/ata.go","line":40,"text":"\tThrottleLimit   int"},
  {"file":"ata/ata.go","line":41,"text":"}"},
  {"file":"ata/ata.go","line":43,"text":"type NpmExecutor interface {"},
  {"file":"ata/ata.go","line":44,"text":"\tNpmInstall(cwd string, args []string) ([]byte, error)"},
  {"file":"ata/ata.go","line":45,"text":"}"},
  {"file":"ata/ata.go","line":47,"text":"type TypingsInstallerHost interface {"},
  {"file":"ata/ata.go","line":48,"text":"\tNpmExecutor"},
  {"file":"ata/ata.go","line":49,"text":"\tmodule.ResolutionHost"},
  {"file":"ata/ata.go","line":50,"text":"}"},
  {"file":"ata/ata.go","line":52,"text":"type TypingsInstaller struct {"},
  {"file":"ata/ata.go","line":53,"text":"\ttypingsLocation string"},
  {"file":"ata/ata.go","line":54,"text":"\thost            TypingsInstallerHost"},
  {"file":"ata/ata.go","line":56,"text":"\tinitOnce sync.Once"},
  {"file":"ata/ata.go","line":58,"text":"\tpackageNameToTypingLocation collections.SyncMap[string, *CachedTyping]"},
  {"file":"ata/ata.go","line":59,"text":"\tmissingTypingsSet           collections.SyncMap[string, bool]"},
  {"file":"ata/ata.go","line":61,"text":"\ttypesRegistry map[string]map[string]string"},
  {"file":"ata/ata.go","line":63,"text":"\tinstallRunCount      atomic.Int32"},
  {"file":"ata/ata.go","line":64,"text":"\tconcurrencySemaphore chan struct{}"},
  {"file":"ata/ata.go","line":65,"text":"}"},
  {"file":"ata/ata.go","line":67,"text":"func NewTypingsInstaller(options *TypingsInstallerOptions, host TypingsInstallerHost) *TypingsInstaller {"},
  {"file":"ata/ata.go","line":68,"text":"\treturn &TypingsInstaller{"},
  {"file":"ata/ata.go","line":69,"text":"\t\ttypingsLocation:      options.TypingsLocation,"},
  {"file":"ata/ata.go","line":70,"text":"\t\thost:                 host,"},
  {"file":"ata/ata.go","line":71,"text":"\t\tconcurrencySemaphore: make(chan struct{}, options.ThrottleLimit),"},
  {"file":"ata/ata.go","line":72,"text":"\t}"},
  {"file":"ata/ata.go","line":73,"text":"}"},
  {"file":"ata/ata.go","line":75,"text":"func (ti *TypingsInstaller) IsKnownTypesPackageName(projectID tspath.Path, name string, fs vfs.FS, logger logging.Logger) bool {"},
  {"file":"ata/ata.go","line":77,"text":"\tvalidationResult, _, _ := ValidatePackageName(name)"},
  {"file":"ata/ata.go","line":78,"text":"\tif validationResult != NameOk {"},
  {"file":"ata/ata.go","line":79,"text":"\t\treturn false"},
  {"file":"ata/ata.go","line":80,"text":"\t}"},
  {"file":"ata/ata.go","line":82,"text":"\tti.init(string(projectID), fs, logger)"},
  {"file":"ata/ata.go","line":83,"text":"\t_, ok := ti.typesRegistry[name]"},
  {"file":"ata/ata.go","line":84,"text":"\treturn ok"},
  {"file":"ata/ata.go","line":85,"text":"}"},
  {"file":"ata/ata.go","line":88,"text":"const tsVersionToUse = \"latest\""},
  {"file":"ata/ata.go","line":90,"text":"type TypingsInstallRequest struct {"},
  {"file":"ata/ata.go","line":91,"text":"\tProjectID        tspath.Path"},
  {"file":"ata/ata.go","line":92,"text":"\tTypingsInfo      *TypingsInfo"},
  {"file":"ata/ata.go","line":93,"text":"\tFileNames        []string"},
  {"file":"ata/ata.go","line":94,"text":"\tProjectRootPath  string"},
  {"file":"ata/ata.go","line":95,"text":"\tCompilerOptions  *core.CompilerOptions"},
  {"file":"ata/ata.go","line":96,"text":"\tCurrentDirectory string"},
  {"file":"ata/ata.go","line":97,"text":"\tGetScriptKind    func(string) core.ScriptKind"},
  {"file":"ata/ata.go","line":98,"text":"\tFS               vfs.FS"},
  {"file":"ata/ata.go","line":99,"text":"\tLogger           logging.Logger"},
  {"file":"ata/ata.go","line":100,"text":"}"},
  {"file":"ata/ata.go","line":102,"text":"type TypingsInstallResult struct {"},
  {"file":"ata/ata.go","line":103,"text":"\tTypingsFiles []string"},
  {"file":"ata/ata.go","line":104,"text":"\tFilesToWatch []string"},
  {"file":"ata/ata.go","line":105,"text":"}"},
  {"file":"ata/ata.go","line":107,"text":"func (ti *TypingsInstaller) InstallTypings(request *TypingsInstallRequest) (*TypingsInstallResult, error) {"},
  {"file":"ata/ata.go","line":108,"text":"\tresult, err := ti.discoverAndInstallTypings(request)"},
  {"file":"ata/ata.go","line":109,"text":"\tif err == nil {"},
  {"file":"ata/ata.go","line":110,"text":"\t\tslices.Sort(result.TypingsFiles)"},
  {"file":"ata/ata.go","line":111,"text":"\t\tslices.Sort(result.FilesToWatch)"},
  {"file":"ata/ata.go","line":112,"text":"\t\trequest.Logger.Log(\"ATA:: Got install request for: \" + string(request.ProjectID))"},
  {"file":"ata/ata.go","line":113,"text":"\t}"},
  {"file":"ata/ata.go","line":114,"text":"\treturn result, err"},
  {"file":"ata/ata.go","line":115,"text":"}"},
  {"file":"ata/ata.go","line":117,"text":"func (ti *TypingsInstaller) discoverAndInstallTypings(request *TypingsInstallRequest) (*TypingsInstallResult, error) {"},
  {"file":"ata/ata.go","line":118,"text":"\tti.init(string(request.ProjectID), request.FS, request.Logger)"},
  {"file":"ata/ata.go","line":120,"text":"\tcachedTypingPaths, newTypingNames, filesToWatch := DiscoverTypings("},
  {"file":"ata/ata.go","line":121,"text":"\t\trequest.FS,"},
  {"file":"ata/ata.go","line":122,"text":"\t\trequest.Logger,"},
  {"file":"ata/ata.go","line":123,"text":"\t\trequest.TypingsInfo,"},
  {"file":"ata/ata.go","line":124,"text":"\t\trequest.FileNames,"},
  {"file":"ata/ata.go","line":125,"text":"\t\trequest.ProjectRootPath,"},
  {"file":"ata/ata.go","line":126,"text":"\t\t&ti.packageNameToTypingLocation,"},
  {"file":"ata/ata.go","line":127,"text":"\t\tti.typesRegistry,"},
  {"file":"ata/ata.go","line":128,"text":"\t)"},
  {"file":"ata/ata.go","line":130,"text":"\trequestId := ti.installRunCount.Add(1)"},
  {"file":"ata/ata.go","line":132,"text":"\tif len(newTypingNames) > 0 {"},
  {"file":"ata/ata.go","line":133,"text":"\t\tfilteredTypings := ti.filterTypings(request.ProjectID, request.Logger, newTypingNames)"},
  {"file":"ata/ata.go","line":134,"text":"\t\tif len(filteredTypings) != 0 {"},
  {"file":"ata/ata.go","line":135,"text":"\t\t\ttypingsFiles, err := ti.installTypings(request.ProjectID, request.TypingsInfo, requestId, cachedTypingPaths, filteredTypings, request.Logger)"},
  {"file":"ata/ata.go","line":136,"text":"\t\t\tif err != nil {"},
  {"file":"ata/ata.go","line":137,"text":"\t\t\t\treturn nil, err"},
  {"file":"ata/ata.go","line":138,"text":"\t\t\t}"},
  {"file":"ata/ata.go","line":139,"text":"\t\t\treturn &TypingsInstallResult{"},
  {"file":"ata/ata.go","line":140,"text":"\t\t\t\tTypingsFiles: typingsFiles,"},
  {"file":"ata/ata.go","line":141,"text":"\t\t\t\tFilesToWatch: filesToWatch,"},
  {"file":"ata/ata.go","line":142,"text":"\t\t\t}, nil"},
  {"file":"ata/ata.go","line":143,"text":"\t\t}"},
  {"file":"ata/ata.go","line":144,"text":"\t\trequest.Logger.Log(\"ATA:: All typings are known to be missing or invalid - no need to install more typings\")"},
  {"file":"ata/ata.go","line":145,"text":"\t} else {"},
  {"file":"ata/ata.go","line":146,"text":"\t\trequest.Logger.Log(\"ATA:: No new typings were requested as a result of typings discovery\")"},
  {"file":"ata/ata.go","line":147,"text":"\t}"},
  {"file":"ata/ata.go","line":149,"text":"\treturn &TypingsInstallResult{"},
  {"file":"ata/ata.go","line":150,"text":"\t\tTypingsFiles: cachedTypingPaths,"},
  {"file":"ata/ata.go","line":151,"text":"\t\tFilesToWatch: filesToWatch,"},
  {"file":"ata/ata.go","line":152,"text":"\t}, nil"},
  {"file":"ata/ata.go","line":155,"text":"}"},
  {"file":"ata/ata.go","line":157,"text":"func (ti *TypingsInstaller) installTypings("},
  {"file":"ata/ata.go","line":158,"text":"\tprojectID tspath.Path,"},
  {"file":"ata/ata.go","line":159,"text":"\ttypingsInfo *TypingsInfo,"},
  {"file":"ata/ata.go","line":160,"text":"\trequestID int32,"},
  {"file":"ata/ata.go","line":161,"text":"\tcurrentlyCachedTypings []string,"},
  {"file":"ata/ata.go","line":162,"text":"\tfilteredTypings []string,"},
  {"file":"ata/ata.go","line":163,"text":"\tlogger logging.Logger,"},
  {"file":"ata/ata.go","line":164,"text":") ([]string, error) {"},
  {"file":"ata/ata.go","line":181,"text":"\tscopedTypings := make([]string, len(filteredTypings))"},
  {"file":"ata/ata.go","line":182,"text":"\tfor i, packageName := range filteredTypings {"},
  {"file":"ata/ata.go","line":183,"text":"\t\tscopedTypings[i] = fmt.Sprintf(\"@types/%s@%s\", packageName, tsVersionToUse) // @tscore.VersionMajorMinor) // This is normally @tsVersionMajorMinor but for now lets use latest"},
  {"file":"ata/ata.go","line":184,"text":"\t}"},
  {"file":"ata/ata.go","line":186,"text":"\tif packageNames, ok := ti.installWorker(projectID, requestID, scopedTypings, logger); ok {"},
  {"file":"ata/ata.go","line":187,"text":"\t\tlogger.Log(fmt.Sprintf(\"ATA:: Installed typings %v\", packageNames))"},
  {"file":"ata/ata.go","line":188,"text":"\t\tvar installedTypingFiles []string"},
  {"file":"ata/ata.go","line":189,"text":"\t\tresolver := module.NewResolver(ti.host, &core.CompilerOptions{ModuleResolution: core.ModuleResolutionKindNodeNext}, \"\", \"\")"},
  {"file":"ata/ata.go","line":190,"text":"\t\tfor _, packageName := range filteredTypings {"},
  {"file":"ata/ata.go","line":191,"text":"\t\t\ttypingFile := ti.typingToFileName(resolver, packageName)"},
  {"file":"ata/ata.go","line":192,"text":"\t\t\tif typingFile == \"\" {"},
  {"file":"ata/ata.go","line":193,"text":"\t\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: Failed to find typing file for package '%s'\", packageName))"},
  {"file":"ata/ata.go","line":194,"text":"\t\t\t\tti.missingTypingsSet.Store(packageName, true)"},
  {"file":"ata/ata.go","line":195,"text":"\t\t\t\tcontinue"},
  {"file":"ata/ata.go","line":196,"text":"\t\t\t}"},
  {"file":"ata/ata.go","line":199,"text":"\t\t\tdistTags := ti.typesRegistry[packageName]"},
  {"file":"ata/ata.go","line":200,"text":"\t\t\tuseVersion, ok := distTags[\"ts\"+core.VersionMajorMinor()]"},
  {"file":"ata/ata.go","line":201,"text":"\t\t\tif !ok {"},
  {"file":"ata/ata.go","line":202,"text":"\t\t\t\tuseVersion = distTags[\"latest\"]"},
  {"file":"ata/ata.go","line":203,"text":"\t\t\t}"},
  {"file":"ata/ata.go","line":204,"text":"\t\t\tnewVersion := semver.MustParse(useVersion)"},
  {"file":"ata/ata.go","line":205,"text":"\t\t\tnewTyping := &CachedTyping{TypingsLocation: typingFile, Version: &newVersion}"},
  {"file":"ata/ata.go","line":206,"text":"\t\t\tti.packageNameToTypingLocation.Store(packageName, newTyping)"},
  {"file":"ata/ata.go","line":207,"text":"\t\t\tinstalledTypingFiles = append(installedTypingFiles, typingFile)"},
  {"file":"ata/ata.go","line":208,"text":"\t\t}"},
  {"file":"ata/ata.go","line":209,"text":"\t\tlogger.Log(fmt.Sprintf(\"ATA:: Installed typing files %v\", installedTypingFiles))"},
  {"file":"ata/ata.go","line":211,"text":"\t\treturn append(currentlyCachedTypings, installedTypingFiles...), nil"},
  {"file":"ata/ata.go","line":212,"text":"\t}"},
  {"file":"ata/ata.go","line":216,"text":"\tlogger.Log(fmt.Sprintf(\"ATA:: install request failed, marking packages as missing to prevent repeated requests: %v\", filteredTypings))"},
  {"file":"ata/ata.go","line":217,"text":"\tfor _, typing := range filteredTypings {"},
  {"file":"ata/ata.go","line":218,"text":"\t\tti.missingTypingsSet.Store(typing, true)"},
  {"file":"ata/ata.go","line":219,"text":"\t}"},
  {"file":"ata/ata.go","line":221,"text":"\treturn nil, errors.New(\"npm install failed\")"},
  {"file":"ata/ata.go","line":254,"text":"}"},
  {"file":"ata/ata.go","line":256,"text":"func (ti *TypingsInstaller) installWorker("},
  {"file":"ata/ata.go","line":257,"text":"\tprojectID tspath.Path,"},
  {"file":"ata/ata.go","line":258,"text":"\trequestId int32,"},
  {"file":"ata/ata.go","line":259,"text":"\tpackageNames []string,"},
  {"file":"ata/ata.go","line":260,"text":"\tlogger logging.Logger,"},
  {"file":"ata/ata.go","line":261,"text":") ([]string, bool) {"},
  {"file":"ata/ata.go","line":262,"text":"\tlogger.Log(fmt.Sprintf(\"ATA:: #%d with cwd: %s arguments: %v\", requestId, ti.typingsLocation, packageNames))"},
  {"file":"ata/ata.go","line":263,"text":"\tctx := context.Background()"},
  {"file":"ata/ata.go","line":264,"text":"\terr := installNpmPackages(ctx, packageNames, ti.concurrencySemaphore, func(packageNames []string) error {"},
  {"file":"ata/ata.go","line":265,"text":"\t\tvar npmArgs []string"},
  {"file":"ata/ata.go","line":266,"text":"\t\tnpmArgs = append(npmArgs, \"install\", \"--ignore-scripts\")"},
  {"file":"ata/ata.go","line":267,"text":"\t\tnpmArgs = append(npmArgs, packageNames...)"},
  {"file":"ata/ata.go","line":268,"text":"\t\tnpmArgs = append(npmArgs, \"--save-dev\", \"--user-agent=\\\"typesInstaller/\"+core.Version()+\"\\\"\")"},
  {"file":"ata/ata.go","line":269,"text":"\t\toutput, err := ti.host.NpmInstall(ti.typingsLocation, npmArgs)"},
  {"file":"ata/ata.go","line":270,"text":"\t\tif err != nil {"},
  {"file":"ata/ata.go","line":271,"text":"\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: Output is: %s\", output))"},
  {"file":"ata/ata.go","line":272,"text":"\t\t\treturn err"},
  {"file":"ata/ata.go","line":273,"text":"\t\t}"},
  {"file":"ata/ata.go","line":274,"text":"\t\treturn nil"},
  {"file":"ata/ata.go","line":275,"text":"\t})"},
  {"file":"ata/ata.go","line":276,"text":"\tlogger.Log(fmt.Sprintf(\"TI:: npm install #%d completed\", requestId))"},
  {"file":"ata/ata.go","line":277,"text":"\treturn packageNames, err == nil"},
  {"file":"ata/ata.go","line":278,"text":"}"},
  {"file":"ata/ata.go","line":280,"text":"func installNpmPackages("},
  {"file":"ata/ata.go","line":281,"text":"\tctx context.Context,"},
  {"file":"ata/ata.go","line":282,"text":"\tpackageNames []string,"},
  {"file":"ata/ata.go","line":283,"text":"\tconcurrencySemaphore chan struct{},"},
  {"file":"ata/ata.go","line":284,"text":"\tinstallPackages func(packages []string) error,"},
  {"file":"ata/ata.go","line":285,"text":") error {"},
  {"file":"ata/ata.go","line":286,"text":"\ttg := core.NewThrottleGroup(ctx, concurrencySemaphore)"},
  {"file":"ata/ata.go","line":288,"text":"\tcurrentCommandStart := 0"},
  {"file":"ata/ata.go","line":289,"text":"\tcurrentCommandEnd := 0"},
  {"file":"ata/ata.go","line":290,"text":"\tcurrentCommandSize := 100"},
  {"file":"ata/ata.go","line":292,"text":"\tfor _, packageName := range packageNames {"},
  {"file":"ata/ata.go","line":293,"text":"\t\tcurrentCommandSize = currentCommandSize + len(packageName) + 1"},
  {"file":"ata/ata.go","line":294,"text":"\t\tif currentCommandSize < 8000 {"},
  {"file":"ata/ata.go","line":295,"text":"\t\t\tcurrentCommandEnd++"},
  {"file":"ata/ata.go","line":296,"text":"\t\t} else {"},
  {"file":"ata/ata.go","line":297,"text":"\t\t\tpackages := packageNames[currentCommandStart:currentCommandEnd]"},
  {"file":"ata/ata.go","line":298,"text":"\t\t\ttg.Go(func() error {"},
  {"file":"ata/ata.go","line":299,"text":"\t\t\t\treturn installPackages(packages)"},
  {"file":"ata/ata.go","line":300,"text":"\t\t\t})"},
  {"file":"ata/ata.go","line":301,"text":"\t\t\tcurrentCommandStart = currentCommandEnd"},
  {"file":"ata/ata.go","line":302,"text":"\t\t\tcurrentCommandSize = 100 + len(packageName) + 1"},
  {"file":"ata/ata.go","line":303,"text":"\t\t\tcurrentCommandEnd++"},
  {"file":"ata/ata.go","line":304,"text":"\t\t}"},
  {"file":"ata/ata.go","line":305,"text":"\t}"},
  {"file":"ata/ata.go","line":308,"text":"\tif currentCommandStart < len(packageNames) {"},
  {"file":"ata/ata.go","line":309,"text":"\t\tpackages := packageNames[currentCommandStart:currentCommandEnd]"},
  {"file":"ata/ata.go","line":310,"text":"\t\ttg.Go(func() error {"},
  {"file":"ata/ata.go","line":311,"text":"\t\t\treturn installPackages(packages)"},
  {"file":"ata/ata.go","line":312,"text":"\t\t})"},
  {"file":"ata/ata.go","line":313,"text":"\t}"},
  {"file":"ata/ata.go","line":315,"text":"\treturn tg.Wait()"},
  {"file":"ata/ata.go","line":316,"text":"}"},
  {"file":"ata/ata.go","line":318,"text":"func (ti *TypingsInstaller) filterTypings("},
  {"file":"ata/ata.go","line":319,"text":"\tprojectID tspath.Path,"},
  {"file":"ata/ata.go","line":320,"text":"\tlogger logging.Logger,"},
  {"file":"ata/ata.go","line":321,"text":"\ttypingsToInstall []string,"},
  {"file":"ata/ata.go","line":322,"text":") []string {"},
  {"file":"ata/ata.go","line":323,"text":"\tvar result []string"},
  {"file":"ata/ata.go","line":324,"text":"\tfor _, typing := range typingsToInstall {"},
  {"file":"ata/ata.go","line":325,"text":"\t\ttypingKey := module.MangleScopedPackageName(typing)"},
  {"file":"ata/ata.go","line":326,"text":"\t\tif _, ok := ti.missingTypingsSet.Load(typingKey); ok {"},
  {"file":"ata/ata.go","line":327,"text":"\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: '%s':: '%s' is in missingTypingsSet - skipping...\", typing, typingKey))"},
  {"file":"ata/ata.go","line":328,"text":"\t\t\tcontinue"},
  {"file":"ata/ata.go","line":329,"text":"\t\t}"},
  {"file":"ata/ata.go","line":330,"text":"\t\tvalidationResult, name, isScopeName := ValidatePackageName(typing)"},
  {"file":"ata/ata.go","line":331,"text":"\t\tif validationResult != NameOk {"},
  {"file":"ata/ata.go","line":333,"text":"\t\t\tti.missingTypingsSet.Store(typingKey, true)"},
  {"file":"ata/ata.go","line":334,"text":"\t\t\tlogger.Log(\"ATA:: \" + renderPackageNameValidationFailure(typing, validationResult, name, isScopeName))"},
  {"file":"ata/ata.go","line":335,"text":"\t\t\tcontinue"},
  {"file":"ata/ata.go","line":336,"text":"\t\t}"},
  {"file":"ata/ata.go","line":337,"text":"\t\ttypesRegistryEntry, ok := ti.typesRegistry[typingKey]"},
  {"file":"ata/ata.go","line":338,"text":"\t\tif !ok {"},
  {"file":"ata/ata.go","line":339,"text":"\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: '%s':: Entry for package '%s' does not exist in local types registry - skipping...\", typing, typingKey))"},
  {"file":"ata/ata.go","line":340,"text":"\t\t\tcontinue"},
  {"file":"ata/ata.go","line":341,"text":"\t\t}"},
  {"file":"ata/ata.go","line":342,"text":"\t\tif typingLocation, ok := ti.packageNameToTypingLocation.Load(typingKey); ok && isTypingUpToDate(typingLocation, typesRegistryEntry) {"},
  {"file":"ata/ata.go","line":343,"text":"\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: '%s':: '%s' already has an up-to-date typing - skipping...\", typing, typingKey))"},
  {"file":"ata/ata.go","line":344,"text":"\t\t\tcontinue"},
  {"file":"ata/ata.go","line":345,"text":"\t\t}"},
  {"file":"ata/ata.go","line":346,"text":"\t\tresult = append(result, typingKey)"},
  {"file":"ata/ata.go","line":347,"text":"\t}"},
  {"file":"ata/ata.go","line":348,"text":"\treturn result"},
  {"file":"ata/ata.go","line":349,"text":"}"},
  {"file":"ata/ata.go","line":351,"text":"func (ti *TypingsInstaller) init(projectID string, fs vfs.FS, logger logging.Logger) {"},
  {"file":"ata/ata.go","line":352,"text":"\tti.initOnce.Do(func() {"},
  {"file":"ata/ata.go","line":353,"text":"\t\tlogger.Log(\"ATA:: Global cache location '\" + ti.typingsLocation + \"'\") //, safe file path '\" + safeListPath + \"', types map path '\" + typesMapLocation + \"`\")"},
  {"file":"ata/ata.go","line":354,"text":"\t\tti.processCacheLocation(projectID, fs, logger)"},
  {"file":"ata/ata.go","line":367,"text":"\t\tti.ensureTypingsLocationExists(fs, logger)"},
  {"file":"ata/ata.go","line":368,"text":"\t\tlogger.Log(\"ATA:: Updating types-registry@latest npm package...\")"},
  {"file":"ata/ata.go","line":369,"text":"\t\tif _, err := ti.host.NpmInstall(ti.typingsLocation, []string{\"install\", \"--ignore-scripts\", \"types-registry@latest\"}); err == nil {"},
  {"file":"ata/ata.go","line":370,"text":"\t\t\tlogger.Log(\"ATA:: Updated types-registry npm package\")"},
  {"file":"ata/ata.go","line":371,"text":"\t\t} else {"},
  {"file":"ata/ata.go","line":372,"text":"\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: Error updating types-registry package: %v\", err))"},
  {"file":"ata/ata.go","line":386,"text":"\t\t}"},
  {"file":"ata/ata.go","line":388,"text":"\t\tti.typesRegistry = ti.loadTypesRegistryFile(fs, logger)"},
  {"file":"ata/ata.go","line":389,"text":"\t})"},
  {"file":"ata/ata.go","line":390,"text":"}"},
  {"file":"ata/ata.go","line":392,"text":"type npmConfig struct {"},
  {"file":"ata/ata.go","line":393,"text":"\tDevDependencies map[string]any `json:\"devDependencies\"`"},
  {"file":"ata/ata.go","line":394,"text":"}"},
  {"file":"ata/ata.go","line":396,"text":"type npmDependecyEntry struct {"},
  {"file":"ata/ata.go","line":397,"text":"\tVersion string `json:\"version\"`"},
  {"file":"ata/ata.go","line":398,"text":"}"},
  {"file":"ata/ata.go","line":399,"text":"type npmLock struct {"},
  {"file":"ata/ata.go","line":400,"text":"\tDependencies map[string]npmDependecyEntry `json:\"dependencies\"`"},
  {"file":"ata/ata.go","line":401,"text":"\tPackages     map[string]npmDependecyEntry `json:\"packages\"`"},
  {"file":"ata/ata.go","line":402,"text":"}"},
  {"file":"ata/ata.go","line":404,"text":"func (ti *TypingsInstaller) processCacheLocation(projectID string, fs vfs.FS, logger logging.Logger) {"},
  {"file":"ata/ata.go","line":405,"text":"\tlogger.Log(\"ATA:: Processing cache location \" + ti.typingsLocation)"},
  {"file":"ata/ata.go","line":406,"text":"\tpackageJson := tspath.CombinePaths(ti.typingsLocation, \"package.json\")"},
  {"file":"ata/ata.go","line":407,"text":"\tpackageLockJson := tspath.CombinePaths(ti.typingsLocation, \"package-lock.json\")"},
  {"file":"ata/ata.go","line":408,"text":"\tlogger.Log(\"ATA:: Trying to find '\" + packageJson + \"'...\")"},
  {"file":"ata/ata.go","line":409,"text":"\tif fs.FileExists(packageJson) && fs.FileExists((packageLockJson)) {"},
  {"file":"ata/ata.go","line":410,"text":"\t\tvar npmConfig npmConfig"},
  {"file":"ata/ata.go","line":411,"text":"\t\tnpmConfigContents := parseNpmConfigOrLock(fs, logger, packageJson, &npmConfig)"},
  {"file":"ata/ata.go","line":412,"text":"\t\tvar npmLock npmLock"},
  {"file":"ata/ata.go","line":413,"text":"\t\tnpmLockContents := parseNpmConfigOrLock(fs, logger, packageLockJson, &npmLock)"},
  {"file":"ata/ata.go","line":415,"text":"\t\tlogger.Log(\"ATA:: Loaded content of \" + packageJson + \": \" + npmConfigContents)"},
  {"file":"ata/ata.go","line":416,"text":"\t\tlogger.Log(\"ATA:: Loaded content of \" + packageLockJson + \": \" + npmLockContents)"},
  {"file":"ata/ata.go","line":419,"text":"\t\tresolver := module.NewResolver(ti.host, &core.CompilerOptions{ModuleResolution: core.ModuleResolutionKindNodeNext}, \"\", \"\")"},
  {"file":"ata/ata.go","line":420,"text":"\t\tif npmConfig.DevDependencies != nil && (npmLock.Packages != nil || npmLock.Dependencies != nil) {"},
  {"file":"ata/ata.go","line":421,"text":"\t\t\tfor key := range npmConfig.DevDependencies {"},
  {"file":"ata/ata.go","line":422,"text":"\t\t\t\tnpmLockValue, npmLockValueExists := npmLock.Packages[\"node_modules/\"+key]"},
  {"file":"ata/ata.go","line":423,"text":"\t\t\t\tif !npmLockValueExists {"},
  {"file":"ata/ata.go","line":424,"text":"\t\t\t\t\tnpmLockValue, npmLockValueExists = npmLock.Dependencies[key]"},
  {"file":"ata/ata.go","line":425,"text":"\t\t\t\t}"},
  {"file":"ata/ata.go","line":426,"text":"\t\t\t\tif !npmLockValueExists {"},
  {"file":"ata/ata.go","line":428,"text":"\t\t\t\t\tcontinue"},
  {"file":"ata/ata.go","line":429,"text":"\t\t\t\t}"},
  {"file":"ata/ata.go","line":431,"text":"\t\t\t\tpackageName := tspath.GetBaseFileName(key)"},
  {"file":"ata/ata.go","line":432,"text":"\t\t\t\tif packageName == \"\" {"},
  {"file":"ata/ata.go","line":433,"text":"\t\t\t\t\tcontinue"},
  {"file":"ata/ata.go","line":434,"text":"\t\t\t\t}"},
  {"file":"ata/ata.go","line":435,"text":"\t\t\t\ttypingFile := ti.typingToFileName(resolver, packageName)"},
  {"file":"ata/ata.go","line":436,"text":"\t\t\t\tif typingFile == \"\" {"},
  {"file":"ata/ata.go","line":437,"text":"\t\t\t\t\tti.missingTypingsSet.Store(packageName, true)"},
  {"file":"ata/ata.go","line":438,"text":"\t\t\t\t\tcontinue"},
  {"file":"ata/ata.go","line":439,"text":"\t\t\t\t}"},
  {"file":"ata/ata.go","line":440,"text":"\t\t\t\tif existingTypingFile, existingTypingsFilePresent := ti.packageNameToTypingLocation.Load(packageName); existingTypingsFilePresent {"},
  {"file":"ata/ata.go","line":441,"text":"\t\t\t\t\tif existingTypingFile.TypingsLocation == typingFile {"},
  {"file":"ata/ata.go","line":442,"text":"\t\t\t\t\t\tcontinue"},
  {"file":"ata/ata.go","line":443,"text":"\t\t\t\t\t}"},
  {"file":"ata/ata.go","line":444,"text":"\t\t\t\t\tlogger.Log(\"ATA:: New typing for package \" + packageName + \" from \" + typingFile + \" conflicts with existing typing file \" + existingTypingFile.TypingsLocation)"},
  {"file":"ata/ata.go","line":445,"text":"\t\t\t\t}"},
  {"file":"ata/ata.go","line":446,"text":"\t\t\t\tlogger.Log(\"ATA:: Adding entry into typings cache: \" + packageName + \" => \" + typingFile)"},
  {"file":"ata/ata.go","line":447,"text":"\t\t\t\tversion := npmLockValue.Version"},
  {"file":"ata/ata.go","line":448,"text":"\t\t\t\tif version == \"\" {"},
  {"file":"ata/ata.go","line":449,"text":"\t\t\t\t\tcontinue"},
  {"file":"ata/ata.go","line":450,"text":"\t\t\t\t}"},
  {"file":"ata/ata.go","line":451,"text":"\t\t\t\tnewVersion := semver.MustParse(version)"},
  {"file":"ata/ata.go","line":452,"text":"\t\t\t\tnewTyping := &CachedTyping{TypingsLocation: typingFile, Version: &newVersion}"},
  {"file":"ata/ata.go","line":453,"text":"\t\t\t\tti.packageNameToTypingLocation.Store(packageName, newTyping)"},
  {"file":"ata/ata.go","line":454,"text":"\t\t\t}"},
  {"file":"ata/ata.go","line":455,"text":"\t\t}"},
  {"file":"ata/ata.go","line":456,"text":"\t}"},
  {"file":"ata/ata.go","line":457,"text":"\tlogger.Log(\"ATA:: Finished processing cache location \" + ti.typingsLocation)"},
  {"file":"ata/ata.go","line":458,"text":"}"},
  {"file":"ata/ata.go","line":460,"text":"func parseNpmConfigOrLock[T npmConfig | npmLock](fs vfs.FS, logger logging.Logger, location string, config *T) string {"},
  {"file":"ata/ata.go","line":461,"text":"\tcontents, _ := fs.ReadFile(location)"},
  {"file":"ata/ata.go","line":462,"text":"\t_ = json.Unmarshal([]byte(contents), config)"},
  {"file":"ata/ata.go","line":463,"text":"\treturn contents"},
  {"file":"ata/ata.go","line":464,"text":"}"},
  {"file":"ata/ata.go","line":466,"text":"func (ti *TypingsInstaller) ensureTypingsLocationExists(fs vfs.FS, logger logging.Logger) {"},
  {"file":"ata/ata.go","line":467,"text":"\tnpmConfigPath := tspath.CombinePaths(ti.typingsLocation, \"package.json\")"},
  {"file":"ata/ata.go","line":468,"text":"\tlogger.Log(\"ATA:: Npm config file: \" + npmConfigPath)"},
  {"file":"ata/ata.go","line":470,"text":"\tif !fs.FileExists(npmConfigPath) {"},
  {"file":"ata/ata.go","line":471,"text":"\t\tlogger.Log(fmt.Sprintf(\"ATA:: Npm config file: '%s' is missing, creating new one...\", npmConfigPath))"},
  {"file":"ata/ata.go","line":472,"text":"\t\terr := fs.WriteFile(npmConfigPath, \"{ \\\"private\\\": true }\")"},
  {"file":"ata/ata.go","line":473,"text":"\t\tif err != nil {"},
  {"file":"ata/ata.go","line":474,"text":"\t\t\tlogger.Log(fmt.Sprintf(\"ATA:: Npm config file write failed: %v\", err))"},
  {"file":"ata/ata.go","line":475,"text":"\t\t}"},
  {"file":"ata/ata.go","line":476,"text":"\t}"},
  {"file":"ata/ata.go","line":477,"text":"}"},
  {"file":"ata/ata.go","line":479,"text":"func (ti *TypingsInstaller) typingToFileName(resolver *module.Resolver, packageName string) string {"},
  {"file":"ata/ata.go","line":480,"text":"\tresult, _ := resolver.ResolveModuleName(packageName, tspath.CombinePaths(ti.typingsLocation, \"index.d.ts\"), core.ModuleKindNone, nil)"},
  {"file":"ata/ata.go","line":481,"text":"\treturn result.ResolvedFileName"},
  {"file":"ata/ata.go","line":482,"text":"}"},
  {"file":"ata/ata.go","line":484,"text":"func (ti *TypingsInstaller) loadTypesRegistryFile(fs vfs.FS, logger logging.Logger) map[string]map[string]string {"},
  {"file":"ata/ata.go","line":485,"text":"\ttypesRegistryFile := tspath.CombinePaths(ti.typingsLocation, \"node_modules/types-registry/index.json\")"},
  {"file":"ata/ata.go","line":486,"text":"\ttypesRegistryFileContents, ok := fs.ReadFile(typesRegistryFile)"},
  {"file":"ata/ata.go","line":487,"text":"\tif ok {"},
  {"file":"ata/ata.go","line":488,"text":"\t\tvar entries map[string]map[string]map[string]string"},
  {"file":"ata/ata.go","line":489,"text":"\t\terr := json.Unmarshal([]byte(typesRegistryFileContents), &entries)"},
  {"file":"ata/ata.go","line":490,"text":"\t\tif err == nil {"},
  {"file":"ata/ata.go","line":491,"text":"\t\t\tif typesRegistry, ok := entries[\"entries\"]; ok {"},
  {"file":"ata/ata.go","line":492,"text":"\t\t\t\treturn typesRegistry"},
  {"file":"ata/ata.go","line":493,"text":"\t\t\t}"},
  {"file":"ata/ata.go","line":494,"text":"\t\t}"},
  {"file":"ata/ata.go","line":495,"text":"\t\tlogger.Log(fmt.Sprintf(\"ATA:: Error when loading types registry file '%s': %v\", typesRegistryFile, err))"},
  {"file":"ata/ata.go","line":496,"text":"\t} else {"},
  {"file":"ata/ata.go","line":497,"text":"\t\tlogger.Log(fmt.Sprintf(\"ATA:: Error reading types registry file '%s'\", typesRegistryFile))"},
  {"file":"ata/ata.go","line":498,"text":"\t}"},
  {"file":"ata/ata.go","line":499,"text":"\treturn map[string]map[string]string{}"},
  {"file":"ata/ata.go","line":500,"text":"}"},
  {"file":"ata/discovertypings.go","line":1,"text":"package ata"},
  {"file":"ata/discovertypings.go","line":3,"text":"import ("},
  {"file":"ata/discovertypings.go","line":4,"text":"\t\"fmt\""},
  {"file":"ata/discovertypings.go","line":5,"text":"\t\"maps\""},
  {"file":"ata/discovertypings.go","line":6,"text":"\t\"slices\""},
  {"file":"ata/discovertypings.go","line":7,"text":"\t\"unicode/utf8\""},
  {"file":"ata/discovertypings.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"ata/discovertypings.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"ata/discovertypings.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/json\""},
  {"file":"ata/discovertypings.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/packagejson\""},
  {"file":"ata/discovertypings.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/project/logging\""},
  {"file":"ata/discovertypings.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/semver\""},
  {"file":"ata/discovertypings.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"ata/discovertypings.go","line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"file":"ata/discovertypings.go","line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs/vfsmatch\""},
  {"file":"ata/discovertypings.go","line":18,"text":")"},
];

export function projectStrictParityLineText(file: string, line: number): string | undefined {
  return projectStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function projectStrictParityFiles(): readonly string[] {
  return [...new Set(projectStrictParitySourceLines.map((entry) => entry.file))].sort();
}
