// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/testing/fstest.ts","contentHash":"e8446a43f3b4bda7d819e8d3a558d20b5d3995382ab64969e63822d85d81c4fb"}

export interface MapFile {
  readonly __goFacadeName: "testing/fstest.MapFile";
}

export interface MapFS {
  readonly __goFacadeName: "testing/fstest.MapFS";
}

export function TestFS(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED testing/fstest.TestFS");
}
