// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/testing/synctest.ts","contentHash":"3df8b5ab4af1852da96016344e8896fdc3f19440751686d2e887a76abfc20d0d"}

export function Test(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED testing/synctest.Test");
}

export function Wait(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED testing/synctest.Wait");
}
