// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/github.com/zeebo/xxh3.ts","contentHash":"77f4420a37c68cf33c1efe945507d3b12c1d204d6b884afc643259679eaefea8"}

export interface Hasher {
  readonly __goFacadeName: "github.com/zeebo/xxh3.Hasher";
}

export function HashString128(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED github.com/zeebo/xxh3.HashString128");
}

export function New(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED github.com/zeebo/xxh3.New");
}

export interface Uint128 {
  readonly __goFacadeName: "github.com/zeebo/xxh3.Uint128";
}
