import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

import { AstSchema } from "../ast-schema-model.mjs";
import { hashText, resolveRepo, writeTextSafely } from "../porter.mjs";
import { astConfig, loadAstSchema } from "./config.mjs";
import { emitData } from "./data-emitter.mjs";
import { emitFlags, emitKinds } from "./flag-emitters.mjs";
import { assertNodeDataMethodsMatchUpstream, emitNode, emitUnions } from "./node-emitters.mjs";
import { emitFactory } from "./factory-emitter.mjs";
import { emitCasts, emitPredicates, emitVisitor } from "./runtime-helper-emitters.mjs";

const GENERATOR = "porter:ast";
const GENERATED_KIND = "ast-generated";

// ── generated AST skips manifest ─────────────────────────────────────────────

export function buildGeneratedAstSkips(config) {
  const schema = loadSchemaModel(config);
  const handWritten = [];
  const handWrittenVisitor = [];
  for (const node of schema.nodeNames()) {
    const def = schema.definitions[node];
    if (def.handWritten) handWritten.push(node);
    if (def.handWrittenVisitor) handWrittenVisitor.push(node);
  }
  const visitEachChildDeferred = [];
  return { handWritten, handWrittenVisitor, visitEachChildDeferred };
}

function loadSchemaModel(config) {
  const schema = loadAstSchema(config);
  return new AstSchema(schema.ast);
}

function emitIndex() {
  const lines = [];
  lines.push(`export * from "./kinds.js";`);
  lines.push(`export * from "./flags.js";`);
  lines.push(`export * from "./unions.js";`);
  lines.push(`export * from "./node.js";`);
  lines.push(`export * from "./data.js";`);
  lines.push(`export * from "./factory.js";`);
  lines.push(`export * from "./predicates.js";`);
  lines.push(`export * from "./casts.js";`);
  // visitor.ts re-exports the Concrete_ForEachChild surface already exported by
  // data.ts; it is not re-barreled here to avoid duplicate re-exports.
  lines.push("");
  return lines.join("\n");
}

const EMITTERS = [
  { file: "kinds.ts", emit: emitKinds, model: false },
  { file: "flags.ts", emit: emitFlags, model: false },
  { file: "unions.ts", emit: emitUnions, model: true },
  { file: "node.ts", emit: emitNode, model: true },
  { file: "data.ts", emit: emitData, model: true },
  { file: "factory.ts", emit: emitFactory, model: true },
  { file: "predicates.ts", emit: emitPredicates, model: true },
  { file: "casts.ts", emit: emitCasts, model: true },
  { file: "visitor.ts", emit: emitVisitor, model: true },
  { file: "index.ts", emit: emitIndex, model: false },
];

// ---------------------------------------------------------------------------
// File assembly + metadata
// ---------------------------------------------------------------------------

// Deterministic digest of each declared schema input, so porter:ast --check can
// fail with a useful diagnostic when a specific input changes.
function schemaInputDigests(ac) {
  return ac.schemaInputs.map((relativePath) => ({
    path: relativePath,
    contentHash: hashText(readFileSync(resolveRepo(relativePath), "utf8")),
  }));
}

function generatedHeader(relativePath, body, sourceRevision, schemaInputs) {
  const metadata = {
    schemaVersion: 1,
    kind: GENERATED_KIND,
    generator: GENERATOR,
    sourceRevision,
    schemaInputs,
    path: relativePath,
    contentHash: hashText(body),
  };
  return `// Code generated by TSTS AST generator. DO NOT EDIT.\n// @tsgo-generated ${JSON.stringify(metadata)}\n\n`;
}

// Returns Map<tsRootRelativePath, fullFileText>.
export function buildAstGeneratedFiles(config, sourceRevision) {
  assertNodeDataMethodsMatchUpstream(config);
  const ac = astConfig(config);
  const schema = loadAstSchema(config);
  const model = new AstSchema(schema.ast);
  assertProtocolGeneratedMatchesSchema(config, model);
  const schemaInputs = schemaInputDigests(ac);
  const files = new Map();
  for (const emitter of EMITTERS) {
    const relativePath = `${ac.generatedDir}/${emitter.file}`;
    const body = emitter.model ? emitter.emit(model) : emitter.emit(schema);
    const header = generatedHeader(relativePath, body, sourceRevision, schemaInputs);
    files.set(relativePath, header + body);
  }
  return files;
}

export function assertProtocolGeneratedMatchesSchema(config, model = new AstSchema(loadAstSchema(config).ast)) {
  const input = config.protocolGeneratedInput === undefined
    ? resolveRepo(path.join(
      config.sourceRoot ?? "packages/tsts/_vendor/typescript-go",
      "_packages/native-preview/src/api/node/protocol.generated.ts",
    ))
    : resolveRepo(config.protocolGeneratedInput);
  if (!existsSync(input)) throw new Error(`missing native-preview protocol generated input: ${input}`);
  const source = readFileSync(input, "utf8");
  const actualChildren = parseProtocolPropertyMap(source, "childProperties", true);
  const actualSingle = parseProtocolPropertyMap(source, "singleChildNodePropertyNames", false);
  const expectedChildren = new Map();
  for (const nodeName of model.nodeNames()) {
    const children = model.schemaMembers(nodeName)
      .filter((member) => member.isChild() && !member.noTS)
      .map((member) => model.uncapitalize(member.name));
    if (children.length === 0) continue;
    const kindTypes = model.kindTypesOf(nodeName).kindNames;
    const kindNames = new Set([...kindTypes, ...model.kindAliasesOf(nodeName)]);
    if (kindTypes.length === 1) kindNames.add(model.syntaxKindName(nodeName));
    for (const kindName of kindNames) expectedChildren.set(kindName, children);
  }
  const expectedSingle = new Map([...expectedChildren].filter(([, children]) => children.length === 1).map(([kind, children]) => [kind, children[0]]));
  const differences = [
    ...compareProtocolMap("childProperties", expectedChildren, actualChildren),
    ...compareProtocolMap("singleChildNodePropertyNames", expectedSingle, actualSingle),
  ];
  if (differences.length > 0) {
    throw new Error(`native-preview protocol child ordering differs from the AST schema: ${differences.slice(0, 8).join("; ")}`);
  }
}

function parseProtocolPropertyMap(source, variableName, arrays) {
  const start = source.indexOf(`export const ${variableName}`);
  if (start < 0) throw new Error(`protocol generated input is missing ${variableName}`);
  const bodyStart = source.indexOf("{", start);
  const bodyEnd = source.indexOf("\n};", bodyStart);
  if (bodyStart < 0 || bodyEnd < 0) throw new Error(`protocol generated input has malformed ${variableName}`);
  const body = source.slice(bodyStart + 1, bodyEnd);
  const result = new Map();
  const expression = arrays
    ? /\[SyntaxKind\.([A-Za-z0-9_]+)\]:\s*\[([^\]]*)\]/g
    : /\[SyntaxKind\.([A-Za-z0-9_]+)\]:\s*"([^"]+)"/g;
  for (const match of body.matchAll(expression)) {
    const value = arrays
      ? [...match[2].matchAll(/"([^"]+)"/g)].map((item) => item[1])
      : match[2];
    result.set(match[1], value);
  }
  return result;
}

function compareProtocolMap(label, expected, actual) {
  const differences = [];
  for (const [kind, value] of expected) {
    if (!actual.has(kind)) differences.push(`${label}.${kind} missing`);
    else if (JSON.stringify(actual.get(kind)) !== JSON.stringify(value)) differences.push(`${label}.${kind} expected ${JSON.stringify(value)}, got ${JSON.stringify(actual.get(kind))}`);
  }
  for (const kind of actual.keys()) {
    if (!expected.has(kind)) differences.push(`${label}.${kind} is unexpected`);
  }
  return differences;
}

function generatedDirAbsolute(config) {
  const ac = astConfig(config);
  return resolveRepo(path.join(ac.tsRoot, ac.generatedDir));
}

function walkTsFiles(root) {
  if (!existsSync(root)) return [];
  const out = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const full = path.join(root, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkTsFiles(full));
    } else if (entry.isFile() && entry.name.endsWith(".ts")) {
      out.push(full);
    }
  }
  return out;
}

function parseAstMetadata(text) {
  const match = /^\/\/ @tsgo-generated\s+({[^\n\r]+})/m.exec(text);
  if (!match) return undefined;
  try {
    return JSON.parse(match[1]);
  } catch {
    return undefined;
  }
}

// Returns { missing, stale, orphan, untracked, invalid } — same shape as facades.
export function buildAstGeneratedArtifactStatus(config, sourceRevision) {
  const ac = astConfig(config);
  const expected = buildAstGeneratedFiles(config, sourceRevision);
  const expectedPaths = new Set(expected.keys());
  const root = generatedDirAbsolute(config);
  const actualFiles = walkTsFiles(root).map((file) => `${ac.generatedDir}/${path.relative(root, file).split(path.sep).join("/")}`);
  const actualPaths = new Set(actualFiles);

  const missing = [];
  const stale = [];
  const orphan = [];
  const untracked = [];
  const invalid = [];

  for (const relativePath of [...expectedPaths].sort()) {
    if (!actualPaths.has(relativePath)) {
      missing.push({ path: relativePath, reason: "Expected generated AST artifact is missing." });
    }
  }

  for (const relativePath of actualFiles) {
    const absolute = resolveRepo(path.join(ac.tsRoot, relativePath));
    const text = readFileSync(absolute, "utf8");
    const metadata = parseAstMetadata(text);
    if (!metadata) {
      untracked.push({ path: relativePath, reason: "Generated AST directory file is missing @tsgo-generated metadata." });
      continue;
    }
    if (metadata.kind !== GENERATED_KIND || metadata.generator !== GENERATOR) {
      invalid.push({ path: relativePath, reason: "Generated AST file metadata kind/generator is not ast-generated/porter:ast." });
      continue;
    }
    if (!expectedPaths.has(relativePath)) {
      orphan.push({ path: relativePath, reason: "Generated AST file is no longer produced from the current schema." });
      continue;
    }
    if (text !== expected.get(relativePath)) {
      stale.push({ path: relativePath, reason: "Generated AST file differs from the current deterministic generator output." });
    }
  }

  return { missing, stale, orphan, untracked, invalid };
}

export function collectAstArtifactFailures(status) {
  const failures = [];
  if (status.missing.length > 0) failures.push(`${status.missing.length} missing AST generated artifacts`);
  if (status.stale.length > 0) failures.push(`${status.stale.length} stale AST generated artifacts`);
  if (status.orphan.length > 0) failures.push(`${status.orphan.length} orphan AST generated artifacts`);
  if (status.untracked.length > 0) failures.push(`${status.untracked.length} untracked AST generated artifacts`);
  if (status.invalid.length > 0) failures.push(`${status.invalid.length} invalid AST generated artifacts`);
  return failures;
}

export function writeAstGenerated(config, sourceRevision, options = {}) {
  const ac = astConfig(config);
  const expected = buildAstGeneratedFiles(config, sourceRevision);
  const results = [];
  for (const [relativePath, text] of expected) {
    const absolute = resolveRepo(path.join(ac.tsRoot, relativePath));
    const outcome = writeTextSafely(absolute, text, { force: options.force === true, label: "AST generated artifact" });
    results.push({ path: relativePath, outcome });
  }
  return results;
}

export function emptyAstGeneratedArtifactStatus() {
  return { missing: [], stale: [], orphan: [], untracked: [], invalid: [] };
}
