// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/io/fs.ts","contentHash":"8539460862153e5bca7aa118464a38c2ce84b0458c9ed3bf5ffc57bb921cb572"}

export function DirectoryExists(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.DirectoryExists");
}

export interface DirEntry {
  readonly __goFacadeName: "io/fs.DirEntry";
}

export const ErrClosed: unknown = undefined as never;

export const ErrExist: unknown = undefined as never;

export const ErrInvalid: unknown = undefined as never;

export const ErrNotExist: unknown = undefined as never;

export const ErrPermission: unknown = undefined as never;

export interface File {
  readonly __goFacadeName: "io/fs.File";
}

export function FileExists(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.FileExists");
}

export interface FileInfo {
  readonly __goFacadeName: "io/fs.FileInfo";
}

export function FileInfoToDirEntry(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.FileInfoToDirEntry");
}

export interface FileMode {
  readonly __goFacadeName: "io/fs.FileMode";
}

export interface FS {
  readonly __goFacadeName: "io/fs.FS";
}

export function GetAccessibleEntries(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.GetAccessibleEntries");
}

export const ModeDir: unknown = undefined as never;

export const ModeIrregular: unknown = undefined as never;

export const ModePerm: unknown = undefined as never;

export const ModeSymlink: unknown = undefined as never;

export function Outputs(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.Outputs");
}

export function ReadDir(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.ReadDir");
}

export interface ReadDirFile {
  readonly __goFacadeName: "io/fs.ReadDirFile";
}

export function ReadFile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.ReadFile");
}

export function Realpath(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.Realpath");
}

export function Remove(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.Remove");
}

export const SkipAll: unknown = undefined as never;

export const SkipDir: unknown = undefined as never;

export function Stat(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.Stat");
}

export function Sub(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.Sub");
}

export function UseCaseSensitiveFileNames(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.UseCaseSensitiveFileNames");
}

export function WalkDir(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.WalkDir");
}

export interface WalkDirFunc {
  readonly __goFacadeName: "io/fs.WalkDirFunc";
}

export function WriteFile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED io/fs.WriteFile");
}
