package main

import (
	"go/constant"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestPrintedFailsHardForUnsupportedInput(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("printed must panic instead of returning a marker that can enter a snapshot")
		}
	}()
	printed(struct{ Value int }{Value: 1})
}

func TestScanGoFileUsesGoGeneratedMarkerContract(t *testing.T) {
	tests := []struct {
		name   string
		source string
		want   bool
	}{
		{name: "canonical", source: "// Code generated by tool; DO NOT EDIT.\npackage sample\n", want: true},
		{name: "crlf", source: "// Code generated by tool; DO NOT EDIT.\r\npackage sample\r\n", want: true},
		{name: "generator source literal", source: "package main\nfunc emit() { write(\"// Code generated by tool; DO NOT EDIT.\\n\") }\n"},
		{name: "generator source raw literal", source: "package main\nconst marker = `\n// Code generated by tool; DO NOT EDIT.\n`\n"},
		{name: "two unrelated fragments", source: "// Code generated appears here\n// DO NOT EDIT appears there\npackage sample\n"},
		{name: "indented marker accepted by go/ast", source: "  // Code generated by tool; DO NOT EDIT.\npackage sample\n", want: true},
		{name: "missing period", source: "// Code generated by tool; DO NOT EDIT\npackage sample\n"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			file := filepath.Join(root, "source.go")
			if err := os.WriteFile(file, []byte(test.source), 0o644); err != nil {
				t.Fatal(err)
			}
			if got := scanGoFile(root, file, "example/source").Generated; got != test.want {
				t.Fatalf("Generated = %v, want %v", got, test.want)
			}
		})
	}
}

func TestShouldSkipNestedGitCheckout(t *testing.T) {
	root := t.TempDir()
	nested := filepath.Join(root, "_submodules", "TypeScript")
	if err := os.MkdirAll(nested, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(nested, ".git"), []byte("gitdir: elsewhere\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !shouldSkipDir("TypeScript", nested, root) {
		t.Fatal("nested Git checkout must be excluded from the Go source walk")
	}
	ordinary := filepath.Join(root, "internal")
	if err := os.MkdirAll(ordinary, 0o755); err != nil {
		t.Fatal(err)
	}
	if shouldSkipDir("internal", ordinary, root) {
		t.Fatal("ordinary source directory must remain in the Go source walk")
	}
}

func TestResolveSnapshotConstantValuesAcrossFilesAndImports(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{
		constantTestFile("core/base.go", "example/core", "core", nil,
			constantTestSpec([]string{"Base"}, []string{"1"}, 0),
		),
		constantTestFile("core/derived.go", "example/core", "core", nil,
			constantTestSpec([]string{"Derived"}, []string{"Base + 2"}, 0),
		),
		constantTestFile("use/use.go", "example/use", "use", []ImportReport{{Name: "source", Path: "example/core"}},
			constantTestSpec([]string{"Result"}, []string{"source.Derived << 1"}, 0),
		),
	}}

	resolveSnapshotConstantValues(&snapshot)

	assertConstantReport(t, snapshot.Files[0].Units[0].ValueSpecs[0].ConstantValues[0], "number", "1")
	assertConstantReport(t, snapshot.Files[1].Units[0].ValueSpecs[0].ConstantValues[0], "number", "3")
	assertConstantReport(t, snapshot.Files[2].Units[0].ValueSpecs[0].ConstantValues[0], "number", "6")
}

func TestResolveSnapshotConstantValuesAcceptsEquivalentBuildVariants(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{
		constantTestFile("platform/value_linux.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Value"}, []string{"4"}, 0),
		),
		constantTestFile("platform/value_windows.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Value"}, []string{"2 + 2"}, 0),
		),
		constantTestFile("platform/use.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Result"}, []string{"Value * 2"}, 0),
		),
	}}

	resolveSnapshotConstantValues(&snapshot)

	assertConstantReport(t, snapshot.Files[2].Units[0].ValueSpecs[0].ConstantValues[0], "number", "8")
}

func TestResolveSnapshotConstantValuesRejectsBuildDependentAndCyclicValues(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{
		constantTestFile("platform/value_linux.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Value"}, []string{"1"}, 0),
		),
		constantTestFile("platform/value_windows.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Value"}, []string{"2"}, 0),
		),
		constantTestFile("platform/use.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Result"}, []string{"Value"}, 0),
			constantTestSpec([]string{"CycleA"}, []string{"CycleB"}, 1),
			constantTestSpec([]string{"CycleB"}, []string{"CycleA"}, 2),
		),
	}}

	resolveSnapshotConstantValues(&snapshot)

	buildDependent := snapshot.Files[2].Units[0].ValueSpecs[0].ConstantValues[0]
	if buildDependent.Supported || !strings.Contains(buildDependent.Reason, "build-dependent constant reference Value") {
		t.Fatalf("expected explicit build-dependent rejection, got %#v", buildDependent)
	}
	cycle := snapshot.Files[2].Units[0].ValueSpecs[1].ConstantValues[0]
	if cycle.Supported || !strings.Contains(cycle.Reason, "constant dependency cycle") {
		t.Fatalf("expected explicit cycle rejection, got %#v", cycle)
	}
}

func TestResolveSnapshotConstantValuesDoesNotTreatConversionsAsReferences(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{
		constantTestFile("convert/convert.go", "example/convert", "convert", nil,
			constantTestSpec([]string{"Value"}, []string{"uint32(3)"}, 0),
		),
	}}

	resolveSnapshotConstantValues(&snapshot)

	assertConstantReport(t, snapshot.Files[0].Units[0].ValueSpecs[0].ConstantValues[0], "number", "3")
}

func TestResolveSnapshotConstantValuesLoadsStandardLibraryConstants(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{
		constantTestFile("duration/duration.go", "example/duration", "duration", []ImportReport{{Path: "time", PackageName: "time"}},
			constantTestSpec([]string{"Delay"}, []string{"5 * time.Millisecond"}, 0),
		),
	}}

	resolveSnapshotConstantValues(&snapshot)

	assertConstantReport(t, snapshot.Files[0].Units[0].ValueSpecs[0].ConstantValues[0], "number", "5000000")
}

func TestResolveSnapshotConstantValuesAppliesNamedUnsignedWidth(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{{
		Path:        "flags/flags.go",
		ImportPath:  "example/flags",
		PackageName: "flags",
		Units: []UnitReport{
			{Kind: "type", Name: "Flags", TypeExpression: identTypeExpr("uint32")},
			{Kind: "constGroup", ValueSpecs: []ValueSpecReport{
				{Names: []string{"One"}, Values: []string{"1"}, Type: identTypeExpr("Flags")},
				{Names: []string{"Mask"}, Values: []string{"^One"}},
			}},
		},
	}}}

	resolveSnapshotConstantValues(&snapshot)

	assertConstantReport(t, snapshot.Files[0].Units[1].ValueSpecs[1].ConstantValues[0], "number", "4294967294")
}

func TestConstantEvaluatorMatchesGoTypesForTypedConversions(t *testing.T) {
	for _, expression := range []string{
		"^uint8(1)",
		"^int16(1)",
		"float32(1.0 / 3.0)",
		"uint32(3) << 4",
	} {
		t.Run(expression, func(t *testing.T) {
			parsed, err := parser.ParseExpr(expression)
			if err != nil {
				t.Fatal(err)
			}
			actual, reason := evaluateConstantExpression(parsed, constant.MakeInt64(0), map[string]constant.Value{})
			if actual == nil {
				t.Fatalf("extractor rejected supported expression: %s", reason)
			}
			expected, err := types.Eval(token.NewFileSet(), types.NewPackage("example/test", "test"), token.NoPos, expression)
			if err != nil {
				t.Fatal(err)
			}
			if actual.Kind() != expected.Value.Kind() || actual.ExactString() != expected.Value.ExactString() {
				t.Fatalf("extractor = %s %s, go/types = %s %s", actual.Kind(), actual.ExactString(), expected.Value.Kind(), expected.Value.ExactString())
			}
		})
	}
	parsed, err := parser.ParseExpr("uint8(256)")
	if err != nil {
		t.Fatal(err)
	}
	if value, reason := evaluateConstantExpression(parsed, constant.MakeInt64(0), map[string]constant.Value{}); value != nil || !strings.Contains(reason, "overflows") {
		t.Fatalf("overflowing conversion must fail closed, got %v, %q", value, reason)
	}
}

func TestResolveSnapshotConstantValuesRejectsSameValueDifferentTypedVariants(t *testing.T) {
	snapshot := Snapshot{Files: []FileReport{
		constantTestFile("platform/value_linux.go", "example/platform", "platform", nil,
			ValueSpecReport{Names: []string{"Value"}, Values: []string{"1"}, Type: identTypeExpr("uint8")},
		),
		constantTestFile("platform/value_windows.go", "example/platform", "platform", nil,
			ValueSpecReport{Names: []string{"Value"}, Values: []string{"1"}, Type: identTypeExpr("uint16")},
		),
		constantTestFile("platform/use.go", "example/platform", "platform", nil,
			constantTestSpec([]string{"Result"}, []string{"Value"}, 0),
		),
	}}

	resolveSnapshotConstantValues(&snapshot)

	report := snapshot.Files[2].Units[0].ValueSpecs[0].ConstantValues[0]
	if report.Supported || !strings.Contains(report.Reason, "build-dependent constant type") {
		t.Fatalf("same-valued variants with different types must reject, got %#v", report)
	}
}

func TestImplicitBuildTagsUseExactGoFilenameSuffixes(t *testing.T) {
	if got := implicitBuildTags("internal/foo_linux_helper.go"); got != nil {
		t.Fatalf("middle filename component must not act as a build suffix: %v", got)
	}
	if got := strings.Join(implicitBuildTags("internal/foo_linux.go"), ","); got != "linux" {
		t.Fatalf("GOOS suffix = %q", got)
	}
	if got := strings.Join(implicitBuildTags("internal/foo_linux_amd64.go"), ","); got != "amd64,linux" {
		t.Fatalf("GOOS/GOARCH suffix = %q", got)
	}
	if got := strings.Join(implicitBuildTags("internal/foo_amd64_test.go"), ","); got != "amd64" {
		t.Fatalf("GOARCH test suffix = %q", got)
	}
}

func TestStructMembersPreserveExactStructAndJSONTags(t *testing.T) {
	source := "package sample\ntype Event struct {\n  Name string `json:\"name,omitzero\" xml:\"Name\"`\n  Empty string `json:\"\"`\n  Internal string\n}\n"
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	report := scanGoFile(root, path, "example")
	if report.ParseError != "" {
		t.Fatalf("unexpected report: %#v", report)
	}
	var event *UnitReport
	for index := range report.Units {
		if report.Units[index].Kind == "type" && report.Units[index].Name == "Event" {
			event = &report.Units[index]
			break
		}
	}
	if event == nil {
		t.Fatalf("missing Event type unit: %#v", report.Units)
	}
	members := event.Members
	if len(members) != 3 {
		t.Fatalf("members = %#v", members)
	}
	if members[0].StructTag == nil || *members[0].StructTag != `json:"name,omitzero" xml:"Name"` || len(members[0].TagValues) != 2 || members[0].TagValues[0] != (StructTagValueReport{Key: "json", Value: "name,omitzero"}) || members[0].TagValues[1] != (StructTagValueReport{Key: "xml", Value: "Name"}) {
		t.Fatalf("tagged member = %#v", members[0])
	}
	if members[1].StructTag == nil || len(members[1].TagValues) != 1 || members[1].TagValues[0] != (StructTagValueReport{Key: "json", Value: ""}) {
		t.Fatalf("empty JSON tag must remain distinguishable from no tag: %#v", members[1])
	}
	if members[2].StructTag != nil || members[2].TagValues != nil {
		t.Fatalf("untagged member = %#v", members[2])
	}
}

func TestParseStructTagValuesRejectsMalformedAndPreservesDuplicates(t *testing.T) {
	values, err := parseStructTagValues(`json:"first" json:"second" note:"a\\tb"`)
	if err != nil {
		t.Fatal(err)
	}
	if len(values) != 3 || values[0].Value != "first" || values[1].Value != "second" || values[2].Value != `a\tb` {
		t.Fatalf("values = %#v", values)
	}
	for _, malformed := range []string{`json`, `json:name`, `json:"unterminated`, `json:"bad\q"`} {
		if _, err := parseStructTagValues(malformed); err == nil {
			t.Fatalf("expected malformed tag %q to fail", malformed)
		}
	}
}

func TestStructTagsPreserveExportStatusInlineStructsAndSummaryCounts(t *testing.T) {
	source := "package sample\ntype Wrapper struct {\n  Public string `json:\"public,omitempty\"`\n  hidden string `json:\"hidden\"`\n  Nested struct { Value string `json:\"value,omitzero\"` }\n}\n"
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	report := scanGoFile(root, path, "example")
	var wrapper *UnitReport
	for index := range report.Units {
		if report.Units[index].Kind == "type" && report.Units[index].Name == "Wrapper" {
			wrapper = &report.Units[index]
		}
	}
	if wrapper == nil || len(wrapper.Members) != 3 {
		t.Fatalf("wrapper = %#v", wrapper)
	}
	if !wrapper.Members[0].Exported || wrapper.Members[1].Exported {
		t.Fatalf("export status = %#v", wrapper.Members)
	}
	nested := wrapper.Members[2].TypeExpr
	if nested == nil || len(nested.Members) != 1 || nested.Members[0].TagValues[0].Value != "value,omitzero" {
		t.Fatalf("nested tags = %#v", nested)
	}
	summary := Summary{StructTagKeys: map[string]int{}}
	accumulateUnitStructTags(&summary, *wrapper)
	if summary.StructTagCount != 3 || summary.StructTagKeys["json"] != 3 {
		t.Fatalf("summary = %#v", summary)
	}
}

func TestFileStructTagInventoryIncludesFunctionLocalAnonymousStructs(t *testing.T) {
	source := "package sample\ntype Top struct { Name string `json:\"name\"` }\nfunc read() { var local struct { Value *int `json:\"value,omitzero\"` }; _ = local }\n"
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	report := scanGoFile(root, path, "example")
	if len(report.StructTags) != 2 {
		t.Fatalf("struct tags = %#v", report.StructTags)
	}
	if report.StructTags[0].Name != "Name" || report.StructTags[0].TagValues[0].Value != "name" {
		t.Fatalf("top-level tag = %#v", report.StructTags[0])
	}
	if report.StructTags[1].Name != "Value" || report.StructTags[1].TypeExpr == nil || report.StructTags[1].TypeExpr.Kind != "pointer" || report.StructTags[1].TagValues[0].Value != "value,omitzero" {
		t.Fatalf("local tag = %#v", report.StructTags[1])
	}
}

func TestExternalReferencesClassifyCallsValuesAndTypes(t *testing.T) {
	source := `package sample
import (
	"encoding"
	"iter"
	"os"
  "reflect"
  "math/rand/v2"
)
func run(seq iter.Seq[int]) {
  _ = reflect.TypeFor[int]()
	_, _ = reflect.TypeAssert[encoding.TextMarshaler](reflect.Value{})
  _ = (rand.IntN)(4)
	_ = os.PathSeparator
}`
	fileSet := token.NewFileSet()
	parsed, err := parser.ParseFile(fileSet, "sample.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	imports := importsOf(parsed, map[string]string{
		"encoding":     "encoding",
		"iter":         "iter",
		"math/rand/v2": "rand",
		"os":           "os",
		"reflect":      "reflect",
	}, "sample.go")
	refs := externalRefsOf(parsed.Decls[len(parsed.Decls)-1], imports)
	if len(refs) != 7 {
		t.Fatalf("expected one semantic role per selector occurrence, got %#v", refs)
	}
	want := map[string]bool{
		"encoding.TextMarshaler:type:0": false,
		"iter.Seq:type:1":               false,
		"math/rand/v2.IntN:call:0":      false,
		"os.PathSeparator:value:0":      false,
		"reflect.TypeAssert:call:0":     false,
		"reflect.TypeFor:call:0":        false,
		"reflect.Value:type:0":          false,
	}
	for _, ref := range refs {
		key := ref.ImportPath + "." + ref.Name + ":" + ref.Role + ":" + strconv.Itoa(ref.Arity)
		if _, ok := want[key]; !ok {
			t.Fatalf("unexpected external reference %s in %#v", key, refs)
		}
		want[key] = true
	}
	for name, found := range want {
		if !found {
			t.Fatalf("missing external reference %s in %#v", name, refs)
		}
	}
}

func TestExternalReferencesResolveTheImportBindingInsteadOfAliasText(t *testing.T) {
	source := `package sample
import "context"
type holder struct{}
func (holder) receiver(context holder) {
	_ = context.flags
	{
		context := holder{}
		_ = context.inferences
	}
	for context := range []holder{} {
		_ = context.returnMapper
	}
}

func generic[context interface{ marker() }](value context) {
	_ = value
}
func external(value context.Context) context.Context {
	return context.Background()
}`
	fileSet := token.NewFileSet()
	parsed, err := parser.ParseFile(fileSet, "sample.go", source, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	imports := importsOf(parsed, map[string]string{"context": "context"}, "sample.go")
	var refs []ExternalRefReport
	for _, declaration := range parsed.Decls {
		refs = append(refs, externalRefsOf(declaration, imports)...)
	}
	if len(refs) != 2 {
		t.Fatalf("expected only the actual context package selectors, got %#v", refs)
	}
	want := map[string]bool{
		"Background:call": false,
		"Context:type":    false,
	}
	for _, ref := range refs {
		key := ref.Name + ":" + ref.Role
		if _, ok := want[key]; !ok {
			t.Fatalf("shadowed lexical binding was classified as an import: %#v", ref)
		}
		want[key] = true
		if ref.Name == "Context" && ref.Count != 2 {
			t.Fatalf("context.Context count = %d, want 2", ref.Count)
		}
	}
	for key, found := range want {
		if !found {
			t.Fatalf("missing import-bound selector %s in %#v", key, refs)
		}
	}
}

func TestReturnFactsDistinguishNilFromAllocatedEmptyValues(t *testing.T) {
	source := `package sample
func nilSlice(flag bool) []int {
	if flag { return nil }
	return []int{}
}
func madeSlice() []int { return make([]int, 0) }
func nilMap() map[string]int { return nil }
func madeMap() map[string]int { return make(map[string]int) }
func nested() func() []int { return func() []int { return nil } }
`
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	report := scanGoFile(root, path, "example")
	facts := map[string][]ReturnFactReport{}
	for _, unit := range report.Units {
		if unit.Kind == "func" {
			facts[unit.Name] = unit.ReturnFacts
		}
	}
	assertReturnKinds(t, facts["nilSlice"], "nil", "empty-slice")
	assertReturnKinds(t, facts["madeSlice"], "make-empty-slice")
	assertReturnKinds(t, facts["nilMap"], "nil")
	assertReturnKinds(t, facts["madeMap"], "make-empty-map")
	assertReturnKinds(t, facts["nested"], "other")
}

func assertReturnKinds(t *testing.T, facts []ReturnFactReport, expected ...string) {
	t.Helper()
	actual := []string{}
	for _, fact := range facts {
		for _, result := range fact.Results {
			actual = append(actual, result.Kind)
		}
	}
	if strings.Join(actual, ",") != strings.Join(expected, ",") {
		t.Fatalf("return facts = %v, want %v", actual, expected)
	}
}

func constantTestFile(path string, importPath string, packageName string, imports []ImportReport, specs ...ValueSpecReport) FileReport {
	return FileReport{
		Path:        path,
		ImportPath:  importPath,
		PackageName: packageName,
		Imports:     imports,
		Units:       []UnitReport{{Kind: "constGroup", ValueSpecs: specs}},
	}
}

func constantTestSpec(names []string, values []string, constIndex int) ValueSpecReport {
	return ValueSpecReport{Names: names, Values: values, ConstIndex: constIndex}
}

func assertConstantReport(t *testing.T, report ConstantValueReport, kind string, exact string) {
	t.Helper()
	if !report.Supported || report.Kind != kind || report.Exact != exact {
		t.Fatalf("expected %s %s, got %#v", kind, exact, report)
	}
}
