/**
 * Strict TS-Go parity gap map for `compiler`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const compilerStrictParityUpstreamModule = "compiler";
export const compilerStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"checkerpool.go","line":1,"text":"package compiler"},
  {"file":"checkerpool.go","line":3,"text":"import ("},
  {"file":"checkerpool.go","line":4,"text":"\t\"context\""},
  {"file":"checkerpool.go","line":5,"text":"\t\"slices\""},
  {"file":"checkerpool.go","line":6,"text":"\t\"sync\""},
  {"file":"checkerpool.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"checkerpool.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"file":"checkerpool.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"checkerpool.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/tracing\""},
  {"file":"checkerpool.go","line":12,"text":")"},
  {"file":"checkerpool.go","line":20,"text":"type CheckerPool interface {"},
  {"file":"checkerpool.go","line":21,"text":"\tGetChecker(ctx context.Context, file *ast.SourceFile) (*checker.Checker, func())"},
  {"file":"checkerpool.go","line":22,"text":"}"},
  {"file":"checkerpool.go","line":24,"text":"type checkerPool struct {"},
  {"file":"checkerpool.go","line":25,"text":"\tprogram *Program"},
  {"file":"checkerpool.go","line":26,"text":"\ttracing *tracing.Tracing"},
  {"file":"checkerpool.go","line":28,"text":"\tcreateCheckersOnce sync.Once"},
  {"file":"checkerpool.go","line":29,"text":"\tcheckers           []*checker.Checker"},
  {"file":"checkerpool.go","line":30,"text":"\tlocks              []*sync.Mutex"},
  {"file":"checkerpool.go","line":31,"text":"\tfileAssociations   map[*ast.SourceFile]*checker.Checker"},
  {"file":"checkerpool.go","line":32,"text":"}"},
  {"file":"checkerpool.go","line":34,"text":"var _ CheckerPool = (*checkerPool)(nil)"},
  {"file":"checkerpool.go","line":36,"text":"func newCheckerPool(program *Program) *checkerPool {"},
  {"file":"checkerpool.go","line":37,"text":"\treturn newCheckerPoolWithTracing(program, nil)"},
  {"file":"checkerpool.go","line":38,"text":"}"},
  {"file":"checkerpool.go","line":40,"text":"func newCheckerPoolWithTracing(program *Program, tr *tracing.Tracing) *checkerPool {"},
  {"file":"checkerpool.go","line":41,"text":"\tcheckerCount := 4"},
  {"file":"checkerpool.go","line":42,"text":"\tif program.SingleThreaded() {"},
  {"file":"checkerpool.go","line":43,"text":"\t\tcheckerCount = 1"},
  {"file":"checkerpool.go","line":44,"text":"\t} else if c := program.Options().Checkers; c != nil {"},
  {"file":"checkerpool.go","line":45,"text":"\t\tcheckerCount = *c"},
  {"file":"checkerpool.go","line":46,"text":"\t}"},
  {"file":"checkerpool.go","line":48,"text":"\tcheckerCount = max(min(checkerCount, len(program.files), 256), 1)"},
  {"file":"checkerpool.go","line":50,"text":"\tpool := &checkerPool{"},
  {"file":"checkerpool.go","line":51,"text":"\t\tprogram:  program,"},
  {"file":"checkerpool.go","line":52,"text":"\t\tcheckers: make([]*checker.Checker, checkerCount),"},
  {"file":"checkerpool.go","line":53,"text":"\t\tlocks:    make([]*sync.Mutex, checkerCount),"},
  {"file":"checkerpool.go","line":54,"text":"\t\ttracing:  tr,"},
  {"file":"checkerpool.go","line":55,"text":"\t}"},
  {"file":"checkerpool.go","line":57,"text":"\treturn pool"},
  {"file":"checkerpool.go","line":58,"text":"}"},
  {"file":"checkerpool.go","line":62,"text":"func (p *checkerPool) GetChecker(ctx context.Context, file *ast.SourceFile) (*checker.Checker, func()) {"},
  {"file":"checkerpool.go","line":63,"text":"\tif file != nil {"},
  {"file":"checkerpool.go","line":64,"text":"\t\treturn p.getCheckerForFileExclusive(ctx, file)"},
  {"file":"checkerpool.go","line":65,"text":"\t}"},
  {"file":"checkerpool.go","line":66,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":67,"text":"\tc := p.checkers[0]"},
  {"file":"checkerpool.go","line":68,"text":"\tp.locks[0].Lock()"},
  {"file":"checkerpool.go","line":69,"text":"\treturn c, sync.OnceFunc(func() {"},
  {"file":"checkerpool.go","line":70,"text":"\t\tp.locks[0].Unlock()"},
  {"file":"checkerpool.go","line":71,"text":"\t})"},
  {"file":"checkerpool.go","line":72,"text":"}"},
  {"file":"checkerpool.go","line":77,"text":"func (p *checkerPool) getCheckerForFileNonExclusive(file *ast.SourceFile) (*checker.Checker, func()) {"},
  {"file":"checkerpool.go","line":78,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":79,"text":"\treturn p.fileAssociations[file], noop"},
  {"file":"checkerpool.go","line":80,"text":"}"},
  {"file":"checkerpool.go","line":82,"text":"func (p *checkerPool) getCheckerForFileExclusive(ctx context.Context, file *ast.SourceFile) (*checker.Checker, func()) {"},
  {"file":"checkerpool.go","line":83,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":84,"text":"\tc := p.fileAssociations[file]"},
  {"file":"checkerpool.go","line":85,"text":"\tidx := slices.Index(p.checkers, c)"},
  {"file":"checkerpool.go","line":86,"text":"\tp.locks[idx].Lock()"},
  {"file":"checkerpool.go","line":87,"text":"\treturn c, sync.OnceFunc(func() {"},
  {"file":"checkerpool.go","line":88,"text":"\t\tp.locks[idx].Unlock()"},
  {"file":"checkerpool.go","line":89,"text":"\t})"},
  {"file":"checkerpool.go","line":90,"text":"}"},
  {"file":"checkerpool.go","line":93,"text":"func (p *checkerPool) getCheckerNonExclusive() (*checker.Checker, func()) {"},
  {"file":"checkerpool.go","line":94,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":95,"text":"\treturn p.checkers[0], noop"},
  {"file":"checkerpool.go","line":96,"text":"}"},
  {"file":"checkerpool.go","line":98,"text":"func (p *checkerPool) createCheckers() {"},
  {"file":"checkerpool.go","line":99,"text":"\tp.createCheckersOnce.Do(func() {"},
  {"file":"checkerpool.go","line":100,"text":"\t\tcheckerCount := len(p.checkers)"},
  {"file":"checkerpool.go","line":101,"text":"\t\twg := core.NewWorkGroup(p.program.SingleThreaded())"},
  {"file":"checkerpool.go","line":102,"text":"\t\tfor i := range checkerCount {"},
  {"file":"checkerpool.go","line":103,"text":"\t\t\twg.Queue(func() {"},
  {"file":"checkerpool.go","line":104,"text":"\t\t\t\tvar tracer *checker.Tracer"},
  {"file":"checkerpool.go","line":105,"text":"\t\t\t\tif p.tracing != nil {"},
  {"file":"checkerpool.go","line":106,"text":"\t\t\t\t\ttracer = checker.NewTracer(p.tracing, i)"},
  {"file":"checkerpool.go","line":107,"text":"\t\t\t\t}"},
  {"file":"checkerpool.go","line":108,"text":"\t\t\t\tp.checkers[i], p.locks[i] = checker.NewChecker(p.program, tracer)"},
  {"file":"checkerpool.go","line":109,"text":"\t\t\t})"},
  {"file":"checkerpool.go","line":110,"text":"\t\t}"},
  {"file":"checkerpool.go","line":112,"text":"\t\twg.RunAndWait()"},
  {"file":"checkerpool.go","line":114,"text":"\t\tp.fileAssociations = make(map[*ast.SourceFile]*checker.Checker, len(p.program.files))"},
  {"file":"checkerpool.go","line":115,"text":"\t\tfor i, file := range p.program.files {"},
  {"file":"checkerpool.go","line":116,"text":"\t\t\tp.fileAssociations[file] = p.checkers[i%checkerCount]"},
  {"file":"checkerpool.go","line":117,"text":"\t\t}"},
  {"file":"checkerpool.go","line":118,"text":"\t})"},
  {"file":"checkerpool.go","line":119,"text":"}"},
  {"file":"checkerpool.go","line":123,"text":"func (p *checkerPool) forEachCheckerParallel(cb func(idx int, c *checker.Checker)) {"},
  {"file":"checkerpool.go","line":124,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":125,"text":"\twg := core.NewWorkGroup(p.program.SingleThreaded())"},
  {"file":"checkerpool.go","line":126,"text":"\tfor idx, checker := range p.checkers {"},
  {"file":"checkerpool.go","line":127,"text":"\t\twg.Queue(func() {"},
  {"file":"checkerpool.go","line":128,"text":"\t\t\tp.locks[idx].Lock()"},
  {"file":"checkerpool.go","line":129,"text":"\t\t\tdefer p.locks[idx].Unlock()"},
  {"file":"checkerpool.go","line":130,"text":"\t\t\tcb(idx, checker)"},
  {"file":"checkerpool.go","line":131,"text":"\t\t})"},
  {"file":"checkerpool.go","line":132,"text":"\t}"},
  {"file":"checkerpool.go","line":133,"text":"\twg.RunAndWait()"},
  {"file":"checkerpool.go","line":134,"text":"}"},
  {"file":"checkerpool.go","line":136,"text":"func (p *checkerPool) GetGlobalDiagnostics() []*ast.Diagnostic {"},
  {"file":"checkerpool.go","line":137,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":138,"text":"\tglobalDiagnostics := make([][]*ast.Diagnostic, len(p.checkers))"},
  {"file":"checkerpool.go","line":139,"text":"\tp.forEachCheckerParallel(func(idx int, checker *checker.Checker) {"},
  {"file":"checkerpool.go","line":140,"text":"\t\tglobalDiagnostics[idx] = checker.GetGlobalDiagnostics()"},
  {"file":"checkerpool.go","line":141,"text":"\t})"},
  {"file":"checkerpool.go","line":142,"text":"\treturn SortAndDeduplicateDiagnostics(slices.Concat(globalDiagnostics...))"},
  {"file":"checkerpool.go","line":143,"text":"}"},
  {"file":"checkerpool.go","line":148,"text":"func (p *checkerPool) forEachCheckerGroupDo(ctx context.Context, files []*ast.SourceFile, singleThreaded bool, cb func(c *checker.Checker, fileIndex int, file *ast.SourceFile)) {"},
  {"file":"checkerpool.go","line":149,"text":"\tp.createCheckers()"},
  {"file":"checkerpool.go","line":151,"text":"\tcheckerCount := len(p.checkers)"},
  {"file":"checkerpool.go","line":152,"text":"\twg := core.NewWorkGroup(singleThreaded)"},
  {"file":"checkerpool.go","line":153,"text":"\tfor checkerIdx := range checkerCount {"},
  {"file":"checkerpool.go","line":154,"text":"\t\twg.Queue(func() {"},
  {"file":"checkerpool.go","line":155,"text":"\t\t\tp.locks[checkerIdx].Lock()"},
  {"file":"checkerpool.go","line":156,"text":"\t\t\tdefer p.locks[checkerIdx].Unlock()"},
  {"file":"checkerpool.go","line":157,"text":"\t\t\tfor i, file := range files {"},
  {"file":"checkerpool.go","line":158,"text":"\t\t\t\tif checker := p.checkers[checkerIdx]; checker == p.fileAssociations[file] {"},
  {"file":"checkerpool.go","line":159,"text":"\t\t\t\t\tcb(checker, i, file)"},
  {"file":"checkerpool.go","line":160,"text":"\t\t\t\t}"},
  {"file":"checkerpool.go","line":161,"text":"\t\t\t}"},
  {"file":"checkerpool.go","line":162,"text":"\t\t})"},
  {"file":"checkerpool.go","line":163,"text":"\t}"},
  {"file":"checkerpool.go","line":164,"text":"\twg.RunAndWait()"},
  {"file":"checkerpool.go","line":165,"text":"}"},
  {"file":"checkerpool.go","line":167,"text":"func noop() {}"},
  {"file":"emitHost.go","line":1,"text":"package compiler"},
  {"file":"emitHost.go","line":3,"text":"import ("},
  {"file":"emitHost.go","line":4,"text":"\t\"context\""},
  {"file":"emitHost.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"emitHost.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"emitHost.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/module\""},
  {"file":"emitHost.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/outputpaths\""},
  {"file":"emitHost.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/packagejson\""},
  {"file":"emitHost.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"file":"emitHost.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/symlinks\""},
  {"file":"emitHost.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/transformers/declarations\""},
  {"file":"emitHost.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/tsoptions\""},
  {"file":"emitHost.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"emitHost.go","line":16,"text":")"},
  {"file":"emitHost.go","line":19,"text":"type EmitHost interface {"},
  {"file":"emitHost.go","line":20,"text":"\tprinter.EmitHost"},
  {"file":"emitHost.go","line":21,"text":"\tdeclarations.DeclarationEmitHost"},
  {"file":"emitHost.go","line":22,"text":"\tOptions() *core.CompilerOptions"},
  {"file":"emitHost.go","line":23,"text":"\tSourceFiles() []*ast.SourceFile"},
  {"file":"emitHost.go","line":24,"text":"\tUseCaseSensitiveFileNames() bool"},
  {"file":"emitHost.go","line":25,"text":"\tGetCurrentDirectory() string"},
  {"file":"emitHost.go","line":26,"text":"\tCommonSourceDirectory() string"},
  {"file":"emitHost.go","line":27,"text":"\tIsEmitBlocked(file string) bool"},
  {"file":"emitHost.go","line":28,"text":"}"},
  {"file":"emitHost.go","line":30,"text":"var _ EmitHost = (*emitHost)(nil)"},
  {"file":"emitHost.go","line":33,"text":"type emitHost struct {"},
  {"file":"emitHost.go","line":34,"text":"\tprogram      *Program"},
  {"file":"emitHost.go","line":35,"text":"\temitResolver printer.EmitResolver"},
  {"file":"emitHost.go","line":36,"text":"}"},
  {"file":"emitHost.go","line":38,"text":"func newEmitHost(ctx context.Context, program *Program, file *ast.SourceFile) (*emitHost, func()) {"},
  {"file":"emitHost.go","line":39,"text":"\tchecker, done := program.GetTypeCheckerForFile(ctx, file)"},
  {"file":"emitHost.go","line":40,"text":"\treturn &emitHost{"},
  {"file":"emitHost.go","line":41,"text":"\t\tprogram:      program,"},
  {"file":"emitHost.go","line":42,"text":"\t\temitResolver: checker.GetEmitResolver(),"},
  {"file":"emitHost.go","line":43,"text":"\t}, done"},
  {"file":"emitHost.go","line":44,"text":"}"},
  {"file":"emitHost.go","line":46,"text":"func (host *emitHost) GetModeForUsageLocation(file ast.HasFileName, moduleSpecifier *ast.StringLiteralLike) core.ResolutionMode {"},
  {"file":"emitHost.go","line":47,"text":"\treturn host.program.GetModeForUsageLocation(file, moduleSpecifier)"},
  {"file":"emitHost.go","line":48,"text":"}"},
  {"file":"emitHost.go","line":50,"text":"func (host *emitHost) GetResolvedModuleFromModuleSpecifier(file ast.HasFileName, moduleSpecifier *ast.StringLiteralLike) *module.ResolvedModule {"},
  {"file":"emitHost.go","line":51,"text":"\treturn host.program.GetResolvedModuleFromModuleSpecifier(file, moduleSpecifier)"},
  {"file":"emitHost.go","line":52,"text":"}"},
  {"file":"emitHost.go","line":54,"text":"func (host *emitHost) GetDefaultResolutionModeForFile(file ast.HasFileName) core.ResolutionMode {"},
  {"file":"emitHost.go","line":55,"text":"\treturn host.program.GetDefaultResolutionModeForFile(file)"},
  {"file":"emitHost.go","line":56,"text":"}"},
  {"file":"emitHost.go","line":58,"text":"func (host *emitHost) GetEmitModuleFormatOfFile(file ast.HasFileName) core.ModuleKind {"},
  {"file":"emitHost.go","line":59,"text":"\treturn host.program.GetEmitModuleFormatOfFile(file)"},
  {"file":"emitHost.go","line":60,"text":"}"},
  {"file":"emitHost.go","line":62,"text":"func (host *emitHost) FileExists(path string) bool {"},
  {"file":"emitHost.go","line":63,"text":"\treturn host.program.FileExists(path)"},
  {"file":"emitHost.go","line":64,"text":"}"},
  {"file":"emitHost.go","line":66,"text":"func (host *emitHost) GetGlobalTypingsCacheLocation() string {"},
  {"file":"emitHost.go","line":67,"text":"\treturn host.program.GetGlobalTypingsCacheLocation()"},
  {"file":"emitHost.go","line":68,"text":"}"},
  {"file":"emitHost.go","line":70,"text":"func (host *emitHost) GetNearestAncestorDirectoryWithPackageJson(dirname string) string {"},
  {"file":"emitHost.go","line":71,"text":"\treturn host.program.GetNearestAncestorDirectoryWithPackageJson(dirname)"},
  {"file":"emitHost.go","line":72,"text":"}"},
  {"file":"emitHost.go","line":74,"text":"func (host *emitHost) GetPackageJsonInfo(pkgJsonPath string) *packagejson.InfoCacheEntry {"},
  {"file":"emitHost.go","line":75,"text":"\treturn host.program.GetPackageJsonInfo(pkgJsonPath)"},
  {"file":"emitHost.go","line":76,"text":"}"},
  {"file":"emitHost.go","line":78,"text":"func (host *emitHost) GetSourceOfProjectReferenceIfOutputIncluded(file ast.HasFileName) string {"},
  {"file":"emitHost.go","line":79,"text":"\treturn host.program.GetSourceOfProjectReferenceIfOutputIncluded(file)"},
  {"file":"emitHost.go","line":80,"text":"}"},
  {"file":"emitHost.go","line":82,"text":"func (host *emitHost) GetProjectReferenceFromSource(path tspath.Path) *tsoptions.SourceOutputAndProjectReference {"},
  {"file":"emitHost.go","line":83,"text":"\treturn host.program.GetProjectReferenceFromSource(path)"},
  {"file":"emitHost.go","line":84,"text":"}"},
  {"file":"emitHost.go","line":86,"text":"func (host *emitHost) GetRedirectTargets(path tspath.Path) []string {"},
  {"file":"emitHost.go","line":87,"text":"\treturn host.program.GetRedirectTargets(path)"},
  {"file":"emitHost.go","line":88,"text":"}"},
  {"file":"emitHost.go","line":90,"text":"func (host *emitHost) GetEffectiveDeclarationFlags(node *ast.Node, flags ast.ModifierFlags) ast.ModifierFlags {"},
  {"file":"emitHost.go","line":91,"text":"\treturn host.GetEmitResolver().GetEffectiveDeclarationFlags(node, flags)"},
  {"file":"emitHost.go","line":92,"text":"}"},
  {"file":"emitHost.go","line":94,"text":"func (host *emitHost) GetOutputPathsFor(file *ast.SourceFile, forceDtsPaths bool) declarations.OutputPaths {"},
  {"file":"emitHost.go","line":96,"text":"\treturn outputpaths.GetOutputPathsFor(file, host.Options(), host, forceDtsPaths)"},
  {"file":"emitHost.go","line":97,"text":"}"},
  {"file":"emitHost.go","line":99,"text":"func (host *emitHost) GetResolutionModeOverride(node *ast.Node) core.ResolutionMode {"},
  {"file":"emitHost.go","line":100,"text":"\treturn host.GetEmitResolver().GetResolutionModeOverride(node)"},
  {"file":"emitHost.go","line":101,"text":"}"},
  {"file":"emitHost.go","line":103,"text":"func (host *emitHost) GetSourceFileFromReference(origin *ast.SourceFile, ref *ast.FileReference) *ast.SourceFile {"},
  {"file":"emitHost.go","line":104,"text":"\treturn host.program.GetSourceFileFromReference(origin, ref)"},
  {"file":"emitHost.go","line":105,"text":"}"},
  {"file":"emitHost.go","line":107,"text":"func (host *emitHost) Options() *core.CompilerOptions { return host.program.Options() }"},
  {"file":"emitHost.go","line":108,"text":"func (host *emitHost) SourceFiles() []*ast.SourceFile { return host.program.SourceFiles() }"},
  {"file":"emitHost.go","line":109,"text":"func (host *emitHost) GetCurrentDirectory() string    { return host.program.GetCurrentDirectory() }"},
  {"file":"emitHost.go","line":110,"text":"func (host *emitHost) CommonSourceDirectory() string  { return host.program.CommonSourceDirectory() }"},
  {"file":"emitHost.go","line":111,"text":"func (host *emitHost) UseCaseSensitiveFileNames() bool {"},
  {"file":"emitHost.go","line":112,"text":"\treturn host.program.UseCaseSensitiveFileNames()"},
  {"file":"emitHost.go","line":113,"text":"}"},
  {"file":"emitHost.go","line":115,"text":"func (host *emitHost) IsEmitBlocked(file string) bool {"},
  {"file":"emitHost.go","line":116,"text":"\treturn host.program.IsEmitBlocked(file)"},
  {"file":"emitHost.go","line":117,"text":"}"},
  {"file":"emitHost.go","line":119,"text":"func (host *emitHost) WriteFile(fileName string, text string) error {"},
  {"file":"emitHost.go","line":120,"text":"\treturn host.program.Host().FS().WriteFile(fileName, text)"},
  {"file":"emitHost.go","line":121,"text":"}"},
  {"file":"emitHost.go","line":123,"text":"func (host *emitHost) GetEmitResolver() printer.EmitResolver {"},
  {"file":"emitHost.go","line":124,"text":"\treturn host.emitResolver"},
  {"file":"emitHost.go","line":125,"text":"}"},
  {"file":"emitHost.go","line":127,"text":"func (host *emitHost) IsSourceFileFromExternalLibrary(file *ast.SourceFile) bool {"},
  {"file":"emitHost.go","line":128,"text":"\treturn host.program.IsSourceFileFromExternalLibrary(file)"},
  {"file":"emitHost.go","line":129,"text":"}"},
  {"file":"emitHost.go","line":131,"text":"func (host *emitHost) GetSymlinkCache() *symlinks.KnownSymlinks {"},
  {"file":"emitHost.go","line":132,"text":"\treturn host.program.GetSymlinkCache()"},
  {"file":"emitHost.go","line":133,"text":"}"},
  {"file":"emitHost.go","line":135,"text":"func (host *emitHost) ResolveModuleName(moduleName string, containingFile string, resolutionMode core.ResolutionMode) *module.ResolvedModule {"},
  {"file":"emitHost.go","line":136,"text":"\tresolved, _ := host.program.resolver.ResolveModuleName(moduleName, containingFile, resolutionMode, nil)"},
  {"file":"emitHost.go","line":137,"text":"\treturn resolved"},
  {"file":"emitHost.go","line":138,"text":"}"},
  {"file":"emitter.go","line":1,"text":"package compiler"},
  {"file":"emitter.go","line":3,"text":"import ("},
  {"file":"emitter.go","line":4,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"emitter.go","line":5,"text":"\t\"github.com/microsoft/typescript-go/internal/binder\""},
  {"file":"emitter.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"emitter.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"emitter.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/outputpaths\""},
  {"file":"emitter.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"file":"emitter.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/sourcemap\""},
  {"file":"emitter.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"file":"emitter.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/tracing\""},
  {"file":"emitter.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/transformers\""},
  {"file":"emitter.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/transformers/declarations\""},
  {"file":"emitter.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/transformers/estransforms\""},
  {"file":"emitter.go","line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/transformers/inliners\""},
  {"file":"emitter.go","line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/transformers/jsxtransforms\""},
];

export function compilerStrictParityLineText(file: string, line: number): string | undefined {
  return compilerStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function compilerStrictParityFiles(): readonly string[] {
  return [...new Set(compilerStrictParitySourceLines.map((entry) => entry.file))].sort();
}
