export {
  ExtensionLifecycleEvent,
  ExtensionDiagnosticStore,
  ExtensionFactResolver,
  ExtensionFactStore,
  ExtensionHost,
  ExtensionHostDiagnosticCode,
  ProviderRegistry,
  TstsProviderContractVersion,
  attachExtensionHost,
  attachExtensionHostToProgram,
  defineExtensionFactKey,
  getExtensionHost,
  hasExtensionHost,
} from "./host.js";
export {
  ExtensionConsumerQueries,
  createExtensionConsumerQueries,
} from "./consumer.js";
export {
  createSourceSemanticsExtension,
  sourcePrimitive,
} from "./source-semantics.js";
export {
  finalizeExtensionSemantics,
} from "./compiler-integration.js";
export {
  ExtensionObservationPoint,
  acceptObservation,
  deferObservation,
  rejectObservation,
} from "./observations.js";
export {
  argumentPassingFactKey,
  associatedTypeFactKey,
  attributeFactKey,
  canonicalIdentityFactKey,
  contextualTargetTypeFactKey,
  constGenericFactKey,
  defaultValueFactKey,
  fieldFactKey,
  flowStateFactKey,
  functionPointerFactKey,
  instantiatedTargetTypeFactKey,
  pointerFactKey,
  providerTypeFamilyFactKey,
  providerVirtualDeclarationFactKey,
  runtimeCarrierFactKey,
  selectedTargetSignatureFactKey,
  sourcePrimitiveFactKey,
  structFactKey,
  targetCallArgumentConversionFactKey,
  targetCallArgumentPassingFactKey,
  targetConversionFactKey,
  targetBindingFactKey,
  targetOperationFactKey,
} from "./facts.js";

export type {
  AttachExtensionHostToProgramOptions,
  CompilerExtension,
  CompilerExtensionKind,
  CompilerExtensionIdentity,
  ExtendedProgram,
  ExtensionCapabilitySpec,
  ExtensionCompositionSpec,
  ExtensionDependencySpec,
  ExtensionDiagnostic,
  ExtensionDiagnosticCategory,
  ExtensionDiagnosticRange,
  ExtensionDiagnosticSourceSpan,
  ExtensionEvidence,
  ExtensionFactEntry,
  ExtensionFactKey,
  ExtensionFactKeyOptions,
  ExtensionFactResolution,
  ExtensionFactResolverCallback,
  ExtensionFactResolverContext,
  ExtensionFactSubject,
  ExtensionFactWriteResult,
  ExtensionHostOptions,
  ExtensionInitializeContext,
  ExtensionLifecycleContext,
  ExtensionLifecycleHook,
  ProviderDeclarationKind,
  ProviderDeclarationModel,
  ProviderExportKind,
  ProviderExportDeclaration,
  ProviderHeritageDeclaration,
  ProviderIdentity,
  ProviderImportDeclaration,
  ProviderImportRequestKind,
  ProviderImportSlice,
  ProviderImportSliceKind,
  ProviderMemberDeclaration,
  ProviderModuleContext,
  ProviderModuleResolution,
  ProviderModuleResolveResult,
  ProviderResolutionMode,
  ProviderOwnership,
  ProviderParameterDeclaration,
  ProviderPropertyName,
  ProviderRequestedExport,
  ProviderResolvedModule,
  ProviderVirtualModuleArtifact,
  ProviderTypeFamilyDeclaration,
  RequiredProviderModuleSpec,
  ProviderVirtualDeclarationDocument,
  ProviderSignatureDeclaration,
  ProviderTypeParameterDeclaration,
  ProviderTypeExpression,
  SourceFileBoundLifecycleRequest,
  TargetBindingProvider,
  TargetIdentity,
  TargetSemanticProvider,
  ProviderWellKnownSymbolName,
  BeforeSemanticsFinalizedLifecycleRequest,
} from "./host.js";
export type {
  SourceCallMarkerKind,
  SourceSemanticsExtensionOptions,
  SourceCallMarkerDeclaration,
  SourceSemanticsExportDeclaration,
  SourceSemanticsModuleCapability,
  SourceSemanticsModule,
  SourceSemanticsModuleIdentity,
  SourcePrimitiveDeclaration,
  SourceTypeMarkerKind,
  SourceTypeMarkerDeclaration,
} from "./source-semantics.js";
export type {
  CheckedCallMappingRequest,
  CheckedCallMappingResult,
  CheckedConversionMappingRequest,
  CheckedConversionMappingResult,
  CheckedElementAccessMappingRequest,
  CheckedIterationKind,
  CheckedIterationMappingRequest,
  CheckedOperationMappingResult,
  CheckedOperationObservationContext,
  CheckedOperationObservationPointName,
  CheckedOperatorMappingRequest,
  CheckedPropertyAccessMappingRequest,
  ContextualTargetTypeRequest,
  ContextualTargetTypeResult,
  ExtensionCompilerQueryContext,
  ExtensionFlowUseValidationRequest,
  ExtensionFlowUseValidationResult,
  ExtensionObservation,
  ExtensionObservationContext,
  ExtensionObservationHook,
  ExtensionObservationMap,
  ExtensionObservationPhase,
  ExtensionObservationPointName,
  ExtensionObservationRequest,
  ExtensionObservationResponse,
  ExtensionObservationResult,
  ExtensionObservationRunOptions,
  ImmediateExtensionObservationContext,
  ImmediateExtensionObservationPointName,
  PostCheckAssignabilityObservationRequest,
  RuntimeCarrierFactRequest,
  RuntimeCarrierFactResult,
  TargetConstraintValidationRequest,
} from "./observations.js";
export type {
  ArgumentPassingFact,
  ArgumentPassingMode,
  CheckedAccessMode,
  CheckedCallKind,
  AssociatedTypeFact,
  AttributeFact,
  ContextualTargetTypeFact,
  DefaultValueFact,
  ExtensionCanonicalIdentity,
  ExtensionCanonicalIdentityKind,
  ExtensionImportKind,
  ConstGenericFact,
  FieldFact,
  FlowStateFact,
  FunctionPointerFact,
  InstantiatedTargetTypeFact,
  PointerFact,
  ProviderDeclarationIdentity,
  ProviderMemberKey,
  ProviderTypeFamilyFact,
  ProviderTypeFamilyVariantFact,
  ProviderVirtualDeclarationFact,
  RuntimeCarrierFact,
  RuntimeCarrierProvenance,
  SelectedSourceTypeEvidence,
  SelectedSourceValueEvidence,
  SelectedTargetSignatureFact,
  SourceSelectedCallArgumentBinding,
  SourceSelectedMethodTypeArgument,
  SourceSelectedSignatureKind,
  SourceSelectedSignatureParameter,
  SourcePointerMutability,
  SourcePrimitiveFact,
  SourcePrimitiveKind,
  StructFact,
  TargetBindingFact,
  TargetCallArgumentConversionSlot,
  TargetConstraint,
  TargetCallArgumentConversionFact,
  TargetCallArgumentPassingFact,
  TargetConversionFact,
  TargetMember,
  TargetOperationFact,
  TargetOperationProvenance,
  TargetParameter,
  TargetSignatureSelection,
  TargetTypeParameter,
  TargetTypeRef,
} from "./facts.js";
