export {
  ExtensionDiagnosticStore,
  ExtensionFactResolver,
  ExtensionFactStore,
  ExtensionHost,
  ExtensionHostDiagnosticCode,
  ExtensionMetadataRegistry,
  attachExtensionHost,
  defineExtensionFactKey,
  getExtensionHost,
  hasExtensionHost,
} from "./host.js";
export {
  ExtensionDecisionQuestion,
  acceptDecision,
  deferDecision,
  rejectDecision,
} from "./decisions.js";
export {
  argumentPassingFactKey,
  associatedTypeFactKey,
  constGenericFactKey,
  flowStateFactKey,
  instantiatedTargetTypeFactKey,
  selectedTargetSignatureFactKey,
  sourcePrimitiveFactKey,
  surfaceOperationFactKey,
  targetBindingFactKey,
} from "./facts.js";

export type {
  CompilerExtension,
  CompilerExtensionIdentity,
  ExtendedProgram,
  ExtensionCapabilitySpec,
  ExtensionDependencySpec,
  ExtensionDiagnostic,
  ExtensionDiagnosticCategory,
  ExtensionEvidence,
  ExtensionFactEntry,
  ExtensionFactKey,
  ExtensionFactKeyOptions,
  ExtensionFactResolution,
  ExtensionFactResolverCallback,
  ExtensionFactResolverContext,
  ExtensionFactSubject,
  ExtensionFactWriteResult,
  ExtensionHostOptions,
  ExtensionInitializeContext,
  TargetBindingMetadataHeader,
} from "./host.js";
export type {
  AssignabilityRequest,
  ContextualTypeRequest,
  ContextualTypeResult,
  ExtensionDecision,
  ExtensionDecisionContext,
  ExtensionDecisionHook,
  ExtensionDecisionResult,
  ExtensionDecisionRunOptions,
  InferTypeArgumentsRequest,
  InferTypeArgumentsResult,
  ResolveCallRequest,
  ResolveCallResult,
  ResolveElementAccessRequest,
  ResolveOperationResult,
  ResolveOperatorRequest,
  ResolvePropertyAccessRequest,
  SatisfiesConstraintRequest,
  ValidateFlowUseRequest,
  ValidateFlowUseResult,
} from "./decisions.js";
export type {
  ArgumentPassingFact,
  ArgumentPassingMode,
  AssociatedTypeFact,
  AttributeFact,
  ConstGenericFact,
  FieldFact,
  FlowStateFact,
  FunctionPointerFact,
  InstantiatedTargetTypeFact,
  PointerFact,
  SelectedTargetSignatureFact,
  SourcePointerMutability,
  SourcePrimitiveFact,
  SourcePrimitiveKind,
  StructFact,
  SurfaceOperationFact,
  TargetBindingFact,
  TargetConstraint,
  TargetMember,
  TargetParameter,
  TargetTypeParameter,
  TargetTypeRef,
} from "./facts.js";
