export {
  ExtensionDiagnosticStore,
  ExtensionFactResolver,
  ExtensionFactStore,
  ExtensionHost,
  ExtensionHostDiagnosticCode,
  ProviderRegistry,
  TstsSourceProviderContractVersion,
  attachExtensionHost,
  attachExtensionHostToProgram,
  defineExtensionFactKey,
  getExtensionHost,
  hasExtensionHost,
} from "./host.js";
export {
  createSourceSemanticsExtension,
  sourceSemanticsExtensionId,
  sourcePrimitive,
} from "./source-semantics.js";
export {
  SourceFactQueries,
  createSourceFactQueries,
} from "./consumer.js";
export {
  argumentPassingFactKey,
  associatedTypeFactKey,
  attributeFactKey,
  canonicalIdentityFactKey,
  constGenericFactKey,
  defaultValueFactKey,
  fieldFactKey,
  flowStateFactKey,
  functionPointerFactKey,
  pointerFactKey,
  providerTypeFamilyFactKey,
  providerVirtualDeclarationFactKey,
  sourcePrimitiveFactKey,
  structFactKey,
} from "./facts.js";

export type {
  AttachExtensionHostToProgramOptions,
  CompilerExtension,
  CompilerExtensionIdentity,
  CompilerExtensionKind,
  ExtendedProgram,
  ExtensionCapabilitySpec,
  ExtensionCompositionSpec,
  ExtensionDependencySpec,
  ExtensionDiagnostic,
  ExtensionDiagnosticCategory,
  ExtensionDiagnosticRange,
  ExtensionDiagnosticSourceSpan,
  ExtensionEvidence,
  ExtensionFactEntry,
  ExtensionFactKey,
  ExtensionFactKeyOptions,
  ExtensionFactResolution,
  ExtensionFactResolverCallback,
  ExtensionFactResolverContext,
  ExtensionFactSubject,
  ExtensionFactWriteResult,
  ExtensionHostOptions,
  ExtensionInitializeContext,
  ProviderDeclarationKind,
  ProviderDeclarationModel,
  ProviderExportDeclaration,
  ProviderExportKind,
  ProviderHeritageDeclaration,
  ProviderIdentity,
  ProviderImportDeclaration,
  ProviderImportRequestKind,
  ProviderImportSlice,
  ProviderImportSliceKind,
  ProviderMemberDeclaration,
  ProviderModuleContext,
  ProviderModuleResolution,
  ProviderModuleResolveResult,
  ProviderOwnership,
  ProviderParameterDeclaration,
  ProviderPropertyName,
  ProviderRequestedExport,
  ProviderResolutionMode,
  ProviderResolvedModule,
  ProviderSignatureDeclaration,
  ProviderTypeExpression,
  ProviderTypeFamilyDeclaration,
  ProviderTypeParameterDeclaration,
  ProviderVirtualDeclarationDocument,
  ProviderVirtualModuleArtifact,
  ProviderWellKnownSymbolName,
  RequiredProviderModuleSpec,
  SourceAnalysisContext,
  SourceDeclarationProvider,
} from "./host.js";
export type {
  ReadonlySourceFactResolver,
} from "./consumer.js";
export type {
  CheckedSourceProgram,
  SourceFileQueries,
  SourceProgramQueries,
} from "./source-program.js";
export type {
  SourceCallMarkerDeclaration,
  SourceCallMarkerKind,
  SourcePrimitiveDeclaration,
  SourceSemanticsExportDeclaration,
  SourceSemanticsExtensionOptions,
  SourceSemanticsModule,
  SourceSemanticsModuleCapability,
  SourceSemanticsModuleIdentity,
  SourceTypeMarkerDeclaration,
  SourceTypeMarkerKind,
} from "./source-semantics.js";
export type {
  ArgumentPassingFact,
  ArgumentPassingMode,
  AssociatedTypeFact,
  AttributeFact,
  ConstGenericFact,
  DefaultValueFact,
  ExtensionCanonicalIdentity,
  ExtensionCanonicalIdentityKind,
  ExtensionImportKind,
  FieldFact,
  FlowStateFact,
  FunctionPointerFact,
  PointerFact,
  ProviderDeclarationIdentity,
  ProviderMemberKey,
  ProviderTypeFamilyFact,
  ProviderTypeFamilyVariantFact,
  ProviderVirtualDeclarationFact,
  SourcePointerMutability,
  SourcePrimitiveFact,
  SourcePrimitiveKind,
  StructFact,
} from "./facts.js";
