/**
 * Strict TS-Go parity gap map for `vfs`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const vfsStrictParityUpstreamModule = "vfs";
export const vfsStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"cachedvfs/cachedvfs.go","line":1,"text":"package cachedvfs"},
  {"file":"cachedvfs/cachedvfs.go","line":3,"text":"import ("},
  {"file":"cachedvfs/cachedvfs.go","line":4,"text":"\t\"sync/atomic\""},
  {"file":"cachedvfs/cachedvfs.go","line":5,"text":"\t\"time\""},
  {"file":"cachedvfs/cachedvfs.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"cachedvfs/cachedvfs.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"file":"cachedvfs/cachedvfs.go","line":9,"text":")"},
  {"file":"cachedvfs/cachedvfs.go","line":11,"text":"type FS struct {"},
  {"file":"cachedvfs/cachedvfs.go","line":12,"text":"\tfs      vfs.FS"},
  {"file":"cachedvfs/cachedvfs.go","line":13,"text":"\tenabled atomic.Bool"},
  {"file":"cachedvfs/cachedvfs.go","line":15,"text":"\tdirectoryExistsCache      collections.SyncMap[string, bool]"},
  {"file":"cachedvfs/cachedvfs.go","line":16,"text":"\tfileExistsCache           collections.SyncMap[string, bool]"},
  {"file":"cachedvfs/cachedvfs.go","line":17,"text":"\tgetAccessibleEntriesCache collections.SyncMap[string, vfs.Entries]"},
  {"file":"cachedvfs/cachedvfs.go","line":18,"text":"\trealpathCache             collections.SyncMap[string, string]"},
  {"file":"cachedvfs/cachedvfs.go","line":19,"text":"\tstatCache                 collections.SyncMap[string, vfs.FileInfo]"},
  {"file":"cachedvfs/cachedvfs.go","line":20,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":22,"text":"var _ vfs.FS = (*FS)(nil)"},
  {"file":"cachedvfs/cachedvfs.go","line":24,"text":"func From(fs vfs.FS) *FS {"},
  {"file":"cachedvfs/cachedvfs.go","line":25,"text":"\tfsys := &FS{fs: fs}"},
  {"file":"cachedvfs/cachedvfs.go","line":26,"text":"\tfsys.enabled.Store(true)"},
  {"file":"cachedvfs/cachedvfs.go","line":27,"text":"\treturn fsys"},
  {"file":"cachedvfs/cachedvfs.go","line":28,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":30,"text":"func (fsys *FS) DisableAndClearCache() {"},
  {"file":"cachedvfs/cachedvfs.go","line":31,"text":"\tif fsys.enabled.CompareAndSwap(true, false) {"},
  {"file":"cachedvfs/cachedvfs.go","line":32,"text":"\t\tfsys.ClearCache()"},
  {"file":"cachedvfs/cachedvfs.go","line":33,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":34,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":36,"text":"func (fsys *FS) Enable() {"},
  {"file":"cachedvfs/cachedvfs.go","line":37,"text":"\tfsys.enabled.Store(true)"},
  {"file":"cachedvfs/cachedvfs.go","line":38,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":40,"text":"func (fsys *FS) ClearCache() {"},
  {"file":"cachedvfs/cachedvfs.go","line":41,"text":"\tfsys.directoryExistsCache.Clear()"},
  {"file":"cachedvfs/cachedvfs.go","line":42,"text":"\tfsys.fileExistsCache.Clear()"},
  {"file":"cachedvfs/cachedvfs.go","line":43,"text":"\tfsys.getAccessibleEntriesCache.Clear()"},
  {"file":"cachedvfs/cachedvfs.go","line":44,"text":"\tfsys.realpathCache.Clear()"},
  {"file":"cachedvfs/cachedvfs.go","line":45,"text":"\tfsys.statCache.Clear()"},
  {"file":"cachedvfs/cachedvfs.go","line":46,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":48,"text":"func (fsys *FS) DirectoryExists(path string) bool {"},
  {"file":"cachedvfs/cachedvfs.go","line":49,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":50,"text":"\t\tif ret, ok := fsys.directoryExistsCache.Load(path); ok {"},
  {"file":"cachedvfs/cachedvfs.go","line":51,"text":"\t\t\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":52,"text":"\t\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":53,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":55,"text":"\tret := fsys.fs.DirectoryExists(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":57,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":58,"text":"\t\tfsys.directoryExistsCache.Store(path, ret)"},
  {"file":"cachedvfs/cachedvfs.go","line":59,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":61,"text":"\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":62,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":64,"text":"func (fsys *FS) FileExists(path string) bool {"},
  {"file":"cachedvfs/cachedvfs.go","line":65,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":66,"text":"\t\tif ret, ok := fsys.fileExistsCache.Load(path); ok {"},
  {"file":"cachedvfs/cachedvfs.go","line":67,"text":"\t\t\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":68,"text":"\t\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":69,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":71,"text":"\tret := fsys.fs.FileExists(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":73,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":74,"text":"\t\tfsys.fileExistsCache.Store(path, ret)"},
  {"file":"cachedvfs/cachedvfs.go","line":75,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":77,"text":"\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":78,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":80,"text":"func (fsys *FS) GetAccessibleEntries(path string) vfs.Entries {"},
  {"file":"cachedvfs/cachedvfs.go","line":81,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":82,"text":"\t\tif ret, ok := fsys.getAccessibleEntriesCache.Load(path); ok {"},
  {"file":"cachedvfs/cachedvfs.go","line":83,"text":"\t\t\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":84,"text":"\t\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":85,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":87,"text":"\tret := fsys.fs.GetAccessibleEntries(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":89,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":90,"text":"\t\tfsys.getAccessibleEntriesCache.Store(path, ret)"},
  {"file":"cachedvfs/cachedvfs.go","line":91,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":93,"text":"\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":94,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":96,"text":"func (fsys *FS) ReadFile(path string) (contents string, ok bool) {"},
  {"file":"cachedvfs/cachedvfs.go","line":97,"text":"\treturn fsys.fs.ReadFile(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":98,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":100,"text":"func (fsys *FS) Realpath(path string) string {"},
  {"file":"cachedvfs/cachedvfs.go","line":101,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":102,"text":"\t\tif ret, ok := fsys.realpathCache.Load(path); ok {"},
  {"file":"cachedvfs/cachedvfs.go","line":103,"text":"\t\t\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":104,"text":"\t\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":105,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":107,"text":"\tret := fsys.fs.Realpath(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":109,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":110,"text":"\t\tfsys.realpathCache.Store(path, ret)"},
  {"file":"cachedvfs/cachedvfs.go","line":111,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":113,"text":"\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":114,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":116,"text":"func (fsys *FS) Remove(path string) error {"},
  {"file":"cachedvfs/cachedvfs.go","line":117,"text":"\treturn fsys.fs.Remove(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":118,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":120,"text":"func (fsys *FS) Chtimes(path string, aTime time.Time, mTime time.Time) error {"},
  {"file":"cachedvfs/cachedvfs.go","line":121,"text":"\treturn fsys.fs.Chtimes(path, aTime, mTime)"},
  {"file":"cachedvfs/cachedvfs.go","line":122,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":124,"text":"func (fsys *FS) Stat(path string) vfs.FileInfo {"},
  {"file":"cachedvfs/cachedvfs.go","line":125,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":126,"text":"\t\tif ret, ok := fsys.statCache.Load(path); ok {"},
  {"file":"cachedvfs/cachedvfs.go","line":127,"text":"\t\t\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":128,"text":"\t\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":129,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":131,"text":"\tret := fsys.fs.Stat(path)"},
  {"file":"cachedvfs/cachedvfs.go","line":133,"text":"\tif fsys.enabled.Load() {"},
  {"file":"cachedvfs/cachedvfs.go","line":134,"text":"\t\tfsys.statCache.Store(path, ret)"},
  {"file":"cachedvfs/cachedvfs.go","line":135,"text":"\t}"},
  {"file":"cachedvfs/cachedvfs.go","line":137,"text":"\treturn ret"},
  {"file":"cachedvfs/cachedvfs.go","line":138,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":140,"text":"func (fsys *FS) UseCaseSensitiveFileNames() bool {"},
  {"file":"cachedvfs/cachedvfs.go","line":141,"text":"\treturn fsys.fs.UseCaseSensitiveFileNames()"},
  {"file":"cachedvfs/cachedvfs.go","line":142,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":144,"text":"func (fsys *FS) WalkDir(root string, walkFn vfs.WalkDirFunc) error {"},
  {"file":"cachedvfs/cachedvfs.go","line":145,"text":"\treturn fsys.fs.WalkDir(root, walkFn)"},
  {"file":"cachedvfs/cachedvfs.go","line":146,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":148,"text":"func (fsys *FS) WriteFile(path string, data string) error {"},
  {"file":"cachedvfs/cachedvfs.go","line":149,"text":"\treturn fsys.fs.WriteFile(path, data)"},
  {"file":"cachedvfs/cachedvfs.go","line":150,"text":"}"},
  {"file":"cachedvfs/cachedvfs.go","line":152,"text":"func (fsys *FS) AppendFile(path string, data string) error {"},
  {"file":"cachedvfs/cachedvfs.go","line":153,"text":"\treturn fsys.fs.AppendFile(path, data)"},
  {"file":"cachedvfs/cachedvfs.go","line":154,"text":"}"},
  {"file":"internal/internal.go","line":1,"text":"package internal"},
  {"file":"internal/internal.go","line":3,"text":"import ("},
  {"file":"internal/internal.go","line":4,"text":"\t\"encoding/binary\""},
  {"file":"internal/internal.go","line":5,"text":"\t\"fmt\""},
  {"file":"internal/internal.go","line":6,"text":"\t\"io/fs\""},
  {"file":"internal/internal.go","line":7,"text":"\t\"strings\""},
  {"file":"internal/internal.go","line":8,"text":"\t\"unicode/utf16\""},
  {"file":"internal/internal.go","line":9,"text":"\t\"unsafe\""},
  {"file":"internal/internal.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"internal/internal.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"file":"internal/internal.go","line":13,"text":")"},
  {"file":"internal/internal.go","line":15,"text":"type Common struct {"},
  {"file":"internal/internal.go","line":16,"text":"\tRootFor        func(root string) fs.FS"},
  {"file":"internal/internal.go","line":17,"text":"\tIsReparsePoint func(path string) bool"},
  {"file":"internal/internal.go","line":18,"text":"}"},
  {"file":"internal/internal.go","line":20,"text":"func RootLength(p string) int {"},
  {"file":"internal/internal.go","line":21,"text":"\tl := tspath.GetEncodedRootLength(p)"},
  {"file":"internal/internal.go","line":22,"text":"\tif l == 0 {"},
  {"file":"internal/internal.go","line":23,"text":"\t\tpanic(fmt.Sprintf(\"vfs: path %q is not absolute\", p))"},
  {"file":"internal/internal.go","line":24,"text":"\t} else if l < 0 {"},
  {"file":"internal/internal.go","line":25,"text":"\t\treturn ^l"},
  {"file":"internal/internal.go","line":26,"text":"\t}"},
  {"file":"internal/internal.go","line":27,"text":"\treturn l"},
  {"file":"internal/internal.go","line":28,"text":"}"},
  {"file":"internal/internal.go","line":30,"text":"func SplitPath(p string) (rootName, rest string) {"},
  {"file":"internal/internal.go","line":31,"text":"\tp = tspath.NormalizePath(p)"},
  {"file":"internal/internal.go","line":32,"text":"\tl := RootLength(p)"},
  {"file":"internal/internal.go","line":33,"text":"\trootName, rest = p[:l], p[l:]"},
  {"file":"internal/internal.go","line":34,"text":"\trest = tspath.RemoveTrailingDirectorySeparator(rest)"},
  {"file":"internal/internal.go","line":35,"text":"\treturn rootName, rest"},
  {"file":"internal/internal.go","line":36,"text":"}"},
  {"file":"internal/internal.go","line":38,"text":"func (vfs *Common) RootAndPath(path string) (fsys fs.FS, rootName string, rest string) {"},
  {"file":"internal/internal.go","line":39,"text":"\trootName, rest = SplitPath(path)"},
  {"file":"internal/internal.go","line":40,"text":"\tif rest == \"\" {"},
  {"file":"internal/internal.go","line":41,"text":"\t\trest = \".\""},
  {"file":"internal/internal.go","line":42,"text":"\t}"},
  {"file":"internal/internal.go","line":43,"text":"\treturn vfs.RootFor(rootName), rootName, rest"},
  {"file":"internal/internal.go","line":44,"text":"}"},
  {"file":"internal/internal.go","line":46,"text":"func (vfs *Common) Stat(path string) vfs.FileInfo {"},
  {"file":"internal/internal.go","line":47,"text":"\tfsys, _, rest := vfs.RootAndPath(path)"},
  {"file":"internal/internal.go","line":48,"text":"\tif fsys == nil {"},
  {"file":"internal/internal.go","line":49,"text":"\t\treturn nil"},
  {"file":"internal/internal.go","line":50,"text":"\t}"},
  {"file":"internal/internal.go","line":51,"text":"\tstat, err := fs.Stat(fsys, rest)"},
  {"file":"internal/internal.go","line":52,"text":"\tif err != nil {"},
  {"file":"internal/internal.go","line":53,"text":"\t\treturn nil"},
  {"file":"internal/internal.go","line":54,"text":"\t}"},
  {"file":"internal/internal.go","line":55,"text":"\treturn stat"},
  {"file":"internal/internal.go","line":56,"text":"}"},
  {"file":"internal/internal.go","line":58,"text":"func (vfs *Common) FileExists(path string) bool {"},
  {"file":"internal/internal.go","line":59,"text":"\tstat := vfs.Stat(path)"},
  {"file":"internal/internal.go","line":60,"text":"\treturn stat != nil && !stat.IsDir()"},
];

export function vfsStrictParityLineText(file: string, line: number): string | undefined {
  return vfsStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function vfsStrictParityFiles(): readonly string[] {
  return [...new Set(vfsStrictParitySourceLines.map((entry) => entry.file))].sort();
}
