import type { bool, int } from "../../go/scalars.js";

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::type::GeneratedIdentifierFlags","kind":"type","status":"implemented","sigHash":"eccc0436f5d9572d1d6d5cce1d5c9208beb6459fb61b7949481ce72db427cb02"}
 *
 * Go source:
 * GeneratedIdentifierFlags int
 */
export type GeneratedIdentifierFlags = int;

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::constGroup::GeneratedIdentifierFlagsNone+GeneratedIdentifierFlagsAuto+GeneratedIdentifierFlagsLoop+GeneratedIdentifierFlagsUnique+GeneratedIdentifierFlagsNode+GeneratedIdentifierFlagsKindMask+GeneratedIdentifierFlagsReservedInNestedScopes+GeneratedIdentifierFlagsOptimistic+GeneratedIdentifierFlagsFileLevel+GeneratedIdentifierFlagsAllowNameSubstitution","kind":"constGroup","status":"implemented","sigHash":"2b8b2cc1070aa4df80b4de52988aebce3735178a8d70af234836f19785ffd5c5"}
 *
 * Go source:
 * const (
 * 	// Kind
 * 
 * 	GeneratedIdentifierFlagsNone     = iota // Not automatically generated.
 * 	GeneratedIdentifierFlagsAuto            // Automatically generated identifier.
 * 	GeneratedIdentifierFlagsLoop            // Automatically generated identifier with a preference for '_i'.
 * 	GeneratedIdentifierFlagsUnique          // Unique name based on the 'text' property.
 * 	GeneratedIdentifierFlagsNode            // Unique name based on the node in the 'Node' property.
 * 	GeneratedIdentifierFlagsKindMask = 7    // Mask to extract the kind of identifier from its flags.
 * 
 * 	// Flags
 * 
 * 	GeneratedIdentifierFlagsReservedInNestedScopes = 1 << 3 // Reserve the generated name in nested scopes
 * 	GeneratedIdentifierFlagsOptimistic             = 1 << 4 // First instance won't use '_#' if there's no conflict
 * 	GeneratedIdentifierFlagsFileLevel              = 1 << 5 // Use only the file identifiers list and not generated names to search for conflicts
 * 	GeneratedIdentifierFlagsAllowNameSubstitution  = 1 << 6 // Used by `module.ts` to indicate generated nodes which can have substitutions performed upon them (as they were generated by an earlier transform phase)
 * )
 */
export const GeneratedIdentifierFlagsNone: int = 0;
export const GeneratedIdentifierFlagsAuto: int = 1;
export const GeneratedIdentifierFlagsLoop: int = 2;
export const GeneratedIdentifierFlagsUnique: int = 3;
export const GeneratedIdentifierFlagsNode: int = 4;
export const GeneratedIdentifierFlagsKindMask: int = 7;
export const GeneratedIdentifierFlagsReservedInNestedScopes: int = 1 << 3;
export const GeneratedIdentifierFlagsOptimistic: int = 1 << 4;
export const GeneratedIdentifierFlagsFileLevel: int = 1 << 5;
export const GeneratedIdentifierFlagsAllowNameSubstitution: int = 1 << 6;

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.Kind","kind":"method","status":"implemented","sigHash":"1ca78de9fab7026da2bae1875a93514bbd643338c7e4a64b511a6f898ca8e60f"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) Kind() GeneratedIdentifierFlags {
 * 	return f & GeneratedIdentifierFlagsKindMask
 * }
 */
export function GeneratedIdentifierFlags_Kind(receiver: GeneratedIdentifierFlags): GeneratedIdentifierFlags {
  return receiver & GeneratedIdentifierFlagsKindMask;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsAuto","kind":"method","status":"implemented","sigHash":"7893119c6efc3f614b703ac731662a9d9eb6ba77dd7be26c55818b797f2ce281"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsAuto() bool {
 * 	return f.Kind() == GeneratedIdentifierFlagsAuto
 * }
 */
export function GeneratedIdentifierFlags_IsAuto(receiver: GeneratedIdentifierFlags): bool {
  return GeneratedIdentifierFlags_Kind(receiver) === GeneratedIdentifierFlagsAuto;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsLoop","kind":"method","status":"implemented","sigHash":"88958ab25773d2c103bf0881cac251a97ef82292d82e0c5560965a6b2e8174e3"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsLoop() bool {
 * 	return f.Kind() == GeneratedIdentifierFlagsLoop
 * }
 */
export function GeneratedIdentifierFlags_IsLoop(receiver: GeneratedIdentifierFlags): bool {
  return GeneratedIdentifierFlags_Kind(receiver) === GeneratedIdentifierFlagsLoop;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsUnique","kind":"method","status":"implemented","sigHash":"8c1d9eecc978cfc76e83c3137fd684f3cf49afd90d375bd8d157ef514c0e0f2c"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsUnique() bool {
 * 	return f.Kind() == GeneratedIdentifierFlagsUnique
 * }
 */
export function GeneratedIdentifierFlags_IsUnique(receiver: GeneratedIdentifierFlags): bool {
  return GeneratedIdentifierFlags_Kind(receiver) === GeneratedIdentifierFlagsUnique;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsNode","kind":"method","status":"implemented","sigHash":"0920ddedd3191e51e10390ea115c6da64df92dfaa64e2f662923c2821174e156"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsNode() bool {
 * 	return f.Kind() == GeneratedIdentifierFlagsNode
 * }
 */
export function GeneratedIdentifierFlags_IsNode(receiver: GeneratedIdentifierFlags): bool {
  return GeneratedIdentifierFlags_Kind(receiver) === GeneratedIdentifierFlagsNode;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsReservedInNestedScopes","kind":"method","status":"implemented","sigHash":"51a5972e8c4a4ccafd5d1bd1e4c6021bbee77978857dabf0c4a0e3f57df56748"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsReservedInNestedScopes() bool {
 * 	return f&GeneratedIdentifierFlagsReservedInNestedScopes != 0
 * }
 */
export function GeneratedIdentifierFlags_IsReservedInNestedScopes(receiver: GeneratedIdentifierFlags): bool {
  return (receiver & GeneratedIdentifierFlagsReservedInNestedScopes) !== 0;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsOptimistic","kind":"method","status":"implemented","sigHash":"475c52ea6331a84b862cc989ef92457d60cab3ee4fa2602a39d251c3adf9de6b"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsOptimistic() bool {
 * 	return f&GeneratedIdentifierFlagsOptimistic != 0
 * }
 */
export function GeneratedIdentifierFlags_IsOptimistic(receiver: GeneratedIdentifierFlags): bool {
  return (receiver & GeneratedIdentifierFlagsOptimistic) !== 0;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.IsFileLevel","kind":"method","status":"implemented","sigHash":"58ca73582c783147573740b431256d59883270caa4d3e33128fb04574dfc60ce"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) IsFileLevel() bool {
 * 	return f&GeneratedIdentifierFlagsFileLevel != 0
 * }
 */
export function GeneratedIdentifierFlags_IsFileLevel(receiver: GeneratedIdentifierFlags): bool {
  return (receiver & GeneratedIdentifierFlagsFileLevel) !== 0;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/generatedidentifierflags.go::method::GeneratedIdentifierFlags.HasAllowNameSubstitution","kind":"method","status":"implemented","sigHash":"33ec1118f17726c59590b13c3ba14b0dc9a1799a08e5ec8a41316abe85ec5511"}
 *
 * Go source:
 * func (f GeneratedIdentifierFlags) HasAllowNameSubstitution() bool {
 * 	return f&GeneratedIdentifierFlagsAllowNameSubstitution != 0
 * }
 */
export function GeneratedIdentifierFlags_HasAllowNameSubstitution(receiver: GeneratedIdentifierFlags): bool {
  return (receiver & GeneratedIdentifierFlagsAllowNameSubstitution) !== 0;
}
