import type { bool, int } from "../../go/scalars.js";
import { GoFieldRef, GoNilMap, GoStringKey, type GoFunc, type GoMap, type GoPtr } from "../../go/compat.js";
import type { Node } from "../ast/spine.js";
import type { MemberName } from "../ast/generated/unions.js";
import type { NodeId } from "../ast/ids.js";
import { GetNodeId, GetExternalModuleName, IsNodeDescendantOf } from "../ast/utilities.js";
import { IsIdentifier, IsPrivateIdentifier, IsStringLiteral } from "../ast/generated/predicates.js";
import { KindClassDeclaration, KindClassExpression, KindComputedPropertyName, KindEnumDeclaration, KindExportAssignment, KindExportDeclaration, KindFunctionDeclaration, KindGetAccessor, KindIdentifier, KindImportDeclaration, KindJSImportDeclaration, KindMethodDeclaration, KindModuleDeclaration, KindPrivateIdentifier, KindSetAccessor } from "../ast/generated/kinds.js";
import { Node_Locals, Node_Text } from "../ast/ast.js";
import { Node_LocalsContainerData, Node_Name } from "../ast/spine.js";
import { SymbolFlagsValue, SymbolFlagsExportValue, SymbolFlagsAlias } from "../ast/symbolflags.js";
import { Set_Has, Set_Add } from "../collections/set.js";
import type { Set } from "../collections/set.js";
import type { AutoGenerateId, EmitContext } from "./emitcontext.js";
import { EmitContext_HasAutoGenerateInfo, EmitContext_GetNodeForGeneratedName } from "./emitcontext.js";
import type { GeneratedIdentifierFlags } from "./generatedidentifierflags.js";
import { GeneratedIdentifierFlagsAuto, GeneratedIdentifierFlagsLoop, GeneratedIdentifierFlagsNone, GeneratedIdentifierFlagsUnique } from "./generatedidentifierflags.js";
import { GeneratedIdentifierFlags_IsNode, GeneratedIdentifierFlags_Kind, GeneratedIdentifierFlags_IsOptimistic, GeneratedIdentifierFlags_IsReservedInNestedScopes, GeneratedIdentifierFlags_IsFileLevel } from "./generatedidentifierflags.js";
import { FormatGeneratedName, ensureLeadingHash, removeLeadingHash, makeIdentifierFromModuleName } from "./utilities.js";

import type { GoRef } from "../../go/compat.js";
/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::type::tempFlags","kind":"type","status":"implemented","sigHash":"743dd98db6ac806ced73789710bf9f48c2924a29522016b43a75017c04ea73e8"}
 *
 * Go source:
 * tempFlags int
 */
export type tempFlags = int;

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::constGroup::tempFlagsAuto+tempFlagsCountMask+tempFlags_i","kind":"constGroup","status":"implemented","sigHash":"ea9c6a0fbbd10057fb25325d8c3174bc621dc3922946aa69e0c0a047c7f75253"}
 *
 * Go source:
 * const (
 * 	tempFlagsAuto      tempFlags = 0x00000000 // No preferred name
 * 	tempFlagsCountMask tempFlags = 0x0FFFFFFF // Temp variable counter
 * 	tempFlags_i        tempFlags = 0x10000000 // Use/preference flag for '_i'
 * )
 */
export const tempFlagsAuto: tempFlags = 0x00000000;
export const tempFlagsCountMask: tempFlags = 0x0fffffff;
export const tempFlags_i: tempFlags = 0x10000000;

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::type::NameGenerator","kind":"type","status":"implemented","sigHash":"e129da42636dc88da2cace59d4f7c4daad8adc65022d14a494cd6b3cb09a6892"}
 *
 * Go source:
 * NameGenerator struct {
 * 	Context                            *EmitContext
 * 	IsFileLevelUniqueNameInCurrentFile func(string, bool) bool   // callback for Printer.isFileLevelUniqueNameInCurrentFile
 * 	GetTextOfNode                      func(*ast.Node) string    // callback for Printer.getTextOfNode
 * 	nodeIdToGeneratedName              map[ast.NodeId]string     // Map of generated names for specific nodes
 * 	nodeIdToGeneratedPrivateName       map[ast.NodeId]string     // Map of generated private names for specific nodes
 * 	autoGeneratedIdToGeneratedName     map[AutoGenerateId]string // Map of generated names for temp and loop variables
 * 	nameGenerationScope                *nameGenerationScope
 * 	privateNameGenerationScope         *nameGenerationScope
 * 	generatedNames                     collections.Set[string] // NOTE: Used to match Strada, but should be moved to nameGenerationScope after port is complete.
 * }
 */
export interface NameGenerator {
  Context: GoPtr<EmitContext>;
  IsFileLevelUniqueNameInCurrentFile: GoFunc<(arg0: string, arg1: bool) => bool>;
  GetTextOfNode: GoFunc<(arg0: GoPtr<Node>) => string>;
  nodeIdToGeneratedName: GoMap<NodeId, string>;
  nodeIdToGeneratedPrivateName: GoMap<NodeId, string>;
  autoGeneratedIdToGeneratedName: GoMap<AutoGenerateId, string>;
  nameGenerationScope: GoPtr<nameGenerationScope>;
  privateNameGenerationScope: GoPtr<nameGenerationScope>;
  generatedNames: Set<string>;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::type::nameGenerationScope","kind":"type","status":"implemented","sigHash":"c403fe9541a71be4524431b7099c9b193a2c0853a1b580cce16bdf5aa1b9211d"}
 *
 * Go source:
 * nameGenerationScope struct {
 * 	next                   *nameGenerationScope    // The next nameGenerationScope in the stack
 * 	tempFlags              tempFlags               // TempFlags for the current name generation scope.
 * 	formattedNameTempFlags map[string]tempFlags    // TempFlags for the current name generation scope.
 * 	reservedNames          collections.Set[string] // Names reserved in nested name generation scopes.
 * 	// generatedNames         collections.Set[string] // NOTE: generated names should be scoped after Strada port is complete.
 * }
 */
export interface nameGenerationScope {
  next: GoPtr<nameGenerationScope>;
  tempFlags: tempFlags;
  formattedNameTempFlags: GoMap<string, tempFlags>;
  reservedNames: Set<string>;
}

function nameGenerationScopeRef(receiver: NameGenerator): NonNullable<GoRef<GoPtr<nameGenerationScope>>> {
  return GoFieldRef(() => receiver.nameGenerationScope, (value) => { receiver.nameGenerationScope = value; });
}

function privateNameGenerationScopeRef(receiver: NameGenerator): NonNullable<GoRef<GoPtr<nameGenerationScope>>> {
  return GoFieldRef(() => receiver.privateNameGenerationScope, (value) => { receiver.privateNameGenerationScope = value; });
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.PushScope","kind":"method","status":"implemented","sigHash":"2ad09250ca60180e83c58a1da88b2fe4f6017857d4f72febf1b24b4d1494ba7a"}
 *
 * Go source:
 * func (g *NameGenerator) PushScope(reuseTempVariableScope bool) {
 * 	g.privateNameGenerationScope = &nameGenerationScope{next: g.privateNameGenerationScope}
 * 	if !reuseTempVariableScope {
 * 		g.nameGenerationScope = &nameGenerationScope{next: g.nameGenerationScope}
 * 	}
 * }
 */
export function NameGenerator_PushScope(receiver: GoPtr<NameGenerator>, reuseTempVariableScope: bool): void {
  receiver!.privateNameGenerationScope = {
    next: receiver!.privateNameGenerationScope,
    tempFlags: tempFlagsAuto,
    formattedNameTempFlags: new globalThis.Map(),
    reservedNames: { M: GoNilMap() },
  };
  if (!reuseTempVariableScope) {
    receiver!.nameGenerationScope = {
      next: receiver!.nameGenerationScope,
      tempFlags: tempFlagsAuto,
      formattedNameTempFlags: new globalThis.Map(),
      reservedNames: { M: GoNilMap() },
    };
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.PopScope","kind":"method","status":"implemented","sigHash":"9e1a854030ca57a7ab6f769926f531e013ec5c9a1d28d7717f1fa8d4b1dd57a1"}
 *
 * Go source:
 * func (g *NameGenerator) PopScope(reuseTempVariableScope bool) {
 * 	if g.privateNameGenerationScope != nil {
 * 		g.privateNameGenerationScope = g.privateNameGenerationScope.next
 * 	}
 * 	if !reuseTempVariableScope && g.nameGenerationScope != nil {
 * 		g.nameGenerationScope = g.nameGenerationScope.next
 * 	}
 * }
 */
export function NameGenerator_PopScope(receiver: GoPtr<NameGenerator>, reuseTempVariableScope: bool): void {
  if (receiver!.privateNameGenerationScope !== undefined) {
    receiver!.privateNameGenerationScope = receiver!.privateNameGenerationScope.next;
  }
  if (!reuseTempVariableScope && receiver!.nameGenerationScope !== undefined) {
    receiver!.nameGenerationScope = receiver!.nameGenerationScope.next;
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.getScope","kind":"method","status":"implemented","sigHash":"20b057f10628457f38f4f96a1825ec6690ce2654839743945e5128662e34d1de"}
 *
 * Go source:
 * func (g *NameGenerator) getScope(privateName bool) **nameGenerationScope {
 * 	return core.IfElse(privateName, &g.privateNameGenerationScope, &g.nameGenerationScope)
 * }
 */
export function NameGenerator_getScope(receiver: GoPtr<NameGenerator>, privateName: bool): GoRef<GoPtr<nameGenerationScope>> {
  return privateName ? privateNameGenerationScopeRef(receiver!) : nameGenerationScopeRef(receiver!);
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.getTempFlags","kind":"method","status":"implemented","sigHash":"08a13191942c49158a1ec1a7644116f3b18622e559f68e1678cf3ade92c57be2"}
 *
 * Go source:
 * func (g *NameGenerator) getTempFlags(privateName bool) tempFlags {
 * 	scope := g.getScope(privateName)
 * 	if *scope != nil {
 * 		return (*scope).tempFlags
 * 	}
 * 	return tempFlagsAuto
 * }
 */
export function NameGenerator_getTempFlags(receiver: GoPtr<NameGenerator>, privateName: bool): tempFlags {
  const scope = NameGenerator_getScope(receiver, privateName)!;
  if (scope.v !== undefined) {
    return scope.v.tempFlags;
  }
  return tempFlagsAuto;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.setTempFlags","kind":"method","status":"implemented","sigHash":"61e5b7ff3b49f92fee911a957cc385c916ef27ee1a3aeed3276bc3bc62e3ab0f"}
 *
 * Go source:
 * func (g *NameGenerator) setTempFlags(privateName bool, flags tempFlags) {
 * 	scope := g.getScope(privateName)
 * 	if *scope == nil {
 * 		*scope = &nameGenerationScope{}
 * 	}
 * 	(*scope).tempFlags = flags
 * }
 */
export function NameGenerator_setTempFlags(receiver: GoPtr<NameGenerator>, privateName: bool, flags: tempFlags): void {
  const scope = NameGenerator_getScope(receiver, privateName)!;
  if (scope.v === undefined) {
    scope.v = {
      next: undefined,
      tempFlags: tempFlagsAuto,
      formattedNameTempFlags: new globalThis.Map(),
      reservedNames: { M: GoNilMap() },
    };
  }
  scope.v!.tempFlags = flags;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.getTempFlagsForFormattedName","kind":"method","status":"implemented","sigHash":"0b1cc551d0f761e7e728fca0f116696bfc0041394a017f3b9e3145e1cce33fe0"}
 *
 * Go source:
 * func (g *NameGenerator) getTempFlagsForFormattedName(privateName bool, formattedNameKey string) tempFlags {
 * 	scope := g.getScope(privateName)
 * 	if *scope != nil {
 * 		if flags, ok := (*scope).formattedNameTempFlags[formattedNameKey]; ok {
 * 			return flags
 * 		}
 * 	}
 * 	return tempFlagsAuto
 * }
 */
export function NameGenerator_getTempFlagsForFormattedName(receiver: GoPtr<NameGenerator>, privateName: bool, formattedNameKey: string): tempFlags {
  const scope = NameGenerator_getScope(receiver, privateName)!;
  if (scope.v !== undefined) {
    const flags = scope.v.formattedNameTempFlags.get(formattedNameKey);
    if (flags !== undefined) {
      return flags;
    }
  }
  return tempFlagsAuto;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.setTempFlagsForFormattedName","kind":"method","status":"implemented","sigHash":"d60f7262271b68ce91521c5acbf23f38a01eee1ba1a021884fd172663a340c4b"}
 *
 * Go source:
 * func (g *NameGenerator) setTempFlagsForFormattedName(privateName bool, formattedNameKey string, flags tempFlags) {
 * 	scope := g.getScope(privateName)
 * 	if *scope == nil {
 * 		*scope = &nameGenerationScope{}
 * 	}
 * 	if (*scope).formattedNameTempFlags == nil {
 * 		(*scope).formattedNameTempFlags = make(map[string]tempFlags)
 * 	}
 * 	(*scope).formattedNameTempFlags[formattedNameKey] = flags
 * }
 */
export function NameGenerator_setTempFlagsForFormattedName(receiver: GoPtr<NameGenerator>, privateName: bool, formattedNameKey: string, flags: tempFlags): void {
  const scope = NameGenerator_getScope(receiver, privateName)!;
  if (scope.v === undefined) {
    scope.v = {
      next: undefined,
      tempFlags: tempFlagsAuto,
      formattedNameTempFlags: new globalThis.Map(),
      reservedNames: { M: GoNilMap() },
    };
  }
  scope.v!.formattedNameTempFlags.set(formattedNameKey, flags);
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.reserveName","kind":"method","status":"implemented","sigHash":"b586c9b0b328513d9dcfccc94f31c999688da71264960cdc6d1749f7da1d478f"}
 *
 * Go source:
 * func (g *NameGenerator) reserveName(name string, privateName bool, scoped bool, temp bool) {
 * 	scope := g.getScope(privateName)
 * 	if *scope == nil {
 * 		*scope = &nameGenerationScope{}
 * 	}
 * 	if privateName || scoped {
 * 		(*scope).reservedNames.Add(name)
 * 	} else if !temp {
 * 		g.generatedNames.Add(name) // NOTE: Matches Strada, but is incorrect.
 * 		// (*scope).generatedNames.Add(name) // TODO: generated names should be scoped after Strada port is complete.
 * 	}
 * }
 */
export function NameGenerator_reserveName(receiver: GoPtr<NameGenerator>, name: string, privateName: bool, scoped: bool, temp: bool): void {
  const scope = NameGenerator_getScope(receiver, privateName)!;
  if (scope.v === undefined) {
    scope.v = {
      next: undefined,
      tempFlags: tempFlagsAuto,
      formattedNameTempFlags: new globalThis.Map(),
      reservedNames: { M: GoNilMap() },
    };
  }
  if (privateName || scoped) {
    Set_Add(scope.v!.reservedNames, name, GoStringKey);
  } else if (!temp) {
    Set_Add(receiver!.generatedNames, name, GoStringKey);
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.GenerateName","kind":"method","status":"implemented","sigHash":"9b99478f3b7702787c5d1dbdf6016d7201df1c173e929f4164171ea99f20baeb"}
 *
 * Go source:
 * func (g *NameGenerator) GenerateName(name *ast.MemberName) string {
 * 	if g.Context != nil {
 * 		if autoGenerate, ok := g.Context.autoGenerate[name]; ok {
 * 			if autoGenerate.Flags.IsNode() {
 * 				// Node names generate unique names based on their original node
 * 				// and are cached based on that node's id.
 * 				return g.generateNameForNodeCached(g.Context.GetNodeForGeneratedName(name), ast.IsPrivateIdentifier(name), autoGenerate.Flags, autoGenerate.Prefix, autoGenerate.Suffix)
 * 			} else {
 * 				// Auto, Loop, and Unique names are cached based on their unique autoGenerateId.
 * 				if autoGeneratedName, ok := g.autoGeneratedIdToGeneratedName[autoGenerate.Id]; ok {
 * 					return autoGeneratedName
 * 				}
 * 				if g.autoGeneratedIdToGeneratedName == nil {
 * 					g.autoGeneratedIdToGeneratedName = make(map[AutoGenerateId]string)
 * 				}
 * 				autoGeneratedName := g.makeName(name)
 * 				g.autoGeneratedIdToGeneratedName[autoGenerate.Id] = autoGeneratedName
 * 				return autoGeneratedName
 * 			}
 * 		}
 * 	}
 * 	return g.GetTextOfNode(name)
 * }
 */
export function NameGenerator_GenerateName(receiver: GoPtr<NameGenerator>, name: GoPtr<MemberName>): string {
  if (receiver!.Context !== undefined) {
    const autoGenerate = receiver!.Context.autoGenerate?.get(name);
    if (autoGenerate !== undefined) {
      if (GeneratedIdentifierFlags_IsNode(autoGenerate.Flags)) {
        return NameGenerator_generateNameForNodeCached(
          receiver,
          EmitContext_GetNodeForGeneratedName(receiver!.Context, name),
          IsPrivateIdentifier(name),
          autoGenerate.Flags,
          autoGenerate.Prefix,
          autoGenerate.Suffix,
        );
      } else {
        const autoGeneratedName = receiver!.autoGeneratedIdToGeneratedName?.get(autoGenerate.Id);
        if (autoGeneratedName !== undefined) {
          return autoGeneratedName;
        }
        if (receiver!.autoGeneratedIdToGeneratedName === undefined) {
          receiver!.autoGeneratedIdToGeneratedName = new globalThis.Map();
        }
        const generated = NameGenerator_makeName(receiver, name);
        receiver!.autoGeneratedIdToGeneratedName.set(autoGenerate.Id, generated);
        return generated;
      }
    }
  }
  return receiver!.GetTextOfNode!(name);
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForNodeCached","kind":"method","status":"implemented","sigHash":"169dedf9f73d62115907d45322297dbd42b9cc50078157d0f12d98ab48f6b4f9"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForNodeCached(node *ast.Node, privateName bool, flags GeneratedIdentifierFlags, prefix string, suffix string) string {
 * 	nodeId := ast.GetNodeId(node)
 * 	cache := core.IfElse(privateName, &g.nodeIdToGeneratedPrivateName, &g.nodeIdToGeneratedName)
 * 	if *cache == nil {
 * 		*cache = make(map[ast.NodeId]string)
 * 	}
 *
 * 	if name, ok := (*cache)[nodeId]; ok {
 * 		return name
 * 	}
 *
 * 	name := g.generateNameForNode(node, privateName, flags, prefix, suffix)
 * 	(*cache)[nodeId] = name
 * 	return name
 * }
 */
export function NameGenerator_generateNameForNodeCached(receiver: GoPtr<NameGenerator>, node: GoPtr<Node>, privateName: bool, flags: GeneratedIdentifierFlags, prefix: string, suffix: string): string {
  const nodeId = GetNodeId(node);
  if (privateName) {
    if (receiver!.nodeIdToGeneratedPrivateName === undefined) {
      receiver!.nodeIdToGeneratedPrivateName = new globalThis.Map();
    }
    const cached = receiver!.nodeIdToGeneratedPrivateName.get(nodeId);
    if (cached !== undefined) {
      return cached;
    }
    const generated = NameGenerator_generateNameForNode(receiver, node, privateName, flags, prefix, suffix);
    receiver!.nodeIdToGeneratedPrivateName.set(nodeId, generated);
    return generated;
  } else {
    if (receiver!.nodeIdToGeneratedName === undefined) {
      receiver!.nodeIdToGeneratedName = new globalThis.Map();
    }
    const cached = receiver!.nodeIdToGeneratedName.get(nodeId);
    if (cached !== undefined) {
      return cached;
    }
    const generated = NameGenerator_generateNameForNode(receiver, node, privateName, flags, prefix, suffix);
    receiver!.nodeIdToGeneratedName.set(nodeId, generated);
    return generated;
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForNode","kind":"method","status":"implemented","sigHash":"ca9c012ca1861ce6478b62a80135e3e79dea4ca36047bd8d1507e4977dc4ce38"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForNode(node *ast.Node, privateName bool, flags GeneratedIdentifierFlags, prefix string, suffix string) string {
 * 	switch node.Kind {
 * 	case ast.KindIdentifier, ast.KindPrivateIdentifier:
 * 		return g.makeUniqueName(g.GetTextOfNode(node), nil /*checkFn* /, flags.IsOptimistic(), flags.IsReservedInNestedScopes(), privateName, prefix, suffix)
 * 	case ast.KindModuleDeclaration, ast.KindEnumDeclaration:
 * 		if privateName || len(prefix) > 0 || len(suffix) > 0 {
 * 			panic("Generated name for a module or enum cannot be private and may have neither a prefix nor suffix")
 * 		}
 * 		return g.generateNameForModuleOrEnum(node)
 * 	case ast.KindImportDeclaration, ast.KindJSImportDeclaration, ast.KindExportDeclaration:
 * 		if privateName || len(prefix) > 0 || len(suffix) > 0 {
 * 			panic("Generated name for an import or export cannot be private and may have neither a prefix nor suffix")
 * 		}
 * 		return g.generateNameForImportOrExportDeclaration(node)
 * 	case ast.KindFunctionDeclaration, ast.KindClassDeclaration:
 * 		if privateName || len(prefix) > 0 || len(suffix) > 0 {
 * 			panic("Generated name for a class or function declaration cannot be private and may have neither a prefix nor suffix")
 * 		}
 * 		name := node.Name()
 * 		if name != nil && !(g.Context == nil && g.Context.HasAutoGenerateInfo(name)) {
 * 			return g.generateNameForNode(name, false /*privateName* /, flags, "" /*prefix* /, "" /*suffix* /)
 * 		}
 * 		return g.generateNameForExportDefault()
 * 	case ast.KindExportAssignment:
 * 		if privateName || len(prefix) > 0 || len(suffix) > 0 {
 * 			panic("Generated name for an export assignment cannot be private and may have neither a prefix nor suffix")
 * 		}
 * 		return g.generateNameForExportDefault()
 * 	case ast.KindClassExpression:
 * 		if privateName || len(prefix) > 0 || len(suffix) > 0 {
 * 			panic("Generated name for a class expression cannot be private and may have neither a prefix nor suffix")
 * 		}
 * 		return g.generateNameForClassExpression()
 * 	case ast.KindMethodDeclaration, ast.KindGetAccessor, ast.KindSetAccessor:
 * 		return g.generateNameForMethodOrAccessor(node, privateName, prefix, suffix)
 * 	case ast.KindComputedPropertyName:
 * 		return g.makeTempVariableName(tempFlagsAuto, true /*reservedInNestedScopes* /, privateName, prefix, suffix)
 * 	default:
 * 		return g.makeTempVariableName(tempFlagsAuto, false /*reservedInNestedScopes* /, privateName, prefix, suffix)
 * 	}
 * }
 */
export function NameGenerator_generateNameForNode(receiver: GoPtr<NameGenerator>, node: GoPtr<Node>, privateName: bool, flags: GeneratedIdentifierFlags, prefix: string, suffix: string): string {
  switch (node!.Kind) {
    case KindIdentifier:
    case KindPrivateIdentifier:
      return NameGenerator_makeUniqueName(
        receiver,
        receiver!.GetTextOfNode!(node),
        undefined,
        GeneratedIdentifierFlags_IsOptimistic(flags),
        GeneratedIdentifierFlags_IsReservedInNestedScopes(flags),
        privateName,
        prefix,
        suffix,
      );
    case KindModuleDeclaration:
    case KindEnumDeclaration:
      if (privateName || prefix.length > 0 || suffix.length > 0) {
        throw new globalThis.Error("Generated name for a module or enum cannot be private and may have neither a prefix nor suffix");
      }
      return NameGenerator_generateNameForModuleOrEnum(receiver, node);
    case KindImportDeclaration:
    case KindJSImportDeclaration:
    case KindExportDeclaration:
      if (privateName || prefix.length > 0 || suffix.length > 0) {
        throw new globalThis.Error("Generated name for an import or export cannot be private and may have neither a prefix nor suffix");
      }
      return NameGenerator_generateNameForImportOrExportDeclaration(receiver, node);
    case KindFunctionDeclaration:
    case KindClassDeclaration:
      if (privateName || prefix.length > 0 || suffix.length > 0) {
        throw new globalThis.Error("Generated name for a class or function declaration cannot be private and may have neither a prefix nor suffix");
      } {
        const nodeName = Node_Name(node);
        if (nodeName !== undefined && !(receiver!.Context === undefined && EmitContext_HasAutoGenerateInfo(receiver!.Context, nodeName as unknown as MemberName))) {
          return NameGenerator_generateNameForNode(receiver, nodeName, false, flags, "", "");
        }
        return NameGenerator_generateNameForExportDefault(receiver);
      }
    case KindExportAssignment:
      if (privateName || prefix.length > 0 || suffix.length > 0) {
        throw new globalThis.Error("Generated name for an export assignment cannot be private and may have neither a prefix nor suffix");
      }
      return NameGenerator_generateNameForExportDefault(receiver);
    case KindClassExpression:
      if (privateName || prefix.length > 0 || suffix.length > 0) {
        throw new globalThis.Error("Generated name for a class expression cannot be private and may have neither a prefix nor suffix");
      }
      return NameGenerator_generateNameForClassExpression(receiver);
    case KindMethodDeclaration:
    case KindGetAccessor:
    case KindSetAccessor:
      return NameGenerator_generateNameForMethodOrAccessor(receiver, node, privateName, prefix, suffix);
    case KindComputedPropertyName:
      return NameGenerator_makeTempVariableName(receiver, tempFlagsAuto, true, privateName, prefix, suffix);
    default:
      return NameGenerator_makeTempVariableName(receiver, tempFlagsAuto, false, privateName, prefix, suffix);
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForModuleOrEnum","kind":"method","status":"implemented","sigHash":"fdbfe0c7ceedcd6ba42d0b9e37b990a1103cf003ed651c577e03ccdb14a87d33"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForModuleOrEnum(node *ast.Node /* ModuleDeclaration | EnumDeclaration * /) string {
 * 	name := g.GetTextOfNode(node.Name())
 * 	// Use module/enum name itself if it is unique, otherwise make a unique variation
 * 	if isUniqueLocalName(name, node) {
 * 		return name
 * 	} else {
 * 		return g.makeUniqueName(name, nil /*checkFn* /, false /*optimistic* /, false /*scoped* /, false /*privateName* /, "" /*prefix* /, "" /*suffix* /)
 * 	}
 * }
 */
export function NameGenerator_generateNameForModuleOrEnum(receiver: GoPtr<NameGenerator>, node: GoPtr<Node>): string {
  const name = receiver!.GetTextOfNode!(Node_Name(node));
  if (isUniqueLocalName(name, node)) {
    return name;
  } else {
    return NameGenerator_makeUniqueName(
      receiver,
      name,
      undefined,
      false,
      false,
      false,
      "",
      "",
    );
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForImportOrExportDeclaration","kind":"method","status":"implemented","sigHash":"d497b1c6ed2a82c948415644de7e84659692733cc11a920d2502c27dc57471b0"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForImportOrExportDeclaration(node *ast.Node /* ImportDeclaration | ExportDeclaration * /) string {
 * 	expr := ast.GetExternalModuleName(node)
 * 	baseName := "module"
 * 	if ast.IsStringLiteral(expr) {
 * 		baseName = makeIdentifierFromModuleName(expr.Text())
 * 	}
 * 	return g.makeUniqueName(baseName, nil /*checkFn* /, false /*optimistic* /, false /*scoped* /, false /*privateName* /, "" /*prefix* /, "" /*suffix* /)
 * }
 */
export function NameGenerator_generateNameForImportOrExportDeclaration(receiver: GoPtr<NameGenerator>, node: GoPtr<Node>): string {
  const expr = GetExternalModuleName(node);
  const baseName = IsStringLiteral(expr)
    ? makeIdentifierFromModuleName(Node_Text(expr))
    : "module";
  return NameGenerator_makeUniqueName(
    receiver,
    baseName,
    undefined,
    false,
    false,
    false,
    "",
    "",
  );
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForExportDefault","kind":"method","status":"implemented","sigHash":"1b39137b1c5ff9119a766a1319623f268960b7157b0f56a50065fb5ef7832ac7"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForExportDefault() string {
 * 	return g.makeUniqueName("default", nil /*checkFn* /, false /*optimistic* /, false /*scoped* /, false /*privateName* /, "" /*prefix* /, "" /*suffix* /)
 * }
 */
export function NameGenerator_generateNameForExportDefault(receiver: GoPtr<NameGenerator>): string {
  return NameGenerator_makeUniqueName(
    receiver,
    "default",
    undefined,
    false,
    false,
    false,
    "",
    "",
  );
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForClassExpression","kind":"method","status":"implemented","sigHash":"7adc3ce7fa5b0349a5c0128819bf0a6c196e68439e20214c508e8e28ba3bd181"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForClassExpression() string {
 * 	return g.makeUniqueName("class", nil /*checkFn* /, false /*optimistic* /, false /*scoped* /, false /*privateName* /, "" /*prefix* /, "" /*suffix* /)
 * }
 */
export function NameGenerator_generateNameForClassExpression(receiver: GoPtr<NameGenerator>): string {
  return NameGenerator_makeUniqueName(
    receiver,
    "class",
    undefined,
    false,
    false,
    false,
    "",
    "",
  );
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.generateNameForMethodOrAccessor","kind":"method","status":"implemented","sigHash":"ea51b8bdc764fb188198528e746499496bbd7d95fd2d94cbd8516038c181fda1"}
 *
 * Go source:
 * func (g *NameGenerator) generateNameForMethodOrAccessor(node *ast.Node /* MethodDeclaration | AccessorDeclaration * /, privateName bool, prefix string, suffix string) string {
 * 	if ast.IsIdentifier(node.Name()) {
 * 		return g.generateNameForNodeCached(node.Name(), privateName, GeneratedIdentifierFlagsNone, prefix, suffix)
 * 	}
 * 	return g.makeTempVariableName(tempFlagsAuto, false /*reservedInNestedScopes* /, privateName, prefix, suffix)
 * }
 */
export function NameGenerator_generateNameForMethodOrAccessor(receiver: GoPtr<NameGenerator>, node: GoPtr<Node>, privateName: bool, prefix: string, suffix: string): string {
  const nodeName = Node_Name(node);
  if (IsIdentifier(nodeName)) {
    return NameGenerator_generateNameForNodeCached(receiver, nodeName, privateName, GeneratedIdentifierFlagsNone as GeneratedIdentifierFlags, prefix, suffix);
  }
  return NameGenerator_makeTempVariableName(receiver, tempFlagsAuto, false, privateName, prefix, suffix);
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.makeName","kind":"method","status":"implemented","sigHash":"dde535361aecdd55eda513d6d7e1b35333e1ca15bd642b1173c6c789fb2ef6a6"}
 *
 * Go source:
 * func (g *NameGenerator) makeName(name *ast.Node) string {
 * 	if g.Context != nil {
 * 		if autoGenerate, ok := g.Context.autoGenerate[name]; ok {
 * 			switch autoGenerate.Flags.Kind() {
 * 			case GeneratedIdentifierFlagsAuto:
 * 				return g.makeTempVariableName(tempFlagsAuto, autoGenerate.Flags.IsReservedInNestedScopes(), ast.IsPrivateIdentifier(name), autoGenerate.Prefix, autoGenerate.Suffix)
 * 			case GeneratedIdentifierFlagsLoop:
 * 				debug.Assert(ast.IsIdentifier(name))
 * 				return g.makeTempVariableName(tempFlags_i, autoGenerate.Flags.IsReservedInNestedScopes(), false /*privateName* /, autoGenerate.Prefix, autoGenerate.Suffix)
 * 			case GeneratedIdentifierFlagsUnique:
 * 				return g.makeUniqueName(
 * 					name.Text(),
 * 					core.IfElse(autoGenerate.Flags.IsFileLevel(), g.IsFileLevelUniqueNameInCurrentFile, nil),
 * 					autoGenerate.Flags.IsOptimistic(),
 * 					autoGenerate.Flags.IsReservedInNestedScopes(),
 * 					ast.IsPrivateIdentifier(name),
 * 					autoGenerate.Prefix,
 * 					autoGenerate.Suffix,
 * 				)
 * 			}
 * 		}
 * 	}
 * 	return g.GetTextOfNode(name)
 * }
 */
export function NameGenerator_makeName(receiver: GoPtr<NameGenerator>, name: GoPtr<Node>): string {
  if (receiver!.Context !== undefined) {
    const autoGenerate = receiver!.Context.autoGenerate?.get(name as unknown as MemberName);
    if (autoGenerate !== undefined) {
      switch (GeneratedIdentifierFlags_Kind(autoGenerate.Flags)) {
        case GeneratedIdentifierFlagsAuto:
          return NameGenerator_makeTempVariableName(
            receiver,
            tempFlagsAuto,
            GeneratedIdentifierFlags_IsReservedInNestedScopes(autoGenerate.Flags),
            IsPrivateIdentifier(name),
            autoGenerate.Prefix,
            autoGenerate.Suffix,
          );
        case GeneratedIdentifierFlagsLoop:
          return NameGenerator_makeTempVariableName(
            receiver,
            tempFlags_i,
            GeneratedIdentifierFlags_IsReservedInNestedScopes(autoGenerate.Flags),
            false,
            autoGenerate.Prefix,
            autoGenerate.Suffix,
          );
        case GeneratedIdentifierFlagsUnique:
          return NameGenerator_makeUniqueName(
            receiver,
            Node_Text(name),
            GeneratedIdentifierFlags_IsFileLevel(autoGenerate.Flags)
              ? receiver!.IsFileLevelUniqueNameInCurrentFile
              : undefined,
            GeneratedIdentifierFlags_IsOptimistic(autoGenerate.Flags),
            GeneratedIdentifierFlags_IsReservedInNestedScopes(autoGenerate.Flags),
            IsPrivateIdentifier(name),
            autoGenerate.Prefix,
            autoGenerate.Suffix,
          );
      }
    }
  }
  return receiver!.GetTextOfNode!(name);
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.makeTempVariableName","kind":"method","status":"implemented","sigHash":"4c6f26d750a187d717da022a3de07dba1e6acf307b64dbfe70f7b7edf53cf158"}
 *
 * Go source:
 * func (g *NameGenerator) makeTempVariableName(flags tempFlags, reservedInNestedScopes bool, privateName bool, prefix string, suffix string) string {
 * 	var tempFlags tempFlags
 * 	var key string
 * 	simple := len(prefix) == 0 && len(suffix) == 0
 * 	if simple {
 * 		tempFlags = g.getTempFlags(privateName)
 * 	} else {
 * 		// Generate a key to use to acquire a TempFlags counter based on the fixed portions of the generated name.
 * 		key = FormatGeneratedName(privateName, prefix, "" /*base* /, suffix)
 * 		if privateName {
 * 			key = ensureLeadingHash(key)
 * 		}
 * 		tempFlags = g.getTempFlagsForFormattedName(privateName, key)
 * 	}
 *
 * 	if flags != 0 && tempFlags&flags == 0 {
 * 		fullName := FormatGeneratedName(privateName, prefix, "_i", suffix)
 * 		if g.isUniqueName(fullName, privateName) {
 * 			tempFlags |= flags
 * 			g.reserveName(fullName, privateName, reservedInNestedScopes, true /*temp* /)
 * 			if simple {
 * 				g.setTempFlags(privateName, tempFlags)
 * 			} else {
 * 				g.setTempFlagsForFormattedName(privateName, key, tempFlags)
 * 			}
 * 			return fullName
 * 		}
 * 	}
 *
 * 	for {
 * 		count := tempFlags & tempFlagsCountMask
 * 		tempFlags++
 * 		// Skip over 'i' and 'n'
 * 		if count != 8 && count != 13 {
 * 			var name string
 * 			if count < 26 {
 * 				name = fmt.Sprintf("_%c", 'a'+byte(count))
 * 			} else {
 * 				name = fmt.Sprintf("_%d", count-26)
 * 			}
 * 			fullName := FormatGeneratedName(privateName, prefix, name, suffix)
 * 			if g.isUniqueName(fullName, privateName) {
 * 				g.reserveName(fullName, privateName, reservedInNestedScopes, true /*temp* /)
 * 				if simple {
 * 					g.setTempFlags(privateName, tempFlags)
 * 				} else {
 * 					g.setTempFlagsForFormattedName(privateName, key, tempFlags)
 * 				}
 * 				return fullName
 * 			}
 * 		}
 * 	}
 * }
 */
export function NameGenerator_makeTempVariableName(receiver: GoPtr<NameGenerator>, flags: tempFlags, reservedInNestedScopes: bool, privateName: bool, prefix: string, suffix: string): string {
  const simple = prefix.length === 0 && suffix.length === 0;
  const key = simple ? "" : (() => {
    const k = FormatGeneratedName(privateName, prefix, "", suffix);
    return privateName ? ensureLeadingHash(k) : k;
  })();
  let currentTempFlags = simple
    ? NameGenerator_getTempFlags(receiver, privateName)
    : NameGenerator_getTempFlagsForFormattedName(receiver, privateName, key);

  if (flags !== 0 && (currentTempFlags & flags) === 0) {
    const fullName = FormatGeneratedName(privateName, prefix, "_i", suffix);
    if (NameGenerator_isUniqueName(receiver, fullName, privateName)) {
      currentTempFlags = (currentTempFlags | flags) as tempFlags;
      NameGenerator_reserveName(receiver, fullName, privateName, reservedInNestedScopes, true);
      if (simple) {
        NameGenerator_setTempFlags(receiver, privateName, currentTempFlags);
      } else {
        NameGenerator_setTempFlagsForFormattedName(receiver, privateName, key, currentTempFlags);
      }
      return fullName;
    }
  }

  for (;;) {
    const count = (currentTempFlags & tempFlagsCountMask) as tempFlags;
    currentTempFlags = (currentTempFlags + 1) as tempFlags;
    // Skip over 'i' (8) and 'n' (13)
    if (count !== 8 && count !== 13) {
      const name = count < 26
        ? `_${globalThis.String.fromCharCode(97 + count)}`
        : `_${count - 26}`;
      const fullName = FormatGeneratedName(privateName, prefix, name, suffix);
      if (NameGenerator_isUniqueName(receiver, fullName, privateName)) {
        NameGenerator_reserveName(receiver, fullName, privateName, reservedInNestedScopes, true);
        if (simple) {
          NameGenerator_setTempFlags(receiver, privateName, currentTempFlags);
        } else {
          NameGenerator_setTempFlagsForFormattedName(receiver, privateName, key, currentTempFlags);
        }
        return fullName;
      }
    }
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.makeUniqueName","kind":"method","status":"implemented","sigHash":"81f2523c502eac064f1671dad0cd869a9be0a883705435d86e54f20dc48b42c5"}
 *
 * Go source:
 * func (g *NameGenerator) makeUniqueName(baseName string, checkFn func(name string, privateName bool) bool, optimistic bool, scoped bool, privateName bool, prefix string, suffix string) string {
 * 	baseName = removeLeadingHash(baseName)
 * 	if optimistic {
 * 		fullName := FormatGeneratedName(privateName, prefix, baseName, suffix)
 * 		if g.checkUniqueName(fullName, privateName, checkFn) {
 * 			g.reserveName(fullName, privateName, scoped, false /*temp* /)
 * 			return fullName
 * 		}
 * 	}
 *
 * 	// Find the first unique 'name_n', where n is a positive integer
 * 	if len(baseName) > 0 && baseName[len(baseName)-1] != '_' {
 * 		baseName += "_"
 * 	}
 *
 * 	i := 1
 * 	for {
 * 		fullName := FormatGeneratedName(privateName, prefix, fmt.Sprintf("%s%d", baseName, i), suffix)
 * 		if g.checkUniqueName(fullName, privateName, checkFn) {
 * 			g.reserveName(fullName, privateName, scoped, false /*temp* /)
 * 			return fullName
 * 		}
 * 		i++
 * 	}
 * }
 */
export function NameGenerator_makeUniqueName(receiver: GoPtr<NameGenerator>, baseName: string, checkFn: GoFunc<(name: string, privateName: bool) => bool>, optimistic: bool, scoped: bool, privateName: bool, prefix: string, suffix: string): string {
  const cleanBase = removeLeadingHash(baseName);
  if (optimistic) {
    const fullName = FormatGeneratedName(privateName, prefix, cleanBase, suffix);
    if (NameGenerator_checkUniqueName(receiver, fullName, privateName, checkFn)) {
      NameGenerator_reserveName(receiver, fullName, privateName, scoped, false);
      return fullName;
    }
  }

  const baseWithUnderscore = cleanBase.length > 0 && cleanBase[cleanBase.length - 1] !== "_"
    ? cleanBase + "_"
    : cleanBase;

  let i = 1;
  for (;;) {
    const fullName = FormatGeneratedName(privateName, prefix, `${baseWithUnderscore}${i}`, suffix);
    if (NameGenerator_checkUniqueName(receiver, fullName, privateName, checkFn)) {
      NameGenerator_reserveName(receiver, fullName, privateName, scoped, false);
      return fullName;
    }
    i++;
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.MakeFileLevelOptimisticUniqueName","kind":"method","status":"implemented","sigHash":"60931a9cc0710f6345e49e1666de07e2a2ed7a9a7ad20b7c3504045204b302f5"}
 *
 * Go source:
 * func (g *NameGenerator) MakeFileLevelOptimisticUniqueName(name string) string {
 * 	return g.makeUniqueName(name, g.IsFileLevelUniqueNameInCurrentFile, true /*optimistic* /, false /*scoped* /, false /*privateName* /, "" /*prefix* /, "" /*suffix* /)
 * }
 */
export function NameGenerator_MakeFileLevelOptimisticUniqueName(receiver: GoPtr<NameGenerator>, name: string): string {
  return NameGenerator_makeUniqueName(receiver, name, receiver!.IsFileLevelUniqueNameInCurrentFile, true, false, false, "", "");
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.checkUniqueName","kind":"method","status":"implemented","sigHash":"fd2a947b6aea9654e32f581a1f886ef3a0ff94992ea629759f8177c3734ef58e"}
 *
 * Go source:
 * func (g *NameGenerator) checkUniqueName(name string, privateName bool, checkFn func(name string, privateName bool) bool) bool {
 * 	if checkFn != nil {
 * 		return checkFn(name, privateName)
 * 	} else {
 * 		return g.isUniqueName(name, privateName)
 * 	}
 * }
 */
export function NameGenerator_checkUniqueName(receiver: GoPtr<NameGenerator>, name: string, privateName: bool, checkFn: GoFunc<(name: string, privateName: bool) => bool>): bool {
  if (checkFn !== undefined && checkFn !== null) {
    return checkFn(name, privateName);
  } else {
    return NameGenerator_isUniqueName(receiver, name, privateName);
  }
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::func::nextContainer","kind":"func","status":"implemented","sigHash":"28fe209997f87b07808200983ac141a6f88eb8994c4f29f015af737e157ce519"}
 *
 * Go source:
 * func nextContainer(node *ast.Node) *ast.Node {
 * 	data := node.LocalsContainerData()
 * 	if data != nil {
 * 		return data.NextContainer
 * 	}
 * 	return nil
 * }
 */
export function nextContainer(node: GoPtr<Node>): GoPtr<Node> {
  const data = Node_LocalsContainerData(node);
  if (data !== undefined) {
    return (data as unknown as { NextContainer?: GoPtr<Node> }).NextContainer;
  }
  return undefined;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::func::isUniqueLocalName","kind":"func","status":"implemented","sigHash":"11b9ea00b944da9fefbac5876a092432852a1c0fdc3ae917e79d7d31c83640c8"}
 *
 * Go source:
 * func isUniqueLocalName(name string, container *ast.Node) bool {
 * 	node := container
 * 	for node != nil && ast.IsNodeDescendantOf(node, container) && node.LocalsContainerData() != nil {
 * 		locals := node.Locals()
 * 		if locals != nil {
 * 			// We conservatively include alias symbols to cover cases where they're emitted as locals
 * 			if local, ok := locals[name]; ok && local.Flags&(ast.SymbolFlagsValue|ast.SymbolFlagsExportValue|ast.SymbolFlagsAlias) != 0 {
 * 				return false
 * 			}
 * 		}
 * 		node = nextContainer(node)
 * 	}
 * 	return true
 * }
 */
export function isUniqueLocalName(name: string, container: GoPtr<Node>): bool {
  let node = container;
  while (node !== undefined && IsNodeDescendantOf(node, container) && Node_LocalsContainerData(node) !== undefined) {
    const locals = Node_Locals(node);
    if (locals !== undefined) {
      const local = locals.get(name);
      if (local !== undefined && (local.Flags & (SymbolFlagsValue | SymbolFlagsExportValue | SymbolFlagsAlias)) !== 0) {
        return false;
      }
    }
    node = nextContainer(node);
  }
  return true;
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.isUniqueName","kind":"method","status":"implemented","sigHash":"206ba650f06c7ca1ebddf213be6e42a27d519c58b1ab7c4c6fe5768736f0e45e"}
 *
 * Go source:
 * func (g *NameGenerator) isUniqueName(name string, privateName bool) bool {
 * 	return (g.IsFileLevelUniqueNameInCurrentFile == nil || g.IsFileLevelUniqueNameInCurrentFile(name, privateName)) &&
 * 		!g.isReservedName(name, privateName)
 * }
 */
export function NameGenerator_isUniqueName(receiver: GoPtr<NameGenerator>, name: string, privateName: bool): bool {
  return (receiver!.IsFileLevelUniqueNameInCurrentFile === undefined ||
    receiver!.IsFileLevelUniqueNameInCurrentFile === null ||
    receiver!.IsFileLevelUniqueNameInCurrentFile(name, privateName)) &&
    !NameGenerator_isReservedName(receiver, name, privateName);
}

/**
 * @tsgo-unit {"id":"github.com/microsoft/typescript-go::internal/printer/namegenerator.go::method::NameGenerator.isReservedName","kind":"method","status":"implemented","sigHash":"0ada1aacdd8497505937b998021698ed323eb15aef47357dffae616920b03a75"}
 *
 * Go source:
 * func (g *NameGenerator) isReservedName(name string, privateName bool) bool {
 * 	scope := g.getScope(privateName)
 *
 * 	// NOTE: The following matches Strada, but is incorrect.
 * 	if g.generatedNames.Has(name) {
 * 		return true
 * 	}
 *
 * 	// TODO: generated names should be scoped after Strada port is complete.
 * 	////if *scope != nil {
 * 	////	if (*scope).generatedNames.Has(name) {
 * 	////		return true
 * 	////	}
 * 	////}
 *
 * 	for *scope != nil {
 * 		if (*scope).reservedNames.Has(name) {
 * 			return true
 * 		}
 * 		scope = &(*scope).next
 * 	}
 * 	return false
 * }
 */
export function NameGenerator_isReservedName(receiver: GoPtr<NameGenerator>, name: string, privateName: bool): bool {
  if (Set_Has(receiver!.generatedNames, name)) {
    return true;
  }

  let scope = NameGenerator_getScope(receiver, privateName)!.v;
  while (scope !== undefined) {
    if (Set_Has(scope.reservedNames, name)) {
      return true;
    }
    scope = scope.next;
  }
  return false;
}
