// Mirror of internal/printer/namegenerator_test.go (all 28 Test* functions),
// with testutil/parsetestutil.ParseTypeScript inlined. The Go tests build
// `&printer.NameGenerator{Context: ec, ...}` struct literals; newNameGenerator
// reproduces that zero-value literal here.
import { test } from "node:test";
import assert from "node:assert/strict";
import type { bool } from "../../go/scalars.js";
import type { GoPtr } from "../../go/compat.js";
import type { SourceFile } from "../ast/ast.js";
import { Node_Body, Node_Expression, Node_Members, Node_Statements, Node_Text } from "../ast/ast.js";
import type { Node } from "../ast/spine.js";
import { Node_Name, NodeFactory_NewNodeList } from "../ast/spine.js";
import { NewObjectLiteralExpression } from "../ast/generated/factory.js";
import type { SourceFileParseOptions } from "../ast/parseoptions.js";
import { BindSourceFile } from "../binder/binder.js";
import { GetScriptKindFromFileName } from "../core/core.js";
import { ParseSourceFile } from "../parser/parser/statements-declarations.js";
import type { AutoGenerateOptions, EmitContext } from "./emitcontext.js";
import { NewEmitContext } from "./emitcontext.js";
import {
  NodeFactory_NewGeneratedNameForNode,
  NodeFactory_NewGeneratedNameForNodeEx,
  NodeFactory_NewGeneratedPrivateNameForNode,
  NodeFactory_NewLoopVariable,
  NodeFactory_NewLoopVariableEx,
  NodeFactory_NewTempVariable,
  NodeFactory_NewTempVariableEx,
  NodeFactory_NewUniqueName,
  NodeFactory_NewUniquePrivateName,
} from "./factory.js";
import { GeneratedIdentifierFlagsReservedInNestedScopes } from "./generatedidentifierflags.js";
import type { GeneratedIdentifierFlags } from "./generatedidentifierflags.js";
import type { NameGenerator } from "./namegenerator.js";
import { NameGenerator_GenerateName, NameGenerator_PopScope, NameGenerator_PushScope } from "./namegenerator.js";

// testutil/parsetestutil.ParseTypeScript
function parseTypeScript(text: string, jsx: boolean): GoPtr<SourceFile> {
  const fileName = jsx ? "/main.tsx" : "/main.ts";
  return ParseSourceFile({ FileName: fileName, Path: fileName } as SourceFileParseOptions, text, GetScriptKindFromFileName(fileName));
}

function nodeAt(nodes: ReadonlyArray<GoPtr<Node>> | undefined, index: number): Node {
  assert.ok(nodes !== undefined, "Expected node list to be non-nil");
  const node = nodes[index];
  assert.ok(node !== undefined, `Expected node at index ${index}`);
  return node;
}

function statementAt(file: GoPtr<SourceFile>, index: number): Node {
  assert.ok(file !== undefined, "Expected parsed source file");
  return nodeAt(file.Statements?.Nodes, index);
}

// Go: &printer.NameGenerator{Context: ec[, GetTextOfNode: (*ast.Node).Text]} —
// zero values for the remaining fields.
function newNameGenerator(ec: GoPtr<EmitContext>, getTextOfNode?: (node: GoPtr<Node>) => string): GoPtr<NameGenerator> {
  return {
    Context: ec,
    IsFileLevelUniqueNameInCurrentFile: undefined,
    GetTextOfNode: getTextOfNode,
    nodeIdToGeneratedName: new globalThis.Map(),
    nodeIdToGeneratedPrivateName: new globalThis.Map(),
    autoGeneratedIdToGeneratedName: new globalThis.Map(),
    nameGenerationScope: undefined,
    privateNameGenerationScope: undefined,
    generatedNames: { M: new globalThis.Map() },
  } as NameGenerator;
}

const getText = (node: GoPtr<Node>): string => Node_Text(node);

test("TempVariable1", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewTempVariable(ec!.Factory);
  const name2 = NodeFactory_NewTempVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
  assert.equal(NameGenerator_GenerateName(g, name2), "_b");
});

test("TempVariable2", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewTempVariableEx(ec!.Factory, { Prefix: "A", Suffix: "B" } as AutoGenerateOptions);
  const name2 = NodeFactory_NewTempVariableEx(ec!.Factory, { Prefix: "A", Suffix: "B" } as AutoGenerateOptions);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "A_aB");
  assert.equal(NameGenerator_GenerateName(g, name2), "A_bB");
});

test("TempVariable3", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewTempVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
});

test("TempVariableScoped", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewTempVariable(ec!.Factory);
  const name2 = NodeFactory_NewTempVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
  NameGenerator_PushScope(g, false);
  assert.equal(NameGenerator_GenerateName(g, name2), "_a");
  NameGenerator_PopScope(g, false);
});

test("TempVariableScopedReserved", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewTempVariableEx(ec!.Factory, { Flags: GeneratedIdentifierFlagsReservedInNestedScopes as GeneratedIdentifierFlags, Prefix: "", Suffix: "" } as AutoGenerateOptions);
  const name2 = NodeFactory_NewTempVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
  NameGenerator_PushScope(g, false);
  assert.equal(NameGenerator_GenerateName(g, name2), "_b");
  NameGenerator_PopScope(g, false);
});

test("LoopVariable1", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewLoopVariable(ec!.Factory);
  const name2 = NodeFactory_NewLoopVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_i");
  assert.equal(NameGenerator_GenerateName(g, name2), "_a");
});

test("LoopVariable2", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewLoopVariableEx(ec!.Factory, { Prefix: "A", Suffix: "B" } as AutoGenerateOptions);
  const name2 = NodeFactory_NewLoopVariableEx(ec!.Factory, { Prefix: "A", Suffix: "B" } as AutoGenerateOptions);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "A_iB");
  assert.equal(NameGenerator_GenerateName(g, name2), "A_aB");
});

test("LoopVariable3", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewLoopVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_i");
  assert.equal(NameGenerator_GenerateName(g, name1), "_i");
});

test("LoopVariableScoped", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewLoopVariable(ec!.Factory);
  const name2 = NodeFactory_NewLoopVariable(ec!.Factory);
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "_i");
  NameGenerator_PushScope(g, false);
  assert.equal(NameGenerator_GenerateName(g, name2), "_i");
  NameGenerator_PopScope(g, false);
});

test("UniqueName1", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewUniqueName(ec!.Factory, "foo");
  const name2 = NodeFactory_NewUniqueName(ec!.Factory, "foo");
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
  assert.equal(NameGenerator_GenerateName(g, name2), "foo_2");
});

test("UniqueName2", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewUniqueName(ec!.Factory, "foo");
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
  // Expected to be same because GenerateName goes off object identity
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
});

test("UniqueNameScoped", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewUniqueName(ec!.Factory, "foo");
  const name2 = NodeFactory_NewUniqueName(ec!.Factory, "foo");
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
  NameGenerator_PushScope(g, false);
  assert.equal(NameGenerator_GenerateName(g, name2), "foo_2"); // Matches Strada, but is incorrect
  NameGenerator_PopScope(g, false);
});

test("UniquePrivateName1", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewUniquePrivateName(ec!.Factory, "#foo");
  const name2 = NodeFactory_NewUniquePrivateName(ec!.Factory, "#foo");
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "#foo_1");
  assert.equal(NameGenerator_GenerateName(g, name2), "#foo_2");
});

test("UniquePrivateName2", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewUniquePrivateName(ec!.Factory, "#foo");
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "#foo_1");
  assert.equal(NameGenerator_GenerateName(g, name1), "#foo_1");
});

test("UniquePrivateNameScoped", () => {
  const ec = NewEmitContext();
  const name1 = NodeFactory_NewUniquePrivateName(ec!.Factory, "#foo");
  const name2 = NodeFactory_NewUniquePrivateName(ec!.Factory, "#foo");
  const g = newNameGenerator(ec);
  assert.equal(NameGenerator_GenerateName(g, name1), "#foo_1");
  NameGenerator_PushScope(g, false); // private names are always reserved in nested scopes
  assert.equal(NameGenerator_GenerateName(g, name2), "#foo_2");
  NameGenerator_PopScope(g, false);
});

test("GeneratedNameForIdentifier1", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("function f() {}", false);
  BindSourceFile(file);
  const n = Node_Name(statementAt(file, 0));
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "f_1");
});

test("GeneratedNameForIdentifier2", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("function f() {}", false);
  BindSourceFile(file);
  const n = Node_Name(statementAt(file, 0));
  const name1 = NodeFactory_NewGeneratedNameForNodeEx(ec!.Factory, n, { Prefix: "a", Suffix: "b" } as AutoGenerateOptions);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "afb");
});

test("GeneratedNameForIdentifier3", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("function f() {}", false);
  BindSourceFile(file);
  const n = Node_Name(statementAt(file, 0));
  const name1 = NodeFactory_NewGeneratedNameForNodeEx(ec!.Factory, n, { Prefix: "a", Suffix: "b" } as AutoGenerateOptions);
  const name2 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, name1);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name2), "afb_1");
});

// namespace reuses name if it does not collide with locals
test("GeneratedNameForNamespace1", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("namespace foo { }", false);
  BindSourceFile(file);
  const ns1 = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns1);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo");
});

// namespace uses generated name if it collides with locals
test("GeneratedNameForNamespace2", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("namespace foo { var foo; }", false);
  BindSourceFile(file);
  const ns1 = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns1);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
});

// avoids collisions when unscoped
test("GeneratedNameForNamespace3", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("namespace ns1 { namespace foo { var foo; } } namespace ns2 { namespace foo { var foo; } }", false);
  BindSourceFile(file);
  const ns1 = nodeAt(Node_Statements(Node_Body(statementAt(file, 0))), 0);
  const ns2 = nodeAt(Node_Statements(Node_Body(statementAt(file, 1))), 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns1);
  const name2 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns2);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
  assert.equal(NameGenerator_GenerateName(g, name2), "foo_2");
});

// reuse name when scoped
test("GeneratedNameForNamespace4", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("namespace ns1 { namespace foo { var foo; } } namespace ns2 { namespace foo { var foo; } }", false);
  BindSourceFile(file);
  const ns1 = nodeAt(Node_Statements(Node_Body(statementAt(file, 0))), 0);
  const ns2 = nodeAt(Node_Statements(Node_Body(statementAt(file, 1))), 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns1);
  const name2 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns2);
  const g = newNameGenerator(ec, getText);
  NameGenerator_PushScope(g, false);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
  NameGenerator_PopScope(g, false);
  NameGenerator_PushScope(g, false);
  assert.equal(NameGenerator_GenerateName(g, name2), "foo_2"); // Matches Strada, but is incorrect
  NameGenerator_PopScope(g, false);
});

test("GeneratedNameForNodeCached", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("namespace foo { var foo; }", false);
  BindSourceFile(file);
  const ns1 = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns1);
  const name2 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, ns1);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
  assert.equal(NameGenerator_GenerateName(g, name2), "foo_1");
});

test("GeneratedNameForImport", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("import * as foo from 'foo'", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
});

test("GeneratedNameForExport", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("export * as foo from 'foo'", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "foo_1");
});

test("GeneratedNameForFunctionDeclaration1", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("export function f() {}", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "f_1");
});

test("GeneratedNameForFunctionDeclaration2", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("export default function () {}", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "default_1");
});

test("GeneratedNameForClassDeclaration1", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("export class C {}", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "C_1");
});

test("GeneratedNameForClassDeclaration2", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("export default class {}", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "default_1");
});

test("GeneratedNameForExportAssignment", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("export default 0", false);
  BindSourceFile(file);
  const n = statementAt(file, 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "default_1");
});

test("GeneratedNameForClassExpression", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("(class {})", false);
  BindSourceFile(file);
  const n = Node_Expression(Node_Expression(statementAt(file, 0)));
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "class_1");
});

test("GeneratedNameForMethod1", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("class C { m() {} }", false);
  BindSourceFile(file);
  const n = nodeAt(Node_Members(statementAt(file, 0)), 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "m_1");
});

test("GeneratedNameForMethod2", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("class C { 0() {} }", false);
  BindSourceFile(file);
  const n = nodeAt(Node_Members(statementAt(file, 0)), 0);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
});

test("GeneratedPrivateNameForMethod", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("class C { m() {} }", false);
  BindSourceFile(file);
  const n = nodeAt(Node_Members(statementAt(file, 0)), 0);
  const name1 = NodeFactory_NewGeneratedPrivateNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "#m_1");
});

test("GeneratedNameForComputedPropertyName", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("class C { [x] }", false);
  BindSourceFile(file);
  const n = Node_Name(nodeAt(Node_Members(statementAt(file, 0)), 0));
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
});

test("GeneratedNameForOther", () => {
  const ec = NewEmitContext();
  const file = parseTypeScript("class C { [x] }", false);
  BindSourceFile(file);
  const n = NewObjectLiteralExpression(ec!.Factory!.__tsgoEmbedded0, NodeFactory_NewNodeList(ec!.Factory!.__tsgoEmbedded0, []), false /*multiLine*/);
  const name1 = NodeFactory_NewGeneratedNameForNode(ec!.Factory, n);
  const g = newNameGenerator(ec, getText);
  assert.equal(NameGenerator_GenerateName(g, name1), "_a");
});
