// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/github.com/google/go-cmp/cmp/cmpopts.ts","contentHash":"f5508957d8f2d3af6c43cdb33598ab69f76e68eb8aaefd56e85457fa18f94232"}

export function IgnoreUnexported(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED github.com/google/go-cmp/cmp/cmpopts.IgnoreUnexported");
}
