// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/golang.org/x/tools/go/analysis.ts","contentHash":"a039bc99f04bb2792bde50b4d9916b99eeebd874952b78696f9b14a9dae60adb"}

export interface Analyzer {
  readonly __goFacadeName: "golang.org/x/tools/go/analysis.Analyzer";
}

export const Diagnostic: unknown = undefined as never;

export interface Pass {
  readonly __goFacadeName: "golang.org/x/tools/go/analysis.Pass";
}

export const SuggestedFix: unknown = undefined as never;

export interface TextEdit {
  readonly __goFacadeName: "golang.org/x/tools/go/analysis.TextEdit";
}
