/**
 * Strict TS-Go parity gap map for `module`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const moduleStrictParityUpstreamModule = "module";
export const moduleStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"cache.go","line":1,"text":"package module"},
  {"file":"cache.go","line":3,"text":"import ("},
  {"file":"cache.go","line":4,"text":"\t\"sync\""},
  {"file":"cache.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"cache.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"cache.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/packagejson\""},
  {"file":"cache.go","line":9,"text":")"},
  {"file":"cache.go","line":11,"text":"type ModeAwareCache[T any] map[ModeAwareCacheKey]T"},
  {"file":"cache.go","line":13,"text":"type moduleResolutionCacheKey struct {"},
  {"file":"cache.go","line":14,"text":"\tcontainingDirectory string"},
  {"file":"cache.go","line":15,"text":"\tmoduleName          string"},
  {"file":"cache.go","line":16,"text":"\tresolutionMode      core.ResolutionMode"},
  {"file":"cache.go","line":17,"text":"\tredirectConfigName  string"},
  {"file":"cache.go","line":18,"text":"}"},
  {"file":"cache.go","line":20,"text":"type moduleResolutionCache struct {"},
  {"file":"cache.go","line":21,"text":"\tcache collections.SyncMap[moduleResolutionCacheKey, *ResolvedModule]"},
  {"file":"cache.go","line":22,"text":"}"},
  {"file":"cache.go","line":24,"text":"func (c *moduleResolutionCache) Get(key moduleResolutionCacheKey) (*ResolvedModule, bool) {"},
  {"file":"cache.go","line":25,"text":"\treturn c.cache.Load(key)"},
  {"file":"cache.go","line":26,"text":"}"},
  {"file":"cache.go","line":28,"text":"func (c *moduleResolutionCache) Set(key moduleResolutionCacheKey, value *ResolvedModule) {"},
  {"file":"cache.go","line":29,"text":"\tc.cache.Store(key, value)"},
  {"file":"cache.go","line":30,"text":"}"},
  {"file":"cache.go","line":32,"text":"type typeRefDirectiveResolutionCacheKey struct {"},
  {"file":"cache.go","line":33,"text":"\tcontainingDirectory             string"},
  {"file":"cache.go","line":34,"text":"\ttypeReferenceName               string"},
  {"file":"cache.go","line":35,"text":"\tresolutionMode                  core.ResolutionMode"},
  {"file":"cache.go","line":36,"text":"\tredirectConfigName              string"},
  {"file":"cache.go","line":37,"text":"\tfromInferredTypesContainingFile bool"},
  {"file":"cache.go","line":38,"text":"}"},
  {"file":"cache.go","line":40,"text":"type typeRefDirectiveResolutionCache struct {"},
  {"file":"cache.go","line":41,"text":"\tcache collections.SyncMap[typeRefDirectiveResolutionCacheKey, *ResolvedTypeReferenceDirective]"},
  {"file":"cache.go","line":42,"text":"}"},
  {"file":"cache.go","line":44,"text":"func (c *typeRefDirectiveResolutionCache) Get(key typeRefDirectiveResolutionCacheKey) (*ResolvedTypeReferenceDirective, bool) {"},
  {"file":"cache.go","line":45,"text":"\treturn c.cache.Load(key)"},
  {"file":"cache.go","line":46,"text":"}"},
  {"file":"cache.go","line":48,"text":"func (c *typeRefDirectiveResolutionCache) Set(key typeRefDirectiveResolutionCacheKey, value *ResolvedTypeReferenceDirective) {"},
  {"file":"cache.go","line":49,"text":"\tc.cache.Store(key, value)"},
  {"file":"cache.go","line":50,"text":"}"},
  {"file":"cache.go","line":52,"text":"type caches struct {"},
  {"file":"cache.go","line":53,"text":"\tpackageJsonInfoCache *packagejson.InfoCache"},
  {"file":"cache.go","line":55,"text":"\tmoduleResolutionCache           moduleResolutionCache"},
  {"file":"cache.go","line":56,"text":"\ttypeRefDirectiveResolutionCache typeRefDirectiveResolutionCache"},
  {"file":"cache.go","line":60,"text":"\tparsedPatternsForPathsOnce sync.Once"},
  {"file":"cache.go","line":61,"text":"\tparsedPatternsForPaths     *ParsedPatterns"},
  {"file":"cache.go","line":62,"text":"}"},
  {"file":"cache.go","line":64,"text":"func newCaches("},
  {"file":"cache.go","line":65,"text":"\tcurrentDirectory string,"},
  {"file":"cache.go","line":66,"text":"\tuseCaseSensitiveFileNames bool,"},
  {"file":"cache.go","line":67,"text":"\toptions *core.CompilerOptions,"},
  {"file":"cache.go","line":68,"text":") caches {"},
  {"file":"cache.go","line":69,"text":"\treturn caches{"},
  {"file":"cache.go","line":70,"text":"\t\tpackageJsonInfoCache: packagejson.NewInfoCache(currentDirectory, useCaseSensitiveFileNames),"},
  {"file":"cache.go","line":71,"text":"\t}"},
  {"file":"cache.go","line":72,"text":"}"},
  {"file":"cache.go","line":74,"text":"func getRedirectConfigName(redirect ResolvedProjectReference) string {"},
  {"file":"cache.go","line":75,"text":"\tif redirect == nil {"},
  {"file":"cache.go","line":76,"text":"\t\treturn \"\""},
  {"file":"cache.go","line":77,"text":"\t}"},
  {"file":"cache.go","line":78,"text":"\treturn redirect.ConfigName()"},
  {"file":"cache.go","line":79,"text":"}"},
  {"file":"resolver.go","line":1,"text":"package module"},
  {"file":"resolver.go","line":3,"text":"import ("},
  {"file":"resolver.go","line":4,"text":"\t\"fmt\""},
  {"file":"resolver.go","line":5,"text":"\t\"maps\""},
  {"file":"resolver.go","line":6,"text":"\t\"slices\""},
  {"file":"resolver.go","line":7,"text":"\t\"strings\""},
  {"file":"resolver.go","line":8,"text":"\t\"sync\""},
  {"file":"resolver.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"resolver.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"resolver.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"resolver.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"resolver.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/packagejson\""},
  {"file":"resolver.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"file":"resolver.go","line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"resolver.go","line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs/vfsmatch\""},
  {"file":"resolver.go","line":18,"text":")"},
  {"file":"resolver.go","line":20,"text":"type resolved struct {"},
  {"file":"resolver.go","line":21,"text":"\tpath                     string"},
  {"file":"resolver.go","line":22,"text":"\textension                string"},
  {"file":"resolver.go","line":23,"text":"\tpackageId                PackageId"},
  {"file":"resolver.go","line":24,"text":"\toriginalPath             string"},
  {"file":"resolver.go","line":25,"text":"\tresolvedUsingTsExtension bool"},
  {"file":"resolver.go","line":26,"text":"}"},
  {"file":"resolver.go","line":28,"text":"func (r *resolved) shouldContinueSearching() bool {"},
  {"file":"resolver.go","line":29,"text":"\treturn r == nil"},
  {"file":"resolver.go","line":30,"text":"}"},
  {"file":"resolver.go","line":32,"text":"func (r *resolved) isResolved() bool {"},
  {"file":"resolver.go","line":33,"text":"\treturn r != nil && r.path != \"\""},
  {"file":"resolver.go","line":34,"text":"}"},
  {"file":"resolver.go","line":36,"text":"func continueSearching() *resolved {"},
  {"file":"resolver.go","line":37,"text":"\treturn nil"},
  {"file":"resolver.go","line":38,"text":"}"},
  {"file":"resolver.go","line":40,"text":"func unresolved() *resolved {"},
  {"file":"resolver.go","line":41,"text":"\treturn &resolved{}"},
  {"file":"resolver.go","line":42,"text":"}"},
  {"file":"resolver.go","line":44,"text":"type resolutionKindSpecificLoader = func(extensions extensions, candidate string) *resolved"},
  {"file":"resolver.go","line":46,"text":"type tracer struct {"},
  {"file":"resolver.go","line":47,"text":"\ttraces []DiagAndArgs"},
  {"file":"resolver.go","line":48,"text":"}"},
  {"file":"resolver.go","line":50,"text":"type DiagAndArgs struct {"},
  {"file":"resolver.go","line":51,"text":"\tMessage *diagnostics.Message"},
  {"file":"resolver.go","line":52,"text":"\tArgs    []any"},
  {"file":"resolver.go","line":53,"text":"}"},
  {"file":"resolver.go","line":55,"text":"func (t *tracer) write(diag *diagnostics.Message, args ...any) {"},
  {"file":"resolver.go","line":56,"text":"\tif t != nil {"},
  {"file":"resolver.go","line":57,"text":"\t\tt.traces = append(t.traces, DiagAndArgs{Message: diag, Args: args})"},
  {"file":"resolver.go","line":58,"text":"\t}"},
  {"file":"resolver.go","line":59,"text":"}"},
  {"file":"resolver.go","line":61,"text":"func (t *tracer) getTraces() []DiagAndArgs {"},
  {"file":"resolver.go","line":62,"text":"\tif t != nil {"},
  {"file":"resolver.go","line":63,"text":"\t\treturn t.traces"},
  {"file":"resolver.go","line":64,"text":"\t}"},
  {"file":"resolver.go","line":65,"text":"\treturn nil"},
  {"file":"resolver.go","line":66,"text":"}"},
  {"file":"resolver.go","line":68,"text":"type resolutionState struct {"},
  {"file":"resolver.go","line":69,"text":"\tresolver *Resolver"},
  {"file":"resolver.go","line":70,"text":"\ttracer   *tracer"},
  {"file":"resolver.go","line":73,"text":"\tname                        string"},
  {"file":"resolver.go","line":74,"text":"\tcontainingDirectory         string"},
];

export function moduleStrictParityLineText(file: string, line: number): string | undefined {
  return moduleStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function moduleStrictParityFiles(): readonly string[] {
  return [...new Set(moduleStrictParitySourceLines.map((entry) => entry.file))].sort();
}
