/**
 * Strict TS-Go parity gap map for `printer`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const printerStrictParityUpstreamModule = "printer";
export const printerStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"changetrackerwriter.go","line":1,"text":"package printer"},
  {"file":"changetrackerwriter.go","line":3,"text":"import ("},
  {"file":"changetrackerwriter.go","line":4,"text":"\t\"unicode/utf8\""},
  {"file":"changetrackerwriter.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"changetrackerwriter.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"changetrackerwriter.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"file":"changetrackerwriter.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"file":"changetrackerwriter.go","line":10,"text":")"},
  {"file":"changetrackerwriter.go","line":12,"text":"type ChangeTrackerWriter struct {"},
  {"file":"changetrackerwriter.go","line":13,"text":"\ttextWriter"},
  {"file":"changetrackerwriter.go","line":14,"text":"\tlastNonTriviaPosition int"},
  {"file":"changetrackerwriter.go","line":15,"text":"\tpos                   map[triviaPositionKey]int"},
  {"file":"changetrackerwriter.go","line":16,"text":"\tend                   map[triviaPositionKey]int"},
  {"file":"changetrackerwriter.go","line":17,"text":"}"},
  {"file":"changetrackerwriter.go","line":19,"text":"type triviaPositionKey interface { // *astNode | *ast.NodeList"},
  {"file":"changetrackerwriter.go","line":20,"text":"\tPos() int"},
  {"file":"changetrackerwriter.go","line":21,"text":"\tEnd() int"},
  {"file":"changetrackerwriter.go","line":22,"text":"}"},
  {"file":"changetrackerwriter.go","line":24,"text":"func NewChangeTrackerWriter(newline string, indentSize int) *ChangeTrackerWriter {"},
  {"file":"changetrackerwriter.go","line":26,"text":"\tif indentSize < 0 {"},
  {"file":"changetrackerwriter.go","line":27,"text":"\t\tindentSize = defaultIndentSize"},
  {"file":"changetrackerwriter.go","line":28,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":29,"text":"\tctw := &ChangeTrackerWriter{"},
  {"file":"changetrackerwriter.go","line":30,"text":"\t\ttextWriter:            textWriter{newLine: newline, indentSize: indentSize},"},
  {"file":"changetrackerwriter.go","line":31,"text":"\t\tlastNonTriviaPosition: 0,"},
  {"file":"changetrackerwriter.go","line":32,"text":"\t\tpos:                   map[triviaPositionKey]int{},"},
  {"file":"changetrackerwriter.go","line":33,"text":"\t\tend:                   map[triviaPositionKey]int{},"},
  {"file":"changetrackerwriter.go","line":34,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":35,"text":"\tctw.textWriter.Clear()"},
  {"file":"changetrackerwriter.go","line":36,"text":"\treturn ctw"},
  {"file":"changetrackerwriter.go","line":37,"text":"}"},
  {"file":"changetrackerwriter.go","line":39,"text":"func (ct *ChangeTrackerWriter) GetPrintHandlers() PrintHandlers {"},
  {"file":"changetrackerwriter.go","line":40,"text":"\treturn PrintHandlers{"},
  {"file":"changetrackerwriter.go","line":41,"text":"\t\tOnBeforeEmitNode: func(nodeOpt *ast.Node) {"},
  {"file":"changetrackerwriter.go","line":42,"text":"\t\t\tif nodeOpt != nil {"},
  {"file":"changetrackerwriter.go","line":43,"text":"\t\t\t\tct.setPos(nodeOpt)"},
  {"file":"changetrackerwriter.go","line":44,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":45,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":46,"text":"\t\tOnAfterEmitNode: func(nodeOpt *ast.Node) {"},
  {"file":"changetrackerwriter.go","line":47,"text":"\t\t\tif nodeOpt != nil {"},
  {"file":"changetrackerwriter.go","line":48,"text":"\t\t\t\tct.setEnd(nodeOpt)"},
  {"file":"changetrackerwriter.go","line":49,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":50,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":51,"text":"\t\tOnBeforeEmitNodeList: func(nodesOpt *ast.NodeList) {"},
  {"file":"changetrackerwriter.go","line":52,"text":"\t\t\tif nodesOpt != nil {"},
  {"file":"changetrackerwriter.go","line":53,"text":"\t\t\t\tct.setPos(nodesOpt)"},
  {"file":"changetrackerwriter.go","line":54,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":55,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":56,"text":"\t\tOnAfterEmitNodeList: func(nodesOpt *ast.NodeList) {"},
  {"file":"changetrackerwriter.go","line":57,"text":"\t\t\tif nodesOpt != nil {"},
  {"file":"changetrackerwriter.go","line":58,"text":"\t\t\t\tct.setEnd(nodesOpt)"},
  {"file":"changetrackerwriter.go","line":59,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":60,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":61,"text":"\t\tOnBeforeEmitToken: func(nodeOpt *ast.TokenNode) {"},
  {"file":"changetrackerwriter.go","line":62,"text":"\t\t\tif nodeOpt != nil {"},
  {"file":"changetrackerwriter.go","line":63,"text":"\t\t\t\tct.setPos(nodeOpt)"},
  {"file":"changetrackerwriter.go","line":64,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":65,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":66,"text":"\t\tOnAfterEmitToken: func(nodeOpt *ast.TokenNode) {"},
  {"file":"changetrackerwriter.go","line":67,"text":"\t\t\tif nodeOpt != nil {"},
  {"file":"changetrackerwriter.go","line":68,"text":"\t\t\t\tct.setEnd(nodeOpt)"},
  {"file":"changetrackerwriter.go","line":69,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":70,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":71,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":72,"text":"}"},
  {"file":"changetrackerwriter.go","line":74,"text":"func (ct *ChangeTrackerWriter) setPos(node triviaPositionKey) {"},
  {"file":"changetrackerwriter.go","line":75,"text":"\tct.pos[node] = ct.lastNonTriviaPosition"},
  {"file":"changetrackerwriter.go","line":76,"text":"}"},
  {"file":"changetrackerwriter.go","line":78,"text":"func (ct *ChangeTrackerWriter) setEnd(node triviaPositionKey) {"},
  {"file":"changetrackerwriter.go","line":79,"text":"\tct.end[node] = ct.lastNonTriviaPosition"},
  {"file":"changetrackerwriter.go","line":80,"text":"}"},
  {"file":"changetrackerwriter.go","line":82,"text":"func (ct *ChangeTrackerWriter) getPos(node triviaPositionKey) int {"},
  {"file":"changetrackerwriter.go","line":83,"text":"\treturn ct.pos[node]"},
  {"file":"changetrackerwriter.go","line":84,"text":"}"},
  {"file":"changetrackerwriter.go","line":86,"text":"func (ct *ChangeTrackerWriter) getEnd(node triviaPositionKey) int {"},
  {"file":"changetrackerwriter.go","line":87,"text":"\treturn ct.end[node]"},
  {"file":"changetrackerwriter.go","line":88,"text":"}"},
  {"file":"changetrackerwriter.go","line":90,"text":"func (ct *ChangeTrackerWriter) setLastNonTriviaPosition(s string, force bool) {"},
  {"file":"changetrackerwriter.go","line":91,"text":"\tif force || scanner.SkipTrivia(s, 0) != len(s) {"},
  {"file":"changetrackerwriter.go","line":92,"text":"\t\tct.lastNonTriviaPosition = ct.textWriter.GetTextPos()"},
  {"file":"changetrackerwriter.go","line":94,"text":"\t\tpos := len(s)"},
  {"file":"changetrackerwriter.go","line":95,"text":"\t\tfor pos > 0 {"},
  {"file":"changetrackerwriter.go","line":96,"text":"\t\t\tr, size := utf8.DecodeLastRuneInString(s[:pos])"},
  {"file":"changetrackerwriter.go","line":97,"text":"\t\t\tif stringutil.IsWhiteSpaceLike(r) {"},
  {"file":"changetrackerwriter.go","line":98,"text":"\t\t\t\tpos -= size"},
  {"file":"changetrackerwriter.go","line":99,"text":"\t\t\t} else {"},
  {"file":"changetrackerwriter.go","line":100,"text":"\t\t\t\tbreak"},
  {"file":"changetrackerwriter.go","line":101,"text":"\t\t\t}"},
  {"file":"changetrackerwriter.go","line":102,"text":"\t\t}"},
  {"file":"changetrackerwriter.go","line":103,"text":"\t\tct.lastNonTriviaPosition -= len(s) - pos"},
  {"file":"changetrackerwriter.go","line":104,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":105,"text":"}"},
  {"file":"changetrackerwriter.go","line":107,"text":"func (ct *ChangeTrackerWriter) AssignPositionsToNode(node *ast.Node, factory *ast.NodeFactory) *ast.Node {"},
  {"file":"changetrackerwriter.go","line":108,"text":"\tvar visitor *ast.NodeVisitor"},
  {"file":"changetrackerwriter.go","line":109,"text":"\tvisitor = &ast.NodeVisitor{"},
  {"file":"changetrackerwriter.go","line":110,"text":"\t\tVisit:   func(n *ast.Node) *ast.Node { return ct.assignPositionsToNodeWorker(n, visitor) },"},
  {"file":"changetrackerwriter.go","line":111,"text":"\t\tFactory: factory,"},
  {"file":"changetrackerwriter.go","line":112,"text":"\t\tHooks: ast.NodeVisitorHooks{"},
  {"file":"changetrackerwriter.go","line":113,"text":"\t\t\tVisitNode:  ct.assignPositionsToNodeWorker,"},
  {"file":"changetrackerwriter.go","line":114,"text":"\t\t\tVisitNodes: ct.assignPositionsToNodeArray,"},
  {"file":"changetrackerwriter.go","line":115,"text":"\t\t\tVisitToken: ct.assignPositionsToNodeWorker,"},
  {"file":"changetrackerwriter.go","line":116,"text":"\t\t\tVisitModifiers: func(modifiers *ast.ModifierList, v *ast.NodeVisitor) *ast.ModifierList {"},
  {"file":"changetrackerwriter.go","line":117,"text":"\t\t\t\tif modifiers != nil {"},
  {"file":"changetrackerwriter.go","line":118,"text":"\t\t\t\t\tnewNodeList := ct.assignPositionsToNodeArray(&modifiers.NodeList, v)"},
  {"file":"changetrackerwriter.go","line":121,"text":"\t\t\t\t\treturn factory.NewModifierList(newNodeList.Nodes)"},
  {"file":"changetrackerwriter.go","line":122,"text":"\t\t\t\t}"},
  {"file":"changetrackerwriter.go","line":123,"text":"\t\t\t\treturn modifiers"},
  {"file":"changetrackerwriter.go","line":124,"text":"\t\t\t},"},
  {"file":"changetrackerwriter.go","line":125,"text":"\t\t},"},
  {"file":"changetrackerwriter.go","line":126,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":127,"text":"\treturn ct.assignPositionsToNodeWorker(node, visitor)"},
  {"file":"changetrackerwriter.go","line":128,"text":"}"},
  {"file":"changetrackerwriter.go","line":130,"text":"func (ct *ChangeTrackerWriter) assignPositionsToNodeWorker("},
  {"file":"changetrackerwriter.go","line":131,"text":"\tnode *ast.Node,"},
  {"file":"changetrackerwriter.go","line":132,"text":"\tv *ast.NodeVisitor,"},
  {"file":"changetrackerwriter.go","line":133,"text":") *ast.Node {"},
  {"file":"changetrackerwriter.go","line":134,"text":"\tif node == nil {"},
  {"file":"changetrackerwriter.go","line":135,"text":"\t\treturn node"},
  {"file":"changetrackerwriter.go","line":136,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":137,"text":"\tvisited := node.VisitEachChild(v)"},
  {"file":"changetrackerwriter.go","line":139,"text":"\tnewNode := visited"},
  {"file":"changetrackerwriter.go","line":140,"text":"\tif !ast.NodeIsSynthesized(visited) {"},
  {"file":"changetrackerwriter.go","line":141,"text":"\t\tnewNode = visited.Clone(v.Factory)"},
  {"file":"changetrackerwriter.go","line":142,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":143,"text":"\tnewNode.ForEachChild(func(child *ast.Node) bool {"},
  {"file":"changetrackerwriter.go","line":144,"text":"\t\tchild.Parent = newNode"},
  {"file":"changetrackerwriter.go","line":145,"text":"\t\treturn true"},
  {"file":"changetrackerwriter.go","line":146,"text":"\t})"},
  {"file":"changetrackerwriter.go","line":147,"text":"\tnewNode.Loc = core.NewTextRange(ct.getPos(node), ct.getEnd(node))"},
  {"file":"changetrackerwriter.go","line":148,"text":"\treturn newNode"},
  {"file":"changetrackerwriter.go","line":149,"text":"}"},
  {"file":"changetrackerwriter.go","line":151,"text":"func (ct *ChangeTrackerWriter) assignPositionsToNodeArray("},
  {"file":"changetrackerwriter.go","line":152,"text":"\tnodes *ast.NodeList,"},
  {"file":"changetrackerwriter.go","line":153,"text":"\tv *ast.NodeVisitor,"},
  {"file":"changetrackerwriter.go","line":154,"text":") *ast.NodeList {"},
  {"file":"changetrackerwriter.go","line":155,"text":"\tvisited := v.VisitNodes(nodes)"},
  {"file":"changetrackerwriter.go","line":156,"text":"\tif visited == nil {"},
  {"file":"changetrackerwriter.go","line":157,"text":"\t\treturn visited"},
  {"file":"changetrackerwriter.go","line":158,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":159,"text":"\tif nodes == nil {"},
  {"file":"changetrackerwriter.go","line":161,"text":"\t\tpanic(\"if nodes is nil, visited should not be nil\")"},
  {"file":"changetrackerwriter.go","line":162,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":164,"text":"\tnodeArray := visited"},
  {"file":"changetrackerwriter.go","line":165,"text":"\tif visited == nodes {"},
  {"file":"changetrackerwriter.go","line":166,"text":"\t\tnodeArray = visited.Clone(v.Factory)"},
  {"file":"changetrackerwriter.go","line":167,"text":"\t}"},
  {"file":"changetrackerwriter.go","line":169,"text":"\tnodeArray.Loc = core.NewTextRange(ct.getPos(nodes), ct.getEnd(nodes))"},
  {"file":"changetrackerwriter.go","line":170,"text":"\treturn nodeArray"},
  {"file":"changetrackerwriter.go","line":171,"text":"}"},
  {"file":"changetrackerwriter.go","line":173,"text":"func (ct *ChangeTrackerWriter) Write(text string) {"},
  {"file":"changetrackerwriter.go","line":174,"text":"\tct.textWriter.Write(text)"},
  {"file":"changetrackerwriter.go","line":175,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":176,"text":"}"},
  {"file":"changetrackerwriter.go","line":178,"text":"func (ct *ChangeTrackerWriter) WriteTrailingSemicolon(text string) {"},
  {"file":"changetrackerwriter.go","line":179,"text":"\tct.textWriter.WriteTrailingSemicolon(text)"},
  {"file":"changetrackerwriter.go","line":180,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":181,"text":"}"},
  {"file":"changetrackerwriter.go","line":182,"text":"func (ct *ChangeTrackerWriter) WriteComment(text string) { ct.textWriter.WriteComment(text) }"},
  {"file":"changetrackerwriter.go","line":183,"text":"func (ct *ChangeTrackerWriter) WriteKeyword(text string) {"},
  {"file":"changetrackerwriter.go","line":184,"text":"\tct.textWriter.WriteKeyword(text)"},
  {"file":"changetrackerwriter.go","line":185,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":186,"text":"}"},
  {"file":"changetrackerwriter.go","line":188,"text":"func (ct *ChangeTrackerWriter) WriteOperator(text string) {"},
  {"file":"changetrackerwriter.go","line":189,"text":"\tct.textWriter.WriteOperator(text)"},
  {"file":"changetrackerwriter.go","line":190,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":191,"text":"}"},
  {"file":"changetrackerwriter.go","line":193,"text":"func (ct *ChangeTrackerWriter) WritePunctuation(text string) {"},
  {"file":"changetrackerwriter.go","line":194,"text":"\tct.textWriter.WritePunctuation(text)"},
  {"file":"changetrackerwriter.go","line":195,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":196,"text":"}"},
  {"file":"changetrackerwriter.go","line":198,"text":"func (ct *ChangeTrackerWriter) WriteSpace(text string) {"},
  {"file":"changetrackerwriter.go","line":199,"text":"\tct.textWriter.WriteSpace(text)"},
  {"file":"changetrackerwriter.go","line":200,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":201,"text":"}"},
  {"file":"changetrackerwriter.go","line":203,"text":"func (ct *ChangeTrackerWriter) WriteStringLiteral(text string) {"},
  {"file":"changetrackerwriter.go","line":204,"text":"\tct.textWriter.WriteStringLiteral(text)"},
  {"file":"changetrackerwriter.go","line":205,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":206,"text":"}"},
  {"file":"changetrackerwriter.go","line":208,"text":"func (ct *ChangeTrackerWriter) WriteParameter(text string) {"},
  {"file":"changetrackerwriter.go","line":209,"text":"\tct.textWriter.WriteParameter(text)"},
  {"file":"changetrackerwriter.go","line":210,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":211,"text":"}"},
  {"file":"changetrackerwriter.go","line":213,"text":"func (ct *ChangeTrackerWriter) WriteProperty(text string) {"},
  {"file":"changetrackerwriter.go","line":214,"text":"\tct.textWriter.WriteProperty(text)"},
  {"file":"changetrackerwriter.go","line":215,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":216,"text":"}"},
  {"file":"changetrackerwriter.go","line":218,"text":"func (ct *ChangeTrackerWriter) WriteSymbol(text string, symbol *ast.Symbol) {"},
  {"file":"changetrackerwriter.go","line":219,"text":"\tct.textWriter.WriteSymbol(text, symbol)"},
  {"file":"changetrackerwriter.go","line":220,"text":"\tct.setLastNonTriviaPosition(text, false)"},
  {"file":"changetrackerwriter.go","line":221,"text":"}"},
  {"file":"changetrackerwriter.go","line":222,"text":"func (ct *ChangeTrackerWriter) WriteLine()                { ct.textWriter.WriteLine() }"},
  {"file":"changetrackerwriter.go","line":223,"text":"func (ct *ChangeTrackerWriter) WriteLineForce(force bool) { ct.textWriter.WriteLineForce(force) }"},
  {"file":"changetrackerwriter.go","line":224,"text":"func (ct *ChangeTrackerWriter) IncreaseIndent()           { ct.textWriter.IncreaseIndent() }"},
  {"file":"changetrackerwriter.go","line":225,"text":"func (ct *ChangeTrackerWriter) DecreaseIndent()           { ct.textWriter.DecreaseIndent() }"},
  {"file":"changetrackerwriter.go","line":226,"text":"func (ct *ChangeTrackerWriter) Clear()                    { ct.textWriter.Clear(); ct.lastNonTriviaPosition = 0 }"},
  {"file":"changetrackerwriter.go","line":227,"text":"func (ct *ChangeTrackerWriter) String() string            { return ct.textWriter.String() }"},
  {"file":"changetrackerwriter.go","line":228,"text":"func (ct *ChangeTrackerWriter) RawWrite(s string) {"},
  {"file":"changetrackerwriter.go","line":229,"text":"\tct.textWriter.RawWrite(s)"},
  {"file":"changetrackerwriter.go","line":230,"text":"\tct.setLastNonTriviaPosition(s, false)"},
  {"file":"changetrackerwriter.go","line":231,"text":"}"},
  {"file":"changetrackerwriter.go","line":233,"text":"func (ct *ChangeTrackerWriter) WriteLiteral(s string) {"},
  {"file":"changetrackerwriter.go","line":234,"text":"\tct.textWriter.WriteLiteral(s)"},
  {"file":"changetrackerwriter.go","line":235,"text":"\tct.setLastNonTriviaPosition(s, true)"},
  {"file":"changetrackerwriter.go","line":236,"text":"}"},
  {"file":"changetrackerwriter.go","line":237,"text":"func (ct *ChangeTrackerWriter) GetTextPos() int             { return ct.textWriter.GetTextPos() }"},
  {"file":"changetrackerwriter.go","line":238,"text":"func (ct *ChangeTrackerWriter) GetLine() int                { return ct.textWriter.GetLine() }"},
  {"file":"changetrackerwriter.go","line":239,"text":"func (ct *ChangeTrackerWriter) GetColumn() core.UTF16Offset { return ct.textWriter.GetColumn() }"},
  {"file":"changetrackerwriter.go","line":240,"text":"func (ct *ChangeTrackerWriter) GetIndent() int              { return ct.textWriter.GetIndent() }"},
  {"file":"changetrackerwriter.go","line":241,"text":"func (ct *ChangeTrackerWriter) IsAtStartOfLine() bool       { return ct.textWriter.IsAtStartOfLine() }"},
  {"file":"changetrackerwriter.go","line":242,"text":"func (ct *ChangeTrackerWriter) HasTrailingComment() bool    { return ct.textWriter.HasTrailingComment() }"},
  {"file":"changetrackerwriter.go","line":243,"text":"func (ct *ChangeTrackerWriter) HasTrailingWhitespace() bool {"},
  {"file":"changetrackerwriter.go","line":244,"text":"\treturn ct.textWriter.HasTrailingWhitespace()"},
  {"file":"changetrackerwriter.go","line":245,"text":"}"},
  {"file":"emitcontext.go","line":1,"text":"package printer"},
  {"file":"emitcontext.go","line":3,"text":"import ("},
  {"file":"emitcontext.go","line":4,"text":"\t\"maps\""},
  {"file":"emitcontext.go","line":5,"text":"\t\"slices\""},
  {"file":"emitcontext.go","line":6,"text":"\t\"sync\""},
  {"file":"emitcontext.go","line":7,"text":"\t\"sync/atomic\""},
  {"file":"emitcontext.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"emitcontext.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"emitcontext.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"emitcontext.go","line":12,"text":")"},
  {"file":"emitcontext.go","line":17,"text":"type EmitContext struct {"},
  {"file":"emitcontext.go","line":18,"text":"\tFactory       *NodeFactory // Required. The NodeFactory to use to create new nodes"},
  {"file":"emitcontext.go","line":19,"text":"\tautoGenerate  map[*ast.MemberName]*AutoGenerateInfo"},
  {"file":"emitcontext.go","line":20,"text":"\ttextSource    map[*ast.StringLiteralNode]*ast.Node"},
  {"file":"emitcontext.go","line":21,"text":"\toriginal      map[*ast.Node]*ast.Node"},
  {"file":"emitcontext.go","line":22,"text":"\temitNodes     core.LinkStore[*ast.Node, emitNode]"},
  {"file":"emitcontext.go","line":23,"text":"\tassignedName  map[*ast.Node]*ast.Expression"},
  {"file":"emitcontext.go","line":24,"text":"\tclassThis     map[*ast.Node]*ast.IdentifierNode"},
  {"file":"emitcontext.go","line":25,"text":"\tvarScopeStack core.Stack[*varScope]"},
  {"file":"emitcontext.go","line":26,"text":"\tletScopeStack core.Stack[*varScope]"},
  {"file":"emitcontext.go","line":27,"text":"\temitHelpers   collections.OrderedSet[*EmitHelper]"},
  {"file":"emitcontext.go","line":28,"text":"}"},
  {"file":"emitcontext.go","line":30,"text":"type environmentFlags int"},
  {"file":"emitcontext.go","line":32,"text":"const ("},
  {"file":"emitcontext.go","line":33,"text":"\tenvironmentFlagsNone                         environmentFlags = 0"},
  {"file":"emitcontext.go","line":34,"text":"\tenvironmentFlagsInParameters                 environmentFlags = 1 << 0 // currently visiting a parameter list"},
  {"file":"emitcontext.go","line":35,"text":"\tenvironmentFlagsVariablesHoistedInParameters environmentFlags = 1 << 1 // a temp variable was hoisted while visiting a parameter list"},
  {"file":"emitcontext.go","line":36,"text":")"},
  {"file":"emitcontext.go","line":38,"text":"type varScope struct {"},
  {"file":"emitcontext.go","line":39,"text":"\tvariables                []*ast.VariableDeclarationNode"},
  {"file":"emitcontext.go","line":40,"text":"\tfunctions                []*ast.FunctionDeclarationNode"},
  {"file":"emitcontext.go","line":41,"text":"\tflags                    environmentFlags"},
  {"file":"emitcontext.go","line":42,"text":"\tinitializationStatements []*ast.Node"},
  {"file":"emitcontext.go","line":43,"text":"}"},
  {"file":"emitcontext.go","line":45,"text":"func NewEmitContext() *EmitContext {"},
  {"file":"emitcontext.go","line":46,"text":"\tc := &EmitContext{}"},
  {"file":"emitcontext.go","line":47,"text":"\tc.Factory = NewNodeFactory(c)"},
  {"file":"emitcontext.go","line":48,"text":"\treturn c"},
  {"file":"emitcontext.go","line":49,"text":"}"},
  {"file":"emitcontext.go","line":51,"text":"var emitContextPool = sync.Pool{"},
  {"file":"emitcontext.go","line":52,"text":"\tNew: func() any {"},
  {"file":"emitcontext.go","line":53,"text":"\t\treturn NewEmitContext()"},
  {"file":"emitcontext.go","line":54,"text":"\t},"},
  {"file":"emitcontext.go","line":55,"text":"}"},
  {"file":"emitcontext.go","line":57,"text":"func GetEmitContext() (*EmitContext, func()) {"},
  {"file":"emitcontext.go","line":58,"text":"\tc := emitContextPool.Get().(*EmitContext)"},
  {"file":"emitcontext.go","line":59,"text":"\treturn c, func() {"},
  {"file":"emitcontext.go","line":60,"text":"\t\tc.Reset()"},
  {"file":"emitcontext.go","line":61,"text":"\t\temitContextPool.Put(c)"},
  {"file":"emitcontext.go","line":62,"text":"\t}"},
  {"file":"emitcontext.go","line":63,"text":"}"},
  {"file":"emitcontext.go","line":65,"text":"func (c *EmitContext) Reset() {"},
  {"file":"emitcontext.go","line":66,"text":"\t*c = EmitContext{"},
  {"file":"emitcontext.go","line":67,"text":"\t\tFactory: c.Factory,"},
  {"file":"emitcontext.go","line":68,"text":"\t}"},
  {"file":"emitcontext.go","line":69,"text":"}"},
  {"file":"emitcontext.go","line":71,"text":"func (c *EmitContext) onCreate(node *ast.Node) {"},
  {"file":"emitcontext.go","line":72,"text":"\tnode.Flags |= ast.NodeFlagsSynthesized"},
  {"file":"emitcontext.go","line":73,"text":"}"},
  {"file":"emitcontext.go","line":75,"text":"func (c *EmitContext) onUpdate(updated *ast.Node, original *ast.Node) {"},
  {"file":"emitcontext.go","line":76,"text":"\tc.SetOriginal(updated, original)"},
  {"file":"emitcontext.go","line":77,"text":"}"},
  {"file":"emitcontext.go","line":79,"text":"func (c *EmitContext) onClone(updated *ast.Node, original *ast.Node) {"},
  {"file":"emitcontext.go","line":80,"text":"\tc.SetOriginal(updated, original)"},
  {"file":"emitcontext.go","line":81,"text":"\tif ast.IsIdentifier(updated) || ast.IsPrivateIdentifier(updated) {"},
  {"file":"emitcontext.go","line":82,"text":"\t\tif autoGenerate := c.autoGenerate[original]; autoGenerate != nil {"},
  {"file":"emitcontext.go","line":83,"text":"\t\t\tautoGenerateCopy := *autoGenerate"},
  {"file":"emitcontext.go","line":84,"text":"\t\t\tc.autoGenerate[updated] = &autoGenerateCopy"},
  {"file":"emitcontext.go","line":85,"text":"\t\t}"},
  {"file":"emitcontext.go","line":86,"text":"\t}"},
  {"file":"emitcontext.go","line":87,"text":"}"},
  {"file":"emitcontext.go","line":90,"text":"func (c *EmitContext) NewNodeVisitor(visit func(node *ast.Node) *ast.Node) *ast.NodeVisitor {"},
  {"file":"emitcontext.go","line":91,"text":"\treturn ast.NewNodeVisitor(visit, c.Factory.AsNodeFactory(), ast.NodeVisitorHooks{"},
  {"file":"emitcontext.go","line":92,"text":"\t\tVisitParameters:         c.VisitParameters,"},
  {"file":"emitcontext.go","line":93,"text":"\t\tVisitFunctionBody:       c.VisitFunctionBody,"},
  {"file":"emitcontext.go","line":94,"text":"\t\tVisitIterationBody:      c.VisitIterationBody,"},
  {"file":"emitcontext.go","line":95,"text":"\t\tVisitTopLevelStatements: c.VisitVariableEnvironment,"},
  {"file":"emitcontext.go","line":96,"text":"\t\tVisitEmbeddedStatement:  c.VisitEmbeddedStatement,"},
  {"file":"emitcontext.go","line":97,"text":"\t})"},
  {"file":"emitcontext.go","line":98,"text":"}"},
  {"file":"emitcontext.go","line":109,"text":"func (c *EmitContext) StartVariableEnvironment() {"},
  {"file":"emitcontext.go","line":110,"text":"\tc.varScopeStack.Push(&varScope{})"},
  {"file":"emitcontext.go","line":111,"text":"\tc.StartLexicalEnvironment()"},
  {"file":"emitcontext.go","line":112,"text":"}"},
  {"file":"emitcontext.go","line":117,"text":"func (c *EmitContext) EndVariableEnvironment() []*ast.Statement {"},
  {"file":"emitcontext.go","line":118,"text":"\tscope := c.varScopeStack.Pop()"},
  {"file":"emitcontext.go","line":119,"text":"\tvar statements []*ast.Statement"},
  {"file":"emitcontext.go","line":120,"text":"\tif len(scope.functions) > 0 {"},
  {"file":"emitcontext.go","line":121,"text":"\t\tstatements = slices.Clone(scope.functions)"},
  {"file":"emitcontext.go","line":122,"text":"\t}"},
  {"file":"emitcontext.go","line":123,"text":"\tif len(scope.variables) > 0 {"},
  {"file":"emitcontext.go","line":124,"text":"\t\tvarDeclList := c.Factory.NewVariableDeclarationList(c.Factory.NewNodeList(scope.variables), ast.NodeFlagsNone)"},
  {"file":"emitcontext.go","line":125,"text":"\t\tvarStatement := c.Factory.NewVariableStatement(nil /*modifiers*/, varDeclList)"},
  {"file":"emitcontext.go","line":126,"text":"\t\tc.SetEmitFlags(varStatement, EFCustomPrologue)"},
  {"file":"emitcontext.go","line":127,"text":"\t\tstatements = append(statements, varStatement)"},
  {"file":"emitcontext.go","line":128,"text":"\t}"},
  {"file":"emitcontext.go","line":129,"text":"\tif len(scope.initializationStatements) > 0 {"},
  {"file":"emitcontext.go","line":130,"text":"\t\tstatements = append(statements, scope.initializationStatements...)"},
  {"file":"emitcontext.go","line":131,"text":"\t}"},
  {"file":"emitcontext.go","line":132,"text":"\treturn append(statements, c.EndLexicalEnvironment()...)"},
  {"file":"emitcontext.go","line":133,"text":"}"},
  {"file":"emitcontext.go","line":136,"text":"func (c *EmitContext) EndAndMergeVariableEnvironmentList(statements *ast.StatementList) *ast.StatementList {"},
  {"file":"emitcontext.go","line":137,"text":"\tvar nodes []*ast.Statement"},
  {"file":"emitcontext.go","line":138,"text":"\tif statements != nil {"},
  {"file":"emitcontext.go","line":139,"text":"\t\tnodes = statements.Nodes"},
  {"file":"emitcontext.go","line":140,"text":"\t}"},
  {"file":"emitcontext.go","line":142,"text":"\tif result, changed := c.endAndMergeVariableEnvironment(nodes); changed {"},
  {"file":"emitcontext.go","line":143,"text":"\t\tlist := c.Factory.NewNodeList(result)"},
  {"file":"emitcontext.go","line":144,"text":"\t\tlist.Loc = statements.Loc"},
  {"file":"emitcontext.go","line":145,"text":"\t\treturn list"},
  {"file":"emitcontext.go","line":146,"text":"\t}"},
  {"file":"emitcontext.go","line":148,"text":"\treturn statements"},
  {"file":"emitcontext.go","line":149,"text":"}"},
  {"file":"emitcontext.go","line":152,"text":"func (c *EmitContext) EndAndMergeVariableEnvironment(statements []*ast.Statement) []*ast.Statement {"},
  {"file":"emitcontext.go","line":153,"text":"\tresult, _ := c.endAndMergeVariableEnvironment(statements)"},
  {"file":"emitcontext.go","line":154,"text":"\treturn result"},
  {"file":"emitcontext.go","line":155,"text":"}"},
  {"file":"emitcontext.go","line":157,"text":"func (c *EmitContext) endAndMergeVariableEnvironment(statements []*ast.Statement) ([]*ast.Statement, bool) {"},
  {"file":"emitcontext.go","line":158,"text":"\treturn c.mergeEnvironment(statements, c.EndVariableEnvironment())"},
  {"file":"emitcontext.go","line":159,"text":"}"},
  {"file":"emitcontext.go","line":164,"text":"func (c *EmitContext) AddVariableDeclaration(name *ast.IdentifierNode) {"},
  {"file":"emitcontext.go","line":165,"text":"\tvarDecl := c.Factory.NewVariableDeclaration(name, nil /*exclamationToken*/, nil /*typeNode*/, nil /*initializer*/)"},
  {"file":"emitcontext.go","line":166,"text":"\tc.SetEmitFlags(varDecl, EFNoNestedSourceMaps)"},
  {"file":"emitcontext.go","line":167,"text":"\tscope := c.varScopeStack.Peek()"},
  {"file":"emitcontext.go","line":168,"text":"\tscope.variables = append(scope.variables, varDecl)"},
  {"file":"emitcontext.go","line":169,"text":"\tif scope.flags&environmentFlagsInParameters != 0 {"},
  {"file":"emitcontext.go","line":170,"text":"\t\tscope.flags |= environmentFlagsVariablesHoistedInParameters"},
  {"file":"emitcontext.go","line":171,"text":"\t}"},
  {"file":"emitcontext.go","line":172,"text":"}"},
  {"file":"emitcontext.go","line":177,"text":"func (c *EmitContext) AddHoistedFunctionDeclaration(node *ast.FunctionDeclarationNode) {"},
  {"file":"emitcontext.go","line":178,"text":"\tc.SetEmitFlags(node, EFCustomPrologue)"},
  {"file":"emitcontext.go","line":179,"text":"\tscope := c.varScopeStack.Peek()"},
  {"file":"emitcontext.go","line":180,"text":"\tscope.functions = append(scope.functions, node)"},
  {"file":"emitcontext.go","line":181,"text":"}"},
  {"file":"emitcontext.go","line":189,"text":"func (c *EmitContext) StartLexicalEnvironment() {"},
  {"file":"emitcontext.go","line":190,"text":"\tc.letScopeStack.Push(&varScope{})"},
  {"file":"emitcontext.go","line":191,"text":"}"},
  {"file":"emitcontext.go","line":197,"text":"func (c *EmitContext) EndLexicalEnvironment() []*ast.Statement {"},
  {"file":"emitcontext.go","line":198,"text":"\tscope := c.letScopeStack.Pop()"},
  {"file":"emitcontext.go","line":199,"text":"\tvar statements []*ast.Statement"},
  {"file":"emitcontext.go","line":200,"text":"\tif len(scope.variables) > 0 {"},
  {"file":"emitcontext.go","line":201,"text":"\t\tvarDeclList := c.Factory.NewVariableDeclarationList(c.Factory.NewNodeList(scope.variables), ast.NodeFlagsLet)"},
  {"file":"emitcontext.go","line":202,"text":"\t\tvarStatement := c.Factory.NewVariableStatement(nil /*modifiers*/, varDeclList)"},
  {"file":"emitcontext.go","line":203,"text":"\t\tc.SetEmitFlags(varStatement, EFCustomPrologue)"},
  {"file":"emitcontext.go","line":204,"text":"\t\tstatements = append(statements, varStatement)"},
  {"file":"emitcontext.go","line":205,"text":"\t}"},
  {"file":"emitcontext.go","line":206,"text":"\treturn statements"},
  {"file":"emitcontext.go","line":207,"text":"}"},
  {"file":"emitcontext.go","line":210,"text":"func (c *EmitContext) EndAndMergeLexicalEnvironmentList(statements *ast.StatementList) *ast.StatementList {"},
  {"file":"emitcontext.go","line":211,"text":"\tvar nodes []*ast.Statement"},
  {"file":"emitcontext.go","line":212,"text":"\tif statements != nil {"},
  {"file":"emitcontext.go","line":213,"text":"\t\tnodes = statements.Nodes"},
  {"file":"emitcontext.go","line":214,"text":"\t}"},
  {"file":"emitcontext.go","line":216,"text":"\tif result, changed := c.endAndMergeLexicalEnvironment(nodes); changed {"},
  {"file":"emitcontext.go","line":217,"text":"\t\tlist := c.Factory.NewNodeList(result)"},
  {"file":"emitcontext.go","line":218,"text":"\t\tlist.Loc = statements.Loc"},
  {"file":"emitcontext.go","line":219,"text":"\t\treturn list"},
  {"file":"emitcontext.go","line":220,"text":"\t}"},
  {"file":"emitcontext.go","line":222,"text":"\treturn statements"},
  {"file":"emitcontext.go","line":223,"text":"}"},
  {"file":"emitcontext.go","line":226,"text":"func (c *EmitContext) EndAndMergeLexicalEnvironment(statements []*ast.Statement) []*ast.Statement {"},
  {"file":"emitcontext.go","line":227,"text":"\tresult, _ := c.endAndMergeLexicalEnvironment(statements)"},
  {"file":"emitcontext.go","line":228,"text":"\treturn result"},
  {"file":"emitcontext.go","line":229,"text":"}"},
  {"file":"emitcontext.go","line":232,"text":"func (c *EmitContext) endAndMergeLexicalEnvironment(statements []*ast.Statement) ([]*ast.Statement, bool) {"},
  {"file":"emitcontext.go","line":233,"text":"\treturn c.mergeEnvironment(statements, c.EndLexicalEnvironment())"},
  {"file":"emitcontext.go","line":234,"text":"}"},
  {"file":"emitcontext.go","line":237,"text":"func (c *EmitContext) AddLexicalDeclaration(name *ast.IdentifierNode) {"},
  {"file":"emitcontext.go","line":238,"text":"\tvarDecl := c.Factory.NewVariableDeclaration(name, nil /*exclamationToken*/, nil /*typeNode*/, nil /*initializer*/)"},
  {"file":"emitcontext.go","line":239,"text":"\tc.SetEmitFlags(varDecl, EFNoNestedSourceMaps)"},
  {"file":"emitcontext.go","line":240,"text":"\tscope := c.letScopeStack.Peek()"},
  {"file":"emitcontext.go","line":241,"text":"\tscope.variables = append(scope.variables, varDecl)"},
  {"file":"emitcontext.go","line":242,"text":"}"},
  {"file":"emitcontext.go","line":245,"text":"func (c *EmitContext) MergeEnvironmentList(statements *ast.StatementList, declarations []*ast.Statement) *ast.StatementList {"},
  {"file":"emitcontext.go","line":246,"text":"\tif result, changed := c.mergeEnvironment(statements.Nodes, declarations); changed {"},
  {"file":"emitcontext.go","line":247,"text":"\t\tlist := c.Factory.NewNodeList(result)"},
  {"file":"emitcontext.go","line":248,"text":"\t\tlist.Loc = statements.Loc"},
  {"file":"emitcontext.go","line":249,"text":"\t\treturn list"},
  {"file":"emitcontext.go","line":250,"text":"\t}"},
  {"file":"emitcontext.go","line":251,"text":"\treturn statements"},
  {"file":"emitcontext.go","line":252,"text":"}"},
  {"file":"emitcontext.go","line":255,"text":"func (c *EmitContext) MergeEnvironment(statements []*ast.Statement, declarations []*ast.Statement) []*ast.Statement {"},
  {"file":"emitcontext.go","line":256,"text":"\tresult, _ := c.mergeEnvironment(statements, declarations)"},
  {"file":"emitcontext.go","line":257,"text":"\treturn result"},
  {"file":"emitcontext.go","line":258,"text":"}"},
  {"file":"emitcontext.go","line":260,"text":"func (c *EmitContext) mergeEnvironment(statements []*ast.Statement, declarations []*ast.Statement) ([]*ast.Statement, bool) {"},
  {"file":"emitcontext.go","line":261,"text":"\tif len(declarations) == 0 {"},
  {"file":"emitcontext.go","line":262,"text":"\t\treturn statements, false"},
  {"file":"emitcontext.go","line":263,"text":"\t}"},
  {"file":"emitcontext.go","line":294,"text":"\tchanged := false"},
  {"file":"emitcontext.go","line":297,"text":"\tleftStandardPrologueEnd := findSpanEnd(statements, ast.IsPrologueDirective, 0)"},
  {"file":"emitcontext.go","line":298,"text":"\tleftHoistedFunctionsEnd := findSpanEndWithEmitContext(c, statements, (*EmitContext).isHoistedFunction, leftStandardPrologueEnd)"},
  {"file":"emitcontext.go","line":299,"text":"\tleftHoistedVariablesEnd := findSpanEndWithEmitContext(c, statements, (*EmitContext).isHoistedVariableStatement, leftHoistedFunctionsEnd)"},
  {"file":"emitcontext.go","line":302,"text":"\trightStandardPrologueEnd := findSpanEnd(declarations, ast.IsPrologueDirective, 0)"},
  {"file":"emitcontext.go","line":303,"text":"\trightHoistedFunctionsEnd := findSpanEndWithEmitContext(c, declarations, (*EmitContext).isHoistedFunction, rightStandardPrologueEnd)"},
  {"file":"emitcontext.go","line":304,"text":"\trightHoistedVariablesEnd := findSpanEndWithEmitContext(c, declarations, (*EmitContext).isHoistedVariableStatement, rightHoistedFunctionsEnd)"},
  {"file":"emitcontext.go","line":305,"text":"\trightCustomPrologueEnd := findSpanEndWithEmitContext(c, declarations, (*EmitContext).isCustomPrologue, rightHoistedVariablesEnd)"},
  {"file":"emitcontext.go","line":306,"text":"\tif rightCustomPrologueEnd != len(declarations) {"},
  {"file":"emitcontext.go","line":307,"text":"\t\tpanic(\"Expected declarations to be valid standard or custom prologues\")"},
  {"file":"emitcontext.go","line":308,"text":"\t}"},
  {"file":"emitcontext.go","line":310,"text":"\tleft := statements"},
  {"file":"emitcontext.go","line":313,"text":"\tif rightCustomPrologueEnd > rightHoistedVariablesEnd {"},
  {"file":"emitcontext.go","line":314,"text":"\t\tleft = core.Splice(left, leftHoistedVariablesEnd, 0, declarations[rightHoistedVariablesEnd:rightCustomPrologueEnd]...)"},
  {"file":"emitcontext.go","line":315,"text":"\t\tchanged = true"},
  {"file":"emitcontext.go","line":316,"text":"\t}"},
  {"file":"emitcontext.go","line":319,"text":"\tif rightHoistedVariablesEnd > rightHoistedFunctionsEnd {"},
  {"file":"emitcontext.go","line":320,"text":"\t\tleft = core.Splice(left, leftHoistedFunctionsEnd, 0, declarations[rightHoistedFunctionsEnd:rightHoistedVariablesEnd]...)"},
  {"file":"emitcontext.go","line":321,"text":"\t\tchanged = true"},
  {"file":"emitcontext.go","line":322,"text":"\t}"},
  {"file":"emitcontext.go","line":325,"text":"\tif rightHoistedFunctionsEnd > rightStandardPrologueEnd {"},
  {"file":"emitcontext.go","line":326,"text":"\t\tleft = core.Splice(left, leftStandardPrologueEnd, 0, declarations[rightStandardPrologueEnd:rightHoistedFunctionsEnd]...)"},
  {"file":"emitcontext.go","line":327,"text":"\t\tchanged = true"},
  {"file":"emitcontext.go","line":328,"text":"\t}"},
  {"file":"emitcontext.go","line":331,"text":"\tif rightStandardPrologueEnd > 0 {"},
  {"file":"emitcontext.go","line":332,"text":"\t\tif leftStandardPrologueEnd == 0 {"},
  {"file":"emitcontext.go","line":333,"text":"\t\t\tleft = core.Splice(left, 0, 0, declarations[:rightStandardPrologueEnd]...)"},
  {"file":"emitcontext.go","line":334,"text":"\t\t\tchanged = true"},
  {"file":"emitcontext.go","line":335,"text":"\t\t} else {"},
  {"file":"emitcontext.go","line":336,"text":"\t\t\tvar leftPrologues collections.Set[string]"},
  {"file":"emitcontext.go","line":337,"text":"\t\t\tfor i := range leftStandardPrologueEnd {"},
  {"file":"emitcontext.go","line":338,"text":"\t\t\t\tleftPrologue := statements[i]"},
  {"file":"emitcontext.go","line":339,"text":"\t\t\t\tleftPrologues.Add(leftPrologue.Expression().Text())"},
  {"file":"emitcontext.go","line":340,"text":"\t\t\t}"},
  {"file":"emitcontext.go","line":341,"text":"\t\t\tfor i := rightStandardPrologueEnd - 1; i >= 0; i-- {"},
  {"file":"emitcontext.go","line":342,"text":"\t\t\t\trightPrologue := declarations[i]"},
  {"file":"emitcontext.go","line":343,"text":"\t\t\t\tif !leftPrologues.Has(rightPrologue.Expression().Text()) {"},
  {"file":"emitcontext.go","line":344,"text":"\t\t\t\t\tleft = core.Concatenate([]*ast.Statement{rightPrologue}, left)"},
  {"file":"emitcontext.go","line":345,"text":"\t\t\t\t\tchanged = true"},
  {"file":"emitcontext.go","line":346,"text":"\t\t\t\t}"},
  {"file":"emitcontext.go","line":347,"text":"\t\t\t}"},
  {"file":"emitcontext.go","line":348,"text":"\t\t}"},
  {"file":"emitcontext.go","line":349,"text":"\t}"},
  {"file":"emitcontext.go","line":351,"text":"\treturn left, changed"},
  {"file":"emitcontext.go","line":352,"text":"}"},
  {"file":"emitcontext.go","line":354,"text":"func (c *EmitContext) isCustomPrologue(node *ast.Statement) bool {"},
  {"file":"emitcontext.go","line":355,"text":"\treturn c.EmitFlags(node)&EFCustomPrologue != 0"},
  {"file":"emitcontext.go","line":356,"text":"}"},
  {"file":"emitcontext.go","line":358,"text":"func (c *EmitContext) isHoistedFunction(node *ast.Statement) bool {"},
  {"file":"emitcontext.go","line":359,"text":"\treturn c.isCustomPrologue(node) && ast.IsFunctionDeclaration(node)"},
  {"file":"emitcontext.go","line":360,"text":"}"},
  {"file":"emitcontext.go","line":362,"text":"func isHoistedVariable(node *ast.VariableDeclarationNode) bool {"},
  {"file":"emitcontext.go","line":363,"text":"\treturn ast.IsIdentifier(node.Name()) && node.Initializer() == nil"},
  {"file":"emitcontext.go","line":364,"text":"}"},
  {"file":"emitcontext.go","line":366,"text":"func (c *EmitContext) isHoistedVariableStatement(node *ast.Statement) bool {"},
  {"file":"emitcontext.go","line":367,"text":"\treturn c.isCustomPrologue(node) &&"},
  {"file":"emitcontext.go","line":368,"text":"\t\tast.IsVariableStatement(node) &&"},
  {"file":"emitcontext.go","line":369,"text":"\t\tcore.Every(node.AsVariableStatement().DeclarationList.AsVariableDeclarationList().Declarations.Nodes, isHoistedVariable)"},
  {"file":"emitcontext.go","line":370,"text":"}"},
  {"file":"emitcontext.go","line":377,"text":"func (c *EmitContext) HasAutoGenerateInfo(node *ast.MemberName) bool {"},
  {"file":"emitcontext.go","line":378,"text":"\tif node != nil {"},
  {"file":"emitcontext.go","line":379,"text":"\t\t_, ok := c.autoGenerate[node]"},
  {"file":"emitcontext.go","line":380,"text":"\t\treturn ok"},
  {"file":"emitcontext.go","line":381,"text":"\t}"},
  {"file":"emitcontext.go","line":382,"text":"\treturn false"},
  {"file":"emitcontext.go","line":383,"text":"}"},
  {"file":"emitcontext.go","line":386,"text":"func (c *EmitContext) GetAutoGenerateInfo(name *ast.MemberName) *AutoGenerateInfo {"},
  {"file":"emitcontext.go","line":387,"text":"\tif name == nil {"},
];

export function printerStrictParityLineText(file: string, line: number): string | undefined {
  return printerStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function printerStrictParityFiles(): readonly string[] {
  return [...new Set(printerStrictParitySourceLines.map((entry) => entry.file))].sort();
}
