// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/golang.org/x/tools/go/analysis/passes/ctrlflow.ts","contentHash":"1ecb59b397744b04a319d4797ad30d77c51aa0c4ac5d5616f3cc410b70a84950"}

export const Analyzer: unknown = undefined as never;

export interface CFGs {
  readonly __goFacadeName: "golang.org/x/tools/go/analysis/passes/ctrlflow.CFGs";
}
