// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"d35cc5f485640a41fbbf5a2267e9b11c7a7db4dc","path":"go/golang.org/x/tools/go/analysis/passes/inspect.ts","contentHash":"6ee23809082fd7fda157ec19e91dbd222117b5b8989b37cbf969407dd0f8b4f7"}

export const Analyzer: unknown = undefined as never;
