/**
 * Language-service parity map for TS-Go `ls/autoimport/aliasresolver.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverUpstreamPath = "ls/autoimport/aliasresolver.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverDeclarations: readonly UpstreamDeclaration[] = [
  {"line":16,"kind":"type","name":"pathAndFileName"},
  {"line":21,"kind":"type","name":"aliasResolver"},
  {"line":33,"kind":"func","name":"newAliasResolver"},
  {"line":53,"kind":"func","name":"BindSourceFiles","receiver":"r *aliasResolver"},
  {"line":58,"kind":"func","name":"SourceFiles","receiver":"r *aliasResolver"},
  {"line":63,"kind":"func","name":"Options","receiver":"r *aliasResolver"},
  {"line":70,"kind":"func","name":"GetCurrentDirectory","receiver":"r *aliasResolver"},
  {"line":75,"kind":"func","name":"UseCaseSensitiveFileNames","receiver":"r *aliasResolver"},
  {"line":80,"kind":"func","name":"GetSourceFile","receiver":"r *aliasResolver"},
  {"line":91,"kind":"func","name":"GetDefaultResolutionModeForFile","receiver":"r *aliasResolver"},
  {"line":96,"kind":"func","name":"GetEmitModuleFormatOfFile","receiver":"r *aliasResolver"},
  {"line":101,"kind":"func","name":"GetEmitSyntaxForUsageLocation","receiver":"r *aliasResolver"},
  {"line":106,"kind":"func","name":"GetImpliedNodeFormatForEmit","receiver":"r *aliasResolver"},
  {"line":111,"kind":"func","name":"GetModeForUsageLocation","receiver":"r *aliasResolver"},
  {"line":116,"kind":"func","name":"GetResolvedModule","receiver":"r *aliasResolver"},
  {"line":130,"kind":"func","name":"GetSourceFileForResolvedModule","receiver":"r *aliasResolver"},
  {"line":135,"kind":"func","name":"GetResolvedModules","receiver":"r *aliasResolver"},
  {"line":143,"kind":"func","name":"GetSymlinkCache","receiver":"r *aliasResolver"},
  {"line":148,"kind":"func","name":"GetSourceFileMetaData","receiver":"r *aliasResolver"},
  {"line":153,"kind":"func","name":"CommonSourceDirectory","receiver":"r *aliasResolver"},
  {"line":158,"kind":"func","name":"FileExists","receiver":"r *aliasResolver"},
  {"line":163,"kind":"func","name":"GetGlobalTypingsCacheLocation","receiver":"r *aliasResolver"},
  {"line":168,"kind":"func","name":"GetImportHelpersImportSpecifier","receiver":"r *aliasResolver"},
  {"line":173,"kind":"func","name":"GetJSXRuntimeImportSpecifier","receiver":"r *aliasResolver"},
  {"line":178,"kind":"func","name":"GetNearestAncestorDirectoryWithPackageJson","receiver":"r *aliasResolver"},
  {"line":183,"kind":"func","name":"GetPackageJsonInfo","receiver":"r *aliasResolver"},
  {"line":188,"kind":"func","name":"GetProjectReferenceFromOutputDts","receiver":"r *aliasResolver"},
  {"line":193,"kind":"func","name":"GetProjectReferenceFromSource","receiver":"r *aliasResolver"},
  {"line":198,"kind":"func","name":"GetRedirectForResolution","receiver":"r *aliasResolver"},
  {"line":203,"kind":"func","name":"GetRedirectTargets","receiver":"r *aliasResolver"},
  {"line":208,"kind":"func","name":"GetResolvedModuleFromModuleSpecifier","receiver":"r *aliasResolver"},
  {"line":213,"kind":"func","name":"GetSourceOfProjectReferenceIfOutputIncluded","receiver":"r *aliasResolver"},
  {"line":218,"kind":"func","name":"IsSourceFileDefaultLibrary","receiver":"r *aliasResolver"},
  {"line":223,"kind":"func","name":"IsSourceFromProjectReference","receiver":"r *aliasResolver"},
  {"line":228,"kind":"func","name":"SourceFileMayBeEmitted","receiver":"r *aliasResolver"},
  {"line":232,"kind":"func","name":"GetPackagesMap","receiver":"r *aliasResolver"},
  {"line":236,"kind":"var","name":"_"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package autoimport"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":5,"text":"\t\"github.com/microsoft/typescript-go/internal/binder\""},
  {"line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/module\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/packagejson\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/symlinks\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/tsoptions\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"line":14,"text":")"},
  {"line":16,"text":"type pathAndFileName struct {"},
  {"line":17,"text":"\tpath     tspath.Path"},
  {"line":18,"text":"\tfileName string"},
  {"line":19,"text":"}"},
  {"line":21,"text":"type aliasResolver struct {"},
  {"line":22,"text":"\ttoPath         func(fileName string) tspath.Path"},
  {"line":23,"text":"\thost           RegistryCloneHost"},
  {"line":24,"text":"\tmoduleResolver *module.Resolver"},
  {"line":26,"text":"\trootFiles []*ast.SourceFile"},
  {"line":28,"text":"\tsymlinks                    map[tspath.Path]pathAndFileName"},
  {"line":29,"text":"\tonFailedAmbientModuleLookup func(source ast.HasFileName, moduleName string)"},
  {"line":30,"text":"\tresolvedModules             collections.SyncMap[tspath.Path, *collections.SyncMap[module.ModeAwareCacheKey, *module.ResolvedModule]]"},
  {"line":31,"text":"}"},
  {"line":33,"text":"func newAliasResolver("},
  {"line":34,"text":"\trootFiles []*ast.SourceFile,"},
  {"line":35,"text":"\tsymlinks map[tspath.Path]pathAndFileName,"},
  {"line":36,"text":"\thost RegistryCloneHost,"},
  {"line":37,"text":"\tmoduleResolver *module.Resolver,"},
  {"line":38,"text":"\ttoPath func(fileName string) tspath.Path,"},
  {"line":39,"text":"\tonFailedAmbientModuleLookup func(source ast.HasFileName, moduleName string),"},
  {"line":40,"text":") *aliasResolver {"},
  {"line":41,"text":"\tr := &aliasResolver{"},
  {"line":42,"text":"\t\ttoPath:                      toPath,"},
  {"line":43,"text":"\t\thost:                        host,"},
  {"line":44,"text":"\t\tmoduleResolver:              moduleResolver,"},
  {"line":45,"text":"\t\trootFiles:                   rootFiles,"},
  {"line":46,"text":"\t\tsymlinks:                    symlinks,"},
  {"line":47,"text":"\t\tonFailedAmbientModuleLookup: onFailedAmbientModuleLookup,"},
  {"line":48,"text":"\t}"},
  {"line":49,"text":"\treturn r"},
  {"line":50,"text":"}"},
  {"line":53,"text":"func (r *aliasResolver) BindSourceFiles() {"},
  {"line":55,"text":"}"},
  {"line":58,"text":"func (r *aliasResolver) SourceFiles() []*ast.SourceFile {"},
  {"line":59,"text":"\treturn r.rootFiles"},
  {"line":60,"text":"}"},
  {"line":63,"text":"func (r *aliasResolver) Options() *core.CompilerOptions {"},
  {"line":64,"text":"\treturn &core.CompilerOptions{"},
  {"line":65,"text":"\t\tNoCheck: core.TSTrue,"},
  {"line":66,"text":"\t}"},
  {"line":67,"text":"}"},
  {"line":70,"text":"func (r *aliasResolver) GetCurrentDirectory() string {"},
  {"line":71,"text":"\treturn r.host.GetCurrentDirectory()"},
  {"line":72,"text":"}"},
  {"line":75,"text":"func (r *aliasResolver) UseCaseSensitiveFileNames() bool {"},
  {"line":76,"text":"\treturn r.host.FS().UseCaseSensitiveFileNames()"},
  {"line":77,"text":"}"},
  {"line":80,"text":"func (r *aliasResolver) GetSourceFile(fileName string) *ast.SourceFile {"},
  {"line":81,"text":"\tfile := r.host.GetSourceFile(fileName, r.toPath(fileName))"},
  {"line":83,"text":"\tif file == nil {"},
  {"line":84,"text":"\t\treturn nil"},
  {"line":85,"text":"\t}"},
  {"line":86,"text":"\tbinder.BindSourceFile(file)"},
  {"line":87,"text":"\treturn file"},
  {"line":88,"text":"}"},
  {"line":91,"text":"func (r *aliasResolver) GetDefaultResolutionModeForFile(file ast.HasFileName) core.ResolutionMode {"},
  {"line":92,"text":"\treturn core.ModuleKindESNext"},
  {"line":93,"text":"}"},
  {"line":96,"text":"func (r *aliasResolver) GetEmitModuleFormatOfFile(sourceFile ast.HasFileName) core.ModuleKind {"},
  {"line":97,"text":"\treturn core.ModuleKindESNext"},
  {"line":98,"text":"}"},
  {"line":101,"text":"func (r *aliasResolver) GetEmitSyntaxForUsageLocation(sourceFile ast.HasFileName, usageLocation *ast.StringLiteralLike) core.ResolutionMode {"},
  {"line":102,"text":"\treturn core.ModuleKindESNext"},
  {"line":103,"text":"}"},
  {"line":106,"text":"func (r *aliasResolver) GetImpliedNodeFormatForEmit(sourceFile ast.HasFileName) core.ModuleKind {"},
  {"line":107,"text":"\treturn core.ModuleKindESNext"},
  {"line":108,"text":"}"},
  {"line":111,"text":"func (r *aliasResolver) GetModeForUsageLocation(file ast.HasFileName, moduleSpecifier *ast.StringLiteralLike) core.ResolutionMode {"},
  {"line":112,"text":"\treturn core.ModuleKindESNext"},
  {"line":113,"text":"}"},
  {"line":116,"text":"func (r *aliasResolver) GetResolvedModule(currentSourceFile ast.HasFileName, moduleReference string, mode core.ResolutionMode) *module.ResolvedModule {"},
  {"line":117,"text":"\tcache, _ := r.resolvedModules.LoadOrStore(currentSourceFile.Path(), &collections.SyncMap[module.ModeAwareCacheKey, *module.ResolvedModule]{})"},
  {"line":118,"text":"\tif resolved, ok := cache.Load(module.ModeAwareCacheKey{Name: moduleReference, Mode: mode}); ok {"},
  {"line":119,"text":"\t\treturn resolved"},
  {"line":120,"text":"\t}"},
  {"line":121,"text":"\tresolved, _ := r.moduleResolver.ResolveModuleName(moduleReference, currentSourceFile.FileName(), mode, nil)"},
  {"line":122,"text":"\tresolved, _ = cache.LoadOrStore(module.ModeAwareCacheKey{Name: moduleReference, Mode: mode}, resolved)"},
  {"line":123,"text":"\tif !resolved.IsResolved() && !tspath.PathIsRelative(moduleReference) {"},
  {"line":124,"text":"\t\tr.onFailedAmbientModuleLookup(currentSourceFile, moduleReference)"},
  {"line":125,"text":"\t}"},
  {"line":126,"text":"\treturn resolved"},
  {"line":127,"text":"}"},
  {"line":130,"text":"func (r *aliasResolver) GetSourceFileForResolvedModule(fileName string) *ast.SourceFile {"},
  {"line":131,"text":"\treturn r.GetSourceFile(fileName)"},
  {"line":132,"text":"}"},
  {"line":135,"text":"func (r *aliasResolver) GetResolvedModules() map[tspath.Path]module.ModeAwareCache[*module.ResolvedModule] {"},
  {"line":137,"text":"\treturn nil"},
  {"line":138,"text":"}"},
  {"line":143,"text":"func (r *aliasResolver) GetSymlinkCache() *symlinks.KnownSymlinks {"},
  {"line":144,"text":"\tpanic(\"unimplemented\")"},
  {"line":145,"text":"}"},
  {"line":148,"text":"func (r *aliasResolver) GetSourceFileMetaData(path tspath.Path) ast.SourceFileMetaData {"},
  {"line":149,"text":"\tpanic(\"unimplemented\")"},
  {"line":150,"text":"}"},
  {"line":153,"text":"func (r *aliasResolver) CommonSourceDirectory() string {"},
  {"line":154,"text":"\tpanic(\"unimplemented\")"},
  {"line":155,"text":"}"},
  {"line":158,"text":"func (r *aliasResolver) FileExists(fileName string) bool {"},
  {"line":159,"text":"\tpanic(\"unimplemented\")"},
  {"line":160,"text":"}"},
  {"line":163,"text":"func (r *aliasResolver) GetGlobalTypingsCacheLocation() string {"},
  {"line":164,"text":"\tpanic(\"unimplemented\")"},
  {"line":165,"text":"}"},
  {"line":168,"text":"func (r *aliasResolver) GetImportHelpersImportSpecifier(path tspath.Path) *ast.Node {"},
  {"line":169,"text":"\tpanic(\"unimplemented\")"},
  {"line":170,"text":"}"},
  {"line":173,"text":"func (r *aliasResolver) GetJSXRuntimeImportSpecifier(path tspath.Path) (moduleReference string, specifier *ast.Node) {"},
  {"line":174,"text":"\tpanic(\"unimplemented\")"},
  {"line":175,"text":"}"},
  {"line":178,"text":"func (r *aliasResolver) GetNearestAncestorDirectoryWithPackageJson(dirname string) string {"},
  {"line":179,"text":"\tpanic(\"unimplemented\")"},
  {"line":180,"text":"}"},
  {"line":183,"text":"func (r *aliasResolver) GetPackageJsonInfo(pkgJsonPath string) *packagejson.InfoCacheEntry {"},
  {"line":184,"text":"\tpanic(\"unimplemented\")"},
  {"line":185,"text":"}"},
  {"line":188,"text":"func (r *aliasResolver) GetProjectReferenceFromOutputDts(path tspath.Path) *tsoptions.SourceOutputAndProjectReference {"},
  {"line":189,"text":"\tpanic(\"unimplemented\")"},
  {"line":190,"text":"}"},
  {"line":193,"text":"func (r *aliasResolver) GetProjectReferenceFromSource(path tspath.Path) *tsoptions.SourceOutputAndProjectReference {"},
  {"line":194,"text":"\tpanic(\"unimplemented\")"},
  {"line":195,"text":"}"},
  {"line":198,"text":"func (r *aliasResolver) GetRedirectForResolution(file ast.HasFileName) *tsoptions.ParsedCommandLine {"},
  {"line":199,"text":"\tpanic(\"unimplemented\")"},
  {"line":200,"text":"}"},
  {"line":203,"text":"func (r *aliasResolver) GetRedirectTargets(path tspath.Path) []string {"},
  {"line":204,"text":"\tpanic(\"unimplemented\")"},
  {"line":205,"text":"}"},
  {"line":208,"text":"func (r *aliasResolver) GetResolvedModuleFromModuleSpecifier(file ast.HasFileName, moduleSpecifier *ast.StringLiteralLike) *module.ResolvedModule {"},
  {"line":209,"text":"\tpanic(\"unimplemented\")"},
  {"line":210,"text":"}"},
  {"line":213,"text":"func (r *aliasResolver) GetSourceOfProjectReferenceIfOutputIncluded(file ast.HasFileName) string {"},
  {"line":214,"text":"\tpanic(\"unimplemented\")"},
  {"line":215,"text":"}"},
  {"line":218,"text":"func (r *aliasResolver) IsSourceFileDefaultLibrary(path tspath.Path) bool {"},
  {"line":219,"text":"\tpanic(\"unimplemented\")"},
  {"line":220,"text":"}"},
  {"line":223,"text":"func (r *aliasResolver) IsSourceFromProjectReference(path tspath.Path) bool {"},
  {"line":224,"text":"\tpanic(\"unimplemented\")"},
  {"line":225,"text":"}"},
  {"line":228,"text":"func (r *aliasResolver) SourceFileMayBeEmitted(sourceFile *ast.SourceFile, forceDtsEmit bool) bool {"},
  {"line":229,"text":"\tpanic(\"unimplemented\")"},
  {"line":230,"text":"}"},
  {"line":232,"text":"func (r *aliasResolver) GetPackagesMap() map[string]bool {"},
  {"line":233,"text":"\treturn nil"},
  {"line":234,"text":"}"},
  {"line":236,"text":"var _ checker.Program = (*aliasResolver)(nil)"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportAliasResolverSourceLines.find((entry) => entry.line === line)?.text;
}
