/**
 * Language-service parity map for TS-Go `ls/autoimport/import_adder.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderUpstreamPath = "ls/autoimport/import_adder.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderDeclarations: readonly UpstreamDeclaration[] = [
  {"line":24,"kind":"type","name":"ImportAdder"},
  {"line":32,"kind":"type","name":"addToExistingState"},
  {"line":39,"kind":"type","name":"importsCollection"},
  {"line":46,"kind":"func","name":"newImportsKey"},
  {"line":53,"kind":"type","name":"importAdder"},
  {"line":70,"kind":"func","name":"NewImportAdder"},
  {"line":94,"kind":"func","name":"HasFixes","receiver":"adder *importAdder"},
  {"line":102,"kind":"func","name":"AddImportFromExportedSymbol","receiver":"adder *importAdder"},
  {"line":118,"kind":"func","name":"Edits","receiver":"adder *importAdder"},
  {"line":175,"kind":"func","name":"sortedNamedImports"},
  {"line":186,"kind":"func","name":"AddImportFix","receiver":"adder *importAdder"},
  {"line":327,"kind":"func","name":"reduceAddAsTypeOnlyValues"},
  {"line":334,"kind":"func","name":"getNewImportEntry","receiver":"adder *importAdder"},
  {"line":372,"kind":"func","name":"getAllExportsForSymbol","receiver":"adder *importAdder"},
  {"line":381,"kind":"func","name":"TypeToAutoImportableTypeNode"},
  {"line":397,"kind":"func","name":"TypeNodeToAutoImportableTypeNode"},
  {"line":414,"kind":"func","name":"importSymbols"},
  {"line":426,"kind":"func","name":"TryGetAutoImportableReferenceFromTypeNode"},
  {"line":464,"kind":"func","name":"getNameForExportedSymbol"},
  {"line":480,"kind":"func","name":"replaceFirstIdentifierOfEntityName"},
  {"line":490,"kind":"func","name":"getImportFixForSymbol","receiver":"adder *importAdder"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package autoimport"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"fmt\""},
  {"line":6,"text":"\t\"maps\""},
  {"line":7,"text":"\t\"slices\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/debug\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/locale\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/change\""},
  {"line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"line":20,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":21,"text":"\t\"github.com/microsoft/typescript-go/internal/nodebuilder\""},
  {"line":22,"text":")"},
  {"line":24,"text":"type ImportAdder interface {"},
  {"line":25,"text":"\tHasFixes() bool"},
  {"line":26,"text":"\tAddImportFromExportedSymbol(symbol *ast.Symbol, isValidTypeOnlyUseSite bool)"},
  {"line":27,"text":"\tAddImportFix(fix *Fix)"},
  {"line":28,"text":"\tEdits() []*lsproto.TextEdit"},
  {"line":29,"text":"}"},
  {"line":32,"text":"type addToExistingState struct {"},
  {"line":33,"text":"\timportClauseOrBindingPattern *ast.ImportClauseOrBindingPattern"},
  {"line":34,"text":"\tdefaultImport                *newImportBinding"},
  {"line":35,"text":"\tnamedImports                 map[string]*newImportBinding"},
  {"line":36,"text":"}"},
  {"line":39,"text":"type importsCollection struct {"},
  {"line":40,"text":"\tdefaultImport       *newImportBinding"},
  {"line":41,"text":"\tnamedImports        map[string]*newImportBinding"},
  {"line":42,"text":"\tnamespaceLikeImport *newImportBinding"},
  {"line":43,"text":"\tuseRequire          bool"},
  {"line":44,"text":"}"},
  {"line":46,"text":"func newImportsKey(moduleSpecifier string, topLevelTypeOnly bool) string {"},
  {"line":47,"text":"\tif topLevelTypeOnly {"},
  {"line":48,"text":"\t\treturn \"1|\" + moduleSpecifier"},
  {"line":49,"text":"\t}"},
  {"line":50,"text":"\treturn \"0|\" + moduleSpecifier"},
  {"line":51,"text":"}"},
  {"line":53,"text":"type importAdder struct {"},
  {"line":55,"text":"\tctx           context.Context"},
  {"line":56,"text":"\tchecker       *checker.Checker"},
  {"line":57,"text":"\tview          *View"},
  {"line":58,"text":"\tformatOptions lsutil.FormatCodeSettings"},
  {"line":59,"text":"\tconverters    *lsconv.Converters"},
  {"line":60,"text":"\tpreferences   lsutil.UserPreferences"},
  {"line":63,"text":"\taddToNamespace []*Fix                                                    // Namespace fixes don't conflict, so just build a list"},
  {"line":64,"text":"\timportType     []*Fix                                                    // JSDoc type import fixes"},
  {"line":65,"text":"\taddToExisting  map[*ast.ImportClauseOrBindingPattern]*addToExistingState // importClauseOrBindingPattern -> default or named bindings"},
  {"line":66,"text":"\tnewImports     map[string]*importsCollection                             // module specifier + type only -> imports"},
  {"line":68,"text":"}"},
  {"line":70,"text":"func NewImportAdder("},
  {"line":71,"text":"\tctx context.Context,"},
  {"line":72,"text":"\tprogram *compiler.Program,"},
  {"line":73,"text":"\tchecker *checker.Checker,"},
  {"line":74,"text":"\tfile *ast.SourceFile,"},
  {"line":75,"text":"\tview *View,"},
  {"line":76,"text":"\tformatOptions lsutil.FormatCodeSettings,"},
  {"line":77,"text":"\tconverters *lsconv.Converters,"},
  {"line":78,"text":"\tpreferences lsutil.UserPreferences,"},
  {"line":79,"text":") ImportAdder {"},
  {"line":80,"text":"\treturn &importAdder{"},
  {"line":81,"text":"\t\tctx:            ctx,"},
  {"line":82,"text":"\t\tchecker:        checker,"},
  {"line":83,"text":"\t\tview:           view,"},
  {"line":84,"text":"\t\tformatOptions:  formatOptions,"},
  {"line":85,"text":"\t\tconverters:     converters,"},
  {"line":86,"text":"\t\tpreferences:    preferences,"},
  {"line":87,"text":"\t\taddToNamespace: nil,"},
  {"line":88,"text":"\t\timportType:     nil,"},
  {"line":89,"text":"\t\taddToExisting:  make(map[*ast.Node]*addToExistingState),"},
  {"line":90,"text":"\t\tnewImports:     make(map[string]*importsCollection),"},
  {"line":91,"text":"\t}"},
  {"line":92,"text":"}"},
  {"line":94,"text":"func (adder *importAdder) HasFixes() bool {"},
  {"line":95,"text":"\treturn len(adder.addToNamespace) > 0 ||"},
  {"line":96,"text":"\t\tlen(adder.importType) > 0 ||"},
  {"line":97,"text":"\t\tlen(adder.addToExisting) > 0 ||"},
  {"line":98,"text":"\t\tlen(adder.newImports) > 0"},
  {"line":99,"text":"}"},
  {"line":102,"text":"func (adder *importAdder) AddImportFromExportedSymbol(exportedSymbol *ast.Symbol, isValidTypeOnlyUseSite bool) {"},
  {"line":103,"text":"\tsymbol := adder.checker.GetMergedSymbol(adder.checker.SkipAlias(exportedSymbol))"},
  {"line":104,"text":"\texportInfos := adder.getAllExportsForSymbol(symbol)"},
  {"line":105,"text":"\tif len(exportInfos) == 0 {"},
  {"line":109,"text":"\t\treturn"},
  {"line":110,"text":"\t}"},
  {"line":111,"text":"\tfix := adder.getImportFixForSymbol(adder.view, adder.view.importingFile, exportInfos, isValidTypeOnlyUseSite)"},
  {"line":112,"text":"\tif fix != nil {"},
  {"line":114,"text":"\t\tadder.AddImportFix(fix)"},
  {"line":115,"text":"\t}"},
  {"line":116,"text":"}"},
  {"line":118,"text":"func (adder *importAdder) Edits() []*lsproto.TextEdit {"},
  {"line":120,"text":"\ttracker := change.NewTracker(adder.ctx, adder.view.program.Options(), adder.formatOptions, adder.converters)"},
  {"line":121,"text":"\tquotePreference := lsutil.GetQuotePreference(adder.view.importingFile, adder.preferences)"},
  {"line":122,"text":"\tfor _, fix := range adder.addToNamespace {"},
  {"line":123,"text":"\t\taddNamespaceQualifier(fix, tracker, adder.view.importingFile, locale.Default)"},
  {"line":124,"text":"\t}"},
  {"line":125,"text":"\tfor _, fix := range adder.importType {"},
  {"line":126,"text":"\t\taddImportType(fix, adder.view.importingFile, adder.preferences, tracker, locale.Default)"},
  {"line":127,"text":"\t}"},
  {"line":128,"text":"\tfor clauseOrPattern, entry := range adder.addToExisting {"},
  {"line":129,"text":"\t\taddToExistingImport("},
  {"line":130,"text":"\t\t\ttracker,"},
  {"line":131,"text":"\t\t\tadder.view.importingFile,"},
  {"line":132,"text":"\t\t\tclauseOrPattern,"},
  {"line":133,"text":"\t\t\tentry.defaultImport,"},
  {"line":134,"text":"\t\t\tsortedNamedImports(entry.namedImports),"},
  {"line":135,"text":"\t\t\tadder.preferences,"},
  {"line":136,"text":"\t\t)"},
  {"line":137,"text":"\t}"},
  {"line":139,"text":"\tvar newDeclarations []*ast.AnyImportOrRequireStatement"},
  {"line":140,"text":"\tfor key, newImport := range adder.newImports {"},
  {"line":141,"text":"\t\tmoduleSpecifier := key[2:] // From `${0 | 1}|${moduleSpecifier}` format"},
  {"line":142,"text":"\t\tvar declarations []*ast.AnyImportOrRequireStatement"},
  {"line":143,"text":"\t\tif newImport.useRequire {"},
  {"line":144,"text":"\t\t\tdeclarations = getNewRequires("},
  {"line":145,"text":"\t\t\t\ttracker,"},
  {"line":146,"text":"\t\t\t\tmoduleSpecifier,"},
  {"line":147,"text":"\t\t\t\tquotePreference,"},
  {"line":148,"text":"\t\t\t\tnewImport.defaultImport,"},
  {"line":149,"text":"\t\t\t\tsortedNamedImports(newImport.namedImports),"},
  {"line":150,"text":"\t\t\t\tnewImport.namespaceLikeImport,"},
  {"line":151,"text":"\t\t\t\tadder.view.program.Options(),"},
  {"line":152,"text":"\t\t\t)"},
  {"line":153,"text":"\t\t} else {"},
  {"line":154,"text":"\t\t\tdeclarations = getNewImports("},
  {"line":155,"text":"\t\t\t\ttracker,"},
  {"line":156,"text":"\t\t\t\tmoduleSpecifier,"},
  {"line":157,"text":"\t\t\t\tquotePreference,"},
  {"line":158,"text":"\t\t\t\tnewImport.defaultImport,"},
  {"line":159,"text":"\t\t\t\tsortedNamedImports(newImport.namedImports),"},
  {"line":160,"text":"\t\t\t\tnewImport.namespaceLikeImport,"},
  {"line":161,"text":"\t\t\t\tadder.view.program.Options(),"},
  {"line":162,"text":"\t\t\t\tadder.preferences,"},
  {"line":163,"text":"\t\t\t)"},
  {"line":164,"text":"\t\t}"},
  {"line":165,"text":"\t\tnewDeclarations = append(newDeclarations, declarations...)"},
  {"line":166,"text":"\t}"},
  {"line":168,"text":"\tif len(newDeclarations) > 0 {"},
  {"line":169,"text":"\t\tinsertImports(tracker, adder.view.importingFile, newDeclarations, true /*blankLineBetween*/, adder.preferences)"},
  {"line":170,"text":"\t}"},
  {"line":172,"text":"\treturn tracker.GetChanges()[adder.view.importingFile.FileName()]"},
  {"line":173,"text":"}"},
  {"line":175,"text":"func sortedNamedImports(m map[string]*newImportBinding) []*newImportBinding {"},
  {"line":176,"text":"\tkeys := slices.Sorted(maps.Keys(m))"},
  {"line":177,"text":"\tresult := make([]*newImportBinding, 0, len(keys))"},
  {"line":178,"text":"\tfor _, k := range keys {"},
  {"line":179,"text":"\t\tresult = append(result, m[k])"},
  {"line":180,"text":"\t}"},
  {"line":181,"text":"\treturn result"},
  {"line":182,"text":"}"},
  {"line":186,"text":"func (adder *importAdder) AddImportFix(fix *Fix) {"},
  {"line":187,"text":"\tsymbolName := fix.Name"},
  {"line":188,"text":"\tcompilerOptions := adder.view.program.Options()"},
  {"line":190,"text":"\tswitch fix.Kind {"},
  {"line":191,"text":"\tcase lsproto.AutoImportFixKindUseNamespace:"},
  {"line":192,"text":"\t\tadder.addToNamespace = append(adder.addToNamespace, fix)"},
  {"line":193,"text":"\tcase lsproto.AutoImportFixKindJsdocTypeImport:"},
  {"line":194,"text":"\t\tadder.importType = append(adder.importType, fix)"},
  {"line":195,"text":"\tcase lsproto.AutoImportFixKindAddToExisting:"},
  {"line":196,"text":"\t\texistingFix := getAddToExistingImportFix(adder.view.importingFile, fix)"},
  {"line":197,"text":"\t\tentry := adder.addToExisting[existingFix.importClauseOrBindingPattern]"},
  {"line":198,"text":"\t\tif entry == nil {"},
  {"line":199,"text":"\t\t\tentry = &addToExistingState{"},
  {"line":200,"text":"\t\t\t\timportClauseOrBindingPattern: existingFix.importClauseOrBindingPattern,"},
  {"line":201,"text":"\t\t\t\tnamedImports:                 make(map[string]*newImportBinding),"},
  {"line":202,"text":"\t\t\t}"},
  {"line":203,"text":"\t\t\tadder.addToExisting[existingFix.importClauseOrBindingPattern] = entry"},
  {"line":204,"text":"\t\t}"},
  {"line":206,"text":"\t\tif fix.ImportKind == lsproto.ImportKindNamed {"},
  {"line":207,"text":"\t\t\tprevImport := entry.namedImports[symbolName]"},
  {"line":208,"text":"\t\t\tvar prevTypeOnly lsproto.AddAsTypeOnly"},
  {"line":209,"text":"\t\t\tif prevImport != nil {"},
  {"line":210,"text":"\t\t\t\tprevTypeOnly = prevImport.addAsTypeOnly"},
  {"line":211,"text":"\t\t\t}"},
  {"line":212,"text":"\t\t\tentry.namedImports[symbolName] = &newImportBinding{"},
  {"line":213,"text":"\t\t\t\tkind:          lsproto.ImportKindNamed,"},
  {"line":214,"text":"\t\t\t\tname:          symbolName,"},
  {"line":215,"text":"\t\t\t\taddAsTypeOnly: reduceAddAsTypeOnlyValues(prevTypeOnly, fix.AddAsTypeOnly),"},
  {"line":216,"text":"\t\t\t\tpropertyName:  existingFix.namedImport.propertyName,"},
  {"line":217,"text":"\t\t\t}"},
  {"line":218,"text":"\t\t} else {"},
  {"line":220,"text":"\t\t\tdebug.Assert("},
  {"line":221,"text":"\t\t\t\tentry.defaultImport == nil || entry.defaultImport.name == symbolName,"},
  {"line":222,"text":"\t\t\t\t\"(Add to Existing) Default import should be missing or match symbolName\","},
  {"line":223,"text":"\t\t\t)"},
  {"line":224,"text":"\t\t\tvar prevTypeOnly lsproto.AddAsTypeOnly"},
  {"line":225,"text":"\t\t\tif entry.defaultImport != nil {"},
  {"line":226,"text":"\t\t\t\tprevTypeOnly = entry.defaultImport.addAsTypeOnly"},
  {"line":227,"text":"\t\t\t}"},
  {"line":228,"text":"\t\t\tentry.defaultImport = &newImportBinding{"},
  {"line":229,"text":"\t\t\t\tkind:          lsproto.ImportKindDefault,"},
  {"line":230,"text":"\t\t\t\tname:          symbolName,"},
  {"line":231,"text":"\t\t\t\taddAsTypeOnly: reduceAddAsTypeOnlyValues(prevTypeOnly, fix.AddAsTypeOnly),"},
  {"line":232,"text":"\t\t\t}"},
  {"line":233,"text":"\t\t}"},
  {"line":235,"text":"\tcase lsproto.AutoImportFixKindAddNew:"},
  {"line":236,"text":"\t\tentry := adder.getNewImportEntry(fix.ModuleSpecifier, fix.ImportKind, fix.UseRequire, fix.AddAsTypeOnly)"},
  {"line":237,"text":"\t\tdebug.Assert("},
  {"line":238,"text":"\t\t\tentry.useRequire == fix.UseRequire,"},
  {"line":239,"text":"\t\t\t\"(Add new) Tried to add an `import` and a `require` for the same module\","},
  {"line":240,"text":"\t\t)"},
  {"line":242,"text":"\t\tswitch fix.ImportKind {"},
  {"line":243,"text":"\t\tcase lsproto.ImportKindDefault:"},
  {"line":244,"text":"\t\t\tdebug.Assert("},
  {"line":245,"text":"\t\t\t\tentry.defaultImport == nil || entry.defaultImport.name == symbolName,"},
  {"line":246,"text":"\t\t\t\t\"(Add new) Default import should be missing or match symbolName\","},
  {"line":247,"text":"\t\t\t)"},
  {"line":248,"text":"\t\t\tvar prevTypeOnly lsproto.AddAsTypeOnly"},
  {"line":249,"text":"\t\t\tif entry.defaultImport != nil {"},
  {"line":250,"text":"\t\t\t\tprevTypeOnly = entry.defaultImport.addAsTypeOnly"},
  {"line":251,"text":"\t\t\t}"},
  {"line":252,"text":"\t\t\tentry.defaultImport = &newImportBinding{"},
  {"line":253,"text":"\t\t\t\tkind:          lsproto.ImportKindDefault,"},
  {"line":254,"text":"\t\t\t\tname:          symbolName,"},
  {"line":255,"text":"\t\t\t\taddAsTypeOnly: reduceAddAsTypeOnlyValues(prevTypeOnly, fix.AddAsTypeOnly),"},
  {"line":256,"text":"\t\t\t}"},
  {"line":258,"text":"\t\tcase lsproto.ImportKindNamed:"},
  {"line":259,"text":"\t\t\tif entry.namedImports == nil {"},
  {"line":260,"text":"\t\t\t\tentry.namedImports = make(map[string]*newImportBinding)"},
  {"line":261,"text":"\t\t\t}"},
  {"line":262,"text":"\t\t\tprevImport := entry.namedImports[symbolName]"},
  {"line":263,"text":"\t\t\tvar prevTypeOnly lsproto.AddAsTypeOnly"},
  {"line":264,"text":"\t\t\tif prevImport != nil {"},
  {"line":265,"text":"\t\t\t\tprevTypeOnly = prevImport.addAsTypeOnly"},
  {"line":266,"text":"\t\t\t}"},
  {"line":267,"text":"\t\t\tentry.namedImports[symbolName] = &newImportBinding{"},
  {"line":268,"text":"\t\t\t\tkind:          lsproto.ImportKindNamed,"},
  {"line":269,"text":"\t\t\t\tname:          symbolName,"},
  {"line":270,"text":"\t\t\t\taddAsTypeOnly: reduceAddAsTypeOnlyValues(prevTypeOnly, fix.AddAsTypeOnly),"},
  {"line":272,"text":"\t\t\t}"},
  {"line":274,"text":"\t\tcase lsproto.ImportKindCommonJS:"},
  {"line":275,"text":"\t\t\tif compilerOptions.VerbatimModuleSyntax == core.TSTrue {"},
  {"line":276,"text":"\t\t\t\tif entry.namedImports == nil {"},
  {"line":277,"text":"\t\t\t\t\tentry.namedImports = make(map[string]*newImportBinding)"},
  {"line":278,"text":"\t\t\t\t}"},
  {"line":279,"text":"\t\t\t\tprevImport := entry.namedImports[symbolName]"},
  {"line":280,"text":"\t\t\t\tvar prevTypeOnly lsproto.AddAsTypeOnly"},
  {"line":281,"text":"\t\t\t\tif prevImport != nil {"},
  {"line":282,"text":"\t\t\t\t\tprevTypeOnly = prevImport.addAsTypeOnly"},
  {"line":283,"text":"\t\t\t\t}"},
  {"line":284,"text":"\t\t\t\tentry.namedImports[symbolName] = &newImportBinding{"},
  {"line":285,"text":"\t\t\t\t\tkind:          lsproto.ImportKindCommonJS,"},
  {"line":286,"text":"\t\t\t\t\tname:          symbolName,"},
  {"line":287,"text":"\t\t\t\t\taddAsTypeOnly: reduceAddAsTypeOnlyValues(prevTypeOnly, fix.AddAsTypeOnly),"},
  {"line":289,"text":"\t\t\t\t}"},
  {"line":290,"text":"\t\t\t} else {"},
  {"line":291,"text":"\t\t\t\tdebug.Assert("},
  {"line":292,"text":"\t\t\t\t\tentry.namespaceLikeImport == nil || entry.namespaceLikeImport.name == symbolName,"},
  {"line":293,"text":"\t\t\t\t\t\"Namespacelike import should be missing or match symbolName\","},
  {"line":294,"text":"\t\t\t\t)"},
  {"line":295,"text":"\t\t\t\tentry.namespaceLikeImport = &newImportBinding{"},
  {"line":296,"text":"\t\t\t\t\tkind:          lsproto.ImportKindCommonJS,"},
  {"line":297,"text":"\t\t\t\t\tname:          symbolName,"},
  {"line":298,"text":"\t\t\t\t\taddAsTypeOnly: fix.AddAsTypeOnly,"},
  {"line":299,"text":"\t\t\t\t}"},
  {"line":300,"text":"\t\t\t}"},
  {"line":302,"text":"\t\tcase lsproto.ImportKindNamespace:"},
  {"line":303,"text":"\t\t\tdebug.Assert("},
  {"line":304,"text":"\t\t\t\tentry.namespaceLikeImport == nil || entry.namespaceLikeImport.name == symbolName,"},
  {"line":305,"text":"\t\t\t\t\"Namespacelike import should be missing or match symbolName\","},
  {"line":306,"text":"\t\t\t)"},
  {"line":307,"text":"\t\t\tentry.namespaceLikeImport = &newImportBinding{"},
  {"line":308,"text":"\t\t\t\tkind:          lsproto.ImportKindNamespace,"},
  {"line":309,"text":"\t\t\t\tname:          symbolName,"},
  {"line":310,"text":"\t\t\t\taddAsTypeOnly: fix.AddAsTypeOnly,"},
  {"line":311,"text":"\t\t\t}"},
  {"line":312,"text":"\t\t}"},
  {"line":314,"text":"\tcase lsproto.AutoImportFixKindPromoteTypeOnly:"},
  {"line":316,"text":"\tdefault:"},
  {"line":317,"text":"\t\tdebug.Fail(fmt.Sprintf(\"Unexpected fix kind: %v\", fix.Kind))"},
  {"line":318,"text":"\t}"},
  {"line":319,"text":"}"},
  {"line":327,"text":"func reduceAddAsTypeOnlyValues(prevValue, newValue lsproto.AddAsTypeOnly) lsproto.AddAsTypeOnly {"},
  {"line":328,"text":"\tif newValue > prevValue {"},
  {"line":329,"text":"\t\treturn newValue"},
  {"line":330,"text":"\t}"},
  {"line":331,"text":"\treturn prevValue"},
  {"line":332,"text":"}"},
  {"line":334,"text":"func (adder *importAdder) getNewImportEntry(moduleSpecifier string, importKind lsproto.ImportKind, useRequire bool, addAsTypeOnly lsproto.AddAsTypeOnly) *importsCollection {"},
  {"line":341,"text":"\ttypeOnlyKey := newImportsKey(moduleSpecifier, true /*topLevelTypeOnly*/)"},
  {"line":342,"text":"\tnonTypeOnlyKey := newImportsKey(moduleSpecifier, false /*topLevelTypeOnly*/)"},
  {"line":343,"text":"\ttypeOnlyEntry := adder.newImports[typeOnlyKey]"},
  {"line":344,"text":"\tnonTypeOnlyEntry := adder.newImports[nonTypeOnlyKey]"},
  {"line":345,"text":"\tnewEntry := &importsCollection{"},
  {"line":346,"text":"\t\tuseRequire: useRequire,"},
  {"line":347,"text":"\t}"},
  {"line":349,"text":"\tif importKind == lsproto.ImportKindDefault && addAsTypeOnly == lsproto.AddAsTypeOnlyRequired {"},
  {"line":350,"text":"\t\tif typeOnlyEntry != nil {"},
  {"line":351,"text":"\t\t\treturn typeOnlyEntry"},
  {"line":352,"text":"\t\t}"},
  {"line":353,"text":"\t\tadder.newImports[typeOnlyKey] = newEntry"},
  {"line":354,"text":"\t\treturn newEntry"},
  {"line":355,"text":"\t}"},
  {"line":357,"text":"\tif addAsTypeOnly == lsproto.AddAsTypeOnlyAllowed && (typeOnlyEntry != nil || nonTypeOnlyEntry != nil) {"},
  {"line":358,"text":"\t\tif typeOnlyEntry != nil {"},
  {"line":359,"text":"\t\t\treturn typeOnlyEntry"},
  {"line":360,"text":"\t\t}"},
  {"line":361,"text":"\t\treturn nonTypeOnlyEntry"},
  {"line":362,"text":"\t}"},
  {"line":364,"text":"\tif nonTypeOnlyEntry != nil {"},
  {"line":365,"text":"\t\treturn nonTypeOnlyEntry"},
  {"line":366,"text":"\t}"},
  {"line":368,"text":"\tadder.newImports[nonTypeOnlyKey] = newEntry"},
  {"line":369,"text":"\treturn newEntry"},
  {"line":370,"text":"}"},
  {"line":372,"text":"func (adder *importAdder) getAllExportsForSymbol("},
  {"line":373,"text":"\tsymbol *ast.Symbol,"},
  {"line":374,"text":") []*Export {"},
  {"line":375,"text":"\tif export := SymbolToExport(symbol, adder.checker); export != nil {"},
  {"line":376,"text":"\t\treturn adder.view.SearchByExportID(export.ExportID)"},
  {"line":377,"text":"\t}"},
  {"line":378,"text":"\treturn nil"},
  {"line":379,"text":"}"},
  {"line":381,"text":"func TypeToAutoImportableTypeNode("},
  {"line":382,"text":"\tc *checker.Checker,"},
  {"line":383,"text":"\timportAdder ImportAdder,"},
  {"line":384,"text":"\tt *checker.Type,"},
  {"line":385,"text":"\tcontextNode *ast.Node, // !!! flags"},
  {"line":386,"text":") *ast.TypeNode {"},
  {"line":387,"text":"\tidToSymbol := make(map[*ast.IdentifierNode]*ast.Symbol)"},
  {"line":388,"text":"\ttypeNode := c.TypeToTypeNode(t, contextNode, nodebuilder.FlagsNone, idToSymbol)"},
  {"line":389,"text":"\tif typeNode == nil {"},
  {"line":390,"text":"\t\treturn nil"},
  {"line":391,"text":"\t}"},
  {"line":392,"text":"\treturn TypeNodeToAutoImportableTypeNode(typeNode, importAdder, idToSymbol)"},
  {"line":393,"text":"}"},
  {"line":397,"text":"func TypeNodeToAutoImportableTypeNode("},
  {"line":398,"text":"\ttypeNode *ast.TypeNode,"},
  {"line":399,"text":"\timportAdder ImportAdder,"},
  {"line":400,"text":"\tidToSymbol map[*ast.IdentifierNode]*ast.Symbol,"},
  {"line":401,"text":") *ast.TypeNode {"},
  {"line":402,"text":"\treferenceTypeNode, importableSymbols := TryGetAutoImportableReferenceFromTypeNode(typeNode, idToSymbol)"},
  {"line":403,"text":"\tif referenceTypeNode != nil {"},
  {"line":404,"text":"\t\tif importAdder != nil {"},
  {"line":405,"text":"\t\t\timportSymbols(importAdder, importableSymbols)"},
  {"line":406,"text":"\t\t}"},
  {"line":407,"text":"\t\ttypeNode = referenceTypeNode"},
  {"line":408,"text":"\t}"},
  {"line":411,"text":"\treturn typeNode"},
  {"line":412,"text":"}"},
  {"line":414,"text":"func importSymbols(importAdder ImportAdder, symbols []*ast.Symbol) {"},
  {"line":415,"text":"\tfor _, symbol := range symbols {"},
  {"line":416,"text":"\t\timportAdder.AddImportFromExportedSymbol(symbol, true /*isValidTypeOnlyUseSite*/)"},
  {"line":417,"text":"\t}"},
  {"line":418,"text":"}"},
  {"line":426,"text":"func TryGetAutoImportableReferenceFromTypeNode(importTypeNode *ast.TypeNode, idToSymbol map[*ast.IdentifierNode]*ast.Symbol) (*ast.TypeNode, []*ast.Symbol) {"},
  {"line":427,"text":"\tvar symbols []*ast.Symbol"},
  {"line":428,"text":"\tvar visitor *ast.NodeVisitor"},
  {"line":429,"text":"\tfactory := ast.NewNodeFactory(ast.NodeFactoryHooks{})"},
  {"line":430,"text":"\tvisit := func(node *ast.Node) *ast.Node {"},
  {"line":431,"text":"\t\tif ast.IsLiteralImportTypeNode(node) && node.AsImportTypeNode().Qualifier != nil {"},
  {"line":432,"text":"\t\t\timportTypeNode := node.AsImportTypeNode()"},
  {"line":434,"text":"\t\t\tfirstIdentifier := ast.GetFirstIdentifier(importTypeNode.Qualifier)"},
  {"line":435,"text":"\t\t\tsymbol := idToSymbol[firstIdentifier]"},
  {"line":436,"text":"\t\t\tif symbol == nil {"},
  {"line":440,"text":"\t\t\t\treturn node.VisitEachChild(visitor)"},
  {"line":441,"text":"\t\t\t}"},
  {"line":442,"text":"\t\t\tname := getNameForExportedSymbol(symbol, false /*preferCapitalized*/)"},
  {"line":443,"text":"\t\t\tvar qualifier *ast.EntityName"},
  {"line":444,"text":"\t\t\tif name != firstIdentifier.Text() {"},
  {"line":445,"text":"\t\t\t\tqualifier = replaceFirstIdentifierOfEntityName(factory, importTypeNode.Qualifier, factory.NewIdentifier(name))"},
  {"line":446,"text":"\t\t\t} else {"},
  {"line":447,"text":"\t\t\t\tqualifier = importTypeNode.Qualifier"},
  {"line":448,"text":"\t\t\t}"},
  {"line":449,"text":"\t\t\tsymbols = append(symbols, symbol)"},
  {"line":450,"text":"\t\t\ttypeArguments := visitor.VisitNodes(importTypeNode.TypeArguments)"},
  {"line":451,"text":"\t\t\treturn factory.NewTypeReferenceNode(qualifier, typeArguments)"},
  {"line":452,"text":"\t\t}"},
  {"line":453,"text":"\t\treturn visitor.VisitEachChild(node)"},
  {"line":454,"text":"\t}"},
  {"line":455,"text":"\tvisitor = ast.NewNodeVisitor(visit, factory, ast.NodeVisitorHooks{})"},
  {"line":457,"text":"\ttypeNode := visitor.VisitNode(importTypeNode)"},
  {"line":458,"text":"\tdebug.Assert(typeNode == nil || ast.IsTypeNode(typeNode), \"expected a type node\")"},
  {"line":459,"text":"\treturn typeNode, symbols"},
  {"line":460,"text":"}"},
  {"line":464,"text":"func getNameForExportedSymbol(symbol *ast.Symbol, preferCapitalized bool) string {"},
  {"line":465,"text":"\tif symbol.Name == ast.InternalSymbolNameExportEquals || symbol.Name == ast.InternalSymbolNameDefault {"},
  {"line":470,"text":"\t\tname := getDefaultLikeExportNameFromDeclaration(symbol)"},
  {"line":471,"text":"\t\tif name != \"\" {"},
  {"line":472,"text":"\t\t\treturn name"},
  {"line":473,"text":"\t\t}"},
  {"line":474,"text":"\t\tdebug.Assert(symbol.Parent != nil, \"Expected exported symbol to have module symbol as parent\")"},
  {"line":475,"text":"\t\treturn lsutil.ModuleSymbolToValidIdentifier(symbol.Parent, preferCapitalized)"},
  {"line":476,"text":"\t}"},
  {"line":477,"text":"\treturn symbol.Name"},
  {"line":478,"text":"}"},
  {"line":480,"text":"func replaceFirstIdentifierOfEntityName(factory *ast.NodeFactory, name *ast.EntityName, newIdentifier *ast.IdentifierNode) *ast.EntityName {"},
  {"line":481,"text":"\tif name.Kind == ast.KindIdentifier {"},
  {"line":482,"text":"\t\treturn newIdentifier"},
  {"line":483,"text":"\t}"},
  {"line":484,"text":"\treturn factory.NewQualifiedName("},
  {"line":485,"text":"\t\treplaceFirstIdentifierOfEntityName(factory, name.AsQualifiedName().Left, newIdentifier),"},
  {"line":486,"text":"\t\tname.AsQualifiedName().Right,"},
  {"line":487,"text":"\t)"},
  {"line":488,"text":"}"},
  {"line":490,"text":"func (adder *importAdder) getImportFixForSymbol(view *View, file *ast.SourceFile, exports []*Export, isValidTypeOnlyUseSite bool) *Fix {"},
  {"line":491,"text":"\tfixes := core.FlatMap(exports, func(export *Export) []*Fix {"},
  {"line":492,"text":"\t\treturn view.GetFixes(adder.ctx, export, false /*forJSX*/, isValidTypeOnlyUseSite, nil /*usagePosition*/)"},
  {"line":493,"text":"\t})"},
  {"line":494,"text":"\tslices.SortFunc(fixes, func(a, b *Fix) int {"},
  {"line":495,"text":"\t\treturn view.CompareFixesForRanking(a, b)"},
  {"line":496,"text":"\t})"},
  {"line":497,"text":"\tif len(fixes) > 0 {"},
  {"line":498,"text":"\t\treturn fixes[0]"},
  {"line":499,"text":"\t}"},
  {"line":500,"text":"\treturn nil"},
  {"line":501,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsAutoimportImportAdderSourceLines.find((entry) => entry.line === line)?.text;
}
