// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/github.com/golangci/plugin-module-register/register.ts","contentHash":"11bdccdf334ed966bbcc6324d3ede09f480eb2cea639953a02a6cbebe79679b8"}

export const LinterPlugin: unknown = undefined as never;

export const LoadModeTypesInfo: unknown = undefined as never;

export function Plugin(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED github.com/golangci/plugin-module-register/register.Plugin");
}
