// Code generated by tools/generateApiEncoder.ts. DO NOT EDIT.
// Source: schema/tsgo/ast.json
// Mirrors TS-Go internal/api/encoder/decoder_generated.go.

import { Kind, type Node as AstNode } from "../../ast/index.js";
import type { ASTDecoder } from "./decoder.js";
import { NodeDataChildMask, NodeDataStringIndexMask, NodeDataTypeExtendedData, NodeDataTypeMask, NodeDataTypeString } from "./encoder.js";

export type DecodeExtendedDataFunc = (
  decoder: ASTDecoder, data: number, childIndices: readonly number[], commonData: number,
) => AstNode | undefined;

export type DecodeCommonDataFunc = (commonData: number) => unknown;

export const GeneratedChildPropertiesByKind: ReadonlyMap<Kind, readonly string[]> = new Map([
  [Kind.Unknown, []],
  [Kind.EndOfFile, []],
  [Kind.SingleLineCommentTrivia, []],
  [Kind.MultiLineCommentTrivia, []],
  [Kind.NewLineTrivia, []],
  [Kind.WhitespaceTrivia, []],
  [Kind.ConflictMarkerTrivia, []],
  [Kind.NonTextFileMarkerTrivia, []],
  [Kind.NumericLiteral, []],
  [Kind.BigIntLiteral, []],
  [Kind.StringLiteral, []],
  [Kind.JsxText, []],
  [Kind.JsxTextAllWhiteSpaces, []],
  [Kind.RegularExpressionLiteral, []],
  [Kind.NoSubstitutionTemplateLiteral, []],
  [Kind.TemplateHead, []],
  [Kind.TemplateMiddle, []],
  [Kind.TemplateTail, []],
  [Kind.OpenBraceToken, []],
  [Kind.CloseBraceToken, []],
  [Kind.OpenParenToken, []],
  [Kind.CloseParenToken, []],
  [Kind.OpenBracketToken, []],
  [Kind.CloseBracketToken, []],
  [Kind.DotToken, []],
  [Kind.DotDotDotToken, []],
  [Kind.SemicolonToken, []],
  [Kind.CommaToken, []],
  [Kind.QuestionDotToken, []],
  [Kind.LessThanToken, []],
  [Kind.LessThanSlashToken, []],
  [Kind.GreaterThanToken, []],
  [Kind.LessThanEqualsToken, []],
  [Kind.GreaterThanEqualsToken, []],
  [Kind.EqualsEqualsToken, []],
  [Kind.ExclamationEqualsToken, []],
  [Kind.EqualsEqualsEqualsToken, []],
  [Kind.ExclamationEqualsEqualsToken, []],
  [Kind.EqualsGreaterThanToken, []],
  [Kind.PlusToken, []],
  [Kind.MinusToken, []],
  [Kind.AsteriskToken, []],
  [Kind.AsteriskAsteriskToken, []],
  [Kind.SlashToken, []],
  [Kind.PercentToken, []],
  [Kind.PlusPlusToken, []],
  [Kind.MinusMinusToken, []],
  [Kind.LessThanLessThanToken, []],
  [Kind.GreaterThanGreaterThanToken, []],
  [Kind.GreaterThanGreaterThanGreaterThanToken, []],
  [Kind.AmpersandToken, []],
  [Kind.BarToken, []],
  [Kind.CaretToken, []],
  [Kind.ExclamationToken, []],
  [Kind.TildeToken, []],
  [Kind.AmpersandAmpersandToken, []],
  [Kind.BarBarToken, []],
  [Kind.QuestionToken, []],
  [Kind.ColonToken, []],
  [Kind.AtToken, []],
  [Kind.QuestionQuestionToken, []],
  [Kind.BacktickToken, []],
  [Kind.HashToken, []],
  [Kind.EqualsToken, []],
  [Kind.PlusEqualsToken, []],
  [Kind.MinusEqualsToken, []],
  [Kind.AsteriskEqualsToken, []],
  [Kind.AsteriskAsteriskEqualsToken, []],
  [Kind.SlashEqualsToken, []],
  [Kind.PercentEqualsToken, []],
  [Kind.LessThanLessThanEqualsToken, []],
  [Kind.GreaterThanGreaterThanEqualsToken, []],
  [Kind.GreaterThanGreaterThanGreaterThanEqualsToken, []],
  [Kind.AmpersandEqualsToken, []],
  [Kind.BarEqualsToken, []],
  [Kind.BarBarEqualsToken, []],
  [Kind.AmpersandAmpersandEqualsToken, []],
  [Kind.QuestionQuestionEqualsToken, []],
  [Kind.CaretEqualsToken, []],
  [Kind.Identifier, []],
  [Kind.PrivateIdentifier, []],
  [Kind.JSDocCommentTextToken, []],
  [Kind.BreakKeyword, []],
  [Kind.CaseKeyword, []],
  [Kind.CatchKeyword, []],
  [Kind.ClassKeyword, []],
  [Kind.ConstKeyword, []],
  [Kind.ContinueKeyword, []],
  [Kind.DebuggerKeyword, []],
  [Kind.DefaultKeyword, []],
  [Kind.DeleteKeyword, []],
  [Kind.DoKeyword, []],
  [Kind.ElseKeyword, []],
  [Kind.EnumKeyword, []],
  [Kind.ExportKeyword, []],
  [Kind.ExtendsKeyword, []],
  [Kind.FalseKeyword, []],
  [Kind.FinallyKeyword, []],
  [Kind.ForKeyword, []],
  [Kind.FunctionKeyword, []],
  [Kind.IfKeyword, []],
  [Kind.ImportKeyword, []],
  [Kind.InKeyword, []],
  [Kind.InstanceOfKeyword, []],
  [Kind.NewKeyword, []],
  [Kind.NullKeyword, []],
  [Kind.ReturnKeyword, []],
  [Kind.SuperKeyword, []],
  [Kind.SwitchKeyword, []],
  [Kind.ThisKeyword, []],
  [Kind.ThrowKeyword, []],
  [Kind.TrueKeyword, []],
  [Kind.TryKeyword, []],
  [Kind.TypeOfKeyword, []],
  [Kind.VarKeyword, []],
  [Kind.VoidKeyword, []],
  [Kind.WhileKeyword, []],
  [Kind.WithKeyword, []],
  [Kind.ImplementsKeyword, []],
  [Kind.InterfaceKeyword, []],
  [Kind.LetKeyword, []],
  [Kind.PackageKeyword, []],
  [Kind.PrivateKeyword, []],
  [Kind.ProtectedKeyword, []],
  [Kind.PublicKeyword, []],
  [Kind.StaticKeyword, []],
  [Kind.YieldKeyword, []],
  [Kind.AbstractKeyword, []],
  [Kind.AccessorKeyword, []],
  [Kind.AsKeyword, []],
  [Kind.AssertsKeyword, []],
  [Kind.AssertKeyword, []],
  [Kind.AnyKeyword, []],
  [Kind.AsyncKeyword, []],
  [Kind.AwaitKeyword, []],
  [Kind.BooleanKeyword, []],
  [Kind.ConstructorKeyword, []],
  [Kind.DeclareKeyword, []],
  [Kind.GetKeyword, []],
  [Kind.ImmediateKeyword, []],
  [Kind.InferKeyword, []],
  [Kind.IntrinsicKeyword, []],
  [Kind.IsKeyword, []],
  [Kind.KeyOfKeyword, []],
  [Kind.ModuleKeyword, []],
  [Kind.NamespaceKeyword, []],
  [Kind.NeverKeyword, []],
  [Kind.OutKeyword, []],
  [Kind.ReadonlyKeyword, []],
  [Kind.RequireKeyword, []],
  [Kind.NumberKeyword, []],
  [Kind.ObjectKeyword, []],
  [Kind.SatisfiesKeyword, []],
  [Kind.SetKeyword, []],
  [Kind.StringKeyword, []],
  [Kind.SymbolKeyword, []],
  [Kind.TypeKeyword, []],
  [Kind.UndefinedKeyword, []],
  [Kind.UniqueKeyword, []],
  [Kind.UnknownKeyword, []],
  [Kind.UsingKeyword, []],
  [Kind.FromKeyword, []],
  [Kind.GlobalKeyword, []],
  [Kind.BigIntKeyword, []],
  [Kind.OverrideKeyword, []],
  [Kind.OfKeyword, []],
  [Kind.DeferKeyword, []],
  [Kind.QualifiedName, [
  "left",
  "right"
]],
  [Kind.ComputedPropertyName, [
  "expression"
]],
  [Kind.Decorator, [
  "expression"
]],
  [Kind.EmptyStatement, []],
  [Kind.IfStatement, [
  "expression",
  "thenStatement",
  "elseStatement"
]],
  [Kind.DoStatement, [
  "statement",
  "expression"
]],
  [Kind.WhileStatement, [
  "expression",
  "statement"
]],
  [Kind.ForStatement, [
  "initializer",
  "condition",
  "incrementor",
  "statement"
]],
  [Kind.ForInStatement, [
  "initializer",
  "expression",
  "statement"
]],
  [Kind.ForOfStatement, [
  "initializer",
  "expression",
  "statement"
]],
  [Kind.BreakStatement, [
  "label"
]],
  [Kind.ContinueStatement, [
  "label"
]],
  [Kind.ReturnStatement, [
  "expression"
]],
  [Kind.WithStatement, [
  "expression",
  "statement"
]],
  [Kind.SwitchStatement, [
  "expression",
  "caseBlock"
]],
  [Kind.CaseBlock, [
  "clauses"
]],
  [Kind.CaseClause, [
  "expression",
  "statements"
]],
  [Kind.DefaultClause, [
  "expression",
  "statements"
]],
  [Kind.ThrowStatement, [
  "expression"
]],
  [Kind.TryStatement, [
  "tryBlock",
  "catchClause",
  "finallyBlock"
]],
  [Kind.CatchClause, [
  "variableDeclaration",
  "block"
]],
  [Kind.DebuggerStatement, []],
  [Kind.LabeledStatement, [
  "label",
  "statement"
]],
  [Kind.ExpressionStatement, [
  "expression"
]],
  [Kind.Block, [
  "statements"
]],
  [Kind.VariableStatement, [
  "modifiers",
  "declarationList"
]],
  [Kind.VariableDeclaration, [
  "name",
  "type",
  "initializer"
]],
  [Kind.VariableDeclarationList, [
  "declarations"
]],
  [Kind.ObjectBindingPattern, [
  "elements"
]],
  [Kind.ArrayBindingPattern, [
  "elements"
]],
  [Kind.Parameter, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.BindingElement, [
  "propertyName",
  "name",
  "initializer"
]],
  [Kind.MissingDeclaration, [
  "modifiers"
]],
  [Kind.FunctionDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.ClassDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "heritageClauses",
  "members"
]],
  [Kind.ClassExpression, [
  "modifiers",
  "name",
  "typeParameters",
  "heritageClauses",
  "members"
]],
  [Kind.HeritageClause, [
  "types"
]],
  [Kind.InterfaceDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "heritageClauses",
  "members"
]],
  [Kind.TypeAliasDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "type"
]],
  [Kind.JSTypeAliasDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "type"
]],
  [Kind.EnumMember, [
  "name",
  "initializer"
]],
  [Kind.EnumDeclaration, [
  "modifiers",
  "name",
  "members"
]],
  [Kind.ModuleBlock, [
  "statements"
]],
  [Kind.NotEmittedStatement, []],
  [Kind.NotEmittedTypeElement, []],
  [Kind.ImportDeclaration, [
  "modifiers",
  "importClause",
  "moduleSpecifier",
  "attributes"
]],
  [Kind.JSImportDeclaration, [
  "modifiers",
  "importClause",
  "moduleSpecifier",
  "attributes"
]],
  [Kind.ExternalModuleReference, [
  "expression"
]],
  [Kind.NamespaceImport, [
  "name"
]],
  [Kind.NamedImports, [
  "elements"
]],
  [Kind.ExportAssignment, [
  "modifiers",
  "type",
  "expression"
]],
  [Kind.NamespaceExportDeclaration, [
  "modifiers",
  "name"
]],
  [Kind.NamespaceExport, [
  "name"
]],
  [Kind.NamedExports, [
  "elements"
]],
  [Kind.ExportSpecifier, [
  "propertyName",
  "name"
]],
  [Kind.CallSignature, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.ConstructSignature, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.Constructor, [
  "modifiers",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.GetAccessor, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.SetAccessor, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.IndexSignature, [
  "modifiers",
  "parameters",
  "type"
]],
  [Kind.MethodSignature, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.MethodDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.PropertySignature, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.PropertyDeclaration, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.SemicolonClassElement, []],
  [Kind.ClassStaticBlockDeclaration, [
  "modifiers",
  "body"
]],
  [Kind.OmittedExpression, []],
  [Kind.BinaryExpression, [
  "modifiers",
  "left",
  "type",
  "right"
]],
  [Kind.PrefixUnaryExpression, [
  "operand"
]],
  [Kind.PostfixUnaryExpression, [
  "operand"
]],
  [Kind.YieldExpression, [
  "expression"
]],
  [Kind.ArrowFunction, [
  "modifiers",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.FunctionExpression, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.AsExpression, [
  "expression",
  "type"
]],
  [Kind.SatisfiesExpression, [
  "expression",
  "type"
]],
  [Kind.ConditionalExpression, [
  "condition",
  "whenTrue",
  "whenFalse"
]],
  [Kind.PropertyAccessExpression, [
  "expression",
  "name"
]],
  [Kind.ElementAccessExpression, [
  "expression",
  "argumentExpression"
]],
  [Kind.CallExpression, [
  "expression",
  "typeArguments",
  "arguments"
]],
  [Kind.NewExpression, [
  "expression",
  "typeArguments",
  "arguments"
]],
  [Kind.MetaProperty, [
  "name"
]],
  [Kind.NonNullExpression, [
  "expression"
]],
  [Kind.SpreadElement, [
  "expression"
]],
  [Kind.TemplateExpression, [
  "head",
  "templateSpans"
]],
  [Kind.TemplateSpan, [
  "expression",
  "literal"
]],
  [Kind.TaggedTemplateExpression, [
  "tag",
  "typeArguments",
  "template"
]],
  [Kind.ParenthesizedExpression, [
  "expression"
]],
  [Kind.ArrayLiteralExpression, [
  "elements"
]],
  [Kind.ObjectLiteralExpression, [
  "properties"
]],
  [Kind.SpreadAssignment, [
  "expression"
]],
  [Kind.PropertyAssignment, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.ShorthandPropertyAssignment, [
  "modifiers",
  "name",
  "type",
  "objectAssignmentInitializer"
]],
  [Kind.DeleteExpression, [
  "expression"
]],
  [Kind.TypeOfExpression, [
  "expression"
]],
  [Kind.VoidExpression, [
  "expression"
]],
  [Kind.AwaitExpression, [
  "expression"
]],
  [Kind.TypeAssertionExpression, [
  "type",
  "expression"
]],
  [Kind.UnionType, [
  "types"
]],
  [Kind.IntersectionType, [
  "types"
]],
  [Kind.ConditionalType, [
  "checkType",
  "extendsType",
  "trueType",
  "falseType"
]],
  [Kind.TypeOperator, [
  "type"
]],
  [Kind.InferType, [
  "typeParameter"
]],
  [Kind.ArrayType, [
  "elementType"
]],
  [Kind.IndexedAccessType, [
  "objectType",
  "indexType"
]],
  [Kind.TypeReference, [
  "typeName",
  "typeArguments"
]],
  [Kind.ExpressionWithTypeArguments, [
  "expression",
  "typeArguments"
]],
  [Kind.LiteralType, []],
  [Kind.ThisType, []],
  [Kind.TypePredicate, [
  "parameterName",
  "type"
]],
  [Kind.ImportAttribute, [
  "name",
  "value"
]],
  [Kind.ImportAttributes, [
  "attributes"
]],
  [Kind.TypeQuery, [
  "exprName",
  "typeArguments"
]],
  [Kind.MappedType, [
  "typeParameter",
  "nameType",
  "type",
  "members"
]],
  [Kind.TypeLiteral, [
  "members"
]],
  [Kind.TupleType, [
  "elements"
]],
  [Kind.NamedTupleMember, [
  "name",
  "type"
]],
  [Kind.OptionalType, [
  "type"
]],
  [Kind.RestType, [
  "type"
]],
  [Kind.ParenthesizedType, [
  "type"
]],
  [Kind.FunctionType, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.ConstructorType, [
  "modifiers",
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.TemplateLiteralType, [
  "head",
  "templateSpans"
]],
  [Kind.TemplateLiteralTypeSpan, [
  "type",
  "literal"
]],
  [Kind.SyntheticExpression, []],
  [Kind.PartiallyEmittedExpression, [
  "expression"
]],
  [Kind.JsxElement, [
  "openingElement",
  "children",
  "closingElement"
]],
  [Kind.JsxAttributes, [
  "properties"
]],
  [Kind.JsxNamespacedName, [
  "namespace",
  "name"
]],
  [Kind.JsxOpeningElement, [
  "tagName",
  "typeArguments",
  "attributes"
]],
  [Kind.JsxSelfClosingElement, [
  "tagName",
  "typeArguments",
  "attributes"
]],
  [Kind.JsxFragment, [
  "openingFragment",
  "children",
  "closingFragment"
]],
  [Kind.JsxOpeningFragment, []],
  [Kind.JsxClosingFragment, []],
  [Kind.JsxAttribute, [
  "name",
  "initializer"
]],
  [Kind.JsxSpreadAttribute, [
  "expression"
]],
  [Kind.JsxClosingElement, [
  "tagName"
]],
  [Kind.JsxExpression, [
  "expression"
]],
  [Kind.SyntaxList, []],
  [Kind.JSDoc, [
  "comment",
  "tags"
]],
  [Kind.JSDocTypeExpression, [
  "type"
]],
  [Kind.JSDocNonNullableType, [
  "type"
]],
  [Kind.JSDocNullableType, [
  "type"
]],
  [Kind.JSDocAllType, []],
  [Kind.JSDocVariadicType, [
  "type"
]],
  [Kind.JSDocOptionalType, [
  "type"
]],
  [Kind.JSDocTypeTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocUnknownTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocTemplateTag, [
  "tagName",
  "typeParameters",
  "comment"
]],
  [Kind.JSDocReturnTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocPublicTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocPrivateTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocProtectedTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocReadonlyTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocOverrideTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocDeprecatedTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocSeeTag, [
  "tagName",
  "nameExpression",
  "comment"
]],
  [Kind.JSDocImplementsTag, [
  "tagName",
  "className",
  "comment"
]],
  [Kind.JSDocAugmentsTag, [
  "tagName",
  "className",
  "comment"
]],
  [Kind.JSDocSatisfiesTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocThrowsTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocThisTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocImportTag, [
  "tagName",
  "importClause",
  "moduleSpecifier",
  "attributes",
  "comment"
]],
  [Kind.JSDocCallbackTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocOverloadTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocTypedefTag, [
  "tagName",
  "name",
  "comment"
]],
  [Kind.JSDocSignature, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.JSDocNameReference, [
  "name"
]],
  [Kind.SourceFile, [
  "statements"
]],
  [Kind.ModuleDeclaration, [
  "modifiers",
  "name",
  "body"
]],
  [Kind.ImportEqualsDeclaration, [
  "modifiers",
  "name",
  "moduleReference"
]],
  [Kind.ExportDeclaration, [
  "modifiers",
  "exportClause",
  "moduleSpecifier",
  "attributes"
]],
  [Kind.ImportType, [
  "argument",
  "attributes",
  "qualifier",
  "typeArguments"
]],
  [Kind.ImportClause, [
  "name",
  "namedBindings"
]],
  [Kind.ImportSpecifier, [
  "propertyName",
  "name"
]],
  [Kind.JSDocText, []],
  [Kind.JSDocLink, [
  "name"
]],
  [Kind.JSDocLinkPlain, [
  "name"
]],
  [Kind.JSDocLinkCode, [
  "name"
]],
  [Kind.TypeParameter, [
  "modifiers",
  "name",
  "constraint",
  "expression",
  "defaultType"
]],
  [Kind.SyntheticReferenceExpression, [
  "expression",
  "thisArg"
]],
  [Kind.JSDocTypeLiteral, [
  "jSDocPropertyTags"
]],
  [Kind.JSDocParameterTag, [
  "tagName",
  "name",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocPropertyTag, [
  "tagName",
  "name",
  "typeExpression",
  "comment"
]],
]);

export function createNode(decoder: ASTDecoder, kind: number, data: number, childIndices: readonly number[]): AstNode {
  const dataType = data & NodeDataTypeMask;
  const commonData = (data >>> 24) & 0x3f;
  switch (dataType) {
    case NodeDataTypeString:
      return createStringNode(decoder, kind, data & NodeDataStringIndexMask, commonData);
    case NodeDataTypeExtendedData:
      return createExtendedNode(decoder, kind, data, childIndices, commonData);
    default:
      return createChildrenNode(decoder, kind, data, childIndices, commonData);
  }
}

export function createStringNode(decoder: ASTDecoder, kind: number, data: number, commonData: number): AstNode {
  return decoder.createStringNode(kind, data, commonData);
}

export function createExtendedNode(
  decoder: ASTDecoder, kind: number, data: number, childIndices: readonly number[], commonData: number,
): AstNode {
  const decoded = decodeExtendedData(decoder, kind, data, childIndices, commonData);
  return decoded ?? decoder.createExtendedNode(kind, data, childIndices, commonData);
}

export function createChildrenNode(
  decoder: ASTDecoder, kind: number, data: number, childIndices: readonly number[], commonData: number,
): AstNode {
  const mask = data & NodeDataChildMask;
  const expectedProperties = GeneratedChildPropertiesByKind.get(kind as Kind) ?? [];
  return decoder.createChildrenNodeWithProperties(kind, mask, childIndices, commonData, expectedProperties);
}

export function decodeExtendedData(
  decoder: ASTDecoder, kind: number, data: number,
  childIndices: readonly number[], commonData: number,
): AstNode | undefined {
  const fn = extendedDataDecoders[kind];
  if (fn === undefined) return undefined;
  return fn(decoder, data, childIndices, commonData);
}

export function decodeNodeCommonData(kind: number, commonData: number): unknown {
  const fn = commonDataDecoders[kind];
  if (fn === undefined) return undefined;
  return fn(commonData);
}

const extendedDataDecoders: Record<number, DecodeExtendedDataFunc | undefined> = {};
const commonDataDecoders: Record<number, DecodeCommonDataFunc | undefined> = {};

export function registerExtendedDataDecoder(kind: number, fn: DecodeExtendedDataFunc): void {
  extendedDataDecoders[kind] = fn;
}

export function registerCommonDataDecoder(kind: number, fn: DecodeCommonDataFunc): void {
  commonDataDecoders[kind] = fn;
}
