// Code generated by tools/generateApiEncoder.ts. DO NOT EDIT.
// Source: schema/tsgo/ast.json
// Mirrors TS-Go internal/api/encoder/encoder_generated.go.

import { Kind, type Node as AstNode, type PositionMap } from "../../ast/index.js";
import type { StringTable } from "./stringTable.js";

export const NodeDataTypeChildren = 0x00000000;
export const NodeDataTypeString = 0x40000000;
export const NodeDataTypeExtendedData = 0x80000000;
export const NodeDataTypeMask = 0xc0000000;
export const NodeDataChildMask = 0x000000ff;
export const NodeDataStringIndexMask = 0x00ffffff;

export type RecordExtendedDataFunc = (
  node: AstNode, strs: StringTable, positionMap: PositionMap,
  extendedData: number[], structuredData: number[],
) => void;

export type GetCommonDataFunc = (node: AstNode) => number;

const stringDataKinds: ReadonlySet<Kind> = new Set([
  Kind.Identifier,
  Kind.PrivateIdentifier,
  Kind.JsxText,
  Kind.JSDocText,
  Kind.JSDocLink,
  Kind.JSDocLinkPlain,
  Kind.JSDocLinkCode,
]);

const extendedDataKinds: ReadonlySet<Kind> = new Set([
  Kind.StringLiteral,
  Kind.NumericLiteral,
  Kind.BigIntLiteral,
  Kind.RegularExpressionLiteral,
  Kind.NoSubstitutionTemplateLiteral,
  Kind.TemplateHead,
  Kind.TemplateMiddle,
  Kind.TemplateTail,
  Kind.SourceFile,
]);

export const GeneratedChildPropertiesByKind: ReadonlyMap<Kind, readonly string[]> = new Map([
  [Kind.Unknown, []],
  [Kind.EndOfFile, []],
  [Kind.SingleLineCommentTrivia, []],
  [Kind.MultiLineCommentTrivia, []],
  [Kind.NewLineTrivia, []],
  [Kind.WhitespaceTrivia, []],
  [Kind.ConflictMarkerTrivia, []],
  [Kind.NonTextFileMarkerTrivia, []],
  [Kind.NumericLiteral, []],
  [Kind.BigIntLiteral, []],
  [Kind.StringLiteral, []],
  [Kind.JsxText, []],
  [Kind.JsxTextAllWhiteSpaces, []],
  [Kind.RegularExpressionLiteral, []],
  [Kind.NoSubstitutionTemplateLiteral, []],
  [Kind.TemplateHead, []],
  [Kind.TemplateMiddle, []],
  [Kind.TemplateTail, []],
  [Kind.OpenBraceToken, []],
  [Kind.CloseBraceToken, []],
  [Kind.OpenParenToken, []],
  [Kind.CloseParenToken, []],
  [Kind.OpenBracketToken, []],
  [Kind.CloseBracketToken, []],
  [Kind.DotToken, []],
  [Kind.DotDotDotToken, []],
  [Kind.SemicolonToken, []],
  [Kind.CommaToken, []],
  [Kind.QuestionDotToken, []],
  [Kind.LessThanToken, []],
  [Kind.LessThanSlashToken, []],
  [Kind.GreaterThanToken, []],
  [Kind.LessThanEqualsToken, []],
  [Kind.GreaterThanEqualsToken, []],
  [Kind.EqualsEqualsToken, []],
  [Kind.ExclamationEqualsToken, []],
  [Kind.EqualsEqualsEqualsToken, []],
  [Kind.ExclamationEqualsEqualsToken, []],
  [Kind.EqualsGreaterThanToken, []],
  [Kind.PlusToken, []],
  [Kind.MinusToken, []],
  [Kind.AsteriskToken, []],
  [Kind.AsteriskAsteriskToken, []],
  [Kind.SlashToken, []],
  [Kind.PercentToken, []],
  [Kind.PlusPlusToken, []],
  [Kind.MinusMinusToken, []],
  [Kind.LessThanLessThanToken, []],
  [Kind.GreaterThanGreaterThanToken, []],
  [Kind.GreaterThanGreaterThanGreaterThanToken, []],
  [Kind.AmpersandToken, []],
  [Kind.BarToken, []],
  [Kind.CaretToken, []],
  [Kind.ExclamationToken, []],
  [Kind.TildeToken, []],
  [Kind.AmpersandAmpersandToken, []],
  [Kind.BarBarToken, []],
  [Kind.QuestionToken, []],
  [Kind.ColonToken, []],
  [Kind.AtToken, []],
  [Kind.QuestionQuestionToken, []],
  [Kind.BacktickToken, []],
  [Kind.HashToken, []],
  [Kind.EqualsToken, []],
  [Kind.PlusEqualsToken, []],
  [Kind.MinusEqualsToken, []],
  [Kind.AsteriskEqualsToken, []],
  [Kind.AsteriskAsteriskEqualsToken, []],
  [Kind.SlashEqualsToken, []],
  [Kind.PercentEqualsToken, []],
  [Kind.LessThanLessThanEqualsToken, []],
  [Kind.GreaterThanGreaterThanEqualsToken, []],
  [Kind.GreaterThanGreaterThanGreaterThanEqualsToken, []],
  [Kind.AmpersandEqualsToken, []],
  [Kind.BarEqualsToken, []],
  [Kind.BarBarEqualsToken, []],
  [Kind.AmpersandAmpersandEqualsToken, []],
  [Kind.QuestionQuestionEqualsToken, []],
  [Kind.CaretEqualsToken, []],
  [Kind.Identifier, []],
  [Kind.PrivateIdentifier, []],
  [Kind.JSDocCommentTextToken, []],
  [Kind.BreakKeyword, []],
  [Kind.CaseKeyword, []],
  [Kind.CatchKeyword, []],
  [Kind.ClassKeyword, []],
  [Kind.ConstKeyword, []],
  [Kind.ContinueKeyword, []],
  [Kind.DebuggerKeyword, []],
  [Kind.DefaultKeyword, []],
  [Kind.DeleteKeyword, []],
  [Kind.DoKeyword, []],
  [Kind.ElseKeyword, []],
  [Kind.EnumKeyword, []],
  [Kind.ExportKeyword, []],
  [Kind.ExtendsKeyword, []],
  [Kind.FalseKeyword, []],
  [Kind.FinallyKeyword, []],
  [Kind.ForKeyword, []],
  [Kind.FunctionKeyword, []],
  [Kind.IfKeyword, []],
  [Kind.ImportKeyword, []],
  [Kind.InKeyword, []],
  [Kind.InstanceOfKeyword, []],
  [Kind.NewKeyword, []],
  [Kind.NullKeyword, []],
  [Kind.ReturnKeyword, []],
  [Kind.SuperKeyword, []],
  [Kind.SwitchKeyword, []],
  [Kind.ThisKeyword, []],
  [Kind.ThrowKeyword, []],
  [Kind.TrueKeyword, []],
  [Kind.TryKeyword, []],
  [Kind.TypeOfKeyword, []],
  [Kind.VarKeyword, []],
  [Kind.VoidKeyword, []],
  [Kind.WhileKeyword, []],
  [Kind.WithKeyword, []],
  [Kind.ImplementsKeyword, []],
  [Kind.InterfaceKeyword, []],
  [Kind.LetKeyword, []],
  [Kind.PackageKeyword, []],
  [Kind.PrivateKeyword, []],
  [Kind.ProtectedKeyword, []],
  [Kind.PublicKeyword, []],
  [Kind.StaticKeyword, []],
  [Kind.YieldKeyword, []],
  [Kind.AbstractKeyword, []],
  [Kind.AccessorKeyword, []],
  [Kind.AsKeyword, []],
  [Kind.AssertsKeyword, []],
  [Kind.AssertKeyword, []],
  [Kind.AnyKeyword, []],
  [Kind.AsyncKeyword, []],
  [Kind.AwaitKeyword, []],
  [Kind.BooleanKeyword, []],
  [Kind.ConstructorKeyword, []],
  [Kind.DeclareKeyword, []],
  [Kind.GetKeyword, []],
  [Kind.ImmediateKeyword, []],
  [Kind.InferKeyword, []],
  [Kind.IntrinsicKeyword, []],
  [Kind.IsKeyword, []],
  [Kind.KeyOfKeyword, []],
  [Kind.ModuleKeyword, []],
  [Kind.NamespaceKeyword, []],
  [Kind.NeverKeyword, []],
  [Kind.OutKeyword, []],
  [Kind.ReadonlyKeyword, []],
  [Kind.RequireKeyword, []],
  [Kind.NumberKeyword, []],
  [Kind.ObjectKeyword, []],
  [Kind.SatisfiesKeyword, []],
  [Kind.SetKeyword, []],
  [Kind.StringKeyword, []],
  [Kind.SymbolKeyword, []],
  [Kind.TypeKeyword, []],
  [Kind.UndefinedKeyword, []],
  [Kind.UniqueKeyword, []],
  [Kind.UnknownKeyword, []],
  [Kind.UsingKeyword, []],
  [Kind.FromKeyword, []],
  [Kind.GlobalKeyword, []],
  [Kind.BigIntKeyword, []],
  [Kind.OverrideKeyword, []],
  [Kind.OfKeyword, []],
  [Kind.DeferKeyword, []],
  [Kind.QualifiedName, [
  "left",
  "right"
]],
  [Kind.ComputedPropertyName, [
  "expression"
]],
  [Kind.Decorator, [
  "expression"
]],
  [Kind.EmptyStatement, []],
  [Kind.IfStatement, [
  "expression",
  "thenStatement",
  "elseStatement"
]],
  [Kind.DoStatement, [
  "statement",
  "expression"
]],
  [Kind.WhileStatement, [
  "expression",
  "statement"
]],
  [Kind.ForStatement, [
  "initializer",
  "condition",
  "incrementor",
  "statement"
]],
  [Kind.ForInStatement, [
  "initializer",
  "expression",
  "statement"
]],
  [Kind.ForOfStatement, [
  "initializer",
  "expression",
  "statement"
]],
  [Kind.BreakStatement, [
  "label"
]],
  [Kind.ContinueStatement, [
  "label"
]],
  [Kind.ReturnStatement, [
  "expression"
]],
  [Kind.WithStatement, [
  "expression",
  "statement"
]],
  [Kind.SwitchStatement, [
  "expression",
  "caseBlock"
]],
  [Kind.CaseBlock, [
  "clauses"
]],
  [Kind.CaseClause, [
  "expression",
  "statements"
]],
  [Kind.DefaultClause, [
  "expression",
  "statements"
]],
  [Kind.ThrowStatement, [
  "expression"
]],
  [Kind.TryStatement, [
  "tryBlock",
  "catchClause",
  "finallyBlock"
]],
  [Kind.CatchClause, [
  "variableDeclaration",
  "block"
]],
  [Kind.DebuggerStatement, []],
  [Kind.LabeledStatement, [
  "label",
  "statement"
]],
  [Kind.ExpressionStatement, [
  "expression"
]],
  [Kind.Block, [
  "statements"
]],
  [Kind.VariableStatement, [
  "modifiers",
  "declarationList"
]],
  [Kind.VariableDeclaration, [
  "name",
  "type",
  "initializer"
]],
  [Kind.VariableDeclarationList, [
  "declarations"
]],
  [Kind.ObjectBindingPattern, [
  "elements"
]],
  [Kind.ArrayBindingPattern, [
  "elements"
]],
  [Kind.Parameter, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.BindingElement, [
  "propertyName",
  "name",
  "initializer"
]],
  [Kind.MissingDeclaration, [
  "modifiers"
]],
  [Kind.FunctionDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.ClassDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "heritageClauses",
  "members"
]],
  [Kind.ClassExpression, [
  "modifiers",
  "name",
  "typeParameters",
  "heritageClauses",
  "members"
]],
  [Kind.HeritageClause, [
  "types"
]],
  [Kind.InterfaceDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "heritageClauses",
  "members"
]],
  [Kind.TypeAliasDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "type"
]],
  [Kind.JSTypeAliasDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "type"
]],
  [Kind.EnumMember, [
  "name",
  "initializer"
]],
  [Kind.EnumDeclaration, [
  "modifiers",
  "name",
  "members"
]],
  [Kind.ModuleBlock, [
  "statements"
]],
  [Kind.NotEmittedStatement, []],
  [Kind.NotEmittedTypeElement, []],
  [Kind.ImportDeclaration, [
  "modifiers",
  "importClause",
  "moduleSpecifier",
  "attributes"
]],
  [Kind.JSImportDeclaration, [
  "modifiers",
  "importClause",
  "moduleSpecifier",
  "attributes"
]],
  [Kind.ExternalModuleReference, [
  "expression"
]],
  [Kind.NamespaceImport, [
  "name"
]],
  [Kind.NamedImports, [
  "elements"
]],
  [Kind.ExportAssignment, [
  "modifiers",
  "type",
  "expression"
]],
  [Kind.NamespaceExportDeclaration, [
  "modifiers",
  "name"
]],
  [Kind.NamespaceExport, [
  "name"
]],
  [Kind.NamedExports, [
  "elements"
]],
  [Kind.ExportSpecifier, [
  "propertyName",
  "name"
]],
  [Kind.CallSignature, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.ConstructSignature, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.Constructor, [
  "modifiers",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.GetAccessor, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.SetAccessor, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.IndexSignature, [
  "modifiers",
  "parameters",
  "type"
]],
  [Kind.MethodSignature, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.MethodDeclaration, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.PropertySignature, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.PropertyDeclaration, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.SemicolonClassElement, []],
  [Kind.ClassStaticBlockDeclaration, [
  "modifiers",
  "body"
]],
  [Kind.OmittedExpression, []],
  [Kind.BinaryExpression, [
  "modifiers",
  "left",
  "type",
  "right"
]],
  [Kind.PrefixUnaryExpression, [
  "operand"
]],
  [Kind.PostfixUnaryExpression, [
  "operand"
]],
  [Kind.YieldExpression, [
  "expression"
]],
  [Kind.ArrowFunction, [
  "modifiers",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.FunctionExpression, [
  "modifiers",
  "name",
  "typeParameters",
  "parameters",
  "type",
  "body"
]],
  [Kind.AsExpression, [
  "expression",
  "type"
]],
  [Kind.SatisfiesExpression, [
  "expression",
  "type"
]],
  [Kind.ConditionalExpression, [
  "condition",
  "whenTrue",
  "whenFalse"
]],
  [Kind.PropertyAccessExpression, [
  "expression",
  "name"
]],
  [Kind.ElementAccessExpression, [
  "expression",
  "argumentExpression"
]],
  [Kind.CallExpression, [
  "expression",
  "typeArguments",
  "arguments"
]],
  [Kind.NewExpression, [
  "expression",
  "typeArguments",
  "arguments"
]],
  [Kind.MetaProperty, [
  "name"
]],
  [Kind.NonNullExpression, [
  "expression"
]],
  [Kind.SpreadElement, [
  "expression"
]],
  [Kind.TemplateExpression, [
  "head",
  "templateSpans"
]],
  [Kind.TemplateSpan, [
  "expression",
  "literal"
]],
  [Kind.TaggedTemplateExpression, [
  "tag",
  "typeArguments",
  "template"
]],
  [Kind.ParenthesizedExpression, [
  "expression"
]],
  [Kind.ArrayLiteralExpression, [
  "elements"
]],
  [Kind.ObjectLiteralExpression, [
  "properties"
]],
  [Kind.SpreadAssignment, [
  "expression"
]],
  [Kind.PropertyAssignment, [
  "modifiers",
  "name",
  "type",
  "initializer"
]],
  [Kind.ShorthandPropertyAssignment, [
  "modifiers",
  "name",
  "type",
  "objectAssignmentInitializer"
]],
  [Kind.DeleteExpression, [
  "expression"
]],
  [Kind.TypeOfExpression, [
  "expression"
]],
  [Kind.VoidExpression, [
  "expression"
]],
  [Kind.AwaitExpression, [
  "expression"
]],
  [Kind.TypeAssertionExpression, [
  "type",
  "expression"
]],
  [Kind.UnionType, [
  "types"
]],
  [Kind.IntersectionType, [
  "types"
]],
  [Kind.ConditionalType, [
  "checkType",
  "extendsType",
  "trueType",
  "falseType"
]],
  [Kind.TypeOperator, [
  "type"
]],
  [Kind.InferType, [
  "typeParameter"
]],
  [Kind.ArrayType, [
  "elementType"
]],
  [Kind.IndexedAccessType, [
  "objectType",
  "indexType"
]],
  [Kind.TypeReference, [
  "typeName",
  "typeArguments"
]],
  [Kind.ExpressionWithTypeArguments, [
  "expression",
  "typeArguments"
]],
  [Kind.LiteralType, []],
  [Kind.ThisType, []],
  [Kind.TypePredicate, [
  "parameterName",
  "type"
]],
  [Kind.ImportAttribute, [
  "name",
  "value"
]],
  [Kind.ImportAttributes, [
  "attributes"
]],
  [Kind.TypeQuery, [
  "exprName",
  "typeArguments"
]],
  [Kind.MappedType, [
  "typeParameter",
  "nameType",
  "type",
  "members"
]],
  [Kind.TypeLiteral, [
  "members"
]],
  [Kind.TupleType, [
  "elements"
]],
  [Kind.NamedTupleMember, [
  "name",
  "type"
]],
  [Kind.OptionalType, [
  "type"
]],
  [Kind.RestType, [
  "type"
]],
  [Kind.ParenthesizedType, [
  "type"
]],
  [Kind.FunctionType, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.ConstructorType, [
  "modifiers",
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.TemplateLiteralType, [
  "head",
  "templateSpans"
]],
  [Kind.TemplateLiteralTypeSpan, [
  "type",
  "literal"
]],
  [Kind.SyntheticExpression, []],
  [Kind.PartiallyEmittedExpression, [
  "expression"
]],
  [Kind.JsxElement, [
  "openingElement",
  "children",
  "closingElement"
]],
  [Kind.JsxAttributes, [
  "properties"
]],
  [Kind.JsxNamespacedName, [
  "namespace",
  "name"
]],
  [Kind.JsxOpeningElement, [
  "tagName",
  "typeArguments",
  "attributes"
]],
  [Kind.JsxSelfClosingElement, [
  "tagName",
  "typeArguments",
  "attributes"
]],
  [Kind.JsxFragment, [
  "openingFragment",
  "children",
  "closingFragment"
]],
  [Kind.JsxOpeningFragment, []],
  [Kind.JsxClosingFragment, []],
  [Kind.JsxAttribute, [
  "name",
  "initializer"
]],
  [Kind.JsxSpreadAttribute, [
  "expression"
]],
  [Kind.JsxClosingElement, [
  "tagName"
]],
  [Kind.JsxExpression, [
  "expression"
]],
  [Kind.SyntaxList, []],
  [Kind.JSDoc, [
  "comment",
  "tags"
]],
  [Kind.JSDocTypeExpression, [
  "type"
]],
  [Kind.JSDocNonNullableType, [
  "type"
]],
  [Kind.JSDocNullableType, [
  "type"
]],
  [Kind.JSDocAllType, []],
  [Kind.JSDocVariadicType, [
  "type"
]],
  [Kind.JSDocOptionalType, [
  "type"
]],
  [Kind.JSDocTypeTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocUnknownTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocTemplateTag, [
  "tagName",
  "typeParameters",
  "comment"
]],
  [Kind.JSDocReturnTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocPublicTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocPrivateTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocProtectedTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocReadonlyTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocOverrideTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocDeprecatedTag, [
  "tagName",
  "comment"
]],
  [Kind.JSDocSeeTag, [
  "tagName",
  "nameExpression",
  "comment"
]],
  [Kind.JSDocImplementsTag, [
  "tagName",
  "className",
  "comment"
]],
  [Kind.JSDocAugmentsTag, [
  "tagName",
  "className",
  "comment"
]],
  [Kind.JSDocSatisfiesTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocThrowsTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocThisTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocImportTag, [
  "tagName",
  "importClause",
  "moduleSpecifier",
  "attributes",
  "comment"
]],
  [Kind.JSDocCallbackTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocOverloadTag, [
  "tagName",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocTypedefTag, [
  "tagName",
  "name",
  "comment"
]],
  [Kind.JSDocSignature, [
  "typeParameters",
  "parameters",
  "type"
]],
  [Kind.JSDocNameReference, [
  "name"
]],
  [Kind.SourceFile, [
  "statements"
]],
  [Kind.ModuleDeclaration, [
  "modifiers",
  "name",
  "body"
]],
  [Kind.ImportEqualsDeclaration, [
  "modifiers",
  "name",
  "moduleReference"
]],
  [Kind.ExportDeclaration, [
  "modifiers",
  "exportClause",
  "moduleSpecifier",
  "attributes"
]],
  [Kind.ImportType, [
  "argument",
  "attributes",
  "qualifier",
  "typeArguments"
]],
  [Kind.ImportClause, [
  "name",
  "namedBindings"
]],
  [Kind.ImportSpecifier, [
  "propertyName",
  "name"
]],
  [Kind.JSDocText, []],
  [Kind.JSDocLink, [
  "name"
]],
  [Kind.JSDocLinkPlain, [
  "name"
]],
  [Kind.JSDocLinkCode, [
  "name"
]],
  [Kind.TypeParameter, [
  "modifiers",
  "name",
  "constraint",
  "expression",
  "defaultType"
]],
  [Kind.SyntheticReferenceExpression, [
  "expression",
  "thisArg"
]],
  [Kind.JSDocTypeLiteral, [
  "jSDocPropertyTags"
]],
  [Kind.JSDocParameterTag, [
  "tagName",
  "name",
  "typeExpression",
  "comment"
]],
  [Kind.JSDocPropertyTag, [
  "tagName",
  "name",
  "typeExpression",
  "comment"
]],
]);

export function getNodeDataType(node: AstNode): number {
  if (stringDataKinds.has(node.kind)) return NodeDataTypeString;
  if (extendedDataKinds.has(node.kind)) return NodeDataTypeExtendedData;
  return NodeDataTypeChildren;
}

export function getChildrenPropertyMask(node: AstNode): number {
  const properties = GeneratedChildPropertiesByKind.get(node.kind) ?? [];
  const record = node as unknown as Record<string, unknown>;
  let mask = 0;
  for (let index = 0; index < properties.length; index += 1) {
    const value = record[properties[index]!];
    if (value !== undefined && value !== null) mask |= 1 << index;
  }
  return mask;
}

export function getNodeCommonData(node: AstNode): number {
  const record = node as unknown as Record<string, unknown>;
  switch (node.kind) {
    case Kind.Block:
    case Kind.ArrayLiteralExpression:
    case Kind.ObjectLiteralExpression:
      return boolToByte(record["multiLine"] === true) << 24;
    case Kind.HeritageClause:
      return (record["token"] === Kind.ImplementsKeyword ? 1 : 0) << 24;
    case Kind.ExportAssignment:
      return boolToByte(record["isExportEquals"] === true) << 24;
    case Kind.ExportSpecifier:
    case Kind.ImportEqualsDeclaration:
    case Kind.ExportDeclaration:
    case Kind.ImportSpecifier:
      return boolToByte(record["isTypeOnly"] === true) << 24;
    case Kind.PrefixUnaryExpression:
      return unaryOperatorIndex(record["operator"]) << 24;
    case Kind.PostfixUnaryExpression:
      return (record["operator"] === Kind.MinusMinusToken ? 1 : 0) << 24;
    case Kind.MetaProperty:
      return (record["keywordToken"] === Kind.NewKeyword ? 1 : 0) << 24;
    case Kind.TypeOperator:
      return typeOperatorIndex(record["operator"]) << 24;
    case Kind.ImportAttributes:
      return (boolToByte(record["multiLine"] === true) << 24)
        | ((record["token"] === Kind.AssertKeyword ? 1 : 0) << 25);
    case Kind.SyntheticExpression:
      throw new Error("SyntheticExpression should never be encoded");
    case Kind.JsxText:
      return boolToByte(record["containsOnlyTriviaWhiteSpaces"] === true) << 24;
    case Kind.ModuleDeclaration:
      return (record["keyword"] === Kind.NamespaceKeyword ? 1 : 0) << 24;
    case Kind.ImportType:
      return boolToByte(record["isTypeOf"] === true) << 24;
    case Kind.ImportClause:
      return importPhaseModifierIndex(record["phaseModifier"]) << 24;
    case Kind.JSDocTypeLiteral:
      return boolToByte(record["isArrayType"] === true) << 24;
    case Kind.JSDocParameterTag:
    case Kind.JSDocPropertyTag:
      return (boolToByte(record["isBracketed"] === true) << 24)
        | (boolToByte(record["isNameFirst"] === true) << 25);
  }
  const fn = commonDataGetters[node.kind];
  return fn === undefined ? 0 : fn(node);
}

export function recordNodeStrings(node: AstNode, strs: StringTable): number {
  const record = node as unknown as { readonly text?: string; readonly textParts?: readonly string[] };
  switch (node.kind) {
    case Kind.Identifier:
    case Kind.PrivateIdentifier:
    case Kind.JsxText:
    case Kind.JSDocText:
    case Kind.JSDocLink:
    case Kind.JSDocLinkPlain:
    case Kind.JSDocLinkCode:
      return strs.add(record.text ?? record.textParts?.join("") ?? "", node.kind, node.pos, node.end);
    default:
      throw new Error(`Unexpected string-data node kind ${node.kind}`);
  }
}

export function recordExtendedData(
  node: AstNode, strs: StringTable, positionMap: PositionMap,
  extendedData: number[], structuredData: number[],
): number {
  const offset = extendedData.length * 4;
  const fn = extendedDataRecorders[node.kind];
  if (fn !== undefined) {
    fn(node, strs, positionMap, extendedData, structuredData);
    return offset;
  }
  recordGeneratedExtendedData(node, strs, extendedData);
  return offset;
}

function recordGeneratedExtendedData(node: AstNode, strs: StringTable, extendedData: number[]): void {
  const record = node as unknown as {
    readonly text?: string;
    readonly rawText?: string;
    readonly tokenFlags?: number;
    readonly templateFlags?: number;
  };
  switch (node.kind) {
    case Kind.StringLiteral:
    case Kind.NumericLiteral:
    case Kind.BigIntLiteral:
    case Kind.RegularExpressionLiteral:
      pushUint32s(extendedData, strs.add(record.text ?? "", node.kind, node.pos, node.end), record.tokenFlags ?? 0);
      return;
    case Kind.NoSubstitutionTemplateLiteral:
      pushUint32s(extendedData, strs.add(record.text ?? "", node.kind, node.pos, node.end), record.templateFlags ?? 0);
      return;
    case Kind.TemplateHead:
    case Kind.TemplateMiddle:
    case Kind.TemplateTail:
      pushUint32s(
        extendedData,
        strs.add(record.text ?? "", node.kind, node.pos, node.end),
        strs.add(record.rawText ?? "", node.kind, node.pos, node.end),
        record.templateFlags ?? 0,
      );
      return;
    default:
      throw new Error(`unknown extended-data node kind ${node.kind}`);
  }
}

function pushUint32s(values: number[], ...items: readonly number[]): void {
  for (const item of items) values.push(item >>> 0);
}

function boolToByte(value: boolean): number {
  return value ? 1 : 0;
}

function unaryOperatorIndex(value: unknown): number {
  switch (value) {
    case Kind.MinusToken: return 1;
    case Kind.TildeToken: return 2;
    case Kind.ExclamationToken: return 3;
    case Kind.PlusPlusToken: return 4;
    case Kind.MinusMinusToken: return 5;
    default: return 0;
  }
}

function typeOperatorIndex(value: unknown): number {
  switch (value) {
    case Kind.ReadonlyKeyword: return 1;
    case Kind.UniqueKeyword: return 2;
    default: return 0;
  }
}

function importPhaseModifierIndex(value: unknown): number {
  switch (value) {
    case Kind.TypeKeyword: return 1;
    case Kind.DeferKeyword: return 2;
    default: return 0;
  }
}

const extendedDataRecorders: Record<number, RecordExtendedDataFunc | undefined> = {};
const commonDataGetters: Record<number, GetCommonDataFunc | undefined> = {};

export function registerExtendedDataRecorder(kind: number, fn: RecordExtendedDataFunc): void {
  extendedDataRecorders[kind] = fn;
}

export function registerCommonDataGetter(kind: number, fn: GetCommonDataFunc): void {
  commonDataGetters[kind] = fn;
}
