// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/encoding/binary.ts","contentHash":"9a6080e5427998ef314857a38841a766e8f98ccfe7ad1a530deb08f483a37545"}

export function Append(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED encoding/binary.Append");
}

export const BigEndian: unknown = undefined as never;

export interface ByteOrder {
  readonly __goFacadeName: "encoding/binary.ByteOrder";
}

export const LittleEndian: unknown = undefined as never;

export function Read(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED encoding/binary.Read");
}

export function Write(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED encoding/binary.Write");
}
