// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/encoding/hex.ts","contentHash":"4c863587347336b8936ce5824a6449900c5d95d87400af35a6611c13cbcacd7d"}

export function EncodeToString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED encoding/hex.EncodeToString");
}
