// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/encoding/json.ts","contentHash":"4f19086ab1f377e43b7a5bf02f4b8b643859dfb63637b2db442349cad4047c5e"}

export function Unmarshal(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED encoding/json.Unmarshal");
}
