// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/bufio.ts","contentHash":"6d62ae426e7c08fc8f1f969389ebffc5a83bcce8a5c16d797d8ba36bf49d4a95"}

export function NewReader(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bufio.NewReader");
}

export function NewScanner(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bufio.NewScanner");
}

export function NewWriter(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bufio.NewWriter");
}

export interface Reader {
  readonly __goFacadeName: "bufio.Reader";
}

export interface Writer {
  readonly __goFacadeName: "bufio.Writer";
}
