// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/bytes.ts","contentHash":"135a3cc2b9fc8de3971ba1fcb9f59660b3f21ad1da02c76f87fe23bfb98d9d96"}

export interface Buffer {
  readonly __goFacadeName: "bytes.Buffer";
}

export function Cut(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.Cut");
}

export function Equal(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.Equal");
}

export function NewBuffer(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.NewBuffer");
}

export function NewReader(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.NewReader");
}

export function ReplaceAll(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.ReplaceAll");
}

export function Split(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.Split");
}

export function TrimSpace(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED bytes.TrimSpace");
}
