// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/cmp.ts","contentHash":"b7bf43eaabfd3b8be436910e920bab8a18a506a3c0dce04d8ef779b14a9337a1"}

export function Compare(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED cmp.Compare");
}
