// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-compat","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/compat.ts","contentHash":"f92973244833b0d0eae33f6640c1e1a9835fd8a82e7cdd59e7e8f105bdff15b3"}

import type { bool, int } from "./scalars.js";

declare global {
  const __tsgoPointerMethodSet: unique symbol;
}

declare const __goBrand: unique symbol;
declare const __goDefinedTypeBrand: unique symbol;
const goRefStorage: unique symbol = Symbol("GoRef.storage");

export type GoNilable<T> = T | undefined;
export type GoDefined<T, Identity extends string> = T extends undefined
  ? T
  : T & { readonly [__goDefinedTypeBrand]?: Identity };
export type GoPointerMethodSet<Methods extends object> = Methods;
type GoPointerMethods<T> = typeof __tsgoPointerMethodSet extends keyof T
  ? T extends { readonly [__tsgoPointerMethodSet]?: infer Methods }
    ? NonNullable<Methods>
    : unknown
  : unknown;
export type GoPtr<T> = GoNilable<T & GoPointerMethods<T>>;
export type GoRef<T> = GoNilable<{ v: T; readonly [goRefStorage]: true } & GoPointerMethods<T>>;
export type GoPointerConstraint<T> = GoPtr<T> | GoRef<T>;
interface GoSequenceBacking<T> {
  readonly values: T[];
  elementRefs: Array<NonNullable<GoRef<T>> | undefined> | undefined;
}

class GoArrayHeader<T, Length extends string> {
  declare private readonly lengthType: Length;

  private constructor(
    private readonly backing: GoSequenceBacking<T>,
    readonly length: int,
  ) {}

  static make<T, Length extends string>(length: int, valueOps: GoValueOps<T>): GoArrayHeader<T, Length> {
    requireGoSequenceExtent(length, "array length");
    return new GoArrayHeader<T, Length>(allocateGoSequenceBacking(length, valueOps), length);
  }

  static makeZeroLength<T>(): GoArrayHeader<T, "0"> {
    const backing = allocateUninitializedGoSequenceBacking<T>(0);
    Object.freeze(backing.values);
    Object.freeze(backing);
    const array = new GoArrayHeader<T, "0">(backing, 0 as int);
    Object.freeze(array);
    return array;
  }

  static loadRaw<T, Length extends string>(array: GoArrayHeader<T, Length>, index: int): T {
    return array.backing.values[GoArrayHeader.absoluteIndex(array, index)]!;
  }

  static storeRaw<T, Length extends string>(array: GoArrayHeader<T, Length>, index: int, value: T): void {
    array.backing.values[GoArrayHeader.absoluteIndex(array, index)] = value;
  }

  static elementRef<T, Length extends string>(
    array: GoArrayHeader<T, Length>,
    index: int,
    valueOps: GoValueOps<T>,
  ): NonNullable<GoRef<T>> {
    return goSequenceElementRef(array.backing, GoArrayHeader.absoluteIndex(array, index), valueOps);
  }

  static clone<T, Length extends string>(array: GoArrayHeader<T, Length>, valueOps: GoValueOps<T>): GoArrayHeader<T, Length> {
    const result = new GoArrayHeader<T, Length>(allocateUninitializedGoSequenceBacking(array.length), array.length);
    for (let index = 0; index < array.length; index++) {
      result.backing.values[index] = valueOps.copy(array.backing.values[index]!);
    }
    return result;
  }

  static cloneZeroLength<T>(array: GoArrayHeader<T, "0">): GoArrayHeader<T, "0"> {
    if (array.length !== 0) throw new RangeError("zero-length array value expected");
    return GoArrayHeader.makeZeroLength<T>();
  }

  static slice<T, Length extends string>(
    array: GoArrayHeader<T, Length>,
    low: int,
    high: int,
    maximum: int,
  ): GoSliceHeader<T> {
    requireGoSequenceExtent(low, "low bound");
    requireGoSequenceExtent(high, "high bound");
    requireGoSequenceExtent(maximum, "maximum bound");
    if (low > high || high > maximum || maximum > array.length) throw new RangeError("slice bounds out of range");
    return GoSliceHeader.fromSequence(array.backing, low, high - low, maximum - low);
  }

  private static absoluteIndex<T, Length extends string>(array: GoArrayHeader<T, Length>, index: int): int {
    requireGoSequenceExtent(index, "index");
    if (index >= array.length) throw new RangeError("index out of range");
    return index;
  }
}

class GoSliceHeader<T> {
  private constructor(
    private readonly backing: GoSequenceBacking<T> | undefined,
    private readonly offset: int,
    readonly length: int,
    private readonly capacityValue: int,
  ) {}

  static nil<T>(): GoSliceHeader<T> {
    return new GoSliceHeader<T>(undefined, 0, 0, 0);
  }

  static make<T>(length: int, capacity: int, valueOps: GoValueOps<T>): GoSliceHeader<T> {
    requireGoSequenceExtent(length, "length");
    requireGoSequenceExtent(capacity, "capacity");
    if (length > capacity) throw new RangeError("makeslice: len out of range");
    return GoSliceHeader.fromSequence(allocateGoSequenceBacking(capacity, valueOps), 0, length, capacity);
  }

  static isNil<T>(slice: GoSliceHeader<T>): bool {
    return (slice.backing === undefined) as bool;
  }

  static capacity<T>(slice: GoSliceHeader<T>): int {
    return slice.capacityValue;
  }

  static reslice<T>(slice: GoSliceHeader<T>, low: int, high: int, maximum: int): GoSliceHeader<T> {
    requireGoSequenceExtent(low, "low bound");
    requireGoSequenceExtent(high, "high bound");
    requireGoSequenceExtent(maximum, "maximum bound");
    if (low > high || high > maximum || maximum > slice.capacityValue) {
      throw new RangeError("slice bounds out of range");
    }
    return GoSliceHeader.fromSequence(
      slice.backing,
      (slice.offset + low) as int,
      (high - low) as int,
      (maximum - low) as int,
    );
  }

  static loadRaw<T>(slice: GoSliceHeader<T>, index: int): T {
    const absoluteIndex = GoSliceHeader.absoluteIndex(slice, index);
    return slice.backing!.values[absoluteIndex]!;
  }

  static storeRaw<T>(slice: GoSliceHeader<T>, index: int, value: T): void {
    const absoluteIndex = GoSliceHeader.absoluteIndex(slice, index);
    slice.backing!.values[absoluteIndex] = value;
  }

  static elementRef<T>(slice: GoSliceHeader<T>, index: int, valueOps: GoValueOps<T>): NonNullable<GoRef<T>> {
    const absoluteIndex = GoSliceHeader.absoluteIndex(slice, index);
    const backing = slice.backing!;
    return goSequenceElementRef(backing, absoluteIndex, valueOps);
  }

  static append<T>(slice: GoSliceHeader<T>, value: T, valueOps: GoValueOps<T>): GoSliceHeader<T> {
    const copiedValue = valueOps.copy(value);
    const requiredLength = checkedGoSliceSum(slice.length, 1);
    if (requiredLength <= slice.capacityValue) {
      slice.backing!.values[slice.offset + slice.length] = copiedValue;
      return GoSliceHeader.fromSequence(slice.backing, slice.offset, requiredLength, slice.capacityValue);
    }
    const result = GoSliceHeader.grow(slice, requiredLength, valueOps);
    result.backing!.values[slice.length] = copiedValue;
    return result;
  }

  static appendSlice<T>(slice: GoSliceHeader<T>, items: GoSliceHeader<T>, valueOps: GoValueOps<T>): GoSliceHeader<T> {
    if (items.length === 0) return slice;
    const requiredLength = checkedGoSliceSum(slice.length, items.length);
    const result = requiredLength <= slice.capacityValue
      ? GoSliceHeader.fromSequence(slice.backing, slice.offset, requiredLength, slice.capacityValue)
      : GoSliceHeader.grow(slice, requiredLength, valueOps);
    const destinationStart = result.offset + slice.length;
    const sourceStart = items.offset;
    const copyBackward = result.backing === items.backing
      && destinationStart > sourceStart
      && destinationStart < sourceStart + items.length;
    if (copyBackward) {
      for (let index = items.length - 1; index >= 0; index--) {
        result.backing!.values[destinationStart + index] = valueOps.copy(items.backing!.values[sourceStart + index]!);
      }
    } else {
      for (let index = 0; index < items.length; index++) {
        result.backing!.values[destinationStart + index] = valueOps.copy(items.backing!.values[sourceStart + index]!);
      }
    }
    return result;
  }

  static copy<T>(destination: GoSliceHeader<T>, source: GoSliceHeader<T>, valueOps: GoValueOps<T>): int {
    const count = Math.min(destination.length, source.length) as int;
    const destinationStart = destination.offset;
    const sourceStart = source.offset;
    const copyBackward = destination.backing === source.backing
      && destinationStart > sourceStart
      && destinationStart < sourceStart + count;
    if (copyBackward) {
      for (let index = count - 1; index >= 0; index--) {
        destination.backing!.values[destinationStart + index] = valueOps.copy(source.backing!.values[sourceStart + index]!);
      }
    } else {
      for (let index = 0; index < count; index++) {
        destination.backing!.values[destinationStart + index] = valueOps.copy(source.backing!.values[sourceStart + index]!);
      }
    }
    return count;
  }

  static clone<T>(slice: GoSliceHeader<T>, valueOps: GoValueOps<T>): GoSliceHeader<T> {
    if (GoSliceHeader.isNil(slice)) return GoSliceHeader.nil<T>();
    const result = GoSliceHeader.fromSequence(allocateUninitializedGoSequenceBacking<T>(slice.length), 0, slice.length, slice.length);
    for (let index = 0; index < slice.length; index++) {
      GoSliceHeader.storeRaw(result, index as int, valueOps.copy(GoSliceHeader.loadRaw(slice, index as int)));
    }
    return result;
  }

  static clear<T>(slice: GoSliceHeader<T>, valueOps: GoValueOps<T>): void {
    for (let index = 0; index < slice.length; index++) {
      GoSliceHeader.storeRaw(slice, index as int, valueOps.zero());
    }
  }

  static fromSequence<T>(
    backing: GoSequenceBacking<T> | undefined,
    offset: int,
    length: int,
    capacity: int,
  ): GoSliceHeader<T> {
    return new GoSliceHeader(backing, offset, length, capacity);
  }

  private static absoluteIndex<T>(slice: GoSliceHeader<T>, index: int): int {
    requireGoSequenceExtent(index, "index");
    if (index >= slice.length) throw new RangeError("index out of range");
    return (slice.offset + index) as int;
  }

  private static grow<T>(slice: GoSliceHeader<T>, requiredLength: int, valueOps: GoValueOps<T>): GoSliceHeader<T> {
    const capacity = goSliceGrowthCapacity(slice.capacityValue, requiredLength);
    const result = GoSliceHeader.fromSequence(allocateUninitializedGoSequenceBacking<T>(capacity), 0, requiredLength, capacity);
    for (let index = 0; index < slice.length; index++) {
      result.backing!.values[index] = valueOps.copy(GoSliceHeader.loadRaw(slice, index as int));
    }
    for (let index = requiredLength; index < capacity; index++) result.backing!.values[index] = valueOps.zero();
    return result;
  }
}

export type GoSlice<T> = GoSliceHeader<T>;
export type GoArray<T, Length extends string> = GoArrayHeader<T, Length>;

function allocateGoSequenceBacking<T>(capacity: int, valueOps: GoValueOps<T>): GoSequenceBacking<T> {
  const backing = allocateUninitializedGoSequenceBacking<T>(capacity);
  const values = backing.values;
  for (let index = 0; index < capacity; index++) values[index] = valueOps.zero();
  return backing;
}

function allocateUninitializedGoSequenceBacking<T>(capacity: int): GoSequenceBacking<T> {
  return { values: new Array<T>(capacity), elementRefs: undefined };
}

function goSequenceElementRef<T>(
  backing: GoSequenceBacking<T>,
  absoluteIndex: int,
  valueOps: GoValueOps<T>,
): NonNullable<GoRef<T>> {
  const elementRefs = backing.elementRefs ??= [];
  const existing = elementRefs[absoluteIndex];
  if (existing !== undefined) return existing;
  const reference = {
    [goRefStorage]: true,
    get v(): T { return backing.values[absoluteIndex]!; },
    set v(value: T) { backing.values[absoluteIndex] = valueOps.copy(value); },
  } as NonNullable<GoRef<T>>;
  elementRefs[absoluteIndex] = reference;
  return reference;
}

function requireGoSequenceExtent(value: int, label: string): void {
  if (!Number.isSafeInteger(value) || value < 0) throw new RangeError(label + " out of range");
}

function checkedGoSliceSum(left: int, right: int): int {
  const result = left + right;
  if (!Number.isSafeInteger(result)) throw new RangeError("growslice: len out of range");
  return result as int;
}

function goSliceGrowthCapacity(current: int, required: int): int {
  let capacity = current === 0 ? 1 : current;
  while (capacity < required) {
    const next = capacity <= 1024 ? capacity * 2 : capacity + Math.ceil(capacity / 4);
    if (!Number.isSafeInteger(next) || next <= capacity) return required;
    capacity = next;
  }
  return capacity as int;
}

export function GoNilSlice<T>(): GoSlice<T> {
  return GoSliceHeader.nil<T>();
}

export function GoArrayMake<T, Length extends string>(length: int, valueOps: GoValueOps<T>): GoArray<T, Length> {
  return GoArrayHeader.make<T, Length>(length, valueOps);
}

export function GoArrayBuild<T, Length extends string>(
  length: int,
  valueOps: GoValueOps<T>,
  initialize: (array: GoArray<T, Length>) => void,
): GoArray<T, Length> {
  const array = GoArrayMake<T, Length>(length, valueOps);
  initialize(array);
  return array;
}

export function GoArrayLoad<T, Length extends string>(array: GoArray<T, Length>, index: int, valueOps: GoValueOps<T>): T {
  return valueOps.copy(GoArrayHeader.loadRaw(array, index));
}

export function GoArrayStore<T, Length extends string>(array: GoArray<T, Length>, index: int, value: T, valueOps: GoValueOps<T>): void {
  GoArrayHeader.storeRaw(array, index, valueOps.copy(value));
}

export function GoArrayElementRef<T, Length extends string>(
  array: GoArray<T, Length>,
  index: int,
  valueOps: GoValueOps<T>,
): NonNullable<GoRef<T>> {
  return GoArrayHeader.elementRef(array, index, valueOps);
}

export function GoArraySlice<T, Length extends string>(array: GoArray<T, Length>, low: int, high: int): GoSlice<T> {
  return GoArrayHeader.slice(array, low, high, array.length);
}

export function GoArrayFullSlice<T, Length extends string>(
  array: GoArray<T, Length>,
  low: int,
  high: int,
  maximum: int,
): GoSlice<T> {
  return GoArrayHeader.slice(array, low, high, maximum);
}

export function GoArrayValueOps<T, Length extends string>(length: int, elementOps: GoValueOps<T>): GoValueOps<GoArray<T, Length>> {
  return Object.freeze({
    zero: (): GoArray<T, Length> => GoArrayMake<T, Length>(length, elementOps),
    copy: (value: GoArray<T, Length>): GoArray<T, Length> => GoArrayHeader.clone(value, elementOps),
  });
}

export function GoZeroLengthArrayValueOps<T>(): GoValueOps<GoArray<T, "0">> {
  return Object.freeze({
    zero: (): GoArray<T, "0"> => GoArrayHeader.makeZeroLength<T>(),
    copy: (value: GoArray<T, "0">): GoArray<T, "0"> => GoArrayHeader.cloneZeroLength(value),
  });
}

export function GoSliceIsNil<T>(slice: GoSlice<T>): bool {
  return GoSliceHeader.isNil(slice);
}

export function GoSliceMake<T>(length: int, capacity: int, valueOps: GoValueOps<T>): GoSlice<T> {
  return GoSliceHeader.make(length, capacity, valueOps);
}

export function GoSliceBuild<T>(
  length: int,
  capacity: int,
  valueOps: GoValueOps<T>,
  initialize: (slice: GoSlice<T>) => void,
): GoSlice<T> {
  const slice = GoSliceMake(length, capacity, valueOps);
  initialize(slice);
  return slice;
}

export function GoSliceCapacity<T>(slice: GoSlice<T>): int {
  return GoSliceHeader.capacity(slice);
}

export function GoSliceReslice<T>(slice: GoSlice<T>, low: int, high: int): GoSlice<T> {
  return GoSliceHeader.reslice(slice, low, high, GoSliceHeader.capacity(slice));
}

export function GoSliceFullReslice<T>(slice: GoSlice<T>, low: int, high: int, maximum: int): GoSlice<T> {
  return GoSliceHeader.reslice(slice, low, high, maximum);
}

export function GoSliceLoad<T>(slice: GoSlice<T>, index: int, valueOps: GoValueOps<T>): T {
  return valueOps.copy(GoSliceHeader.loadRaw(slice, index));
}

export function GoSliceStore<T>(slice: GoSlice<T>, index: int, value: T, valueOps: GoValueOps<T>): void {
  GoSliceHeader.storeRaw(slice, index, valueOps.copy(value));
}

export function GoSliceElementRef<T>(slice: GoSlice<T>, index: int, valueOps: GoValueOps<T>): NonNullable<GoRef<T>> {
  return GoSliceHeader.elementRef(slice, index, valueOps);
}

export function GoSliceAppend<T>(slice: GoSlice<T>, value: T, valueOps: GoValueOps<T>): GoSlice<T> {
  return GoSliceHeader.append(slice, value, valueOps);
}

export function GoSliceAppendSlice<T>(slice: GoSlice<T>, items: GoSlice<T>, valueOps: GoValueOps<T>): GoSlice<T> {
  return GoSliceHeader.appendSlice(slice, items, valueOps);
}

export function GoSliceCopy<T>(destination: GoSlice<T>, source: GoSlice<T>, valueOps: GoValueOps<T>): int {
  return GoSliceHeader.copy(destination, source, valueOps);
}

export function GoSliceClone<T>(slice: GoSlice<T>, valueOps: GoValueOps<T>): GoSlice<T> {
  return GoSliceHeader.clone(slice, valueOps);
}

export function GoSliceClear<T>(slice: GoSlice<T>, valueOps: GoValueOps<T>): void {
  GoSliceHeader.clear(slice, valueOps);
}

export type GoMap<K, V> = Map<K, V>;
export type GoChan<T, Direction extends string = "bidirectional"> = {
  readonly [__goBrand]?: { readonly element: T; readonly direction: Direction };
  readonly [goChannelState]?: GoChannelState<T>;
};
export type GoFunc<F> = GoNilable<F>;
export type GoInterface<I> = GoNilable<I>;
export type GoError = GoInterface<Error>;
export type GoComparable = unknown;
export type GoOrdered = string | number | bigint | bool;
export type GoConstraint<Text extends string> = unknown;
export type GoUnsupported<Text extends string> = { readonly [__goBrand]: { readonly unsupported: Text } };
export type GoComplex64 = { readonly real: number; readonly imag: number };
export type GoComplex128 = { readonly real: number; readonly imag: number };
declare const goUnsafePointerBrand: unique symbol;
export type GoUnsafePointer = GoNilable<{ readonly [goUnsafePointerBrand]: never }>;
export type GoRune = int;
export type GoZeroFactory<T> = () => T;
export type GoCopy<T> = (value: T) => T;
export interface GoValueOps<T> {
  readonly zero: GoZeroFactory<T>;
  readonly copy: GoCopy<T>;
}
export type GoEquality<T> = (left: T, right: T) => bool;

export function GoEqualStrict<T extends GoComparable>(left: T, right: T): bool {
  return left === right;
}

export function GoEqualEmptyStruct(_left: { readonly __tsgoEmpty?: never }, _right: { readonly __tsgoEmpty?: never }): bool {
  return true;
}

export function GoZeroBoolean(): bool {
  return false;
}

export function GoZeroNumber(): number {
  return 0;
}

export function GoZeroBigInt(): bigint {
  return 0n;
}

export function GoZeroString(): string {
  return "";
}

export function GoZeroPointer<T>(): GoPtr<T> {
  return undefined;
}

export function GoZeroRef<T>(): GoRef<T> {
  return undefined;
}

export function GoZeroFunction<F>(): GoFunc<F> {
  return undefined;
}

export function GoZeroInterface<I>(): GoInterface<I> {
  return undefined;
}

export function GoZeroComparableInterface<T>(): GoComparableInterface<T> {
  return undefined;
}

export function GoZeroSlice<T>(): GoSlice<T> {
  return GoNilSlice();
}

export function GoZeroMap<K, V>(): GoMap<K, V> {
  return GoNilMap();
}

export function GoZeroChannel<T, Direction extends string = "bidirectional">(): GoChan<T, Direction> {
  return GoNilChan();
}

export function GoZeroUnsafePointer(): GoUnsafePointer {
  return undefined;
}

export function GoZeroEmptyStruct(): { readonly __tsgoEmpty?: never } {
  return {};
}

export function GoCopyIdentity<T>(value: T): T {
  return value;
}

export const GoBooleanValueOps: GoValueOps<boolean> = Object.freeze({ zero: GoZeroBoolean, copy: GoCopyIdentity });
export const GoNumberValueOps: GoValueOps<number> = Object.freeze({ zero: GoZeroNumber, copy: GoCopyIdentity });
export const GoBigIntValueOps: GoValueOps<bigint> = Object.freeze({ zero: GoZeroBigInt, copy: GoCopyIdentity });
export const GoStringValueOps: GoValueOps<string> = Object.freeze({ zero: GoZeroString, copy: GoCopyIdentity });
export const GoComplex64ValueOps: GoValueOps<GoComplex64> = Object.freeze({
  zero: (): GoComplex64 => ({ real: 0, imag: 0 }),
  copy: (value: GoComplex64): GoComplex64 => ({ real: value.real, imag: value.imag }),
});
export const GoComplex128ValueOps: GoValueOps<GoComplex128> = Object.freeze({
  zero: (): GoComplex128 => ({ real: 0, imag: 0 }),
  copy: (value: GoComplex128): GoComplex128 => ({ real: value.real, imag: value.imag }),
});

const goPointerValueOps = Object.freeze({ zero: GoZeroPointer, copy: GoCopyIdentity });
const goRefValueOps = Object.freeze({ zero: GoZeroRef, copy: GoCopyIdentity });
const goFunctionValueOps = Object.freeze({ zero: GoZeroFunction, copy: GoCopyIdentity });
const goSliceValueOps = Object.freeze({ zero: GoZeroSlice, copy: GoCopyIdentity });
const goMapValueOps = Object.freeze({ zero: GoZeroMap, copy: GoCopyIdentity });
const goChannelValueOps = Object.freeze({ zero: GoZeroChannel, copy: GoCopyIdentity });
const goInterfaceValueOps = Object.freeze({ zero: GoZeroInterface, copy: GoCopyIdentity });
const goUnsafePointerValueOps = Object.freeze({ zero: GoZeroUnsafePointer, copy: GoCopyIdentity });

export function GoPointerValueOps<T>(): GoValueOps<GoPtr<T>> {
  return goPointerValueOps;
}

export function GoRefValueOps<T>(): GoValueOps<GoRef<T>> {
  return goRefValueOps;
}

export function GoFunctionValueOps<F>(): GoValueOps<GoFunc<F>> {
  return goFunctionValueOps;
}

export function GoSliceValueOps<T>(): GoValueOps<GoSlice<T>> {
  return goSliceValueOps;
}

export function GoMapValueOps<K, V>(): GoValueOps<GoMap<K, V>> {
  return goMapValueOps;
}

export function GoChannelValueOps<T, Direction extends string = "bidirectional">(): GoValueOps<GoChan<T, Direction>> {
  return goChannelValueOps;
}

export function GoInterfaceValueOps<I>(): GoValueOps<GoInterface<I>> {
  return goInterfaceValueOps;
}

export function GoUnsafePointerValueOps(): GoValueOps<GoUnsafePointer> {
  return goUnsafePointerValueOps;
}


export function GoValueRef<T>(value: T): NonNullable<GoRef<T>> {
  return { v: value, [goRefStorage]: true } as NonNullable<GoRef<T>>;
}

export function GoFieldRef<T>(read: () => T, write: (value: T) => void): NonNullable<GoRef<T>> {
  return {
    [goRefStorage]: true,
    get v(): T { return read(); },
    set v(value: T) { write(value); },
  } as NonNullable<GoRef<T>>;
}

export function GoIsRef(value: unknown): value is NonNullable<GoRef<unknown>> {
  return typeof value === "object" && value !== null && (value as { readonly [goRefStorage]?: unknown })[goRefStorage] === true;
}

export function GoRequireNonNilAfterSuccess<T>(value: GoPtr<T>, operation: string): T {
  if (value === undefined) {
    throw new TypeError(`${operation} returned nil after success`);
  }
  return value;
}

const goNilMap: Map<unknown, unknown> = new class extends Map<unknown, unknown> {
  override clear(): void {}
  override delete(_key: unknown): boolean { return false; }
  override set(_key: unknown, _value: unknown): this { throw new Error("assignment to entry in nil map"); }
}();

export function GoNilMap<K, V>(): GoMap<K, V> {
  return goNilMap as GoMap<K, V>;
}

export function GoMapIsNil<K, V>(map: GoMap<K, V>): bool {
  return (map === goNilMap) as bool;
}

export interface GoInterfaceValue<T> {
  __tsgoGoReceiver(): GoPtr<T>;
}

type GoChannelReceiver<T> = (value: T, ok: bool) => void;

interface GoChannelWaiter<T> {
  active: bool;
  deliver(value: T, ok: bool): bool;
}

interface GoChannelState<T> {
  capacity: number;
  queue: T[];
  waiters: GoChannelWaiter<T>[];
  closed: bool;
  zeroValue(): T;
}

export interface GoChanSelectCase {
  readonly channel: GoChan<unknown, string>;
  readonly receiver: GoChannelReceiver<unknown>;
}

const goChannelState: unique symbol = Symbol("GoChannel.state");
const goNilChannel: GoChan<unknown, string> = {};

export function GoNilChan<T, Direction extends string = "bidirectional">(): GoChan<T, Direction> {
  return goNilChannel as GoChan<T, Direction>;
}

export function GoChanIsNil<T, Direction extends string>(channel: GoChan<T, Direction>): bool {
  return (channel === goNilChannel) as bool;
}

export function MakeGoChan<T>(capacity: number, zeroValue: () => T): GoChan<T> {
  if (!Number.isSafeInteger(capacity) || capacity < 0) {
    throw new RangeError("makechan: size out of range");
  }
  return {
    [goChannelState]: {
      capacity,
      queue: [],
      waiters: [],
      closed: false,
      zeroValue,
    },
  };
}

export function GoChanAsReceive<T>(channel: GoChan<T>): GoChan<T, "receive"> {
  return channel as unknown as GoChan<T, "receive">;
}

export function GoChanAsSend<T>(channel: GoChan<T>): GoChan<T, "send"> {
  return channel as unknown as GoChan<T, "send">;
}

export function GoChanTrySend<T>(channel: GoChan<T, string>, value: T): bool {
  if (GoChanIsNil(channel)) return false as bool;
  const state = requireGoChannelState(channel);
  if (state.closed) throw new Error("send on closed channel");
  const waiter = takeGoChannelWaiter(state);
  if (waiter !== undefined) return waiter.deliver(value, true as bool);
  if (state.queue.length < state.capacity) {
    state.queue.push(value);
    return true as bool;
  }
  return false as bool;
}

export function GoChanReceive<T>(channel: GoChan<T, string>, receiver: GoChannelReceiver<T>): () => void {
  if (GoChanIsNil(channel)) return () => {};
  const state = requireGoChannelState(channel);
  if (goChannelReceiveReady(state)) {
    const [value, ok] = takeGoChannelReadyValue(state);
    queueMicrotask(() => receiver(value, ok));
    return () => {};
  }
  const waiter: GoChannelWaiter<T> = {
    active: true,
    deliver(value, ok) {
      queueMicrotask(() => receiver(value, ok));
      return true as bool;
    },
  };
  state.waiters.push(waiter);
  return () => { waiter.active = false; };
}

export function GoChanSelectReceive<T>(channel: GoChan<T, string>, receiver: GoChannelReceiver<T>): GoChanSelectCase {
  return {
    channel: channel as GoChan<unknown, string>,
    receiver: receiver as GoChannelReceiver<unknown>,
  };
}

export function GoChanSelect(cases: readonly GoChanSelectCase[]): () => void {
  const ready = [] as number[];
  for (let index = 0; index < cases.length; index++) {
    const channel = cases[index]!.channel;
    if (!GoChanIsNil(channel) && goChannelReceiveReady(requireGoChannelState(channel))) ready.push(index);
  }
  if (ready.length > 0) {
    const selectedIndex = ready.length === 1 ? ready[0]! : ready[Math.floor(Math.random() * ready.length)]!;
    const selected = cases[selectedIndex]!;
    const [value, ok] = takeGoChannelReadyValue(requireGoChannelState(selected.channel));
    queueMicrotask(() => selected.receiver(value, ok));
    return () => {};
  }

  let active = true;
  const waiters: Array<GoChannelWaiter<unknown>> = [];
  const cancel = (): void => {
    if (!active) return;
    active = false;
    for (const waiter of waiters) waiter.active = false;
  };
  for (const selectCase of cases) {
    if (GoChanIsNil(selectCase.channel)) continue;
    const waiter: GoChannelWaiter<unknown> = {
      active: true,
      deliver(value, ok) {
        if (!active) return false as bool;
        active = false;
        for (const other of waiters) other.active = false;
        queueMicrotask(() => selectCase.receiver(value, ok));
        return true as bool;
      },
    };
    waiters.push(waiter);
    requireGoChannelState(selectCase.channel).waiters.push(waiter);
  }
  return cancel;
}

export function GoChanClose<T>(channel: GoChan<T, string>): void {
  if (GoChanIsNil(channel)) throw new Error("close of nil channel");
  const state = requireGoChannelState(channel);
  if (state.closed) throw new Error("close of closed channel");
  state.closed = true;
  while (state.queue.length > 0) {
    const waiter = takeGoChannelWaiter(state);
    if (waiter === undefined) break;
    waiter.deliver(state.queue.shift()!, true as bool);
  }
  let waiter: GoChannelWaiter<T> | undefined;
  while ((waiter = takeGoChannelWaiter(state)) !== undefined) waiter.deliver(state.zeroValue(), false as bool);
}

function requireGoChannelState<T>(channel: GoChan<T, string>): GoChannelState<T> {
  const state = channel[goChannelState];
  if (state === undefined) throw new Error("channel has no runtime state");
  return state;
}

function takeGoChannelWaiter<T>(state: GoChannelState<T>): GoChannelWaiter<T> | undefined {
  while (state.waiters.length > 0) {
    const waiter = state.waiters.shift()!;
    if (waiter.active) {
      waiter.active = false;
      return waiter;
    }
  }
  return undefined;
}

function goChannelReceiveReady<T>(state: GoChannelState<T>): bool {
  return (state.queue.length > 0 || state.closed) as bool;
}

function takeGoChannelReadyValue<T>(state: GoChannelState<T>): [T, bool] {
  if (state.queue.length > 0) return [state.queue.shift()!, true as bool];
  if (state.closed) return [state.zeroValue(), false as bool];
  throw new Error("receive from channel that is not ready");
}


export interface GoMapKeyDescriptor<K> {
  readonly identity: symbol;
  appendHashParts(parts: unknown[], value: K): void;
  snapshot(value: K): K;
  makeMap<V>(): GoMap<K, V>;
}

export interface GoStructKeyField<K, V> {
  appendHashParts(parts: unknown[], value: K): void;
  snapshot(value: K): V;
}

export interface GoDynamicComparable<T = unknown> {
  readonly typeIdentity: symbol;
  readonly value: T;
  appendHashParts(parts: unknown[]): void;
  snapshot(): GoDynamicComparable<T>;
}

export type GoComparableInterface<T = unknown> = GoDynamicComparable<T> | undefined;

const goNilPointerKey = Symbol("GoKey.nilPointer");
const goNilInterfaceKey = Symbol("GoKey.nilInterface");

function createGoMapKeyDescriptor<K>(
  appendHashParts: (parts: unknown[], value: K) => void,
  snapshot: (value: K) => K,
  makeMap: <V>(descriptor: GoMapKeyDescriptor<K>) => GoMap<K, V>,
): GoMapKeyDescriptor<K> {
  const descriptor: GoMapKeyDescriptor<K> = {
    identity: Symbol("GoKey.type"),
    appendHashParts,
    snapshot,
    makeMap<V>(): GoMap<K, V> {
      return makeMap<V>(descriptor);
    },
  };
  return globalThis.Object.freeze(descriptor);
}

function newNativeGoMap<K, V>(_descriptor: GoMapKeyDescriptor<K>): GoMap<K, V> {
  return new globalThis.Map<K, V>();
}

function newNumberGoMap<K extends number, V>(_descriptor: GoMapKeyDescriptor<K>): GoMap<K, V> {
  return new GoNumberMap<K, V>();
}

function newStructuredGoMap<K, V>(descriptor: GoMapKeyDescriptor<K>): GoMap<K, V> {
  return new GoStructMap<K, V>(descriptor);
}

function appendGoMapKey<K>(parts: unknown[], descriptor: GoMapKeyDescriptor<K>, value: K): void {
  parts.push(descriptor.identity);
  descriptor.appendHashParts(parts, value);
}

function requireGoKeyType(value: unknown, expected: string): void {
  if (typeof value !== expected) throw new TypeError("Go map key descriptor expected " + expected + ", got " + typeof value);
}

export const GoBooleanKey: GoMapKeyDescriptor<boolean> = createGoMapKeyDescriptor<boolean>((parts, value) => {
  requireGoKeyType(value, "boolean");
  parts.push(value);
}, (value) => {
  requireGoKeyType(value, "boolean");
  return value;
}, newNativeGoMap);

export const GoNumberKey: GoMapKeyDescriptor<number> = createGoMapKeyDescriptor<number>((parts, value) => {
  requireGoKeyType(value, "number");
  parts.push(Number.isNaN(value) ? Symbol("GoKey.NaN") : value);
}, (value) => {
  requireGoKeyType(value, "number");
  return value;
}, newNumberGoMap);

export const GoBigIntKey: GoMapKeyDescriptor<bigint> = createGoMapKeyDescriptor<bigint>((parts, value) => {
  requireGoKeyType(value, "bigint");
  parts.push(value);
}, (value) => {
  requireGoKeyType(value, "bigint");
  return value;
}, newNativeGoMap);

export const GoStringKey: GoMapKeyDescriptor<string> = createGoMapKeyDescriptor<string>((parts, value) => {
  requireGoKeyType(value, "string");
  parts.push(value);
}, (value) => {
  requireGoKeyType(value, "string");
  return value;
}, newNativeGoMap);

export function GoPointerKey<T extends object>(): GoMapKeyDescriptor<GoPtr<T>> {
  const exact = (value: GoPtr<T>): GoPtr<T> => {
    if (value === undefined) return undefined;
    if ((typeof value !== "object" || value === null) && typeof value !== "function") {
      throw new TypeError("Go pointer map key must retain object identity");
    }
    return value;
  };
  return createGoMapKeyDescriptor<GoPtr<T>>((parts, value) => {
    if (exact(value) === undefined) {
      parts.push(goNilPointerKey);
      return;
    }
    parts.push(value);
  }, exact, newNativeGoMap);
}

export function GoArrayKey<T>(length: number, element: GoMapKeyDescriptor<T>): GoMapKeyDescriptor<readonly T[]> {
  if (!Number.isSafeInteger(length) || length < 0) throw new RangeError("Go array key length must be a non-negative safe integer");
  const requireArray = (value: readonly T[]): void => {
    if (!globalThis.Array.isArray(value) || value.length !== length) {
      throw new TypeError("Go array map key expected length " + length);
    }
  };
  return createGoMapKeyDescriptor<readonly T[]>((parts, value) => {
    requireArray(value);
    for (const item of value) appendGoMapKey(parts, element, item);
  }, (value) => {
    requireArray(value);
    return value.map((item) => element.snapshot(item));
  }, newStructuredGoMap);
}

export function GoStructField<K, V>(read: (value: K) => V, descriptor: GoMapKeyDescriptor<V>): GoStructKeyField<K, V> {
  return {
    appendHashParts: (parts, value) => appendGoMapKey(parts, descriptor, read(value)),
    snapshot: (value) => descriptor.snapshot(read(value)),
  };
}

export function GoStructKey<K, const Values extends readonly unknown[]>(
  fields: { readonly [Index in keyof Values]: GoStructKeyField<K, Values[Index]> },
  construct: (values: Values, source: K) => K,
): GoMapKeyDescriptor<K> {
  return createGoMapKeyDescriptor<K>((parts, value) => {
    if (typeof value !== "object" || value === null) throw new TypeError("Go struct map key must be an object value");
    for (const field of fields) field.appendHashParts(parts, value);
  }, (value) => {
    if (typeof value !== "object" || value === null) throw new TypeError("Go struct map key must be an object value");
    const snapshots = fields.map((field) => field.snapshot(value)) as unknown as Values;
    return construct(snapshots, value);
  }, newStructuredGoMap);
}

export function GoNamedStringKey<K extends string>(): GoMapKeyDescriptor<K> {
  return createGoMapKeyDescriptor<K>((parts, value) => {
    requireGoKeyType(value, "string");
    parts.push(value);
  }, (value) => {
    requireGoKeyType(value, "string");
    return value;
  }, newNativeGoMap);
}

export function GoNamedNumberKey<K extends number>(): GoMapKeyDescriptor<K> {
  return createGoMapKeyDescriptor<K>((parts, value) => {
    requireGoKeyType(value, "number");
    parts.push(Number.isNaN(value) ? Symbol("GoKey.NaN") : value);
  }, (value) => {
    requireGoKeyType(value, "number");
    return value;
  }, newNumberGoMap);
}

export function GoDynamicValue<T>(descriptor: GoMapKeyDescriptor<T>, value: T): GoDynamicComparable<T> {
  return globalThis.Object.freeze({
    typeIdentity: descriptor.identity,
    value,
    appendHashParts(parts: unknown[]): void {
      descriptor.appendHashParts(parts, value);
    },
    snapshot(): GoDynamicComparable<T> {
      return GoDynamicValue(descriptor, descriptor.snapshot(value));
    },
  });
}

export function GoBoxComparableInterface<T>(descriptor: GoMapKeyDescriptor<T>, value: T): GoInterface<unknown> {
  return GoDynamicValue(descriptor, value);
}

export function GoRequireComparableInterface(value: GoInterface<unknown>): GoComparableInterface {
  if (value === undefined) return undefined;
  const dynamic = value as GoDynamicComparable<unknown>;
  if (typeof dynamic.typeIdentity !== "symbol") throw new TypeError("hash of unboxed Go interface value");
  return dynamic;
}

export function GoUnboxComparableInterface(value: GoInterface<unknown>): GoInterface<unknown> {
  return GoRequireComparableInterface(value)?.value;
}

export function GoAssertComparableInterface<T>(value: GoInterface<unknown>, descriptor: GoMapKeyDescriptor<T>, expectedType: string): T {
  if (value === undefined) throw new TypeError("interface conversion: interface is nil, not " + expectedType);
  const dynamic = GoRequireComparableInterface(value)!;
  if (dynamic.typeIdentity !== descriptor.identity) throw new TypeError("interface conversion: interface does not contain " + expectedType);
  return dynamic.value as T;
}

export function GoInterfaceKey<K>(
  dynamic: (value: K) => GoDynamicComparable | undefined,
  construct: (dynamic: GoDynamicComparable | undefined) => K,
): GoMapKeyDescriptor<K> {
  return createGoMapKeyDescriptor<K>((parts, value) => {
    const selected = dynamic(value);
    if (selected === undefined) {
      parts.push(goNilInterfaceKey);
      return;
    }
    parts.push(selected.typeIdentity);
    selected.appendHashParts(parts);
  }, (value) => {
    const selected = dynamic(value);
    return selected === undefined
      ? construct(undefined)
      : construct(selected.snapshot());
  }, newStructuredGoMap);
}

export const GoComparableInterfaceKey: GoMapKeyDescriptor<GoComparableInterface> = GoInterfaceKey<GoComparableInterface>(
  (value) => value,
  (value) => value,
);


interface GoNumberMapEntry<K extends number, V> {
  readonly key: K;
  value: V;
  active: boolean;
}

export class GoNumberMap<K extends number = number, V = unknown> implements Map<K, V> {
  readonly [Symbol.toStringTag] = "Map";
  private readonly indexedEntries = new globalThis.Map<number, GoNumberMapEntry<K, V>>();
  private readonly orderedEntries: Array<GoNumberMapEntry<K, V>> = [];
  private activeSize = 0;

  get size(): number { return this.activeSize; }

  clear(): void {
    this.indexedEntries.clear();
    this.orderedEntries.length = 0;
    this.activeSize = 0;
  }

  delete(key: K): boolean {
    requireGoKeyType(key, "number");
    if (Number.isNaN(key)) return false;
    const entry = this.indexedEntries.get(key);
    if (entry === undefined) return false;
    entry.active = false;
    this.indexedEntries.delete(key);
    this.activeSize--;
    return true;
  }

  forEach(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: unknown): void {
    for (const entry of this.orderedEntries) if (entry.active) callbackfn.call(thisArg, entry.value, entry.key, this);
  }

  get(key: K): V | undefined {
    requireGoKeyType(key, "number");
    return Number.isNaN(key) ? undefined : this.indexedEntries.get(key)?.value;
  }

  has(key: K): boolean {
    requireGoKeyType(key, "number");
    return !Number.isNaN(key) && this.indexedEntries.has(key);
  }

  set(key: K, value: V): this {
    requireGoKeyType(key, "number");
    if (!Number.isNaN(key)) {
      const existing = this.indexedEntries.get(key);
      if (existing !== undefined) {
        existing.value = value;
        return this;
      }
    }
    const entry: GoNumberMapEntry<K, V> = { key, value, active: true };
    if (!Number.isNaN(key)) this.indexedEntries.set(key, entry);
    this.orderedEntries.push(entry);
    this.activeSize++;
    return this;
  }

  *entries(): MapIterator<[K, V]> {
    for (const entry of this.orderedEntries) if (entry.active) yield [entry.key, entry.value];
  }

  *keys(): MapIterator<K> {
    for (const entry of this.orderedEntries) if (entry.active) yield entry.key;
  }

  *values(): MapIterator<V> {
    for (const entry of this.orderedEntries) if (entry.active) yield entry.value;
  }

  [Symbol.iterator](): MapIterator<[K, V]> { return this.entries(); }
}

interface GoStructMapEntry<K, V> {
  readonly key: K;
  value: V;
  active: boolean;
}

interface GoStructMapTrieNode<K, V> {
  readonly children: Map<unknown, GoStructMapTrieNode<K, V>>;
  entry?: GoStructMapEntry<K, V>;
}

function newGoStructMapTrieNode<K, V>(): GoStructMapTrieNode<K, V> {
  return { children: new globalThis.Map() };
}

export class GoStructMap<K, V> implements Map<K, V> {
  readonly [Symbol.toStringTag] = "Map";
  private root = newGoStructMapTrieNode<K, V>();
  private readonly orderedEntries: Array<GoStructMapEntry<K, V>> = [];
  private activeSize = 0;

  constructor(private readonly keyDescriptor: GoMapKeyDescriptor<K>) {}

  get size(): number { return this.activeSize; }

  clear(): void {
    this.root = newGoStructMapTrieNode<K, V>();
    this.orderedEntries.length = 0;
    this.activeSize = 0;
  }

  delete(key: K): boolean {
    const entry = this.findEntry(key);
    if (entry === undefined) return false;
    entry.active = false;
    delete this.leafForHashParts(this.hashParts(key), false)!.entry;
    this.activeSize--;
    return true;
  }

  forEach(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: unknown): void {
    for (const entry of this.orderedEntries) if (entry.active) callbackfn.call(thisArg, entry.value, entry.key, this);
  }

  get(key: K): V | undefined { return this.findEntry(key)?.value; }

  getOrInsert(key: K, value: V): V {
    const existing = this.findEntry(key);
    if (existing !== undefined) return existing.value;
    this.insert(key, value);
    return value;
  }

  getOrInsertComputed(key: K, callbackfn: (key: K) => V): V {
    const existing = this.findEntry(key);
    if (existing !== undefined) return existing.value;
    const value = callbackfn(key);
    this.insert(key, value);
    return value;
  }

  has(key: K): boolean { return this.findEntry(key) !== undefined; }

  set(key: K, value: V): this {
    const existing = this.findEntry(key);
    if (existing !== undefined) existing.value = value;
    else this.insert(key, value);
    return this;
  }

  load(key: K): [V | undefined, boolean] {
    const entry = this.findEntry(key);
    return entry === undefined ? [undefined, false] : [entry.value, true];
  }

  lookup(key: K): { value: V } | undefined {
    const entry = this.findEntry(key);
    return entry === undefined ? undefined : { value: entry.value };
  }

  loadOrStore(key: K, value: V): [V, boolean] {
    const existing = this.findEntry(key);
    if (existing !== undefined) return [existing.value, true];
    this.insert(key, value);
    return [value, false];
  }

  loadAndDelete(key: K): [V | undefined, boolean] {
    const entry = this.findEntry(key);
    if (entry === undefined) return [undefined, false];
    const value = entry.value;
    this.delete(key);
    return [value, true];
  }

  *entries(): MapIterator<[K, V]> { for (const entry of this.orderedEntries) if (entry.active) yield [entry.key, entry.value]; }
  *keys(): MapIterator<K> { for (const entry of this.orderedEntries) if (entry.active) yield entry.key; }
  *values(): MapIterator<V> { for (const entry of this.orderedEntries) if (entry.active) yield entry.value; }
  [Symbol.iterator](): MapIterator<[K, V]> { return this.entries(); }

  private findEntry(key: K): GoStructMapEntry<K, V> | undefined {
    return this.leafForHashParts(this.hashParts(key), false)?.entry;
  }

  private insert(key: K, value: V): void {
    const keySnapshot = this.keyDescriptor.snapshot(key);
    const entry = { key: keySnapshot, value, active: true };
    this.leafForHashParts(this.hashParts(keySnapshot), true)!.entry = entry;
    this.orderedEntries.push(entry);
    this.activeSize++;
  }

  private hashParts(key: K): unknown[] {
    const parts: unknown[] = [];
    appendGoMapKey(parts, this.keyDescriptor, key);
    return parts;
  }

  private leafForHashParts(parts: readonly unknown[], create: boolean): GoStructMapTrieNode<K, V> | undefined {
    let node = this.root;
    for (const part of parts) {
      let child = node.children.get(part);
      if (child === undefined) {
        if (!create) return undefined;
        child = newGoStructMapTrieNode<K, V>();
        node.children.set(part, child);
      }
      node = child;
    }
    return node;
  }
}

export function NewGoStructMap<K, V>(keyDescriptor: GoMapKeyDescriptor<K>): GoStructMap<K, V> {
  return new GoStructMap<K, V>(keyDescriptor);
}

export function GoMapMake<K, V>(keyDescriptor: GoMapKeyDescriptor<K>): GoMap<K, V> {
  return keyDescriptor.makeMap<V>();
}

export function GoMapClone<K, V>(map: GoMap<K, V>, keyDescriptor: GoMapKeyDescriptor<K>): GoMap<K, V> {
  if (GoMapIsNil(map)) return GoNilMap();
  const clone = GoMapMake<K, V>(keyDescriptor);
  for (const [key, value] of map) clone.set(key, value);
  return clone;
}

export function GoMapGetExisting<K, V>(map: NonNullable<GoMap<K, V>>, key: K): V {
  if (map.has(key)) return map.get(key)!;
  throw new TypeError("map key lookup is inconsistent with its entries");
}

export function GoMapLookup<K, V>(map: GoMap<K, V>, key: K, zeroValue: GoZeroFactory<V>): [V, bool] {
  if (!map.has(key)) {
    return [zeroValue(), false];
  }
  return [GoMapGetExisting(map, key), true];
}
