// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-compat","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/compat.ts","contentHash":"eab94e609a324a9944483ec423a064802a2e7d72f8990db98b962068be127edd"}

import type { bool, int } from "./scalars.js";

declare const __goBrand: unique symbol;

export type GoPtr<T> = T | undefined;
export type GoRef<T> = { v: T };
export type GoSlice<T> = T[];
export type GoArray<T, Length extends string> = T[] & { readonly [__goBrand]?: { readonly length: Length } };
export type GoMap<K, V> = Map<K, V>;
export type GoChan<T, Direction extends string = "bidirectional"> = { readonly [__goBrand]?: { readonly element: T; readonly direction: Direction } };
export type GoSeq<T> = (yieldValue: (value: T) => bool) => void;
export type GoSeq2<K, V> = (yieldValue: (key: K, value: V) => bool) => void;
export type GoError = Error | undefined;
export type GoComparable = unknown;
export type GoOrdered = string | number | bigint | bool;
export type GoConstraint<Text extends string> = unknown;
export type GoUnresolved<Name extends string> = { readonly [__goBrand]: { readonly unresolved: Name } };
export type GoUnsupported<Text extends string> = { readonly [__goBrand]: { readonly unsupported: Text } };
export type GoComplex64 = { readonly real: number; readonly imag: number };
export type GoComplex128 = { readonly real: number; readonly imag: number };
export type GoUnsafePointer = GoPtr<unknown>;
export type GoRune = int;

const goObjectIds = new WeakMap<object, number>();
let nextGoObjectId = 1;

export class GoStructMap<K, V> implements Map<K, V> {
  readonly [Symbol.toStringTag] = "Map";
  private readonly entriesByKey = new globalThis.Map<string, { key: K; value: V }>();

  get size(): number {
    return this.entriesByKey.size;
  }

  clear(): void {
    this.entriesByKey.clear();
  }

  delete(key: K): boolean {
    return this.entriesByKey.delete(goStructMapKey(key));
  }

  forEach(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: unknown): void {
    for (const entry of this.entriesByKey.values()) {
      callbackfn.call(thisArg, entry.value, entry.key, this as unknown as Map<K, V>);
    }
  }

  get(key: K): V | undefined {
    return this.entriesByKey.get(goStructMapKey(key))?.value;
  }

  getOrInsert(key: K, value: V): V {
    const keyText = goStructMapKey(key);
    const existing = this.entriesByKey.get(keyText);
    if (existing !== undefined) {
      return existing.value;
    }
    this.entriesByKey.set(keyText, { key, value });
    return value;
  }

  getOrInsertComputed(key: K, callbackfn: (key: K) => V): V {
    const keyText = goStructMapKey(key);
    const existing = this.entriesByKey.get(keyText);
    if (existing !== undefined) {
      return existing.value;
    }
    const value = callbackfn(key);
    this.entriesByKey.set(keyText, { key, value });
    return value;
  }

  has(key: K): boolean {
    return this.entriesByKey.has(goStructMapKey(key));
  }

  set(key: K, value: V): this {
    this.entriesByKey.set(goStructMapKey(key), { key, value });
    return this;
  }

  load(key: K): [V | undefined, boolean] {
    const entry = this.entriesByKey.get(goStructMapKey(key));
    if (entry === undefined) {
      return [undefined, false];
    }
    return [entry.value, true];
  }

  loadOrStore(key: K, value: V): [V, boolean] {
    const keyText = goStructMapKey(key);
    const existing = this.entriesByKey.get(keyText);
    if (existing !== undefined) {
      return [existing.value, true];
    }
    this.entriesByKey.set(keyText, { key, value });
    return [value, false];
  }

  loadAndDelete(key: K): [V | undefined, boolean] {
    const keyText = goStructMapKey(key);
    const existing = this.entriesByKey.get(keyText);
    if (existing === undefined) {
      return [undefined, false];
    }
    this.entriesByKey.delete(keyText);
    return [existing.value, true];
  }

  *entries(): MapIterator<[K, V]> {
    for (const entry of this.entriesByKey.values()) {
      yield [entry.key, entry.value];
    }
  }

  *keys(): MapIterator<K> {
    for (const entry of this.entriesByKey.values()) {
      yield entry.key;
    }
  }

  *values(): MapIterator<V> {
    for (const entry of this.entriesByKey.values()) {
      yield entry.value;
    }
  }

  [Symbol.iterator](): MapIterator<[K, V]> {
    return this.entries();
  }
}

export function NewGoStructMap<K, V>(): GoStructMap<K, V> {
  return new GoStructMap<K, V>();
}

export function GoAppend<T>(slice: GoPtr<GoSlice<T>>, ...items: GoSlice<T>): GoSlice<T> {
  return [...(slice ?? []), ...items];
}

function goStructMapKey(value: unknown): string {
  return goValueKey(value, true);
}

function goValueKey(value: unknown, topLevelStruct: boolean): string {
  if (value === undefined || value === null) {
    return "nil";
  }
  const valueType = typeof value;
  switch (valueType) {
    case "boolean":
    case "number":
    case "bigint":
    case "string":
      return `${valueType}:${String(value)}`;
    case "symbol":
      return `symbol:${String(value)}`;
    case "function":
      return `ref:${goObjectId(value)}`;
    case "object":
      break;
    default:
      return `${valueType}:${String(value)}`;
  }

  const objectValue = value as Record<PropertyKey, unknown>;
  if (isUint128Like(objectValue)) {
    return `u128:${objectValue.Hi!.toString()}:${objectValue.Lo!.toString()}`;
  }
  if (!topLevelStruct) {
    if (isValueStruct(objectValue)) {
      return goStructFieldsKey(objectValue);
    }
    return `ref:${goObjectId(objectValue)}`;
  }
  return goStructFieldsKey(objectValue);
}

function goStructFieldsKey(value: Record<PropertyKey, unknown>): string {
  if (globalThis.Array.isArray(value)) {
    let result = "array:[";
    for (let index = 0; index < value.length; index++) {
      if (index > 0) {
        result += ",";
      }
      result += goValueKey(value[index], false);
    }
    return result + "]";
  }
  const keys = globalThis.Object.keys(value).sort();
  let result = "struct:{";
  for (let index = 0; index < keys.length; index++) {
    if (index > 0) {
      result += ",";
    }
    const key = keys[index]!;
    result += `${key}=${goValueKey(value[key], false)}`;
  }
  return result + "}";
}

function isUint128Like(value: Record<PropertyKey, unknown>): boolean {
  return typeof value.Hi === "bigint" && typeof value.Lo === "bigint";
}

function isValueStruct(value: Record<PropertyKey, unknown>): boolean {
  if (isUint128Like(value)) {
    return true;
  }
  if (typeof value.Negative === "boolean" && typeof value.Base10Value === "string") {
    return true;
  }
  if (typeof value.pos === "number" && typeof value.end === "number") {
    return true;
  }
  return false;
}

function goObjectId(value: object): number {
  let id = goObjectIds.get(value);
  if (id === undefined) {
    id = nextGoObjectId++;
    goObjectIds.set(value, id);
  }
  return id;
}
