// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/context.ts","contentHash":"b53619b71661ebba82b49635f25f7bf59b7d379de9d6aa0da75fd62ed19485ce"}

import type { GoError } from "./compat.js";

export function Background(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED context.Background");
}

export const Canceled: unknown = undefined as never;

export type CancelFunc = () => void;

export interface Context {
  Err(): GoError;
  Value(key: unknown): unknown;
}

export const flags: unknown = undefined as never;

export function getChildContext(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED context.getChildContext");
}

export const inferences: unknown = undefined as never;

export const inferredTypeParameters: unknown = undefined as never;

export const IsRetrigger: unknown = undefined as never;

export const mapper: unknown = undefined as never;

export const nonFixingMapper: unknown = undefined as never;

export const parent: unknown = undefined as never;

export const propertyName: unknown = undefined as never;

export const resolvedProperties: unknown = undefined as never;

export const returnMapper: unknown = undefined as never;

export const siblings: unknown = undefined as never;

export const signature: unknown = undefined as never;

export const thisParameter: unknown = undefined as never;

export function TODO(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED context.TODO");
}

export const TriggerCharacter: unknown = undefined as never;

export const TriggerKind: unknown = undefined as never;

export const typeParameters: unknown = undefined as never;

export const widenedTypes: unknown = undefined as never;

export function WithCancel(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED context.WithCancel");
}

export function WithCancelCause(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED context.WithCancelCause");
}

export function WithValue(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED context.WithValue");
}
