// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/encoding.ts","contentHash":"60a8025e68adabab5e75dd70cfa9052779e9b7ea4937d759b99d2eff36a55be8"}

export const TextMarshaler: unknown = undefined as never;
