// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/errors.ts","contentHash":"841e32118a5b1a28ccfe784cdd928281a5eafee3c4e29b6b151a70adf5f46948"}

export const AsType: unknown = undefined as never;

export function Is(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED errors.Is");
}

export function New(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED errors.New");
}
