// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/flag.ts","contentHash":"fb461ff9e95f310727293f1abc4891b2944959b1983d46d058f4d2f09667c755"}

export function Bool(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED flag.Bool");
}

export const CommandLine: unknown = undefined as never;

export const ContinueOnError: unknown = undefined as never;

export function NewFlagSet(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED flag.NewFlagSet");
}

export function Parse(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED flag.Parse");
}

export function String(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED flag.String");
}

export function Usage(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED flag.Usage");
}
