// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/iter.ts","contentHash":"8aba5aecc8f50bfb9e62d3ba05d9c212c628aa3217fed368d053a2ef782cdd46"}

import type { bool } from "./scalars.js";
import type { GoFunc } from "./compat.js";

export type Seq<V> = (GoFunc<(yield_: GoFunc<(arg0: V) => bool>) => void>) & { readonly "__goDefinedType::iter::type::Seq::1a3590520c18886a1073f5a4249a7b31762a93e8733d9ad959c0b702627eee70": never };

export type Seq2<K, V> = (GoFunc<(yield_: GoFunc<(arg0: K, arg1: V) => bool>) => void>) & { readonly "__goDefinedType::iter::type::Seq2::7a948b3bbf7c71e720f64d645d9918748e61add0f9bd68829597d38a48f0bbac": never };
