// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/iter.ts","contentHash":"207c52c09b271b2e17a2a00ee1d09eed8118172cd21ecc128606afb88592aa51"}

export const Seq: unknown = undefined as never;

export const Seq2: unknown = undefined as never;
