// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/iter.ts","contentHash":"ea1db51987dddd0b6d7ccec2d46e191dbabbbe63503c56f33751b8d77f33a08d"}

import type { bool } from "./scalars.js";
import type { GoDefined, GoFunc } from "./compat.js";

export type Seq<V> = GoDefined<GoFunc<(yield_: GoFunc<(arg0: V) => bool>) => void>, "__goDefinedType::iter::type::Seq::ce749adf94d21b370bc4bfc7fa49f823530039fc0fd7925732cfb1ac1c27a04f">;

export type Seq2<K, V> = GoDefined<GoFunc<(yield_: GoFunc<(arg0: K, arg1: V) => bool>) => void>, "__goDefinedType::iter::type::Seq2::bd84fbe52024373a8c8d4a1d23f0db211642bd6bd32e6f783ef945b096cb4df2">;
