// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/os.ts","contentHash":"1aeb17d6735b4722b918ea986da741a3df2cb273a9a1aabc6e49080bf053ffa4"}

export const Args: unknown = undefined as never;

export function Chtimes(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Chtimes");
}

export function Create(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Create");
}

export function DirFS(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.DirFS");
}

export function Environ(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Environ");
}

export function Executable(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Executable");
}

export function Exit(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Exit");
}

export interface File {
  readonly __goFacadeName: "os.File";
}

export function Getenv(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Getenv");
}

export function Getpid(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Getpid");
}

export function Getwd(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Getwd");
}

export const Interrupt: unknown = undefined as never;

export function IsNotExist(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.IsNotExist");
}

export function MkdirAll(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.MkdirAll");
}

export const O_APPEND: unknown = undefined as never;

export const O_CREATE: unknown = undefined as never;

export const O_TRUNC: unknown = undefined as never;

export const O_WRONLY: unknown = undefined as never;

export function Open(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Open");
}

export function OpenFile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.OpenFile");
}

export const PathError: unknown = undefined as never;

export function ReadDir(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.ReadDir");
}

export function ReadFile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.ReadFile");
}

export function Remove(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Remove");
}

export function RemoveAll(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.RemoveAll");
}

export function Stat(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Stat");
}

export const Stderr: unknown = undefined as never;

export const Stdin: unknown = undefined as never;

export const Stdout: unknown = undefined as never;

export function Symlink(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.Symlink");
}

export function TempDir(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.TempDir");
}

export function UserCacheDir(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.UserCacheDir");
}

export function UserHomeDir(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.UserHomeDir");
}

export function WriteFile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED os.WriteFile");
}
