// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/reflect.ts","contentHash":"29fe771423185ec1c42623cb57ef03d1edc7a80877d3785af937abfe221b2dd0"}

export function Append(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.Append");
}

export const Array: unknown = undefined as never;

export const Bool: unknown = undefined as never;

export function DeepEqual(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.DeepEqual");
}

export const Float64: unknown = undefined as never;

export const Int: unknown = undefined as never;

export const Int16: unknown = undefined as never;

export const Int32: unknown = undefined as never;

export const Int64: unknown = undefined as never;

export const Int8: unknown = undefined as never;

export function MakeSlice(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.MakeSlice");
}

export const Map: unknown = undefined as never;

export const Pointer: unknown = undefined as never;

export const Slice: unknown = undefined as never;

export const String: unknown = undefined as never;

export const Struct: unknown = undefined as never;

export interface StructField {
  readonly __goFacadeName: "reflect.StructField";
}

export interface Type {
  readonly __goFacadeName: "reflect.Type";
}

export const TypeAssert: unknown = undefined as never;

export const TypeFor: unknown = undefined as never;

export function TypeOf(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.TypeOf");
}

export const Uint: unknown = undefined as never;

export const Uint16: unknown = undefined as never;

export const Uint32: unknown = undefined as never;

export const Uint64: unknown = undefined as never;

export const Uint8: unknown = undefined as never;

export const Uintptr: unknown = undefined as never;

export interface Value {
  readonly __goFacadeName: "reflect.Value";
}

export function ValueOf(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.ValueOf");
}

export function VisibleFields(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.VisibleFields");
}

export function Zero(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED reflect.Zero");
}
