// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/regexp.ts","contentHash":"28ac199c3e2d34689253d74003119600c691a16d036a63522d1862cbcbd6bf77"}

import type { bool } from "@tsonic/core/types.js";

export function Compile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED regexp.Compile");
}

export function MustCompile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED regexp.MustCompile");
}

export class Regexp {
  MatchString(s: string): bool {
    throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED regexp.Regexp.MatchString");
  }
}
