// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/runtime.ts","contentHash":"0692c72aec86b0fb5e59e4317ba73dab92974790183edf93fd2e814f08357ab0"}

export function Caller(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime.Caller");
}

export function Callers(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime.Callers");
}

export function CallersFrames(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime.CallersFrames");
}

export function GC(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime.GC");
}

export const GOARCH: unknown = undefined as never;

export function GOMAXPROCS(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime.GOMAXPROCS");
}

export const GOOS: unknown = undefined as never;

export interface MemStats {
  readonly __goFacadeName: "runtime.MemStats";
}

export function ReadMemStats(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime.ReadMemStats");
}
