// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-scalars","generator":"porter:facades","sourceRevision":"d35cc5f485640a41fbbf5a2267e9b11c7a7db4dc","path":"go/scalars.ts","contentHash":"d39f20c5b02f6ab07f59afcff564080daaf0c2676bbd59000e1b0c18da3c70b9"}

export type bool = boolean;
export type byte = number;
export type double = number;
export type float = number;
export type int = number;
export type long = number;
export type nint = number;
export type nuint = number;
export type sbyte = number;
export type short = number;
export type uint = number;
export type ulong = bigint;
export type ushort = number;
