// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"c78d39e7075b4fc641b12b1f35d905c54cdc13ef","path":"go/syscall.ts","contentHash":"c37420f0e0997afc7b69ddda3bd5d417c209d4e039d8c1c8b5b132eee8bbda1b"}

export function CloseHandle(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.CloseHandle");
}

export const EINTR: unknown = undefined as never;

export const ENOTDIR: unknown = undefined as never;

export const EPERM: unknown = undefined as never;

export interface Errno {
  readonly __goFacadeName: "syscall.Errno";
}

export const FILE_ATTRIBUTE_REPARSE_POINT: unknown = undefined as never;

export function GetFileAttributesEx(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.GetFileAttributesEx");
}

export const GetFileExInfoStandard: unknown = undefined as never;

export function OpenProcess(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.OpenProcess");
}

export const SIGINT: unknown = undefined as never;

export function Signal(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.Signal");
}

export const SIGTERM: unknown = undefined as never;

export function UTF16PtrFromString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.UTF16PtrFromString");
}

export function UTF16ToString(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.UTF16ToString");
}

export function WaitForSingleObject(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED syscall.WaitForSingleObject");
}

export const Win32FileAttributeData: unknown = undefined as never;
