// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"d35cc5f485640a41fbbf5a2267e9b11c7a7db4dc","path":"go/syscall.ts","contentHash":"acd6070bb235d591ffd6c1f272bcb2b9d8cbd72162a5b12c7b557e889a3a1fb9"}

export const SIGINT = "SIGINT";

export const SIGTERM = "SIGTERM";
