// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"168e7015edf98244febc8f4ae450b673b5d195d7","path":"go/syscall.ts","contentHash":"69bd3a7e3a0e897c577de7beeb05296ae8afedf21f97540bb4327581262bea3f"}

export const SIGINT = "SIGINT";

export const SIGTERM = "SIGTERM";

export interface Win32FileAttributeData {
  readonly __goFacadeName: "syscall.Win32FileAttributeData";
}
