// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/testing.ts","contentHash":"92cb9193231e725c1354e3942ecf85fc2bcebbf4e8b4e828812f6b593a767883"}

export function AllocsPerRun(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED testing.AllocsPerRun");
}

export class B {
  readonly __tsgoEmpty?: never;
}

export interface F {
  readonly __goFacadeName: "testing.F";
}

export class M {
  readonly __tsgoEmpty?: never;
}

export const PB: unknown = undefined as never;

export class T {
  readonly __tsgoEmpty?: never;
}

export interface TB {
  readonly __tsgoEmpty?: never;
}

export function Testing(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED testing.Testing");
}
