// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/time.ts","contentHash":"f7ac8b12a494e1f787a53fd29d8448bd8665674d79c5c85a656e3dc8f022aaea"}

import type { long } from "@tsonic/core/types.js";

export function After(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.After");
}

export function AfterFunc(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.AfterFunc");
}

export type Duration = long;

export const Millisecond: unknown = undefined as never;

export const Minute: unknown = undefined as never;

export function NewTicker(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.NewTicker");
}

export function NewTimer(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.NewTimer");
}

export function Now(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.Now");
}

export const Second: unknown = undefined as never;

export function Since(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.Since");
}

export function Sleep(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.Sleep");
}

export class Time {
  readonly __tsgoEmpty?: never;
}

export interface Timer {
  readonly __goFacadeName: "time.Timer";
}

export function Unix(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.Unix");
}

export function UnixMilli(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED time.UnixMilli");
}
