// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/unicode.ts","contentHash":"d5ad2e4e34531c3f7a342b71b2e1032647546c484366d6bc85a063727b177b33"}

export function Is(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.Is");
}

export function IsDigit(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.IsDigit");
}

export function IsLetter(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.IsLetter");
}

export function IsLower(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.IsLower");
}

export function IsSpace(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.IsSpace");
}

export function IsUpper(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.IsUpper");
}

export const MaxASCII: unknown = undefined as never;

export function ToLower(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.ToLower");
}

export function ToUpper(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED unicode.ToUpper");
}

export const Zs: unknown = undefined as never;
