// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"d35cc5f485640a41fbbf5a2267e9b11c7a7db4dc","path":"go/golang.org/x/tools/go/ast/inspector.ts","contentHash":"a08e533ef8356236ac46ba0ca4bc14aa678bd91eb6cf4917f0bd30208ac81e43"}

export interface Inspector {
  readonly __goFacadeName: "golang.org/x/tools/go/ast/inspector.Inspector";
}
