// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/go/ast.ts","contentHash":"7bdce10e71b0d177c378aed783011484c3027bf7a98c8af66554d384f5909873"}

export const ArrayType: unknown = undefined as never;

export const AssignStmt: unknown = undefined as never;

export const BasicLit: unknown = undefined as never;

export const BinaryExpr: unknown = undefined as never;

export interface BlockStmt {
  readonly __goFacadeName: "go/ast.BlockStmt";
}

export interface CallExpr {
  readonly __goFacadeName: "go/ast.CallExpr";
}

export const CaseClause: unknown = undefined as never;

export const ChanType: unknown = undefined as never;

export const CommClause: unknown = undefined as never;

export interface CommentGroup {
  readonly __goFacadeName: "go/ast.CommentGroup";
}

export const Ellipsis: unknown = undefined as never;

export interface Expr {
  readonly __goFacadeName: "go/ast.Expr";
}

export interface Field {
  readonly __goFacadeName: "go/ast.Field";
}

export interface FieldList {
  readonly __goFacadeName: "go/ast.FieldList";
}

export interface File {
  readonly __goFacadeName: "go/ast.File";
}

export interface FuncDecl {
  readonly __goFacadeName: "go/ast.FuncDecl";
}

export interface FuncLit {
  readonly __goFacadeName: "go/ast.FuncLit";
}

export interface FuncType {
  readonly __goFacadeName: "go/ast.FuncType";
}

export const GenDecl: unknown = undefined as never;

export interface Ident {
  readonly __goFacadeName: "go/ast.Ident";
}

export const IndexExpr: unknown = undefined as never;

export const IndexListExpr: unknown = undefined as never;

export function Inspect(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED go/ast.Inspect");
}

export const InterfaceType: unknown = undefined as never;

export const MapType: unknown = undefined as never;

export interface Node {
  readonly __goFacadeName: "go/ast.Node";
}

export const ParenExpr: unknown = undefined as never;

export const SelectorExpr: unknown = undefined as never;

export const SelectStmt: unknown = undefined as never;

export const StarExpr: unknown = undefined as never;

export interface Stmt {
  readonly __goFacadeName: "go/ast.Stmt";
}

export const StructType: unknown = undefined as never;

export const SwitchStmt: unknown = undefined as never;

export interface TypeSpec {
  readonly __goFacadeName: "go/ast.TypeSpec";
}

export const UnaryExpr: unknown = undefined as never;

export interface ValueSpec {
  readonly __goFacadeName: "go/ast.ValueSpec";
}
