// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/go/token.ts","contentHash":"cdab6ad46ec4cf3cfe3b6169c0b13349a9fe81d104235a59f87cb62fe4c344a7"}

export const AND_ASSIGN: unknown = undefined as never;

export const DEFINE: unknown = undefined as never;

export function IsExported(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED go/token.IsExported");
}

export function IsIdentifier(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED go/token.IsIdentifier");
}

export const NoPos: unknown = undefined as never;

export interface Pos {
  readonly __goFacadeName: "go/token.Pos";
}

export interface Position {
  readonly __goFacadeName: "go/token.Position";
}

export const VAR: unknown = undefined as never;

export const XOR: unknown = undefined as never;
