/**
 * Fourslash test utility helpers.
 *
 * Porting surface for TS-Go `internal/fourslash/tests/util/util.go`.
 */

import { newFourslash, type FourslashCapabilities, type FourslashTest } from "../../fourslash.js";

export interface FourslashFixture {
  readonly name: string;
  readonly content: string;
  readonly capabilities?: FourslashCapabilities;
}

export function createFourslashFixture(fixture: FourslashFixture): FourslashTest {
  return newFourslash(fixture.content, fixture.capabilities ?? {}, `${fixture.name}.ts`);
}

export function fixtureWithMarker(name: string, source: string, marker = "marker"): FourslashFixture {
  return {
    name,
    content: source.includes("/*")
      ? source
      : `${source}\n/*${marker}*/`,
  };
}

export function assertMarker(fixture: FourslashTest, name: string): void {
  fixture.marker(name);
}

export function assertRangeText(fixture: FourslashTest, text: string): void {
  fixture.rangeByText(text);
}

// Source parity map: internal/fourslash/tests/util/util.go
/**
 * Source parity map for TS-Go `fourslash/tests/util/util.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

const fourslashTestsUtilUtilUpstreamPath = "fourslash/tests/util/util.go";

const fourslashTestsUtilUtilDeclarations: readonly UpstreamDeclaration[] = [
  {"line":14,"kind":"var","name":"Ignored"},
  {"line":16,"kind":"var","name":"DefaultCommitCharacters"},
  {"line":18,"kind":"var","name":"CompletionGlobalThisItem"},
  {"line":24,"kind":"var","name":"CompletionUndefinedVarItem"},
  {"line":30,"kind":"var","name":"CompletionGlobalVars"},
  {"line":245,"kind":"var","name":"CompletionGlobalKeywords"},
  {"line":573,"kind":"var","name":"CompletionGlobalTypeDecls"},
  {"line":1172,"kind":"var","name":"CompletionTypeKeywords"},
  {"line":1275,"kind":"var","name":"CompletionClassElementKeywords"},
  {"line":1343,"kind":"var","name":"CompletionClassElementInJSKeywords"},
  {"line":1345,"kind":"var","name":"CompletionGlobals"},
  {"line":1354,"kind":"func","name":"sortCompletionItems"},
  {"line":1400,"kind":"func","name":"CompletionGlobalsPlus"},
  {"line":1414,"kind":"func","name":"CompletionGlobalTypesPlus"},
  {"line":1423,"kind":"var","name":"CompletionGlobalTypes"},
  {"line":1425,"kind":"func","name":"getInJSKeywords"},
  {"line":1449,"kind":"var","name":"CompletionGlobalInJSKeywords"},
  {"line":1451,"kind":"func","name":"CompletionGlobalsInJSPlus"},
  {"line":1463,"kind":"var","name":"CompletionConstructorParameterKeywords"},
  {"line":1491,"kind":"var","name":"CompletionFunctionMembers"},
  {"line":1522,"kind":"func","name":"CompletionFunctionMembersPlus"},
  {"line":1531,"kind":"var","name":"CompletionFunctionMembersWithPrototype"},
  {"line":1541,"kind":"func","name":"CompletionFunctionMembersWithPrototypePlus"},
  {"line":1550,"kind":"func","name":"CompletionTypeKeywordsPlus"},
  {"line":1559,"kind":"var","name":"CompletionTypeAssertionKeywords"},
];

const fourslashTestsUtilUtilSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package fourslash_test"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"fmt\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/fourslash\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/ls\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"line":12,"text":")"},
  {"line":14,"text":"var Ignored = struct{}{}"},
  {"line":16,"text":"var DefaultCommitCharacters = []string{\".\", \",\", \";\"}"},
  {"line":18,"text":"var CompletionGlobalThisItem = &lsproto.CompletionItem{"},
  {"line":19,"text":"\tLabel:    \"globalThis\","},
  {"line":20,"text":"\tKind:     new(lsproto.CompletionItemKindModule),"},
  {"line":21,"text":"\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":22,"text":"}"},
  {"line":24,"text":"var CompletionUndefinedVarItem = &lsproto.CompletionItem{"},
  {"line":25,"text":"\tLabel:    \"undefined\","},
  {"line":26,"text":"\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":27,"text":"\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":28,"text":"}"},
  {"line":30,"text":"var CompletionGlobalVars = []fourslash.CompletionsExpectedItem{"},
  {"line":31,"text":"\t&lsproto.CompletionItem{"},
  {"line":32,"text":"\t\tLabel:    \"Array\","},
  {"line":33,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":34,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":35,"text":"\t},"},
  {"line":36,"text":"\t&lsproto.CompletionItem{"},
  {"line":37,"text":"\t\tLabel:    \"ArrayBuffer\","},
  {"line":38,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":39,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":40,"text":"\t},"},
  {"line":41,"text":"\t&lsproto.CompletionItem{"},
  {"line":42,"text":"\t\tLabel:    \"Boolean\","},
  {"line":43,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":44,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":45,"text":"\t},"},
  {"line":46,"text":"\t&lsproto.CompletionItem{"},
  {"line":47,"text":"\t\tLabel:    \"DataView\","},
  {"line":48,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":49,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":50,"text":"\t},"},
  {"line":51,"text":"\t&lsproto.CompletionItem{"},
  {"line":52,"text":"\t\tLabel:    \"Date\","},
  {"line":53,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":54,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":55,"text":"\t},"},
  {"line":56,"text":"\t&lsproto.CompletionItem{"},
  {"line":57,"text":"\t\tLabel:    \"Error\","},
  {"line":58,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":59,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":60,"text":"\t},"},
  {"line":61,"text":"\t&lsproto.CompletionItem{"},
  {"line":62,"text":"\t\tLabel:    \"EvalError\","},
  {"line":63,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":64,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":65,"text":"\t},"},
  {"line":66,"text":"\t&lsproto.CompletionItem{"},
  {"line":67,"text":"\t\tLabel:    \"Float32Array\","},
  {"line":68,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":69,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":70,"text":"\t},"},
  {"line":71,"text":"\t&lsproto.CompletionItem{"},
  {"line":72,"text":"\t\tLabel:    \"Float64Array\","},
  {"line":73,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":74,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":75,"text":"\t},"},
  {"line":76,"text":"\t&lsproto.CompletionItem{"},
  {"line":77,"text":"\t\tLabel:    \"Function\","},
  {"line":78,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":79,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":80,"text":"\t},"},
  {"line":81,"text":"\t&lsproto.CompletionItem{"},
  {"line":82,"text":"\t\tLabel:    \"Infinity\","},
  {"line":83,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":84,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":85,"text":"\t},"},
  {"line":86,"text":"\t&lsproto.CompletionItem{"},
  {"line":87,"text":"\t\tLabel:    \"Int16Array\","},
  {"line":88,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":89,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":90,"text":"\t},"},
  {"line":91,"text":"\t&lsproto.CompletionItem{"},
  {"line":92,"text":"\t\tLabel:    \"Int32Array\","},
  {"line":93,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":94,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":95,"text":"\t},"},
  {"line":96,"text":"\t&lsproto.CompletionItem{"},
  {"line":97,"text":"\t\tLabel:    \"Int8Array\","},
  {"line":98,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":99,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":100,"text":"\t},"},
  {"line":101,"text":"\t&lsproto.CompletionItem{"},
  {"line":102,"text":"\t\tLabel:    \"Intl\","},
  {"line":103,"text":"\t\tKind:     new(lsproto.CompletionItemKindModule),"},
  {"line":104,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":105,"text":"\t},"},
  {"line":106,"text":"\t&lsproto.CompletionItem{"},
  {"line":107,"text":"\t\tLabel:    \"JSON\","},
  {"line":108,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":109,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":110,"text":"\t},"},
  {"line":111,"text":"\t&lsproto.CompletionItem{"},
  {"line":112,"text":"\t\tLabel:    \"Math\","},
  {"line":113,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":114,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":115,"text":"\t},"},
  {"line":116,"text":"\t&lsproto.CompletionItem{"},
  {"line":117,"text":"\t\tLabel:    \"NaN\","},
  {"line":118,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":119,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":120,"text":"\t},"},
  {"line":121,"text":"\t&lsproto.CompletionItem{"},
  {"line":122,"text":"\t\tLabel:    \"Number\","},
  {"line":123,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":124,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":125,"text":"\t},"},
  {"line":126,"text":"\t&lsproto.CompletionItem{"},
  {"line":127,"text":"\t\tLabel:    \"Object\","},
  {"line":128,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":129,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":130,"text":"\t},"},
  {"line":131,"text":"\t&lsproto.CompletionItem{"},
  {"line":132,"text":"\t\tLabel:    \"RangeError\","},
  {"line":133,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":134,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":135,"text":"\t},"},
  {"line":136,"text":"\t&lsproto.CompletionItem{"},
  {"line":137,"text":"\t\tLabel:    \"ReferenceError\","},
  {"line":138,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":139,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":140,"text":"\t},"},
  {"line":141,"text":"\t&lsproto.CompletionItem{"},
  {"line":142,"text":"\t\tLabel:    \"RegExp\","},
  {"line":143,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":144,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":145,"text":"\t},"},
  {"line":146,"text":"\t&lsproto.CompletionItem{"},
  {"line":147,"text":"\t\tLabel:    \"String\","},
  {"line":148,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":149,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":150,"text":"\t},"},
  {"line":151,"text":"\t&lsproto.CompletionItem{"},
  {"line":152,"text":"\t\tLabel:    \"SyntaxError\","},
  {"line":153,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":154,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":155,"text":"\t},"},
  {"line":156,"text":"\t&lsproto.CompletionItem{"},
  {"line":157,"text":"\t\tLabel:    \"TypeError\","},
  {"line":158,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":159,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":160,"text":"\t},"},
  {"line":161,"text":"\t&lsproto.CompletionItem{"},
  {"line":162,"text":"\t\tLabel:    \"URIError\","},
  {"line":163,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":164,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":165,"text":"\t},"},
  {"line":166,"text":"\t&lsproto.CompletionItem{"},
  {"line":167,"text":"\t\tLabel:    \"Uint16Array\","},
  {"line":168,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":169,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":170,"text":"\t},"},
  {"line":171,"text":"\t&lsproto.CompletionItem{"},
  {"line":172,"text":"\t\tLabel:    \"Uint32Array\","},
  {"line":173,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":174,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":175,"text":"\t},"},
  {"line":176,"text":"\t&lsproto.CompletionItem{"},
  {"line":177,"text":"\t\tLabel:    \"Uint8Array\","},
  {"line":178,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":179,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":180,"text":"\t},"},
  {"line":181,"text":"\t&lsproto.CompletionItem{"},
  {"line":182,"text":"\t\tLabel:    \"Uint8ClampedArray\","},
  {"line":183,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":184,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":185,"text":"\t},"},
  {"line":186,"text":"\t&lsproto.CompletionItem{"},
  {"line":187,"text":"\t\tLabel:    \"decodeURI\","},
  {"line":188,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":189,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":190,"text":"\t},"},
  {"line":191,"text":"\t&lsproto.CompletionItem{"},
  {"line":192,"text":"\t\tLabel:    \"decodeURIComponent\","},
  {"line":193,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":194,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":195,"text":"\t},"},
  {"line":196,"text":"\t&lsproto.CompletionItem{"},
  {"line":197,"text":"\t\tLabel:    \"encodeURI\","},
  {"line":198,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":199,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":200,"text":"\t},"},
  {"line":201,"text":"\t&lsproto.CompletionItem{"},
  {"line":202,"text":"\t\tLabel:    \"encodeURIComponent\","},
  {"line":203,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":204,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":205,"text":"\t},"},
  {"line":206,"text":"\t&lsproto.CompletionItem{"},
  {"line":207,"text":"\t\tLabel:    \"eval\","},
  {"line":208,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":209,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":210,"text":"\t},"},
  {"line":211,"text":"\t&lsproto.CompletionItem{"},
  {"line":212,"text":"\t\tLabel:    \"isFinite\","},
  {"line":213,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":214,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":215,"text":"\t},"},
  {"line":216,"text":"\t&lsproto.CompletionItem{"},
  {"line":217,"text":"\t\tLabel:    \"isNaN\","},
  {"line":218,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":219,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":220,"text":"\t},"},
  {"line":221,"text":"\t&lsproto.CompletionItem{"},
  {"line":222,"text":"\t\tLabel:    \"parseFloat\","},
  {"line":223,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":224,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":225,"text":"\t},"},
  {"line":226,"text":"\t&lsproto.CompletionItem{"},
  {"line":227,"text":"\t\tLabel:    \"parseInt\","},
  {"line":228,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":229,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":230,"text":"\t},"},
  {"line":231,"text":"\t&lsproto.CompletionItem{"},
  {"line":232,"text":"\t\tLabel:    \"escape\","},
  {"line":233,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":234,"text":"\t\tTags:     &[]lsproto.CompletionItemTag{lsproto.CompletionItemTagDeprecated},"},
  {"line":235,"text":"\t\tSortText: new(string(ls.DeprecateSortText(ls.SortTextGlobalsOrKeywords))),"},
  {"line":236,"text":"\t},"},
  {"line":237,"text":"\t&lsproto.CompletionItem{"},
  {"line":238,"text":"\t\tLabel:    \"unescape\","},
  {"line":239,"text":"\t\tKind:     new(lsproto.CompletionItemKindFunction),"},
  {"line":240,"text":"\t\tTags:     &[]lsproto.CompletionItemTag{lsproto.CompletionItemTagDeprecated},"},
  {"line":241,"text":"\t\tSortText: new(string(ls.DeprecateSortText(ls.SortTextGlobalsOrKeywords))),"},
  {"line":242,"text":"\t},"},
  {"line":243,"text":"}"},
  {"line":245,"text":"var CompletionGlobalKeywords = []fourslash.CompletionsExpectedItem{"},
  {"line":246,"text":"\t&lsproto.CompletionItem{"},
  {"line":247,"text":"\t\tLabel:    \"abstract\","},
  {"line":248,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":249,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":250,"text":"\t},"},
  {"line":251,"text":"\t&lsproto.CompletionItem{"},
  {"line":252,"text":"\t\tLabel:    \"any\","},
  {"line":253,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":254,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":255,"text":"\t},"},
  {"line":256,"text":"\t&lsproto.CompletionItem{"},
  {"line":257,"text":"\t\tLabel:    \"as\","},
  {"line":258,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":259,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":260,"text":"\t},"},
  {"line":261,"text":"\t&lsproto.CompletionItem{"},
  {"line":262,"text":"\t\tLabel:    \"asserts\","},
  {"line":263,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":264,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":265,"text":"\t},"},
  {"line":266,"text":"\t&lsproto.CompletionItem{"},
  {"line":267,"text":"\t\tLabel:    \"async\","},
  {"line":268,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":269,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":270,"text":"\t},"},
  {"line":271,"text":"\t&lsproto.CompletionItem{"},
  {"line":272,"text":"\t\tLabel:    \"await\","},
  {"line":273,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":274,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":275,"text":"\t},"},
  {"line":276,"text":"\t&lsproto.CompletionItem{"},
  {"line":277,"text":"\t\tLabel:    \"bigint\","},
  {"line":278,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":279,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":280,"text":"\t},"},
  {"line":281,"text":"\t&lsproto.CompletionItem{"},
  {"line":282,"text":"\t\tLabel:    \"boolean\","},
  {"line":283,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":284,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":285,"text":"\t},"},
  {"line":286,"text":"\t&lsproto.CompletionItem{"},
  {"line":287,"text":"\t\tLabel:    \"break\","},
  {"line":288,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":289,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":290,"text":"\t},"},
  {"line":291,"text":"\t&lsproto.CompletionItem{"},
  {"line":292,"text":"\t\tLabel:    \"case\","},
  {"line":293,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":294,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":295,"text":"\t},"},
  {"line":296,"text":"\t&lsproto.CompletionItem{"},
  {"line":297,"text":"\t\tLabel:    \"catch\","},
  {"line":298,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":299,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":300,"text":"\t},"},
  {"line":301,"text":"\t&lsproto.CompletionItem{"},
  {"line":302,"text":"\t\tLabel:    \"class\","},
  {"line":303,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":304,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":305,"text":"\t},"},
  {"line":306,"text":"\t&lsproto.CompletionItem{"},
  {"line":307,"text":"\t\tLabel:    \"const\","},
  {"line":308,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":309,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":310,"text":"\t},"},
  {"line":311,"text":"\t&lsproto.CompletionItem{"},
  {"line":312,"text":"\t\tLabel:    \"continue\","},
  {"line":313,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":314,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":315,"text":"\t},"},
  {"line":316,"text":"\t&lsproto.CompletionItem{"},
  {"line":317,"text":"\t\tLabel:    \"debugger\","},
  {"line":318,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":319,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":320,"text":"\t},"},
  {"line":321,"text":"\t&lsproto.CompletionItem{"},
  {"line":322,"text":"\t\tLabel:    \"declare\","},
  {"line":323,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":324,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":325,"text":"\t},"},
  {"line":326,"text":"\t&lsproto.CompletionItem{"},
  {"line":327,"text":"\t\tLabel:    \"default\","},
  {"line":328,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":329,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":330,"text":"\t},"},
  {"line":331,"text":"\t&lsproto.CompletionItem{"},
  {"line":332,"text":"\t\tLabel:    \"delete\","},
  {"line":333,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":334,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":335,"text":"\t},"},
  {"line":336,"text":"\t&lsproto.CompletionItem{"},
  {"line":337,"text":"\t\tLabel:    \"do\","},
  {"line":338,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":339,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":340,"text":"\t},"},
  {"line":341,"text":"\t&lsproto.CompletionItem{"},
  {"line":342,"text":"\t\tLabel:    \"else\","},
  {"line":343,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":344,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":345,"text":"\t},"},
  {"line":346,"text":"\t&lsproto.CompletionItem{"},
  {"line":347,"text":"\t\tLabel:    \"enum\","},
  {"line":348,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":349,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":350,"text":"\t},"},
  {"line":351,"text":"\t&lsproto.CompletionItem{"},
  {"line":352,"text":"\t\tLabel:    \"export\","},
  {"line":353,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":354,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":355,"text":"\t},"},
  {"line":356,"text":"\t&lsproto.CompletionItem{"},
  {"line":357,"text":"\t\tLabel:    \"extends\","},
  {"line":358,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":359,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":360,"text":"\t},"},
  {"line":361,"text":"\t&lsproto.CompletionItem{"},
  {"line":362,"text":"\t\tLabel:    \"false\","},
  {"line":363,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":364,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":365,"text":"\t},"},
  {"line":366,"text":"\t&lsproto.CompletionItem{"},
  {"line":367,"text":"\t\tLabel:    \"finally\","},
  {"line":368,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":369,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":370,"text":"\t},"},
  {"line":371,"text":"\t&lsproto.CompletionItem{"},
  {"line":372,"text":"\t\tLabel:    \"for\","},
  {"line":373,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":374,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":375,"text":"\t},"},
  {"line":376,"text":"\t&lsproto.CompletionItem{"},
  {"line":377,"text":"\t\tLabel:    \"function\","},
  {"line":378,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":379,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":380,"text":"\t},"},
  {"line":381,"text":"\t&lsproto.CompletionItem{"},
  {"line":382,"text":"\t\tLabel:    \"if\","},
  {"line":383,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":384,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":385,"text":"\t},"},
  {"line":386,"text":"\t&lsproto.CompletionItem{"},
  {"line":387,"text":"\t\tLabel:    \"implements\","},
  {"line":388,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":389,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":390,"text":"\t},"},
  {"line":391,"text":"\t&lsproto.CompletionItem{"},
  {"line":392,"text":"\t\tLabel:    \"import\","},
  {"line":393,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":394,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":395,"text":"\t},"},
  {"line":396,"text":"\t&lsproto.CompletionItem{"},
  {"line":397,"text":"\t\tLabel:    \"in\","},
  {"line":398,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":399,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":400,"text":"\t},"},
  {"line":401,"text":"\t&lsproto.CompletionItem{"},
  {"line":402,"text":"\t\tLabel:    \"infer\","},
  {"line":403,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":404,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":405,"text":"\t},"},
  {"line":406,"text":"\t&lsproto.CompletionItem{"},
  {"line":407,"text":"\t\tLabel:    \"instanceof\","},
  {"line":408,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":409,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":410,"text":"\t},"},
  {"line":411,"text":"\t&lsproto.CompletionItem{"},
  {"line":412,"text":"\t\tLabel:    \"interface\","},
  {"line":413,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":414,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":415,"text":"\t},"},
  {"line":416,"text":"\t&lsproto.CompletionItem{"},
  {"line":417,"text":"\t\tLabel:    \"keyof\","},
  {"line":418,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":419,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":420,"text":"\t},"},
  {"line":421,"text":"\t&lsproto.CompletionItem{"},
  {"line":422,"text":"\t\tLabel:    \"let\","},
  {"line":423,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":424,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":425,"text":"\t},"},
  {"line":426,"text":"\t&lsproto.CompletionItem{"},
  {"line":427,"text":"\t\tLabel:    \"module\","},
  {"line":428,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":429,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":430,"text":"\t},"},
  {"line":431,"text":"\t&lsproto.CompletionItem{"},
  {"line":432,"text":"\t\tLabel:    \"namespace\","},
  {"line":433,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":434,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":435,"text":"\t},"},
  {"line":436,"text":"\t&lsproto.CompletionItem{"},
  {"line":437,"text":"\t\tLabel:    \"never\","},
  {"line":438,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":439,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":440,"text":"\t},"},
  {"line":441,"text":"\t&lsproto.CompletionItem{"},
  {"line":442,"text":"\t\tLabel:    \"new\","},
  {"line":443,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":444,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":445,"text":"\t},"},
  {"line":446,"text":"\t&lsproto.CompletionItem{"},
  {"line":447,"text":"\t\tLabel:    \"null\","},
  {"line":448,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":449,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":450,"text":"\t},"},
  {"line":451,"text":"\t&lsproto.CompletionItem{"},
  {"line":452,"text":"\t\tLabel:    \"number\","},
  {"line":453,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":454,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":455,"text":"\t},"},
  {"line":456,"text":"\t&lsproto.CompletionItem{"},
  {"line":457,"text":"\t\tLabel:    \"object\","},
  {"line":458,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":459,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":460,"text":"\t},"},
  {"line":461,"text":"\t&lsproto.CompletionItem{"},
  {"line":462,"text":"\t\tLabel:    \"package\","},
  {"line":463,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":464,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":465,"text":"\t},"},
  {"line":466,"text":"\t&lsproto.CompletionItem{"},
  {"line":467,"text":"\t\tLabel:    \"readonly\","},
  {"line":468,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":469,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":470,"text":"\t},"},
  {"line":471,"text":"\t&lsproto.CompletionItem{"},
  {"line":472,"text":"\t\tLabel:    \"return\","},
  {"line":473,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":474,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":475,"text":"\t},"},
  {"line":476,"text":"\t&lsproto.CompletionItem{"},
  {"line":477,"text":"\t\tLabel:    \"satisfies\","},
  {"line":478,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":479,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":480,"text":"\t},"},
  {"line":481,"text":"\t&lsproto.CompletionItem{"},
  {"line":482,"text":"\t\tLabel:    \"string\","},
  {"line":483,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":484,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":485,"text":"\t},"},
  {"line":486,"text":"\t&lsproto.CompletionItem{"},
  {"line":487,"text":"\t\tLabel:    \"super\","},
  {"line":488,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":489,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":490,"text":"\t},"},
  {"line":491,"text":"\t&lsproto.CompletionItem{"},
  {"line":492,"text":"\t\tLabel:    \"switch\","},
  {"line":493,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":494,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":495,"text":"\t},"},
  {"line":496,"text":"\t&lsproto.CompletionItem{"},
  {"line":497,"text":"\t\tLabel:    \"symbol\","},
  {"line":498,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":499,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":500,"text":"\t},"},
  {"line":501,"text":"\t&lsproto.CompletionItem{"},
  {"line":502,"text":"\t\tLabel:    \"this\","},
  {"line":503,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":504,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":505,"text":"\t},"},
  {"line":506,"text":"\t&lsproto.CompletionItem{"},
  {"line":507,"text":"\t\tLabel:    \"throw\","},
  {"line":508,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":509,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":510,"text":"\t},"},
  {"line":511,"text":"\t&lsproto.CompletionItem{"},
  {"line":512,"text":"\t\tLabel:    \"true\","},
  {"line":513,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":514,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":515,"text":"\t},"},
  {"line":516,"text":"\t&lsproto.CompletionItem{"},
  {"line":517,"text":"\t\tLabel:    \"try\","},
  {"line":518,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":519,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":520,"text":"\t},"},
  {"line":521,"text":"\t&lsproto.CompletionItem{"},
  {"line":522,"text":"\t\tLabel:    \"type\","},
  {"line":523,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":524,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":525,"text":"\t},"},
  {"line":526,"text":"\t&lsproto.CompletionItem{"},
  {"line":527,"text":"\t\tLabel:    \"typeof\","},
  {"line":528,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":529,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":530,"text":"\t},"},
  {"line":531,"text":"\t&lsproto.CompletionItem{"},
  {"line":532,"text":"\t\tLabel:    \"unique\","},
  {"line":533,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":534,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":535,"text":"\t},"},
  {"line":536,"text":"\t&lsproto.CompletionItem{"},
  {"line":537,"text":"\t\tLabel:    \"unknown\","},
  {"line":538,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":539,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":540,"text":"\t},"},
  {"line":541,"text":"\t&lsproto.CompletionItem{"},
  {"line":542,"text":"\t\tLabel:    \"using\","},
  {"line":543,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":544,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":545,"text":"\t},"},
  {"line":546,"text":"\t&lsproto.CompletionItem{"},
  {"line":547,"text":"\t\tLabel:    \"var\","},
  {"line":548,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":549,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":550,"text":"\t},"},
  {"line":551,"text":"\t&lsproto.CompletionItem{"},
  {"line":552,"text":"\t\tLabel:    \"void\","},
  {"line":553,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":554,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":555,"text":"\t},"},
  {"line":556,"text":"\t&lsproto.CompletionItem{"},
  {"line":557,"text":"\t\tLabel:    \"while\","},
  {"line":558,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":559,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":560,"text":"\t},"},
  {"line":561,"text":"\t&lsproto.CompletionItem{"},
  {"line":562,"text":"\t\tLabel:    \"with\","},
  {"line":563,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":564,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":565,"text":"\t},"},
  {"line":566,"text":"\t&lsproto.CompletionItem{"},
  {"line":567,"text":"\t\tLabel:    \"yield\","},
  {"line":568,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":569,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":570,"text":"\t},"},
  {"line":571,"text":"}"},
  {"line":573,"text":"var CompletionGlobalTypeDecls = []fourslash.CompletionsExpectedItem{"},
  {"line":574,"text":"\t&lsproto.CompletionItem{"},
  {"line":575,"text":"\t\tLabel:    \"Symbol\","},
  {"line":576,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":577,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":578,"text":"\t},"},
  {"line":579,"text":"\t&lsproto.CompletionItem{"},
  {"line":580,"text":"\t\tLabel:    \"PropertyKey\","},
  {"line":581,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":582,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":583,"text":"\t},"},
  {"line":584,"text":"\t&lsproto.CompletionItem{"},
  {"line":585,"text":"\t\tLabel:    \"PropertyDescriptor\","},
  {"line":586,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":587,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":588,"text":"\t},"},
  {"line":589,"text":"\t&lsproto.CompletionItem{"},
  {"line":590,"text":"\t\tLabel:    \"PropertyDescriptorMap\","},
  {"line":591,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":592,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":593,"text":"\t},"},
  {"line":594,"text":"\t&lsproto.CompletionItem{"},
  {"line":595,"text":"\t\tLabel:    \"Object\","},
  {"line":596,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":597,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":598,"text":"\t},"},
  {"line":599,"text":"\t&lsproto.CompletionItem{"},
  {"line":600,"text":"\t\tLabel:    \"ObjectConstructor\","},
  {"line":601,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":602,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":603,"text":"\t},"},
  {"line":604,"text":"\t&lsproto.CompletionItem{"},
  {"line":605,"text":"\t\tLabel:    \"Function\","},
  {"line":606,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":607,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":608,"text":"\t},"},
  {"line":609,"text":"\t&lsproto.CompletionItem{"},
  {"line":610,"text":"\t\tLabel:    \"FunctionConstructor\","},
  {"line":611,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":612,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":613,"text":"\t},"},
  {"line":614,"text":"\t&lsproto.CompletionItem{"},
  {"line":615,"text":"\t\tLabel:    \"ThisParameterType\","},
  {"line":616,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":617,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":618,"text":"\t},"},
  {"line":619,"text":"\t&lsproto.CompletionItem{"},
  {"line":620,"text":"\t\tLabel:    \"OmitThisParameter\","},
  {"line":621,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":622,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":623,"text":"\t},"},
  {"line":624,"text":"\t&lsproto.CompletionItem{"},
  {"line":625,"text":"\t\tLabel:    \"CallableFunction\","},
  {"line":626,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":627,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":628,"text":"\t},"},
  {"line":629,"text":"\t&lsproto.CompletionItem{"},
  {"line":630,"text":"\t\tLabel:    \"NewableFunction\","},
  {"line":631,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":632,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":633,"text":"\t},"},
  {"line":634,"text":"\t&lsproto.CompletionItem{"},
  {"line":635,"text":"\t\tLabel:    \"IArguments\","},
  {"line":636,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":637,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":638,"text":"\t},"},
  {"line":639,"text":"\t&lsproto.CompletionItem{"},
  {"line":640,"text":"\t\tLabel:    \"String\","},
  {"line":641,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":642,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":643,"text":"\t},"},
  {"line":644,"text":"\t&lsproto.CompletionItem{"},
  {"line":645,"text":"\t\tLabel:    \"StringConstructor\","},
  {"line":646,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":647,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":648,"text":"\t},"},
  {"line":649,"text":"\t&lsproto.CompletionItem{"},
  {"line":650,"text":"\t\tLabel:    \"Boolean\","},
  {"line":651,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":652,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":653,"text":"\t},"},
  {"line":654,"text":"\t&lsproto.CompletionItem{"},
  {"line":655,"text":"\t\tLabel:    \"BooleanConstructor\","},
  {"line":656,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":657,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":658,"text":"\t},"},
  {"line":659,"text":"\t&lsproto.CompletionItem{"},
  {"line":660,"text":"\t\tLabel:    \"Number\","},
  {"line":661,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":662,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":663,"text":"\t},"},
  {"line":664,"text":"\t&lsproto.CompletionItem{"},
  {"line":665,"text":"\t\tLabel:    \"NumberConstructor\","},
  {"line":666,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":667,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":668,"text":"\t},"},
  {"line":669,"text":"\t&lsproto.CompletionItem{"},
  {"line":670,"text":"\t\tLabel:    \"TemplateStringsArray\","},
  {"line":671,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":672,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":673,"text":"\t},"},
  {"line":674,"text":"\t&lsproto.CompletionItem{"},
  {"line":675,"text":"\t\tLabel:    \"ImportMeta\","},
  {"line":676,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":677,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":678,"text":"\t},"},
  {"line":679,"text":"\t&lsproto.CompletionItem{"},
  {"line":680,"text":"\t\tLabel:    \"ImportCallOptions\","},
  {"line":681,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":682,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":683,"text":"\t},"},
  {"line":684,"text":"\t&lsproto.CompletionItem{"},
  {"line":685,"text":"\t\tLabel:    \"ImportAssertions\","},
  {"line":686,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":687,"text":"\t\tTags:     &[]lsproto.CompletionItemTag{lsproto.CompletionItemTagDeprecated},"},
  {"line":688,"text":"\t\tSortText: new(string(ls.DeprecateSortText(ls.SortTextGlobalsOrKeywords))),"},
  {"line":689,"text":"\t},"},
  {"line":690,"text":"\t&lsproto.CompletionItem{"},
  {"line":691,"text":"\t\tLabel:    \"ImportAttributes\","},
  {"line":692,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":693,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":694,"text":"\t},"},
  {"line":695,"text":"\t&lsproto.CompletionItem{"},
  {"line":696,"text":"\t\tLabel:    \"Math\","},
  {"line":697,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":698,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":699,"text":"\t},"},
  {"line":700,"text":"\t&lsproto.CompletionItem{"},
  {"line":701,"text":"\t\tLabel:    \"Date\","},
  {"line":702,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":703,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":704,"text":"\t},"},
  {"line":705,"text":"\t&lsproto.CompletionItem{"},
  {"line":706,"text":"\t\tLabel:    \"DateConstructor\","},
  {"line":707,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":708,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":709,"text":"\t},"},
  {"line":710,"text":"\t&lsproto.CompletionItem{"},
  {"line":711,"text":"\t\tLabel:    \"RegExpMatchArray\","},
  {"line":712,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":713,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":714,"text":"\t},"},
  {"line":715,"text":"\t&lsproto.CompletionItem{"},
  {"line":716,"text":"\t\tLabel:    \"RegExpExecArray\","},
  {"line":717,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":718,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":719,"text":"\t},"},
  {"line":720,"text":"\t&lsproto.CompletionItem{"},
  {"line":721,"text":"\t\tLabel:    \"RegExp\","},
  {"line":722,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":723,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":724,"text":"\t},"},
  {"line":725,"text":"\t&lsproto.CompletionItem{"},
  {"line":726,"text":"\t\tLabel:    \"RegExpConstructor\","},
  {"line":727,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":728,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":729,"text":"\t},"},
  {"line":730,"text":"\t&lsproto.CompletionItem{"},
  {"line":731,"text":"\t\tLabel:    \"Error\","},
  {"line":732,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":733,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":734,"text":"\t},"},
  {"line":735,"text":"\t&lsproto.CompletionItem{"},
  {"line":736,"text":"\t\tLabel:    \"ErrorConstructor\","},
  {"line":737,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":738,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":739,"text":"\t},"},
  {"line":740,"text":"\t&lsproto.CompletionItem{"},
  {"line":741,"text":"\t\tLabel:    \"EvalError\","},
  {"line":742,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":743,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":744,"text":"\t},"},
  {"line":745,"text":"\t&lsproto.CompletionItem{"},
  {"line":746,"text":"\t\tLabel:    \"EvalErrorConstructor\","},
  {"line":747,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":748,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":749,"text":"\t},"},
  {"line":750,"text":"\t&lsproto.CompletionItem{"},
  {"line":751,"text":"\t\tLabel:    \"RangeError\","},
  {"line":752,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":753,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":754,"text":"\t},"},
  {"line":755,"text":"\t&lsproto.CompletionItem{"},
  {"line":756,"text":"\t\tLabel:    \"RangeErrorConstructor\","},
  {"line":757,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":758,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":759,"text":"\t},"},
  {"line":760,"text":"\t&lsproto.CompletionItem{"},
  {"line":761,"text":"\t\tLabel:    \"ReferenceError\","},
  {"line":762,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":763,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":764,"text":"\t},"},
  {"line":765,"text":"\t&lsproto.CompletionItem{"},
  {"line":766,"text":"\t\tLabel:    \"ReferenceErrorConstructor\","},
  {"line":767,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":768,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":769,"text":"\t},"},
  {"line":770,"text":"\t&lsproto.CompletionItem{"},
  {"line":771,"text":"\t\tLabel:    \"SyntaxError\","},
  {"line":772,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":773,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":774,"text":"\t},"},
  {"line":775,"text":"\t&lsproto.CompletionItem{"},
  {"line":776,"text":"\t\tLabel:    \"SyntaxErrorConstructor\","},
  {"line":777,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":778,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":779,"text":"\t},"},
  {"line":780,"text":"\t&lsproto.CompletionItem{"},
  {"line":781,"text":"\t\tLabel:    \"TypeError\","},
  {"line":782,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":783,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":784,"text":"\t},"},
  {"line":785,"text":"\t&lsproto.CompletionItem{"},
  {"line":786,"text":"\t\tLabel:    \"TypeErrorConstructor\","},
  {"line":787,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":788,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":789,"text":"\t},"},
  {"line":790,"text":"\t&lsproto.CompletionItem{"},
  {"line":791,"text":"\t\tLabel:    \"URIError\","},
  {"line":792,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":793,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":794,"text":"\t},"},
  {"line":795,"text":"\t&lsproto.CompletionItem{"},
  {"line":796,"text":"\t\tLabel:    \"URIErrorConstructor\","},
  {"line":797,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":798,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":799,"text":"\t},"},
  {"line":800,"text":"\t&lsproto.CompletionItem{"},
  {"line":801,"text":"\t\tLabel:    \"JSON\","},
  {"line":802,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":803,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":804,"text":"\t},"},
  {"line":805,"text":"\t&lsproto.CompletionItem{"},
  {"line":806,"text":"\t\tLabel:    \"ReadonlyArray\","},
  {"line":807,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":808,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":809,"text":"\t},"},
  {"line":810,"text":"\t&lsproto.CompletionItem{"},
  {"line":811,"text":"\t\tLabel:    \"ConcatArray\","},
  {"line":812,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":813,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":814,"text":"\t},"},
  {"line":815,"text":"\t&lsproto.CompletionItem{"},
  {"line":816,"text":"\t\tLabel:    \"Array\","},
  {"line":817,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":818,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":819,"text":"\t},"},
  {"line":820,"text":"\t&lsproto.CompletionItem{"},
  {"line":821,"text":"\t\tLabel:    \"ArrayConstructor\","},
  {"line":822,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":823,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":824,"text":"\t},"},
  {"line":825,"text":"\t&lsproto.CompletionItem{"},
  {"line":826,"text":"\t\tLabel:    \"TypedPropertyDescriptor\","},
  {"line":827,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":828,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":829,"text":"\t},"},
  {"line":830,"text":"\t&lsproto.CompletionItem{"},
  {"line":831,"text":"\t\tLabel:    \"ClassDecorator\","},
  {"line":832,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":833,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":834,"text":"\t},"},
  {"line":835,"text":"\t&lsproto.CompletionItem{"},
  {"line":836,"text":"\t\tLabel:    \"PropertyDecorator\","},
  {"line":837,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":838,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":839,"text":"\t},"},
  {"line":840,"text":"\t&lsproto.CompletionItem{"},
  {"line":841,"text":"\t\tLabel:    \"MethodDecorator\","},
  {"line":842,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":843,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":844,"text":"\t},"},
  {"line":845,"text":"\t&lsproto.CompletionItem{"},
  {"line":846,"text":"\t\tLabel:    \"ParameterDecorator\","},
  {"line":847,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":848,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":849,"text":"\t},"},
  {"line":850,"text":"\t&lsproto.CompletionItem{"},
  {"line":851,"text":"\t\tLabel:    \"ClassMemberDecoratorContext\","},
  {"line":852,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":853,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":854,"text":"\t},"},
  {"line":855,"text":"\t&lsproto.CompletionItem{"},
  {"line":856,"text":"\t\tLabel:    \"DecoratorContext\","},
  {"line":857,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":858,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":859,"text":"\t},"},
  {"line":860,"text":"\t&lsproto.CompletionItem{"},
  {"line":861,"text":"\t\tLabel:    \"DecoratorMetadata\","},
  {"line":862,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":863,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":864,"text":"\t},"},
  {"line":865,"text":"\t&lsproto.CompletionItem{"},
  {"line":866,"text":"\t\tLabel:    \"DecoratorMetadataObject\","},
  {"line":867,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":868,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":869,"text":"\t},"},
  {"line":870,"text":"\t&lsproto.CompletionItem{"},
  {"line":871,"text":"\t\tLabel:    \"ClassDecoratorContext\","},
  {"line":872,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":873,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":874,"text":"\t},"},
  {"line":875,"text":"\t&lsproto.CompletionItem{"},
  {"line":876,"text":"\t\tLabel:    \"ClassMethodDecoratorContext\","},
  {"line":877,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":878,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":879,"text":"\t},"},
  {"line":880,"text":"\t&lsproto.CompletionItem{"},
  {"line":881,"text":"\t\tLabel:    \"ClassGetterDecoratorContext\","},
  {"line":882,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":883,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":884,"text":"\t},"},
  {"line":885,"text":"\t&lsproto.CompletionItem{"},
  {"line":886,"text":"\t\tLabel:    \"ClassSetterDecoratorContext\","},
  {"line":887,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":888,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":889,"text":"\t},"},
  {"line":890,"text":"\t&lsproto.CompletionItem{"},
  {"line":891,"text":"\t\tLabel:    \"ClassAccessorDecoratorContext\","},
  {"line":892,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":893,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":894,"text":"\t},"},
  {"line":895,"text":"\t&lsproto.CompletionItem{"},
  {"line":896,"text":"\t\tLabel:    \"ClassAccessorDecoratorTarget\","},
  {"line":897,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":898,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":899,"text":"\t},"},
  {"line":900,"text":"\t&lsproto.CompletionItem{"},
  {"line":901,"text":"\t\tLabel:    \"ClassAccessorDecoratorResult\","},
  {"line":902,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":903,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":904,"text":"\t},"},
  {"line":905,"text":"\t&lsproto.CompletionItem{"},
  {"line":906,"text":"\t\tLabel:    \"ClassFieldDecoratorContext\","},
  {"line":907,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":908,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":909,"text":"\t},"},
  {"line":910,"text":"\t&lsproto.CompletionItem{"},
  {"line":911,"text":"\t\tLabel:    \"PromiseConstructorLike\","},
  {"line":912,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":913,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":914,"text":"\t},"},
  {"line":915,"text":"\t&lsproto.CompletionItem{"},
  {"line":916,"text":"\t\tLabel:    \"PromiseLike\","},
  {"line":917,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":918,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":919,"text":"\t},"},
  {"line":920,"text":"\t&lsproto.CompletionItem{"},
  {"line":921,"text":"\t\tLabel:    \"Promise\","},
  {"line":922,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":923,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":924,"text":"\t},"},
  {"line":925,"text":"\t&lsproto.CompletionItem{"},
  {"line":926,"text":"\t\tLabel:    \"Awaited\","},
  {"line":927,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":928,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":929,"text":"\t},"},
  {"line":930,"text":"\t&lsproto.CompletionItem{"},
  {"line":931,"text":"\t\tLabel:    \"ArrayLike\","},
  {"line":932,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":933,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":934,"text":"\t},"},
  {"line":935,"text":"\t&lsproto.CompletionItem{"},
  {"line":936,"text":"\t\tLabel:    \"Partial\","},
  {"line":937,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":938,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":939,"text":"\t},"},
  {"line":940,"text":"\t&lsproto.CompletionItem{"},
  {"line":941,"text":"\t\tLabel:    \"Required\","},
  {"line":942,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":943,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":944,"text":"\t},"},
  {"line":945,"text":"\t&lsproto.CompletionItem{"},
  {"line":946,"text":"\t\tLabel:    \"Readonly\","},
  {"line":947,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":948,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":949,"text":"\t},"},
  {"line":950,"text":"\t&lsproto.CompletionItem{"},
  {"line":951,"text":"\t\tLabel:    \"Pick\","},
  {"line":952,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":953,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":954,"text":"\t},"},
  {"line":955,"text":"\t&lsproto.CompletionItem{"},
  {"line":956,"text":"\t\tLabel:    \"Record\","},
  {"line":957,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":958,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":959,"text":"\t},"},
  {"line":960,"text":"\t&lsproto.CompletionItem{"},
  {"line":961,"text":"\t\tLabel:    \"Exclude\","},
  {"line":962,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":963,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":964,"text":"\t},"},
  {"line":965,"text":"\t&lsproto.CompletionItem{"},
  {"line":966,"text":"\t\tLabel:    \"Extract\","},
  {"line":967,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":968,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":969,"text":"\t},"},
  {"line":970,"text":"\t&lsproto.CompletionItem{"},
  {"line":971,"text":"\t\tLabel:    \"Omit\","},
  {"line":972,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":973,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":974,"text":"\t},"},
  {"line":975,"text":"\t&lsproto.CompletionItem{"},
  {"line":976,"text":"\t\tLabel:    \"NonNullable\","},
  {"line":977,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":978,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":979,"text":"\t},"},
  {"line":980,"text":"\t&lsproto.CompletionItem{"},
  {"line":981,"text":"\t\tLabel:    \"Parameters\","},
  {"line":982,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":983,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":984,"text":"\t},"},
  {"line":985,"text":"\t&lsproto.CompletionItem{"},
  {"line":986,"text":"\t\tLabel:    \"ConstructorParameters\","},
  {"line":987,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":988,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":989,"text":"\t},"},
  {"line":990,"text":"\t&lsproto.CompletionItem{"},
  {"line":991,"text":"\t\tLabel:    \"ReturnType\","},
  {"line":992,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":993,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":994,"text":"\t},"},
  {"line":995,"text":"\t&lsproto.CompletionItem{"},
  {"line":996,"text":"\t\tLabel:    \"InstanceType\","},
  {"line":997,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":998,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":999,"text":"\t},"},
  {"line":1000,"text":"\t&lsproto.CompletionItem{"},
  {"line":1001,"text":"\t\tLabel:    \"Uppercase\","},
  {"line":1002,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1003,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1004,"text":"\t},"},
  {"line":1005,"text":"\t&lsproto.CompletionItem{"},
  {"line":1006,"text":"\t\tLabel:    \"Lowercase\","},
  {"line":1007,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1008,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1009,"text":"\t},"},
  {"line":1010,"text":"\t&lsproto.CompletionItem{"},
  {"line":1011,"text":"\t\tLabel:    \"Capitalize\","},
  {"line":1012,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1013,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1014,"text":"\t},"},
  {"line":1015,"text":"\t&lsproto.CompletionItem{"},
  {"line":1016,"text":"\t\tLabel:    \"Uncapitalize\","},
  {"line":1017,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1018,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1019,"text":"\t},"},
  {"line":1020,"text":"\t&lsproto.CompletionItem{"},
  {"line":1021,"text":"\t\tLabel:    \"NoInfer\","},
  {"line":1022,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1023,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1024,"text":"\t},"},
  {"line":1025,"text":"\t&lsproto.CompletionItem{"},
  {"line":1026,"text":"\t\tLabel:    \"ThisType\","},
  {"line":1027,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1028,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1029,"text":"\t},"},
  {"line":1030,"text":"\t&lsproto.CompletionItem{"},
  {"line":1031,"text":"\t\tLabel:    \"ArrayBuffer\","},
  {"line":1032,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1033,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1034,"text":"\t},"},
  {"line":1035,"text":"\t&lsproto.CompletionItem{"},
  {"line":1036,"text":"\t\tLabel:    \"ArrayBufferTypes\","},
  {"line":1037,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1038,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1039,"text":"\t},"},
  {"line":1040,"text":"\t&lsproto.CompletionItem{"},
  {"line":1041,"text":"\t\tLabel:    \"ArrayBufferLike\","},
  {"line":1042,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1043,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1044,"text":"\t},"},
  {"line":1045,"text":"\t&lsproto.CompletionItem{"},
  {"line":1046,"text":"\t\tLabel:    \"ArrayBufferConstructor\","},
  {"line":1047,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1048,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1049,"text":"\t},"},
  {"line":1050,"text":"\t&lsproto.CompletionItem{"},
  {"line":1051,"text":"\t\tLabel:    \"ArrayBufferView\","},
  {"line":1052,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1053,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1054,"text":"\t},"},
  {"line":1055,"text":"\t&lsproto.CompletionItem{"},
  {"line":1056,"text":"\t\tLabel:    \"DataView\","},
  {"line":1057,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1058,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1059,"text":"\t},"},
  {"line":1060,"text":"\t&lsproto.CompletionItem{"},
  {"line":1061,"text":"\t\tLabel:    \"DataViewConstructor\","},
  {"line":1062,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1063,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1064,"text":"\t},"},
  {"line":1065,"text":"\t&lsproto.CompletionItem{"},
  {"line":1066,"text":"\t\tLabel:    \"Int8Array\","},
  {"line":1067,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1068,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1069,"text":"\t},"},
  {"line":1070,"text":"\t&lsproto.CompletionItem{"},
  {"line":1071,"text":"\t\tLabel:    \"Int8ArrayConstructor\","},
  {"line":1072,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1073,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1074,"text":"\t},"},
  {"line":1075,"text":"\t&lsproto.CompletionItem{"},
  {"line":1076,"text":"\t\tLabel:    \"Uint8Array\","},
  {"line":1077,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1078,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1079,"text":"\t},"},
  {"line":1080,"text":"\t&lsproto.CompletionItem{"},
  {"line":1081,"text":"\t\tLabel:    \"Uint8ArrayConstructor\","},
  {"line":1082,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1083,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1084,"text":"\t},"},
  {"line":1085,"text":"\t&lsproto.CompletionItem{"},
  {"line":1086,"text":"\t\tLabel:    \"Uint8ClampedArray\","},
  {"line":1087,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1088,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1089,"text":"\t},"},
  {"line":1090,"text":"\t&lsproto.CompletionItem{"},
  {"line":1091,"text":"\t\tLabel:    \"Uint8ClampedArrayConstructor\","},
  {"line":1092,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1093,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1094,"text":"\t},"},
  {"line":1095,"text":"\t&lsproto.CompletionItem{"},
  {"line":1096,"text":"\t\tLabel:    \"Int16Array\","},
  {"line":1097,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1098,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1099,"text":"\t},"},
  {"line":1100,"text":"\t&lsproto.CompletionItem{"},
  {"line":1101,"text":"\t\tLabel:    \"Int16ArrayConstructor\","},
  {"line":1102,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1103,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1104,"text":"\t},"},
  {"line":1105,"text":"\t&lsproto.CompletionItem{"},
  {"line":1106,"text":"\t\tLabel:    \"Uint16Array\","},
  {"line":1107,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1108,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1109,"text":"\t},"},
  {"line":1110,"text":"\t&lsproto.CompletionItem{"},
  {"line":1111,"text":"\t\tLabel:    \"Uint16ArrayConstructor\","},
  {"line":1112,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1113,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1114,"text":"\t},"},
  {"line":1115,"text":"\t&lsproto.CompletionItem{"},
  {"line":1116,"text":"\t\tLabel:    \"Int32Array\","},
  {"line":1117,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1118,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1119,"text":"\t},"},
  {"line":1120,"text":"\t&lsproto.CompletionItem{"},
  {"line":1121,"text":"\t\tLabel:    \"Int32ArrayConstructor\","},
  {"line":1122,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1123,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1124,"text":"\t},"},
  {"line":1125,"text":"\t&lsproto.CompletionItem{"},
  {"line":1126,"text":"\t\tLabel:    \"Uint32Array\","},
  {"line":1127,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1128,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1129,"text":"\t},"},
  {"line":1130,"text":"\t&lsproto.CompletionItem{"},
  {"line":1131,"text":"\t\tLabel:    \"Uint32ArrayConstructor\","},
  {"line":1132,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1133,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1134,"text":"\t},"},
  {"line":1135,"text":"\t&lsproto.CompletionItem{"},
  {"line":1136,"text":"\t\tLabel:    \"Float32Array\","},
  {"line":1137,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1138,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1139,"text":"\t},"},
  {"line":1140,"text":"\t&lsproto.CompletionItem{"},
  {"line":1141,"text":"\t\tLabel:    \"Float32ArrayConstructor\","},
  {"line":1142,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1143,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1144,"text":"\t},"},
  {"line":1145,"text":"\t&lsproto.CompletionItem{"},
  {"line":1146,"text":"\t\tLabel:    \"Float64Array\","},
  {"line":1147,"text":"\t\tKind:     new(lsproto.CompletionItemKindVariable),"},
  {"line":1148,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1149,"text":"\t},"},
  {"line":1150,"text":"\t&lsproto.CompletionItem{"},
  {"line":1151,"text":"\t\tLabel:    \"Float64ArrayConstructor\","},
  {"line":1152,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1153,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1154,"text":"\t},"},
  {"line":1155,"text":"\t&lsproto.CompletionItem{"},
  {"line":1156,"text":"\t\tLabel:    \"Intl\","},
  {"line":1157,"text":"\t\tKind:     new(lsproto.CompletionItemKindModule),"},
  {"line":1158,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1159,"text":"\t},"},
  {"line":1160,"text":"\t&lsproto.CompletionItem{"},
  {"line":1161,"text":"\t\tLabel:    \"WeakKey\","},
  {"line":1162,"text":"\t\tKind:     new(lsproto.CompletionItemKindClass),"},
  {"line":1163,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1164,"text":"\t},"},
  {"line":1165,"text":"\t&lsproto.CompletionItem{"},
  {"line":1166,"text":"\t\tLabel:    \"WeakKeyTypes\","},
  {"line":1167,"text":"\t\tKind:     new(lsproto.CompletionItemKindInterface),"},
  {"line":1168,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1169,"text":"\t},"},
  {"line":1170,"text":"}"},
  {"line":1172,"text":"var CompletionTypeKeywords = []fourslash.CompletionsExpectedItem{"},
  {"line":1173,"text":"\t&lsproto.CompletionItem{"},
  {"line":1174,"text":"\t\tLabel:    \"any\","},
  {"line":1175,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1176,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1177,"text":"\t},"},
  {"line":1178,"text":"\t&lsproto.CompletionItem{"},
  {"line":1179,"text":"\t\tLabel:    \"asserts\","},
  {"line":1180,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1181,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1182,"text":"\t},"},
  {"line":1183,"text":"\t&lsproto.CompletionItem{"},
  {"line":1184,"text":"\t\tLabel:    \"bigint\","},
  {"line":1185,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1186,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1187,"text":"\t},"},
  {"line":1188,"text":"\t&lsproto.CompletionItem{"},
  {"line":1189,"text":"\t\tLabel:    \"boolean\","},
  {"line":1190,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1191,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1192,"text":"\t},"},
  {"line":1193,"text":"\t&lsproto.CompletionItem{"},
  {"line":1194,"text":"\t\tLabel:    \"false\","},
  {"line":1195,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1196,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1197,"text":"\t},"},
  {"line":1198,"text":"\t&lsproto.CompletionItem{"},
  {"line":1199,"text":"\t\tLabel:    \"infer\","},
  {"line":1200,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1201,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1202,"text":"\t},"},
  {"line":1203,"text":"\t&lsproto.CompletionItem{"},
  {"line":1204,"text":"\t\tLabel:    \"keyof\","},
  {"line":1205,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1206,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1207,"text":"\t},"},
  {"line":1208,"text":"\t&lsproto.CompletionItem{"},
  {"line":1209,"text":"\t\tLabel:    \"never\","},
  {"line":1210,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1211,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1212,"text":"\t},"},
  {"line":1213,"text":"\t&lsproto.CompletionItem{"},
  {"line":1214,"text":"\t\tLabel:    \"null\","},
  {"line":1215,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1216,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1217,"text":"\t},"},
  {"line":1218,"text":"\t&lsproto.CompletionItem{"},
  {"line":1219,"text":"\t\tLabel:    \"number\","},
  {"line":1220,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1221,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1222,"text":"\t},"},
  {"line":1223,"text":"\t&lsproto.CompletionItem{"},
  {"line":1224,"text":"\t\tLabel:    \"object\","},
  {"line":1225,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1226,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1227,"text":"\t},"},
  {"line":1228,"text":"\t&lsproto.CompletionItem{"},
  {"line":1229,"text":"\t\tLabel:    \"readonly\","},
  {"line":1230,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1231,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1232,"text":"\t},"},
  {"line":1233,"text":"\t&lsproto.CompletionItem{"},
  {"line":1234,"text":"\t\tLabel:    \"string\","},
  {"line":1235,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1236,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1237,"text":"\t},"},
  {"line":1238,"text":"\t&lsproto.CompletionItem{"},
  {"line":1239,"text":"\t\tLabel:    \"symbol\","},
  {"line":1240,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1241,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1242,"text":"\t},"},
  {"line":1243,"text":"\t&lsproto.CompletionItem{"},
  {"line":1244,"text":"\t\tLabel:    \"true\","},
  {"line":1245,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1246,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1247,"text":"\t},"},
  {"line":1248,"text":"\t&lsproto.CompletionItem{"},
  {"line":1249,"text":"\t\tLabel:    \"typeof\","},
  {"line":1250,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1251,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1252,"text":"\t},"},
  {"line":1253,"text":"\t&lsproto.CompletionItem{"},
  {"line":1254,"text":"\t\tLabel:    \"undefined\","},
  {"line":1255,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1256,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1257,"text":"\t},"},
  {"line":1258,"text":"\t&lsproto.CompletionItem{"},
  {"line":1259,"text":"\t\tLabel:    \"unique\","},
  {"line":1260,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1261,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1262,"text":"\t},"},
  {"line":1263,"text":"\t&lsproto.CompletionItem{"},
  {"line":1264,"text":"\t\tLabel:    \"unknown\","},
  {"line":1265,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1266,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1267,"text":"\t},"},
  {"line":1268,"text":"\t&lsproto.CompletionItem{"},
  {"line":1269,"text":"\t\tLabel:    \"void\","},
  {"line":1270,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1271,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1272,"text":"\t},"},
  {"line":1273,"text":"}"},
  {"line":1275,"text":"var CompletionClassElementKeywords = []fourslash.CompletionsExpectedItem{"},
  {"line":1276,"text":"\t&lsproto.CompletionItem{"},
  {"line":1277,"text":"\t\tLabel:    \"abstract\","},
  {"line":1278,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1279,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1280,"text":"\t},"},
  {"line":1281,"text":"\t&lsproto.CompletionItem{"},
  {"line":1282,"text":"\t\tLabel:    \"accessor\","},
  {"line":1283,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1284,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1285,"text":"\t},"},
  {"line":1286,"text":"\t&lsproto.CompletionItem{"},
  {"line":1287,"text":"\t\tLabel:    \"async\","},
  {"line":1288,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1289,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1290,"text":"\t},"},
  {"line":1291,"text":"\t&lsproto.CompletionItem{"},
  {"line":1292,"text":"\t\tLabel:    \"constructor\","},
  {"line":1293,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1294,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1295,"text":"\t},"},
  {"line":1296,"text":"\t&lsproto.CompletionItem{"},
  {"line":1297,"text":"\t\tLabel:    \"declare\","},
  {"line":1298,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1299,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1300,"text":"\t},"},
  {"line":1301,"text":"\t&lsproto.CompletionItem{"},
  {"line":1302,"text":"\t\tLabel:    \"get\","},
  {"line":1303,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1304,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1305,"text":"\t},"},
  {"line":1306,"text":"\t&lsproto.CompletionItem{"},
  {"line":1307,"text":"\t\tLabel:    \"override\","},
  {"line":1308,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1309,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1310,"text":"\t},"},
  {"line":1311,"text":"\t&lsproto.CompletionItem{"},
  {"line":1312,"text":"\t\tLabel:    \"private\","},
  {"line":1313,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1314,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1315,"text":"\t},"},
  {"line":1316,"text":"\t&lsproto.CompletionItem{"},
  {"line":1317,"text":"\t\tLabel:    \"protected\","},
  {"line":1318,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1319,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1320,"text":"\t},"},
  {"line":1321,"text":"\t&lsproto.CompletionItem{"},
  {"line":1322,"text":"\t\tLabel:    \"public\","},
  {"line":1323,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1324,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1325,"text":"\t},"},
  {"line":1326,"text":"\t&lsproto.CompletionItem{"},
  {"line":1327,"text":"\t\tLabel:    \"readonly\","},
  {"line":1328,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1329,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1330,"text":"\t},"},
  {"line":1331,"text":"\t&lsproto.CompletionItem{"},
  {"line":1332,"text":"\t\tLabel:    \"set\","},
  {"line":1333,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1334,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1335,"text":"\t},"},
  {"line":1336,"text":"\t&lsproto.CompletionItem{"},
  {"line":1337,"text":"\t\tLabel:    \"static\","},
  {"line":1338,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1339,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1340,"text":"\t},"},
  {"line":1341,"text":"}"},
  {"line":1343,"text":"var CompletionClassElementInJSKeywords = getInJSKeywords(CompletionClassElementKeywords)"},
  {"line":1345,"text":"var CompletionGlobals = sortCompletionItems(slices.Concat("},
  {"line":1346,"text":"\tCompletionGlobalVars,"},
  {"line":1347,"text":"\tCompletionGlobalKeywords,"},
  {"line":1348,"text":"\t[]fourslash.CompletionsExpectedItem{"},
  {"line":1349,"text":"\t\tCompletionGlobalThisItem,"},
  {"line":1350,"text":"\t\tCompletionUndefinedVarItem,"},
  {"line":1351,"text":"\t},"},
  {"line":1352,"text":"))"},
  {"line":1354,"text":"func sortCompletionItems(items []fourslash.CompletionsExpectedItem) []fourslash.CompletionsExpectedItem {"},
  {"line":1355,"text":"\tcompareStrings := stringutil.CompareStringsCaseInsensitiveThenSensitive"},
  {"line":1356,"text":"\titems = slices.Clone(items)"},
  {"line":1357,"text":"\tslices.SortStableFunc(items, func(a fourslash.CompletionsExpectedItem, b fourslash.CompletionsExpectedItem) int {"},
  {"line":1358,"text":"\t\tdefaultSortText := string(ls.SortTextLocationPriority)"},
  {"line":1359,"text":"\t\tvar aSortText, bSortText string"},
  {"line":1360,"text":"\t\tswitch a := a.(type) {"},
  {"line":1361,"text":"\t\tcase *lsproto.CompletionItem:"},
  {"line":1362,"text":"\t\t\tif a.SortText != nil {"},
  {"line":1363,"text":"\t\t\t\taSortText = *a.SortText"},
  {"line":1364,"text":"\t\t\t}"},
  {"line":1365,"text":"\t\t}"},
  {"line":1366,"text":"\t\tswitch b := b.(type) {"},
  {"line":1367,"text":"\t\tcase *lsproto.CompletionItem:"},
  {"line":1368,"text":"\t\t\tif b.SortText != nil {"},
  {"line":1369,"text":"\t\t\t\tbSortText = *b.SortText"},
  {"line":1370,"text":"\t\t\t}"},
  {"line":1371,"text":"\t\t}"},
  {"line":1372,"text":"\t\taSortText = core.OrElse(aSortText, defaultSortText)"},
  {"line":1373,"text":"\t\tbSortText = core.OrElse(bSortText, defaultSortText)"},
  {"line":1374,"text":"\t\tbySortText := compareStrings(aSortText, bSortText)"},
  {"line":1375,"text":"\t\tif bySortText != 0 {"},
  {"line":1376,"text":"\t\t\treturn bySortText"},
  {"line":1377,"text":"\t\t}"},
  {"line":1378,"text":"\t\tvar aLabel, bLabel string"},
  {"line":1379,"text":"\t\tswitch a := a.(type) {"},
  {"line":1380,"text":"\t\tcase *lsproto.CompletionItem:"},
  {"line":1381,"text":"\t\t\taLabel = a.Label"},
  {"line":1382,"text":"\t\tcase string:"},
  {"line":1383,"text":"\t\t\taLabel = a"},
  {"line":1384,"text":"\t\tdefault:"},
  {"line":1385,"text":"\t\t\tpanic(fmt.Sprintf(\"unexpected completion item type: %T\", a))"},
  {"line":1386,"text":"\t\t}"},
  {"line":1387,"text":"\t\tswitch b := b.(type) {"},
  {"line":1388,"text":"\t\tcase *lsproto.CompletionItem:"},
  {"line":1389,"text":"\t\t\tbLabel = b.Label"},
  {"line":1390,"text":"\t\tcase string:"},
  {"line":1391,"text":"\t\t\tbLabel = b"},
  {"line":1392,"text":"\t\tdefault:"},
  {"line":1393,"text":"\t\t\tpanic(fmt.Sprintf(\"unexpected completion item type: %T\", b))"},
  {"line":1394,"text":"\t\t}"},
  {"line":1395,"text":"\t\treturn compareStrings(aLabel, bLabel)"},
  {"line":1396,"text":"\t})"},
  {"line":1397,"text":"\treturn items"},
  {"line":1398,"text":"}"},
  {"line":1400,"text":"func CompletionGlobalsPlus(items []fourslash.CompletionsExpectedItem, noLib bool) []fourslash.CompletionsExpectedItem {"},
  {"line":1401,"text":"\tvar all []fourslash.CompletionsExpectedItem"},
  {"line":1402,"text":"\tif noLib {"},
  {"line":1403,"text":"\t\tall = slices.Concat("},
  {"line":1404,"text":"\t\t\titems,"},
  {"line":1405,"text":"\t\t\t[]fourslash.CompletionsExpectedItem{CompletionGlobalThisItem, CompletionUndefinedVarItem},"},
  {"line":1406,"text":"\t\t\tCompletionGlobalKeywords,"},
  {"line":1407,"text":"\t\t)"},
  {"line":1408,"text":"\t} else {"},
  {"line":1409,"text":"\t\tall = slices.Concat(items, CompletionGlobals)"},
  {"line":1410,"text":"\t}"},
  {"line":1411,"text":"\treturn sortCompletionItems(all)"},
  {"line":1412,"text":"}"},
  {"line":1414,"text":"func CompletionGlobalTypesPlus(items []fourslash.CompletionsExpectedItem) []fourslash.CompletionsExpectedItem {"},
  {"line":1415,"text":"\treturn sortCompletionItems(slices.Concat("},
  {"line":1416,"text":"\t\tCompletionGlobalTypeDecls,"},
  {"line":1417,"text":"\t\t[]fourslash.CompletionsExpectedItem{CompletionGlobalThisItem},"},
  {"line":1418,"text":"\t\tCompletionTypeKeywords,"},
  {"line":1419,"text":"\t\titems,"},
  {"line":1420,"text":"\t))"},
  {"line":1421,"text":"}"},
  {"line":1423,"text":"var CompletionGlobalTypes = CompletionGlobalTypesPlus(nil)"},
  {"line":1425,"text":"func getInJSKeywords(keywords []fourslash.CompletionsExpectedItem) []fourslash.CompletionsExpectedItem {"},
  {"line":1426,"text":"\treturn core.Filter(keywords, func(item fourslash.CompletionsExpectedItem) bool {"},
  {"line":1427,"text":"\t\tvar label string"},
  {"line":1428,"text":"\t\tswitch item := item.(type) {"},
  {"line":1429,"text":"\t\tcase *lsproto.CompletionItem:"},
  {"line":1430,"text":"\t\t\tlabel = item.Label"},
  {"line":1431,"text":"\t\tcase string:"},
  {"line":1432,"text":"\t\t\tlabel = item"},
  {"line":1433,"text":"\t\tdefault:"},
  {"line":1434,"text":"\t\t\tpanic(fmt.Sprintf(\"unexpected completion item type: %T\", item))"},
  {"line":1435,"text":"\t\t}"},
  {"line":1436,"text":"\t\tswitch label {"},
  {"line":1437,"text":"\t\tcase \"enum\", \"interface\", \"implements\", \"private\", \"protected\", \"public\", \"abstract\","},
  {"line":1438,"text":"\t\t\t\"any\", \"boolean\", \"declare\", \"infer\", \"is\", \"keyof\", \"module\", \"namespace\", \"never\","},
  {"line":1439,"text":"\t\t\t\"readonly\", \"number\", \"object\", \"string\", \"symbol\", \"type\", \"unique\", \"override\","},
  {"line":1440,"text":"\t\t\t\"unknown\", \"global\", \"bigint\":"},
  {"line":1441,"text":"\t\t\treturn false"},
  {"line":1442,"text":"\t\tdefault:"},
  {"line":1443,"text":"\t\t\treturn true"},
  {"line":1444,"text":"\t\t}"},
  {"line":1445,"text":"\t},"},
  {"line":1446,"text":"\t)"},
  {"line":1447,"text":"}"},
  {"line":1449,"text":"var CompletionGlobalInJSKeywords = getInJSKeywords(CompletionGlobalKeywords)"},
  {"line":1451,"text":"func CompletionGlobalsInJSPlus(items []fourslash.CompletionsExpectedItem, noLib bool) []fourslash.CompletionsExpectedItem {"},
  {"line":1452,"text":"\tall := slices.Concat("},
  {"line":1453,"text":"\t\titems,"},
  {"line":1454,"text":"\t\t[]fourslash.CompletionsExpectedItem{CompletionGlobalThisItem, CompletionUndefinedVarItem},"},
  {"line":1455,"text":"\t\tCompletionGlobalInJSKeywords,"},
  {"line":1456,"text":"\t)"},
  {"line":1457,"text":"\tif !noLib {"},
  {"line":1458,"text":"\t\tall = append(all, CompletionGlobalVars...)"},
  {"line":1459,"text":"\t}"},
  {"line":1460,"text":"\treturn sortCompletionItems(all)"},
  {"line":1461,"text":"}"},
  {"line":1463,"text":"var CompletionConstructorParameterKeywords = []fourslash.CompletionsExpectedItem{"},
  {"line":1464,"text":"\t&lsproto.CompletionItem{"},
  {"line":1465,"text":"\t\tLabel:    \"override\","},
  {"line":1466,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1467,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1468,"text":"\t},"},
  {"line":1469,"text":"\t&lsproto.CompletionItem{"},
  {"line":1470,"text":"\t\tLabel:    \"private\","},
  {"line":1471,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1472,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1473,"text":"\t},"},
  {"line":1474,"text":"\t&lsproto.CompletionItem{"},
  {"line":1475,"text":"\t\tLabel:    \"protected\","},
  {"line":1476,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1477,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1478,"text":"\t},"},
  {"line":1479,"text":"\t&lsproto.CompletionItem{"},
  {"line":1480,"text":"\t\tLabel:    \"public\","},
  {"line":1481,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1482,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1483,"text":"\t},"},
  {"line":1484,"text":"\t&lsproto.CompletionItem{"},
  {"line":1485,"text":"\t\tLabel:    \"readonly\","},
  {"line":1486,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1487,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1488,"text":"\t},"},
  {"line":1489,"text":"}"},
  {"line":1491,"text":"var CompletionFunctionMembers = []fourslash.CompletionsExpectedItem{"},
  {"line":1492,"text":"\t&lsproto.CompletionItem{"},
  {"line":1493,"text":"\t\tLabel: \"apply\","},
  {"line":1494,"text":"\t\tKind:  new(lsproto.CompletionItemKindMethod),"},
  {"line":1495,"text":"\t},"},
  {"line":1496,"text":"\t&lsproto.CompletionItem{"},
  {"line":1497,"text":"\t\tLabel: \"arguments\","},
  {"line":1498,"text":"\t\tKind:  new(lsproto.CompletionItemKindField),"},
  {"line":1499,"text":"\t},"},
  {"line":1500,"text":"\t&lsproto.CompletionItem{"},
  {"line":1501,"text":"\t\tLabel: \"bind\","},
  {"line":1502,"text":"\t\tKind:  new(lsproto.CompletionItemKindMethod),"},
  {"line":1503,"text":"\t},"},
  {"line":1504,"text":"\t&lsproto.CompletionItem{"},
  {"line":1505,"text":"\t\tLabel: \"call\","},
  {"line":1506,"text":"\t\tKind:  new(lsproto.CompletionItemKindMethod),"},
  {"line":1507,"text":"\t},"},
  {"line":1508,"text":"\t&lsproto.CompletionItem{"},
  {"line":1509,"text":"\t\tLabel: \"caller\","},
  {"line":1510,"text":"\t\tKind:  new(lsproto.CompletionItemKindField),"},
  {"line":1511,"text":"\t},"},
  {"line":1512,"text":"\t&lsproto.CompletionItem{"},
  {"line":1513,"text":"\t\tLabel: \"length\","},
  {"line":1514,"text":"\t\tKind:  new(lsproto.CompletionItemKindField),"},
  {"line":1515,"text":"\t},"},
  {"line":1516,"text":"\t&lsproto.CompletionItem{"},
  {"line":1517,"text":"\t\tLabel: \"toString\","},
  {"line":1518,"text":"\t\tKind:  new(lsproto.CompletionItemKindMethod),"},
  {"line":1519,"text":"\t},"},
  {"line":1520,"text":"}"},
  {"line":1522,"text":"func CompletionFunctionMembersPlus(items []fourslash.CompletionsExpectedItem) []fourslash.CompletionsExpectedItem {"},
  {"line":1523,"text":"\treturn sortCompletionItems("},
  {"line":1524,"text":"\t\tslices.Concat("},
  {"line":1525,"text":"\t\t\tCompletionFunctionMembers,"},
  {"line":1526,"text":"\t\t\titems,"},
  {"line":1527,"text":"\t\t),"},
  {"line":1528,"text":"\t)"},
  {"line":1529,"text":"}"},
  {"line":1531,"text":"var CompletionFunctionMembersWithPrototype = sortCompletionItems(slices.Concat("},
  {"line":1532,"text":"\tCompletionFunctionMembers,"},
  {"line":1533,"text":"\t[]fourslash.CompletionsExpectedItem{"},
  {"line":1534,"text":"\t\t&lsproto.CompletionItem{"},
  {"line":1535,"text":"\t\t\tLabel: \"prototype\","},
  {"line":1536,"text":"\t\t\tKind:  new(lsproto.CompletionItemKindField),"},
  {"line":1537,"text":"\t\t},"},
  {"line":1538,"text":"\t},"},
  {"line":1539,"text":"))"},
  {"line":1541,"text":"func CompletionFunctionMembersWithPrototypePlus(items []fourslash.CompletionsExpectedItem) []fourslash.CompletionsExpectedItem {"},
  {"line":1542,"text":"\treturn sortCompletionItems("},
  {"line":1543,"text":"\t\tslices.Concat("},
  {"line":1544,"text":"\t\t\tCompletionFunctionMembersWithPrototype,"},
  {"line":1545,"text":"\t\t\titems,"},
  {"line":1546,"text":"\t\t),"},
  {"line":1547,"text":"\t)"},
  {"line":1548,"text":"}"},
  {"line":1550,"text":"func CompletionTypeKeywordsPlus(items []fourslash.CompletionsExpectedItem) []fourslash.CompletionsExpectedItem {"},
  {"line":1551,"text":"\treturn sortCompletionItems("},
  {"line":1552,"text":"\t\tslices.Concat("},
  {"line":1553,"text":"\t\t\tCompletionTypeKeywords,"},
  {"line":1554,"text":"\t\t\titems,"},
  {"line":1555,"text":"\t\t),"},
  {"line":1556,"text":"\t)"},
  {"line":1557,"text":"}"},
  {"line":1559,"text":"var CompletionTypeAssertionKeywords = CompletionGlobalTypesPlus([]fourslash.CompletionsExpectedItem{"},
  {"line":1560,"text":"\t&lsproto.CompletionItem{"},
  {"line":1561,"text":"\t\tLabel:    \"const\","},
  {"line":1562,"text":"\t\tKind:     new(lsproto.CompletionItemKindKeyword),"},
  {"line":1563,"text":"\t\tSortText: new(string(ls.SortTextGlobalsOrKeywords)),"},
  {"line":1564,"text":"\t},"},
  {"line":1565,"text":"})"},
  {"line":1567,"text":"func ToAny[T any](items []T) []any {"},
  {"line":1568,"text":"\treturn core.Map(items, func(item T) any { return item })"},
  {"line":1569,"text":"}"},
];

function findFourslashTestsUtilUtilDeclaration(name: string): UpstreamDeclaration | undefined {
  return fourslashTestsUtilUtilDeclarations.find((declaration) => declaration.name === name);
}

function requireFourslashTestsUtilUtilDeclaration(name: string): UpstreamDeclaration {
  const declaration = findFourslashTestsUtilUtilDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

function fourslashTestsUtilUtilLineText(line: number): string | undefined {
  return fourslashTestsUtilUtilSourceLines.find((entry) => entry.line === line)?.text;
}
