/**
 * Strict TS-Go parity gap map for `core`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const coreStrictParityUpstreamModule = "core";
export const coreStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"arena.go","line":1,"text":"package core"},
  {"file":"arena.go","line":3,"text":"import \"slices\""},
  {"file":"arena.go","line":7,"text":"type Arena[T any] struct {"},
  {"file":"arena.go","line":8,"text":"\tdata []T"},
  {"file":"arena.go","line":9,"text":"}"},
  {"file":"arena.go","line":13,"text":"func (a *Arena[T]) New() *T {"},
  {"file":"arena.go","line":14,"text":"\tif len(a.data) == cap(a.data) {"},
  {"file":"arena.go","line":15,"text":"\t\tnextSize := nextArenaSize(len(a.data))"},
  {"file":"arena.go","line":17,"text":"\t\ta.data = slices.Grow[[]T](nil, nextSize)"},
  {"file":"arena.go","line":18,"text":"\t}"},
  {"file":"arena.go","line":19,"text":"\tindex := len(a.data)"},
  {"file":"arena.go","line":20,"text":"\ta.data = a.data[:index+1]"},
  {"file":"arena.go","line":21,"text":"\treturn &a.data[index]"},
  {"file":"arena.go","line":22,"text":"}"},
  {"file":"arena.go","line":28,"text":"func (a *Arena[T]) NewSlice(size int) []T {"},
  {"file":"arena.go","line":29,"text":"\tif size == 0 {"},
  {"file":"arena.go","line":30,"text":"\t\treturn nil"},
  {"file":"arena.go","line":31,"text":"\t}"},
  {"file":"arena.go","line":32,"text":"\tif len(a.data)+size > cap(a.data) {"},
  {"file":"arena.go","line":33,"text":"\t\tnextSize := nextArenaSize(len(a.data))"},
  {"file":"arena.go","line":34,"text":"\t\tif size > nextSize {"},
  {"file":"arena.go","line":35,"text":"\t\t\treturn make([]T, size)"},
  {"file":"arena.go","line":36,"text":"\t\t}"},
  {"file":"arena.go","line":38,"text":"\t\ta.data = slices.Grow[[]T](nil, nextSize)"},
  {"file":"arena.go","line":39,"text":"\t}"},
  {"file":"arena.go","line":40,"text":"\tnewLen := len(a.data) + size"},
  {"file":"arena.go","line":41,"text":"\tslice := a.data[len(a.data):newLen:newLen]"},
  {"file":"arena.go","line":42,"text":"\ta.data = a.data[:newLen]"},
  {"file":"arena.go","line":43,"text":"\treturn slice"},
  {"file":"arena.go","line":44,"text":"}"},
  {"file":"arena.go","line":46,"text":"func (a *Arena[T]) NewSlice1(t T) []T {"},
  {"file":"arena.go","line":47,"text":"\tslice := a.NewSlice(1)"},
  {"file":"arena.go","line":48,"text":"\tslice[0] = t"},
  {"file":"arena.go","line":49,"text":"\treturn slice"},
  {"file":"arena.go","line":50,"text":"}"},
  {"file":"arena.go","line":52,"text":"func (a *Arena[T]) Clone(t []T) []T {"},
  {"file":"arena.go","line":53,"text":"\tif len(t) == 0 {"},
  {"file":"arena.go","line":54,"text":"\t\treturn nil"},
  {"file":"arena.go","line":55,"text":"\t}"},
  {"file":"arena.go","line":56,"text":"\tslice := a.NewSlice(len(t))"},
  {"file":"arena.go","line":57,"text":"\tcopy(slice, t)"},
  {"file":"arena.go","line":58,"text":"\treturn slice"},
  {"file":"arena.go","line":59,"text":"}"},
  {"file":"arena.go","line":61,"text":"func nextArenaSize(size int) int {"},
  {"file":"arena.go","line":63,"text":"\tsize = max(size, 1)"},
  {"file":"arena.go","line":64,"text":"\tsize = min(size*2, 256)"},
  {"file":"arena.go","line":65,"text":"\treturn size"},
  {"file":"arena.go","line":66,"text":"}"},
  {"file":"bfs.go","line":1,"text":"package core"},
  {"file":"bfs.go","line":3,"text":"import ("},
  {"file":"bfs.go","line":4,"text":"\t\"math\""},
  {"file":"bfs.go","line":5,"text":"\t\"sync\""},
  {"file":"bfs.go","line":6,"text":"\t\"sync/atomic\""},
  {"file":"bfs.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"bfs.go","line":9,"text":")"},
  {"file":"bfs.go","line":11,"text":"type BreadthFirstSearchResult[N any] struct {"},
  {"file":"bfs.go","line":12,"text":"\tStopped bool"},
  {"file":"bfs.go","line":13,"text":"\tPath    []N"},
  {"file":"bfs.go","line":14,"text":"}"},
  {"file":"bfs.go","line":16,"text":"type breadthFirstSearchJob[N any] struct {"},
  {"file":"bfs.go","line":17,"text":"\tnode   N"},
  {"file":"bfs.go","line":18,"text":"\tparent *breadthFirstSearchJob[N]"},
  {"file":"bfs.go","line":19,"text":"}"},
  {"file":"bfs.go","line":21,"text":"type BreadthFirstSearchLevel[K comparable, N any] struct {"},
  {"file":"bfs.go","line":22,"text":"\tjobs *collections.OrderedMap[K, *breadthFirstSearchJob[N]]"},
  {"file":"bfs.go","line":23,"text":"}"},
  {"file":"bfs.go","line":25,"text":"func (l *BreadthFirstSearchLevel[K, N]) Has(key K) bool {"},
  {"file":"bfs.go","line":26,"text":"\treturn l.jobs.Has(key)"},
  {"file":"bfs.go","line":27,"text":"}"},
  {"file":"bfs.go","line":29,"text":"func (l *BreadthFirstSearchLevel[K, N]) Delete(key K) {"},
  {"file":"bfs.go","line":30,"text":"\tl.jobs.Delete(key)"},
  {"file":"bfs.go","line":31,"text":"}"},
  {"file":"bfs.go","line":33,"text":"func (l *BreadthFirstSearchLevel[K, N]) Range(f func(node N) bool) {"},
  {"file":"bfs.go","line":34,"text":"\tfor job := range l.jobs.Values() {"},
  {"file":"bfs.go","line":35,"text":"\t\tif !f(job.node) {"},
  {"file":"bfs.go","line":36,"text":"\t\t\treturn"},
  {"file":"bfs.go","line":37,"text":"\t\t}"},
  {"file":"bfs.go","line":38,"text":"\t}"},
  {"file":"bfs.go","line":39,"text":"}"},
  {"file":"bfs.go","line":41,"text":"type BreadthFirstSearchOptions[K comparable, N any] struct {"},
  {"file":"bfs.go","line":44,"text":"\tVisited *collections.SyncSet[K]"},
  {"file":"bfs.go","line":47,"text":"\tPreprocessLevel func(*BreadthFirstSearchLevel[K, N])"},
  {"file":"bfs.go","line":48,"text":"}"},
  {"file":"bfs.go","line":53,"text":"func BreadthFirstSearchParallel[N comparable]("},
  {"file":"bfs.go","line":54,"text":"\tstart N,"},
  {"file":"bfs.go","line":55,"text":"\tneighbors func(N) []N,"},
  {"file":"bfs.go","line":56,"text":"\tvisit func(node N) (isResult bool, stop bool),"},
  {"file":"bfs.go","line":57,"text":") BreadthFirstSearchResult[N] {"},
  {"file":"bfs.go","line":58,"text":"\treturn BreadthFirstSearchParallelEx(start, neighbors, visit, BreadthFirstSearchOptions[N, N]{}, Identity)"},
  {"file":"bfs.go","line":59,"text":"}"},
  {"file":"bfs.go","line":64,"text":"func BreadthFirstSearchParallelEx[K comparable, N any]("},
  {"file":"bfs.go","line":65,"text":"\tstart N,"},
  {"file":"bfs.go","line":66,"text":"\tneighbors func(N) []N,"},
  {"file":"bfs.go","line":67,"text":"\tvisit func(node N) (isResult bool, stop bool),"},
  {"file":"bfs.go","line":68,"text":"\toptions BreadthFirstSearchOptions[K, N],"},
  {"file":"bfs.go","line":69,"text":"\tgetKey func(N) K,"},
  {"file":"bfs.go","line":70,"text":") BreadthFirstSearchResult[N] {"},
  {"file":"bfs.go","line":71,"text":"\tvisited := options.Visited"},
  {"file":"bfs.go","line":72,"text":"\tif visited == nil {"},
  {"file":"bfs.go","line":73,"text":"\t\tvisited = &collections.SyncSet[K]{}"},
  {"file":"bfs.go","line":74,"text":"\t}"},
  {"file":"bfs.go","line":76,"text":"\ttype result struct {"},
  {"file":"bfs.go","line":77,"text":"\t\tstop bool"},
  {"file":"bfs.go","line":78,"text":"\t\tjob  *breadthFirstSearchJob[N]"},
  {"file":"bfs.go","line":79,"text":"\t\tnext *collections.OrderedMap[K, *breadthFirstSearchJob[N]]"},
  {"file":"bfs.go","line":80,"text":"\t}"},
  {"file":"bfs.go","line":82,"text":"\tvar fallback *breadthFirstSearchJob[N]"},
  {"file":"bfs.go","line":86,"text":"\tprocessLevel := func(index int, jobs *collections.OrderedMap[K, *breadthFirstSearchJob[N]]) result {"},
  {"file":"bfs.go","line":87,"text":"\t\tvar lowestFallback atomic.Int64"},
  {"file":"bfs.go","line":88,"text":"\t\tvar lowestGoal atomic.Int64"},
  {"file":"bfs.go","line":89,"text":"\t\tvar nextJobCount atomic.Int64"},
  {"file":"bfs.go","line":90,"text":"\t\tlowestGoal.Store(math.MaxInt64)"},
  {"file":"bfs.go","line":91,"text":"\t\tlowestFallback.Store(math.MaxInt64)"},
  {"file":"bfs.go","line":92,"text":"\t\tif options.PreprocessLevel != nil {"},
  {"file":"bfs.go","line":93,"text":"\t\t\toptions.PreprocessLevel(&BreadthFirstSearchLevel[K, N]{jobs: jobs})"},
  {"file":"bfs.go","line":94,"text":"\t\t}"},
  {"file":"bfs.go","line":95,"text":"\t\tnext := make([][]*breadthFirstSearchJob[N], jobs.Size())"},
  {"file":"bfs.go","line":96,"text":"\t\tvar wg sync.WaitGroup"},
  {"file":"bfs.go","line":97,"text":"\t\ti := 0"},
  {"file":"bfs.go","line":98,"text":"\t\tfor j := range jobs.Values() {"},
  {"file":"bfs.go","line":99,"text":"\t\t\twg.Add(1)"},
  {"file":"bfs.go","line":100,"text":"\t\t\tgo func(i int, j *breadthFirstSearchJob[N]) {"},
  {"file":"bfs.go","line":101,"text":"\t\t\t\tdefer wg.Done()"},
  {"file":"bfs.go","line":102,"text":"\t\t\t\tif int64(i) >= lowestGoal.Load() {"},
  {"file":"bfs.go","line":103,"text":"\t\t\t\t\treturn // Stop processing if we already found a lower result"},
  {"file":"bfs.go","line":104,"text":"\t\t\t\t}"},
  {"file":"bfs.go","line":107,"text":"\t\t\t\tif !visited.AddIfAbsent(getKey(j.node)) {"},
  {"file":"bfs.go","line":112,"text":"\t\t\t\t\treturn"},
  {"file":"bfs.go","line":113,"text":"\t\t\t\t}"},
  {"file":"bfs.go","line":115,"text":"\t\t\t\tisResult, stop := visit(j.node)"},
  {"file":"bfs.go","line":116,"text":"\t\t\t\tif isResult {"},
  {"file":"bfs.go","line":119,"text":"\t\t\t\t\tif stop {"},
  {"file":"bfs.go","line":120,"text":"\t\t\t\t\t\tupdateMin(&lowestGoal, int64(i))"},
  {"file":"bfs.go","line":121,"text":"\t\t\t\t\t\treturn"},
  {"file":"bfs.go","line":122,"text":"\t\t\t\t\t}"},
  {"file":"bfs.go","line":123,"text":"\t\t\t\t\tif fallback == nil {"},
  {"file":"bfs.go","line":124,"text":"\t\t\t\t\t\tupdateMin(&lowestFallback, int64(i))"},
  {"file":"bfs.go","line":125,"text":"\t\t\t\t\t}"},
  {"file":"bfs.go","line":126,"text":"\t\t\t\t}"},
  {"file":"bfs.go","line":128,"text":"\t\t\t\tif int64(i) >= lowestGoal.Load() {"},
  {"file":"bfs.go","line":132,"text":"\t\t\t\t\treturn"},
  {"file":"bfs.go","line":133,"text":"\t\t\t\t}"},
  {"file":"bfs.go","line":135,"text":"\t\t\t\tneighborNodes := neighbors(j.node)"},
  {"file":"bfs.go","line":136,"text":"\t\t\t\tif len(neighborNodes) > 0 {"},
  {"file":"bfs.go","line":137,"text":"\t\t\t\t\tnextJobCount.Add(int64(len(neighborNodes)))"},
  {"file":"bfs.go","line":138,"text":"\t\t\t\t\tnext[i] = Map(neighborNodes, func(child N) *breadthFirstSearchJob[N] {"},
  {"file":"bfs.go","line":139,"text":"\t\t\t\t\t\treturn &breadthFirstSearchJob[N]{node: child, parent: j}"},
  {"file":"bfs.go","line":140,"text":"\t\t\t\t\t})"},
  {"file":"bfs.go","line":141,"text":"\t\t\t\t}"},
  {"file":"bfs.go","line":142,"text":"\t\t\t}(i, j)"},
  {"file":"bfs.go","line":143,"text":"\t\t\ti++"},
  {"file":"bfs.go","line":144,"text":"\t\t}"},
  {"file":"bfs.go","line":145,"text":"\t\twg.Wait()"},
  {"file":"bfs.go","line":146,"text":"\t\tif index := lowestGoal.Load(); index != math.MaxInt64 {"},
  {"file":"bfs.go","line":148,"text":"\t\t\t_, job, _ := jobs.EntryAt(int(index))"},
  {"file":"bfs.go","line":149,"text":"\t\t\treturn result{stop: true, job: job}"},
  {"file":"bfs.go","line":150,"text":"\t\t}"},
  {"file":"bfs.go","line":151,"text":"\t\tif fallback == nil {"},
  {"file":"bfs.go","line":152,"text":"\t\t\tif index := lowestFallback.Load(); index != math.MaxInt64 {"},
  {"file":"bfs.go","line":153,"text":"\t\t\t\t_, fallback, _ = jobs.EntryAt(int(index))"},
  {"file":"bfs.go","line":154,"text":"\t\t\t}"},
  {"file":"bfs.go","line":155,"text":"\t\t}"},
  {"file":"bfs.go","line":156,"text":"\t\tnextJobs := collections.NewOrderedMapWithSizeHint[K, *breadthFirstSearchJob[N]](int(nextJobCount.Load()))"},
  {"file":"bfs.go","line":157,"text":"\t\tfor _, jobs := range next {"},
  {"file":"bfs.go","line":158,"text":"\t\t\tfor _, j := range jobs {"},
  {"file":"bfs.go","line":159,"text":"\t\t\t\tif !nextJobs.Has(getKey(j.node)) {"},
  {"file":"bfs.go","line":162,"text":"\t\t\t\t\tnextJobs.Set(getKey(j.node), j)"},
  {"file":"bfs.go","line":163,"text":"\t\t\t\t}"},
  {"file":"bfs.go","line":164,"text":"\t\t\t}"},
  {"file":"bfs.go","line":165,"text":"\t\t}"},
  {"file":"bfs.go","line":166,"text":"\t\treturn result{next: nextJobs}"},
  {"file":"bfs.go","line":167,"text":"\t}"},
  {"file":"bfs.go","line":169,"text":"\tcreatePath := func(job *breadthFirstSearchJob[N]) []N {"},
  {"file":"bfs.go","line":170,"text":"\t\tvar path []N"},
  {"file":"bfs.go","line":171,"text":"\t\tfor job != nil {"},
  {"file":"bfs.go","line":172,"text":"\t\t\tpath = append(path, job.node)"},
  {"file":"bfs.go","line":173,"text":"\t\t\tjob = job.parent"},
  {"file":"bfs.go","line":174,"text":"\t\t}"},
  {"file":"bfs.go","line":175,"text":"\t\treturn path"},
  {"file":"bfs.go","line":176,"text":"\t}"},
  {"file":"bfs.go","line":178,"text":"\tlevelIndex := 0"},
  {"file":"bfs.go","line":179,"text":"\tlevel := collections.NewOrderedMapFromList([]collections.MapEntry[K, *breadthFirstSearchJob[N]]{"},
  {"file":"bfs.go","line":180,"text":"\t\t{Key: getKey(start), Value: &breadthFirstSearchJob[N]{node: start}},"},
  {"file":"bfs.go","line":181,"text":"\t})"},
  {"file":"bfs.go","line":182,"text":"\tfor level.Size() > 0 {"},
  {"file":"bfs.go","line":183,"text":"\t\tresult := processLevel(levelIndex, level)"},
  {"file":"bfs.go","line":184,"text":"\t\tif result.stop {"},
  {"file":"bfs.go","line":185,"text":"\t\t\treturn BreadthFirstSearchResult[N]{Stopped: true, Path: createPath(result.job)}"},
  {"file":"bfs.go","line":186,"text":"\t\t} else if result.job != nil && fallback == nil {"},
  {"file":"bfs.go","line":187,"text":"\t\t\tfallback = result.job"},
  {"file":"bfs.go","line":188,"text":"\t\t}"},
  {"file":"bfs.go","line":189,"text":"\t\tlevel = result.next"},
  {"file":"bfs.go","line":190,"text":"\t\tlevelIndex++"},
  {"file":"bfs.go","line":191,"text":"\t}"},
  {"file":"bfs.go","line":192,"text":"\treturn BreadthFirstSearchResult[N]{Stopped: false, Path: createPath(fallback)}"},
  {"file":"bfs.go","line":193,"text":"}"},
  {"file":"bfs.go","line":196,"text":"func updateMin(a *atomic.Int64, candidate int64) bool {"},
  {"file":"bfs.go","line":197,"text":"\tfor {"},
  {"file":"bfs.go","line":198,"text":"\t\tcurrent := a.Load()"},
  {"file":"bfs.go","line":199,"text":"\t\tif current < candidate {"},
  {"file":"bfs.go","line":200,"text":"\t\t\treturn false"},
  {"file":"bfs.go","line":201,"text":"\t\t}"},
  {"file":"bfs.go","line":202,"text":"\t\tif a.CompareAndSwap(current, candidate) {"},
  {"file":"bfs.go","line":203,"text":"\t\t\treturn true"},
  {"file":"bfs.go","line":204,"text":"\t\t}"},
  {"file":"bfs.go","line":205,"text":"\t}"},
  {"file":"bfs.go","line":206,"text":"}"},
  {"file":"binarysearch.go","line":1,"text":"package core"},
  {"file":"binarysearch.go","line":8,"text":"func BinarySearchUniqueFunc[S ~[]E, E any](x S, cmp func(int, E) int) (int, bool) {"},
  {"file":"binarysearch.go","line":9,"text":"\tn := len(x)"},
  {"file":"binarysearch.go","line":10,"text":"\tif n == 0 {"},
  {"file":"binarysearch.go","line":11,"text":"\t\treturn 0, false"},
  {"file":"binarysearch.go","line":12,"text":"\t}"},
  {"file":"binarysearch.go","line":13,"text":"\tlow, high := 0, n-1"},
  {"file":"binarysearch.go","line":14,"text":"\tfor low <= high {"},
  {"file":"binarysearch.go","line":15,"text":"\t\tmiddle := low + ((high - low) >> 1)"},
  {"file":"binarysearch.go","line":16,"text":"\t\tvalue := cmp(middle, x[middle])"},
  {"file":"binarysearch.go","line":17,"text":"\t\tif value < 0 {"},
  {"file":"binarysearch.go","line":18,"text":"\t\t\tlow = middle + 1"},
  {"file":"binarysearch.go","line":19,"text":"\t\t} else if value > 0 {"},
  {"file":"binarysearch.go","line":20,"text":"\t\t\thigh = middle - 1"},
  {"file":"binarysearch.go","line":21,"text":"\t\t} else {"},
  {"file":"binarysearch.go","line":22,"text":"\t\t\treturn middle, true"},
  {"file":"binarysearch.go","line":23,"text":"\t\t}"},
  {"file":"binarysearch.go","line":24,"text":"\t}"},
  {"file":"binarysearch.go","line":25,"text":"\treturn low, false"},
  {"file":"binarysearch.go","line":26,"text":"}"},
  {"file":"buildoptions.go","line":1,"text":"package core"},
  {"file":"buildoptions.go","line":3,"text":"type BuildOptions struct {"},
  {"file":"buildoptions.go","line":4,"text":"\t_ noCopy"},
  {"file":"buildoptions.go","line":6,"text":"\tDry               Tristate `json:\"dry,omitzero\"`"},
  {"file":"buildoptions.go","line":7,"text":"\tForce             Tristate `json:\"force,omitzero\"`"},
  {"file":"buildoptions.go","line":8,"text":"\tVerbose           Tristate `json:\"verbose,omitzero\"`"},
  {"file":"buildoptions.go","line":9,"text":"\tBuilders          *int     `json:\"builders,omitzero\"`"},
  {"file":"buildoptions.go","line":10,"text":"\tStopBuildOnErrors Tristate `json:\"stopBuildOnErrors,omitzero\"`"},
  {"file":"buildoptions.go","line":15,"text":"\tClean Tristate `json:\"clean,omitzero\"`"},
  {"file":"buildoptions.go","line":16,"text":"}"},
  {"file":"compileroptions.go","line":1,"text":"package core"},
  {"file":"compileroptions.go","line":3,"text":"import ("},
  {"file":"compileroptions.go","line":4,"text":"\t\"reflect\""},
];

export function coreStrictParityLineText(file: string, line: number): string | undefined {
  return coreStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function coreStrictParityFiles(): readonly string[] {
  return [...new Set(coreStrictParitySourceLines.map((entry) => entry.file))].sort();
}
