// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/golang.org/x/tools/go/analysis/checker.ts","contentHash":"e7534444f24dcdd2fc67fbfbe221bd052baf35da46ce90f5e264a4adc997b57d"}

export function Analyze(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED golang.org/x/tools/go/analysis/checker.Analyze");
}
