// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/github.com/mackerelio/go-osstat/memory.ts","contentHash":"c9c7aca83229432203156b1c520ef225464df31eb4eac491165f270ea7150786"}

export function Get(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED github.com/mackerelio/go-osstat/memory.Get");
}
