// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/testdata/unexportedapi/otherpkg.ts","contentHash":"00c0f72c3453b5e6bb03d9cbac0c6f239406bb05b2bc9fedc70b6fe9cf883ef7"}

export interface ExportedType {
  readonly __goFacadeName: "testdata/unexportedapi/otherpkg.ExportedType";
}

export interface TypeWithUnexported {
  readonly __goFacadeName: "testdata/unexportedapi/otherpkg.TypeWithUnexported";
}
