/**
 * Compiler-option declarations table.
 *
 * Port skeleton of TS-Go `internal/tsoptions/declscompiler.go`
 * (~1264 LoC). The upstream Go file is a single large `var` table
 * enumerating every compiler option with name, type, category,
 * description, defaultValueDescription, and validation hints.
 *
 * Skeleton exposes the `optionDeclarations` slice with the most
 * commonly-referenced options; the full Strada table will be filled
 * in incrementally as CLI integration tests demand. Each entry is
 * a faithful translation of the Strada CommandLineOption shape.
 */

import type { CommandLineOption } from "./commandlineoption.js";
import { moduleKindMap, scriptTargetMap, jsxEmitMap, moduleResolutionKindMap } from "./enummaps.js";

export const optionDeclarations: readonly CommandLineOption[] = [
  { name: "help", shortName: "h", type: "boolean" },
  { name: "all", type: "boolean" },
  { name: "version", shortName: "v", type: "boolean" },
  { name: "init", type: "boolean" },
  { name: "project", shortName: "p", type: "string", isFilePath: true },
  { name: "build", shortName: "b", type: "boolean" },
  { name: "showConfig", type: "boolean" },
  { name: "listFiles", type: "boolean" },
  { name: "listFilesOnly", type: "boolean" },
  { name: "watch", shortName: "w", type: "boolean" },
  { name: "target", shortName: "t", type: scriptTargetMap },
  { name: "module", shortName: "m", type: moduleKindMap },
  { name: "moduleResolution", type: moduleResolutionKindMap },
  { name: "jsx", type: jsxEmitMap },
  { name: "outFile", type: "string", isFilePath: true },
  { name: "outDir", type: "string", isFilePath: true },
  { name: "rootDir", type: "string", isFilePath: true },
  { name: "declaration", shortName: "d", type: "boolean" },
  { name: "declarationDir", type: "string", isFilePath: true },
  { name: "declarationMap", type: "boolean" },
  { name: "sourceMap", type: "boolean" },
  { name: "inlineSourceMap", type: "boolean" },
  { name: "inlineSources", type: "boolean" },
  { name: "noEmit", type: "boolean" },
  { name: "noEmitOnError", type: "boolean" },
  { name: "removeComments", type: "boolean" },
  { name: "preserveConstEnums", type: "boolean" },
  { name: "strict", type: "boolean" },
  { name: "noImplicitAny", type: "boolean" },
  { name: "strictNullChecks", type: "boolean" },
  { name: "strictFunctionTypes", type: "boolean" },
  { name: "strictBindCallApply", type: "boolean" },
  { name: "strictPropertyInitialization", type: "boolean" },
  { name: "noImplicitThis", type: "boolean" },
  { name: "alwaysStrict", type: "boolean" },
  { name: "noUnusedLocals", type: "boolean" },
  { name: "noUnusedParameters", type: "boolean" },
  { name: "noImplicitReturns", type: "boolean" },
  { name: "noFallthroughCasesInSwitch", type: "boolean" },
  { name: "noUncheckedIndexedAccess", type: "boolean" },
  { name: "noPropertyAccessFromIndexSignature", type: "boolean" },
  { name: "allowJs", type: "boolean" },
  { name: "checkJs", type: "boolean" },
  { name: "maxNodeModuleJsDepth", type: "number" },
  { name: "allowSyntheticDefaultImports", type: "boolean" },
  { name: "esModuleInterop", type: "boolean" },
  { name: "isolatedModules", type: "boolean" },
  { name: "isolatedDeclarations", type: "boolean" },
  { name: "verbatimModuleSyntax", type: "boolean" },
  { name: "preserveSymlinks", type: "boolean" },
  { name: "skipLibCheck", type: "boolean" },
  { name: "skipDefaultLibCheck", type: "boolean" },
  { name: "incremental", type: "boolean" },
  { name: "composite", type: "boolean" },
  { name: "tsBuildInfoFile", type: "string", isFilePath: true },
  { name: "stripInternal", type: "boolean" },
  { name: "importHelpers", type: "boolean" },
  { name: "experimentalDecorators", type: "boolean" },
  { name: "emitDecoratorMetadata", type: "boolean" },
  { name: "useDefineForClassFields", type: "boolean" },
  { name: "noLib", type: "boolean" },
  { name: "lib", type: "list", element: { name: "lib", type: "string" } },
  { name: "types", type: "list", element: { name: "types", type: "string" } },
  { name: "typeRoots", type: "list", element: { name: "typeRoots", type: "string", isFilePath: true } },
  { name: "paths", type: "object" },
  { name: "baseUrl", type: "string", isFilePath: true },
  { name: "rootDirs", type: "list", element: { name: "rootDirs", type: "string", isFilePath: true } },
  { name: "moduleDetection", type: "string" },
  { name: "resolveJsonModule", type: "boolean" },
  { name: "resolvePackageJsonExports", type: "boolean" },
  { name: "resolvePackageJsonImports", type: "boolean" },
  { name: "customConditions", type: "list", element: { name: "customConditions", type: "string" } },
  { name: "rewriteRelativeImportExtensions", type: "boolean" },
  { name: "allowImportingTsExtensions", type: "boolean" },
  { name: "forceConsistentCasingInFileNames", type: "boolean" },
  { name: "diagnostics", type: "boolean" },
  { name: "extendedDiagnostics", type: "boolean" },
  { name: "traceResolution", type: "boolean" },
  { name: "explainFiles", type: "boolean" },
  { name: "newLine", type: "string" },
];
