/**
 * Compiler-option declarations table.
 *
 * Port skeleton of TS-Go `internal/tsoptions/declscompiler.go`
 * (~1264 LoC). The upstream Go file is a single large `var` table
 * enumerating every compiler option with name, type, category,
 * description, defaultValueDescription, and validation hints.
 *
 * Skeleton exposes the `optionDeclarations` slice with the most
 * commonly-referenced options; the full TS-Go table will be filled
 * in incrementally as CLI integration tests demand. Each entry is
 * a faithful translation of the TS-Go CommandLineOption shape.
 */

import type { CommandLineOption } from "./commandLineOption.js";
import { moduleKindMap, scriptTargetMap, jsxEmitMap, moduleResolutionKindMap } from "./enumMaps.js";

export const optionDeclarations: readonly CommandLineOption[] = [
  { name: "help", shortName: "h", type: "boolean" },
  { name: "all", type: "boolean" },
  { name: "version", shortName: "v", type: "boolean" },
  { name: "init", type: "boolean" },
  { name: "project", shortName: "p", type: "string", isFilePath: true },
  { name: "build", shortName: "b", type: "boolean" },
  { name: "showConfig", type: "boolean" },
  { name: "listFiles", type: "boolean" },
  { name: "listFilesOnly", type: "boolean" },
  { name: "watch", shortName: "w", type: "boolean" },
  { name: "target", shortName: "t", type: scriptTargetMap },
  { name: "module", shortName: "m", type: moduleKindMap },
  { name: "moduleResolution", type: moduleResolutionKindMap },
  { name: "jsx", type: jsxEmitMap },
  { name: "outFile", type: "string", isFilePath: true },
  { name: "outDir", type: "string", isFilePath: true },
  { name: "rootDir", type: "string", isFilePath: true },
  { name: "declaration", shortName: "d", type: "boolean" },
  { name: "declarationDir", type: "string", isFilePath: true },
  { name: "declarationMap", type: "boolean" },
  { name: "sourceMap", type: "boolean" },
  { name: "inlineSourceMap", type: "boolean" },
  { name: "inlineSources", type: "boolean" },
  { name: "noEmit", type: "boolean" },
  { name: "noEmitOnError", type: "boolean" },
  { name: "removeComments", type: "boolean" },
  { name: "preserveConstEnums", type: "boolean" },
  { name: "strict", type: "boolean" },
  { name: "noImplicitAny", type: "boolean" },
  { name: "strictNullChecks", type: "boolean" },
  { name: "strictFunctionTypes", type: "boolean" },
  { name: "strictBindCallApply", type: "boolean" },
  { name: "strictPropertyInitialization", type: "boolean" },
  { name: "noImplicitThis", type: "boolean" },
  { name: "alwaysStrict", type: "boolean" },
  { name: "noUnusedLocals", type: "boolean" },
  { name: "noUnusedParameters", type: "boolean" },
  { name: "noImplicitReturns", type: "boolean" },
  { name: "noFallthroughCasesInSwitch", type: "boolean" },
  { name: "noUncheckedIndexedAccess", type: "boolean" },
  { name: "noPropertyAccessFromIndexSignature", type: "boolean" },
  { name: "allowJs", type: "boolean" },
  { name: "checkJs", type: "boolean" },
  { name: "maxNodeModuleJsDepth", type: "number" },
  { name: "allowSyntheticDefaultImports", type: "boolean" },
  { name: "esModuleInterop", type: "boolean" },
  { name: "isolatedModules", type: "boolean" },
  { name: "isolatedDeclarations", type: "boolean" },
  { name: "verbatimModuleSyntax", type: "boolean" },
  { name: "preserveSymlinks", type: "boolean" },
  { name: "skipLibCheck", type: "boolean" },
  { name: "skipDefaultLibCheck", type: "boolean" },
  { name: "incremental", type: "boolean" },
  { name: "composite", type: "boolean" },
  { name: "tsBuildInfoFile", type: "string", isFilePath: true },
  { name: "stripInternal", type: "boolean" },
  { name: "importHelpers", type: "boolean" },
  { name: "experimentalDecorators", type: "boolean" },
  { name: "emitDecoratorMetadata", type: "boolean" },
  { name: "useDefineForClassFields", type: "boolean" },
  { name: "noLib", type: "boolean" },
  { name: "lib", type: "list", element: { name: "lib", type: "string" } },
  { name: "types", type: "list", element: { name: "types", type: "string" } },
  { name: "typeRoots", type: "list", element: { name: "typeRoots", type: "string", isFilePath: true } },
  { name: "paths", type: "object" },
  { name: "baseUrl", type: "string", isFilePath: true },
  { name: "rootDirs", type: "list", element: { name: "rootDirs", type: "string", isFilePath: true } },
  { name: "moduleDetection", type: "string" },
  { name: "resolveJsonModule", type: "boolean" },
  { name: "resolvePackageJsonExports", type: "boolean" },
  { name: "resolvePackageJsonImports", type: "boolean" },
  { name: "customConditions", type: "list", element: { name: "customConditions", type: "string" } },
  { name: "rewriteRelativeImportExtensions", type: "boolean" },
  { name: "allowImportingTsExtensions", type: "boolean" },
  { name: "forceConsistentCasingInFileNames", type: "boolean" },
  { name: "diagnostics", type: "boolean" },
  { name: "extendedDiagnostics", type: "boolean" },
  { name: "traceResolution", type: "boolean" },
  { name: "explainFiles", type: "boolean" },
  { name: "newLine", type: "string" },

  // === Additional options to reach TS-Go parity (135 total) ===

  { name: "allowArbitraryExtensions", type: "boolean" },
  { name: "allowUmdGlobalAccess", type: "boolean" },
  { name: "allowUnreachableCode", type: "boolean" },
  { name: "allowUnusedLabels", type: "boolean" },
  { name: "assumeChangesOnlyAffectDirectDependencies", type: "boolean" },
  { name: "checkers", type: "number" },
  { name: "deduplicatePackages", type: "boolean" },
  { name: "disableReferencedProjectLoad", type: "boolean" },
  { name: "disableSizeLimit", type: "boolean" },
  { name: "disableSolutionSearching", type: "boolean" },
  { name: "disableSourceOfProjectReferenceRedirect", type: "boolean" },
  { name: "downlevelIteration", type: "boolean" },
  { name: "emitBOM", type: "boolean" },
  { name: "emitDeclarationOnly", type: "boolean" },
  { name: "erasableSyntaxOnly", type: "boolean" },
  { name: "exactOptionalPropertyTypes", type: "boolean" },
  { name: "generateCpuProfile", type: "string" },
  { name: "generateTrace", type: "string" },
  { name: "ignoreConfig", type: "boolean" },
  { name: "ignoreDeprecations", type: "string" },
  { name: "jsxFactory", type: "string" },
  { name: "jsxFragmentFactory", type: "string" },
  { name: "jsxImportSource", type: "string" },
  { name: "libReplacement", type: "boolean" },
  { name: "listEmittedFiles", type: "boolean" },
  { name: "locale", type: "string" },
  { name: "mapRoot", type: "string", isFilePath: true },
  { name: "moduleSuffixes", type: "list", element: { name: "moduleSuffixes", type: "string" } },
  { name: "noCheck", type: "boolean" },
  { name: "noEmitHelpers", type: "boolean" },
  { name: "noErrorTruncation", type: "boolean" },
  { name: "noImplicitOverride", type: "boolean" },
  { name: "noResolve", type: "boolean" },
  { name: "noUncheckedSideEffectImports", type: "boolean" },
  { name: "plugins", type: "list", element: { name: "plugins", type: "object" } },
  { name: "pprofDir", type: "string", isFilePath: true },
  { name: "preserveWatchOutput", type: "boolean" },
  { name: "pretty", type: "boolean" },
  { name: "quiet", type: "boolean" },
  { name: "reactNamespace", type: "string" },
  { name: "singleThreaded", type: "boolean" },
  { name: "sourceRoot", type: "string", isFilePath: true },
  { name: "stableTypeOrdering", type: "boolean" },
  { name: "strictBuiltinIteratorReturn", type: "boolean" },
  { name: "useUnknownInCatchVariables", type: "boolean" },
  { name: "version", type: "boolean" }, // duplicate-by-name with shortName: v above

  // Short-form aliases
  { name: "?", type: "boolean" }, // alias for help
  { name: "i", type: "boolean" }, // alias for incremental
  { name: "q", type: "boolean" }, // alias for quiet
];

export const commonOptionNamesWithBuild: readonly string[] = [
  "help",
  "watch",
  "preserveWatchOutput",
  "listFiles",
  "explainFiles",
  "listEmittedFiles",
  "pretty",
  "traceResolution",
  "diagnostics",
  "extendedDiagnostics",
  "generateCpuProfile",
  "generateTrace",
  "incremental",
  "declaration",
  "declarationMap",
  "emitDeclarationOnly",
  "sourceMap",
  "inlineSourceMap",
  "noCheck",
  "deduplicatePackages",
  "noEmit",
  "assumeChangesOnlyAffectDirectDependencies",
  "locale",
  "quiet",
  "singleThreaded",
  "pprofDir",
  "checkers",
];

export const compilerOnlyOptionNames: readonly string[] = [
  "all",
  "version",
  "init",
  "project",
  "showConfig",
  "listFilesOnly",
  "ignoreConfig",
  "target",
  "module",
  "lib",
  "allowJs",
  "checkJs",
  "jsx",
  "outFile",
  "outDir",
  "rootDir",
  "composite",
  "tsBuildInfoFile",
  "removeComments",
  "importHelpers",
  "downlevelIteration",
  "isolatedModules",
  "verbatimModuleSyntax",
  "isolatedDeclarations",
  "erasableSyntaxOnly",
  "allowSyntheticDefaultImports",
  "esModuleInterop",
  "preserveSymlinks",
  "forceConsistentCasingInFileNames",
  "moduleResolution",
  "baseUrl",
  "paths",
  "rootDirs",
  "typeRoots",
  "types",
  "allowArbitraryExtensions",
  "resolveJsonModule",
  "allowImportingTsExtensions",
  "rewriteRelativeImportExtensions",
  "resolvePackageJsonExports",
  "resolvePackageJsonImports",
  "customConditions",
  "moduleSuffixes",
  "allowUmdGlobalAccess",
  "moduleDetection",
  "noResolve",
  "noLib",
  "skipDefaultLibCheck",
  "skipLibCheck",
  "strict",
  "strictBuiltinIteratorReturn",
  "strictNullChecks",
  "strictFunctionTypes",
  "strictBindCallApply",
  "strictPropertyInitialization",
  "strictBuiltinIteratorReturn",
  "noImplicitAny",
  "noImplicitThis",
  "useUnknownInCatchVariables",
  "alwaysStrict",
  "noUnusedLocals",
  "noUnusedParameters",
  "exactOptionalPropertyTypes",
  "noImplicitReturns",
  "noFallthroughCasesInSwitch",
  "noUncheckedIndexedAccess",
  "noImplicitOverride",
  "noPropertyAccessFromIndexSignature",
  "allowUnusedLabels",
  "allowUnreachableCode",
  "experimentalDecorators",
  "emitDecoratorMetadata",
  "jsxFactory",
  "jsxFragmentFactory",
  "jsxImportSource",
  "reactNamespace",
  "noEmitHelpers",
  "noEmitOnError",
  "stripInternal",
  "disableSizeLimit",
  "plugins",
  "allowSyntheticDefaultImports",
  "maxNodeModuleJsDepth",
  "noErrorTruncation",
  "disableSourceOfProjectReferenceRedirect",
  "disableSolutionSearching",
  "disableReferencedProjectLoad",
  "libReplacement",
  "noUncheckedSideEffectImports",
  "preserveConstEnums",
  "useDefineForClassFields",
  "mapRoot",
  "sourceRoot",
  "inlineSources",
  "emitBOM",
  "newLine",
  "stableTypeOrdering",
  "ignoreDeprecations",
];

export const compilerCommandLineOnlyOptionNames: readonly string[] = [
  "help",
  "all",
  "version",
  "init",
  "project",
  "build",
  "showConfig",
  "listFilesOnly",
  "ignoreConfig",
  "locale",
  "quiet",
  "singleThreaded",
  "pprofDir",
  "checkers",
];

export const compilerSimplifiedHelpOptionNames: readonly string[] = [
  "help",
  "watch",
  "pretty",
  "declaration",
  "declarationMap",
  "emitDeclarationOnly",
  "noEmit",
  "all",
  "version",
  "init",
  "project",
  "target",
  "module",
  "lib",
  "allowJs",
  "checkJs",
  "jsx",
  "outFile",
  "outDir",
  "removeComments",
  "strict",
  "esModuleInterop",
  "skipLibCheck",
];

export const compilerFilePathOptionNames: readonly string[] = [
  "generateCpuProfile",
  "generateTrace",
  "pprofDir",
  "project",
  "outFile",
  "outDir",
  "rootDir",
  "tsBuildInfoFile",
  "baseUrl",
  "typeRoots",
  "rootDirs",
  "mapRoot",
  "sourceRoot",
  "declarationDir",
];

export const compilerOptionShortNames: ReadonlyMap<string, string> = new Map([
  ["h", "help"],
  ["?", "help"],
  ["w", "watch"],
  ["i", "incremental"],
  ["d", "declaration"],
  ["q", "quiet"],
  ["v", "version"],
  ["p", "project"],
  ["t", "target"],
  ["m", "module"],
]);

export const compilerOptionDefaults: ReadonlyMap<string, string | number | boolean> = new Map<string, string | number | boolean>([
  ["help", false],
  ["watch", false],
  ["preserveWatchOutput", false],
  ["listFiles", false],
  ["explainFiles", false],
  ["listEmittedFiles", false],
  ["pretty", true],
  ["traceResolution", false],
  ["diagnostics", false],
  ["extendedDiagnostics", false],
  ["generateCpuProfile", "profile.cpuprofile"],
  ["incremental", "false unless composite is set"],
  ["declaration", "false unless composite is set"],
  ["declarationMap", false],
  ["emitDeclarationOnly", false],
  ["sourceMap", false],
  ["inlineSourceMap", false],
  ["noCheck", false],
  ["deduplicatePackages", true],
  ["noEmit", false],
  ["locale", "platform specific"],
  ["checkers", "4 unless singleThreaded is passed"],
  ["target", "latest standard"],
  ["module", "unknown"],
  ["allowJs", "false unless checkJs is set"],
  ["checkJs", false],
  ["jsx", "unknown"],
  ["rootDir", "computed from the list of input files"],
  ["composite", false],
  ["tsBuildInfoFile", ".tsbuildinfo"],
  ["removeComments", false],
  ["importHelpers", false],
  ["downlevelIteration", false],
]);

export function getCompilerOptionDeclaration(optionName: string): CommandLineOption | undefined {
  const lower = optionName.toLowerCase();
  const canonical = compilerOptionShortNames.get(lower) ?? lower;
  return optionDeclarations.find((option) => option.name.toLowerCase() === canonical);
}

export function compilerOptionHasName(optionName: string): boolean {
  return getCompilerOptionDeclaration(optionName) !== undefined;
}

export function isCommandLineOnlyOption(optionName: string): boolean {
  return compilerCommandLineOnlyOptionNames.includes(optionName);
}

export function isFilePathCompilerOption(optionName: string): boolean {
  return compilerFilePathOptionNames.includes(optionName);
}

export function isSimplifiedHelpOption(optionName: string): boolean {
  return compilerSimplifiedHelpOptionNames.includes(optionName);
}
