/**
 * Strict TS-Go parity gap map for `tsoptions`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const tsoptionsStrictParityUpstreamModule = "tsoptions";
export const tsoptionsStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"commandlineoption.go","line":1,"text":"package tsoptions"},
  {"file":"commandlineoption.go","line":3,"text":"import ("},
  {"file":"commandlineoption.go","line":4,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"commandlineoption.go","line":5,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"commandlineoption.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"commandlineoption.go","line":7,"text":")"},
  {"file":"commandlineoption.go","line":9,"text":"type CommandLineOptionKind string"},
  {"file":"commandlineoption.go","line":11,"text":"const ("},
  {"file":"commandlineoption.go","line":12,"text":"\tCommandLineOptionTypeString        CommandLineOptionKind = \"string\""},
  {"file":"commandlineoption.go","line":13,"text":"\tCommandLineOptionTypeNumber        CommandLineOptionKind = \"number\""},
  {"file":"commandlineoption.go","line":14,"text":"\tCommandLineOptionTypeBoolean       CommandLineOptionKind = \"boolean\""},
  {"file":"commandlineoption.go","line":15,"text":"\tCommandLineOptionTypeObject        CommandLineOptionKind = \"object\""},
  {"file":"commandlineoption.go","line":16,"text":"\tCommandLineOptionTypeList          CommandLineOptionKind = \"list\""},
  {"file":"commandlineoption.go","line":17,"text":"\tCommandLineOptionTypeListOrElement CommandLineOptionKind = \"listOrElement\""},
  {"file":"commandlineoption.go","line":18,"text":"\tCommandLineOptionTypeEnum          CommandLineOptionKind = \"enum\" // map"},
  {"file":"commandlineoption.go","line":19,"text":")"},
  {"file":"commandlineoption.go","line":21,"text":"type CommandLineOption struct {"},
  {"file":"commandlineoption.go","line":22,"text":"\tName, ShortName string"},
  {"file":"commandlineoption.go","line":23,"text":"\tKind            CommandLineOptionKind"},
  {"file":"commandlineoption.go","line":26,"text":"\tIsFilePath        bool"},
  {"file":"commandlineoption.go","line":27,"text":"\tIsTSConfigOnly    bool"},
  {"file":"commandlineoption.go","line":28,"text":"\tIsCommandLineOnly bool"},
  {"file":"commandlineoption.go","line":31,"text":"\tDescription              *diagnostics.Message"},
  {"file":"commandlineoption.go","line":32,"text":"\tDefaultValueDescription  any"},
  {"file":"commandlineoption.go","line":33,"text":"\tShowInSimplifiedHelpView bool"},
  {"file":"commandlineoption.go","line":36,"text":"\tCategory *diagnostics.Message"},
  {"file":"commandlineoption.go","line":39,"text":"\textraValidation extraValidation"},
  {"file":"commandlineoption.go","line":42,"text":"\tminValue int"},
  {"file":"commandlineoption.go","line":46,"text":"\tallowConfigDirTemplateSubstitution bool"},
  {"file":"commandlineoption.go","line":49,"text":"\tAffectsDeclarationPath     bool"},
  {"file":"commandlineoption.go","line":50,"text":"\tAffectsProgramStructure    bool"},
  {"file":"commandlineoption.go","line":51,"text":"\tAffectsSemanticDiagnostics bool"},
  {"file":"commandlineoption.go","line":52,"text":"\tAffectsBuildInfo           bool"},
  {"file":"commandlineoption.go","line":53,"text":"\tAffectsBindDiagnostics     bool"},
  {"file":"commandlineoption.go","line":54,"text":"\tAffectsSourceFile          bool"},
  {"file":"commandlineoption.go","line":55,"text":"\tAffectsModuleResolution    bool"},
  {"file":"commandlineoption.go","line":56,"text":"\tAffectsEmit                bool"},
  {"file":"commandlineoption.go","line":58,"text":"\tallowJsFlag bool"},
  {"file":"commandlineoption.go","line":59,"text":"\tstrictFlag  bool"},
  {"file":"commandlineoption.go","line":63,"text":"\ttranspileOptionValue core.Tristate"},
  {"file":"commandlineoption.go","line":66,"text":"\tlistPreserveFalsyValues bool"},
  {"file":"commandlineoption.go","line":68,"text":"\tElementOptions CommandLineOptionNameMap"},
  {"file":"commandlineoption.go","line":69,"text":"}"},
  {"file":"commandlineoption.go","line":71,"text":"type extraValidation string"},
  {"file":"commandlineoption.go","line":73,"text":"const ("},
  {"file":"commandlineoption.go","line":74,"text":"\textraValidationNone   extraValidation = \"\""},
  {"file":"commandlineoption.go","line":75,"text":"\textraValidationSpec   extraValidation = \"spec\""},
  {"file":"commandlineoption.go","line":76,"text":"\textraValidationLocale extraValidation = \"locale\""},
  {"file":"commandlineoption.go","line":77,"text":")"},
  {"file":"commandlineoption.go","line":79,"text":"func (o *CommandLineOption) DeprecatedKeys() *collections.Set[string] {"},
  {"file":"commandlineoption.go","line":80,"text":"\tif o.Kind != CommandLineOptionTypeEnum {"},
  {"file":"commandlineoption.go","line":81,"text":"\t\treturn nil"},
  {"file":"commandlineoption.go","line":82,"text":"\t}"},
  {"file":"commandlineoption.go","line":83,"text":"\treturn commandLineOptionDeprecated[o.Name]"},
  {"file":"commandlineoption.go","line":84,"text":"}"},
  {"file":"commandlineoption.go","line":86,"text":"func (o *CommandLineOption) EnumMap() *collections.OrderedMap[string, any] {"},
  {"file":"commandlineoption.go","line":87,"text":"\tif o.Kind != CommandLineOptionTypeEnum {"},
  {"file":"commandlineoption.go","line":88,"text":"\t\treturn nil"},
  {"file":"commandlineoption.go","line":89,"text":"\t}"},
  {"file":"commandlineoption.go","line":90,"text":"\treturn commandLineOptionEnumMap[o.Name]"},
  {"file":"commandlineoption.go","line":91,"text":"}"},
  {"file":"commandlineoption.go","line":93,"text":"func (o *CommandLineOption) Elements() *CommandLineOption {"},
  {"file":"commandlineoption.go","line":94,"text":"\tif o.Kind != CommandLineOptionTypeList && o.Kind != CommandLineOptionTypeListOrElement {"},
  {"file":"commandlineoption.go","line":95,"text":"\t\treturn nil"},
  {"file":"commandlineoption.go","line":96,"text":"\t}"},
  {"file":"commandlineoption.go","line":97,"text":"\treturn commandLineOptionElements[o.Name]"},
  {"file":"commandlineoption.go","line":98,"text":"}"},
  {"file":"commandlineoption.go","line":100,"text":"func (o *CommandLineOption) DisallowNullOrUndefined() bool {"},
  {"file":"commandlineoption.go","line":101,"text":"\treturn o.Name == \"extends\""},
  {"file":"commandlineoption.go","line":102,"text":"}"},
  {"file":"commandlineoption.go","line":105,"text":"var commandLineOptionElements = map[string]*CommandLineOption{"},
  {"file":"commandlineoption.go","line":106,"text":"\t\"lib\": {"},
  {"file":"commandlineoption.go","line":107,"text":"\t\tName:                    \"lib\","},
  {"file":"commandlineoption.go","line":108,"text":"\t\tKind:                    CommandLineOptionTypeEnum, // libMap,"},
  {"file":"commandlineoption.go","line":109,"text":"\t\tDefaultValueDescription: core.TSUnknown,"},
  {"file":"commandlineoption.go","line":110,"text":"\t},"},
  {"file":"commandlineoption.go","line":111,"text":"\t\"rootDirs\": {"},
  {"file":"commandlineoption.go","line":112,"text":"\t\tName:       \"rootDirs\","},
  {"file":"commandlineoption.go","line":113,"text":"\t\tKind:       CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":114,"text":"\t\tIsFilePath: true,"},
  {"file":"commandlineoption.go","line":115,"text":"\t},"},
  {"file":"commandlineoption.go","line":116,"text":"\t\"typeRoots\": {"},
  {"file":"commandlineoption.go","line":117,"text":"\t\tName:       \"typeRoots\","},
  {"file":"commandlineoption.go","line":118,"text":"\t\tKind:       CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":119,"text":"\t\tIsFilePath: true,"},
  {"file":"commandlineoption.go","line":120,"text":"\t},"},
  {"file":"commandlineoption.go","line":121,"text":"\t\"types\": {"},
  {"file":"commandlineoption.go","line":122,"text":"\t\tName: \"types\","},
  {"file":"commandlineoption.go","line":123,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":124,"text":"\t},"},
  {"file":"commandlineoption.go","line":125,"text":"\t\"moduleSuffixes\": {"},
  {"file":"commandlineoption.go","line":126,"text":"\t\tName: \"moduleSuffixes\","},
  {"file":"commandlineoption.go","line":127,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":128,"text":"\t},"},
  {"file":"commandlineoption.go","line":129,"text":"\t\"customConditions\": {"},
  {"file":"commandlineoption.go","line":130,"text":"\t\tName: \"condition\","},
  {"file":"commandlineoption.go","line":131,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":132,"text":"\t},"},
  {"file":"commandlineoption.go","line":133,"text":"\t\"plugins\": {"},
  {"file":"commandlineoption.go","line":134,"text":"\t\tName: \"plugin\","},
  {"file":"commandlineoption.go","line":135,"text":"\t\tKind: CommandLineOptionTypeObject,"},
  {"file":"commandlineoption.go","line":136,"text":"\t},"},
  {"file":"commandlineoption.go","line":138,"text":"\t\"references\": {"},
  {"file":"commandlineoption.go","line":139,"text":"\t\tName: \"references\","},
  {"file":"commandlineoption.go","line":140,"text":"\t\tKind: CommandLineOptionTypeObject,"},
  {"file":"commandlineoption.go","line":141,"text":"\t},"},
  {"file":"commandlineoption.go","line":142,"text":"\t\"files\": {"},
  {"file":"commandlineoption.go","line":143,"text":"\t\tName: \"files\","},
  {"file":"commandlineoption.go","line":144,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":145,"text":"\t},"},
  {"file":"commandlineoption.go","line":146,"text":"\t\"include\": {"},
  {"file":"commandlineoption.go","line":147,"text":"\t\tName: \"include\","},
  {"file":"commandlineoption.go","line":148,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":149,"text":"\t},"},
  {"file":"commandlineoption.go","line":150,"text":"\t\"exclude\": {"},
  {"file":"commandlineoption.go","line":151,"text":"\t\tName: \"exclude\","},
  {"file":"commandlineoption.go","line":152,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":153,"text":"\t},"},
  {"file":"commandlineoption.go","line":154,"text":"\t\"extends\": {"},
  {"file":"commandlineoption.go","line":155,"text":"\t\tName: \"extends\","},
  {"file":"commandlineoption.go","line":156,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":157,"text":"\t},"},
  {"file":"commandlineoption.go","line":159,"text":"\t\"excludeDirectories\": {"},
  {"file":"commandlineoption.go","line":160,"text":"\t\tName:            \"excludeDirectory\","},
  {"file":"commandlineoption.go","line":161,"text":"\t\tKind:            CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":162,"text":"\t\tIsFilePath:      true,"},
  {"file":"commandlineoption.go","line":163,"text":"\t\textraValidation: extraValidationSpec,"},
  {"file":"commandlineoption.go","line":164,"text":"\t},"},
  {"file":"commandlineoption.go","line":165,"text":"\t\"excludeFiles\": {"},
  {"file":"commandlineoption.go","line":166,"text":"\t\tName:            \"excludeFile\","},
  {"file":"commandlineoption.go","line":167,"text":"\t\tKind:            CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":168,"text":"\t\tIsFilePath:      true,"},
  {"file":"commandlineoption.go","line":169,"text":"\t\textraValidation: extraValidationSpec,"},
  {"file":"commandlineoption.go","line":170,"text":"\t},"},
  {"file":"commandlineoption.go","line":172,"text":"\t\"libFiles\": {"},
  {"file":"commandlineoption.go","line":173,"text":"\t\tName: \"libFiles\","},
  {"file":"commandlineoption.go","line":174,"text":"\t\tKind: CommandLineOptionTypeString,"},
  {"file":"commandlineoption.go","line":175,"text":"\t},"},
  {"file":"commandlineoption.go","line":176,"text":"}"},
  {"file":"commandlineoption.go","line":179,"text":"var commandLineOptionEnumMap = map[string]*collections.OrderedMap[string, any]{"},
  {"file":"commandlineoption.go","line":180,"text":"\t\"lib\":              LibMap,"},
  {"file":"commandlineoption.go","line":181,"text":"\t\"moduleResolution\": moduleResolutionOptionMap,"},
  {"file":"commandlineoption.go","line":182,"text":"\t\"module\":           moduleOptionMap,"},
  {"file":"commandlineoption.go","line":183,"text":"\t\"target\":           targetOptionMap,"},
  {"file":"commandlineoption.go","line":184,"text":"\t\"moduleDetection\":  moduleDetectionOptionMap,"},
  {"file":"commandlineoption.go","line":185,"text":"\t\"jsx\":              jsxOptionMap,"},
  {"file":"commandlineoption.go","line":186,"text":"\t\"newLine\":          newLineOptionMap,"},
  {"file":"commandlineoption.go","line":187,"text":"\t\"watchFile\":        watchFileEnumMap,"},
  {"file":"commandlineoption.go","line":188,"text":"\t\"watchDirectory\":   watchDirectoryEnumMap,"},
  {"file":"commandlineoption.go","line":189,"text":"\t\"fallbackPolling\":  fallbackEnumMap,"},
  {"file":"commandlineoption.go","line":190,"text":"}"},
  {"file":"commandlineoption.go","line":193,"text":"var commandLineOptionDeprecated = map[string]*collections.Set[string]{"},
  {"file":"commandlineoption.go","line":194,"text":"\t\"module\":           collections.NewSetFromItems(\"none\", \"amd\", \"system\", \"umd\"),"},
  {"file":"commandlineoption.go","line":195,"text":"\t\"moduleResolution\": collections.NewSetFromItems(\"node\", \"classic\", \"node10\"),"},
  {"file":"commandlineoption.go","line":196,"text":"\t\"target\":           collections.NewSetFromItems(\"es5\"),"},
  {"file":"commandlineoption.go","line":197,"text":"}"},
  {"file":"commandlineoption.go","line":200,"text":"type CompilerOptionsValue any"},
  {"file":"commandlineparser.go","line":1,"text":"package tsoptions"},
  {"file":"commandlineparser.go","line":3,"text":"import ("},
  {"file":"commandlineparser.go","line":4,"text":"\t\"strconv\""},
  {"file":"commandlineparser.go","line":5,"text":"\t\"strings\""},
  {"file":"commandlineparser.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"commandlineparser.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"commandlineparser.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"commandlineparser.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"commandlineparser.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"file":"commandlineparser.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"commandlineparser.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"file":"commandlineparser.go","line":14,"text":")"},
  {"file":"commandlineparser.go","line":16,"text":"func (p *commandLineParser) AlternateMode() *AlternateModeDiagnostics {"},
  {"file":"commandlineparser.go","line":17,"text":"\treturn p.workerDiagnostics.didYouMean.alternateMode"},
  {"file":"commandlineparser.go","line":18,"text":"}"},
  {"file":"commandlineparser.go","line":20,"text":"func (p *commandLineParser) OptionsDeclarations() []*CommandLineOption {"},
  {"file":"commandlineparser.go","line":21,"text":"\treturn p.workerDiagnostics.didYouMean.OptionDeclarations"},
  {"file":"commandlineparser.go","line":22,"text":"}"},
  {"file":"commandlineparser.go","line":24,"text":"func (p *commandLineParser) UnknownOptionDiagnostic() *diagnostics.Message {"},
  {"file":"commandlineparser.go","line":25,"text":"\treturn p.workerDiagnostics.didYouMean.UnknownOptionDiagnostic"},
  {"file":"commandlineparser.go","line":26,"text":"}"},
  {"file":"commandlineparser.go","line":28,"text":"func (p *commandLineParser) UnknownDidYouMeanDiagnostic() *diagnostics.Message {"},
  {"file":"commandlineparser.go","line":29,"text":"\treturn p.workerDiagnostics.didYouMean.UnknownDidYouMeanDiagnostic"},
  {"file":"commandlineparser.go","line":30,"text":"}"},
  {"file":"commandlineparser.go","line":32,"text":"type commandLineParser struct {"},
  {"file":"commandlineparser.go","line":33,"text":"\tworkerDiagnostics *ParseCommandLineWorkerDiagnostics"},
  {"file":"commandlineparser.go","line":34,"text":"\toptionsMap        *NameMap"},
  {"file":"commandlineparser.go","line":35,"text":"\tfs                vfs.FS"},
  {"file":"commandlineparser.go","line":36,"text":"\toptions           *collections.OrderedMap[string, any]"},
  {"file":"commandlineparser.go","line":37,"text":"\tfileNames         []string"},
  {"file":"commandlineparser.go","line":38,"text":"\terrors            []*ast.Diagnostic"},
  {"file":"commandlineparser.go","line":39,"text":"}"},
  {"file":"commandlineparser.go","line":41,"text":"func ParseCommandLine("},
  {"file":"commandlineparser.go","line":42,"text":"\tcommandLine []string,"},
  {"file":"commandlineparser.go","line":43,"text":"\thost ParseConfigHost,"},
  {"file":"commandlineparser.go","line":44,"text":") *ParsedCommandLine {"},
  {"file":"commandlineparser.go","line":45,"text":"\tif commandLine == nil {"},
  {"file":"commandlineparser.go","line":46,"text":"\t\tcommandLine = []string{}"},
  {"file":"commandlineparser.go","line":47,"text":"\t}"},
  {"file":"commandlineparser.go","line":48,"text":"\tparser := parseCommandLineWorker(CompilerOptionsDidYouMeanDiagnostics, commandLine, host.FS())"},
  {"file":"commandlineparser.go","line":49,"text":"\toptionsWithAbsolutePaths := convertToOptionsWithAbsolutePaths(parser.options.Clone(), CommandLineCompilerOptionsMap, host.GetCurrentDirectory())"},
  {"file":"commandlineparser.go","line":50,"text":"\tcompilerOptions := convertMapToOptions(optionsWithAbsolutePaths, &compilerOptionsParser{&core.CompilerOptions{}}).CompilerOptions"},
  {"file":"commandlineparser.go","line":51,"text":"\twatchOptions := convertMapToOptions(optionsWithAbsolutePaths, &watchOptionsParser{&core.WatchOptions{}}).WatchOptions"},
  {"file":"commandlineparser.go","line":52,"text":"\tresult := NewParsedCommandLine(compilerOptions, parser.fileNames, tspath.ComparePathsOptions{"},
  {"file":"commandlineparser.go","line":53,"text":"\t\tUseCaseSensitiveFileNames: host.FS().UseCaseSensitiveFileNames(),"},
  {"file":"commandlineparser.go","line":54,"text":"\t\tCurrentDirectory:          host.GetCurrentDirectory(),"},
  {"file":"commandlineparser.go","line":55,"text":"\t})"},
  {"file":"commandlineparser.go","line":56,"text":"\tresult.ParsedConfig.WatchOptions = watchOptions"},
  {"file":"commandlineparser.go","line":57,"text":"\tresult.Errors = parser.errors"},
  {"file":"commandlineparser.go","line":58,"text":"\tresult.Raw = parser.options"},
  {"file":"commandlineparser.go","line":59,"text":"\treturn result"},
  {"file":"commandlineparser.go","line":60,"text":"}"},
  {"file":"commandlineparser.go","line":62,"text":"func ParseBuildCommandLine("},
  {"file":"commandlineparser.go","line":63,"text":"\tcommandLine []string,"},
  {"file":"commandlineparser.go","line":64,"text":"\thost ParseConfigHost,"},
  {"file":"commandlineparser.go","line":65,"text":") *ParsedBuildCommandLine {"},
  {"file":"commandlineparser.go","line":66,"text":"\tif commandLine == nil {"},
  {"file":"commandlineparser.go","line":67,"text":"\t\tcommandLine = []string{}"},
  {"file":"commandlineparser.go","line":68,"text":"\t}"},
  {"file":"commandlineparser.go","line":69,"text":"\tparser := parseCommandLineWorker(buildOptionsDidYouMeanDiagnostics, commandLine, host.FS())"},
  {"file":"commandlineparser.go","line":70,"text":"\tcompilerOptions := &core.CompilerOptions{}"},
  {"file":"commandlineparser.go","line":71,"text":"\tfor key, value := range parser.options.Entries() {"},
  {"file":"commandlineparser.go","line":72,"text":"\t\tbuildOption := BuildNameMap.Get(key)"},
  {"file":"commandlineparser.go","line":73,"text":"\t\tif buildOption == &TscBuildOption || buildOption == CompilerNameMap.Get(key) {"},
  {"file":"commandlineparser.go","line":74,"text":"\t\t\tParseCompilerOptions(key, value, compilerOptions)"},
  {"file":"commandlineparser.go","line":75,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":76,"text":"\t}"},
  {"file":"commandlineparser.go","line":77,"text":"\tresult := &ParsedBuildCommandLine{"},
  {"file":"commandlineparser.go","line":78,"text":"\t\tBuildOptions:    convertMapToOptions(parser.options, &buildOptionsParser{&core.BuildOptions{}}).BuildOptions,"},
  {"file":"commandlineparser.go","line":79,"text":"\t\tCompilerOptions: compilerOptions,"},
  {"file":"commandlineparser.go","line":80,"text":"\t\tWatchOptions:    convertMapToOptions(parser.options, &watchOptionsParser{&core.WatchOptions{}}).WatchOptions,"},
  {"file":"commandlineparser.go","line":81,"text":"\t\tProjects:        parser.fileNames,"},
  {"file":"commandlineparser.go","line":82,"text":"\t\tErrors:          parser.errors,"},
  {"file":"commandlineparser.go","line":83,"text":"\t\tRaw:             parser.options,"},
  {"file":"commandlineparser.go","line":85,"text":"\t\tcomparePathsOptions: tspath.ComparePathsOptions{"},
  {"file":"commandlineparser.go","line":86,"text":"\t\t\tUseCaseSensitiveFileNames: host.FS().UseCaseSensitiveFileNames(),"},
  {"file":"commandlineparser.go","line":87,"text":"\t\t\tCurrentDirectory:          host.GetCurrentDirectory(),"},
  {"file":"commandlineparser.go","line":88,"text":"\t\t},"},
  {"file":"commandlineparser.go","line":89,"text":"\t}"},
  {"file":"commandlineparser.go","line":91,"text":"\tif len(result.Projects) == 0 {"},
  {"file":"commandlineparser.go","line":93,"text":"\t\tresult.Projects = append(result.Projects, \".\")"},
  {"file":"commandlineparser.go","line":94,"text":"\t}"},
  {"file":"commandlineparser.go","line":97,"text":"\tif result.BuildOptions.Clean.IsTrue() && result.BuildOptions.Force.IsTrue() {"},
  {"file":"commandlineparser.go","line":98,"text":"\t\tresult.Errors = append(result.Errors, ast.NewCompilerDiagnostic(diagnostics.Options_0_and_1_cannot_be_combined, \"clean\", \"force\"))"},
  {"file":"commandlineparser.go","line":99,"text":"\t}"},
  {"file":"commandlineparser.go","line":100,"text":"\tif result.BuildOptions.Clean.IsTrue() && result.BuildOptions.Verbose.IsTrue() {"},
  {"file":"commandlineparser.go","line":101,"text":"\t\tresult.Errors = append(result.Errors, ast.NewCompilerDiagnostic(diagnostics.Options_0_and_1_cannot_be_combined, \"clean\", \"verbose\"))"},
  {"file":"commandlineparser.go","line":102,"text":"\t}"},
  {"file":"commandlineparser.go","line":103,"text":"\tif result.BuildOptions.Clean.IsTrue() && result.CompilerOptions.Watch.IsTrue() {"},
  {"file":"commandlineparser.go","line":104,"text":"\t\tresult.Errors = append(result.Errors, ast.NewCompilerDiagnostic(diagnostics.Options_0_and_1_cannot_be_combined, \"clean\", \"watch\"))"},
  {"file":"commandlineparser.go","line":105,"text":"\t}"},
  {"file":"commandlineparser.go","line":106,"text":"\tif result.CompilerOptions.Watch.IsTrue() && result.BuildOptions.Dry.IsTrue() {"},
  {"file":"commandlineparser.go","line":107,"text":"\t\tresult.Errors = append(result.Errors, ast.NewCompilerDiagnostic(diagnostics.Options_0_and_1_cannot_be_combined, \"watch\", \"dry\"))"},
  {"file":"commandlineparser.go","line":108,"text":"\t}"},
  {"file":"commandlineparser.go","line":110,"text":"\treturn result"},
  {"file":"commandlineparser.go","line":111,"text":"}"},
  {"file":"commandlineparser.go","line":113,"text":"func parseCommandLineWorker("},
  {"file":"commandlineparser.go","line":114,"text":"\tparseCommandLineWithDiagnostics *ParseCommandLineWorkerDiagnostics,"},
  {"file":"commandlineparser.go","line":115,"text":"\tcommandLine []string,"},
  {"file":"commandlineparser.go","line":116,"text":"\tfs vfs.FS,"},
  {"file":"commandlineparser.go","line":117,"text":") *commandLineParser {"},
  {"file":"commandlineparser.go","line":118,"text":"\tparser := &commandLineParser{"},
  {"file":"commandlineparser.go","line":119,"text":"\t\tfs:                fs,"},
  {"file":"commandlineparser.go","line":120,"text":"\t\tworkerDiagnostics: parseCommandLineWithDiagnostics,"},
  {"file":"commandlineparser.go","line":121,"text":"\t\tfileNames:         []string{},"},
  {"file":"commandlineparser.go","line":122,"text":"\t\toptions:           &collections.OrderedMap[string, any]{},"},
  {"file":"commandlineparser.go","line":123,"text":"\t\terrors:            []*ast.Diagnostic{},"},
  {"file":"commandlineparser.go","line":124,"text":"\t}"},
  {"file":"commandlineparser.go","line":125,"text":"\tparser.optionsMap = GetNameMapFromList(parser.OptionsDeclarations())"},
  {"file":"commandlineparser.go","line":126,"text":"\tparser.parseStrings(commandLine)"},
  {"file":"commandlineparser.go","line":127,"text":"\treturn parser"},
  {"file":"commandlineparser.go","line":128,"text":"}"},
  {"file":"commandlineparser.go","line":130,"text":"func (p *commandLineParser) parseStrings(args []string) {"},
  {"file":"commandlineparser.go","line":131,"text":"\ti := 0"},
  {"file":"commandlineparser.go","line":132,"text":"\tfor i < len(args) {"},
  {"file":"commandlineparser.go","line":133,"text":"\t\ts := args[i]"},
  {"file":"commandlineparser.go","line":134,"text":"\t\ti++"},
  {"file":"commandlineparser.go","line":135,"text":"\t\tif s == \"\" {"},
  {"file":"commandlineparser.go","line":136,"text":"\t\t\tcontinue"},
  {"file":"commandlineparser.go","line":137,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":138,"text":"\t\tswitch s[0] {"},
  {"file":"commandlineparser.go","line":139,"text":"\t\tcase '@':"},
  {"file":"commandlineparser.go","line":140,"text":"\t\t\tp.parseResponseFile(s[1:])"},
  {"file":"commandlineparser.go","line":141,"text":"\t\tcase '-':"},
  {"file":"commandlineparser.go","line":142,"text":"\t\t\tinputOptionName := getInputOptionName(s)"},
  {"file":"commandlineparser.go","line":143,"text":"\t\t\topt := p.optionsMap.GetOptionDeclarationFromName(inputOptionName, true /*allowShort*/)"},
  {"file":"commandlineparser.go","line":144,"text":"\t\t\tif opt != nil {"},
  {"file":"commandlineparser.go","line":145,"text":"\t\t\t\ti = p.parseOptionValue(args, i, opt, p.workerDiagnostics.OptionTypeMismatchDiagnostic)"},
  {"file":"commandlineparser.go","line":146,"text":"\t\t\t} else {"},
  {"file":"commandlineparser.go","line":147,"text":"\t\t\t\twatchOpt := WatchNameMap.GetOptionDeclarationFromName(inputOptionName, true /*allowShort*/)"},
  {"file":"commandlineparser.go","line":148,"text":"\t\t\t\tif watchOpt != nil {"},
  {"file":"commandlineparser.go","line":149,"text":"\t\t\t\t\ti = p.parseOptionValue(args, i, watchOpt, watchOptionsDidYouMeanDiagnostics.OptionTypeMismatchDiagnostic)"},
  {"file":"commandlineparser.go","line":150,"text":"\t\t\t\t} else {"},
  {"file":"commandlineparser.go","line":151,"text":"\t\t\t\t\tp.errors = append(p.errors, p.createUnknownOptionError(inputOptionName, s, nil, nil))"},
  {"file":"commandlineparser.go","line":152,"text":"\t\t\t\t}"},
  {"file":"commandlineparser.go","line":153,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":154,"text":"\t\tdefault:"},
  {"file":"commandlineparser.go","line":155,"text":"\t\t\tp.fileNames = append(p.fileNames, s)"},
  {"file":"commandlineparser.go","line":156,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":157,"text":"\t}"},
  {"file":"commandlineparser.go","line":158,"text":"}"},
  {"file":"commandlineparser.go","line":160,"text":"func getInputOptionName(input string) string {"},
  {"file":"commandlineparser.go","line":162,"text":"\treturn strings.TrimPrefix(strings.TrimPrefix(input, \"-\"), \"-\")"},
  {"file":"commandlineparser.go","line":163,"text":"}"},
  {"file":"commandlineparser.go","line":165,"text":"func (p *commandLineParser) parseResponseFile(fileName string) {"},
  {"file":"commandlineparser.go","line":166,"text":"\tfileContents, errors := tryReadFile(fileName, func(fileName string) (string, bool) {"},
  {"file":"commandlineparser.go","line":167,"text":"\t\tif p.fs == nil {"},
  {"file":"commandlineparser.go","line":168,"text":"\t\t\treturn \"\", false"},
  {"file":"commandlineparser.go","line":169,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":170,"text":"\t\tread, err := p.fs.ReadFile(fileName)"},
  {"file":"commandlineparser.go","line":171,"text":"\t\treturn read, err"},
  {"file":"commandlineparser.go","line":172,"text":"\t}, p.errors)"},
  {"file":"commandlineparser.go","line":173,"text":"\tp.errors = errors"},
  {"file":"commandlineparser.go","line":175,"text":"\tif fileContents == \"\" {"},
  {"file":"commandlineparser.go","line":176,"text":"\t\treturn"},
  {"file":"commandlineparser.go","line":177,"text":"\t}"},
  {"file":"commandlineparser.go","line":179,"text":"\tvar args []string"},
  {"file":"commandlineparser.go","line":180,"text":"\ttext := []rune(fileContents)"},
  {"file":"commandlineparser.go","line":181,"text":"\ttextLength := len(text)"},
  {"file":"commandlineparser.go","line":182,"text":"\tpos := 0"},
  {"file":"commandlineparser.go","line":183,"text":"\tfor pos < textLength {"},
  {"file":"commandlineparser.go","line":184,"text":"\t\tfor pos < textLength && text[pos] <= ' ' {"},
  {"file":"commandlineparser.go","line":185,"text":"\t\t\tpos++"},
  {"file":"commandlineparser.go","line":186,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":187,"text":"\t\tif pos >= textLength {"},
  {"file":"commandlineparser.go","line":188,"text":"\t\t\tbreak"},
  {"file":"commandlineparser.go","line":189,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":190,"text":"\t\tstart := pos"},
  {"file":"commandlineparser.go","line":191,"text":"\t\tif text[pos] == '\"' {"},
  {"file":"commandlineparser.go","line":192,"text":"\t\t\tpos++"},
  {"file":"commandlineparser.go","line":193,"text":"\t\t\tfor pos < textLength && text[pos] != '\"' {"},
  {"file":"commandlineparser.go","line":194,"text":"\t\t\t\tpos++"},
  {"file":"commandlineparser.go","line":195,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":196,"text":"\t\t\tif pos < textLength {"},
  {"file":"commandlineparser.go","line":197,"text":"\t\t\t\targs = append(args, string(text[start+1:pos]))"},
  {"file":"commandlineparser.go","line":198,"text":"\t\t\t\tpos++"},
  {"file":"commandlineparser.go","line":199,"text":"\t\t\t} else {"},
  {"file":"commandlineparser.go","line":200,"text":"\t\t\t\tp.errors = append(p.errors, ast.NewCompilerDiagnostic(diagnostics.Unterminated_quoted_string_in_response_file_0, fileName))"},
  {"file":"commandlineparser.go","line":201,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":202,"text":"\t\t} else {"},
  {"file":"commandlineparser.go","line":203,"text":"\t\t\tfor text[pos] > ' ' {"},
  {"file":"commandlineparser.go","line":204,"text":"\t\t\t\tpos++"},
  {"file":"commandlineparser.go","line":205,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":206,"text":"\t\t\targs = append(args, string(text[start:pos]))"},
  {"file":"commandlineparser.go","line":207,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":208,"text":"\t}"},
  {"file":"commandlineparser.go","line":209,"text":"\tp.parseStrings(args)"},
  {"file":"commandlineparser.go","line":210,"text":"}"},
  {"file":"commandlineparser.go","line":212,"text":"func tryReadFile(fileName string, readFile func(string) (string, bool), errors []*ast.Diagnostic) (string, []*ast.Diagnostic) {"},
  {"file":"commandlineparser.go","line":214,"text":"\ttext, e := readFile(fileName)"},
  {"file":"commandlineparser.go","line":216,"text":"\tif !e || text == \"\" {"},
  {"file":"commandlineparser.go","line":219,"text":"\t\ttext = \"\""},
  {"file":"commandlineparser.go","line":220,"text":"\t\terrors = append(errors, ast.NewCompilerDiagnostic(diagnostics.Cannot_read_file_0, fileName))"},
  {"file":"commandlineparser.go","line":221,"text":"\t}"},
  {"file":"commandlineparser.go","line":222,"text":"\treturn text, errors"},
  {"file":"commandlineparser.go","line":223,"text":"}"},
  {"file":"commandlineparser.go","line":225,"text":"func (p *commandLineParser) parseOptionValue("},
  {"file":"commandlineparser.go","line":226,"text":"\targs []string,"},
  {"file":"commandlineparser.go","line":227,"text":"\ti int,"},
  {"file":"commandlineparser.go","line":228,"text":"\topt *CommandLineOption,"},
  {"file":"commandlineparser.go","line":229,"text":"\tdiag *diagnostics.Message,"},
  {"file":"commandlineparser.go","line":230,"text":") int {"},
  {"file":"commandlineparser.go","line":231,"text":"\tif opt.IsTSConfigOnly && i <= len(args) {"},
  {"file":"commandlineparser.go","line":232,"text":"\t\toptValue := \"\""},
  {"file":"commandlineparser.go","line":233,"text":"\t\tif i < len(args) {"},
  {"file":"commandlineparser.go","line":234,"text":"\t\t\toptValue = args[i]"},
  {"file":"commandlineparser.go","line":235,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":236,"text":"\t\tif optValue == \"null\" {"},
  {"file":"commandlineparser.go","line":237,"text":"\t\t\tp.options.Set(opt.Name, nil)"},
  {"file":"commandlineparser.go","line":238,"text":"\t\t\ti++"},
  {"file":"commandlineparser.go","line":239,"text":"\t\t} else if opt.Kind == \"boolean\" {"},
  {"file":"commandlineparser.go","line":240,"text":"\t\t\tif optValue == \"false\" {"},
  {"file":"commandlineparser.go","line":241,"text":"\t\t\t\tp.options.Set(opt.Name, false)"},
  {"file":"commandlineparser.go","line":242,"text":"\t\t\t\ti++"},
  {"file":"commandlineparser.go","line":243,"text":"\t\t\t} else {"},
  {"file":"commandlineparser.go","line":244,"text":"\t\t\t\tif optValue == \"true\" {"},
  {"file":"commandlineparser.go","line":245,"text":"\t\t\t\t\ti++"},
  {"file":"commandlineparser.go","line":246,"text":"\t\t\t\t}"},
  {"file":"commandlineparser.go","line":247,"text":"\t\t\t\tp.errors = append(p.errors, ast.NewCompilerDiagnostic(diagnostics.Option_0_can_only_be_specified_in_tsconfig_json_file_or_set_to_false_or_null_on_command_line, opt.Name))"},
  {"file":"commandlineparser.go","line":248,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":249,"text":"\t\t} else {"},
  {"file":"commandlineparser.go","line":250,"text":"\t\t\tp.errors = append(p.errors, ast.NewCompilerDiagnostic(diagnostics.Option_0_can_only_be_specified_in_tsconfig_json_file_or_set_to_null_on_command_line, opt.Name))"},
  {"file":"commandlineparser.go","line":251,"text":"\t\t\tif len(optValue) != 0 && !strings.HasPrefix(optValue, \"-\") {"},
  {"file":"commandlineparser.go","line":252,"text":"\t\t\t\ti++"},
  {"file":"commandlineparser.go","line":253,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":254,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":255,"text":"\t} else {"},
  {"file":"commandlineparser.go","line":257,"text":"\t\tif i >= len(args) {"},
  {"file":"commandlineparser.go","line":258,"text":"\t\t\tif opt.Kind != \"boolean\" {"},
  {"file":"commandlineparser.go","line":259,"text":"\t\t\t\tp.errors = append(p.errors, ast.NewCompilerDiagnostic(diag, opt.Name, getCompilerOptionValueTypeString(opt)))"},
  {"file":"commandlineparser.go","line":260,"text":"\t\t\t\tif opt.Kind == \"list\" {"},
  {"file":"commandlineparser.go","line":261,"text":"\t\t\t\t\tp.options.Set(opt.Name, []string{})"},
  {"file":"commandlineparser.go","line":262,"text":"\t\t\t\t} else if opt.Kind == \"enum\" {"},
  {"file":"commandlineparser.go","line":263,"text":"\t\t\t\t\tp.errors = append(p.errors, createDiagnosticForInvalidEnumType(opt, nil, nil))"},
  {"file":"commandlineparser.go","line":264,"text":"\t\t\t\t}"},
  {"file":"commandlineparser.go","line":265,"text":"\t\t\t} else {"},
  {"file":"commandlineparser.go","line":266,"text":"\t\t\t\tp.options.Set(opt.Name, true)"},
  {"file":"commandlineparser.go","line":267,"text":"\t\t\t}"},
  {"file":"commandlineparser.go","line":268,"text":"\t\t\treturn i"},
  {"file":"commandlineparser.go","line":269,"text":"\t\t}"},
  {"file":"commandlineparser.go","line":270,"text":"\t\tif args[i] != \"null\" {"},
  {"file":"commandlineparser.go","line":271,"text":"\t\t\tswitch opt.Kind {"},
  {"file":"commandlineparser.go","line":272,"text":"\t\t\tcase \"number\":"},
];

export function tsoptionsStrictParityLineText(file: string, line: number): string | undefined {
  return tsoptionsStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function tsoptionsStrictParityFiles(): readonly string[] {
  return [...new Set(tsoptionsStrictParitySourceLines.map((entry) => entry.file))].sort();
}
