import { readFile } from "node:fs/promises";
import { stableJson, writeGenerated } from "./common.js";

interface RawDiagnosticMessage {
  readonly category: string;
  readonly code: number;
  readonly reportsUnnecessary?: Record<string, unknown>;
  readonly elidedInCompatabilityPyramid?: Record<string, unknown>;
}

type RawDiagnosticCatalog = Record<string, RawDiagnosticMessage>;

const sourcePath = "schema/typescript/diagnosticMessages.json";
const outputPath = "src/diagnostics/generated/messages.ts";

function diagnosticKey(text: string, code: number): string {
  const sanitized = text
    .replace(/'{(\d+)}'/g, "_$1")
    .replace(/\{(\d+)\}/g, "_$1")
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 180);
  const base = sanitized.length === 0 ? "Diagnostic" : sanitized;
  const identifier = /^[A-Za-z_]/.test(base) ? base : `Diagnostic_${base}`;
  return `${identifier}_${code}`;
}

function normalizeCatalog(raw: RawDiagnosticCatalog): readonly DiagnosticEntry[] {
  const entries = Object.entries(raw).map(([text, message]) => ({
    code: message.code,
    category: message.category,
    key: diagnosticKey(text, message.code),
    text,
  }));
  entries.sort((left, right) => left.code - right.code || left.text.localeCompare(right.text));

  const seenCodes = new Map<number, string>();
  for (const entry of entries) {
    const prior = seenCodes.get(entry.code);
    if (prior !== undefined) {
      throw new Error(`Duplicate diagnostic code ${entry.code}: ${prior} and ${entry.text}`);
    }
    seenCodes.set(entry.code, entry.text);
  }

  return entries;
}

interface DiagnosticEntry {
  readonly code: number;
  readonly category: string;
  readonly key: string;
  readonly text: string;
}

function generate(entries: readonly DiagnosticEntry[]): string {
  const codes = entries.map(entry => entry.code);
  return [
    "// Code generated by tools/generate-diagnostics.ts. DO NOT EDIT.",
    `// Source: ${sourcePath}`,
    "",
    "export type DiagnosticCategory = \"Error\" | \"Message\" | \"Suggestion\";",
    "",
    `export type DiagnosticCode = ${codes.join(" | ")};`,
    "",
    "export interface DiagnosticMessageTemplate {",
    "  readonly code: DiagnosticCode;",
    "  readonly category: DiagnosticCategory;",
    "  readonly key: string;",
    "  readonly text: string;",
    "}",
    "",
    `export const diagnosticMessages = ${stableJson(entries).trimEnd()} as const satisfies readonly DiagnosticMessageTemplate[];`,
    "",
    "export const diagnosticMessagesByCode = Object.fromEntries(",
    "  diagnosticMessages.map(message => [message.code, message]),",
    ") as Record<DiagnosticCode, DiagnosticMessageTemplate>;",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const raw = JSON.parse(await readFile(sourcePath, "utf8")) as RawDiagnosticCatalog;
  await writeGenerated(outputPath, generate(normalizeCatalog(raw)));
}

await main();
