import {
  getCombinedNodeFlags,
  isArrowFunction,
  isClassDeclaration,
  isClassExpression,
  isClassStaticBlockDeclaration,
  isFunctionDeclaration,
  isFunctionExpression,
  isGetAccessorDeclaration,
  isIdentifier,
  isMethodDeclaration,
  isMethodSignatureDeclaration,
  isModuleDeclaration,
  isPropertyDeclaration,
  isSetAccessorDeclaration,
  isSourceFile,
  isVariableDeclaration,
  Kind,
  NodeFlags,
  type Node,
} from "../ast/index.js";

export type CallHierarchyDeclaration = Node;

interface CallHierarchyNodeWithName extends Node {
  readonly name?: Node;
  readonly initializer?: Node;
  readonly modifiers?: readonly Node[];
}

function callHierarchyName(node: Node): Node | undefined {
  return (node as CallHierarchyNodeWithName).name;
}

function callHierarchyInitializer(node: Node): Node | undefined {
  return (node as CallHierarchyNodeWithName).initializer;
}

function callHierarchyModifiers(node: Node): readonly Node[] | undefined {
  return (node as CallHierarchyNodeWithName).modifiers;
}

export function isNamedExpression(node: Node | undefined): boolean {
  if (node === undefined) return false;
  if (!isFunctionExpression(node) && !isClassExpression(node)) return false;
  const name = callHierarchyName(node);
  return name !== undefined && isIdentifier(name);
}

export function isVariableLike(node: Node | undefined): boolean {
  if (node === undefined) return false;
  return isPropertyDeclaration(node) || isVariableDeclaration(node);
}

export function isAssignedExpression(node: Node | undefined): boolean {
  if (node === undefined) return false;
  if (!isFunctionExpression(node) && !isArrowFunction(node) && !isClassExpression(node)) return false;
  if (callHierarchyName(node) !== undefined) return false;

  const parent = node.parent;
  if (!isVariableLike(parent)) return false;
  if (callHierarchyInitializer(parent) !== node) return false;

  const name = callHierarchyName(parent);
  if (name === undefined || !isIdentifier(name)) return false;

  return (getCombinedNodeFlags(parent) & NodeFlags.Const) !== 0 || isPropertyDeclaration(parent);
}

export function isPossibleCallHierarchyDeclaration(node: Node | undefined): boolean {
  if (node === undefined) return false;
  return isSourceFile(node)
    || isModuleDeclaration(node)
    || isFunctionDeclaration(node)
    || isFunctionExpression(node)
    || isClassDeclaration(node)
    || isClassExpression(node)
    || isClassStaticBlockDeclaration(node)
    || isMethodDeclaration(node)
    || isMethodSignatureDeclaration(node)
    || isGetAccessorDeclaration(node)
    || isSetAccessorDeclaration(node);
}

export function isValidCallHierarchyDeclaration(node: Node | undefined): boolean {
  if (node === undefined) return false;
  if (isSourceFile(node)) return true;
  if (isModuleDeclaration(node)) {
    const name = callHierarchyName(node);
    return name !== undefined && isIdentifier(name);
  }
  return isFunctionDeclaration(node)
    || isClassDeclaration(node)
    || isClassStaticBlockDeclaration(node)
    || isMethodDeclaration(node)
    || isMethodSignatureDeclaration(node)
    || isGetAccessorDeclaration(node)
    || isSetAccessorDeclaration(node)
    || isNamedExpression(node)
    || isAssignedExpression(node);
}

export function getCallHierarchyDeclarationReferenceNode(node: Node | undefined): Node | undefined {
  if (node === undefined) return undefined;
  if (isSourceFile(node)) return node;

  const name = callHierarchyName(node);
  if (name !== undefined) return name;

  if (isAssignedExpression(node)) return callHierarchyName(node.parent);

  const modifiers = callHierarchyModifiers(node);
  if (modifiers !== undefined) {
    for (const modifier of modifiers) {
      if (modifier.kind === Kind.DefaultKeyword) return modifier;
    }
  }

  return undefined;
}

// Language-service parity map: internal/ls/callhierarchy.go
/**
 * Language-service parity map for TS-Go `ls/callhierarchy.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const lsCallHierarchyUpstreamPath = "ls/callhierarchy.go";

export const lsCallHierarchyDeclarations: readonly UpstreamDeclaration[] = [
  {"line":21,"kind":"type","name":"CallHierarchyDeclaration"},
  {"line":24,"kind":"func","name":"isNamedExpression"},
  {"line":35,"kind":"func","name":"isVariableLike"},
  {"line":43,"kind":"func","name":"isAssignedExpression"},
  {"line":73,"kind":"func","name":"isPossibleCallHierarchyDeclaration"},
  {"line":93,"kind":"func","name":"isValidCallHierarchyDeclaration"},
  {"line":118,"kind":"func","name":"getCallHierarchyDeclarationReferenceNode"},
  {"line":147,"kind":"func","name":"getSymbolOfCallHierarchyDeclaration"},
  {"line":159,"kind":"func","name":"getCallHierarchyItemName"},
  {"line":219,"kind":"func","name":"getTextOfCallHierarchyName"},
  {"line":248,"kind":"func","name":"getCallHierarchyItemContainerName"},
  {"line":296,"kind":"func","name":"moveRangePastModifiers"},
  {"line":305,"kind":"func","name":"findImplementation"},
  {"line":335,"kind":"func","name":"findAllInitialDeclarations"},
  {"line":386,"kind":"func","name":"findImplementationOrAllInitialDeclarations"},
  {"line":408,"kind":"func","name":"resolveCallHierarchyDeclaration"},
  {"line":499,"kind":"func","name":"createCallHierarchyItem","receiver":"l *LanguageService"},
  {"line":526,"kind":"type","name":"callSite"},
  {"line":532,"kind":"func","name":"convertEntryToCallSite"},
  {"line":561,"kind":"func","name":"getCallSiteGroupKey"},
  {"line":565,"kind":"func","name":"convertCallSiteGroupToIncomingCall","receiver":"l *LanguageService"},
  {"line":580,"kind":"type","name":"incomingEntry"},
  {"line":594,"kind":"var","name":"_"},
  {"line":596,"kind":"func","name":"getSourceFile","receiver":"d *incomingEntry"},
  {"line":603,"kind":"func","name":"TextDocumentURI","receiver":"d *incomingEntry"},
  {"line":610,"kind":"func","name":"TextDocumentPosition","receiver":"d *incomingEntry"},
  {"line":619,"kind":"func","name":"getIncomingCalls","receiver":"l *LanguageService"},
  {"line":660,"kind":"func","name":"symbolAndEntriesToIncomingCalls","receiver":"l *LanguageService"},
  {"line":691,"kind":"type","name":"callSiteCollector"},
  {"line":696,"kind":"func","name":"recordCallSite","receiver":"c *callSiteCollector"},
  {"line":749,"kind":"func","name":"collect","receiver":"c *callSiteCollector"},
  {"line":849,"kind":"func","name":"collectCallSites"},
  {"line":922,"kind":"func","name":"convertCallSiteGroupToOutgoingCall","receiver":"l *LanguageService"},
  {"line":938,"kind":"func","name":"getOutgoingCalls","receiver":"l *LanguageService"},
  {"line":976,"kind":"func","name":"ProvidePrepareCallHierarchy","receiver":"l *LanguageService"},
  {"line":1010,"kind":"func","name":"ProvideCallHierarchyIncomingCalls","receiver":"l *LanguageService"},
  {"line":1056,"kind":"func","name":"ProvideCallHierarchyOutgoingCalls","receiver":"l *LanguageService"},
];

export const lsCallHierarchySourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":6,"text":"\t\"strings\""},
  {"line":7,"text":"\t\"sync\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/debug\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":19,"text":")"},
  {"line":21,"text":"type CallHierarchyDeclaration = *ast.Node"},
  {"line":24,"text":"func isNamedExpression(node *ast.Node) bool {"},
  {"line":25,"text":"\tif node == nil {"},
  {"line":26,"text":"\t\treturn false"},
  {"line":27,"text":"\t}"},
  {"line":28,"text":"\tif !ast.IsFunctionExpression(node) && !ast.IsClassExpression(node) {"},
  {"line":29,"text":"\t\treturn false"},
  {"line":30,"text":"\t}"},
  {"line":31,"text":"\tname := node.Name()"},
  {"line":32,"text":"\treturn name != nil && ast.IsIdentifier(name)"},
  {"line":33,"text":"}"},
  {"line":35,"text":"func isVariableLike(node *ast.Node) bool {"},
  {"line":36,"text":"\tif node == nil {"},
  {"line":37,"text":"\t\treturn false"},
  {"line":38,"text":"\t}"},
  {"line":39,"text":"\treturn ast.IsPropertyDeclaration(node) || ast.IsVariableDeclaration(node)"},
  {"line":40,"text":"}"},
  {"line":43,"text":"func isAssignedExpression(node *ast.Node) bool {"},
  {"line":44,"text":"\tif node == nil {"},
  {"line":45,"text":"\t\treturn false"},
  {"line":46,"text":"\t}"},
  {"line":47,"text":"\tif !(ast.IsFunctionExpression(node) || ast.IsArrowFunction(node) || ast.IsClassExpression(node)) {"},
  {"line":48,"text":"\t\treturn false"},
  {"line":49,"text":"\t}"},
  {"line":50,"text":"\tif node.Name() != nil {"},
  {"line":51,"text":"\t\treturn false"},
  {"line":52,"text":"\t}"},
  {"line":53,"text":"\tparent := node.Parent"},
  {"line":54,"text":"\tif !isVariableLike(parent) {"},
  {"line":55,"text":"\t\treturn false"},
  {"line":56,"text":"\t}"},
  {"line":58,"text":"\tif parent.Initializer() != node {"},
  {"line":59,"text":"\t\treturn false"},
  {"line":60,"text":"\t}"},
  {"line":62,"text":"\tname := parent.Name()"},
  {"line":63,"text":"\tif !ast.IsIdentifier(name) {"},
  {"line":64,"text":"\t\treturn false"},
  {"line":65,"text":"\t}"},
  {"line":67,"text":"\treturn (ast.GetCombinedNodeFlags(parent)&ast.NodeFlagsConst) != 0 || ast.IsPropertyDeclaration(parent)"},
  {"line":68,"text":"}"},
  {"line":73,"text":"func isPossibleCallHierarchyDeclaration(node *ast.Node) bool {"},
  {"line":74,"text":"\tif node == nil {"},
  {"line":75,"text":"\t\treturn false"},
  {"line":76,"text":"\t}"},
  {"line":77,"text":"\treturn ast.IsSourceFile(node) ||"},
  {"line":78,"text":"\t\tast.IsModuleDeclaration(node) ||"},
  {"line":79,"text":"\t\tast.IsFunctionDeclaration(node) ||"},
  {"line":80,"text":"\t\tast.IsFunctionExpression(node) ||"},
  {"line":81,"text":"\t\tast.IsClassDeclaration(node) ||"},
  {"line":82,"text":"\t\tast.IsClassExpression(node) ||"},
  {"line":83,"text":"\t\tast.IsClassStaticBlockDeclaration(node) ||"},
  {"line":84,"text":"\t\tast.IsMethodDeclaration(node) ||"},
  {"line":85,"text":"\t\tast.IsMethodSignatureDeclaration(node) ||"},
  {"line":86,"text":"\t\tast.IsGetAccessorDeclaration(node) ||"},
  {"line":87,"text":"\t\tast.IsSetAccessorDeclaration(node)"},
  {"line":88,"text":"}"},
  {"line":93,"text":"func isValidCallHierarchyDeclaration(node *ast.Node) bool {"},
  {"line":94,"text":"\tif node == nil {"},
  {"line":95,"text":"\t\treturn false"},
  {"line":96,"text":"\t}"},
  {"line":98,"text":"\tif ast.IsSourceFile(node) {"},
  {"line":99,"text":"\t\treturn true"},
  {"line":100,"text":"\t}"},
  {"line":102,"text":"\tif ast.IsModuleDeclaration(node) {"},
  {"line":103,"text":"\t\treturn ast.IsIdentifier(node.Name())"},
  {"line":104,"text":"\t}"},
  {"line":106,"text":"\treturn ast.IsFunctionDeclaration(node) ||"},
  {"line":107,"text":"\t\tast.IsClassDeclaration(node) ||"},
  {"line":108,"text":"\t\tast.IsClassStaticBlockDeclaration(node) ||"},
  {"line":109,"text":"\t\tast.IsMethodDeclaration(node) ||"},
  {"line":110,"text":"\t\tast.IsMethodSignatureDeclaration(node) ||"},
  {"line":111,"text":"\t\tast.IsGetAccessorDeclaration(node) ||"},
  {"line":112,"text":"\t\tast.IsSetAccessorDeclaration(node) ||"},
  {"line":113,"text":"\t\tisNamedExpression(node) ||"},
  {"line":114,"text":"\t\tisAssignedExpression(node)"},
  {"line":115,"text":"}"},
  {"line":118,"text":"func getCallHierarchyDeclarationReferenceNode(node *ast.Node) *ast.Node {"},
  {"line":119,"text":"\tif node == nil {"},
  {"line":120,"text":"\t\treturn nil"},
  {"line":121,"text":"\t}"},
  {"line":123,"text":"\tif ast.IsSourceFile(node) {"},
  {"line":124,"text":"\t\treturn node"},
  {"line":125,"text":"\t}"},
  {"line":127,"text":"\tif name := node.Name(); name != nil {"},
  {"line":128,"text":"\t\treturn name"},
  {"line":129,"text":"\t}"},
  {"line":131,"text":"\tif isAssignedExpression(node) {"},
  {"line":132,"text":"\t\treturn node.Parent.Name()"},
  {"line":133,"text":"\t}"},
  {"line":135,"text":"\tif modifiers := node.Modifiers(); modifiers != nil {"},
  {"line":136,"text":"\t\tfor _, mod := range modifiers.Nodes {"},
  {"line":137,"text":"\t\t\tif mod.Kind == ast.KindDefaultKeyword {"},
  {"line":138,"text":"\t\t\t\treturn mod"},
  {"line":139,"text":"\t\t\t}"},
  {"line":140,"text":"\t\t}"},
  {"line":141,"text":"\t}"},
  {"line":143,"text":"\treturn nil"},
  {"line":144,"text":"}"},
  {"line":147,"text":"func getSymbolOfCallHierarchyDeclaration(c *checker.Checker, node *ast.Node) *ast.Symbol {"},
  {"line":148,"text":"\tif ast.IsClassStaticBlockDeclaration(node) {"},
  {"line":149,"text":"\t\treturn nil"},
  {"line":150,"text":"\t}"},
  {"line":151,"text":"\tlocation := getCallHierarchyDeclarationReferenceNode(node)"},
  {"line":152,"text":"\tif location == nil {"},
  {"line":153,"text":"\t\treturn nil"},
  {"line":154,"text":"\t}"},
  {"line":155,"text":"\treturn c.GetSymbolAtLocation(location)"},
  {"line":156,"text":"}"},
  {"line":159,"text":"func getCallHierarchyItemName(program *compiler.Program, node *ast.Node) (text string, pos int, end int) {"},
  {"line":160,"text":"\tif ast.IsSourceFile(node) {"},
  {"line":161,"text":"\t\tsourceFile := node.AsSourceFile()"},
  {"line":162,"text":"\t\treturn sourceFile.FileName(), 0, 0"},
  {"line":163,"text":"\t}"},
  {"line":165,"text":"\tif (ast.IsFunctionDeclaration(node) || ast.IsClassDeclaration(node)) && node.Name() == nil {"},
  {"line":166,"text":"\t\tif modifiers := node.Modifiers(); modifiers != nil {"},
  {"line":167,"text":"\t\t\tfor _, mod := range modifiers.Nodes {"},
  {"line":168,"text":"\t\t\t\tif mod.Kind == ast.KindDefaultKeyword {"},
  {"line":169,"text":"\t\t\t\t\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":170,"text":"\t\t\t\t\tstart := scanner.SkipTrivia(sourceFile.Text(), mod.Pos())"},
  {"line":171,"text":"\t\t\t\t\treturn \"default\", start, mod.End()"},
  {"line":172,"text":"\t\t\t\t}"},
  {"line":173,"text":"\t\t\t}"},
  {"line":174,"text":"\t\t}"},
  {"line":175,"text":"\t}"},
  {"line":177,"text":"\tif ast.IsClassStaticBlockDeclaration(node) {"},
  {"line":178,"text":"\t\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":179,"text":"\t\tpos := scanner.SkipTrivia(sourceFile.Text(), moveRangePastModifiers(node).Pos())"},
  {"line":180,"text":"\t\tend := pos + 6 // \"static\".length"},
  {"line":181,"text":"\t\tc, done := program.GetTypeCheckerForFile(context.Background(), sourceFile)"},
  {"line":182,"text":"\t\tdefer done()"},
  {"line":183,"text":"\t\tsymbol := c.GetSymbolAtLocation(node.Parent)"},
  {"line":184,"text":"\t\tprefix := \"\""},
  {"line":185,"text":"\t\tif symbol != nil {"},
  {"line":186,"text":"\t\t\tprefix = c.SymbolToString(symbol) + \" \""},
  {"line":187,"text":"\t\t}"},
  {"line":188,"text":"\t\treturn prefix + \"static {}\", pos, end"},
  {"line":189,"text":"\t}"},
  {"line":191,"text":"\tvar declName *ast.Node"},
  {"line":192,"text":"\tif isAssignedExpression(node) {"},
  {"line":193,"text":"\t\tdeclName = node.Parent.Name()"},
  {"line":194,"text":"\t} else {"},
  {"line":195,"text":"\t\tdeclName = ast.GetNameOfDeclaration(node)"},
  {"line":196,"text":"\t}"},
  {"line":198,"text":"\tif declName == nil || !ast.NodeIsPresent(declName) {"},
  {"line":199,"text":"\t\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":200,"text":"\t\tswitch {"},
  {"line":201,"text":"\t\tcase ast.IsFunctionDeclaration(node) || ast.IsFunctionExpression(node):"},
  {"line":202,"text":"\t\t\tkwPos := scanner.SkipTrivia(sourceFile.Text(), moveRangePastModifiers(node).Pos())"},
  {"line":203,"text":"\t\t\treturn \"(anonymous)\", kwPos, kwPos + 8 // \"function\".length"},
  {"line":204,"text":"\t\tcase ast.IsClassDeclaration(node) || ast.IsClassExpression(node):"},
  {"line":205,"text":"\t\t\tkwPos := scanner.SkipTrivia(sourceFile.Text(), moveRangePastModifiers(node).Pos())"},
  {"line":206,"text":"\t\t\treturn \"(anonymous)\", kwPos, kwPos + 5 // \"class\".length"},
  {"line":207,"text":"\t\t}"},
  {"line":208,"text":"\t\tdebug.Assert(declName != nil, \"Expected call hierarchy item to have a name\")"},
  {"line":209,"text":"\t}"},
  {"line":211,"text":"\ttext = getTextOfCallHierarchyName(program, node, declName, node)"},
  {"line":213,"text":"\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":214,"text":"\tnamePos := scanner.SkipTrivia(sourceFile.Text(), declName.Pos())"},
  {"line":216,"text":"\treturn text, namePos, declName.End()"},
  {"line":217,"text":"}"},
  {"line":219,"text":"func getTextOfCallHierarchyName(program *compiler.Program, sourceNode *ast.Node, name *ast.Node, printNode *ast.Node) string {"},
  {"line":220,"text":"\tif ast.IsIdentifier(name) || ast.IsStringOrNumericLiteralLike(name) {"},
  {"line":221,"text":"\t\treturn name.Text()"},
  {"line":222,"text":"\t}"},
  {"line":223,"text":"\tif ast.IsComputedPropertyName(name) {"},
  {"line":224,"text":"\t\texpr := name.Expression()"},
  {"line":225,"text":"\t\tif ast.IsStringOrNumericLiteralLike(expr) {"},
  {"line":226,"text":"\t\t\treturn expr.Text()"},
  {"line":227,"text":"\t\t}"},
  {"line":228,"text":"\t}"},
  {"line":230,"text":"\tc, done := program.GetTypeCheckerForFile(context.Background(), ast.GetSourceFileOfNode(sourceNode))"},
  {"line":231,"text":"\tdefer done()"},
  {"line":232,"text":"\tsymbol := c.GetSymbolAtLocation(name)"},
  {"line":233,"text":"\tif symbol != nil {"},
  {"line":234,"text":"\t\ttext := c.SymbolToString(symbol)"},
  {"line":235,"text":"\t\tif text != \"\" {"},
  {"line":236,"text":"\t\t\treturn text"},
  {"line":237,"text":"\t\t}"},
  {"line":238,"text":"\t}"},
  {"line":240,"text":"\tsourceFile := ast.GetSourceFileOfNode(sourceNode)"},
  {"line":241,"text":"\twriter, putWriter := printer.GetSingleLineStringWriter()"},
  {"line":242,"text":"\tdefer putWriter()"},
  {"line":243,"text":"\tp := printer.NewPrinter(printer.PrinterOptions{RemoveComments: true}, printer.PrintHandlers{}, nil)"},
  {"line":244,"text":"\tp.Write(printNode, sourceFile, writer, nil)"},
  {"line":245,"text":"\treturn writer.String()"},
  {"line":246,"text":"}"},
  {"line":248,"text":"func getCallHierarchyItemContainerName(program *compiler.Program, node *ast.Node) string {"},
  {"line":249,"text":"\tif isAssignedExpression(node) {"},
  {"line":250,"text":"\t\tparent := node.Parent"},
  {"line":251,"text":"\t\tif ast.IsPropertyDeclaration(parent) && ast.IsClassLike(parent.Parent) {"},
  {"line":252,"text":"\t\t\tif ast.IsClassExpression(parent.Parent) {"},
  {"line":253,"text":"\t\t\t\tif assignedName := ast.GetAssignedName(parent.Parent); assignedName != nil {"},
  {"line":254,"text":"\t\t\t\t\treturn getTextOfCallHierarchyName(program, node, assignedName, assignedName)"},
  {"line":255,"text":"\t\t\t\t}"},
  {"line":256,"text":"\t\t\t} else {"},
  {"line":257,"text":"\t\t\t\tif name := parent.Parent.Name(); name != nil {"},
  {"line":258,"text":"\t\t\t\t\treturn getTextOfCallHierarchyName(program, node, name, name)"},
  {"line":259,"text":"\t\t\t\t}"},
  {"line":260,"text":"\t\t\t}"},
  {"line":261,"text":"\t\t}"},
  {"line":262,"text":"\t\tif parent.Parent.Parent != nil && parent.Parent.Parent.Parent != nil && ast.IsModuleBlock(parent.Parent.Parent.Parent) {"},
  {"line":263,"text":"\t\t\tmodParent := parent.Parent.Parent.Parent.Parent"},
  {"line":264,"text":"\t\t\tif ast.IsModuleDeclaration(modParent) {"},
  {"line":265,"text":"\t\t\t\tif name := modParent.Name(); name != nil && ast.IsIdentifier(name) {"},
  {"line":266,"text":"\t\t\t\t\treturn name.Text()"},
  {"line":267,"text":"\t\t\t\t}"},
  {"line":268,"text":"\t\t\t}"},
  {"line":269,"text":"\t\t}"},
  {"line":270,"text":"\t\treturn \"\""},
  {"line":271,"text":"\t}"},
  {"line":273,"text":"\tswitch node.Kind {"},
  {"line":274,"text":"\tcase ast.KindGetAccessor, ast.KindSetAccessor, ast.KindMethodDeclaration:"},
  {"line":275,"text":"\t\tif node.Parent.Kind == ast.KindObjectLiteralExpression {"},
  {"line":276,"text":"\t\t\tif assignedName := ast.GetAssignedName(node.Parent); assignedName != nil {"},
  {"line":277,"text":"\t\t\t\treturn getTextOfCallHierarchyName(program, node, assignedName, assignedName)"},
  {"line":278,"text":"\t\t\t}"},
  {"line":279,"text":"\t\t}"},
  {"line":280,"text":"\t\tif name := ast.GetNameOfDeclaration(node.Parent); name != nil {"},
  {"line":281,"text":"\t\t\treturn getTextOfCallHierarchyName(program, node, name, name)"},
  {"line":282,"text":"\t\t}"},
  {"line":283,"text":"\tcase ast.KindFunctionDeclaration, ast.KindClassDeclaration, ast.KindModuleDeclaration:"},
  {"line":284,"text":"\t\tif ast.IsModuleBlock(node.Parent) {"},
  {"line":285,"text":"\t\t\tif ast.IsModuleDeclaration(node.Parent.Parent) {"},
  {"line":286,"text":"\t\t\t\tif name := node.Parent.Parent.Name(); name != nil && ast.IsIdentifier(name) {"},
  {"line":287,"text":"\t\t\t\t\treturn name.Text()"},
  {"line":288,"text":"\t\t\t\t}"},
  {"line":289,"text":"\t\t\t}"},
  {"line":290,"text":"\t\t}"},
  {"line":291,"text":"\t}"},
  {"line":293,"text":"\treturn \"\""},
  {"line":294,"text":"}"},
  {"line":296,"text":"func moveRangePastModifiers(node *ast.Node) core.TextRange {"},
  {"line":297,"text":"\tif modifiers := node.Modifiers(); modifiers != nil && len(modifiers.Nodes) > 0 {"},
  {"line":298,"text":"\t\tlastMod := modifiers.Nodes[len(modifiers.Nodes)-1]"},
  {"line":299,"text":"\t\treturn core.NewTextRange(lastMod.End(), node.End())"},
  {"line":300,"text":"\t}"},
  {"line":301,"text":"\treturn core.NewTextRange(node.Pos(), node.End())"},
  {"line":302,"text":"}"},
  {"line":305,"text":"func findImplementation(c *checker.Checker, node *ast.Node) *ast.Node {"},
  {"line":306,"text":"\tif node == nil {"},
  {"line":307,"text":"\t\treturn nil"},
  {"line":308,"text":"\t}"},
  {"line":310,"text":"\tif !ast.IsFunctionLikeDeclaration(node) {"},
  {"line":311,"text":"\t\treturn node"},
  {"line":312,"text":"\t}"},
  {"line":314,"text":"\tif node.Body() != nil {"},
  {"line":315,"text":"\t\treturn node"},
  {"line":316,"text":"\t}"},
  {"line":318,"text":"\tif ast.IsConstructorDeclaration(node) {"},
  {"line":319,"text":"\t\treturn ast.GetFirstConstructorWithBody(node.Parent)"},
  {"line":320,"text":"\t}"},
  {"line":322,"text":"\tif ast.IsFunctionDeclaration(node) || ast.IsMethodDeclaration(node) {"},
  {"line":323,"text":"\t\tsymbol := getSymbolOfCallHierarchyDeclaration(c, node)"},
  {"line":324,"text":"\t\tif symbol != nil && symbol.ValueDeclaration != nil {"},
  {"line":325,"text":"\t\t\tif ast.IsFunctionLikeDeclaration(symbol.ValueDeclaration) && symbol.ValueDeclaration.Body() != nil {"},
  {"line":326,"text":"\t\t\t\treturn symbol.ValueDeclaration"},
  {"line":327,"text":"\t\t\t}"},
  {"line":328,"text":"\t\t}"},
  {"line":329,"text":"\t\treturn nil"},
  {"line":330,"text":"\t}"},
  {"line":332,"text":"\treturn node"},
  {"line":333,"text":"}"},
  {"line":335,"text":"func findAllInitialDeclarations(c *checker.Checker, node *ast.Node) []*ast.Node {"},
  {"line":336,"text":"\tif ast.IsClassStaticBlockDeclaration(node) {"},
  {"line":337,"text":"\t\treturn nil"},
  {"line":338,"text":"\t}"},
  {"line":340,"text":"\tsymbol := getSymbolOfCallHierarchyDeclaration(c, node)"},
  {"line":341,"text":"\tif symbol == nil || symbol.Declarations == nil {"},
  {"line":342,"text":"\t\treturn nil"},
  {"line":343,"text":"\t}"},
  {"line":345,"text":"\ttype declKey struct {"},
  {"line":346,"text":"\t\tfile string"},
  {"line":347,"text":"\t\tpos  int"},
  {"line":348,"text":"\t}"},
  {"line":350,"text":"\tindices := make([]int, len(symbol.Declarations))"},
  {"line":351,"text":"\tfor i := range indices {"},
  {"line":352,"text":"\t\tindices[i] = i"},
  {"line":353,"text":"\t}"},
  {"line":354,"text":"\tkeys := make([]declKey, len(symbol.Declarations))"},
  {"line":355,"text":"\tfor i, decl := range symbol.Declarations {"},
  {"line":356,"text":"\t\tkeys[i] = declKey{"},
  {"line":357,"text":"\t\t\tfile: ast.GetSourceFileOfNode(decl).FileName(),"},
  {"line":358,"text":"\t\t\tpos:  decl.Pos(),"},
  {"line":359,"text":"\t\t}"},
  {"line":360,"text":"\t}"},
  {"line":362,"text":"\tslices.SortFunc(indices, func(a, b int) int {"},
  {"line":363,"text":"\t\tif keys[a].file != keys[b].file {"},
  {"line":364,"text":"\t\t\treturn strings.Compare(keys[a].file, keys[b].file)"},
  {"line":365,"text":"\t\t}"},
  {"line":366,"text":"\t\treturn keys[a].pos - keys[b].pos"},
  {"line":367,"text":"\t})"},
  {"line":369,"text":"\tvar declarations []*ast.Node"},
  {"line":370,"text":"\tvar lastDecl *ast.Node"},
  {"line":372,"text":"\tfor _, i := range indices {"},
  {"line":373,"text":"\t\tdecl := symbol.Declarations[i]"},
  {"line":374,"text":"\t\tif isValidCallHierarchyDeclaration(decl) {"},
  {"line":375,"text":"\t\t\tif lastDecl == nil || lastDecl.Parent != decl.Parent || lastDecl.End() != decl.Pos() {"},
  {"line":376,"text":"\t\t\t\tdeclarations = append(declarations, decl)"},
  {"line":377,"text":"\t\t\t}"},
  {"line":378,"text":"\t\t\tlastDecl = decl"},
  {"line":379,"text":"\t\t}"},
  {"line":380,"text":"\t}"},
  {"line":382,"text":"\treturn declarations"},
  {"line":383,"text":"}"},
  {"line":386,"text":"func findImplementationOrAllInitialDeclarations(c *checker.Checker, node *ast.Node) any {"},
  {"line":387,"text":"\tif ast.IsClassStaticBlockDeclaration(node) {"},
  {"line":388,"text":"\t\treturn node"},
  {"line":389,"text":"\t}"},
  {"line":391,"text":"\tif ast.IsFunctionLikeDeclaration(node) {"},
  {"line":392,"text":"\t\tif impl := findImplementation(c, node); impl != nil {"},
  {"line":393,"text":"\t\t\treturn impl"},
  {"line":394,"text":"\t\t}"},
  {"line":395,"text":"\t\tif decls := findAllInitialDeclarations(c, node); decls != nil {"},
  {"line":396,"text":"\t\t\treturn decls"},
  {"line":397,"text":"\t\t}"},
  {"line":398,"text":"\t\treturn node"},
  {"line":399,"text":"\t}"},
  {"line":401,"text":"\tif decls := findAllInitialDeclarations(c, node); decls != nil {"},
  {"line":402,"text":"\t\treturn decls"},
  {"line":403,"text":"\t}"},
  {"line":404,"text":"\treturn node"},
  {"line":405,"text":"}"},
  {"line":408,"text":"func resolveCallHierarchyDeclaration(program *compiler.Program, location *ast.Node) (result any) {"},
  {"line":423,"text":"\tc, done := program.GetTypeChecker(context.Background())"},
  {"line":424,"text":"\tdefer done()"},
  {"line":426,"text":"\tfollowingSymbol := false"},
  {"line":428,"text":"\tfor location != nil {"},
  {"line":429,"text":"\t\tif isValidCallHierarchyDeclaration(location) {"},
  {"line":430,"text":"\t\t\treturn findImplementationOrAllInitialDeclarations(c, location)"},
  {"line":431,"text":"\t\t}"},
  {"line":433,"text":"\t\tif isPossibleCallHierarchyDeclaration(location) {"},
  {"line":434,"text":"\t\t\tancestor := ast.FindAncestor(location, isValidCallHierarchyDeclaration)"},
  {"line":435,"text":"\t\t\tif ancestor != nil {"},
  {"line":436,"text":"\t\t\t\treturn findImplementationOrAllInitialDeclarations(c, ancestor)"},
  {"line":437,"text":"\t\t\t}"},
  {"line":438,"text":"\t\t}"},
  {"line":440,"text":"\t\tif ast.IsDeclarationName(location) {"},
  {"line":441,"text":"\t\t\tif isValidCallHierarchyDeclaration(location.Parent) {"},
  {"line":442,"text":"\t\t\t\treturn findImplementationOrAllInitialDeclarations(c, location.Parent)"},
  {"line":443,"text":"\t\t\t}"},
  {"line":444,"text":"\t\t\tif isPossibleCallHierarchyDeclaration(location.Parent) {"},
  {"line":445,"text":"\t\t\t\tancestor := ast.FindAncestor(location.Parent, isValidCallHierarchyDeclaration)"},
  {"line":446,"text":"\t\t\t\tif ancestor != nil {"},
  {"line":447,"text":"\t\t\t\t\treturn findImplementationOrAllInitialDeclarations(c, ancestor)"},
  {"line":448,"text":"\t\t\t\t}"},
  {"line":449,"text":"\t\t\t}"},
  {"line":450,"text":"\t\t\tif isVariableLike(location.Parent) {"},
  {"line":451,"text":"\t\t\t\tinitializer := location.Parent.Initializer()"},
  {"line":452,"text":"\t\t\t\tif initializer != nil && isAssignedExpression(initializer) {"},
  {"line":453,"text":"\t\t\t\t\treturn initializer"},
  {"line":454,"text":"\t\t\t\t}"},
  {"line":455,"text":"\t\t\t}"},
  {"line":456,"text":"\t\t\treturn nil"},
  {"line":457,"text":"\t\t}"},
  {"line":459,"text":"\t\tif ast.IsConstructorDeclaration(location) {"},
  {"line":460,"text":"\t\t\tif isValidCallHierarchyDeclaration(location.Parent) {"},
  {"line":461,"text":"\t\t\t\treturn location.Parent"},
  {"line":462,"text":"\t\t\t}"},
  {"line":463,"text":"\t\t\treturn nil"},
  {"line":464,"text":"\t\t}"},
  {"line":466,"text":"\t\tif location.Kind == ast.KindStaticKeyword && ast.IsClassStaticBlockDeclaration(location.Parent) {"},
  {"line":467,"text":"\t\t\tlocation = location.Parent"},
  {"line":468,"text":"\t\t\tcontinue"},
  {"line":469,"text":"\t\t}"},
  {"line":472,"text":"\t\tif ast.IsVariableDeclaration(location) {"},
  {"line":473,"text":"\t\t\tif initializer := location.Initializer(); initializer != nil && isAssignedExpression(initializer) {"},
  {"line":474,"text":"\t\t\t\treturn initializer"},
  {"line":475,"text":"\t\t\t}"},
  {"line":476,"text":"\t\t}"},
  {"line":478,"text":"\t\tif !followingSymbol {"},
  {"line":479,"text":"\t\t\tsymbol := c.GetSymbolAtLocation(location)"},
  {"line":480,"text":"\t\t\tif symbol != nil {"},
  {"line":481,"text":"\t\t\t\tif (symbol.Flags & ast.SymbolFlagsAlias) != 0 {"},
  {"line":482,"text":"\t\t\t\t\tsymbol = c.GetAliasedSymbol(symbol)"},
  {"line":483,"text":"\t\t\t\t}"},
  {"line":484,"text":"\t\t\t\tif symbol.ValueDeclaration != nil {"},
  {"line":485,"text":"\t\t\t\t\tfollowingSymbol = true"},
  {"line":486,"text":"\t\t\t\t\tlocation = symbol.ValueDeclaration"},
  {"line":487,"text":"\t\t\t\t\tcontinue"},
  {"line":488,"text":"\t\t\t\t}"},
  {"line":489,"text":"\t\t\t}"},
  {"line":490,"text":"\t\t}"},
  {"line":492,"text":"\t\treturn nil"},
  {"line":493,"text":"\t}"},
  {"line":495,"text":"\treturn nil"},
  {"line":496,"text":"}"},
  {"line":499,"text":"func (l *LanguageService) createCallHierarchyItem(program *compiler.Program, node *ast.Node) *lsproto.CallHierarchyItem {"},
  {"line":500,"text":"\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":501,"text":"\tnameText, namePos, nameEnd := getCallHierarchyItemName(program, node)"},
  {"line":502,"text":"\tcontainerName := getCallHierarchyItemContainerName(program, node)"},
  {"line":504,"text":"\tkind := getSymbolKindFromNode(node)"},
  {"line":506,"text":"\tfullStart := scanner.SkipTriviaEx(sourceFile.Text(), node.Pos(), &scanner.SkipTriviaOptions{StopAtComments: true})"},
  {"line":507,"text":"\tscript := l.getScript(sourceFile.FileName())"},
  {"line":508,"text":"\tspan := l.converters.ToLSPRange(script, core.NewTextRange(fullStart, node.End()))"},
  {"line":509,"text":"\tselectionSpan := l.converters.ToLSPRange(script, core.NewTextRange(namePos, nameEnd))"},
  {"line":511,"text":"\titem := &lsproto.CallHierarchyItem{"},
  {"line":512,"text":"\t\tName:           nameText,"},
  {"line":513,"text":"\t\tKind:           kind,"},
  {"line":514,"text":"\t\tUri:            lsconv.FileNameToDocumentURI(sourceFile.FileName()),"},
  {"line":515,"text":"\t\tRange:          span,"},
  {"line":516,"text":"\t\tSelectionRange: selectionSpan,"},
  {"line":517,"text":"\t}"},
  {"line":519,"text":"\tif containerName != \"\" {"},
  {"line":520,"text":"\t\titem.Detail = &containerName"},
  {"line":521,"text":"\t}"},
  {"line":523,"text":"\treturn item"},
  {"line":524,"text":"}"},
  {"line":526,"text":"type callSite struct {"},
  {"line":527,"text":"\tdeclaration *ast.Node"},
  {"line":528,"text":"\ttextRange   core.TextRange"},
  {"line":529,"text":"\tsourceFile  *ast.Node"},
  {"line":530,"text":"}"},
  {"line":532,"text":"func convertEntryToCallSite(entry *ReferenceEntry) *callSite {"},
  {"line":533,"text":"\tif entry.kind != entryKindNode {"},
  {"line":534,"text":"\t\treturn nil"},
  {"line":535,"text":"\t}"},
  {"line":537,"text":"\tnode := entry.node"},
  {"line":538,"text":"\tif !ast.IsCallOrNewExpressionTarget(node, true /*includeElementAccess*/, true /*skipPastOuterExpressions*/) &&"},
  {"line":539,"text":"\t\t!ast.IsTaggedTemplateTag(node, true, true) &&"},
  {"line":540,"text":"\t\t!ast.IsDecoratorTarget(node, true, true) &&"},
  {"line":541,"text":"\t\t!ast.IsJsxOpeningLikeElementTagName(node, true, true) &&"},
  {"line":542,"text":"\t\t!ast.IsRightSideOfPropertyAccess(node) &&"},
  {"line":543,"text":"\t\t!ast.IsArgumentExpressionOfElementAccess(node) {"},
  {"line":544,"text":"\t\treturn nil"},
  {"line":545,"text":"\t}"},
  {"line":547,"text":"\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":548,"text":"\tancestor := ast.FindAncestor(node, isValidCallHierarchyDeclaration)"},
  {"line":549,"text":"\tif ancestor == nil {"},
  {"line":550,"text":"\t\tancestor = sourceFile.AsNode()"},
  {"line":551,"text":"\t}"},
  {"line":553,"text":"\tstart := scanner.SkipTrivia(sourceFile.Text(), node.Pos())"},
  {"line":554,"text":"\treturn &callSite{"},
  {"line":555,"text":"\t\tdeclaration: ancestor,"},
  {"line":556,"text":"\t\ttextRange:   core.NewTextRange(start, node.End()),"},
  {"line":557,"text":"\t\tsourceFile:  sourceFile.AsNode(),"},
  {"line":558,"text":"\t}"},
  {"line":559,"text":"}"},
  {"line":561,"text":"func getCallSiteGroupKey(site *callSite) ast.NodeId {"},
  {"line":562,"text":"\treturn ast.GetNodeId(site.declaration)"},
  {"line":563,"text":"}"},
  {"line":565,"text":"func (l *LanguageService) convertCallSiteGroupToIncomingCall(program *compiler.Program, entries []*callSite) *lsproto.CallHierarchyIncomingCall {"},
  {"line":566,"text":"\tfromRanges := make([]lsproto.Range, len(entries))"},
  {"line":567,"text":"\tfor i, entry := range entries {"},
  {"line":568,"text":"\t\tscript := l.getScript(entry.sourceFile.AsSourceFile().FileName())"},
  {"line":569,"text":"\t\tfromRanges[i] = l.converters.ToLSPRange(script, entry.textRange)"},
  {"line":570,"text":"\t}"},
  {"line":572,"text":"\tslices.SortFunc(fromRanges, lsproto.CompareRanges)"},
  {"line":574,"text":"\treturn &lsproto.CallHierarchyIncomingCall{"},
  {"line":575,"text":"\t\tFrom:       l.createCallHierarchyItem(program, entries[0].declaration),"},
  {"line":576,"text":"\t\tFromRanges: fromRanges,"},
  {"line":577,"text":"\t}"},
  {"line":578,"text":"}"},
  {"line":580,"text":"type incomingEntry struct {"},
  {"line":581,"text":"\tls   *LanguageService"},
  {"line":582,"text":"\tnode *ast.Node"},
  {"line":584,"text":"\tsourceFileOnce sync.Once"},
  {"line":585,"text":"\tsourceFile     *ast.SourceFile"},
  {"line":587,"text":"\tdocumentUriOnce sync.Once"},
  {"line":588,"text":"\tdocumentUri     lsproto.DocumentUri"},
  {"line":590,"text":"\tpositionOnce sync.Once"},
  {"line":591,"text":"\tposition     lsproto.Position"},
  {"line":592,"text":"}"},
  {"line":594,"text":"var _ lsproto.HasTextDocumentPosition = (*incomingEntry)(nil)"},
  {"line":596,"text":"func (d *incomingEntry) getSourceFile() *ast.SourceFile {"},
  {"line":597,"text":"\td.sourceFileOnce.Do(func() {"},
  {"line":598,"text":"\t\td.sourceFile = ast.GetSourceFileOfNode(d.node)"},
  {"line":599,"text":"\t})"},
  {"line":600,"text":"\treturn d.sourceFile"},
  {"line":601,"text":"}"},
  {"line":603,"text":"func (d *incomingEntry) TextDocumentURI() lsproto.DocumentUri {"},
  {"line":604,"text":"\td.documentUriOnce.Do(func() {"},
  {"line":605,"text":"\t\td.documentUri = lsconv.FileNameToDocumentURI(d.getSourceFile().FileName())"},
  {"line":606,"text":"\t})"},
  {"line":607,"text":"\treturn d.documentUri"},
  {"line":608,"text":"}"},
  {"line":610,"text":"func (d *incomingEntry) TextDocumentPosition() lsproto.Position {"},
  {"line":611,"text":"\td.positionOnce.Do(func() {"},
  {"line":612,"text":"\t\tstart := scanner.GetTokenPosOfNode(d.node, d.getSourceFile(), false /*includeJsDoc*/)"},
  {"line":613,"text":"\t\td.position = d.ls.createLspPosition(start, d.getSourceFile())"},
  {"line":614,"text":"\t})"},
  {"line":615,"text":"\treturn d.position"},
  {"line":616,"text":"}"},
  {"line":619,"text":"func (l *LanguageService) getIncomingCalls(ctx context.Context, program *compiler.Program, declaration *ast.Node, orchestrator CrossProjectOrchestrator) (lsproto.CallHierarchyIncomingCallsResponse, error) {"},
  {"line":621,"text":"\tif ast.IsSourceFile(declaration) || ast.IsModuleDeclaration(declaration) || ast.IsClassStaticBlockDeclaration(declaration) {"},
  {"line":622,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":623,"text":"\t}"},
  {"line":625,"text":"\tlocation := getCallHierarchyDeclarationReferenceNode(declaration)"},
  {"line":626,"text":"\tif location == nil {"},
  {"line":627,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":628,"text":"\t}"},
  {"line":630,"text":"\tincomingEntry := &incomingEntry{"},
  {"line":631,"text":"\t\tls:   l,"},
  {"line":632,"text":"\t\tnode: location,"},
  {"line":633,"text":"\t}"},
  {"line":635,"text":"\tresult, err := handleCrossProject("},
  {"line":636,"text":"\t\tl,"},
  {"line":637,"text":"\t\tctx,"},
  {"line":638,"text":"\t\tincomingEntry,"},
  {"line":639,"text":"\t\torchestrator,"},
  {"line":640,"text":"\t\t(*LanguageService).symbolAndEntriesToIncomingCalls,"},
  {"line":641,"text":"\t\tcombineIncomingCalls,"},
  {"line":642,"text":"\t\tfalse,"},
  {"line":643,"text":"\t\tfalse,"},
  {"line":644,"text":"\t\tsymbolEntryTransformOptions{},"},
  {"line":645,"text":"\t)"},
  {"line":646,"text":"\tif result.CallHierarchyIncomingCalls != nil {"},
  {"line":647,"text":"\t\tslices.SortFunc(*result.CallHierarchyIncomingCalls, func(a, b *lsproto.CallHierarchyIncomingCall) int {"},
  {"line":648,"text":"\t\t\tif uriComp := strings.Compare(string(a.From.Uri), string(b.From.Uri)); uriComp != 0 {"},
  {"line":649,"text":"\t\t\t\treturn uriComp"},
  {"line":650,"text":"\t\t\t}"},
  {"line":651,"text":"\t\t\tif len(a.FromRanges) == 0 || len(b.FromRanges) == 0 {"},
  {"line":652,"text":"\t\t\t\treturn 0"},
  {"line":653,"text":"\t\t\t}"},
  {"line":654,"text":"\t\t\treturn lsproto.CompareRanges(a.FromRanges[0], b.FromRanges[0])"},
  {"line":655,"text":"\t\t})"},
  {"line":656,"text":"\t}"},
  {"line":657,"text":"\treturn result, err"},
  {"line":658,"text":"}"},
  {"line":660,"text":"func (l *LanguageService) symbolAndEntriesToIncomingCalls(ctx context.Context, params *incomingEntry, data SymbolAndEntriesData, options symbolEntryTransformOptions) (lsproto.CallHierarchyIncomingCallsResponse, error) {"},
  {"line":661,"text":"\tprogram := l.GetProgram()"},
  {"line":662,"text":"\tvar refEntries []*ReferenceEntry"},
  {"line":663,"text":"\tfor _, symbolAndEntry := range data.SymbolsAndEntries {"},
  {"line":664,"text":"\t\trefEntries = append(refEntries, symbolAndEntry.references...)"},
  {"line":665,"text":"\t}"},
  {"line":667,"text":"\tvar callSites []*callSite"},
  {"line":668,"text":"\tfor _, entry := range refEntries {"},
  {"line":669,"text":"\t\tif site := convertEntryToCallSite(entry); site != nil {"},
  {"line":670,"text":"\t\t\tcallSites = append(callSites, site)"},
  {"line":671,"text":"\t\t}"},
  {"line":672,"text":"\t}"},
  {"line":674,"text":"\tif len(callSites) == 0 {"},
  {"line":675,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":676,"text":"\t}"},
  {"line":678,"text":"\tgrouped := make(map[ast.NodeId][]*callSite)"},
  {"line":679,"text":"\tfor _, site := range callSites {"},
  {"line":680,"text":"\t\tkey := getCallSiteGroupKey(site)"},
  {"line":681,"text":"\t\tgrouped[key] = append(grouped[key], site)"},
  {"line":682,"text":"\t}"},
  {"line":684,"text":"\tvar result []*lsproto.CallHierarchyIncomingCall"},
  {"line":685,"text":"\tfor _, sites := range grouped {"},
  {"line":686,"text":"\t\tresult = append(result, l.convertCallSiteGroupToIncomingCall(program, sites))"},
  {"line":687,"text":"\t}"},
  {"line":688,"text":"\treturn lsproto.CallHierarchyIncomingCallsOrNull{CallHierarchyIncomingCalls: &result}, nil"},
  {"line":689,"text":"}"},
  {"line":691,"text":"type callSiteCollector struct {"},
  {"line":692,"text":"\tprogram   *compiler.Program"},
  {"line":693,"text":"\tcallSites []*callSite"},
  {"line":694,"text":"}"},
  {"line":696,"text":"func (c *callSiteCollector) recordCallSite(node *ast.Node) {"},
  {"line":697,"text":"\tvar target *ast.Node"},
  {"line":699,"text":"\tswitch {"},
  {"line":700,"text":"\tcase ast.IsTaggedTemplateExpression(node):"},
  {"line":701,"text":"\t\ttarget = node.AsTaggedTemplateExpression().Tag"},
  {"line":702,"text":"\tcase ast.IsJsxOpeningElement(node):"},
  {"line":703,"text":"\t\ttarget = node.TagName()"},
  {"line":704,"text":"\tcase ast.IsJsxSelfClosingElement(node):"},
  {"line":705,"text":"\t\ttarget = node.TagName()"},
  {"line":706,"text":"\tcase ast.IsPropertyAccessExpression(node) || ast.IsElementAccessExpression(node):"},
  {"line":707,"text":"\t\ttarget = node"},
  {"line":708,"text":"\tcase ast.IsClassStaticBlockDeclaration(node):"},
  {"line":709,"text":"\t\ttarget = node"},
  {"line":710,"text":"\tcase ast.IsCallExpression(node):"},
  {"line":711,"text":"\t\ttarget = node.Expression()"},
  {"line":712,"text":"\tcase ast.IsNewExpression(node):"},
  {"line":713,"text":"\t\ttarget = node.Expression()"},
  {"line":714,"text":"\tcase ast.IsDecorator(node):"},
  {"line":715,"text":"\t\ttarget = node.Expression()"},
  {"line":716,"text":"\t}"},
  {"line":718,"text":"\tif target == nil {"},
  {"line":719,"text":"\t\treturn"},
  {"line":720,"text":"\t}"},
  {"line":722,"text":"\tdeclaration := resolveCallHierarchyDeclaration(c.program, target)"},
  {"line":723,"text":"\tif declaration == nil {"},
  {"line":724,"text":"\t\treturn"},
  {"line":725,"text":"\t}"},
  {"line":727,"text":"\tsourceFile := ast.GetSourceFileOfNode(target)"},
  {"line":728,"text":"\tstart := scanner.SkipTrivia(sourceFile.Text(), target.Pos())"},
  {"line":729,"text":"\ttextRange := core.NewTextRange(start, target.End())"},
  {"line":731,"text":"\tswitch decl := declaration.(type) {"},
  {"line":732,"text":"\tcase *ast.Node:"},
  {"line":733,"text":"\t\tc.callSites = append(c.callSites, &callSite{"},
  {"line":734,"text":"\t\t\tdeclaration: decl,"},
  {"line":735,"text":"\t\t\ttextRange:   textRange,"},
  {"line":736,"text":"\t\t\tsourceFile:  sourceFile.AsNode(),"},
  {"line":737,"text":"\t\t})"},
  {"line":738,"text":"\tcase []*ast.Node:"},
  {"line":739,"text":"\t\tfor _, d := range decl {"},
  {"line":740,"text":"\t\t\tc.callSites = append(c.callSites, &callSite{"},
  {"line":741,"text":"\t\t\t\tdeclaration: d,"},
  {"line":742,"text":"\t\t\t\ttextRange:   textRange,"},
  {"line":743,"text":"\t\t\t\tsourceFile:  sourceFile.AsNode(),"},
  {"line":744,"text":"\t\t\t})"},
  {"line":745,"text":"\t\t}"},
  {"line":746,"text":"\t}"},
  {"line":747,"text":"}"},
  {"line":749,"text":"func (c *callSiteCollector) collect(node *ast.Node) {"},
  {"line":750,"text":"\tif node == nil {"},
  {"line":751,"text":"\t\treturn"},
  {"line":752,"text":"\t}"},
  {"line":755,"text":"\tif (node.Flags & ast.NodeFlagsAmbient) != 0 {"},
  {"line":756,"text":"\t\treturn"},
  {"line":757,"text":"\t}"},
  {"line":760,"text":"\tif isValidCallHierarchyDeclaration(node) {"},
  {"line":761,"text":"\t\tif ast.IsClassLike(node) {"},
  {"line":762,"text":"\t\t\tfor _, member := range node.Members() {"},
  {"line":763,"text":"\t\t\t\tif member.Name() != nil && ast.IsComputedPropertyName(member.Name()) {"},
  {"line":764,"text":"\t\t\t\t\tc.collect(member.Name().Expression())"},
  {"line":765,"text":"\t\t\t\t}"},
  {"line":766,"text":"\t\t\t}"},
  {"line":767,"text":"\t\t}"},
  {"line":768,"text":"\t\treturn"},
  {"line":769,"text":"\t}"},
  {"line":771,"text":"\tswitch node.Kind {"},
  {"line":772,"text":"\tcase ast.KindIdentifier,"},
  {"line":773,"text":"\t\tast.KindImportEqualsDeclaration,"},
  {"line":774,"text":"\t\tast.KindImportDeclaration,"},
  {"line":775,"text":"\t\tast.KindExportDeclaration,"},
  {"line":776,"text":"\t\tast.KindInterfaceDeclaration,"},
  {"line":777,"text":"\t\tast.KindTypeAliasDeclaration:"},
  {"line":779,"text":"\t\treturn"},
  {"line":780,"text":"\tcase ast.KindClassStaticBlockDeclaration:"},
  {"line":781,"text":"\t\tc.recordCallSite(node)"},
  {"line":782,"text":"\t\treturn"},
  {"line":783,"text":"\tcase ast.KindTypeAssertionExpression, ast.KindAsExpression:"},
  {"line":785,"text":"\t\tc.collect(node.Expression())"},
  {"line":786,"text":"\t\treturn"},
  {"line":787,"text":"\tcase ast.KindVariableDeclaration, ast.KindParameter:"},
  {"line":789,"text":"\t\tc.collect(node.Name())"},
  {"line":790,"text":"\t\tc.collect(node.Initializer())"},
  {"line":791,"text":"\t\treturn"},
  {"line":792,"text":"\tcase ast.KindCallExpression:"},
  {"line":794,"text":"\t\tc.recordCallSite(node)"},
  {"line":795,"text":"\t\tc.collect(node.Expression())"},
  {"line":796,"text":"\t\tfor _, arg := range node.Arguments() {"},
  {"line":797,"text":"\t\t\tc.collect(arg)"},
  {"line":798,"text":"\t\t}"},
  {"line":799,"text":"\t\treturn"},
  {"line":800,"text":"\tcase ast.KindNewExpression:"},
  {"line":802,"text":"\t\tc.recordCallSite(node)"},
  {"line":803,"text":"\t\tc.collect(node.Expression())"},
  {"line":804,"text":"\t\tfor _, arg := range node.Arguments() {"},
  {"line":805,"text":"\t\t\tc.collect(arg)"},
  {"line":806,"text":"\t\t}"},
  {"line":807,"text":"\t\treturn"},
  {"line":808,"text":"\tcase ast.KindTaggedTemplateExpression:"},
  {"line":810,"text":"\t\tc.recordCallSite(node)"},
  {"line":811,"text":"\t\ttaggedTemplate := node.AsTaggedTemplateExpression()"},
  {"line":812,"text":"\t\tc.collect(taggedTemplate.Tag)"},
  {"line":813,"text":"\t\tc.collect(taggedTemplate.Template)"},
  {"line":814,"text":"\t\treturn"},
  {"line":815,"text":"\tcase ast.KindJsxOpeningElement, ast.KindJsxSelfClosingElement:"},
  {"line":817,"text":"\t\tc.recordCallSite(node)"},
  {"line":818,"text":"\t\tc.collect(node.TagName())"},
  {"line":819,"text":"\t\tc.collect(node.Attributes())"},
  {"line":820,"text":"\t\treturn"},
  {"line":821,"text":"\tcase ast.KindDecorator:"},
  {"line":822,"text":"\t\tc.recordCallSite(node)"},
  {"line":823,"text":"\t\tc.collect(node.Expression())"},
  {"line":824,"text":"\t\treturn"},
  {"line":825,"text":"\tcase ast.KindPropertyAccessExpression, ast.KindElementAccessExpression:"},
  {"line":826,"text":"\t\tc.recordCallSite(node)"},
  {"line":827,"text":"\t\tnode.ForEachChild(func(child *ast.Node) bool {"},
  {"line":828,"text":"\t\t\tc.collect(child)"},
  {"line":829,"text":"\t\t\treturn false"},
  {"line":830,"text":"\t\t})"},
  {"line":831,"text":"\t\treturn"},
  {"line":832,"text":"\tcase ast.KindSatisfiesExpression:"},
  {"line":834,"text":"\t\tc.collect(node.Expression())"},
  {"line":835,"text":"\t\treturn"},
  {"line":836,"text":"\t}"},
  {"line":838,"text":"\tif ast.IsPartOfTypeNode(node) {"},
  {"line":840,"text":"\t\treturn"},
  {"line":841,"text":"\t}"},
  {"line":843,"text":"\tnode.ForEachChild(func(child *ast.Node) bool {"},
  {"line":844,"text":"\t\tc.collect(child)"},
  {"line":845,"text":"\t\treturn false"},
  {"line":846,"text":"\t})"},
  {"line":847,"text":"}"},
  {"line":849,"text":"func collectCallSites(program *compiler.Program, c *checker.Checker, node *ast.Node) []*callSite {"},
  {"line":850,"text":"\tcollector := &callSiteCollector{"},
  {"line":851,"text":"\t\tprogram:   program,"},
  {"line":852,"text":"\t\tcallSites: make([]*callSite, 0),"},
  {"line":853,"text":"\t}"},
  {"line":855,"text":"\tswitch node.Kind {"},
  {"line":856,"text":"\tcase ast.KindSourceFile:"},
  {"line":857,"text":"\t\tfor _, stmt := range node.Statements() {"},
  {"line":858,"text":"\t\t\tcollector.collect(stmt)"},
  {"line":859,"text":"\t\t}"},
  {"line":861,"text":"\tcase ast.KindModuleDeclaration:"},
  {"line":862,"text":"\t\tif body := node.Body(); !ast.HasSyntacticModifier(node, ast.ModifierFlagsAmbient) && body != nil && ast.IsModuleBlock(body) {"},
  {"line":863,"text":"\t\t\tfor _, stmt := range body.Statements() {"},
  {"line":864,"text":"\t\t\t\tcollector.collect(stmt)"},
  {"line":865,"text":"\t\t\t}"},
  {"line":866,"text":"\t\t}"},
  {"line":868,"text":"\tcase ast.KindFunctionDeclaration, ast.KindFunctionExpression, ast.KindArrowFunction,"},
  {"line":869,"text":"\t\tast.KindMethodDeclaration, ast.KindGetAccessor, ast.KindSetAccessor:"},
  {"line":870,"text":"\t\timpl := findImplementation(c, node)"},
  {"line":871,"text":"\t\tif impl != nil {"},
  {"line":872,"text":"\t\t\tfor _, param := range impl.Parameters() {"},
  {"line":873,"text":"\t\t\t\tcollector.collect(param)"},
  {"line":874,"text":"\t\t\t}"},
  {"line":875,"text":"\t\t\tcollector.collect(impl.Body())"},
  {"line":876,"text":"\t\t}"},
  {"line":878,"text":"\tcase ast.KindClassDeclaration, ast.KindClassExpression:"},
  {"line":879,"text":"\t\tif modifiers := node.Modifiers(); modifiers != nil {"},
  {"line":880,"text":"\t\t\tfor _, mod := range modifiers.Nodes {"},
  {"line":881,"text":"\t\t\t\tcollector.collect(mod)"},
  {"line":882,"text":"\t\t\t}"},
  {"line":883,"text":"\t\t}"},
  {"line":885,"text":"\t\theritage := ast.GetClassExtendsHeritageElement(node)"},
  {"line":886,"text":"\t\tif heritage != nil {"},
  {"line":887,"text":"\t\t\tcollector.collect(heritage.Expression())"},
  {"line":888,"text":"\t\t}"},
  {"line":890,"text":"\t\tfor _, member := range node.Members() {"},
  {"line":891,"text":"\t\t\tif ast.CanHaveModifiers(member) && member.Modifiers() != nil {"},
  {"line":892,"text":"\t\t\t\tfor _, mod := range member.Modifiers().Nodes {"},
  {"line":893,"text":"\t\t\t\t\tcollector.collect(mod)"},
  {"line":894,"text":"\t\t\t\t}"},
  {"line":895,"text":"\t\t\t}"},
  {"line":897,"text":"\t\t\tif ast.IsPropertyDeclaration(member) {"},
  {"line":898,"text":"\t\t\t\tcollector.collect(member.Initializer())"},
  {"line":899,"text":"\t\t\t} else if ast.IsConstructorDeclaration(member) {"},
  {"line":900,"text":"\t\t\t\tif body := member.Body(); body != nil {"},
  {"line":901,"text":"\t\t\t\t\tfor _, param := range member.Parameters() {"},
  {"line":902,"text":"\t\t\t\t\t\tcollector.collect(param)"},
  {"line":903,"text":"\t\t\t\t\t}"},
  {"line":904,"text":"\t\t\t\t\tcollector.collect(body)"},
  {"line":905,"text":"\t\t\t\t}"},
  {"line":906,"text":"\t\t\t} else if ast.IsClassStaticBlockDeclaration(member) {"},
  {"line":907,"text":"\t\t\t\tcollector.collect(member)"},
  {"line":908,"text":"\t\t\t}"},
  {"line":909,"text":"\t\t}"},
  {"line":911,"text":"\tcase ast.KindClassStaticBlockDeclaration:"},
  {"line":912,"text":"\t\tstaticBlock := node.AsClassStaticBlockDeclaration()"},
  {"line":913,"text":"\t\tcollector.collect(staticBlock.Body)"},
  {"line":915,"text":"\tdefault:"},
  {"line":916,"text":"\t\tdebug.AssertNever(node)"},
  {"line":917,"text":"\t}"},
  {"line":919,"text":"\treturn collector.callSites"},
  {"line":920,"text":"}"},
  {"line":922,"text":"func (l *LanguageService) convertCallSiteGroupToOutgoingCall(program *compiler.Program, entries []*callSite) *lsproto.CallHierarchyOutgoingCall {"},
  {"line":923,"text":"\tfromRanges := make([]lsproto.Range, len(entries))"},
  {"line":924,"text":"\tfor i, entry := range entries {"},
  {"line":925,"text":"\t\tscript := l.getScript(entry.sourceFile.AsSourceFile().FileName())"},
  {"line":926,"text":"\t\tfromRanges[i] = l.converters.ToLSPRange(script, entry.textRange)"},
  {"line":927,"text":"\t}"},
  {"line":929,"text":"\tslices.SortFunc(fromRanges, lsproto.CompareRanges)"},
  {"line":931,"text":"\treturn &lsproto.CallHierarchyOutgoingCall{"},
  {"line":932,"text":"\t\tTo:         l.createCallHierarchyItem(program, entries[0].declaration),"},
  {"line":933,"text":"\t\tFromRanges: fromRanges,"},
  {"line":934,"text":"\t}"},
  {"line":935,"text":"}"},
  {"line":938,"text":"func (l *LanguageService) getOutgoingCalls(program *compiler.Program, declaration *ast.Node) []*lsproto.CallHierarchyOutgoingCall {"},
  {"line":939,"text":"\tif (declaration.Flags&ast.NodeFlagsAmbient) != 0 || ast.IsMethodSignatureDeclaration(declaration) {"},
  {"line":940,"text":"\t\treturn nil"},
  {"line":941,"text":"\t}"},
  {"line":943,"text":"\tc, done := program.GetTypeChecker(context.Background())"},
  {"line":944,"text":"\tdefer done()"},
  {"line":946,"text":"\tcallSites := collectCallSites(program, c, declaration)"},
  {"line":948,"text":"\tif len(callSites) == 0 {"},
  {"line":949,"text":"\t\treturn nil"},
  {"line":950,"text":"\t}"},
  {"line":952,"text":"\tgrouped := make(map[ast.NodeId][]*callSite)"},
  {"line":953,"text":"\tfor _, site := range callSites {"},
  {"line":954,"text":"\t\tkey := getCallSiteGroupKey(site)"},
  {"line":955,"text":"\t\tgrouped[key] = append(grouped[key], site)"},
  {"line":956,"text":"\t}"},
  {"line":958,"text":"\tvar result []*lsproto.CallHierarchyOutgoingCall"},
  {"line":959,"text":"\tfor _, sites := range grouped {"},
  {"line":960,"text":"\t\tresult = append(result, l.convertCallSiteGroupToOutgoingCall(program, sites))"},
  {"line":961,"text":"\t}"},
  {"line":963,"text":"\tslices.SortFunc(result, func(a, b *lsproto.CallHierarchyOutgoingCall) int {"},
  {"line":964,"text":"\t\tif uriComp := strings.Compare(string(a.To.Uri), string(b.To.Uri)); uriComp != 0 {"},
  {"line":965,"text":"\t\t\treturn uriComp"},
  {"line":966,"text":"\t\t}"},
  {"line":967,"text":"\t\tif len(a.FromRanges) == 0 || len(b.FromRanges) == 0 {"},
  {"line":968,"text":"\t\t\treturn 0"},
  {"line":969,"text":"\t\t}"},
  {"line":970,"text":"\t\treturn lsproto.CompareRanges(a.FromRanges[0], b.FromRanges[0])"},
  {"line":971,"text":"\t})"},
  {"line":973,"text":"\treturn result"},
  {"line":974,"text":"}"},
  {"line":976,"text":"func (l *LanguageService) ProvidePrepareCallHierarchy("},
  {"line":977,"text":"\tctx context.Context,"},
  {"line":978,"text":"\tdocumentURI lsproto.DocumentUri,"},
  {"line":979,"text":"\tposition lsproto.Position,"},
  {"line":980,"text":") (lsproto.CallHierarchyPrepareResponse, error) {"},
  {"line":981,"text":"\tprogram, file := l.getProgramAndFile(documentURI)"},
  {"line":982,"text":"\tnode := astnav.GetTouchingPropertyName(file, int(l.converters.LineAndCharacterToPosition(file, position)))"},
  {"line":984,"text":"\tif node.Kind == ast.KindSourceFile {"},
  {"line":985,"text":"\t\treturn lsproto.CallHierarchyItemsOrNull{}, nil"},
  {"line":986,"text":"\t}"},
  {"line":988,"text":"\tdeclaration := resolveCallHierarchyDeclaration(program, node)"},
  {"line":989,"text":"\tif declaration == nil {"},
  {"line":990,"text":"\t\treturn lsproto.CallHierarchyItemsOrNull{}, nil"},
  {"line":991,"text":"\t}"},
  {"line":993,"text":"\tvar items []*lsproto.CallHierarchyItem"},
  {"line":994,"text":"\tswitch decl := declaration.(type) {"},
  {"line":995,"text":"\tcase *ast.Node:"},
  {"line":996,"text":"\t\titems = []*lsproto.CallHierarchyItem{l.createCallHierarchyItem(program, decl)}"},
  {"line":997,"text":"\tcase []*ast.Node:"},
  {"line":998,"text":"\t\titems = make([]*lsproto.CallHierarchyItem, len(decl))"},
  {"line":999,"text":"\t\tfor i, d := range decl {"},
  {"line":1000,"text":"\t\t\titems[i] = l.createCallHierarchyItem(program, d)"},
  {"line":1001,"text":"\t\t}"},
  {"line":1002,"text":"\t}"},
  {"line":1004,"text":"\tif items == nil {"},
  {"line":1005,"text":"\t\treturn lsproto.CallHierarchyItemsOrNull{}, nil"},
  {"line":1006,"text":"\t}"},
  {"line":1007,"text":"\treturn lsproto.CallHierarchyItemsOrNull{CallHierarchyItems: &items}, nil"},
  {"line":1008,"text":"}"},
  {"line":1010,"text":"func (l *LanguageService) ProvideCallHierarchyIncomingCalls("},
  {"line":1011,"text":"\tctx context.Context,"},
  {"line":1012,"text":"\titem *lsproto.CallHierarchyItem,"},
  {"line":1013,"text":"\torchestrator CrossProjectOrchestrator,"},
  {"line":1014,"text":") (lsproto.CallHierarchyIncomingCallsResponse, error) {"},
  {"line":1015,"text":"\tprogram := l.GetProgram()"},
  {"line":1016,"text":"\tfileName := item.Uri.FileName()"},
  {"line":1017,"text":"\tfile := program.GetSourceFile(fileName)"},
  {"line":1018,"text":"\tif file == nil {"},
  {"line":1019,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":1020,"text":"\t}"},
  {"line":1022,"text":"\tpos := int(l.converters.LineAndCharacterToPosition(file, item.SelectionRange.Start))"},
  {"line":1023,"text":"\tvar node *ast.Node"},
  {"line":1024,"text":"\tif pos == 0 {"},
  {"line":1025,"text":"\t\tnode = file.AsNode()"},
  {"line":1026,"text":"\t} else {"},
  {"line":1027,"text":"\t\tnode = astnav.GetTouchingPropertyName(file, pos)"},
  {"line":1028,"text":"\t}"},
  {"line":1030,"text":"\tif node == nil {"},
  {"line":1031,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":1032,"text":"\t}"},
  {"line":1034,"text":"\tdeclaration := resolveCallHierarchyDeclaration(program, node)"},
  {"line":1035,"text":"\tif declaration == nil {"},
  {"line":1036,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":1037,"text":"\t}"},
  {"line":1039,"text":"\tvar decl *ast.Node"},
  {"line":1040,"text":"\tswitch d := declaration.(type) {"},
  {"line":1041,"text":"\tcase *ast.Node:"},
  {"line":1042,"text":"\t\tdecl = d"},
  {"line":1043,"text":"\tcase []*ast.Node:"},
  {"line":1044,"text":"\t\tif len(d) > 0 {"},
  {"line":1045,"text":"\t\t\tdecl = d[0]"},
  {"line":1046,"text":"\t\t}"},
  {"line":1047,"text":"\t}"},
  {"line":1049,"text":"\tif decl == nil {"},
  {"line":1050,"text":"\t\treturn lsproto.CallHierarchyIncomingCallsOrNull{}, nil"},
  {"line":1051,"text":"\t}"},
  {"line":1053,"text":"\treturn l.getIncomingCalls(ctx, program, decl, orchestrator)"},
  {"line":1054,"text":"}"},
  {"line":1056,"text":"func (l *LanguageService) ProvideCallHierarchyOutgoingCalls("},
  {"line":1057,"text":"\tctx context.Context,"},
  {"line":1058,"text":"\titem *lsproto.CallHierarchyItem,"},
  {"line":1059,"text":") (lsproto.CallHierarchyOutgoingCallsResponse, error) {"},
  {"line":1060,"text":"\tprogram := l.GetProgram()"},
  {"line":1061,"text":"\tfileName := item.Uri.FileName()"},
  {"line":1062,"text":"\tfile := program.GetSourceFile(fileName)"},
  {"line":1063,"text":"\tif file == nil {"},
  {"line":1064,"text":"\t\treturn lsproto.CallHierarchyOutgoingCallsOrNull{}, nil"},
  {"line":1065,"text":"\t}"},
  {"line":1067,"text":"\tpos := int(l.converters.LineAndCharacterToPosition(file, item.SelectionRange.Start))"},
  {"line":1068,"text":"\tvar node *ast.Node"},
  {"line":1069,"text":"\tif pos == 0 {"},
  {"line":1070,"text":"\t\tnode = file.AsNode()"},
  {"line":1071,"text":"\t} else {"},
  {"line":1072,"text":"\t\tnode = astnav.GetTouchingPropertyName(file, pos)"},
  {"line":1073,"text":"\t}"},
  {"line":1075,"text":"\tif node == nil {"},
  {"line":1076,"text":"\t\treturn lsproto.CallHierarchyOutgoingCallsOrNull{}, nil"},
  {"line":1077,"text":"\t}"},
  {"line":1079,"text":"\tdeclaration := resolveCallHierarchyDeclaration(program, node)"},
  {"line":1080,"text":"\tif declaration == nil {"},
  {"line":1081,"text":"\t\treturn lsproto.CallHierarchyOutgoingCallsOrNull{}, nil"},
  {"line":1082,"text":"\t}"},
  {"line":1084,"text":"\tvar decl *ast.Node"},
  {"line":1085,"text":"\tswitch d := declaration.(type) {"},
  {"line":1086,"text":"\tcase *ast.Node:"},
  {"line":1087,"text":"\t\tdecl = d"},
  {"line":1088,"text":"\tcase []*ast.Node:"},
  {"line":1089,"text":"\t\tif len(d) > 0 {"},
  {"line":1090,"text":"\t\t\tdecl = d[0]"},
  {"line":1091,"text":"\t\t}"},
  {"line":1092,"text":"\t}"},
  {"line":1094,"text":"\tif decl == nil {"},
  {"line":1095,"text":"\t\treturn lsproto.CallHierarchyOutgoingCallsOrNull{}, nil"},
  {"line":1096,"text":"\t}"},
  {"line":1098,"text":"\tcalls := l.getOutgoingCalls(program, decl)"},
  {"line":1099,"text":"\tif calls == nil {"},
  {"line":1100,"text":"\t\treturn lsproto.CallHierarchyOutgoingCallsOrNull{}, nil"},
  {"line":1101,"text":"\t}"},
  {"line":1102,"text":"\treturn lsproto.CallHierarchyOutgoingCallsOrNull{CallHierarchyOutgoingCalls: &calls}, nil"},
  {"line":1103,"text":"}"},
];

export function findLsCallHierarchyDeclaration(name: string): UpstreamDeclaration | undefined {
  return lsCallHierarchyDeclarations.find((declaration) => declaration.name === name);
}

export function requireLsCallHierarchyDeclaration(name: string): UpstreamDeclaration {
  const declaration = findLsCallHierarchyDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function lsCallHierarchyLineText(line: number): string | undefined {
  return lsCallHierarchySourceLines.find((entry) => entry.line === line)?.text;
}
