/**
 * Language-service parity map for TS-Go `ls/codeactions_fixmissingtypeannotation.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationUpstreamPath = "ls/codeactions_fixmissingtypeannotation.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationDeclarations: readonly UpstreamDeclaration[] = [
  {"line":22,"kind":"var","name":"isolatedDeclarationsFixErrorCodes"},
  {"line":46,"kind":"const","name":"fixMissingTypeAnnotationOnExportsFixID"},
  {"line":49,"kind":"var","name":"IsolatedDeclarationsFixProvider"},
  {"line":57,"kind":"var","name":"canHaveTypeAnnotationKinds"},
  {"line":73,"kind":"var","name":"declarationEmitNodeBuilderFlags"},
  {"line":81,"kind":"type","name":"typePrintMode"},
  {"line":89,"kind":"func","name":"getIsolatedDeclarationsCodeActions"},
  {"line":135,"kind":"func","name":"getAllIsolatedDeclarationsCodeActions"},
  {"line":175,"kind":"func","name":"tryCodeAction"},
  {"line":223,"kind":"type","name":"isolatedDeclarationsFixer"},
  {"line":236,"kind":"func","name":"addTypeAnnotation","receiver":"f *isolatedDeclarationsFixer"},
  {"line":254,"kind":"func","name":"createNamespaceForExpandoProperties","receiver":"f *isolatedDeclarationsFixer"},
  {"line":315,"kind":"func","name":"needsParenthesizedExpressionForAssertion"},
  {"line":320,"kind":"func","name":"createAsExpression"},
  {"line":327,"kind":"func","name":"addInlineAssertion","receiver":"f *isolatedDeclarationsFixer"},
  {"line":411,"kind":"func","name":"extractAsVariable","receiver":"f *isolatedDeclarationsFixer"},
  {"line":486,"kind":"func","name":"isExpandoPropertyDeclarationForFix"},
  {"line":490,"kind":"func","name":"findExpandoFunction"},
  {"line":556,"kind":"func","name":"fixIsolatedDeclarationError","receiver":"f *isolatedDeclarationsFixer"},
  {"line":580,"kind":"func","name":"addTypeToSignatureDeclaration","receiver":"f *isolatedDeclarationsFixer"},
  {"line":592,"kind":"func","name":"transformExportAssignment","receiver":"f *isolatedDeclarationsFixer"},
  {"line":621,"kind":"func","name":"transformExtendsClauseWithExpression","receiver":"f *isolatedDeclarationsFixer"},
  {"line":670,"kind":"func","name":"transformDestructuringPatterns","receiver":"f *isolatedDeclarationsFixer"},
  {"line":736,"kind":"func","name":"extractBindingElements","receiver":"f *isolatedDeclarationsFixer"},
  {"line":806,"kind":"func","name":"emitBindingElementVariable","receiver":"f *isolatedDeclarationsFixer"},
  {"line":853,"kind":"func","name":"getExportModifier","receiver":"f *isolatedDeclarationsFixer"},
  {"line":861,"kind":"func","name":"inferType","receiver":"f *isolatedDeclarationsFixer"},
  {"line":931,"kind":"func","name":"getExtraFlags","receiver":"f *isolatedDeclarationsFixer"},
  {"line":941,"kind":"func","name":"createTypeOfFromEntityNameExpression","receiver":"f *isolatedDeclarationsFixer"},
  {"line":948,"kind":"func","name":"typeFromArraySpreadElements","receiver":"f *isolatedDeclarationsFixer"},
  {"line":983,"kind":"func","name":"typeFromObjectSpreadAssignment","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1014,"kind":"func","name":"typeFromSpreads","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1059,"kind":"func","name":"makeSpreadVariable","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1095,"kind":"func","name":"finalizesVariablePart","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1113,"kind":"func","name":"isConstAssertion"},
  {"line":1124,"kind":"func","name":"relativeType","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1177,"kind":"func","name":"typeToMinimizedReferenceType","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1214,"kind":"func","name":"endOfRequiredTypeParameters"},
  {"line":1251,"kind":"func","name":"typeParamHasDefault"},
  {"line":1264,"kind":"func","name":"addTypeToVariableLike","receiver":"f *isolatedDeclarationsFixer"},
  {"line":1287,"kind":"func","name":"typeToStringForDiag"},
  {"line":1310,"kind":"func","name":"findAncestorWithMissingType"},
  {"line":1323,"kind":"func","name":"findBestFittingNode"},
  {"line":1345,"kind":"func","name":"isNamedDeclarationKind"},
  {"line":1365,"kind":"func","name":"isValueSignatureDeclaration"},
  {"line":1373,"kind":"func","name":"getIdentifierNameForNode"},
  {"line":1385,"kind":"func","name":"addSymbolToExistingImport","receiver":"f *isolatedDeclarationsFixer"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":6,"text":"\t\"strconv\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/locale\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/autoimport\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/change\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/nodebuilder\""},
  {"line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":20,"text":")"},
  {"line":22,"text":"var isolatedDeclarationsFixErrorCodes = []int32{"},
  {"line":23,"text":"\tdiagnostics.Function_must_have_an_explicit_return_type_annotation_with_isolatedDeclarations.Code(),"},
  {"line":24,"text":"\tdiagnostics.Method_must_have_an_explicit_return_type_annotation_with_isolatedDeclarations.Code(),"},
  {"line":25,"text":"\tdiagnostics.At_least_one_accessor_must_have_an_explicit_type_annotation_with_isolatedDeclarations.Code(),"},
  {"line":26,"text":"\tdiagnostics.Variable_must_have_an_explicit_type_annotation_with_isolatedDeclarations.Code(),"},
  {"line":27,"text":"\tdiagnostics.Parameter_must_have_an_explicit_type_annotation_with_isolatedDeclarations.Code(),"},
  {"line":28,"text":"\tdiagnostics.Property_must_have_an_explicit_type_annotation_with_isolatedDeclarations.Code(),"},
  {"line":29,"text":"\tdiagnostics.Expression_type_can_t_be_inferred_with_isolatedDeclarations.Code(),"},
  {"line":30,"text":"\tdiagnostics.Binding_elements_can_t_be_exported_directly_with_isolatedDeclarations.Code(),"},
  {"line":31,"text":"\tdiagnostics.Computed_property_names_on_class_or_object_literals_cannot_be_inferred_with_isolatedDeclarations.Code(),"},
  {"line":32,"text":"\tdiagnostics.Computed_properties_must_be_number_or_string_literals_variables_or_dotted_expressions_with_isolatedDeclarations.Code(),"},
  {"line":33,"text":"\tdiagnostics.Enum_member_initializers_must_be_computable_without_references_to_external_symbols_with_isolatedDeclarations.Code(),"},
  {"line":34,"text":"\tdiagnostics.Extends_clause_can_t_contain_an_expression_with_isolatedDeclarations.Code(),"},
  {"line":35,"text":"\tdiagnostics.Objects_that_contain_shorthand_properties_can_t_be_inferred_with_isolatedDeclarations.Code(),"},
  {"line":36,"text":"\tdiagnostics.Objects_that_contain_spread_assignments_can_t_be_inferred_with_isolatedDeclarations.Code(),"},
  {"line":37,"text":"\tdiagnostics.Arrays_with_spread_elements_can_t_inferred_with_isolatedDeclarations.Code(),"},
  {"line":38,"text":"\tdiagnostics.Default_exports_can_t_be_inferred_with_isolatedDeclarations.Code(),"},
  {"line":39,"text":"\tdiagnostics.Only_const_arrays_can_be_inferred_with_isolatedDeclarations.Code(),"},
  {"line":40,"text":"\tdiagnostics.Assigning_properties_to_functions_without_declaring_them_is_not_supported_with_isolatedDeclarations_Add_an_explicit_declaration_for_the_properties_assigned_to_this_function.Code(),"},
  {"line":41,"text":"\tdiagnostics.Declaration_emit_for_this_parameter_requires_implicitly_adding_undefined_to_its_type_This_is_not_supported_with_isolatedDeclarations.Code(),"},
  {"line":42,"text":"\tdiagnostics.Type_containing_private_name_0_can_t_be_used_with_isolatedDeclarations.Code(),"},
  {"line":43,"text":"\tdiagnostics.Add_satisfies_and_a_type_assertion_to_this_expression_satisfies_T_as_T_to_make_the_type_explicit.Code(),"},
  {"line":44,"text":"}"},
  {"line":46,"text":"const fixMissingTypeAnnotationOnExportsFixID = \"fixMissingTypeAnnotationOnExports\""},
  {"line":49,"text":"var IsolatedDeclarationsFixProvider = &CodeFixProvider{"},
  {"line":50,"text":"\tErrorCodes:        isolatedDeclarationsFixErrorCodes,"},
  {"line":51,"text":"\tGetCodeActions:    getIsolatedDeclarationsCodeActions,"},
  {"line":52,"text":"\tFixIds:            []string{fixMissingTypeAnnotationOnExportsFixID},"},
  {"line":53,"text":"\tGetAllCodeActions: getAllIsolatedDeclarationsCodeActions,"},
  {"line":54,"text":"}"},
  {"line":57,"text":"var canHaveTypeAnnotationKinds = map[ast.Kind]bool{"},
  {"line":58,"text":"\tast.KindGetAccessor:          true,"},
  {"line":59,"text":"\tast.KindMethodDeclaration:    true,"},
  {"line":60,"text":"\tast.KindPropertyDeclaration:  true,"},
  {"line":61,"text":"\tast.KindFunctionDeclaration:  true,"},
  {"line":62,"text":"\tast.KindFunctionExpression:   true,"},
  {"line":63,"text":"\tast.KindArrowFunction:        true,"},
  {"line":64,"text":"\tast.KindVariableDeclaration:  true,"},
  {"line":65,"text":"\tast.KindParameter:            true,"},
  {"line":66,"text":"\tast.KindExportAssignment:     true,"},
  {"line":67,"text":"\tast.KindClassDeclaration:     true,"},
  {"line":68,"text":"\tast.KindObjectBindingPattern: true,"},
  {"line":69,"text":"\tast.KindArrayBindingPattern:  true,"},
  {"line":70,"text":"}"},
  {"line":73,"text":"var declarationEmitNodeBuilderFlags = nodebuilder.FlagsMultilineObjectLiterals |"},
  {"line":74,"text":"\tnodebuilder.FlagsWriteClassExpressionAsTypeLiteral |"},
  {"line":75,"text":"\tnodebuilder.FlagsUseTypeOfFunction |"},
  {"line":76,"text":"\tnodebuilder.FlagsUseStructuralFallback |"},
  {"line":77,"text":"\tnodebuilder.FlagsAllowEmptyTuple |"},
  {"line":78,"text":"\tnodebuilder.FlagsGenerateNamesForShadowedTypeParams |"},
  {"line":79,"text":"\tnodebuilder.FlagsNoTruncation"},
  {"line":81,"text":"type typePrintMode int"},
  {"line":83,"text":"const ("},
  {"line":84,"text":"\ttypePrintModeFull     typePrintMode = iota"},
  {"line":85,"text":"\ttypePrintModeRelative               // typeof X"},
  {"line":86,"text":"\ttypePrintModeWidened                // widened literal type"},
  {"line":87,"text":")"},
  {"line":89,"text":"func getIsolatedDeclarationsCodeActions(ctx context.Context, fixContext *CodeFixContext) ([]*CodeAction, error) {"},
  {"line":90,"text":"\tch, done := fixContext.Program.GetTypeCheckerForFile(ctx, fixContext.SourceFile)"},
  {"line":91,"text":"\tdefer done()"},
  {"line":93,"text":"\tvar fixes []*CodeAction"},
  {"line":94,"text":"\tvar seen []*CodeAction // sorted for binary search dedup"},
  {"line":96,"text":"\taddFix := func(action *CodeAction) {"},
  {"line":97,"text":"\t\tif action == nil {"},
  {"line":98,"text":"\t\t\treturn"},
  {"line":99,"text":"\t\t}"},
  {"line":100,"text":"\t\ti, found := slices.BinarySearchFunc(seen, action, (*CodeAction).Compare)"},
  {"line":101,"text":"\t\tif found {"},
  {"line":102,"text":"\t\t\treturn"},
  {"line":103,"text":"\t\t}"},
  {"line":104,"text":"\t\tseen = slices.Insert(seen, i, action)"},
  {"line":105,"text":"\t\tfixes = append(fixes, action)"},
  {"line":106,"text":"\t}"},
  {"line":110,"text":"\tmodes := []typePrintMode{typePrintModeFull, typePrintModeRelative, typePrintModeWidened}"},
  {"line":112,"text":"\tfor _, mode := range modes {"},
  {"line":113,"text":"\t\taddFix(tryCodeAction(ctx, fixContext, ch, func(f *isolatedDeclarationsFixer) string {"},
  {"line":114,"text":"\t\t\tf.typePrintMode = mode"},
  {"line":115,"text":"\t\t\treturn f.addTypeAnnotation(fixContext.Span)"},
  {"line":116,"text":"\t\t}))"},
  {"line":117,"text":"\t}"},
  {"line":119,"text":"\tfor _, mode := range modes {"},
  {"line":120,"text":"\t\taddFix(tryCodeAction(ctx, fixContext, ch, func(f *isolatedDeclarationsFixer) string {"},
  {"line":121,"text":"\t\t\tf.typePrintMode = mode"},
  {"line":122,"text":"\t\t\treturn f.addInlineAssertion(fixContext.Span)"},
  {"line":123,"text":"\t\t}))"},
  {"line":124,"text":"\t}"},
  {"line":127,"text":"\taddFix(tryCodeAction(ctx, fixContext, ch, func(f *isolatedDeclarationsFixer) string {"},
  {"line":128,"text":"\t\tf.typePrintMode = typePrintModeFull"},
  {"line":129,"text":"\t\treturn f.extractAsVariable(fixContext.Span)"},
  {"line":130,"text":"\t}))"},
  {"line":132,"text":"\treturn fixes, nil"},
  {"line":133,"text":"}"},
  {"line":135,"text":"func getAllIsolatedDeclarationsCodeActions(ctx context.Context, fixContext *CodeFixContext) (*CombinedCodeActions, error) {"},
  {"line":136,"text":"\tch, done := fixContext.Program.GetTypeCheckerForFile(ctx, fixContext.SourceFile)"},
  {"line":137,"text":"\tdefer done()"},
  {"line":139,"text":"\tchangeTracker := change.NewTracker(ctx, fixContext.Program.Options(), fixContext.LS.FormatOptions(), fixContext.LS.converters)"},
  {"line":141,"text":"\tfixer := &isolatedDeclarationsFixer{"},
  {"line":142,"text":"\t\tsourceFile:    fixContext.SourceFile,"},
  {"line":143,"text":"\t\tprogram:       fixContext.Program,"},
  {"line":144,"text":"\t\tchecker:       ch,"},
  {"line":145,"text":"\t\tchangeTracker: changeTracker,"},
  {"line":146,"text":"\t\tlocale:        locale.FromContext(ctx),"},
  {"line":147,"text":"\t\tfixedNodes:    make(map[*ast.Node]bool),"},
  {"line":148,"text":"\t\ttypePrintMode: typePrintModeFull,"},
  {"line":149,"text":"\t}"},
  {"line":151,"text":"\tallDiags := getAllDiagnostics(ctx, fixContext.Program, fixContext.SourceFile)"},
  {"line":152,"text":"\tfor _, diag := range allDiags {"},
  {"line":153,"text":"\t\tif containsErrorCode(isolatedDeclarationsFixErrorCodes, diag.Code()) {"},
  {"line":154,"text":"\t\t\tspan := core.NewTextRange(diag.Loc().Pos(), diag.Loc().End())"},
  {"line":155,"text":"\t\t\tfixer.addTypeAnnotation(span)"},
  {"line":156,"text":"\t\t}"},
  {"line":157,"text":"\t}"},
  {"line":159,"text":"\tfor _, sym := range fixer.symbolsToImport {"},
  {"line":160,"text":"\t\tfixer.addSymbolToExistingImport(sym)"},
  {"line":161,"text":"\t}"},
  {"line":163,"text":"\tchanges := changeTracker.GetChanges()"},
  {"line":164,"text":"\tfileChanges := changes[fixContext.SourceFile.FileName()]"},
  {"line":165,"text":"\tif len(fileChanges) == 0 {"},
  {"line":166,"text":"\t\treturn nil, nil"},
  {"line":167,"text":"\t}"},
  {"line":169,"text":"\treturn &CombinedCodeActions{"},
  {"line":170,"text":"\t\tDescription: diagnostics.Add_all_missing_type_annotations.Localize(locale.FromContext(ctx)),"},
  {"line":171,"text":"\t\tChanges:     fileChanges,"},
  {"line":172,"text":"\t}, nil"},
  {"line":173,"text":"}"},
  {"line":175,"text":"func tryCodeAction(ctx context.Context, fixContext *CodeFixContext, ch *checker.Checker, fn func(*isolatedDeclarationsFixer) string) *CodeAction {"},
  {"line":176,"text":"\tchangeTracker := change.NewTracker(ctx, fixContext.Program.Options(), fixContext.LS.FormatOptions(), fixContext.LS.converters)"},
  {"line":178,"text":"\tvar importAdder autoimport.ImportAdder"},
  {"line":182,"text":"\tfixer := &isolatedDeclarationsFixer{"},
  {"line":183,"text":"\t\tsourceFile:    fixContext.SourceFile,"},
  {"line":184,"text":"\t\tprogram:       fixContext.Program,"},
  {"line":185,"text":"\t\tchecker:       ch,"},
  {"line":186,"text":"\t\tchangeTracker: changeTracker,"},
  {"line":187,"text":"\t\timportAdder:   importAdder,"},
  {"line":188,"text":"\t\tlocale:        locale.FromContext(ctx),"},
  {"line":189,"text":"\t\tfixedNodes:    make(map[*ast.Node]bool),"},
  {"line":190,"text":"\t}"},
  {"line":192,"text":"\tdescription := fn(fixer)"},
  {"line":193,"text":"\tif description == \"\" {"},
  {"line":194,"text":"\t\treturn nil"},
  {"line":195,"text":"\t}"},
  {"line":198,"text":"\tfor _, sym := range fixer.symbolsToImport {"},
  {"line":199,"text":"\t\tfixer.addSymbolToExistingImport(sym)"},
  {"line":200,"text":"\t}"},
  {"line":202,"text":"\tchanges := changeTracker.GetChanges()"},
  {"line":203,"text":"\tfileChanges := changes[fixContext.SourceFile.FileName()]"},
  {"line":206,"text":"\tif importAdder != nil && importAdder.HasFixes() {"},
  {"line":207,"text":"\t\tfileChanges = append(fileChanges, importAdder.Edits()...)"},
  {"line":208,"text":"\t}"},
  {"line":210,"text":"\tif len(fileChanges) == 0 {"},
  {"line":211,"text":"\t\treturn nil"},
  {"line":212,"text":"\t}"},
  {"line":214,"text":"\treturn &CodeAction{"},
  {"line":215,"text":"\t\tDescription:       description,"},
  {"line":216,"text":"\t\tChanges:           fileChanges,"},
  {"line":217,"text":"\t\tFixID:             fixMissingTypeAnnotationOnExportsFixID,"},
  {"line":218,"text":"\t\tFixAllDescription: diagnostics.Add_all_missing_type_annotations.Localize(locale.FromContext(ctx)),"},
  {"line":219,"text":"\t}"},
  {"line":220,"text":"}"},
  {"line":223,"text":"type isolatedDeclarationsFixer struct {"},
  {"line":224,"text":"\tsourceFile      *ast.SourceFile"},
  {"line":225,"text":"\tprogram         *compiler.Program"},
  {"line":226,"text":"\tchecker         *checker.Checker"},
  {"line":227,"text":"\tchangeTracker   *change.Tracker"},
  {"line":228,"text":"\timportAdder     autoimport.ImportAdder"},
  {"line":229,"text":"\tlocale          locale.Locale"},
  {"line":230,"text":"\tfixedNodes      map[*ast.Node]bool"},
  {"line":231,"text":"\ttypePrintMode   typePrintMode"},
  {"line":232,"text":"\tsymbolsToImport []*ast.Symbol"},
  {"line":233,"text":"\tmutatedTarget   bool // set by inferType/relativeType when the target was mutated (e.g., spread decomposition)"},
  {"line":234,"text":"}"},
  {"line":236,"text":"func (f *isolatedDeclarationsFixer) addTypeAnnotation(span core.TextRange) string {"},
  {"line":237,"text":"\tnodeWithDiag := astnav.GetTokenAtPosition(f.sourceFile, span.Pos())"},
  {"line":239,"text":"\texpandoFunction := findExpandoFunction(f.checker, nodeWithDiag)"},
  {"line":240,"text":"\tif expandoFunction != nil {"},
  {"line":241,"text":"\t\tif ast.IsFunctionDeclaration(expandoFunction) {"},
  {"line":242,"text":"\t\t\treturn f.createNamespaceForExpandoProperties(expandoFunction)"},
  {"line":243,"text":"\t\t}"},
  {"line":244,"text":"\t\treturn f.fixIsolatedDeclarationError(expandoFunction)"},
  {"line":245,"text":"\t}"},
  {"line":247,"text":"\tnodeMissingType := findAncestorWithMissingType(nodeWithDiag)"},
  {"line":248,"text":"\tif nodeMissingType != nil {"},
  {"line":249,"text":"\t\treturn f.fixIsolatedDeclarationError(nodeMissingType)"},
  {"line":250,"text":"\t}"},
  {"line":251,"text":"\treturn \"\""},
  {"line":252,"text":"}"},
  {"line":254,"text":"func (f *isolatedDeclarationsFixer) createNamespaceForExpandoProperties(expandoFunc *ast.Node) string {"},
  {"line":255,"text":"\tfuncDecl := expandoFunc.AsFunctionDeclaration()"},
  {"line":256,"text":"\tif funcDecl.Name() == nil {"},
  {"line":257,"text":"\t\treturn \"\""},
  {"line":258,"text":"\t}"},
  {"line":260,"text":"\tt := f.checker.GetTypeAtLocation(expandoFunc)"},
  {"line":261,"text":"\telements := f.checker.GetPropertiesOfType(t)"},
  {"line":262,"text":"\tif len(elements) == 0 {"},
  {"line":263,"text":"\t\treturn \"\""},
  {"line":264,"text":"\t}"},
  {"line":266,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":268,"text":"\tvar newProperties []*ast.Node"},
  {"line":269,"text":"\tfor _, symbol := range elements {"},
  {"line":270,"text":"\t\tif !scanner.IsIdentifierText(symbol.Name, core.LanguageVariantStandard) {"},
  {"line":271,"text":"\t\t\tcontinue"},
  {"line":272,"text":"\t\t}"},
  {"line":274,"text":"\t\tif symbol.ValueDeclaration != nil && ast.IsVariableDeclaration(symbol.ValueDeclaration) {"},
  {"line":275,"text":"\t\t\tcontinue"},
  {"line":276,"text":"\t\t}"},
  {"line":278,"text":"\t\tsymType := f.checker.GetTypeOfSymbol(symbol)"},
  {"line":279,"text":"\t\ttypeNode := f.typeToMinimizedReferenceType(symType, expandoFunc, declarationEmitNodeBuilderFlags)"},
  {"line":280,"text":"\t\tif typeNode == nil {"},
  {"line":281,"text":"\t\t\tcontinue"},
  {"line":282,"text":"\t\t}"},
  {"line":284,"text":"\t\tvarDecl := factory.NewVariableDeclaration(factory.NewIdentifier(symbol.Name), nil, typeNode, nil)"},
  {"line":285,"text":"\t\texportToken := factory.NewToken(ast.KindExportKeyword)"},
  {"line":286,"text":"\t\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsNone)"},
  {"line":287,"text":"\t\tvarStmt := factory.NewVariableStatement(factory.NewModifierList([]*ast.Node{exportToken}), varDeclList)"},
  {"line":288,"text":"\t\tnewProperties = append(newProperties, varStmt)"},
  {"line":289,"text":"\t}"},
  {"line":291,"text":"\tif len(newProperties) == 0 {"},
  {"line":292,"text":"\t\treturn \"\""},
  {"line":293,"text":"\t}"},
  {"line":295,"text":"\tvar modifiers []*ast.Node"},
  {"line":296,"text":"\tif ast.HasSyntacticModifier(expandoFunc, ast.ModifierFlagsExport) {"},
  {"line":297,"text":"\t\tmodifiers = append(modifiers, factory.NewToken(ast.KindExportKeyword))"},
  {"line":298,"text":"\t}"},
  {"line":299,"text":"\tmodifiers = append(modifiers, factory.NewToken(ast.KindDeclareKeyword))"},
  {"line":301,"text":"\tnamespace := factory.NewModuleDeclaration("},
  {"line":302,"text":"\t\tfactory.NewModifierList(modifiers),"},
  {"line":303,"text":"\t\tast.KindNamespaceKeyword,"},
  {"line":304,"text":"\t\tfactory.NewIdentifier(funcDecl.Name().Text()),"},
  {"line":305,"text":"\t\tfactory.NewModuleBlock(factory.NewNodeList(newProperties)),"},
  {"line":306,"text":"\t)"},
  {"line":308,"text":"\tnamespace.Flags = ast.NodeFlagsAmbient | ast.NodeFlagsExportContext | ast.NodeFlagsContextFlags"},
  {"line":310,"text":"\tf.changeTracker.InsertNodeAfter(f.sourceFile, expandoFunc, namespace)"},
  {"line":311,"text":"\treturn diagnostics.Annotate_types_of_properties_expando_function_in_a_namespace.Localize(f.locale)"},
  {"line":312,"text":"}"},
  {"line":315,"text":"func needsParenthesizedExpressionForAssertion(node *ast.Node) bool {"},
  {"line":316,"text":"\treturn !ast.IsEntityNameExpression(node) && !ast.IsCallExpression(node) && !ast.IsObjectLiteralExpression(node) && !ast.IsArrayLiteralExpression(node)"},
  {"line":317,"text":"}"},
  {"line":320,"text":"func createAsExpression(factory *ast.NodeFactory, node *ast.Node, typeNode *ast.Node) *ast.Node {"},
  {"line":321,"text":"\tif needsParenthesizedExpressionForAssertion(node) {"},
  {"line":322,"text":"\t\tnode = factory.NewParenthesizedExpression(node)"},
  {"line":323,"text":"\t}"},
  {"line":324,"text":"\treturn factory.NewAsExpression(node, typeNode)"},
  {"line":325,"text":"}"},
  {"line":327,"text":"func (f *isolatedDeclarationsFixer) addInlineAssertion(span core.TextRange) string {"},
  {"line":328,"text":"\tnodeWithDiag := astnav.GetTokenAtPosition(f.sourceFile, span.Pos())"},
  {"line":331,"text":"\texpandoFunction := findExpandoFunction(f.checker, nodeWithDiag)"},
  {"line":332,"text":"\tif expandoFunction != nil {"},
  {"line":333,"text":"\t\treturn \"\""},
  {"line":334,"text":"\t}"},
  {"line":336,"text":"\ttargetNode := findBestFittingNode(nodeWithDiag, span)"},
  {"line":337,"text":"\tif targetNode == nil || isValueSignatureDeclaration(targetNode) || isValueSignatureDeclaration(targetNode.Parent) {"},
  {"line":338,"text":"\t\treturn \"\""},
  {"line":339,"text":"\t}"},
  {"line":341,"text":"\tisExpressionTarget := ast.IsExpression(targetNode)"},
  {"line":342,"text":"\tisShorthandPropertyAssignmentTarget := ast.IsShorthandPropertyAssignment(targetNode)"},
  {"line":346,"text":"\tif !isShorthandPropertyAssignmentTarget && isNamedDeclarationKind(targetNode) {"},
  {"line":347,"text":"\t\treturn \"\""},
  {"line":348,"text":"\t}"},
  {"line":350,"text":"\tif ast.FindAncestor(targetNode, ast.IsBindingPattern) != nil {"},
  {"line":351,"text":"\t\treturn \"\""},
  {"line":352,"text":"\t}"},
  {"line":354,"text":"\tif ast.FindAncestor(targetNode, ast.IsEnumMember) != nil {"},
  {"line":355,"text":"\t\treturn \"\""},
  {"line":356,"text":"\t}"},
  {"line":358,"text":"\tif isExpressionTarget && (ast.FindAncestorKind(targetNode, ast.KindHeritageClause) != nil || ast.FindAncestor(targetNode, ast.IsTypeNode) != nil) {"},
  {"line":359,"text":"\t\treturn \"\""},
  {"line":360,"text":"\t}"},
  {"line":362,"text":"\tif ast.IsSpreadElement(targetNode) {"},
  {"line":363,"text":"\t\treturn \"\""},
  {"line":364,"text":"\t}"},
  {"line":366,"text":"\tvariableDeclaration := ast.FindAncestorKind(targetNode, ast.KindVariableDeclaration)"},
  {"line":367,"text":"\tvar variableType *checker.Type"},
  {"line":368,"text":"\tif variableDeclaration != nil {"},
  {"line":369,"text":"\t\tvariableType = f.checker.GetTypeAtLocation(variableDeclaration)"},
  {"line":370,"text":"\t}"},
  {"line":372,"text":"\tif variableType != nil && variableType.Flags()&checker.TypeFlagsUniqueESSymbol != 0 {"},
  {"line":373,"text":"\t\treturn \"\""},
  {"line":374,"text":"\t}"},
  {"line":376,"text":"\tif !isExpressionTarget && !isShorthandPropertyAssignmentTarget {"},
  {"line":377,"text":"\t\treturn \"\""},
  {"line":378,"text":"\t}"},
  {"line":380,"text":"\ttypeNode := f.inferType(targetNode, variableType)"},
  {"line":381,"text":"\tif typeNode == nil || f.mutatedTarget {"},
  {"line":382,"text":"\t\treturn \"\""},
  {"line":383,"text":"\t}"},
  {"line":385,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":387,"text":"\tif isShorthandPropertyAssignmentTarget {"},
  {"line":389,"text":"\t\tclonedName := factory.DeepCloneNode(targetNode.AsShorthandPropertyAssignment().Name())"},
  {"line":390,"text":"\t\tasExpr := createAsExpression(factory, clonedName, typeNode)"},
  {"line":391,"text":"\t\tf.changeTracker.InsertNodeAt(f.sourceFile, core.TextPos(targetNode.End()), asExpr, change.NodeOptions{Prefix: \": \"})"},
  {"line":392,"text":"\t} else if isExpressionTarget {"},
  {"line":394,"text":"\t\tclonedTarget := factory.DeepCloneNode(targetNode)"},
  {"line":395,"text":"\t\tif needsParenthesizedExpressionForAssertion(targetNode) {"},
  {"line":396,"text":"\t\t\tclonedTarget = factory.NewParenthesizedExpression(clonedTarget)"},
  {"line":397,"text":"\t\t}"},
  {"line":398,"text":"\t\tclonedType := factory.DeepCloneNode(typeNode)"},
  {"line":399,"text":"\t\tsatisfiesAsExpr := factory.NewAsExpression("},
  {"line":400,"text":"\t\t\tfactory.NewSatisfiesExpression(clonedTarget, clonedType),"},
  {"line":401,"text":"\t\t\ttypeNode,"},
  {"line":402,"text":"\t\t)"},
  {"line":403,"text":"\t\tf.changeTracker.ReplaceNode(f.sourceFile, targetNode, satisfiesAsExpr, nil)"},
  {"line":404,"text":"\t} else {"},
  {"line":405,"text":"\t\treturn \"\""},
  {"line":406,"text":"\t}"},
  {"line":408,"text":"\treturn diagnostics.Add_satisfies_and_an_inline_type_assertion_with_0.Localize(f.locale, typeToStringForDiag(typeNode, f.sourceFile, f.changeTracker))"},
  {"line":409,"text":"}"},
  {"line":411,"text":"func (f *isolatedDeclarationsFixer) extractAsVariable(span core.TextRange) string {"},
  {"line":412,"text":"\tnodeWithDiag := astnav.GetTokenAtPosition(f.sourceFile, span.Pos())"},
  {"line":413,"text":"\ttargetNode := findBestFittingNode(nodeWithDiag, span)"},
  {"line":414,"text":"\tif targetNode == nil || isValueSignatureDeclaration(targetNode) || isValueSignatureDeclaration(targetNode.Parent) {"},
  {"line":415,"text":"\t\treturn \"\""},
  {"line":416,"text":"\t}"},
  {"line":418,"text":"\tif !ast.IsExpression(targetNode) {"},
  {"line":419,"text":"\t\treturn \"\""},
  {"line":420,"text":"\t}"},
  {"line":422,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":425,"text":"\tif ast.IsArrayLiteralExpression(targetNode) {"},
  {"line":426,"text":"\t\tconstRef := factory.NewTypeReferenceNode(factory.NewIdentifier(\"const\"), nil)"},
  {"line":427,"text":"\t\tcloned := factory.DeepCloneNode(targetNode)"},
  {"line":428,"text":"\t\tf.changeTracker.ReplaceNode(f.sourceFile, targetNode, createAsExpression(factory, cloned, constRef), nil)"},
  {"line":429,"text":"\t\treturn diagnostics.Mark_array_literal_as_const.Localize(f.locale)"},
  {"line":430,"text":"\t}"},
  {"line":432,"text":"\tparentPropertyAssignment := ast.FindAncestorKind(targetNode, ast.KindPropertyAssignment)"},
  {"line":433,"text":"\tif parentPropertyAssignment != nil {"},
  {"line":435,"text":"\t\tif parentPropertyAssignment == targetNode.Parent && ast.IsEntityNameExpression(targetNode) {"},
  {"line":436,"text":"\t\t\treturn \"\""},
  {"line":437,"text":"\t\t}"},
  {"line":439,"text":"\t\ttempName := f.changeTracker.EmitContext.Factory.NewUniqueNameEx(getIdentifierNameForNode(targetNode), printer.AutoGenerateOptions{Flags: printer.GeneratedIdentifierFlagsOptimistic})"},
  {"line":441,"text":"\t\treplacementTarget := targetNode"},
  {"line":442,"text":"\t\tinitializationNode := targetNode"},
  {"line":445,"text":"\t\tif ast.IsSpreadElement(replacementTarget) {"},
  {"line":446,"text":"\t\t\treplacementTarget = ast.WalkUpParenthesizedExpressions(replacementTarget.Parent)"},
  {"line":447,"text":"\t\t\tif isConstAssertion(replacementTarget.Parent) {"},
  {"line":448,"text":"\t\t\t\treplacementTarget = replacementTarget.Parent"},
  {"line":449,"text":"\t\t\t\tinitializationNode = replacementTarget"},
  {"line":450,"text":"\t\t\t} else {"},
  {"line":451,"text":"\t\t\t\tconstRef := factory.NewTypeReferenceNode(factory.NewIdentifier(\"const\"), nil)"},
  {"line":452,"text":"\t\t\t\tinitializationNode = createAsExpression(factory, factory.DeepCloneNode(replacementTarget), constRef)"},
  {"line":453,"text":"\t\t\t}"},
  {"line":454,"text":"\t\t}"},
  {"line":456,"text":"\t\tif ast.IsEntityNameExpression(replacementTarget) {"},
  {"line":457,"text":"\t\t\treturn \"\""},
  {"line":458,"text":"\t\t}"},
  {"line":460,"text":"\t\tclonedInit := factory.DeepCloneNode(initializationNode)"},
  {"line":461,"text":"\t\tvarDecl := factory.NewVariableDeclaration(tempName.AsNode(), nil, nil, clonedInit)"},
  {"line":462,"text":"\t\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsConst)"},
  {"line":463,"text":"\t\tvarStmt := factory.NewVariableStatement(nil, varDeclList)"},
  {"line":465,"text":"\t\tstatement := ast.FindAncestor(targetNode, ast.IsStatement)"},
  {"line":466,"text":"\t\tif statement == nil {"},
  {"line":467,"text":"\t\t\treturn \"\""},
  {"line":468,"text":"\t\t}"},
  {"line":469,"text":"\t\tf.changeTracker.InsertNodeBefore(f.sourceFile, statement, varStmt, false, change.LeadingTriviaOptionNone)"},
  {"line":471,"text":"\t\ttypeQuery := factory.NewTypeQueryNode(tempName.AsNode(), nil)"},
  {"line":472,"text":"\t\tasExpr := factory.NewAsExpression(tempName.AsNode(), typeQuery)"},
  {"line":473,"text":"\t\tf.changeTracker.ReplaceNode(f.sourceFile, replacementTarget, asExpr, nil)"},
  {"line":475,"text":"\t\tidText := typeToStringForDiag(tempName.AsNode(), f.sourceFile, f.changeTracker)"},
  {"line":476,"text":"\t\treturn diagnostics.Extract_to_variable_and_replace_with_0_as_typeof_0.Localize(f.locale, idText)"},
  {"line":477,"text":"\t}"},
  {"line":479,"text":"\treturn \"\""},
  {"line":480,"text":"}"},
  {"line":486,"text":"func isExpandoPropertyDeclarationForFix(node *ast.Node) bool {"},
  {"line":487,"text":"\treturn node != nil && (ast.IsPropertyAccessExpression(node) || ast.IsElementAccessExpression(node) || ast.IsBinaryExpression(node))"},
  {"line":488,"text":"}"},
  {"line":490,"text":"func findExpandoFunction(ch *checker.Checker, node *ast.Node) *ast.Node {"},
  {"line":491,"text":"\texpandoDeclaration := ast.FindAncestorOrQuit(node, func(n *ast.Node) ast.FindAncestorResult {"},
  {"line":492,"text":"\t\tif ast.IsStatement(n) {"},
  {"line":493,"text":"\t\t\treturn ast.FindAncestorQuit"},
  {"line":494,"text":"\t\t}"},
  {"line":495,"text":"\t\tif isExpandoPropertyDeclarationForFix(n) {"},
  {"line":496,"text":"\t\t\treturn ast.FindAncestorTrue"},
  {"line":497,"text":"\t\t}"},
  {"line":498,"text":"\t\treturn ast.FindAncestorFalse"},
  {"line":499,"text":"\t})"},
  {"line":501,"text":"\tif expandoDeclaration == nil || !isExpandoPropertyDeclarationForFix(expandoDeclaration) {"},
  {"line":502,"text":"\t\treturn nil"},
  {"line":503,"text":"\t}"},
  {"line":505,"text":"\tassignmentTarget := expandoDeclaration"},
  {"line":507,"text":"\tif ast.IsBinaryExpression(assignmentTarget) {"},
  {"line":508,"text":"\t\tassignmentTarget = assignmentTarget.AsBinaryExpression().Left"},
  {"line":509,"text":"\t\tif !isExpandoPropertyDeclarationForFix(assignmentTarget) {"},
  {"line":510,"text":"\t\t\treturn nil"},
  {"line":511,"text":"\t\t}"},
  {"line":512,"text":"\t}"},
  {"line":514,"text":"\tvar expression *ast.Node"},
  {"line":515,"text":"\tif ast.IsPropertyAccessExpression(assignmentTarget) {"},
  {"line":516,"text":"\t\texpression = assignmentTarget.AsPropertyAccessExpression().Expression"},
  {"line":517,"text":"\t} else if ast.IsElementAccessExpression(assignmentTarget) {"},
  {"line":518,"text":"\t\texpression = assignmentTarget.AsElementAccessExpression().Expression"},
  {"line":519,"text":"\t} else {"},
  {"line":520,"text":"\t\treturn nil"},
  {"line":521,"text":"\t}"},
  {"line":523,"text":"\ttargetType := ch.GetTypeAtLocation(expression)"},
  {"line":524,"text":"\tif targetType == nil {"},
  {"line":525,"text":"\t\treturn nil"},
  {"line":526,"text":"\t}"},
  {"line":528,"text":"\tproperties := ch.GetPropertiesOfType(targetType)"},
  {"line":529,"text":"\tfound := false"},
  {"line":530,"text":"\tfor _, p := range properties {"},
  {"line":531,"text":"\t\tif p.ValueDeclaration == expandoDeclaration || p.ValueDeclaration == expandoDeclaration.Parent {"},
  {"line":532,"text":"\t\t\tfound = true"},
  {"line":533,"text":"\t\t\tbreak"},
  {"line":534,"text":"\t\t}"},
  {"line":535,"text":"\t}"},
  {"line":536,"text":"\tif !found {"},
  {"line":537,"text":"\t\treturn nil"},
  {"line":538,"text":"\t}"},
  {"line":540,"text":"\tsymbol := targetType.Symbol()"},
  {"line":541,"text":"\tif symbol == nil || symbol.ValueDeclaration == nil {"},
  {"line":542,"text":"\t\treturn nil"},
  {"line":543,"text":"\t}"},
  {"line":545,"text":"\tfn := symbol.ValueDeclaration"},
  {"line":546,"text":"\tif (ast.IsFunctionExpression(fn) || ast.IsArrowFunction(fn)) && ast.IsVariableDeclaration(fn.Parent) {"},
  {"line":547,"text":"\t\treturn fn.Parent"},
  {"line":548,"text":"\t}"},
  {"line":549,"text":"\tif ast.IsFunctionDeclaration(fn) {"},
  {"line":550,"text":"\t\treturn fn"},
  {"line":551,"text":"\t}"},
  {"line":553,"text":"\treturn nil"},
  {"line":554,"text":"}"},
  {"line":556,"text":"func (f *isolatedDeclarationsFixer) fixIsolatedDeclarationError(node *ast.Node) string {"},
  {"line":558,"text":"\tif f.fixedNodes[node] {"},
  {"line":559,"text":"\t\treturn \"\""},
  {"line":560,"text":"\t}"},
  {"line":561,"text":"\tf.fixedNodes[node] = true"},
  {"line":563,"text":"\tswitch node.Kind {"},
  {"line":564,"text":"\tcase ast.KindParameter, ast.KindPropertyDeclaration, ast.KindVariableDeclaration:"},
  {"line":565,"text":"\t\treturn f.addTypeToVariableLike(node)"},
  {"line":566,"text":"\tcase ast.KindArrowFunction, ast.KindFunctionExpression, ast.KindFunctionDeclaration,"},
  {"line":567,"text":"\t\tast.KindMethodDeclaration, ast.KindGetAccessor:"},
  {"line":568,"text":"\t\treturn f.addTypeToSignatureDeclaration(node)"},
  {"line":569,"text":"\tcase ast.KindExportAssignment:"},
  {"line":570,"text":"\t\treturn f.transformExportAssignment(node)"},
  {"line":571,"text":"\tcase ast.KindClassDeclaration:"},
  {"line":572,"text":"\t\treturn f.transformExtendsClauseWithExpression(node)"},
  {"line":573,"text":"\tcase ast.KindObjectBindingPattern, ast.KindArrayBindingPattern:"},
  {"line":574,"text":"\t\treturn f.transformDestructuringPatterns(node)"},
  {"line":575,"text":"\tdefault:"},
  {"line":576,"text":"\t\treturn \"\""},
  {"line":577,"text":"\t}"},
  {"line":578,"text":"}"},
  {"line":580,"text":"func (f *isolatedDeclarationsFixer) addTypeToSignatureDeclaration(funcNode *ast.Node) string {"},
  {"line":581,"text":"\tif funcNode.Type() != nil {"},
  {"line":582,"text":"\t\treturn \"\""},
  {"line":583,"text":"\t}"},
  {"line":584,"text":"\ttypeNode := f.inferType(funcNode, nil)"},
  {"line":585,"text":"\tif typeNode == nil {"},
  {"line":586,"text":"\t\treturn \"\""},
  {"line":587,"text":"\t}"},
  {"line":588,"text":"\tf.changeTracker.TryInsertTypeAnnotation(f.sourceFile, funcNode, typeNode)"},
  {"line":589,"text":"\treturn diagnostics.Add_return_type_0.Localize(f.locale, typeToStringForDiag(typeNode, f.sourceFile, f.changeTracker))"},
  {"line":590,"text":"}"},
  {"line":592,"text":"func (f *isolatedDeclarationsFixer) transformExportAssignment(defaultExport *ast.Node) string {"},
  {"line":593,"text":"\texportAssignment := defaultExport.AsExportAssignment()"},
  {"line":594,"text":"\tif exportAssignment.IsExportEquals {"},
  {"line":595,"text":"\t\treturn \"\""},
  {"line":596,"text":"\t}"},
  {"line":598,"text":"\texpression := exportAssignment.Expression"},
  {"line":599,"text":"\ttypeNode := f.inferType(expression, nil)"},
  {"line":600,"text":"\tif typeNode == nil {"},
  {"line":601,"text":"\t\treturn \"\""},
  {"line":602,"text":"\t}"},
  {"line":604,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":606,"text":"\tdefaultIdentifier := f.changeTracker.EmitContext.Factory.NewUniqueName(\"_default\")"},
  {"line":609,"text":"\tclonedExpression := factory.DeepCloneNode(expression)"},
  {"line":611,"text":"\tvarDecl := factory.NewVariableDeclaration(defaultIdentifier.AsNode(), nil, typeNode, clonedExpression)"},
  {"line":612,"text":"\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsConst)"},
  {"line":613,"text":"\tvarStmt := factory.NewVariableStatement(nil, varDeclList)"},
  {"line":615,"text":"\tnewExport := factory.UpdateExportAssignment(defaultExport.AsExportAssignment(), defaultExport.Modifiers(), false, nil, defaultIdentifier.AsNode())"},
  {"line":617,"text":"\tf.changeTracker.ReplaceNodeWithNodes(f.sourceFile, defaultExport, []*ast.Node{varStmt, newExport}, nil)"},
  {"line":618,"text":"\treturn diagnostics.Extract_default_export_to_variable.Localize(f.locale)"},
  {"line":619,"text":"}"},
  {"line":621,"text":"func (f *isolatedDeclarationsFixer) transformExtendsClauseWithExpression(classDecl *ast.Node) string {"},
  {"line":622,"text":"\tcd := classDecl.AsClassDeclaration()"},
  {"line":623,"text":"\tvar extendsClause *ast.Node"},
  {"line":624,"text":"\tif cd.HeritageClauses != nil {"},
  {"line":625,"text":"\t\tfor _, clause := range cd.HeritageClauses.Nodes {"},
  {"line":626,"text":"\t\t\tif clause.AsHeritageClause().Token == ast.KindExtendsKeyword {"},
  {"line":627,"text":"\t\t\t\textendsClause = clause"},
  {"line":628,"text":"\t\t\t\tbreak"},
  {"line":629,"text":"\t\t\t}"},
  {"line":630,"text":"\t\t}"},
  {"line":631,"text":"\t}"},
  {"line":632,"text":"\tif extendsClause == nil {"},
  {"line":633,"text":"\t\treturn \"\""},
  {"line":634,"text":"\t}"},
  {"line":636,"text":"\theritageTypes := extendsClause.AsHeritageClause().Types"},
  {"line":637,"text":"\tif heritageTypes == nil || len(heritageTypes.Nodes) == 0 {"},
  {"line":638,"text":"\t\treturn \"\""},
  {"line":639,"text":"\t}"},
  {"line":640,"text":"\theritageExpression := heritageTypes.Nodes[0]"},
  {"line":641,"text":"\texpression := heritageExpression.AsExpressionWithTypeArguments().Expression"},
  {"line":643,"text":"\theritageTypeNode := f.inferType(expression, nil)"},
  {"line":644,"text":"\tif heritageTypeNode == nil {"},
  {"line":645,"text":"\t\treturn \"\""},
  {"line":646,"text":"\t}"},
  {"line":648,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":650,"text":"\tbaseName := \"Anonymous\""},
  {"line":651,"text":"\tif cd.Name() != nil {"},
  {"line":652,"text":"\t\tbaseName = cd.Name().Text() + \"Base\""},
  {"line":653,"text":"\t}"},
  {"line":654,"text":"\tbaseClassName := f.changeTracker.EmitContext.Factory.NewUniqueNameEx(baseName, printer.AutoGenerateOptions{Flags: printer.GeneratedIdentifierFlagsOptimistic})"},
  {"line":657,"text":"\tclonedExpression := factory.DeepCloneNode(expression)"},
  {"line":658,"text":"\tvarDecl := factory.NewVariableDeclaration(baseClassName.AsNode(), nil, heritageTypeNode, clonedExpression)"},
  {"line":659,"text":"\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsConst)"},
  {"line":660,"text":"\tvarStmt := factory.NewVariableStatement(nil, varDeclList)"},
  {"line":662,"text":"\tf.changeTracker.InsertNodeBefore(f.sourceFile, classDecl, varStmt, false, change.LeadingTriviaOptionNone)"},
  {"line":665,"text":"\tf.changeTracker.ReplaceNode(f.sourceFile, heritageExpression, factory.NewExpressionWithTypeArguments(baseClassName.AsNode(), nil), nil)"},
  {"line":667,"text":"\treturn diagnostics.Extract_base_class_to_variable.Localize(f.locale)"},
  {"line":668,"text":"}"},
  {"line":670,"text":"func (f *isolatedDeclarationsFixer) transformDestructuringPatterns(bindingPattern *ast.Node) string {"},
  {"line":671,"text":"\tenclosingVariableDeclaration := bindingPattern.Parent"},
  {"line":672,"text":"\tif !ast.IsVariableDeclaration(enclosingVariableDeclaration) {"},
  {"line":673,"text":"\t\treturn \"\""},
  {"line":674,"text":"\t}"},
  {"line":675,"text":"\tenclosingVarStmt := enclosingVariableDeclaration.Parent.Parent"},
  {"line":676,"text":"\tif !ast.IsVariableStatement(enclosingVarStmt) {"},
  {"line":677,"text":"\t\treturn \"\""},
  {"line":678,"text":"\t}"},
  {"line":680,"text":"\tinitializer := enclosingVariableDeclaration.Initializer()"},
  {"line":681,"text":"\tif initializer == nil {"},
  {"line":682,"text":"\t\treturn \"\""},
  {"line":683,"text":"\t}"},
  {"line":685,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":686,"text":"\tvar newNodes []*ast.Node"},
  {"line":688,"text":"\tvar baseExprNode *ast.Node"},
  {"line":689,"text":"\tif !ast.IsIdentifier(initializer) {"},
  {"line":691,"text":"\t\ttempName := f.changeTracker.EmitContext.Factory.NewUniqueNameEx(\"dest\", printer.AutoGenerateOptions{Flags: printer.GeneratedIdentifierFlagsOptimistic})"},
  {"line":692,"text":"\t\tclonedInitializer := factory.DeepCloneNode(initializer)"},
  {"line":693,"text":"\t\tvarDecl := factory.NewVariableDeclaration(tempName.AsNode(), nil, nil, clonedInitializer)"},
  {"line":694,"text":"\t\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsConst)"},
  {"line":695,"text":"\t\tvarStmt := factory.NewVariableStatement(nil, varDeclList)"},
  {"line":696,"text":"\t\tnewNodes = append(newNodes, varStmt)"},
  {"line":697,"text":"\t\tbaseExprNode = tempName.AsNode()"},
  {"line":698,"text":"\t} else {"},
  {"line":700,"text":"\t\tbaseExprNode = factory.NewIdentifier(initializer.Text())"},
  {"line":701,"text":"\t}"},
  {"line":704,"text":"\tf.extractBindingElements(bindingPattern, baseExprNode, &newNodes, enclosingVarStmt)"},
  {"line":706,"text":"\tif len(newNodes) == 0 {"},
  {"line":707,"text":"\t\treturn \"\""},
  {"line":708,"text":"\t}"},
  {"line":711,"text":"\tdeclList := enclosingVarStmt.AsVariableStatement().DeclarationList.AsVariableDeclarationList()"},
  {"line":712,"text":"\tif len(declList.Declarations.Nodes) > 1 {"},
  {"line":713,"text":"\t\tvar remainingDecls []*ast.Node"},
  {"line":714,"text":"\t\tfor _, d := range declList.Declarations.Nodes {"},
  {"line":715,"text":"\t\t\tif d != enclosingVariableDeclaration {"},
  {"line":716,"text":"\t\t\t\tremainingDecls = append(remainingDecls, d)"},
  {"line":717,"text":"\t\t\t}"},
  {"line":718,"text":"\t\t}"},
  {"line":719,"text":"\t\tif len(remainingDecls) > 0 {"},
  {"line":720,"text":"\t\t\tnewNodes = append(newNodes, factory.UpdateVariableStatement("},
  {"line":721,"text":"\t\t\t\tenclosingVarStmt.AsVariableStatement(),"},
  {"line":722,"text":"\t\t\t\tenclosingVarStmt.AsVariableStatement().Modifiers(),"},
  {"line":723,"text":"\t\t\t\tfactory.UpdateVariableDeclarationList("},
  {"line":724,"text":"\t\t\t\t\tdeclList,"},
  {"line":725,"text":"\t\t\t\t\tfactory.NewNodeList(remainingDecls),"},
  {"line":726,"text":"\t\t\t\t\tdeclList.Flags,"},
  {"line":727,"text":"\t\t\t\t),"},
  {"line":728,"text":"\t\t\t))"},
  {"line":729,"text":"\t\t}"},
  {"line":730,"text":"\t}"},
  {"line":732,"text":"\tf.changeTracker.ReplaceNodeWithNodes(f.sourceFile, enclosingVarStmt, newNodes, nil)"},
  {"line":733,"text":"\treturn diagnostics.Extract_binding_expressions_to_variable.Localize(f.locale)"},
  {"line":734,"text":"}"},
  {"line":736,"text":"func (f *isolatedDeclarationsFixer) extractBindingElements("},
  {"line":737,"text":"\tbindingPattern *ast.Node,"},
  {"line":738,"text":"\tbaseExpr *ast.Node,"},
  {"line":739,"text":"\tnewNodes *[]*ast.Node,"},
  {"line":740,"text":"\tenclosingVarStmt *ast.Node,"},
  {"line":741,"text":") {"},
  {"line":742,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":744,"text":"\tif ast.IsObjectBindingPattern(bindingPattern) {"},
  {"line":745,"text":"\t\tfor _, element := range bindingPattern.AsBindingPattern().Elements.Nodes {"},
  {"line":746,"text":"\t\t\tif ast.IsOmittedExpression(element) {"},
  {"line":747,"text":"\t\t\t\tcontinue"},
  {"line":748,"text":"\t\t\t}"},
  {"line":749,"text":"\t\t\tbe := element.AsBindingElement()"},
  {"line":750,"text":"\t\t\tname := be.Name()"},
  {"line":751,"text":"\t\t\tif name == nil {"},
  {"line":752,"text":"\t\t\t\tcontinue"},
  {"line":753,"text":"\t\t\t}"},
  {"line":756,"text":"\t\t\tvar accessExpr *ast.Node"},
  {"line":757,"text":"\t\t\tif be.PropertyName != nil && ast.IsComputedPropertyName(be.PropertyName) {"},
  {"line":759,"text":"\t\t\t\tcomputedExpression := be.PropertyName.AsComputedPropertyName().Expression"},
  {"line":760,"text":"\t\t\t\tidentifierForComputedProperty := f.changeTracker.EmitContext.Factory.NewGeneratedNameForNode(computedExpression)"},
  {"line":761,"text":"\t\t\t\tcompVarDecl := factory.NewVariableDeclaration(identifierForComputedProperty.AsNode(), nil, nil, computedExpression)"},
  {"line":762,"text":"\t\t\t\tcompVarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{compVarDecl}), ast.NodeFlagsConst)"},
  {"line":763,"text":"\t\t\t\tcompVarStmt := factory.NewVariableStatement(nil, compVarDeclList)"},
  {"line":764,"text":"\t\t\t\t*newNodes = append(*newNodes, compVarStmt)"},
  {"line":765,"text":"\t\t\t\taccessExpr = factory.NewElementAccessExpression(baseExpr, nil, identifierForComputedProperty.AsNode(), ast.NodeFlagsNone)"},
  {"line":766,"text":"\t\t\t} else if be.PropertyName != nil {"},
  {"line":768,"text":"\t\t\t\tpropText := be.PropertyName.Text()"},
  {"line":769,"text":"\t\t\t\taccessExpr = factory.NewPropertyAccessExpression(baseExpr, nil, factory.NewIdentifier(propText), ast.NodeFlagsNone)"},
  {"line":770,"text":"\t\t\t} else if ast.IsIdentifier(name) {"},
  {"line":771,"text":"\t\t\t\taccessExpr = factory.NewPropertyAccessExpression(baseExpr, nil, factory.NewIdentifier(name.Text()), ast.NodeFlagsNone)"},
  {"line":772,"text":"\t\t\t} else {"},
  {"line":773,"text":"\t\t\t\tcontinue"},
  {"line":774,"text":"\t\t\t}"},
  {"line":776,"text":"\t\t\tif ast.IsBindingPattern(name) {"},
  {"line":777,"text":"\t\t\t\tf.extractBindingElements(name, accessExpr, newNodes, enclosingVarStmt)"},
  {"line":778,"text":"\t\t\t} else {"},
  {"line":779,"text":"\t\t\t\tf.emitBindingElementVariable(factory, name, be, accessExpr, newNodes, enclosingVarStmt)"},
  {"line":780,"text":"\t\t\t}"},
  {"line":781,"text":"\t\t}"},
  {"line":782,"text":"\t} else if ast.IsArrayBindingPattern(bindingPattern) {"},
  {"line":783,"text":"\t\tfor i, element := range bindingPattern.AsBindingPattern().Elements.Nodes {"},
  {"line":784,"text":"\t\t\tif ast.IsOmittedExpression(element) {"},
  {"line":785,"text":"\t\t\t\tcontinue"},
  {"line":786,"text":"\t\t\t}"},
  {"line":787,"text":"\t\t\tbe := element.AsBindingElement()"},
  {"line":788,"text":"\t\t\tname := be.Name()"},
  {"line":789,"text":"\t\t\tif name == nil {"},
  {"line":790,"text":"\t\t\t\tcontinue"},
  {"line":791,"text":"\t\t\t}"},
  {"line":793,"text":"\t\t\taccessExpr := factory.NewElementAccessExpression(baseExpr, nil, factory.NewNumericLiteral(strconv.Itoa(i), ast.TokenFlagsNone), ast.NodeFlagsNone)"},
  {"line":795,"text":"\t\t\tif ast.IsBindingPattern(name) {"},
  {"line":796,"text":"\t\t\t\tf.extractBindingElements(name, accessExpr, newNodes, enclosingVarStmt)"},
  {"line":797,"text":"\t\t\t} else {"},
  {"line":798,"text":"\t\t\t\tf.emitBindingElementVariable(factory, name, be, accessExpr, newNodes, enclosingVarStmt)"},
  {"line":799,"text":"\t\t\t}"},
  {"line":800,"text":"\t\t}"},
  {"line":801,"text":"\t}"},
  {"line":802,"text":"}"},
  {"line":806,"text":"func (f *isolatedDeclarationsFixer) emitBindingElementVariable("},
  {"line":807,"text":"\tfactory *ast.NodeFactory,"},
  {"line":808,"text":"\tname *ast.Node,"},
  {"line":809,"text":"\tbe *ast.BindingElement,"},
  {"line":810,"text":"\taccessExpr *ast.Node,"},
  {"line":811,"text":"\tnewNodes *[]*ast.Node,"},
  {"line":812,"text":"\tenclosingVarStmt *ast.Node,"},
  {"line":813,"text":") {"},
  {"line":814,"text":"\ttypeNode := f.inferType(name, nil)"},
  {"line":815,"text":"\tvariableInitializer := accessExpr"},
  {"line":817,"text":"\tif be.Initializer != nil {"},
  {"line":820,"text":"\t\tpropName := be.PropertyName"},
  {"line":821,"text":"\t\ttempBaseName := \"temp\""},
  {"line":822,"text":"\t\tif propName != nil && ast.IsIdentifier(propName) {"},
  {"line":823,"text":"\t\t\ttempBaseName = propName.Text()"},
  {"line":824,"text":"\t\t}"},
  {"line":825,"text":"\t\ttempName := f.changeTracker.EmitContext.Factory.NewUniqueNameEx(tempBaseName, printer.AutoGenerateOptions{Flags: printer.GeneratedIdentifierFlagsOptimistic})"},
  {"line":826,"text":"\t\ttempVarDecl := factory.NewVariableDeclaration(tempName.AsNode(), nil, nil, variableInitializer)"},
  {"line":827,"text":"\t\ttempVarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{tempVarDecl}), ast.NodeFlagsConst)"},
  {"line":828,"text":"\t\ttempVarStmt := factory.NewVariableStatement(nil, tempVarDeclList)"},
  {"line":829,"text":"\t\t*newNodes = append(*newNodes, tempVarStmt)"},
  {"line":831,"text":"\t\tvariableInitializer = factory.NewConditionalExpression("},
  {"line":832,"text":"\t\t\tfactory.NewBinaryExpression("},
  {"line":833,"text":"\t\t\t\tnil,"},
  {"line":834,"text":"\t\t\t\ttempName.AsNode(),"},
  {"line":835,"text":"\t\t\t\tnil,"},
  {"line":836,"text":"\t\t\t\tfactory.NewToken(ast.KindEqualsEqualsEqualsToken),"},
  {"line":837,"text":"\t\t\t\tfactory.NewIdentifier(\"undefined\"),"},
  {"line":838,"text":"\t\t\t),"},
  {"line":839,"text":"\t\t\tfactory.NewToken(ast.KindQuestionToken),"},
  {"line":840,"text":"\t\t\tbe.Initializer,"},
  {"line":841,"text":"\t\t\tfactory.NewToken(ast.KindColonToken),"},
  {"line":842,"text":"\t\t\tvariableInitializer,"},
  {"line":843,"text":"\t\t)"},
  {"line":844,"text":"\t}"},
  {"line":846,"text":"\texportModifier := f.getExportModifier(enclosingVarStmt)"},
  {"line":847,"text":"\tvarDecl := factory.NewVariableDeclaration(factory.NewIdentifier(name.Text()), nil, typeNode, variableInitializer)"},
  {"line":848,"text":"\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsConst)"},
  {"line":849,"text":"\tvarStmt := factory.NewVariableStatement(exportModifier, varDeclList)"},
  {"line":850,"text":"\t*newNodes = append(*newNodes, varStmt)"},
  {"line":851,"text":"}"},
  {"line":853,"text":"func (f *isolatedDeclarationsFixer) getExportModifier(enclosingVarStmt *ast.Node) *ast.ModifierList {"},
  {"line":854,"text":"\tif ast.HasSyntacticModifier(enclosingVarStmt, ast.ModifierFlagsExport) {"},
  {"line":855,"text":"\t\texportToken := f.changeTracker.NodeFactory.NewToken(ast.KindExportKeyword)"},
  {"line":856,"text":"\t\treturn f.changeTracker.NodeFactory.NewModifierList([]*ast.Node{exportToken})"},
  {"line":857,"text":"\t}"},
  {"line":858,"text":"\treturn nil"},
  {"line":859,"text":"}"},
  {"line":861,"text":"func (f *isolatedDeclarationsFixer) inferType(node *ast.Node, variableType *checker.Type) *ast.TypeNode {"},
  {"line":862,"text":"\tf.mutatedTarget = false"},
  {"line":865,"text":"\tif f.typePrintMode == typePrintModeRelative {"},
  {"line":866,"text":"\t\treturn f.relativeType(node)"},
  {"line":867,"text":"\t}"},
  {"line":869,"text":"\tvar t *checker.Type"},
  {"line":871,"text":"\tif isValueSignatureDeclaration(node) {"},
  {"line":872,"text":"\t\tsignature := f.checker.GetSignatureFromDeclaration(node)"},
  {"line":873,"text":"\t\tif signature != nil {"},
  {"line":874,"text":"\t\t\ttypePredicate := f.checker.GetTypePredicateOfSignature(signature)"},
  {"line":875,"text":"\t\t\tif typePredicate != nil {"},
  {"line":876,"text":"\t\t\t\tif typePredicate.Type() == nil {"},
  {"line":877,"text":"\t\t\t\t\treturn nil"},
  {"line":878,"text":"\t\t\t\t}"},
  {"line":879,"text":"\t\t\t\tenclosingDecl := ast.FindAncestor(node, ast.IsDeclaration)"},
  {"line":880,"text":"\t\t\t\tif enclosingDecl == nil {"},
  {"line":881,"text":"\t\t\t\t\tenclosingDecl = f.sourceFile.AsNode()"},
  {"line":882,"text":"\t\t\t\t}"},
  {"line":883,"text":"\t\t\t\tflags := declarationEmitNodeBuilderFlags"},
  {"line":884,"text":"\t\t\t\tif typePredicate.Type().Flags()&checker.TypeFlagsUniqueESSymbol != 0 {"},
  {"line":885,"text":"\t\t\t\t\tflags |= nodebuilder.FlagsAllowUniqueESSymbolType"},
  {"line":886,"text":"\t\t\t\t}"},
  {"line":887,"text":"\t\t\t\tresult := f.checker.TypePredicateToTypePredicateNode(typePredicate, enclosingDecl, flags, nil)"},
  {"line":888,"text":"\t\t\t\tif result != nil {"},
  {"line":889,"text":"\t\t\t\t\treturn result.AsNode()"},
  {"line":890,"text":"\t\t\t\t}"},
  {"line":891,"text":"\t\t\t\treturn nil"},
  {"line":892,"text":"\t\t\t}"},
  {"line":893,"text":"\t\t\tt = f.checker.GetReturnTypeOfSignature(signature)"},
  {"line":894,"text":"\t\t}"},
  {"line":895,"text":"\t} else {"},
  {"line":896,"text":"\t\tt = f.checker.GetTypeAtLocation(node)"},
  {"line":897,"text":"\t}"},
  {"line":899,"text":"\tif t == nil {"},
  {"line":900,"text":"\t\treturn nil"},
  {"line":901,"text":"\t}"},
  {"line":904,"text":"\tif f.typePrintMode == typePrintModeWidened {"},
  {"line":905,"text":"\t\tif variableType != nil {"},
  {"line":906,"text":"\t\t\tt = variableType"},
  {"line":907,"text":"\t\t}"},
  {"line":908,"text":"\t\twidenedType := f.checker.GetWidenedLiteralType(t)"},
  {"line":909,"text":"\t\tif f.checker.IsTypeAssignableTo(widenedType, t) {"},
  {"line":910,"text":"\t\t\treturn nil // widened type is same, no fix needed"},
  {"line":911,"text":"\t\t}"},
  {"line":912,"text":"\t\tt = widenedType"},
  {"line":913,"text":"\t}"},
  {"line":915,"text":"\tenclosingDecl := ast.FindAncestor(node, ast.IsDeclaration)"},
  {"line":916,"text":"\tif enclosingDecl == nil {"},
  {"line":917,"text":"\t\tenclosingDecl = f.sourceFile.AsNode()"},
  {"line":918,"text":"\t}"},
  {"line":920,"text":"\tflags := declarationEmitNodeBuilderFlags | f.getExtraFlags(node, t)"},
  {"line":923,"text":"\tif ast.IsParameterDeclaration(node) && f.checker.RequiresAddingImplicitUndefined(node) {"},
  {"line":924,"text":"\t\tt = f.checker.GetUnionTypeEx([]*checker.Type{f.checker.GetUndefinedType(), t}, checker.UnionReductionNone)"},
  {"line":925,"text":"\t}"},
  {"line":927,"text":"\ttypeNode := f.typeToMinimizedReferenceType(t, enclosingDecl, flags)"},
  {"line":928,"text":"\treturn typeNode"},
  {"line":929,"text":"}"},
  {"line":931,"text":"func (f *isolatedDeclarationsFixer) getExtraFlags(node *ast.Node, t *checker.Type) nodebuilder.Flags {"},
  {"line":932,"text":"\tif (ast.IsVariableDeclaration(node) ||"},
  {"line":933,"text":"\t\t(ast.IsPropertyDeclaration(node) && ast.HasSyntacticModifier(node, ast.ModifierFlagsStatic|ast.ModifierFlagsReadonly))) &&"},
  {"line":934,"text":"\t\tt.Flags()&checker.TypeFlagsUniqueESSymbol != 0 {"},
  {"line":935,"text":"\t\treturn nodebuilder.FlagsAllowUniqueESSymbolType"},
  {"line":936,"text":"\t}"},
  {"line":937,"text":"\treturn nodebuilder.FlagsNone"},
  {"line":938,"text":"}"},
  {"line":941,"text":"func (f *isolatedDeclarationsFixer) createTypeOfFromEntityNameExpression(node *ast.Node) *ast.TypeNode {"},
  {"line":942,"text":"\treturn f.changeTracker.NodeFactory.NewTypeQueryNode("},
  {"line":943,"text":"\t\tf.changeTracker.NodeFactory.DeepCloneNode(node), nil)"},
  {"line":944,"text":"}"},
  {"line":948,"text":"func (f *isolatedDeclarationsFixer) typeFromArraySpreadElements(node *ast.ArrayLiteralExpression, name string) *ast.TypeNode {"},
  {"line":949,"text":"\tisInConstContext := ast.FindAncestor(node.AsNode(), isConstAssertion) != nil"},
  {"line":950,"text":"\tif !isInConstContext {"},
  {"line":951,"text":"\t\treturn nil"},
  {"line":952,"text":"\t}"},
  {"line":953,"text":"\tif name == \"\" {"},
  {"line":954,"text":"\t\tname = \"temp\""},
  {"line":955,"text":"\t}"},
  {"line":956,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":957,"text":"\treturn f.typeFromSpreads("},
  {"line":958,"text":"\t\tnode.AsNode(),"},
  {"line":959,"text":"\t\tname,"},
  {"line":960,"text":"\t\tisInConstContext,"},
  {"line":961,"text":"\t\tfunc(n *ast.Node) []*ast.Node {"},
  {"line":962,"text":"\t\t\treturn n.AsArrayLiteralExpression().Elements.Nodes"},
  {"line":963,"text":"\t\t},"},
  {"line":964,"text":"\t\tast.IsSpreadElement,"},
  {"line":965,"text":"\t\tfunc(expr *ast.Node) *ast.Node {"},
  {"line":966,"text":"\t\t\treturn factory.NewSpreadElement(expr)"},
  {"line":967,"text":"\t\t},"},
  {"line":968,"text":"\t\tfunc(elements []*ast.Node) *ast.Node {"},
  {"line":969,"text":"\t\t\treturn factory.NewArrayLiteralExpression(factory.NewNodeList(elements), true)"},
  {"line":970,"text":"\t\t},"},
  {"line":971,"text":"\t\tfunc(types []*ast.TypeNode) *ast.TypeNode {"},
  {"line":972,"text":"\t\t\trestTypes := make([]*ast.TypeNode, len(types))"},
  {"line":973,"text":"\t\t\tfor i, t := range types {"},
  {"line":974,"text":"\t\t\t\trestTypes[i] = factory.NewRestTypeNode(t)"},
  {"line":975,"text":"\t\t\t}"},
  {"line":976,"text":"\t\t\treturn factory.NewTupleTypeNode(factory.NewNodeList(restTypes))"},
  {"line":977,"text":"\t\t},"},
  {"line":978,"text":"\t)"},
  {"line":979,"text":"}"},
  {"line":983,"text":"func (f *isolatedDeclarationsFixer) typeFromObjectSpreadAssignment(node *ast.ObjectLiteralExpression, name string) *ast.TypeNode {"},
  {"line":984,"text":"\tisInConstContext := ast.FindAncestor(node.AsNode(), isConstAssertion) != nil"},
  {"line":985,"text":"\tif name == \"\" {"},
  {"line":986,"text":"\t\tname = \"temp\""},
  {"line":987,"text":"\t}"},
  {"line":988,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":989,"text":"\treturn f.typeFromSpreads("},
  {"line":990,"text":"\t\tnode.AsNode(),"},
  {"line":991,"text":"\t\tname,"},
  {"line":992,"text":"\t\tisInConstContext,"},
  {"line":993,"text":"\t\tfunc(n *ast.Node) []*ast.Node {"},
  {"line":994,"text":"\t\t\tif n.AsObjectLiteralExpression().Properties != nil {"},
  {"line":995,"text":"\t\t\t\treturn n.AsObjectLiteralExpression().Properties.Nodes"},
  {"line":996,"text":"\t\t\t}"},
  {"line":997,"text":"\t\t\treturn nil"},
  {"line":998,"text":"\t\t},"},
  {"line":999,"text":"\t\tast.IsSpreadAssignment,"},
  {"line":1000,"text":"\t\tfunc(expr *ast.Node) *ast.Node {"},
  {"line":1001,"text":"\t\t\treturn factory.NewSpreadAssignment(expr)"},
  {"line":1002,"text":"\t\t},"},
  {"line":1003,"text":"\t\tfunc(elements []*ast.Node) *ast.Node {"},
  {"line":1004,"text":"\t\t\treturn factory.NewObjectLiteralExpression(factory.NewNodeList(elements), true)"},
  {"line":1005,"text":"\t\t},"},
  {"line":1006,"text":"\t\tfunc(types []*ast.TypeNode) *ast.TypeNode {"},
  {"line":1007,"text":"\t\t\treturn factory.NewIntersectionTypeNode(factory.NewNodeList(types))"},
  {"line":1008,"text":"\t\t},"},
  {"line":1009,"text":"\t)"},
  {"line":1010,"text":"}"},
  {"line":1014,"text":"func (f *isolatedDeclarationsFixer) typeFromSpreads("},
  {"line":1015,"text":"\tnode *ast.Node,"},
  {"line":1016,"text":"\tname string,"},
  {"line":1017,"text":"\tisInConstContext bool,"},
  {"line":1018,"text":"\tgetChildren func(*ast.Node) []*ast.Node,"},
  {"line":1019,"text":"\tisSpread func(*ast.Node) bool,"},
  {"line":1020,"text":"\tcreateSpread func(*ast.Node) *ast.Node,"},
  {"line":1021,"text":"\tmakeNodeOfKind func([]*ast.Node) *ast.Node,"},
  {"line":1022,"text":"\tfinalType func([]*ast.TypeNode) *ast.TypeNode,"},
  {"line":1023,"text":") *ast.TypeNode {"},
  {"line":1024,"text":"\tfactory := f.changeTracker.NodeFactory"},
  {"line":1025,"text":"\tvar intersectionTypes []*ast.TypeNode"},
  {"line":1026,"text":"\tvar newSpreads []*ast.Node"},
  {"line":1027,"text":"\tvar currentVariableProperties []*ast.Node"},
  {"line":1029,"text":"\tstatement := ast.FindAncestor(node, ast.IsStatement)"},
  {"line":1031,"text":"\tchildren := getChildren(node)"},
  {"line":1032,"text":"\tfor _, prop := range children {"},
  {"line":1033,"text":"\t\tif isSpread(prop) {"},
  {"line":1034,"text":"\t\t\tf.finalizesVariablePart(factory, name, isInConstContext, statement, makeNodeOfKind, createSpread, &currentVariableProperties, &intersectionTypes, &newSpreads)"},
  {"line":1035,"text":"\t\t\tif ast.IsEntityNameExpression(prop.Expression()) {"},
  {"line":1036,"text":"\t\t\t\tintersectionTypes = append(intersectionTypes, f.createTypeOfFromEntityNameExpression(prop.Expression()))"},
  {"line":1037,"text":"\t\t\t\tnewSpreads = append(newSpreads, prop)"},
  {"line":1038,"text":"\t\t\t} else {"},
  {"line":1039,"text":"\t\t\t\tf.makeSpreadVariable(factory, name, isInConstContext, statement, createSpread, prop.Expression(), &intersectionTypes, &newSpreads)"},
  {"line":1040,"text":"\t\t\t}"},
  {"line":1041,"text":"\t\t} else {"},
  {"line":1042,"text":"\t\t\tcurrentVariableProperties = append(currentVariableProperties, prop)"},
  {"line":1043,"text":"\t\t}"},
  {"line":1044,"text":"\t}"},
  {"line":1046,"text":"\tif len(newSpreads) == 0 {"},
  {"line":1047,"text":"\t\treturn nil"},
  {"line":1048,"text":"\t}"},
  {"line":1050,"text":"\tf.finalizesVariablePart(factory, name, isInConstContext, statement, makeNodeOfKind, createSpread, &currentVariableProperties, &intersectionTypes, &newSpreads)"},
  {"line":1052,"text":"\tf.changeTracker.ReplaceNode(f.sourceFile, node, makeNodeOfKind(newSpreads), nil)"},
  {"line":1053,"text":"\tf.mutatedTarget = true"},
  {"line":1055,"text":"\treturn finalType(intersectionTypes)"},
  {"line":1056,"text":"}"},
  {"line":1059,"text":"func (f *isolatedDeclarationsFixer) makeSpreadVariable("},
  {"line":1060,"text":"\tfactory *ast.NodeFactory,"},
  {"line":1061,"text":"\tname string,"},
  {"line":1062,"text":"\tisInConstContext bool,"},
  {"line":1063,"text":"\tstatement *ast.Node,"},
  {"line":1064,"text":"\tcreateSpread func(*ast.Node) *ast.Node,"},
  {"line":1065,"text":"\texpression *ast.Node,"},
  {"line":1066,"text":"\tintersectionTypes *[]*ast.TypeNode,"},
  {"line":1067,"text":"\tnewSpreads *[]*ast.Node,"},
  {"line":1068,"text":") {"},
  {"line":1069,"text":"\ttempName := f.changeTracker.EmitContext.Factory.NewUniqueNameEx("},
  {"line":1070,"text":"\t\tname+\"_Part\"+strconv.Itoa(len(*newSpreads)+1),"},
  {"line":1071,"text":"\t\tprinter.AutoGenerateOptions{Flags: printer.GeneratedIdentifierFlagsOptimistic},"},
  {"line":1072,"text":"\t).AsNode()"},
  {"line":1074,"text":"\tvar initializer *ast.Node"},
  {"line":1075,"text":"\tif !isInConstContext {"},
  {"line":1076,"text":"\t\tinitializer = factory.DeepCloneNode(expression)"},
  {"line":1077,"text":"\t} else {"},
  {"line":1078,"text":"\t\tconstRef := factory.NewTypeReferenceNode(factory.NewIdentifier(\"const\"), nil)"},
  {"line":1079,"text":"\t\tinitializer = factory.NewAsExpression(factory.DeepCloneNode(expression), constRef)"},
  {"line":1080,"text":"\t}"},
  {"line":1082,"text":"\tvarDecl := factory.NewVariableDeclaration(tempName, nil, nil, initializer)"},
  {"line":1083,"text":"\tvarDeclList := factory.NewVariableDeclarationList(factory.NewNodeList([]*ast.Node{varDecl}), ast.NodeFlagsConst)"},
  {"line":1084,"text":"\tvarStmt := factory.NewVariableStatement(nil, varDeclList)"},
  {"line":1086,"text":"\tif statement != nil {"},
  {"line":1087,"text":"\t\tf.changeTracker.InsertNodeBefore(f.sourceFile, statement, varStmt, false, change.LeadingTriviaOptionNone)"},
  {"line":1088,"text":"\t}"},
  {"line":1090,"text":"\t*intersectionTypes = append(*intersectionTypes, f.createTypeOfFromEntityNameExpression(tempName))"},
  {"line":1091,"text":"\t*newSpreads = append(*newSpreads, createSpread(tempName))"},
  {"line":1092,"text":"}"},
  {"line":1095,"text":"func (f *isolatedDeclarationsFixer) finalizesVariablePart("},
  {"line":1096,"text":"\tfactory *ast.NodeFactory,"},
  {"line":1097,"text":"\tname string,"},
  {"line":1098,"text":"\tisInConstContext bool,"},
  {"line":1099,"text":"\tstatement *ast.Node,"},
  {"line":1100,"text":"\tmakeNodeOfKind func([]*ast.Node) *ast.Node,"},
  {"line":1101,"text":"\tcreateSpread func(*ast.Node) *ast.Node,"},
  {"line":1102,"text":"\tcurrentVariableProperties *[]*ast.Node,"},
  {"line":1103,"text":"\tintersectionTypes *[]*ast.TypeNode,"},
  {"line":1104,"text":"\tnewSpreads *[]*ast.Node,"},
  {"line":1105,"text":") {"},
  {"line":1106,"text":"\tif len(*currentVariableProperties) > 0 {"},
  {"line":1107,"text":"\t\tf.makeSpreadVariable(factory, name, isInConstContext, statement, createSpread, makeNodeOfKind(*currentVariableProperties), intersectionTypes, newSpreads)"},
  {"line":1108,"text":"\t\t*currentVariableProperties = nil"},
  {"line":1109,"text":"\t}"},
  {"line":1110,"text":"}"},
  {"line":1113,"text":"func isConstAssertion(node *ast.Node) bool {"},
  {"line":1114,"text":"\tif ast.IsAssertionExpression(node) {"},
  {"line":1115,"text":"\t\ttypeNode := node.Type()"},
  {"line":1116,"text":"\t\treturn ast.IsConstTypeReference(typeNode)"},
  {"line":1117,"text":"\t}"},
  {"line":1118,"text":"\treturn false"},
  {"line":1119,"text":"}"},
  {"line":1124,"text":"func (f *isolatedDeclarationsFixer) relativeType(node *ast.Node) *ast.TypeNode {"},
  {"line":1125,"text":"\tif ast.IsParameterDeclaration(node) {"},
  {"line":1126,"text":"\t\treturn nil"},
  {"line":1127,"text":"\t}"},
  {"line":1128,"text":"\tif ast.IsShorthandPropertyAssignment(node) {"},
  {"line":1129,"text":"\t\treturn f.createTypeOfFromEntityNameExpression(node.AsShorthandPropertyAssignment().Name())"},
  {"line":1130,"text":"\t}"},
  {"line":1131,"text":"\tif ast.IsEntityNameExpression(node) {"},
  {"line":1132,"text":"\t\treturn f.createTypeOfFromEntityNameExpression(node)"},
  {"line":1133,"text":"\t}"},
  {"line":1134,"text":"\tif isConstAssertion(node) {"},
  {"line":1135,"text":"\t\treturn f.relativeType(node.Expression())"},
  {"line":1136,"text":"\t}"},
  {"line":1137,"text":"\tif ast.IsArrayLiteralExpression(node) {"},
  {"line":1138,"text":"\t\tvarDecl := ast.FindAncestorKind(node, ast.KindVariableDeclaration)"},
  {"line":1139,"text":"\t\tpartName := \"\""},
  {"line":1140,"text":"\t\tif varDecl != nil && ast.IsIdentifier(varDecl.Name()) {"},
  {"line":1141,"text":"\t\t\tpartName = varDecl.Name().AsIdentifier().Text"},
  {"line":1142,"text":"\t\t}"},
  {"line":1143,"text":"\t\treturn f.typeFromArraySpreadElements(node.AsArrayLiteralExpression(), partName)"},
  {"line":1144,"text":"\t}"},
  {"line":1145,"text":"\tif ast.IsObjectLiteralExpression(node) {"},
  {"line":1146,"text":"\t\tvarDecl := ast.FindAncestorKind(node, ast.KindVariableDeclaration)"},
  {"line":1147,"text":"\t\tpartName := \"\""},
  {"line":1148,"text":"\t\tif varDecl != nil && ast.IsIdentifier(varDecl.Name()) {"},
  {"line":1149,"text":"\t\t\tpartName = varDecl.Name().AsIdentifier().Text"},
  {"line":1150,"text":"\t\t}"},
  {"line":1151,"text":"\t\treturn f.typeFromObjectSpreadAssignment(node.AsObjectLiteralExpression(), partName)"},
  {"line":1152,"text":"\t}"},
  {"line":1153,"text":"\tif ast.IsVariableDeclaration(node) && node.Initializer() != nil {"},
  {"line":1154,"text":"\t\treturn f.relativeType(node.Initializer())"},
  {"line":1155,"text":"\t}"},
  {"line":1156,"text":"\tif ast.IsConditionalExpression(node) {"},
  {"line":1157,"text":"\t\tcond := node.AsConditionalExpression()"},
  {"line":1158,"text":"\t\ttrueType := f.relativeType(cond.WhenTrue)"},
  {"line":1159,"text":"\t\tif trueType == nil {"},
  {"line":1160,"text":"\t\t\treturn nil"},
  {"line":1161,"text":"\t\t}"},
  {"line":1162,"text":"\t\ttrueMutated := f.mutatedTarget"},
  {"line":1163,"text":"\t\tfalseType := f.relativeType(cond.WhenFalse)"},
  {"line":1164,"text":"\t\tif falseType == nil {"},
  {"line":1165,"text":"\t\t\treturn nil"},
  {"line":1166,"text":"\t\t}"},
  {"line":1167,"text":"\t\tf.mutatedTarget = trueMutated || f.mutatedTarget"},
  {"line":1168,"text":"\t\tfactory := f.changeTracker.NodeFactory"},
  {"line":1169,"text":"\t\treturn factory.NewUnionTypeNode(factory.NewNodeList([]*ast.Node{trueType, falseType}))"},
  {"line":1170,"text":"\t}"},
  {"line":1171,"text":"\treturn nil"},
  {"line":1172,"text":"}"},
  {"line":1177,"text":"func (f *isolatedDeclarationsFixer) typeToMinimizedReferenceType(t *checker.Type, enclosingDecl *ast.Node, flags nodebuilder.Flags) *ast.TypeNode {"},
  {"line":1178,"text":"\tidToSymbol := make(map[*ast.IdentifierNode]*ast.Symbol)"},
  {"line":1181,"text":"\ttypeNode := f.checker.TypeToTypeNodeEx(t, enclosingDecl, flags, nodebuilder.InternalFlagsWriteComputedProps, idToSymbol)"},
  {"line":1182,"text":"\tif typeNode == nil {"},
  {"line":1183,"text":"\t\treturn nil"},
  {"line":1184,"text":"\t}"},
  {"line":1185,"text":"\tif ast.IsTypeReferenceNode(typeNode) && t.ObjectFlags()&checker.ObjectFlagsReference != 0 {"},
  {"line":1186,"text":"\t\ttypeArgs := f.checker.GetTypeArguments(t)"},
  {"line":1187,"text":"\t\tnodeTypeArgs := typeNode.TypeArguments()"},
  {"line":1188,"text":"\t\tif len(typeArgs) > 0 && len(nodeTypeArgs) > 0 {"},
  {"line":1189,"text":"\t\t\tcutoff := endOfRequiredTypeParameters(f.checker, t)"},
  {"line":1190,"text":"\t\t\tif cutoff < len(nodeTypeArgs) {"},
  {"line":1192,"text":"\t\t\t\ttrimmedArgs := f.changeTracker.NodeFactory.NewNodeList(nodeTypeArgs[:cutoff])"},
  {"line":1193,"text":"\t\t\t\ttypeNode = f.changeTracker.NodeFactory.UpdateTypeReferenceNode("},
  {"line":1194,"text":"\t\t\t\t\ttypeNode.AsTypeReferenceNode(),"},
  {"line":1195,"text":"\t\t\t\t\ttypeNode.AsTypeReferenceNode().TypeName,"},
  {"line":1196,"text":"\t\t\t\t\ttrimmedArgs,"},
  {"line":1197,"text":"\t\t\t\t)"},
  {"line":1198,"text":"\t\t\t}"},
  {"line":1199,"text":"\t\t}"},
  {"line":1200,"text":"\t}"},
  {"line":1203,"text":"\treferenceTypeNode, importableSymbols := autoimport.TryGetAutoImportableReferenceFromTypeNode(typeNode, idToSymbol)"},
  {"line":1204,"text":"\tif referenceTypeNode != nil {"},
  {"line":1205,"text":"\t\ttypeNode = referenceTypeNode"},
  {"line":1206,"text":"\t\tf.symbolsToImport = append(f.symbolsToImport, importableSymbols...)"},
  {"line":1207,"text":"\t}"},
  {"line":1208,"text":"\treturn typeNode"},
  {"line":1209,"text":"}"},
  {"line":1214,"text":"func endOfRequiredTypeParameters(ch *checker.Checker, t *checker.Type) int {"},
  {"line":1215,"text":"\ttypeArgs := ch.GetTypeArguments(t)"},
  {"line":1216,"text":"\tif len(typeArgs) == 0 {"},
  {"line":1217,"text":"\t\treturn 0"},
  {"line":1218,"text":"\t}"},
  {"line":1219,"text":"\ttarget := t.Target()"},
  {"line":1220,"text":"\tif target == nil || target.AsInterfaceType() == nil {"},
  {"line":1221,"text":"\t\treturn len(typeArgs)"},
  {"line":1222,"text":"\t}"},
  {"line":1223,"text":"\ttypeParams := target.AsInterfaceType().TypeParameters()"},
  {"line":1224,"text":"\tlocalTypeParams := target.AsInterfaceType().LocalTypeParameters()"},
  {"line":1225,"text":"\touterCount := len(typeParams) - len(localTypeParams)"},
  {"line":1226,"text":"\tfor cutoff := range typeArgs {"},
  {"line":1231,"text":"\t\tlocalIdx := cutoff - outerCount"},
  {"line":1232,"text":"\t\tif localIdx < 0 || localIdx >= len(localTypeParams) || !typeParamHasDefault(localTypeParams[localIdx]) {"},
  {"line":1233,"text":"\t\t\tcontinue"},
  {"line":1234,"text":"\t\t}"},
  {"line":1235,"text":"\t\tfilledIn := ch.FillMissingTypeArguments(typeArgs[:cutoff], typeParams, cutoff, false)"},
  {"line":1236,"text":"\t\tallMatch := true"},
  {"line":1237,"text":"\t\tfor i, fill := range filledIn {"},
  {"line":1238,"text":"\t\t\tif fill != typeArgs[i] {"},
  {"line":1239,"text":"\t\t\t\tallMatch = false"},
  {"line":1240,"text":"\t\t\t\tbreak"},
  {"line":1241,"text":"\t\t\t}"},
  {"line":1242,"text":"\t\t}"},
  {"line":1243,"text":"\t\tif allMatch {"},
  {"line":1244,"text":"\t\t\treturn cutoff"},
  {"line":1245,"text":"\t\t}"},
  {"line":1246,"text":"\t}"},
  {"line":1247,"text":"\treturn len(typeArgs)"},
  {"line":1248,"text":"}"},
  {"line":1251,"text":"func typeParamHasDefault(tp *checker.Type) bool {"},
  {"line":1252,"text":"\tsym := tp.Symbol()"},
  {"line":1253,"text":"\tif sym == nil {"},
  {"line":1254,"text":"\t\treturn false"},
  {"line":1255,"text":"\t}"},
  {"line":1256,"text":"\tfor _, decl := range sym.Declarations {"},
  {"line":1257,"text":"\t\tif ast.IsTypeParameterDeclaration(decl) && decl.AsTypeParameterDeclaration().DefaultType != nil {"},
  {"line":1258,"text":"\t\t\treturn true"},
  {"line":1259,"text":"\t\t}"},
  {"line":1260,"text":"\t}"},
  {"line":1261,"text":"\treturn false"},
  {"line":1262,"text":"}"},
  {"line":1264,"text":"func (f *isolatedDeclarationsFixer) addTypeToVariableLike(decl *ast.Node) string {"},
  {"line":1265,"text":"\ttypeNode := f.inferType(decl, nil)"},
  {"line":1266,"text":"\tif typeNode == nil {"},
  {"line":1267,"text":"\t\treturn \"\""},
  {"line":1268,"text":"\t}"},
  {"line":1269,"text":"\tif decl.Type() != nil {"},
  {"line":1270,"text":"\t\tf.changeTracker.ReplaceNode(f.sourceFile, decl.Type(), typeNode, nil)"},
  {"line":1271,"text":"\t} else {"},
  {"line":1272,"text":"\t\tf.changeTracker.TryInsertTypeAnnotation(f.sourceFile, decl, typeNode)"},
  {"line":1276,"text":"\t\tif ast.IsParameterDeclaration(decl) && decl.Parent != nil && ast.IsArrowFunction(decl.Parent) {"},
  {"line":1277,"text":"\t\t\tf.changeTracker.ParenthesizeArrowParameters(f.sourceFile, decl.Parent)"},
  {"line":1278,"text":"\t\t}"},
  {"line":1279,"text":"\t}"},
  {"line":1280,"text":"\treturn diagnostics.Add_annotation_of_type_0.Localize(f.locale, typeToStringForDiag(typeNode, f.sourceFile, f.changeTracker))"},
  {"line":1281,"text":"}"},
  {"line":1287,"text":"func typeToStringForDiag(typeNode *ast.Node, sourceFile *ast.SourceFile, ct *change.Tracker) string {"},
  {"line":1288,"text":"\tsavedFlags := ct.EmitContext.EmitFlags(typeNode)"},
  {"line":1289,"text":"\tct.EmitContext.SetEmitFlags(typeNode, savedFlags|printer.EFSingleLine)"},
  {"line":1290,"text":"\tp := printer.NewPrinter("},
  {"line":1291,"text":"\t\tprinter.PrinterOptions{"},
  {"line":1292,"text":"\t\t\tNewLine: core.NewLineKindLF,"},
  {"line":1293,"text":"\t\t},"},
  {"line":1294,"text":"\t\tprinter.PrintHandlers{},"},
  {"line":1295,"text":"\t\tct.EmitContext,"},
  {"line":1296,"text":"\t)"},
  {"line":1297,"text":"\twriter, release := printer.GetSingleLineStringWriter()"},
  {"line":1298,"text":"\tdefer release()"},
  {"line":1299,"text":"\tp.Write(typeNode, sourceFile, writer, nil)"},
  {"line":1300,"text":"\tct.EmitContext.SetEmitFlags(typeNode, savedFlags)"},
  {"line":1301,"text":"\tresult := writer.String()"},
  {"line":1302,"text":"\tif len(result) > 160 {"},
  {"line":1303,"text":"\t\treturn result[:157] + \"...\""},
  {"line":1304,"text":"\t}"},
  {"line":1305,"text":"\treturn result"},
  {"line":1306,"text":"}"},
  {"line":1310,"text":"func findAncestorWithMissingType(node *ast.Node) *ast.Node {"},
  {"line":1311,"text":"\treturn ast.FindAncestor(node, func(n *ast.Node) bool {"},
  {"line":1312,"text":"\t\tif !canHaveTypeAnnotationKinds[n.Kind] {"},
  {"line":1313,"text":"\t\t\treturn false"},
  {"line":1314,"text":"\t\t}"},
  {"line":1315,"text":"\t\tif ast.IsObjectBindingPattern(n) || ast.IsArrayBindingPattern(n) {"},
  {"line":1316,"text":"\t\t\treturn ast.IsVariableDeclaration(n.Parent)"},
  {"line":1317,"text":"\t\t}"},
  {"line":1318,"text":"\t\treturn true"},
  {"line":1319,"text":"\t})"},
  {"line":1320,"text":"}"},
  {"line":1323,"text":"func findBestFittingNode(node *ast.Node, span core.TextRange) *ast.Node {"},
  {"line":1324,"text":"\tif node == nil {"},
  {"line":1325,"text":"\t\treturn nil"},
  {"line":1326,"text":"\t}"},
  {"line":1327,"text":"\tfor node != nil && node.End() < span.Pos()+span.Len() {"},
  {"line":1328,"text":"\t\tnode = node.Parent"},
  {"line":1329,"text":"\t}"},
  {"line":1330,"text":"\tfor node.Parent != nil && node.Parent.Pos() == node.Pos() && node.Parent.End() == node.End() {"},
  {"line":1331,"text":"\t\tnode = node.Parent"},
  {"line":1332,"text":"\t}"},
  {"line":1333,"text":"\tif ast.IsIdentifier(node) && ast.HasInitializer(node.Parent) && node.Parent.Initializer() != nil {"},
  {"line":1334,"text":"\t\treturn node.Parent.Initializer()"},
  {"line":1335,"text":"\t}"},
  {"line":1336,"text":"\tif ast.IsIdentifier(node) && ast.IsShorthandPropertyAssignment(node.Parent) {"},
  {"line":1337,"text":"\t\treturn node.Parent"},
  {"line":1338,"text":"\t}"},
  {"line":1339,"text":"\treturn node"},
  {"line":1340,"text":"}"},
  {"line":1345,"text":"func isNamedDeclarationKind(node *ast.Node) bool {"},
  {"line":1346,"text":"\tswitch node.Kind {"},
  {"line":1347,"text":"\tcase ast.KindArrowFunction, ast.KindBindingElement, ast.KindClassDeclaration, ast.KindClassExpression,"},
  {"line":1348,"text":"\t\tast.KindClassStaticBlockDeclaration, ast.KindConstructor, ast.KindEnumDeclaration, ast.KindEnumMember,"},
  {"line":1349,"text":"\t\tast.KindExportSpecifier, ast.KindFunctionDeclaration, ast.KindFunctionExpression,"},
  {"line":1350,"text":"\t\tast.KindGetAccessor, ast.KindImportClause, ast.KindImportEqualsDeclaration,"},
  {"line":1351,"text":"\t\tast.KindImportSpecifier, ast.KindInterfaceDeclaration, ast.KindJsxAttribute,"},
  {"line":1352,"text":"\t\tast.KindMethodDeclaration, ast.KindMethodSignature, ast.KindModuleDeclaration,"},
  {"line":1353,"text":"\t\tast.KindNamespaceExportDeclaration, ast.KindNamespaceImport, ast.KindNamespaceExport,"},
  {"line":1354,"text":"\t\tast.KindParameter, ast.KindPropertyAssignment, ast.KindPropertyDeclaration,"},
  {"line":1355,"text":"\t\tast.KindPropertySignature, ast.KindSetAccessor, ast.KindShorthandPropertyAssignment,"},
  {"line":1356,"text":"\t\tast.KindTypeAliasDeclaration, ast.KindTypeParameter, ast.KindVariableDeclaration,"},
  {"line":1357,"text":"\t\tast.KindJSDocTypedefTag, ast.KindJSDocCallbackTag, ast.KindJSDocPropertyTag,"},
  {"line":1358,"text":"\t\tast.KindNamedTupleMember:"},
  {"line":1359,"text":"\t\treturn true"},
  {"line":1360,"text":"\t}"},
  {"line":1361,"text":"\treturn false"},
  {"line":1362,"text":"}"},
  {"line":1365,"text":"func isValueSignatureDeclaration(node *ast.Node) bool {"},
  {"line":1366,"text":"\treturn ast.IsFunctionExpression(node) || ast.IsArrowFunction(node) || ast.IsMethodDeclaration(node) ||"},
  {"line":1367,"text":"\t\tast.IsAccessor(node) || ast.IsFunctionDeclaration(node) || ast.IsConstructorDeclaration(node)"},
  {"line":1368,"text":"}"},
  {"line":1373,"text":"func getIdentifierNameForNode(node *ast.Node) string {"},
  {"line":1374,"text":"\tif ast.IsPropertyAccessExpression(node) {"},
  {"line":1375,"text":"\t\tname := node.AsPropertyAccessExpression().Name()"},
  {"line":1376,"text":"\t\tif ast.IsIdentifier(name) && !ast.IsPrivateIdentifier(name) && scanner.IdentifierToKeywordKind(name.AsIdentifier()) == ast.KindUnknown {"},
  {"line":1377,"text":"\t\t\treturn name.Text()"},
  {"line":1378,"text":"\t\t}"},
  {"line":1379,"text":"\t}"},
  {"line":1380,"text":"\treturn \"newLocal\""},
  {"line":1381,"text":"}"},
  {"line":1385,"text":"func (f *isolatedDeclarationsFixer) addSymbolToExistingImport(sym *ast.Symbol) {"},
  {"line":1386,"text":"\tif sym == nil || sym.Parent == nil {"},
  {"line":1387,"text":"\t\treturn"},
  {"line":1388,"text":"\t}"},
  {"line":1391,"text":"\tmoduleSymbol := sym.Parent"},
  {"line":1392,"text":"\tsymbolName := sym.Name"},
  {"line":1395,"text":"\tfor _, stmt := range f.sourceFile.Statements.Nodes {"},
  {"line":1396,"text":"\t\tif !ast.IsImportDeclaration(stmt) {"},
  {"line":1397,"text":"\t\t\tcontinue"},
  {"line":1398,"text":"\t\t}"},
  {"line":1399,"text":"\t\timportDecl := stmt.AsImportDeclaration()"},
  {"line":1400,"text":"\t\tif importDecl.ImportClause == nil {"},
  {"line":1401,"text":"\t\t\tcontinue"},
  {"line":1402,"text":"\t\t}"},
  {"line":1405,"text":"\t\timportModuleSymbol := f.checker.GetSymbolAtLocation(importDecl.ModuleSpecifier)"},
  {"line":1406,"text":"\t\tif importModuleSymbol == nil || f.checker.GetMergedSymbol(importModuleSymbol) != f.checker.GetMergedSymbol(moduleSymbol) {"},
  {"line":1407,"text":"\t\t\tcontinue"},
  {"line":1408,"text":"\t\t}"},
  {"line":1411,"text":"\t\timportClause := importDecl.ImportClause.AsImportClause()"},
  {"line":1412,"text":"\t\tif importClause.NamedBindings != nil && ast.IsNamedImports(importClause.NamedBindings) {"},
  {"line":1414,"text":"\t\t\texistingElements := importClause.NamedBindings.AsNamedImports().Elements.Nodes"},
  {"line":1415,"text":"\t\t\tfactory := f.changeTracker.NodeFactory"},
  {"line":1416,"text":"\t\t\tnewSpecifier := factory.NewImportSpecifier(false, nil, factory.NewIdentifier(symbolName))"},
  {"line":1417,"text":"\t\t\tnewElements := append(existingElements, newSpecifier.AsNode())"},
  {"line":1418,"text":"\t\t\tnewNamedImports := factory.NewNamedImports(factory.NewNodeList(newElements))"},
  {"line":1419,"text":"\t\t\tnewImportClause := factory.UpdateImportClause(importClause, importClause.PhaseModifier, importClause.Name(), newNamedImports)"},
  {"line":1420,"text":"\t\t\tnewImportDecl := factory.UpdateImportDeclaration(importDecl, importDecl.Modifiers(), newImportClause, importDecl.ModuleSpecifier, importDecl.Attributes)"},
  {"line":1421,"text":"\t\t\tf.changeTracker.ReplaceNode(f.sourceFile, stmt, newImportDecl.AsNode(), nil)"},
  {"line":1422,"text":"\t\t}"},
  {"line":1423,"text":"\t\treturn"},
  {"line":1424,"text":"\t}"},
  {"line":1425,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsCodeActionsFixMissingTypeAnnotationSourceLines.find((entry) => entry.line === line)?.text;
}
