/**
 * Language-service parity map for TS-Go `ls/codeactions_fixclassincorrectlyimplementsinterface.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const lsCodeActionsFixClassIncorrectlyImplementsInterfaceUpstreamPath = "ls/codeactions_fixclassincorrectlyimplementsinterface.go";

export const lsCodeActionsFixClassIncorrectlyImplementsInterfaceDeclarations: readonly UpstreamDeclaration[] = [
  {"line":19,"kind":"const","name":"fixClassIncorrectlyImplementsInterfaceFixID"},
  {"line":21,"kind":"var","name":"fixClassIncorrectlyImplementsInterfaceErrorCodes"},
  {"line":26,"kind":"var","name":"FixClassIncorrectlyImplementsInterfaceProvider"},
  {"line":33,"kind":"func","name":"getCodeActionsToFixClassIncorrectlyImplementsInterface"},
  {"line":69,"kind":"func","name":"getAllCodeActionsToFixClassIncorrectlyImplementsInterface"},
  {"line":107,"kind":"func","name":"addChanges"},
  {"line":136,"kind":"func","name":"getChanges"},
  {"line":144,"kind":"func","name":"insertInterfaceMemberNode"},
  {"line":152,"kind":"func","name":"getClass"},
  {"line":160,"kind":"func","name":"getConstructor"},
  {"line":172,"kind":"func","name":"getMissingMembers"},
  {"line":203,"kind":"func","name":"getInheritedMembers"},
  {"line":227,"kind":"func","name":"createImportAdder"},
];

export const lsCodeActionsFixClassIncorrectlyImplementsInterfaceSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/locale\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/autoimport\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/change\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":17,"text":")"},
  {"line":19,"text":"const fixClassIncorrectlyImplementsInterfaceFixID = \"fixClassIncorrectlyImplementsInterface\""},
  {"line":21,"text":"var fixClassIncorrectlyImplementsInterfaceErrorCodes = []int32{"},
  {"line":22,"text":"\tdiagnostics.Class_0_incorrectly_implements_interface_1.Code(),"},
  {"line":23,"text":"\tdiagnostics.Class_0_incorrectly_implements_class_1_Did_you_mean_to_extend_1_and_inherit_its_members_as_a_subclass.Code(),"},
  {"line":24,"text":"}"},
  {"line":26,"text":"var FixClassIncorrectlyImplementsInterfaceProvider = &CodeFixProvider{"},
  {"line":27,"text":"\tErrorCodes:        fixClassIncorrectlyImplementsInterfaceErrorCodes,"},
  {"line":28,"text":"\tGetCodeActions:    getCodeActionsToFixClassIncorrectlyImplementsInterface,"},
  {"line":29,"text":"\tFixIds:            []string{fixClassIncorrectlyImplementsInterfaceFixID},"},
  {"line":30,"text":"\tGetAllCodeActions: getAllCodeActionsToFixClassIncorrectlyImplementsInterface,"},
  {"line":31,"text":"}"},
  {"line":33,"text":"func getCodeActionsToFixClassIncorrectlyImplementsInterface(context context.Context, fixContext *CodeFixContext) ([]*CodeAction, error) {"},
  {"line":34,"text":"\tclassDeclaration := getClass(fixContext.SourceFile, fixContext.Span)"},
  {"line":35,"text":"\tif classDeclaration == nil {"},
  {"line":36,"text":"\t\treturn nil, nil"},
  {"line":37,"text":"\t}"},
  {"line":39,"text":"\timplementsTypes := ast.GetImplementsTypeNodes(classDeclaration)"},
  {"line":40,"text":"\tlocale := locale.FromContext(context)"},
  {"line":42,"text":"\ttypeChecker, done := fixContext.Program.GetTypeCheckerForFile(context, fixContext.SourceFile)"},
  {"line":43,"text":"\tdefer done()"},
  {"line":45,"text":"\tvar actions []*CodeAction"},
  {"line":46,"text":"\tfor _, implementedTypeNode := range implementsTypes {"},
  {"line":47,"text":"\t\tchangeTracker := change.NewTracker(context, fixContext.Program.Options(), fixContext.LS.FormatOptions(), fixContext.LS.converters)"},
  {"line":48,"text":"\t\timportAdder, err := createImportAdder(context, fixContext, typeChecker)"},
  {"line":49,"text":"\t\tif err != nil {"},
  {"line":50,"text":"\t\t\treturn nil, err"},
  {"line":51,"text":"\t\t}"},
  {"line":53,"text":"\t\taddChanges(context, fixContext, changeTracker, importAdder, typeChecker, classDeclaration, implementedTypeNode)"},
  {"line":54,"text":"\t\tchanges := getChanges(changeTracker, importAdder, fixContext.SourceFile)"},
  {"line":55,"text":"\t\tif len(changes) == 0 {"},
  {"line":56,"text":"\t\t\tcontinue"},
  {"line":57,"text":"\t\t}"},
  {"line":59,"text":"\t\tactions = append(actions, &CodeAction{"},
  {"line":60,"text":"\t\t\tDescription:       diagnostics.Implement_interface_0.Localize(locale, scanner.GetTextOfNode(implementedTypeNode)),"},
  {"line":61,"text":"\t\t\tChanges:           changes,"},
  {"line":62,"text":"\t\t\tFixID:             fixClassIncorrectlyImplementsInterfaceFixID,"},
  {"line":63,"text":"\t\t\tFixAllDescription: diagnostics.Implement_all_unimplemented_interfaces.Localize(locale),"},
  {"line":64,"text":"\t\t})"},
  {"line":65,"text":"\t}"},
  {"line":66,"text":"\treturn actions, nil"},
  {"line":67,"text":"}"},
  {"line":69,"text":"func getAllCodeActionsToFixClassIncorrectlyImplementsInterface(context context.Context, fixContext *CodeFixContext) (*CombinedCodeActions, error) {"},
  {"line":70,"text":"\ttypeChecker, done := fixContext.Program.GetTypeCheckerForFile(context, fixContext.SourceFile)"},
  {"line":71,"text":"\tdefer done()"},
  {"line":73,"text":"\tchangeTracker := change.NewTracker(context, fixContext.Program.Options(), fixContext.LS.FormatOptions(), fixContext.LS.converters)"},
  {"line":74,"text":"\timportAdder, err := createImportAdder(context, fixContext, typeChecker)"},
  {"line":75,"text":"\tif err != nil {"},
  {"line":76,"text":"\t\treturn nil, err"},
  {"line":77,"text":"\t}"},
  {"line":79,"text":"\tseenClassDeclarations := collections.Set[*ast.Node]{}"},
  {"line":81,"text":"\tfor _, diag := range getAllDiagnostics(context, fixContext.Program, fixContext.SourceFile) {"},
  {"line":82,"text":"\t\tif containsErrorCode(fixClassIncorrectlyImplementsInterfaceErrorCodes, diag.Code()) {"},
  {"line":83,"text":"\t\t\tclassDeclaration := getClass(fixContext.SourceFile, core.NewTextRange(diag.Pos(), diag.End()))"},
  {"line":84,"text":"\t\t\tif classDeclaration == nil {"},
  {"line":85,"text":"\t\t\t\tcontinue"},
  {"line":86,"text":"\t\t\t}"},
  {"line":87,"text":"\t\t\tif seenClassDeclarations.AddIfAbsent(classDeclaration) {"},
  {"line":88,"text":"\t\t\t\timplementsTypes := ast.GetImplementsTypeNodes(classDeclaration)"},
  {"line":89,"text":"\t\t\t\tfor _, implementedTypeNode := range implementsTypes {"},
  {"line":90,"text":"\t\t\t\t\taddChanges(context, fixContext, changeTracker, importAdder, typeChecker, classDeclaration, implementedTypeNode)"},
  {"line":91,"text":"\t\t\t\t}"},
  {"line":92,"text":"\t\t\t}"},
  {"line":93,"text":"\t\t}"},
  {"line":94,"text":"\t}"},
  {"line":96,"text":"\tchanges := getChanges(changeTracker, importAdder, fixContext.SourceFile)"},
  {"line":97,"text":"\tif len(changes) == 0 {"},
  {"line":98,"text":"\t\treturn nil, nil"},
  {"line":99,"text":"\t}"},
  {"line":101,"text":"\treturn &CombinedCodeActions{"},
  {"line":102,"text":"\t\tDescription: diagnostics.Implement_all_unimplemented_interfaces.Localize(locale.FromContext(context)),"},
  {"line":103,"text":"\t\tChanges:     changes,"},
  {"line":104,"text":"\t}, nil"},
  {"line":105,"text":"}"},
  {"line":107,"text":"func addChanges(context context.Context, fixContext *CodeFixContext, changeTracker *change.Tracker, importAdder autoimport.ImportAdder, typeChecker *checker.Checker, classDeclaration *ast.Node, implementedTypeNode *ast.Node) {"},
  {"line":108,"text":"\tmissingMemberFixer := newMissingMemberFixer(changeTracker, fixContext.Program, typeChecker, fixContext.LS.UserPreferences(), importAdder, locale.FromContext(context))"},
  {"line":109,"text":"\tconstructor := getConstructor(classDeclaration)"},
  {"line":110,"text":"\timplementedType := typeChecker.GetTypeAtLocation(implementedTypeNode)"},
  {"line":111,"text":"\tclassType := typeChecker.GetTypeAtLocation(classDeclaration)"},
  {"line":113,"text":"\tif typeChecker.GetNumberIndexType(classType) == nil {"},
  {"line":114,"text":"\t\tmember := missingMemberFixer.createIndexSignatureDeclarationFromType(classDeclaration, implementedType, typeChecker.GetNumberType())"},
  {"line":115,"text":"\t\tif member != nil {"},
  {"line":116,"text":"\t\t\tinsertInterfaceMemberNode(changeTracker, fixContext.SourceFile, classDeclaration, constructor, member)"},
  {"line":117,"text":"\t\t}"},
  {"line":118,"text":"\t}"},
  {"line":120,"text":"\tif typeChecker.GetStringIndexType(classType) == nil {"},
  {"line":121,"text":"\t\tmember := missingMemberFixer.createIndexSignatureDeclarationFromType(classDeclaration, implementedType, typeChecker.GetStringType())"},
  {"line":122,"text":"\t\tif member != nil {"},
  {"line":123,"text":"\t\t\tinsertInterfaceMemberNode(changeTracker, fixContext.SourceFile, classDeclaration, constructor, member)"},
  {"line":124,"text":"\t\t}"},
  {"line":125,"text":"\t}"},
  {"line":127,"text":"\tmissingMembers := getMissingMembers(typeChecker, classDeclaration, []*checker.Type{implementedType})"},
  {"line":128,"text":"\tfor _, member := range missingMembers {"},
  {"line":129,"text":"\t\tmemberNodes := missingMemberFixer.createMemberFromSymbol(member, classDeclaration, fixContext.SourceFile, nil /*body*/, preserveOptionalFlagsAll)"},
  {"line":130,"text":"\t\tfor _, memberNode := range memberNodes {"},
  {"line":131,"text":"\t\t\tinsertInterfaceMemberNode(changeTracker, fixContext.SourceFile, classDeclaration, constructor, memberNode)"},
  {"line":132,"text":"\t\t}"},
  {"line":133,"text":"\t}"},
  {"line":134,"text":"}"},
  {"line":136,"text":"func getChanges(changeTracker *change.Tracker, importAdder autoimport.ImportAdder, sourceFile *ast.SourceFile) []*lsproto.TextEdit {"},
  {"line":137,"text":"\tfileChanges := changeTracker.GetChanges()[sourceFile.FileName()]"},
  {"line":138,"text":"\tif importAdder != nil && importAdder.HasFixes() {"},
  {"line":139,"text":"\t\tfileChanges = append(fileChanges, importAdder.Edits()...)"},
  {"line":140,"text":"\t}"},
  {"line":141,"text":"\treturn fileChanges"},
  {"line":142,"text":"}"},
  {"line":144,"text":"func insertInterfaceMemberNode(changeTracker *change.Tracker, sourceFile *ast.SourceFile, classDeclaration *ast.Node, constructor *ast.Node, member *ast.Node) {"},
  {"line":145,"text":"\tif constructor == nil {"},
  {"line":146,"text":"\t\tchangeTracker.InsertMemberAtStart(sourceFile, classDeclaration, member)"},
  {"line":147,"text":"\t} else {"},
  {"line":148,"text":"\t\tchangeTracker.InsertNodeAfter(sourceFile, constructor, member)"},
  {"line":149,"text":"\t}"},
  {"line":150,"text":"}"},
  {"line":152,"text":"func getClass(sourceFile *ast.SourceFile, span core.TextRange) *ast.Node {"},
  {"line":153,"text":"\ttoken := astnav.GetTokenAtPosition(sourceFile, span.Pos())"},
  {"line":154,"text":"\tif token == nil {"},
  {"line":155,"text":"\t\treturn nil"},
  {"line":156,"text":"\t}"},
  {"line":157,"text":"\treturn ast.GetContainingClass(token)"},
  {"line":158,"text":"}"},
  {"line":160,"text":"func getConstructor(classDeclaration *ast.Node) *ast.Node {"},
  {"line":161,"text":"\tif classDeclaration == nil || classDeclaration.MemberList() == nil {"},
  {"line":162,"text":"\t\treturn nil"},
  {"line":163,"text":"\t}"},
  {"line":164,"text":"\tfor _, member := range classDeclaration.MemberList().Nodes {"},
  {"line":165,"text":"\t\tif member != nil && ast.IsConstructorDeclaration(member) {"},
  {"line":166,"text":"\t\t\treturn member"},
  {"line":167,"text":"\t\t}"},
  {"line":168,"text":"\t}"},
  {"line":169,"text":"\treturn nil"},
  {"line":170,"text":"}"},
  {"line":172,"text":"func getMissingMembers(typeChecker *checker.Checker, classDeclaration *ast.Node, implementedTypes []*checker.Type) []*ast.Symbol {"},
  {"line":173,"text":"\tinheritedMembers := getInheritedMembers(typeChecker, classDeclaration)"},
  {"line":174,"text":"\tseenMembers := make(map[string]*ast.Symbol)"},
  {"line":176,"text":"\tvar classMembers ast.SymbolTable"},
  {"line":177,"text":"\tif classDeclaration.Symbol() != nil {"},
  {"line":178,"text":"\t\tclassMembers = classDeclaration.Symbol().Members"},
  {"line":179,"text":"\t}"},
  {"line":181,"text":"\tvar missingMembers []*ast.Symbol"},
  {"line":182,"text":"\tfor _, implementedType := range implementedTypes {"},
  {"line":183,"text":"\t\tfor _, symbol := range typeChecker.GetPropertiesOfType(implementedType) {"},
  {"line":184,"text":"\t\t\tif symbol == nil {"},
  {"line":185,"text":"\t\t\t\tcontinue"},
  {"line":186,"text":"\t\t\t}"},
  {"line":187,"text":"\t\t\tif classMembers != nil && classMembers[symbol.Name] != nil {"},
  {"line":188,"text":"\t\t\t\tcontinue"},
  {"line":189,"text":"\t\t\t}"},
  {"line":190,"text":"\t\t\tif inheritedMembers[symbol.Name] != nil || seenMembers[symbol.Name] != nil {"},
  {"line":191,"text":"\t\t\t\tcontinue"},
  {"line":192,"text":"\t\t\t}"},
  {"line":193,"text":"\t\t\tflags := checker.GetDeclarationModifierFlagsFromSymbol(symbol)"},
  {"line":194,"text":"\t\t\tif flags&ast.ModifierFlagsPrivate == 0 {"},
  {"line":195,"text":"\t\t\t\tseenMembers[symbol.Name] = symbol"},
  {"line":196,"text":"\t\t\t\tmissingMembers = append(missingMembers, symbol)"},
  {"line":197,"text":"\t\t\t}"},
  {"line":198,"text":"\t\t}"},
  {"line":199,"text":"\t}"},
  {"line":200,"text":"\treturn missingMembers"},
  {"line":201,"text":"}"},
  {"line":203,"text":"func getInheritedMembers(typeChecker *checker.Checker, classDeclaration *ast.Node) ast.SymbolTable {"},
  {"line":204,"text":"\ttypeNode := ast.GetClassExtendsHeritageElement(classDeclaration)"},
  {"line":205,"text":"\tif typeNode == nil {"},
  {"line":206,"text":"\t\treturn ast.SymbolTable{}"},
  {"line":207,"text":"\t}"},
  {"line":209,"text":"\tbaseType := typeChecker.GetTypeAtLocation(typeNode.AsNode())"},
  {"line":210,"text":"\tif baseType == nil {"},
  {"line":211,"text":"\t\treturn ast.SymbolTable{}"},
  {"line":212,"text":"\t}"},
  {"line":214,"text":"\tinheritedMembers := make(ast.SymbolTable)"},
  {"line":215,"text":"\tfor _, symbol := range typeChecker.GetPropertiesOfType(baseType) {"},
  {"line":216,"text":"\t\tif symbol == nil {"},
  {"line":217,"text":"\t\t\tcontinue"},
  {"line":218,"text":"\t\t}"},
  {"line":219,"text":"\t\tflags := checker.GetDeclarationModifierFlagsFromSymbol(symbol)"},
  {"line":220,"text":"\t\tif flags&ast.ModifierFlagsPrivate == 0 {"},
  {"line":221,"text":"\t\t\tinheritedMembers[symbol.Name] = symbol"},
  {"line":222,"text":"\t\t}"},
  {"line":223,"text":"\t}"},
  {"line":224,"text":"\treturn inheritedMembers"},
  {"line":225,"text":"}"},
  {"line":227,"text":"func createImportAdder(context context.Context, fixContext *CodeFixContext, typeChecker *checker.Checker) (autoimport.ImportAdder, error) {"},
  {"line":228,"text":"\tview, err := fixContext.LS.getPreparedAutoImportView(fixContext.SourceFile)"},
  {"line":229,"text":"\tif err != nil {"},
  {"line":230,"text":"\t\treturn nil, err"},
  {"line":231,"text":"\t}"},
  {"line":232,"text":"\tif view == nil {"},
  {"line":233,"text":"\t\treturn nil, nil"},
  {"line":234,"text":"\t}"},
  {"line":235,"text":"\treturn autoimport.NewImportAdder(context, fixContext.Program, typeChecker, fixContext.SourceFile, view, fixContext.LS.FormatOptions(), fixContext.LS.converters, fixContext.LS.UserPreferences()), nil"},
  {"line":236,"text":"}"},
];

export function findLsCodeActionsFixClassIncorrectlyImplementsInterfaceDeclaration(name: string): UpstreamDeclaration | undefined {
  return lsCodeActionsFixClassIncorrectlyImplementsInterfaceDeclarations.find((declaration) => declaration.name === name);
}

export function requireLsCodeActionsFixClassIncorrectlyImplementsInterfaceDeclaration(name: string): UpstreamDeclaration {
  const declaration = findLsCodeActionsFixClassIncorrectlyImplementsInterfaceDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function lsCodeActionsFixClassIncorrectlyImplementsInterfaceLineText(line: number): string | undefined {
  return lsCodeActionsFixClassIncorrectlyImplementsInterfaceSourceLines.find((entry) => entry.line === line)?.text;
}
