/**
 * Language-service parity map for TS-Go `ls/displaypartswriter.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const lsDisplayPartsWriterUpstreamPath = "ls/displaypartswriter.go";

export const lsDisplayPartsWriterDeclarations: readonly UpstreamDeclaration[] = [
  {"line":14,"kind":"var","name":"_"},
  {"line":19,"kind":"type","name":"displayPartsWriter"},
  {"line":26,"kind":"func","name":"newDisplayPartsWriter"},
  {"line":30,"kind":"func","name":"addRun","receiver":"w *displayPartsWriter"},
  {"line":45,"kind":"func","name":"WriteClassified","receiver":"w *displayPartsWriter"},
  {"line":50,"kind":"func","name":"WriteFrom","receiver":"w *displayPartsWriter"},
  {"line":60,"kind":"func","name":"GetRuns","receiver":"w *displayPartsWriter"},
  {"line":64,"kind":"func","name":"String","receiver":"w *displayPartsWriter"},
  {"line":68,"kind":"func","name":"Clear","receiver":"w *displayPartsWriter"},
  {"line":74,"kind":"func","name":"DecreaseIndent","receiver":"w displayPartsWriter"},
  {"line":76,"kind":"func","name":"GetColumn","receiver":"w displayPartsWriter"},
  {"line":78,"kind":"func","name":"GetIndent","receiver":"w displayPartsWriter"},
  {"line":80,"kind":"func","name":"GetLine","receiver":"w displayPartsWriter"},
  {"line":82,"kind":"func","name":"GetTextPos","receiver":"w displayPartsWriter"},
  {"line":86,"kind":"func","name":"HasTrailingComment","receiver":"w displayPartsWriter"},
  {"line":88,"kind":"func","name":"HasTrailingWhitespace","receiver":"w displayPartsWriter"},
  {"line":99,"kind":"func","name":"IncreaseIndent","receiver":"w displayPartsWriter"},
  {"line":101,"kind":"func","name":"IsAtStartOfLine","receiver":"w displayPartsWriter"},
  {"line":103,"kind":"func","name":"RawWrite","receiver":"w *displayPartsWriter"},
  {"line":107,"kind":"func","name":"Write","receiver":"w *displayPartsWriter"},
  {"line":111,"kind":"func","name":"WriteComment","receiver":"w *displayPartsWriter"},
  {"line":116,"kind":"func","name":"WriteKeyword","receiver":"w *displayPartsWriter"},
  {"line":120,"kind":"func","name":"WriteLine","receiver":"w *displayPartsWriter"},
  {"line":124,"kind":"func","name":"WriteLineForce","receiver":"w *displayPartsWriter"},
  {"line":128,"kind":"func","name":"WriteLiteral","receiver":"w *displayPartsWriter"},
  {"line":133,"kind":"func","name":"WriteOperator","receiver":"w *displayPartsWriter"},
  {"line":137,"kind":"func","name":"WriteParameter","receiver":"w *displayPartsWriter"},
  {"line":141,"kind":"func","name":"WriteProperty","receiver":"w *displayPartsWriter"},
  {"line":145,"kind":"func","name":"WritePunctuation","receiver":"w *displayPartsWriter"},
  {"line":149,"kind":"func","name":"WriteSpace","receiver":"w *displayPartsWriter"},
  {"line":153,"kind":"func","name":"WriteStringLiteral","receiver":"w *displayPartsWriter"},
  {"line":157,"kind":"func","name":"WriteSymbol","receiver":"w *displayPartsWriter"},
  {"line":162,"kind":"func","name":"WriteTrailingSemicolon","receiver":"w *displayPartsWriter"},
  {"line":168,"kind":"func","name":"classificationForSymbol"},
  {"line":211,"kind":"func","name":"isFirstDeclarationOfSymbolParameter"},
];

export const lsDisplayPartsWriterSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"strings\""},
  {"line":5,"text":"\t\"unicode/utf8\""},
  {"line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"line":12,"text":")"},
  {"line":14,"text":"var _ printer.EmitTextWriter = &displayPartsWriter{}"},
  {"line":19,"text":"type displayPartsWriter struct {"},
  {"line":20,"text":"\tbuilder      strings.Builder"},
  {"line":21,"text":"\truns         []*lsproto.ClassifiedTextRun"},
  {"line":22,"text":"\tvsCapability bool"},
  {"line":23,"text":"\tlastWritten  string"},
  {"line":24,"text":"}"},
  {"line":26,"text":"func newDisplayPartsWriter(vsCapability bool) *displayPartsWriter {"},
  {"line":27,"text":"\treturn &displayPartsWriter{vsCapability: vsCapability}"},
  {"line":28,"text":"}"},
  {"line":30,"text":"func (w *displayPartsWriter) addRun(classification lsproto.ClassificationTypeName, text string) {"},
  {"line":31,"text":"\tif text == \"\" {"},
  {"line":32,"text":"\t\treturn"},
  {"line":33,"text":"\t}"},
  {"line":34,"text":"\tif w.vsCapability {"},
  {"line":35,"text":"\t\tw.runs = append(w.runs, &lsproto.ClassifiedTextRun{"},
  {"line":36,"text":"\t\t\tClassificationTypeName: string(classification),"},
  {"line":37,"text":"\t\t\tText:                   text,"},
  {"line":38,"text":"\t\t})"},
  {"line":39,"text":"\t}"},
  {"line":40,"text":"\tw.lastWritten = text"},
  {"line":41,"text":"\tw.builder.WriteString(text)"},
  {"line":42,"text":"}"},
  {"line":45,"text":"func (w *displayPartsWriter) WriteClassified(text string, classification lsproto.ClassificationTypeName) {"},
  {"line":46,"text":"\tw.addRun(classification, text)"},
  {"line":47,"text":"}"},
  {"line":50,"text":"func (w *displayPartsWriter) WriteFrom(other *displayPartsWriter) {"},
  {"line":51,"text":"\tw.builder.WriteString(other.String())"},
  {"line":52,"text":"\tif w.vsCapability {"},
  {"line":53,"text":"\t\tw.runs = append(w.runs, other.GetRuns()...)"},
  {"line":54,"text":"\t}"},
  {"line":55,"text":"\tif other.lastWritten != \"\" {"},
  {"line":56,"text":"\t\tw.lastWritten = other.lastWritten"},
  {"line":57,"text":"\t}"},
  {"line":58,"text":"}"},
  {"line":60,"text":"func (w *displayPartsWriter) GetRuns() []*lsproto.ClassifiedTextRun {"},
  {"line":61,"text":"\treturn w.runs"},
  {"line":62,"text":"}"},
  {"line":64,"text":"func (w *displayPartsWriter) String() string {"},
  {"line":65,"text":"\treturn w.builder.String()"},
  {"line":66,"text":"}"},
  {"line":68,"text":"func (w *displayPartsWriter) Clear() {"},
  {"line":69,"text":"\tw.lastWritten = \"\""},
  {"line":70,"text":"\tw.builder.Reset()"},
  {"line":71,"text":"\tw.runs = nil"},
  {"line":72,"text":"}"},
  {"line":74,"text":"func (w displayPartsWriter) DecreaseIndent() {}"},
  {"line":76,"text":"func (w displayPartsWriter) GetColumn() core.UTF16Offset { return 0 }"},
  {"line":78,"text":"func (w displayPartsWriter) GetIndent() int { return 0 }"},
  {"line":80,"text":"func (w displayPartsWriter) GetLine() int { return 0 }"},
  {"line":82,"text":"func (w displayPartsWriter) GetTextPos() int {"},
  {"line":83,"text":"\treturn w.builder.Len()"},
  {"line":84,"text":"}"},
  {"line":86,"text":"func (w displayPartsWriter) HasTrailingComment() bool { return false }"},
  {"line":88,"text":"func (w displayPartsWriter) HasTrailingWhitespace() bool {"},
  {"line":89,"text":"\tif w.builder.Len() == 0 {"},
  {"line":90,"text":"\t\treturn false"},
  {"line":91,"text":"\t}"},
  {"line":92,"text":"\tch, _ := utf8.DecodeLastRuneInString(w.lastWritten)"},
  {"line":93,"text":"\tif ch == utf8.RuneError {"},
  {"line":94,"text":"\t\treturn false"},
  {"line":95,"text":"\t}"},
  {"line":96,"text":"\treturn stringutil.IsWhiteSpaceLike(ch)"},
  {"line":97,"text":"}"},
  {"line":99,"text":"func (w displayPartsWriter) IncreaseIndent() {}"},
  {"line":101,"text":"func (w displayPartsWriter) IsAtStartOfLine() bool { return false }"},
  {"line":103,"text":"func (w *displayPartsWriter) RawWrite(s string) {"},
  {"line":104,"text":"\tw.addRun(lsproto.ClassificationTypeNameText, s)"},
  {"line":105,"text":"}"},
  {"line":107,"text":"func (w *displayPartsWriter) Write(s string) {"},
  {"line":108,"text":"\tw.addRun(lsproto.ClassificationTypeNameText, s)"},
  {"line":109,"text":"}"},
  {"line":111,"text":"func (w *displayPartsWriter) WriteComment(text string) {"},
  {"line":113,"text":"\tw.addRun(lsproto.ClassificationTypeNameText, text)"},
  {"line":114,"text":"}"},
  {"line":116,"text":"func (w *displayPartsWriter) WriteKeyword(text string) {"},
  {"line":117,"text":"\tw.addRun(lsproto.ClassificationTypeNameKeyword, text)"},
  {"line":118,"text":"}"},
  {"line":120,"text":"func (w *displayPartsWriter) WriteLine() {"},
  {"line":121,"text":"\tw.addRun(lsproto.ClassificationTypeNameWhiteSpace, \" \")"},
  {"line":122,"text":"}"},
  {"line":124,"text":"func (w *displayPartsWriter) WriteLineForce(force bool) {"},
  {"line":125,"text":"\tw.addRun(lsproto.ClassificationTypeNameWhiteSpace, \" \")"},
  {"line":126,"text":"}"},
  {"line":128,"text":"func (w *displayPartsWriter) WriteLiteral(s string) {"},
  {"line":130,"text":"\tw.addRun(lsproto.ClassificationTypeNameString, s)"},
  {"line":131,"text":"}"},
  {"line":133,"text":"func (w *displayPartsWriter) WriteOperator(text string) {"},
  {"line":134,"text":"\tw.addRun(lsproto.ClassificationTypeNameOperator, text)"},
  {"line":135,"text":"}"},
  {"line":137,"text":"func (w *displayPartsWriter) WriteParameter(text string) {"},
  {"line":138,"text":"\tw.addRun(lsproto.ClassificationTypeNameParameterName, text)"},
  {"line":139,"text":"}"},
  {"line":141,"text":"func (w *displayPartsWriter) WriteProperty(text string) {"},
  {"line":142,"text":"\tw.addRun(lsproto.ClassificationTypeNamePropertyName, text)"},
  {"line":143,"text":"}"},
  {"line":145,"text":"func (w *displayPartsWriter) WritePunctuation(text string) {"},
  {"line":146,"text":"\tw.addRun(lsproto.ClassificationTypeNamePunctuation, text)"},
  {"line":147,"text":"}"},
  {"line":149,"text":"func (w *displayPartsWriter) WriteSpace(text string) {"},
  {"line":150,"text":"\tw.addRun(lsproto.ClassificationTypeNameWhiteSpace, text)"},
  {"line":151,"text":"}"},
  {"line":153,"text":"func (w *displayPartsWriter) WriteStringLiteral(text string) {"},
  {"line":154,"text":"\tw.addRun(lsproto.ClassificationTypeNameString, text)"},
  {"line":155,"text":"}"},
  {"line":157,"text":"func (w *displayPartsWriter) WriteSymbol(text string, symbol *ast.Symbol) {"},
  {"line":158,"text":"\tclassification := classificationForSymbol(symbol)"},
  {"line":159,"text":"\tw.addRun(classification, text)"},
  {"line":160,"text":"}"},
  {"line":162,"text":"func (w *displayPartsWriter) WriteTrailingSemicolon(text string) {"},
  {"line":163,"text":"\tw.addRun(lsproto.ClassificationTypeNamePunctuation, text)"},
  {"line":164,"text":"}"},
  {"line":168,"text":"func classificationForSymbol(symbol *ast.Symbol) lsproto.ClassificationTypeName {"},
  {"line":169,"text":"\tif symbol == nil {"},
  {"line":170,"text":"\t\treturn lsproto.ClassificationTypeNameText"},
  {"line":171,"text":"\t}"},
  {"line":172,"text":"\tflags := symbol.Flags"},
  {"line":173,"text":"\tswitch {"},
  {"line":174,"text":"\tcase flags&ast.SymbolFlagsVariable != 0:"},
  {"line":175,"text":"\t\tif isFirstDeclarationOfSymbolParameter(symbol) {"},
  {"line":176,"text":"\t\t\treturn lsproto.ClassificationTypeNameParameterName"},
  {"line":177,"text":"\t\t}"},
  {"line":178,"text":"\t\treturn lsproto.ClassificationTypeNameLocalName"},
  {"line":179,"text":"\tcase flags&ast.SymbolFlagsProperty != 0:"},
  {"line":180,"text":"\t\treturn lsproto.ClassificationTypeNamePropertyName"},
  {"line":181,"text":"\tcase flags&ast.SymbolFlagsGetAccessor != 0:"},
  {"line":182,"text":"\t\treturn lsproto.ClassificationTypeNamePropertyName"},
  {"line":183,"text":"\tcase flags&ast.SymbolFlagsSetAccessor != 0:"},
  {"line":184,"text":"\t\treturn lsproto.ClassificationTypeNamePropertyName"},
  {"line":185,"text":"\tcase flags&ast.SymbolFlagsEnumMember != 0:"},
  {"line":186,"text":"\t\treturn lsproto.ClassificationTypeNameFieldName"},
  {"line":187,"text":"\tcase flags&ast.SymbolFlagsFunction != 0:"},
  {"line":188,"text":"\t\treturn lsproto.ClassificationTypeNameMethodName"},
  {"line":189,"text":"\tcase flags&ast.SymbolFlagsClass != 0:"},
  {"line":190,"text":"\t\treturn lsproto.ClassificationTypeNameClassName"},
  {"line":191,"text":"\tcase flags&ast.SymbolFlagsInterface != 0:"},
  {"line":192,"text":"\t\treturn lsproto.ClassificationTypeNameInterfaceName"},
  {"line":193,"text":"\tcase flags&ast.SymbolFlagsEnum != 0:"},
  {"line":194,"text":"\t\treturn lsproto.ClassificationTypeNameEnumName"},
  {"line":195,"text":"\tcase flags&ast.SymbolFlagsModule != 0:"},
  {"line":196,"text":"\t\treturn lsproto.ClassificationTypeNameModuleName"},
  {"line":197,"text":"\tcase flags&ast.SymbolFlagsMethod != 0:"},
  {"line":198,"text":"\t\treturn lsproto.ClassificationTypeNameMethodName"},
  {"line":199,"text":"\tcase flags&ast.SymbolFlagsTypeParameter != 0:"},
  {"line":200,"text":"\t\treturn lsproto.ClassificationTypeNameTypeParameterName"},
  {"line":201,"text":"\tcase flags&ast.SymbolFlagsTypeAlias != 0:"},
  {"line":202,"text":"\t\treturn lsproto.ClassificationTypeNameIdentifier"},
  {"line":203,"text":"\tcase flags&ast.SymbolFlagsAlias != 0:"},
  {"line":204,"text":"\t\treturn lsproto.ClassificationTypeNameIdentifier"},
  {"line":205,"text":"\tdefault:"},
  {"line":206,"text":"\t\treturn lsproto.ClassificationTypeNameText"},
  {"line":207,"text":"\t}"},
  {"line":208,"text":"}"},
  {"line":211,"text":"func isFirstDeclarationOfSymbolParameter(symbol *ast.Symbol) bool {"},
  {"line":212,"text":"\tdeclarations := symbol.Declarations"},
  {"line":213,"text":"\tif len(declarations) == 0 {"},
  {"line":214,"text":"\t\treturn false"},
  {"line":215,"text":"\t}"},
  {"line":216,"text":"\treturn declarations[0].Kind == ast.KindParameter"},
  {"line":217,"text":"}"},
];

export function findLsDisplayPartsWriterDeclaration(name: string): UpstreamDeclaration | undefined {
  return lsDisplayPartsWriterDeclarations.find((declaration) => declaration.name === name);
}

export function requireLsDisplayPartsWriterDeclaration(name: string): UpstreamDeclaration {
  const declaration = findLsDisplayPartsWriterDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function lsDisplayPartsWriterLineText(line: number): string | undefined {
  return lsDisplayPartsWriterSourceLines.find((entry) => entry.line === line)?.text;
}
