/**
 * Language-service parity map for TS-Go `ls/file_rename.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameUpstreamPath = "ls/file_rename.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameDeclarations: readonly UpstreamDeclaration[] = [
  {"line":20,"kind":"type","name":"pathUpdater"},
  {"line":22,"kind":"type","name":"toImport"},
  {"line":27,"kind":"func","name":"GetEditsForFileRename","receiver":"l *LanguageService"},
  {"line":81,"kind":"func","name":"createPathUpdater","receiver":"l *LanguageService"},
  {"line":94,"kind":"func","name":"updateTsconfigFiles","receiver":"l *LanguageService"},
  {"line":159,"kind":"func","name":"updatePathsProperty"},
  {"line":172,"kind":"func","name":"tryUpdateConfigString"},
  {"line":190,"kind":"func","name":"updateRelativePath","receiver":"l *LanguageService"},
  {"line":199,"kind":"func","name":"updateImportsForFileRename","receiver":"l *LanguageService"},
  {"line":233,"kind":"func","name":"getUpdatedImportSpecifier","receiver":"l *LanguageService"},
  {"line":282,"kind":"func","name":"getSourceFileToImport"},
  {"line":301,"kind":"func","name":"getUpdatedImportSpecifierFromMovedSourceFiles"},
  {"line":341,"kind":"func","name":"createStringTextRange"},
  {"line":345,"kind":"func","name":"getTsConfigObjectLiteralExpression"},
  {"line":355,"kind":"func","name":"forEachObjectProperty"},
  {"line":369,"kind":"func","name":"relativePathFromDirectory"},
  {"line":373,"kind":"func","name":"relativeImportPathFromDirectory"},
  {"line":377,"kind":"func","name":"isAmbientModuleSymbol"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/change\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/modulespecifiers\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/tsoptions\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"line":18,"text":")"},
  {"line":20,"text":"type pathUpdater func(path string) (string, bool)"},
  {"line":22,"text":"type toImport struct {"},
  {"line":23,"text":"\tnewFileName string"},
  {"line":24,"text":"\tupdated     bool"},
  {"line":25,"text":"}"},
  {"line":27,"text":"func (l *LanguageService) GetEditsForFileRename(ctx context.Context, oldURI lsproto.DocumentUri, newURI lsproto.DocumentUri) []lsproto.TextDocumentEditOrCreateFileOrRenameFileOrDeleteFile {"},
  {"line":28,"text":"\tprogram := l.GetProgram()"},
  {"line":29,"text":"\toldPath := oldURI.FileName()"},
  {"line":30,"text":"\tnewPath := newURI.FileName()"},
  {"line":32,"text":"\toldToNew := l.createPathUpdater(oldPath, newPath)"},
  {"line":34,"text":"\tchangeTracker := change.NewTracker(ctx, program.Options(), l.FormatOptions(), l.converters)"},
  {"line":35,"text":"\tl.updateTsconfigFiles(program, changeTracker, oldToNew, oldPath, newPath)"},
  {"line":36,"text":"\tl.updateImportsForFileRename(program, changeTracker, oldToNew)"},
  {"line":38,"text":"\tvar documentChanges []lsproto.TextDocumentEditOrCreateFileOrRenameFileOrDeleteFile"},
  {"line":41,"text":"\tif tspath.IsDeclarationFileName(oldPath) && tspath.IsDeclarationFileName(newPath) {"},
  {"line":42,"text":"\t\tdtsExt := tspath.GetDeclarationFileExtension(oldPath)"},
  {"line":43,"text":"\t\toriginalExtensions := tspath.GetPossibleOriginalInputExtensionForExtension(dtsExt)"},
  {"line":44,"text":"\t\tfor _, ext := range originalExtensions {"},
  {"line":45,"text":"\t\t\toldOriginalPath := tspath.ChangeFullExtension(oldPath, ext)"},
  {"line":46,"text":"\t\t\tif l.host.FileExists(oldOriginalPath) {"},
  {"line":47,"text":"\t\t\t\tnewDtsExt := tspath.GetDeclarationFileExtension(oldPath)"},
  {"line":48,"text":"\t\t\t\tnewOriginalExtensions := tspath.GetPossibleOriginalInputExtensionForExtension(newDtsExt)"},
  {"line":49,"text":"\t\t\t\tif slices.Contains(newOriginalExtensions, ext) {"},
  {"line":50,"text":"\t\t\t\t\tnewOriginalPath := tspath.ChangeFullExtension(newPath, ext)"},
  {"line":51,"text":"\t\t\t\t\tdocumentChanges = append(documentChanges, lsproto.TextDocumentEditOrCreateFileOrRenameFileOrDeleteFile{"},
  {"line":52,"text":"\t\t\t\t\t\tRenameFile: &lsproto.RenameFile{"},
  {"line":53,"text":"\t\t\t\t\t\t\tOldUri: lsconv.FileNameToDocumentURI(oldOriginalPath),"},
  {"line":54,"text":"\t\t\t\t\t\t\tNewUri: lsconv.FileNameToDocumentURI(newOriginalPath),"},
  {"line":55,"text":"\t\t\t\t\t\t},"},
  {"line":56,"text":"\t\t\t\t\t})"},
  {"line":57,"text":"\t\t\t\t}"},
  {"line":58,"text":"\t\t\t}"},
  {"line":59,"text":"\t\t}"},
  {"line":60,"text":"\t}"},
  {"line":62,"text":"\tfor fileName, edits := range changeTracker.GetChanges() {"},
  {"line":63,"text":"\t\turi := lsconv.FileNameToDocumentURI(fileName)"},
  {"line":64,"text":"\t\tlspEdits := make([]lsproto.TextEditOrAnnotatedTextEditOrSnippetTextEdit, 0, len(edits))"},
  {"line":65,"text":"\t\tfor _, edit := range edits {"},
  {"line":66,"text":"\t\t\tlspEdits = append(lspEdits, lsproto.TextEditOrAnnotatedTextEditOrSnippetTextEdit{"},
  {"line":67,"text":"\t\t\t\tTextEdit: edit,"},
  {"line":68,"text":"\t\t\t})"},
  {"line":69,"text":"\t\t}"},
  {"line":70,"text":"\t\tdocumentChanges = append(documentChanges, lsproto.TextDocumentEditOrCreateFileOrRenameFileOrDeleteFile{"},
  {"line":71,"text":"\t\t\tTextDocumentEdit: &lsproto.TextDocumentEdit{"},
  {"line":72,"text":"\t\t\t\tTextDocument: lsproto.OptionalVersionedTextDocumentIdentifier{Uri: uri},"},
  {"line":73,"text":"\t\t\t\tEdits:        lspEdits,"},
  {"line":74,"text":"\t\t\t},"},
  {"line":75,"text":"\t\t})"},
  {"line":76,"text":"\t}"},
  {"line":78,"text":"\treturn documentChanges"},
  {"line":79,"text":"}"},
  {"line":81,"text":"func (l *LanguageService) createPathUpdater(oldPath string, newPath string) pathUpdater {"},
  {"line":82,"text":"\tcompareOptions := tspath.ComparePathsOptions{UseCaseSensitiveFileNames: l.UseCaseSensitiveFileNames()}"},
  {"line":83,"text":"\treturn func(path string) (string, bool) {"},
  {"line":84,"text":"\t\tif tspath.ComparePaths(path, oldPath, compareOptions) == 0 {"},
  {"line":85,"text":"\t\t\treturn newPath, true"},
  {"line":86,"text":"\t\t}"},
  {"line":87,"text":"\t\tif tspath.StartsWithDirectory(path, oldPath, l.UseCaseSensitiveFileNames()) {"},
  {"line":88,"text":"\t\t\treturn newPath + path[len(oldPath):], true"},
  {"line":89,"text":"\t\t}"},
  {"line":90,"text":"\t\treturn \"\", false"},
  {"line":91,"text":"\t}"},
  {"line":92,"text":"}"},
  {"line":94,"text":"func (l *LanguageService) updateTsconfigFiles(program *compiler.Program, changeTracker *change.Tracker, oldToNew pathUpdater, oldPath string, newPath string) {"},
  {"line":95,"text":"\tcommandLine := program.CommandLine()"},
  {"line":96,"text":"\tif commandLine == nil || commandLine.ConfigFile == nil {"},
  {"line":97,"text":"\t\treturn"},
  {"line":98,"text":"\t}"},
  {"line":100,"text":"\tconfigFile := commandLine.ConfigFile.SourceFile"},
  {"line":101,"text":"\tif configFile == nil {"},
  {"line":102,"text":"\t\treturn"},
  {"line":103,"text":"\t}"},
  {"line":104,"text":"\tconfigDir := tspath.GetDirectoryPath(configFile.FileName())"},
  {"line":105,"text":"\tjsonObjectLiteral := getTsConfigObjectLiteralExpression(configFile)"},
  {"line":106,"text":"\tif jsonObjectLiteral == nil {"},
  {"line":107,"text":"\t\treturn"},
  {"line":108,"text":"\t}"},
  {"line":110,"text":"\tforEachObjectProperty(jsonObjectLiteral, func(property *ast.PropertyAssignment, propertyName string) {"},
  {"line":111,"text":"\t\tswitch propertyName {"},
  {"line":112,"text":"\t\tcase \"files\", \"include\", \"exclude\":"},
  {"line":113,"text":"\t\t\tfoundExactMatch := updatePathsProperty(configFile, configDir, property, changeTracker, oldToNew, l.converters, l.UseCaseSensitiveFileNames())"},
  {"line":114,"text":"\t\t\tif foundExactMatch || propertyName != \"include\" || !ast.IsArrayLiteralExpression(property.Initializer) {"},
  {"line":115,"text":"\t\t\t\treturn"},
  {"line":116,"text":"\t\t\t}"},
  {"line":117,"text":"\t\t\tif oldSpec, isDefault := commandLine.GetMatchedIncludeSpec(oldPath); oldSpec != \"\" && !isDefault {"},
  {"line":118,"text":"\t\t\t\tif newSpec, _ := commandLine.GetMatchedIncludeSpec(newPath); newSpec == \"\" {"},
  {"line":119,"text":"\t\t\t\t\telements := property.Initializer.Elements()"},
  {"line":120,"text":"\t\t\t\t\tif len(elements) > 0 {"},
  {"line":121,"text":"\t\t\t\t\t\tchangeTracker.InsertNodeAfter("},
  {"line":122,"text":"\t\t\t\t\t\t\tconfigFile,"},
  {"line":123,"text":"\t\t\t\t\t\t\telements[len(elements)-1],"},
  {"line":124,"text":"\t\t\t\t\t\t\tchangeTracker.NodeFactory.NewStringLiteral(relativePathFromDirectory(configDir, newPath, l.UseCaseSensitiveFileNames()), ast.TokenFlagsNone),"},
  {"line":125,"text":"\t\t\t\t\t\t)"},
  {"line":126,"text":"\t\t\t\t\t}"},
  {"line":127,"text":"\t\t\t\t}"},
  {"line":128,"text":"\t\t\t}"},
  {"line":129,"text":"\t\tcase \"compilerOptions\":"},
  {"line":130,"text":"\t\t\tif !ast.IsObjectLiteralExpression(property.Initializer) {"},
  {"line":131,"text":"\t\t\t\treturn"},
  {"line":132,"text":"\t\t\t}"},
  {"line":133,"text":"\t\t\tforEachObjectProperty(property.Initializer.AsObjectLiteralExpression(), func(property *ast.PropertyAssignment, propertyName string) {"},
  {"line":134,"text":"\t\t\t\toption := tsoptions.CommandLineCompilerOptionsMap.Get(propertyName)"},
  {"line":135,"text":"\t\t\t\tif option != nil {"},
  {"line":136,"text":"\t\t\t\t\telementOption := option.Elements()"},
  {"line":137,"text":"\t\t\t\t\tif option.IsFilePath || (option.Kind == tsoptions.CommandLineOptionTypeList && elementOption != nil && elementOption.IsFilePath) {"},
  {"line":138,"text":"\t\t\t\t\t\tupdatePathsProperty(configFile, configDir, property, changeTracker, oldToNew, l.converters, l.UseCaseSensitiveFileNames())"},
  {"line":139,"text":"\t\t\t\t\t\treturn"},
  {"line":140,"text":"\t\t\t\t\t}"},
  {"line":141,"text":"\t\t\t\t}"},
  {"line":143,"text":"\t\t\t\tif propertyName != \"paths\" || !ast.IsObjectLiteralExpression(property.Initializer) {"},
  {"line":144,"text":"\t\t\t\t\treturn"},
  {"line":145,"text":"\t\t\t\t}"},
  {"line":146,"text":"\t\t\t\tforEachObjectProperty(property.Initializer.AsObjectLiteralExpression(), func(pathsProperty *ast.PropertyAssignment, _ string) {"},
  {"line":147,"text":"\t\t\t\t\tif !ast.IsArrayLiteralExpression(pathsProperty.Initializer) {"},
  {"line":148,"text":"\t\t\t\t\t\treturn"},
  {"line":149,"text":"\t\t\t\t\t}"},
  {"line":150,"text":"\t\t\t\t\tfor _, element := range pathsProperty.Initializer.Elements() {"},
  {"line":151,"text":"\t\t\t\t\t\ttryUpdateConfigString(configFile, configDir, element, changeTracker, oldToNew, l.converters, l.UseCaseSensitiveFileNames())"},
  {"line":152,"text":"\t\t\t\t\t}"},
  {"line":153,"text":"\t\t\t\t})"},
  {"line":154,"text":"\t\t\t})"},
  {"line":155,"text":"\t\t}"},
  {"line":156,"text":"\t})"},
  {"line":157,"text":"}"},
  {"line":159,"text":"func updatePathsProperty(configFile *ast.SourceFile, configDir string, property *ast.PropertyAssignment, changeTracker *change.Tracker, oldToNew pathUpdater, converters *lsconv.Converters, useCaseSensitiveFileNames bool) bool {"},
  {"line":160,"text":"\telements := []*ast.Node{property.Initializer}"},
  {"line":161,"text":"\tif ast.IsArrayLiteralExpression(property.Initializer) {"},
  {"line":162,"text":"\t\telements = property.Initializer.Elements()"},
  {"line":163,"text":"\t}"},
  {"line":165,"text":"\tfoundExactMatch := false"},
  {"line":166,"text":"\tfor _, element := range elements {"},
  {"line":167,"text":"\t\tfoundExactMatch = tryUpdateConfigString(configFile, configDir, element, changeTracker, oldToNew, converters, useCaseSensitiveFileNames) || foundExactMatch"},
  {"line":168,"text":"\t}"},
  {"line":169,"text":"\treturn foundExactMatch"},
  {"line":170,"text":"}"},
  {"line":172,"text":"func tryUpdateConfigString(configFile *ast.SourceFile, configDir string, element *ast.Node, changeTracker *change.Tracker, oldToNew pathUpdater, converters *lsconv.Converters, useCaseSensitiveFileNames bool) bool {"},
  {"line":173,"text":"\tif !ast.IsStringLiteral(element) {"},
  {"line":174,"text":"\t\treturn false"},
  {"line":175,"text":"\t}"},
  {"line":177,"text":"\telementFileName := tspath.NormalizePath(tspath.CombinePaths(configDir, element.Text()))"},
  {"line":178,"text":"\tupdated, ok := oldToNew(elementFileName)"},
  {"line":179,"text":"\tif !ok {"},
  {"line":180,"text":"\t\treturn false"},
  {"line":181,"text":"\t}"},
  {"line":183,"text":"\tchangeTracker.ReplaceRangeWithText(configFile, lsproto.Range{"},
  {"line":184,"text":"\t\tStart: converters.PositionToLineAndCharacter(configFile, core.TextPos(scanner.GetTokenPosOfNode(element, configFile, false)+1)),"},
  {"line":185,"text":"\t\tEnd:   converters.PositionToLineAndCharacter(configFile, core.TextPos(element.End()-1)),"},
  {"line":186,"text":"\t}, relativePathFromDirectory(configDir, updated, useCaseSensitiveFileNames))"},
  {"line":187,"text":"\treturn true"},
  {"line":188,"text":"}"},
  {"line":190,"text":"func (l *LanguageService) updateRelativePath(oldToNew pathUpdater, oldImportFromPath, newImportFromPath, relativeSpecifier string) string {"},
  {"line":191,"text":"\toldAbsolute := tspath.NormalizePath(tspath.CombinePaths(tspath.GetDirectoryPath(oldImportFromPath), relativeSpecifier))"},
  {"line":192,"text":"\tnewAbsolute, ok := oldToNew(oldAbsolute)"},
  {"line":193,"text":"\tif !ok {"},
  {"line":194,"text":"\t\tnewAbsolute = oldAbsolute"},
  {"line":195,"text":"\t}"},
  {"line":196,"text":"\treturn relativeImportPathFromDirectory(tspath.GetDirectoryPath(newImportFromPath), newAbsolute, l.UseCaseSensitiveFileNames())"},
  {"line":197,"text":"}"},
  {"line":199,"text":"func (l *LanguageService) updateImportsForFileRename(program *compiler.Program, changeTracker *change.Tracker, oldToNew pathUpdater) {"},
  {"line":200,"text":"\tallFiles := program.GetSourceFiles()"},
  {"line":201,"text":"\tchecker, done := program.GetTypeChecker(context.Background())"},
  {"line":202,"text":"\tdefer done()"},
  {"line":203,"text":"\tmoduleSpecifierPreferences := l.UserPreferences().ModuleSpecifierPreferences()"},
  {"line":205,"text":"\tfor _, sourceFile := range allFiles {"},
  {"line":206,"text":"\t\toldFileName := sourceFile.FileName()"},
  {"line":207,"text":"\t\tnewFromOld, fileMoved := oldToNew(sourceFile.FileName())"},
  {"line":208,"text":"\t\tnewImportFromPath := sourceFile.FileName()"},
  {"line":209,"text":"\t\tif fileMoved {"},
  {"line":210,"text":"\t\t\tnewImportFromPath = newFromOld"},
  {"line":211,"text":"\t\t}"},
  {"line":213,"text":"\t\tfor _, ref := range sourceFile.ReferencedFiles {"},
  {"line":214,"text":"\t\t\tif !tspath.IsExternalModuleNameRelative(ref.FileName) {"},
  {"line":215,"text":"\t\t\t\tcontinue"},
  {"line":216,"text":"\t\t\t}"},
  {"line":217,"text":"\t\t\tupdated := l.updateRelativePath(oldToNew, oldFileName, newImportFromPath, ref.FileName)"},
  {"line":218,"text":"\t\t\tif updated != ref.FileName {"},
  {"line":219,"text":"\t\t\t\tchangeTracker.ReplaceRangeWithText(sourceFile, l.converters.ToLSPRange(sourceFile, ref.TextRange), updated)"},
  {"line":220,"text":"\t\t\t}"},
  {"line":221,"text":"\t\t}"},
  {"line":223,"text":"\t\tfor _, importStringLiteral := range sourceFile.Imports() {"},
  {"line":224,"text":"\t\t\tupdated := l.getUpdatedImportSpecifier(program, checker, sourceFile, importStringLiteral, oldToNew, newImportFromPath, fileMoved, moduleSpecifierPreferences)"},
  {"line":225,"text":"\t\t\tif updated != \"\" && updated != importStringLiteral.Text() {"},
  {"line":226,"text":"\t\t\t\tchangeTracker.ReplaceRangeWithText(sourceFile, l.converters.ToLSPRange(sourceFile, createStringTextRange(sourceFile, importStringLiteral)), updated)"},
  {"line":227,"text":"\t\t\t}"},
  {"line":228,"text":"\t\t}"},
  {"line":229,"text":"\t}"},
  {"line":230,"text":"}"},
  {"line":233,"text":"func (l *LanguageService) getUpdatedImportSpecifier("},
  {"line":234,"text":"\tprogram *compiler.Program,"},
  {"line":235,"text":"\tchecker *checker.Checker,"},
  {"line":236,"text":"\tsourceFile *ast.SourceFile, // old importing source file"},
  {"line":237,"text":"\timportLiteral *ast.StringLiteralLike,"},
  {"line":238,"text":"\toldToNew pathUpdater,"},
  {"line":239,"text":"\tnewImportFromPath string,"},
  {"line":240,"text":"\timportingSourceFileMoved bool,"},
  {"line":241,"text":"\tuserPreferences modulespecifiers.UserPreferences,"},
  {"line":242,"text":") string {"},
  {"line":243,"text":"\timportedModuleSymbol := checker.GetSymbolAtLocation(importLiteral)"},
  {"line":244,"text":"\tif isAmbientModuleSymbol(importedModuleSymbol) {"},
  {"line":245,"text":"\t\treturn \"\""},
  {"line":246,"text":"\t}"},
  {"line":248,"text":"\ttarget := getSourceFileToImport(program, sourceFile, importLiteral, oldToNew)"},
  {"line":250,"text":"\tif target == nil {"},
  {"line":252,"text":"\t\tif updated := getUpdatedImportSpecifierFromMovedSourceFiles(program, sourceFile, importLiteral, oldToNew, newImportFromPath, userPreferences); updated != \"\" && updated != importLiteral.Text() {"},
  {"line":253,"text":"\t\t\treturn updated"},
  {"line":254,"text":"\t\t}"},
  {"line":256,"text":"\t\tif tspath.IsExternalModuleNameRelative(importLiteral.Text()) {"},
  {"line":257,"text":"\t\t\treturn l.updateRelativePath(oldToNew, sourceFile.FileName(), newImportFromPath, importLiteral.Text())"},
  {"line":258,"text":"\t\t}"},
  {"line":259,"text":"\t\treturn \"\""},
  {"line":260,"text":"\t}"},
  {"line":263,"text":"\tif !target.updated && !(importingSourceFileMoved && tspath.IsExternalModuleNameRelative(importLiteral.Text())) {"},
  {"line":264,"text":"\t\treturn \"\""},
  {"line":265,"text":"\t}"},
  {"line":267,"text":"\tupdated := modulespecifiers.UpdateModuleSpecifier("},
  {"line":268,"text":"\t\tprogram.Options(),"},
  {"line":269,"text":"\t\tprogram,"},
  {"line":270,"text":"\t\tsourceFile,"},
  {"line":271,"text":"\t\tnewImportFromPath,"},
  {"line":272,"text":"\t\timportLiteral.Text(),"},
  {"line":273,"text":"\t\ttarget.newFileName,"},
  {"line":274,"text":"\t\tuserPreferences,"},
  {"line":275,"text":"\t\tmodulespecifiers.ModuleSpecifierOptions{"},
  {"line":276,"text":"\t\t\tOverrideImportMode: program.GetModeForUsageLocation(sourceFile, importLiteral),"},
  {"line":277,"text":"\t\t},"},
  {"line":278,"text":"\t)"},
  {"line":279,"text":"\treturn updated"},
  {"line":280,"text":"}"},
  {"line":282,"text":"func getSourceFileToImport("},
  {"line":283,"text":"\tprogram *compiler.Program,"},
  {"line":284,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":285,"text":"\timportLiteral *ast.StringLiteralLike,"},
  {"line":286,"text":"\toldToNew pathUpdater,"},
  {"line":287,"text":") *toImport {"},
  {"line":288,"text":"\tif resolved := program.GetResolvedModuleFromModuleSpecifier(sourceFile, importLiteral); resolved != nil && resolved.ResolvedFileName != \"\" {"},
  {"line":289,"text":"\t\toldFileName := resolved.ResolvedFileName"},
  {"line":290,"text":"\t\tif newFileName, ok := oldToNew(oldFileName); ok {"},
  {"line":291,"text":"\t\t\treturn &toImport{newFileName: newFileName, updated: true}"},
  {"line":292,"text":"\t\t}"},
  {"line":293,"text":"\t\treturn &toImport{newFileName: oldFileName, updated: false}"},
  {"line":294,"text":"\t}"},
  {"line":296,"text":"\treturn nil"},
  {"line":297,"text":"}"},
  {"line":301,"text":"func getUpdatedImportSpecifierFromMovedSourceFiles(program *compiler.Program, sourceFile *ast.SourceFile, importLiteral *ast.StringLiteralLike, oldToNew pathUpdater, importingSourceFileName string, userPreferences modulespecifiers.UserPreferences) string {"},
  {"line":302,"text":"\tresolutionMode := program.GetModeForUsageLocation(sourceFile, importLiteral)"},
  {"line":303,"text":"\tfor _, candidate := range program.GetSourceFiles() {"},
  {"line":304,"text":"\t\tnewFileName, ok := oldToNew(candidate.FileName())"},
  {"line":305,"text":"\t\tif !ok {"},
  {"line":306,"text":"\t\t\tcontinue"},
  {"line":307,"text":"\t\t}"},
  {"line":309,"text":"\t\toldSpecifier := modulespecifiers.UpdateModuleSpecifier("},
  {"line":310,"text":"\t\t\tprogram.Options(),"},
  {"line":311,"text":"\t\t\tprogram,"},
  {"line":312,"text":"\t\t\tsourceFile,"},
  {"line":313,"text":"\t\t\timportingSourceFileName,"},
  {"line":314,"text":"\t\t\timportLiteral.Text(),"},
  {"line":315,"text":"\t\t\tcandidate.FileName(),"},
  {"line":316,"text":"\t\t\tuserPreferences,"},
  {"line":317,"text":"\t\t\tmodulespecifiers.ModuleSpecifierOptions{"},
  {"line":318,"text":"\t\t\t\tOverrideImportMode: resolutionMode,"},
  {"line":319,"text":"\t\t\t},"},
  {"line":320,"text":"\t\t)"},
  {"line":321,"text":"\t\tif oldSpecifier != importLiteral.Text() {"},
  {"line":322,"text":"\t\t\tcontinue"},
  {"line":323,"text":"\t\t}"},
  {"line":325,"text":"\t\treturn modulespecifiers.UpdateModuleSpecifier("},
  {"line":326,"text":"\t\t\tprogram.Options(),"},
  {"line":327,"text":"\t\t\tprogram,"},
  {"line":328,"text":"\t\t\tsourceFile,"},
  {"line":329,"text":"\t\t\timportingSourceFileName,"},
  {"line":330,"text":"\t\t\timportLiteral.Text(),"},
  {"line":331,"text":"\t\t\tnewFileName,"},
  {"line":332,"text":"\t\t\tuserPreferences,"},
  {"line":333,"text":"\t\t\tmodulespecifiers.ModuleSpecifierOptions{"},
  {"line":334,"text":"\t\t\t\tOverrideImportMode: resolutionMode,"},
  {"line":335,"text":"\t\t\t},"},
  {"line":336,"text":"\t\t)"},
  {"line":337,"text":"\t}"},
  {"line":338,"text":"\treturn \"\""},
  {"line":339,"text":"}"},
  {"line":341,"text":"func createStringTextRange(sourceFile *ast.SourceFile, node *ast.LiteralLikeNode) core.TextRange {"},
  {"line":342,"text":"\treturn core.NewTextRange(scanner.GetTokenPosOfNode(node, sourceFile, false)+1, node.End()-1)"},
  {"line":343,"text":"}"},
  {"line":345,"text":"func getTsConfigObjectLiteralExpression(tsConfigSourceFile *ast.SourceFile) *ast.ObjectLiteralExpression {"},
  {"line":346,"text":"\tif tsConfigSourceFile != nil && tsConfigSourceFile.Statements != nil && len(tsConfigSourceFile.Statements.Nodes) > 0 {"},
  {"line":347,"text":"\t\texpression := tsConfigSourceFile.Statements.Nodes[0].Expression()"},
  {"line":348,"text":"\t\tif ast.IsObjectLiteralExpression(expression) {"},
  {"line":349,"text":"\t\t\treturn expression.AsObjectLiteralExpression()"},
  {"line":350,"text":"\t\t}"},
  {"line":351,"text":"\t}"},
  {"line":352,"text":"\treturn nil"},
  {"line":353,"text":"}"},
  {"line":355,"text":"func forEachObjectProperty(objectLiteral *ast.ObjectLiteralExpression, cb func(property *ast.PropertyAssignment, propertyName string)) {"},
  {"line":356,"text":"\tif objectLiteral == nil {"},
  {"line":357,"text":"\t\treturn"},
  {"line":358,"text":"\t}"},
  {"line":359,"text":"\tfor _, property := range objectLiteral.Properties.Nodes {"},
  {"line":360,"text":"\t\tif !ast.IsPropertyAssignment(property) {"},
  {"line":361,"text":"\t\t\tcontinue"},
  {"line":362,"text":"\t\t}"},
  {"line":363,"text":"\t\tif name, ok := ast.TryGetTextOfPropertyName(property.Name()); ok {"},
  {"line":364,"text":"\t\t\tcb(property.AsPropertyAssignment(), name)"},
  {"line":365,"text":"\t\t}"},
  {"line":366,"text":"\t}"},
  {"line":367,"text":"}"},
  {"line":369,"text":"func relativePathFromDirectory(fromDirectory string, to string, useCaseSensitiveFileNames bool) string {"},
  {"line":370,"text":"\treturn tspath.GetRelativePathFromDirectory(fromDirectory, to, tspath.ComparePathsOptions{UseCaseSensitiveFileNames: useCaseSensitiveFileNames})"},
  {"line":371,"text":"}"},
  {"line":373,"text":"func relativeImportPathFromDirectory(fromDirectory string, to string, useCaseSensitiveFileNames bool) string {"},
  {"line":374,"text":"\treturn tspath.EnsurePathIsNonModuleName(relativePathFromDirectory(fromDirectory, to, useCaseSensitiveFileNames))"},
  {"line":375,"text":"}"},
  {"line":377,"text":"func isAmbientModuleSymbol(symbol *ast.Symbol) bool {"},
  {"line":378,"text":"\tif symbol == nil {"},
  {"line":379,"text":"\t\treturn false"},
  {"line":380,"text":"\t}"},
  {"line":381,"text":"\treturn slices.ContainsFunc(symbol.Declarations, ast.IsModuleWithStringLiteralName)"},
  {"line":382,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsFileRenameSourceLines.find((entry) => entry.line === line)?.text;
}
