/**
 * Language-service parity map for TS-Go `ls/hover.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const lsHoverUpstreamPath = "ls/hover.go";

export const lsHoverDeclarations: readonly UpstreamDeclaration[] = [
  {"line":22,"kind":"func","name":"ProvideHover","receiver":"l *LanguageService"},
  {"line":85,"kind":"func","name":"getQuickInfoAndDocumentationForSymbol","receiver":"l *LanguageService"},
  {"line":104,"kind":"func","name":"documentationFromSignature","receiver":"l *LanguageService"},
  {"line":122,"kind":"func","name":"documentationFromAlias","receiver":"l *LanguageService"},
  {"line":151,"kind":"func","name":"getDocumentationFromDeclaration","receiver":"l *LanguageService"},
  {"line":269,"kind":"func","name":"getCommentText"},
  {"line":282,"kind":"func","name":"formatQuickInfo"},
  {"line":289,"kind":"func","name":"shouldGetType"},
  {"line":304,"kind":"func","name":"getQuickInfoAndDeclarationAtLocation"},
  {"line":709,"kind":"func","name":"typeParameterToString"},
  {"line":713,"kind":"func","name":"getNodeForQuickInfo"},
  {"line":732,"kind":"func","name":"getSymbolAtLocationForQuickInfo"},
  {"line":743,"kind":"func","name":"getSignaturesAtLocation"},
  {"line":754,"kind":"func","name":"getCallOrNewExpression"},
  {"line":767,"kind":"func","name":"containsTypedefTag"},
  {"line":780,"kind":"func","name":"getJSDoc"},
  {"line":784,"kind":"func","name":"getJSDocOrTag"},
  {"line":840,"kind":"func","name":"getMatchingJSDocTag"},
  {"line":855,"kind":"func","name":"getJSDocParameterTagByPosition"},
  {"line":898,"kind":"func","name":"isMatchingParameterTag"},
  {"line":902,"kind":"func","name":"isMatchingTemplateTag"},
  {"line":906,"kind":"func","name":"isNodeWithName"},
  {"line":911,"kind":"func","name":"writeCode"},
  {"line":932,"kind":"func","name":"writeComments","receiver":"l *LanguageService"},
  {"line":945,"kind":"func","name":"writeJSDocLink","receiver":"l *LanguageService"},
  {"line":977,"kind":"func","name":"writeNameLink","receiver":"l *LanguageService"},
  {"line":1000,"kind":"func","name":"trimCommentPrefix"},
  {"line":1004,"kind":"func","name":"writeMarkdownLink"},
  {"line":1012,"kind":"func","name":"writeOptionalEntityName"},
  {"line":1019,"kind":"func","name":"writeQuotedString"},
  {"line":1030,"kind":"func","name":"findPropertyInType"},
  {"line":1043,"kind":"func","name":"getEntityNameString"},
  {"line":1049,"kind":"func","name":"writeEntityNameParts"},
];

export const lsHoverSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"fmt\""},
  {"line":6,"text":"\t\"strings\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":15,"text":")"},
  {"line":17,"text":"const ("},
  {"line":18,"text":"\tsymbolFormatFlags = checker.SymbolFormatFlagsWriteTypeParametersOrArguments | checker.SymbolFormatFlagsUseOnlyExternalAliasing | checker.SymbolFormatFlagsAllowAnyNodeKind | checker.SymbolFormatFlagsUseAliasDefinedOutsideCurrentScope"},
  {"line":19,"text":"\ttypeFormatFlags   = checker.TypeFormatFlagsUseAliasDefinedOutsideCurrentScope | checker.TypeFormatFlagsUseInstantiationExpressions"},
  {"line":20,"text":")"},
  {"line":22,"text":"func (l *LanguageService) ProvideHover(ctx context.Context, params *lsproto.HoverParams) (lsproto.HoverResponse, error) {"},
  {"line":23,"text":"\tcaps := lsproto.GetClientCapabilities(ctx)"},
  {"line":24,"text":"\tcontentFormat := lsproto.PreferredMarkupKind(caps.TextDocument.Hover.ContentFormat)"},
  {"line":26,"text":"\tverbosityLevel := 0"},
  {"line":27,"text":"\tif params.VerbosityLevel != nil {"},
  {"line":28,"text":"\t\tverbosityLevel = int(*params.VerbosityLevel)"},
  {"line":29,"text":"\t}"},
  {"line":31,"text":"\tprogram, file := l.getProgramAndFile(params.TextDocument.Uri)"},
  {"line":32,"text":"\tposition := int(l.converters.LineAndCharacterToPosition(file, params.Position))"},
  {"line":33,"text":"\tnode := astnav.GetTouchingPropertyName(file, position)"},
  {"line":34,"text":"\tif ast.IsSourceFile(node) || ast.IsPropertyAccessOrQualifiedName(node) && isInComment(file, position, node) == nil {"},
  {"line":36,"text":"\t\treturn lsproto.HoverOrNull{}, nil"},
  {"line":37,"text":"\t}"},
  {"line":38,"text":"\tc, done := program.GetTypeCheckerForFile(ctx, file)"},
  {"line":39,"text":"\tdefer done()"},
  {"line":40,"text":"\trangeNode := getNodeForQuickInfo(node)"},
  {"line":41,"text":"\tsymbol := getSymbolAtLocationForQuickInfo(c, node)"},
  {"line":46,"text":"\tmaxTruncLen := l.UserPreferences().MaximumHoverLength"},
  {"line":47,"text":"\tif maxTruncLen <= 0 {"},
  {"line":48,"text":"\t\tmaxTruncLen = 500"},
  {"line":49,"text":"\t}"},
  {"line":50,"text":"\tvc := &checker.VerbosityContext{"},
  {"line":51,"text":"\t\tLevel:               verbosityLevel,"},
  {"line":52,"text":"\t\tMaxTruncationLength: maxTruncLen,"},
  {"line":53,"text":"\t}"},
  {"line":55,"text":"\tquickInfo, documentation := l.getQuickInfoAndDocumentationForSymbol(c, symbol, rangeNode, contentFormat, vc)"},
  {"line":56,"text":"\tif quickInfo == \"\" {"},
  {"line":57,"text":"\t\treturn lsproto.HoverOrNull{}, nil"},
  {"line":58,"text":"\t}"},
  {"line":59,"text":"\thoverRange := l.getLspRangeOfNode(rangeNode, nil, nil)"},
  {"line":61,"text":"\tvar content string"},
  {"line":62,"text":"\tif contentFormat == lsproto.MarkupKindMarkdown {"},
  {"line":63,"text":"\t\tcontent = formatQuickInfo(quickInfo) + documentation"},
  {"line":64,"text":"\t} else {"},
  {"line":65,"text":"\t\tcontent = quickInfo + documentation"},
  {"line":66,"text":"\t}"},
  {"line":68,"text":"\thover := &lsproto.Hover{"},
  {"line":69,"text":"\t\tContents: lsproto.MarkupContentOrStringOrMarkedStringWithLanguageOrMarkedStrings{"},
  {"line":70,"text":"\t\t\tMarkupContent: &lsproto.MarkupContent{"},
  {"line":71,"text":"\t\t\t\tKind:  contentFormat,"},
  {"line":72,"text":"\t\t\t\tValue: content,"},
  {"line":73,"text":"\t\t\t},"},
  {"line":74,"text":"\t\t},"},
  {"line":75,"text":"\t\tRange: &hoverRange,"},
  {"line":76,"text":"\t}"},
  {"line":78,"text":"\tif caps.TextDocument.Hover.VerbosityLevel {"},
  {"line":79,"text":"\t\thover.CanIncreaseVerbosity = vc.CanIncreaseVerbosity && !vc.Truncated"},
  {"line":80,"text":"\t}"},
  {"line":82,"text":"\treturn lsproto.HoverOrNull{Hover: hover}, nil"},
  {"line":83,"text":"}"},
  {"line":85,"text":"func (l *LanguageService) getQuickInfoAndDocumentationForSymbol(c *checker.Checker, symbol *ast.Symbol, node *ast.Node, contentFormat lsproto.MarkupKind, vc *checker.VerbosityContext) (string, string) {"},
  {"line":86,"text":"\tquickInfo, declaration := getQuickInfoAndDeclarationAtLocation(c, symbol, node, vc)"},
  {"line":87,"text":"\tif quickInfo == \"\" {"},
  {"line":88,"text":"\t\treturn \"\", \"\""},
  {"line":89,"text":"\t}"},
  {"line":91,"text":"\tdocumentation := l.documentationFromSignature(c, symbol, getCallOrNewExpression(node), node, contentFormat, false /*commentOnly*/)"},
  {"line":92,"text":"\tif documentation != \"\" {"},
  {"line":93,"text":"\t\treturn quickInfo, documentation"},
  {"line":94,"text":"\t}"},
  {"line":96,"text":"\tdocumentation = l.getDocumentationFromDeclaration(c, symbol, declaration, node, contentFormat, false /*commentOnly*/)"},
  {"line":97,"text":"\tif documentation != \"\" {"},
  {"line":98,"text":"\t\treturn quickInfo, documentation"},
  {"line":99,"text":"\t}"},
  {"line":101,"text":"\treturn quickInfo, l.documentationFromAlias(c, symbol, node, contentFormat)"},
  {"line":102,"text":"}"},
  {"line":104,"text":"func (l *LanguageService) documentationFromSignature(c *checker.Checker, symbol *ast.Symbol, node *ast.Node, location *ast.Node, contentFormat lsproto.MarkupKind, commentOnly bool) string {"},
  {"line":105,"text":"\tif node == nil {"},
  {"line":106,"text":"\t\treturn \"\""},
  {"line":107,"text":"\t}"},
  {"line":108,"text":"\tsignature := c.GetResolvedSignature(node)"},
  {"line":109,"text":"\tif signature == nil {"},
  {"line":110,"text":"\t\treturn \"\""},
  {"line":111,"text":"\t}"},
  {"line":112,"text":"\tdeclaration := signature.Declaration()"},
  {"line":113,"text":"\tif declaration == nil {"},
  {"line":114,"text":"\t\treturn \"\""},
  {"line":115,"text":"\t}"},
  {"line":116,"text":"\tif ast.IsCallSignatureDeclaration(declaration) || ast.IsConstructSignatureDeclaration(declaration) {"},
  {"line":117,"text":"\t\treturn l.getDocumentationFromDeclaration(c, symbol, declaration, location, contentFormat, commentOnly)"},
  {"line":118,"text":"\t}"},
  {"line":119,"text":"\treturn \"\""},
  {"line":120,"text":"}"},
  {"line":122,"text":"func (l *LanguageService) documentationFromAlias(c *checker.Checker, symbol *ast.Symbol, node *ast.Node, contentFormat lsproto.MarkupKind) string {"},
  {"line":123,"text":"\tif symbol == nil || symbol.Flags&ast.SymbolFlagsAlias == 0 {"},
  {"line":124,"text":"\t\treturn \"\""},
  {"line":125,"text":"\t}"},
  {"line":127,"text":"\taliasedSymbol := c.GetAliasedSymbol(symbol)"},
  {"line":128,"text":"\tif aliasedSymbol == nil || aliasedSymbol == c.GetUnknownSymbol() {"},
  {"line":129,"text":"\t\treturn \"\""},
  {"line":130,"text":"\t}"},
  {"line":132,"text":"\tcandidates := []*ast.Symbol{aliasedSymbol}"},
  {"line":133,"text":"\tif aliasedSymbol.ExportSymbol != nil {"},
  {"line":134,"text":"\t\tcandidates = append(candidates, aliasedSymbol.ExportSymbol)"},
  {"line":135,"text":"\t}"},
  {"line":137,"text":"\tfor _, candidate := range candidates {"},
  {"line":138,"text":"\t\taliasedDeclaration := core.OrElse(candidate.ValueDeclaration, core.FirstOrNil(candidate.Declarations))"},
  {"line":139,"text":"\t\tif aliasedDeclaration == nil {"},
  {"line":140,"text":"\t\t\tcontinue"},
  {"line":141,"text":"\t\t}"},
  {"line":143,"text":"\t\tif documentation := l.getDocumentationFromDeclaration(c, candidate, aliasedDeclaration, node, contentFormat, false /*commentOnly*/); documentation != \"\" {"},
  {"line":144,"text":"\t\t\treturn documentation"},
  {"line":145,"text":"\t\t}"},
  {"line":146,"text":"\t}"},
  {"line":148,"text":"\treturn \"\""},
  {"line":149,"text":"}"},
  {"line":151,"text":"func (l *LanguageService) getDocumentationFromDeclaration(c *checker.Checker, symbol *ast.Symbol, declaration *ast.Node, location *ast.Node, contentFormat lsproto.MarkupKind, commentOnly bool) string {"},
  {"line":152,"text":"\tif declaration == nil {"},
  {"line":153,"text":"\t\treturn \"\""},
  {"line":154,"text":"\t}"},
  {"line":156,"text":"\tisMarkdown := contentFormat == lsproto.MarkupKindMarkdown"},
  {"line":157,"text":"\tvar b strings.Builder"},
  {"line":158,"text":"\tjsdoc := getJSDocOrTag(c, declaration)"},
  {"line":162,"text":"\tif jsdoc == nil && symbol != nil && symbol.ValueDeclaration != nil && ast.IsBindingElement(symbol.ValueDeclaration) && ast.IsIdentifier(location) {"},
  {"line":163,"text":"\t\tbindingElement := symbol.ValueDeclaration"},
  {"line":164,"text":"\t\tparent := bindingElement.Parent"},
  {"line":165,"text":"\t\tname := bindingElement.PropertyName()"},
  {"line":166,"text":"\t\tif name == nil {"},
  {"line":167,"text":"\t\t\tname = bindingElement.Name()"},
  {"line":168,"text":"\t\t}"},
  {"line":169,"text":"\t\tif ast.IsIdentifier(name) && ast.IsObjectBindingPattern(parent) {"},
  {"line":170,"text":"\t\t\tpropertyName := name.Text()"},
  {"line":171,"text":"\t\t\tobjectType := c.GetTypeAtLocation(parent)"},
  {"line":172,"text":"\t\t\tif objectType != nil {"},
  {"line":173,"text":"\t\t\t\tpropertySymbol := findPropertyInType(c, objectType, propertyName)"},
  {"line":174,"text":"\t\t\t\tif propertySymbol != nil && propertySymbol.ValueDeclaration != nil {"},
  {"line":175,"text":"\t\t\t\t\tjsdoc = getJSDocOrTag(c, propertySymbol.ValueDeclaration)"},
  {"line":176,"text":"\t\t\t\t\tif jsdoc != nil {"},
  {"line":178,"text":"\t\t\t\t\t\tdeclaration = propertySymbol.ValueDeclaration"},
  {"line":179,"text":"\t\t\t\t\t}"},
  {"line":180,"text":"\t\t\t\t}"},
  {"line":181,"text":"\t\t\t}"},
  {"line":182,"text":"\t\t}"},
  {"line":183,"text":"\t}"},
  {"line":185,"text":"\tif jsdoc != nil && !(declaration.Flags&ast.NodeFlagsReparsed == 0 && containsTypedefTag(jsdoc)) {"},
  {"line":186,"text":"\t\tl.writeComments(&b, c, jsdoc.Comments(), isMarkdown)"},
  {"line":187,"text":"\t\tif jsdoc.Kind == ast.KindJSDoc && !commentOnly {"},
  {"line":188,"text":"\t\t\tif tags := jsdoc.AsJSDoc().Tags; tags != nil {"},
  {"line":189,"text":"\t\t\t\tfor _, tag := range tags.Nodes {"},
  {"line":190,"text":"\t\t\t\t\tif tag.Kind == ast.KindJSDocTypeTag || tag.Kind == ast.KindJSDocTypedefTag || tag.Kind == ast.KindJSDocCallbackTag {"},
  {"line":191,"text":"\t\t\t\t\t\tcontinue"},
  {"line":192,"text":"\t\t\t\t\t}"},
  {"line":193,"text":"\t\t\t\t\tb.WriteString(\"\\n\\n\")"},
  {"line":194,"text":"\t\t\t\t\tif isMarkdown {"},
  {"line":195,"text":"\t\t\t\t\t\tb.WriteString(\"*@\")"},
  {"line":196,"text":"\t\t\t\t\t\tb.WriteString(tag.TagName().Text())"},
  {"line":197,"text":"\t\t\t\t\t\tb.WriteString(\"*\")"},
  {"line":198,"text":"\t\t\t\t\t} else {"},
  {"line":199,"text":"\t\t\t\t\t\tb.WriteString(\"@\")"},
  {"line":200,"text":"\t\t\t\t\t\tb.WriteString(tag.TagName().Text())"},
  {"line":201,"text":"\t\t\t\t\t}"},
  {"line":202,"text":"\t\t\t\t\tswitch tag.Kind {"},
  {"line":203,"text":"\t\t\t\t\tcase ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:"},
  {"line":204,"text":"\t\t\t\t\t\twriteOptionalEntityName(&b, tag.Name())"},
  {"line":205,"text":"\t\t\t\t\tcase ast.KindJSDocAugmentsTag:"},
  {"line":206,"text":"\t\t\t\t\t\twriteOptionalEntityName(&b, tag.ClassName())"},
  {"line":207,"text":"\t\t\t\t\tcase ast.KindJSDocTemplateTag:"},
  {"line":208,"text":"\t\t\t\t\t\tfor i, tp := range tag.TypeParameters() {"},
  {"line":209,"text":"\t\t\t\t\t\t\tif i != 0 {"},
  {"line":210,"text":"\t\t\t\t\t\t\t\tb.WriteString(\",\")"},
  {"line":211,"text":"\t\t\t\t\t\t\t}"},
  {"line":212,"text":"\t\t\t\t\t\t\twriteOptionalEntityName(&b, tp.Name())"},
  {"line":213,"text":"\t\t\t\t\t\t}"},
  {"line":214,"text":"\t\t\t\t\t}"},
  {"line":215,"text":"\t\t\t\t\tcomments := tag.Comments()"},
  {"line":216,"text":"\t\t\t\t\tif tag.Kind == ast.KindJSDocUnknownTag && tag.TagName().Text() == \"example\" {"},
  {"line":217,"text":"\t\t\t\t\t\tcommentText := strings.TrimRight(getCommentText(comments), \" \\t\\r\\n\")"},
  {"line":218,"text":"\t\t\t\t\t\tif strings.HasPrefix(commentText, \"<caption>\") {"},
  {"line":219,"text":"\t\t\t\t\t\t\tif captionEnd := strings.Index(commentText, \"</caption>\"); captionEnd > 0 {"},
  {"line":220,"text":"\t\t\t\t\t\t\t\tb.WriteString(\" — \")"},
  {"line":221,"text":"\t\t\t\t\t\t\t\tb.WriteString(commentText[len(\"<caption>\"):captionEnd])"},
  {"line":222,"text":"\t\t\t\t\t\t\t\tcommentText = commentText[captionEnd+len(\"</caption>\"):]"},
  {"line":224,"text":"\t\t\t\t\t\t\t\tfor {"},
  {"line":225,"text":"\t\t\t\t\t\t\t\t\ts1 := strings.TrimLeft(commentText, \" \\t\")"},
  {"line":226,"text":"\t\t\t\t\t\t\t\t\ts2 := strings.TrimLeft(s1, \"\\r\\n\")"},
  {"line":227,"text":"\t\t\t\t\t\t\t\t\tif len(s1) == len(s2) {"},
  {"line":228,"text":"\t\t\t\t\t\t\t\t\t\tbreak"},
  {"line":229,"text":"\t\t\t\t\t\t\t\t\t}"},
  {"line":230,"text":"\t\t\t\t\t\t\t\t\tcommentText = s2"},
  {"line":231,"text":"\t\t\t\t\t\t\t\t}"},
  {"line":232,"text":"\t\t\t\t\t\t\t}"},
  {"line":233,"text":"\t\t\t\t\t\t}"},
  {"line":234,"text":"\t\t\t\t\t\tb.WriteString(\"\\n\")"},
  {"line":235,"text":"\t\t\t\t\t\tif len(commentText) > 6 && strings.HasPrefix(commentText, \"```\") && strings.HasSuffix(commentText, \"```\") && strings.Contains(commentText, \"\\n\") {"},
  {"line":236,"text":"\t\t\t\t\t\t\tb.WriteString(commentText)"},
  {"line":237,"text":"\t\t\t\t\t\t\tb.WriteString(\"\\n\")"},
  {"line":238,"text":"\t\t\t\t\t\t} else {"},
  {"line":239,"text":"\t\t\t\t\t\t\twriteCode(&b, \"tsx\", commentText)"},
  {"line":240,"text":"\t\t\t\t\t\t}"},
  {"line":241,"text":"\t\t\t\t\t} else if tag.Kind == ast.KindJSDocSeeTag && tag.AsJSDocSeeTag().NameExpression != nil {"},
  {"line":242,"text":"\t\t\t\t\t\tb.WriteString(\" — \")"},
  {"line":243,"text":"\t\t\t\t\t\tl.writeNameLink(&b, c, tag.AsJSDocSeeTag().NameExpression.Name(), \"\", false /*quote*/, isMarkdown)"},
  {"line":244,"text":"\t\t\t\t\t\tif len(comments) != 0 {"},
  {"line":245,"text":"\t\t\t\t\t\t\tb.WriteString(\" \")"},
  {"line":246,"text":"\t\t\t\t\t\t\tl.writeComments(&b, c, comments, isMarkdown)"},
  {"line":247,"text":"\t\t\t\t\t\t}"},
  {"line":248,"text":"\t\t\t\t\t} else if tag.Kind == ast.KindJSDocThrowsTag && tag.AsJSDocThrowsTag().TypeExpression != nil {"},
  {"line":249,"text":"\t\t\t\t\t\tb.WriteString(\" — \")"},
  {"line":250,"text":"\t\t\t\t\t\tb.WriteString(scanner.GetTextOfNode(tag.AsJSDocThrowsTag().TypeExpression))"},
  {"line":251,"text":"\t\t\t\t\t\tif len(comments) != 0 {"},
  {"line":252,"text":"\t\t\t\t\t\t\tb.WriteString(\" \")"},
  {"line":253,"text":"\t\t\t\t\t\t\tl.writeComments(&b, c, comments, isMarkdown)"},
  {"line":254,"text":"\t\t\t\t\t\t}"},
  {"line":255,"text":"\t\t\t\t\t} else if len(comments) != 0 {"},
  {"line":256,"text":"\t\t\t\t\t\tb.WriteString(\" \")"},
  {"line":257,"text":"\t\t\t\t\t\tif comments[0].Kind != ast.KindJSDocText || !strings.HasPrefix(comments[0].Text(), \"-\") {"},
  {"line":258,"text":"\t\t\t\t\t\t\tb.WriteString(\"— \")"},
  {"line":259,"text":"\t\t\t\t\t\t}"},
  {"line":260,"text":"\t\t\t\t\t\tl.writeComments(&b, c, comments, isMarkdown)"},
  {"line":261,"text":"\t\t\t\t\t}"},
  {"line":262,"text":"\t\t\t\t}"},
  {"line":263,"text":"\t\t\t}"},
  {"line":264,"text":"\t\t}"},
  {"line":265,"text":"\t}"},
  {"line":266,"text":"\treturn b.String()"},
  {"line":267,"text":"}"},
  {"line":269,"text":"func getCommentText(comments []*ast.Node) string {"},
  {"line":270,"text":"\tvar b strings.Builder"},
  {"line":271,"text":"\tfor _, comment := range comments {"},
  {"line":272,"text":"\t\tswitch comment.Kind {"},
  {"line":273,"text":"\t\tcase ast.KindJSDocText:"},
  {"line":274,"text":"\t\t\tb.WriteString(comment.Text())"},
  {"line":275,"text":"\t\tcase ast.KindJSDocLink, ast.KindJSDocLinkCode, ast.KindJSDocLinkPlain:"},
  {"line":276,"text":"\t\t\tb.WriteString(scanner.GetTextOfNode(comment))"},
  {"line":277,"text":"\t\t}"},
  {"line":278,"text":"\t}"},
  {"line":279,"text":"\treturn b.String()"},
  {"line":280,"text":"}"},
  {"line":282,"text":"func formatQuickInfo(quickInfo string) string {"},
  {"line":283,"text":"\tvar b strings.Builder"},
  {"line":284,"text":"\tb.Grow(32)"},
  {"line":285,"text":"\twriteCode(&b, \"typescript\", quickInfo)"},
  {"line":286,"text":"\treturn b.String()"},
  {"line":287,"text":"}"},
  {"line":289,"text":"func shouldGetType(node *ast.Node) bool {"},
  {"line":290,"text":"\tswitch node.Kind {"},
  {"line":291,"text":"\tcase ast.KindIdentifier:"},
  {"line":294,"text":"\t\treturn !(node.Flags&ast.NodeFlagsJSDoc != 0 && ast.IsDeclarationName(node)) && !ast.IsLabelName(node) && !ast.IsTagName(node) && !ast.IsConstTypeReference(node.Parent)"},
  {"line":295,"text":"\tcase ast.KindThisKeyword, ast.KindThisType, ast.KindSuperKeyword, ast.KindNamedTupleMember:"},
  {"line":296,"text":"\t\treturn true"},
  {"line":297,"text":"\tcase ast.KindMetaProperty:"},
  {"line":298,"text":"\t\treturn ast.IsImportMeta(node)"},
  {"line":299,"text":"\tdefault:"},
  {"line":300,"text":"\t\treturn false"},
  {"line":301,"text":"\t}"},
  {"line":302,"text":"}"},
  {"line":304,"text":"func getQuickInfoAndDeclarationAtLocation(c *checker.Checker, symbol *ast.Symbol, node *ast.Node, vc *checker.VerbosityContext) (string, *ast.Node) {"},
  {"line":305,"text":"\tcontainer := getContainerNode(node)"},
  {"line":306,"text":"\tif vc == nil {"},
  {"line":307,"text":"\t\tvc = &checker.VerbosityContext{}"},
  {"line":308,"text":"\t}"},
  {"line":309,"text":"\ttypeToString := func(t *checker.Type, enclosing *ast.Node, flags checker.TypeFormatFlags) string {"},
  {"line":310,"text":"\t\tflags |= checker.TypeFormatFlagsMultilineObjectLiterals"},
  {"line":311,"text":"\t\treturn c.TypeToStringEx(t, enclosing, flags, vc)"},
  {"line":312,"text":"\t}"},
  {"line":313,"text":"\tsignatureToString := func(sig *checker.Signature, enclosing *ast.Node, flags checker.TypeFormatFlags) string {"},
  {"line":314,"text":"\t\tflags |= checker.TypeFormatFlagsMultilineObjectLiterals"},
  {"line":315,"text":"\t\treturn c.SignatureToStringEx(sig, enclosing, flags, vc)"},
  {"line":316,"text":"\t}"},
  {"line":317,"text":"\tif node.Kind == ast.KindThisKeyword && ast.IsInExpressionContext(node) || ast.IsThisInTypeQuery(node) {"},
  {"line":318,"text":"\t\treturn \"this: \" + typeToString(c.GetTypeAtLocation(node), container, typeFormatFlags), nil"},
  {"line":319,"text":"\t}"},
  {"line":320,"text":"\tif symbol == nil {"},
  {"line":321,"text":"\t\tif shouldGetType(node) {"},
  {"line":322,"text":"\t\t\treturn typeToString(c.GetTypeAtLocation(node), container, typeFormatFlags), nil"},
  {"line":323,"text":"\t\t}"},
  {"line":324,"text":"\t\treturn \"\", nil"},
  {"line":325,"text":"\t}"},
  {"line":326,"text":"\tvar b strings.Builder"},
  {"line":327,"text":"\tvar visitedAliases collections.Set[*ast.Symbol]"},
  {"line":328,"text":"\tvar aliasLevel int"},
  {"line":329,"text":"\tvar firstDeclaration *ast.Node"},
  {"line":330,"text":"\tsetDeclaration := func(declaration *ast.Node) {"},
  {"line":331,"text":"\t\tif firstDeclaration == nil {"},
  {"line":332,"text":"\t\t\tfirstDeclaration = declaration"},
  {"line":333,"text":"\t\t}"},
  {"line":334,"text":"\t}"},
  {"line":335,"text":"\twriteNewLine := func() {"},
  {"line":336,"text":"\t\tif b.Len() != 0 {"},
  {"line":337,"text":"\t\t\tb.WriteString(\"\\n\")"},
  {"line":338,"text":"\t\t}"},
  {"line":339,"text":"\t\tif aliasLevel != 0 {"},
  {"line":340,"text":"\t\t\tb.WriteString(\"(alias) \")"},
  {"line":341,"text":"\t\t}"},
  {"line":342,"text":"\t}"},
  {"line":343,"text":"\twriteSignatures := func(signatures []*checker.Signature, prefix string, symbol *ast.Symbol) {"},
  {"line":344,"text":"\t\tfor i, sig := range signatures {"},
  {"line":345,"text":"\t\t\twriteNewLine()"},
  {"line":346,"text":"\t\t\tif i == 3 && len(signatures) >= 5 {"},
  {"line":347,"text":"\t\t\t\tb.WriteString(fmt.Sprintf(\"// +%v more overloads\", len(signatures)-3))"},
  {"line":348,"text":"\t\t\t\tbreak"},
  {"line":349,"text":"\t\t\t}"},
  {"line":350,"text":"\t\t\tb.WriteString(prefix)"},
  {"line":351,"text":"\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":352,"text":"\t\t\tif symbol.Flags&ast.SymbolFlagsOptional != 0 {"},
  {"line":353,"text":"\t\t\t\tb.WriteByte('?')"},
  {"line":354,"text":"\t\t\t}"},
  {"line":355,"text":"\t\t\tb.WriteString(signatureToString(sig, container, typeFormatFlags|checker.TypeFormatFlagsWriteCallStyleSignature|checker.TypeFormatFlagsWriteTypeArgumentsOfSignature))"},
  {"line":356,"text":"\t\t}"},
  {"line":357,"text":"\t}"},
  {"line":358,"text":"\twriteTypeParams := func(params []*checker.Type) {"},
  {"line":359,"text":"\t\tif len(params) > 0 {"},
  {"line":360,"text":"\t\t\tb.WriteString(\"<\")"},
  {"line":361,"text":"\t\t\tfor i, tp := range params {"},
  {"line":362,"text":"\t\t\t\tif i != 0 {"},
  {"line":363,"text":"\t\t\t\t\tb.WriteString(\", \")"},
  {"line":364,"text":"\t\t\t\t}"},
  {"line":365,"text":"\t\t\t\tb.WriteString(c.SymbolToStringEx(tp.Symbol(), nil, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":366,"text":"\t\t\t\tcons := c.GetConstraintOfTypeParameter(tp)"},
  {"line":367,"text":"\t\t\t\tif cons != nil {"},
  {"line":368,"text":"\t\t\t\t\tb.WriteString(\" extends \")"},
  {"line":369,"text":"\t\t\t\t\tb.WriteString(typeToString(cons, nil, typeFormatFlags))"},
  {"line":370,"text":"\t\t\t\t}"},
  {"line":371,"text":"\t\t\t\tdef := c.GetDefaultFromTypeParameter(tp)"},
  {"line":372,"text":"\t\t\t\tif def != nil {"},
  {"line":373,"text":"\t\t\t\t\tb.WriteString(\" = \")"},
  {"line":374,"text":"\t\t\t\t\tb.WriteString(typeToString(def, nil, typeFormatFlags))"},
  {"line":375,"text":"\t\t\t\t}"},
  {"line":376,"text":"\t\t\t}"},
  {"line":377,"text":"\t\t\tb.WriteString(\">\")"},
  {"line":378,"text":"\t\t}"},
  {"line":379,"text":"\t}"},
  {"line":380,"text":"\tsymbolWasExpanded := false"},
  {"line":381,"text":"\tcanExpandSymbol := func(symbol *ast.Symbol) bool {"},
  {"line":382,"text":"\t\tif vc == nil {"},
  {"line":383,"text":"\t\t\treturn false"},
  {"line":384,"text":"\t\t}"},
  {"line":388,"text":"\t\tif symbol.Flags&(ast.SymbolFlagsClass|ast.SymbolFlagsInterface|ast.SymbolFlagsNamespace) == 0 {"},
  {"line":389,"text":"\t\t\treturn false"},
  {"line":390,"text":"\t\t}"},
  {"line":391,"text":"\t\tvar t *checker.Type"},
  {"line":392,"text":"\t\tif symbol.Flags&(ast.SymbolFlagsClass|ast.SymbolFlagsInterface) != 0 {"},
  {"line":393,"text":"\t\t\tt = c.GetDeclaredTypeOfSymbol(symbol)"},
  {"line":394,"text":"\t\t} else {"},
  {"line":395,"text":"\t\t\tt = c.GetTypeOfSymbolAtLocation(symbol, node)"},
  {"line":396,"text":"\t\t}"},
  {"line":397,"text":"\t\tif t == nil || c.IsLibTypeForHoverVerbosity(t) {"},
  {"line":398,"text":"\t\t\treturn false"},
  {"line":399,"text":"\t\t}"},
  {"line":400,"text":"\t\tif vc.Level > 0 {"},
  {"line":401,"text":"\t\t\treturn true"},
  {"line":402,"text":"\t\t}"},
  {"line":404,"text":"\t\tvc.CanIncreaseVerbosity = true"},
  {"line":405,"text":"\t\treturn false"},
  {"line":406,"text":"\t}"},
  {"line":408,"text":"\ttryExpandSymbol := func(symbol *ast.Symbol, meaning ast.SymbolFlags) bool {"},
  {"line":409,"text":"\t\tif symbolWasExpanded {"},
  {"line":410,"text":"\t\t\treturn true"},
  {"line":411,"text":"\t\t}"},
  {"line":412,"text":"\t\tif canExpandSymbol(symbol) {"},
  {"line":413,"text":"\t\t\texpandVC := &checker.VerbosityContext{"},
  {"line":414,"text":"\t\t\t\tLevel:               vc.Level - 1,"},
  {"line":415,"text":"\t\t\t\tMaxTruncationLength: vc.MaxTruncationLength,"},
  {"line":416,"text":"\t\t\t}"},
  {"line":417,"text":"\t\t\texpanded := c.ExpandSymbolForHover(symbol, meaning, expandVC)"},
  {"line":418,"text":"\t\t\tif expanded != \"\" {"},
  {"line":419,"text":"\t\t\t\tvc.CanIncreaseVerbosity = vc.CanIncreaseVerbosity || expandVC.CanIncreaseVerbosity"},
  {"line":420,"text":"\t\t\t\tvc.Truncated = vc.Truncated || expandVC.Truncated"},
  {"line":421,"text":"\t\t\t\tb.WriteString(expanded)"},
  {"line":422,"text":"\t\t\t\tsymbolWasExpanded = true"},
  {"line":423,"text":"\t\t\t\treturn true"},
  {"line":424,"text":"\t\t\t}"},
  {"line":425,"text":"\t\t}"},
  {"line":426,"text":"\t\treturn false"},
  {"line":427,"text":"\t}"},
  {"line":428,"text":"\tvar writeSymbol func(*ast.Symbol)"},
  {"line":429,"text":"\twriteSymbol = func(symbol *ast.Symbol) {"},
  {"line":431,"text":"\t\tif symbol.Flags&ast.SymbolFlagsAlias != 0 && visitedAliases.AddIfAbsent(symbol) {"},
  {"line":432,"text":"\t\t\tif aliasedSymbol := c.GetAliasedSymbol(symbol); aliasedSymbol != c.GetUnknownSymbol() {"},
  {"line":433,"text":"\t\t\t\taliasLevel++"},
  {"line":434,"text":"\t\t\t\twriteSymbol(aliasedSymbol)"},
  {"line":435,"text":"\t\t\t\taliasLevel--"},
  {"line":436,"text":"\t\t\t}"},
  {"line":437,"text":"\t\t}"},
  {"line":438,"text":"\t\tvar flags ast.SymbolFlags"},
  {"line":439,"text":"\t\tswitch getMeaningFromLocation(node) {"},
  {"line":440,"text":"\t\tcase ast.SemanticMeaningValue:"},
  {"line":441,"text":"\t\t\tflags = symbol.Flags & (ast.SymbolFlagsValue | ast.SymbolFlagsSignature)"},
  {"line":442,"text":"\t\tcase ast.SemanticMeaningType:"},
  {"line":443,"text":"\t\t\tflags = symbol.Flags & ast.SymbolFlagsType"},
  {"line":444,"text":"\t\tcase ast.SemanticMeaningNamespace:"},
  {"line":445,"text":"\t\t\tflags = symbol.Flags & ast.SymbolFlagsNamespace"},
  {"line":446,"text":"\t\tdefault:"},
  {"line":447,"text":"\t\t\tflags = symbol.Flags & (ast.SymbolFlagsValue | ast.SymbolFlagsSignature | ast.SymbolFlagsType | ast.SymbolFlagsNamespace)"},
  {"line":448,"text":"\t\t}"},
  {"line":449,"text":"\t\tif flags == 0 {"},
  {"line":450,"text":"\t\t\tif aliasLevel != 0 || b.Len() != 0 {"},
  {"line":451,"text":"\t\t\t\treturn"},
  {"line":452,"text":"\t\t\t}"},
  {"line":453,"text":"\t\t\tflags = symbol.Flags & (ast.SymbolFlagsValue | ast.SymbolFlagsSignature | ast.SymbolFlagsType | ast.SymbolFlagsNamespace)"},
  {"line":454,"text":"\t\t\tif flags == 0 {"},
  {"line":455,"text":"\t\t\t\treturn"},
  {"line":456,"text":"\t\t\t}"},
  {"line":457,"text":"\t\t}"},
  {"line":458,"text":"\t\tif flags&ast.SymbolFlagsProperty != 0 && symbol.ValueDeclaration != nil && ast.IsMethodDeclaration(symbol.ValueDeclaration) {"},
  {"line":459,"text":"\t\t\tflags = ast.SymbolFlagsMethod"},
  {"line":460,"text":"\t\t}"},
  {"line":461,"text":"\t\tif flags&(ast.SymbolFlagsVariable|ast.SymbolFlagsProperty|ast.SymbolFlagsAccessor) != 0 {"},
  {"line":462,"text":"\t\t\twriteNewLine()"},
  {"line":463,"text":"\t\t\tif symbol.CheckFlags&ast.CheckFlagsIndexSymbol == 0 {"},
  {"line":464,"text":"\t\t\t\tswitch {"},
  {"line":465,"text":"\t\t\t\tcase flags&ast.SymbolFlagsProperty != 0:"},
  {"line":466,"text":"\t\t\t\t\tb.WriteString(\"(property) \")"},
  {"line":467,"text":"\t\t\t\tcase flags&ast.SymbolFlagsAccessor != 0:"},
  {"line":468,"text":"\t\t\t\t\tb.WriteString(\"(accessor) \")"},
  {"line":469,"text":"\t\t\t\tdefault:"},
  {"line":470,"text":"\t\t\t\t\tdecl := symbol.ValueDeclaration"},
  {"line":471,"text":"\t\t\t\t\tif decl != nil {"},
  {"line":472,"text":"\t\t\t\t\t\tdecl = ast.GetRootDeclaration(decl)"},
  {"line":473,"text":"\t\t\t\t\t\tswitch {"},
  {"line":474,"text":"\t\t\t\t\t\tcase ast.IsParameterDeclaration(decl):"},
  {"line":475,"text":"\t\t\t\t\t\t\tb.WriteString(\"(parameter) \")"},
  {"line":476,"text":"\t\t\t\t\t\tcase ast.IsVarLet(decl):"},
  {"line":477,"text":"\t\t\t\t\t\t\tb.WriteString(\"let \")"},
  {"line":478,"text":"\t\t\t\t\t\tcase ast.IsVarConst(decl):"},
  {"line":479,"text":"\t\t\t\t\t\t\tb.WriteString(\"const \")"},
  {"line":480,"text":"\t\t\t\t\t\tcase ast.IsVarUsing(decl):"},
  {"line":481,"text":"\t\t\t\t\t\t\tb.WriteString(\"using \")"},
  {"line":482,"text":"\t\t\t\t\t\tcase ast.IsVarAwaitUsing(decl):"},
  {"line":483,"text":"\t\t\t\t\t\t\tb.WriteString(\"await using \")"},
  {"line":484,"text":"\t\t\t\t\t\tdefault:"},
  {"line":485,"text":"\t\t\t\t\t\t\tb.WriteString(\"var \")"},
  {"line":486,"text":"\t\t\t\t\t\t}"},
  {"line":487,"text":"\t\t\t\t\t}"},
  {"line":488,"text":"\t\t\t\t}"},
  {"line":489,"text":"\t\t\t\tif symbol.Name == ast.InternalSymbolNameExportEquals && symbol.Parent != nil && symbol.Parent.Flags&ast.SymbolFlagsModule != 0 {"},
  {"line":490,"text":"\t\t\t\t\tb.WriteString(\"exports\")"},
  {"line":491,"text":"\t\t\t\t} else {"},
  {"line":492,"text":"\t\t\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":493,"text":"\t\t\t\t}"},
  {"line":494,"text":"\t\t\t\tif symbol.Flags&ast.SymbolFlagsOptional != 0 {"},
  {"line":495,"text":"\t\t\t\t\tb.WriteByte('?')"},
  {"line":496,"text":"\t\t\t\t}"},
  {"line":497,"text":"\t\t\t\tb.WriteString(\": \")"},
  {"line":498,"text":"\t\t\t}"},
  {"line":499,"text":"\t\t\tif callNode := getCallOrNewExpression(node); callNode != nil {"},
  {"line":500,"text":"\t\t\t\tflags := typeFormatFlags | checker.TypeFormatFlagsWriteTypeArgumentsOfSignature | checker.TypeFormatFlagsWriteArrowStyleSignature"},
  {"line":501,"text":"\t\t\t\tif ast.IsCallExpression(callNode) {"},
  {"line":502,"text":"\t\t\t\t\tflags |= checker.TypeFormatFlagsWriteCallStyleSignature"},
  {"line":503,"text":"\t\t\t\t}"},
  {"line":504,"text":"\t\t\t\tb.WriteString(signatureToString(c.GetResolvedSignature(callNode), container, flags))"},
  {"line":505,"text":"\t\t\t} else {"},
  {"line":506,"text":"\t\t\t\tt := c.GetTypeOfSymbolAtLocation(symbol, node)"},
  {"line":510,"text":"\t\t\t\tif vc != nil && t.Symbol() != nil && t.Symbol().Flags&ast.SymbolFlagsTypeParameter != 0 && c.GetConstraintOfTypeParameter(t) != nil {"},
  {"line":511,"text":"\t\t\t\t\tif vc.Level > 0 {"},
  {"line":512,"text":"\t\t\t\t\t\texpandVC := &checker.VerbosityContext{"},
  {"line":513,"text":"\t\t\t\t\t\t\tLevel:               vc.Level - 1,"},
  {"line":514,"text":"\t\t\t\t\t\t\tMaxTruncationLength: vc.MaxTruncationLength,"},
  {"line":515,"text":"\t\t\t\t\t\t}"},
  {"line":516,"text":"\t\t\t\t\t\tb.WriteString(typeParameterToString(c, t, container, expandVC))"},
  {"line":517,"text":"\t\t\t\t\t\tvc.CanIncreaseVerbosity = vc.CanIncreaseVerbosity || expandVC.CanIncreaseVerbosity"},
  {"line":518,"text":"\t\t\t\t\t\tvc.Truncated = vc.Truncated || expandVC.Truncated"},
  {"line":519,"text":"\t\t\t\t\t} else {"},
  {"line":520,"text":"\t\t\t\t\t\tb.WriteString(typeToString(t, container, typeFormatFlags))"},
  {"line":521,"text":"\t\t\t\t\t\tvc.CanIncreaseVerbosity = true"},
  {"line":522,"text":"\t\t\t\t\t}"},
  {"line":523,"text":"\t\t\t\t} else {"},
  {"line":524,"text":"\t\t\t\t\tb.WriteString(typeToString(t, container, typeFormatFlags))"},
  {"line":525,"text":"\t\t\t\t}"},
  {"line":526,"text":"\t\t\t}"},
  {"line":527,"text":"\t\t\tsetDeclaration(symbol.ValueDeclaration)"},
  {"line":528,"text":"\t\t}"},
  {"line":529,"text":"\t\tif flags&ast.SymbolFlagsEnumMember != 0 {"},
  {"line":530,"text":"\t\t\twriteNewLine()"},
  {"line":531,"text":"\t\t\tb.WriteString(\"(enum member) \")"},
  {"line":532,"text":"\t\t\tt := c.GetTypeOfSymbol(symbol)"},
  {"line":533,"text":"\t\t\tb.WriteString(typeToString(t, container, typeFormatFlags))"},
  {"line":534,"text":"\t\t\tif t.Flags()&checker.TypeFlagsLiteral != 0 {"},
  {"line":535,"text":"\t\t\t\tb.WriteString(\" = \")"},
  {"line":536,"text":"\t\t\t\tb.WriteString(t.AsLiteralType().String())"},
  {"line":537,"text":"\t\t\t}"},
  {"line":538,"text":"\t\t\tsetDeclaration(symbol.ValueDeclaration)"},
  {"line":539,"text":"\t\t}"},
  {"line":540,"text":"\t\tif flags&(ast.SymbolFlagsFunction|ast.SymbolFlagsMethod) != 0 {"},
  {"line":541,"text":"\t\t\tprefix := core.IfElse(flags&ast.SymbolFlagsMethod != 0, \"(method) \", \"function \")"},
  {"line":542,"text":"\t\t\tif ast.IsIdentifier(node) && (ast.IsFunctionLikeDeclaration(node.Parent) || ast.IsMethodSignatureDeclaration(node.Parent)) && node.Parent.Name() == node {"},
  {"line":543,"text":"\t\t\t\tsetDeclaration(node.Parent)"},
  {"line":544,"text":"\t\t\t\tsignatures := []*checker.Signature{c.GetSignatureFromDeclaration(node.Parent)}"},
  {"line":545,"text":"\t\t\t\twriteSignatures(signatures, prefix, symbol)"},
  {"line":546,"text":"\t\t\t} else {"},
  {"line":547,"text":"\t\t\t\tsignatures := getSignaturesAtLocation(c, symbol, checker.SignatureKindCall, node)"},
  {"line":548,"text":"\t\t\t\tif len(signatures) == 1 {"},
  {"line":549,"text":"\t\t\t\t\tif d := signatures[0].Declaration(); d != nil && d.Flags&ast.NodeFlagsJSDoc == 0 {"},
  {"line":550,"text":"\t\t\t\t\t\tsetDeclaration(d)"},
  {"line":551,"text":"\t\t\t\t\t}"},
  {"line":552,"text":"\t\t\t\t}"},
  {"line":553,"text":"\t\t\t\twriteSignatures(signatures, prefix, symbol)"},
  {"line":554,"text":"\t\t\t}"},
  {"line":555,"text":"\t\t\tsetDeclaration(symbol.ValueDeclaration)"},
  {"line":556,"text":"\t\t}"},
  {"line":557,"text":"\t\tif flags&(ast.SymbolFlagsClass|ast.SymbolFlagsInterface) != 0 {"},
  {"line":558,"text":"\t\t\tif node.Kind == ast.KindThisKeyword || ast.IsThisInTypeQuery(node) {"},
  {"line":559,"text":"\t\t\t\twriteNewLine()"},
  {"line":560,"text":"\t\t\t\tb.WriteString(\"this\")"},
  {"line":561,"text":"\t\t\t} else if node.Kind == ast.KindConstructorKeyword && (ast.IsConstructorDeclaration(node.Parent) || ast.IsConstructSignatureDeclaration(node.Parent)) {"},
  {"line":562,"text":"\t\t\t\tsetDeclaration(node.Parent)"},
  {"line":563,"text":"\t\t\t\tsignatures := []*checker.Signature{c.GetSignatureFromDeclaration(node.Parent)}"},
  {"line":564,"text":"\t\t\t\twriteSignatures(signatures, \"constructor \", symbol)"},
  {"line":565,"text":"\t\t\t} else {"},
  {"line":566,"text":"\t\t\t\tvar signatures []*checker.Signature"},
  {"line":567,"text":"\t\t\t\tif flags&ast.SymbolFlagsClass != 0 && getCallOrNewExpression(node) != nil {"},
  {"line":568,"text":"\t\t\t\t\tsignatures = getSignaturesAtLocation(c, symbol, checker.SignatureKindConstruct, node)"},
  {"line":569,"text":"\t\t\t\t}"},
  {"line":570,"text":"\t\t\t\tif len(signatures) == 1 {"},
  {"line":571,"text":"\t\t\t\t\tif d := signatures[0].Declaration(); d != nil && d.Flags&ast.NodeFlagsJSDoc == 0 {"},
  {"line":572,"text":"\t\t\t\t\t\tsetDeclaration(d)"},
  {"line":573,"text":"\t\t\t\t\t}"},
  {"line":574,"text":"\t\t\t\t\twriteSignatures(signatures, \"constructor \", symbol)"},
  {"line":575,"text":"\t\t\t\t} else {"},
  {"line":576,"text":"\t\t\t\t\twriteNewLine()"},
  {"line":577,"text":"\t\t\t\t\tif flags&ast.SymbolFlagsClass != 0 {"},
  {"line":578,"text":"\t\t\t\t\t\tclassExpression := ast.GetDeclarationOfKind(symbol, ast.KindClassExpression)"},
  {"line":579,"text":"\t\t\t\t\t\tif classExpression != nil {"},
  {"line":581,"text":"\t\t\t\t\t\t\tb.WriteString(\"(local class) \")"},
  {"line":582,"text":"\t\t\t\t\t\t}"},
  {"line":583,"text":"\t\t\t\t\t\tif !tryExpandSymbol(symbol, flags) {"},
  {"line":584,"text":"\t\t\t\t\t\t\tif classExpression == nil {"},
  {"line":585,"text":"\t\t\t\t\t\t\t\tif core.Some(symbol.Declarations, func(d *ast.Node) bool {"},
  {"line":586,"text":"\t\t\t\t\t\t\t\t\treturn ast.IsClassDeclaration(d) && ast.HasAbstractModifier(d)"},
  {"line":587,"text":"\t\t\t\t\t\t\t\t}) {"},
  {"line":588,"text":"\t\t\t\t\t\t\t\t\tb.WriteString(\"abstract \")"},
  {"line":589,"text":"\t\t\t\t\t\t\t\t}"},
  {"line":590,"text":"\t\t\t\t\t\t\t\tb.WriteString(\"class \")"},
  {"line":591,"text":"\t\t\t\t\t\t\t}"},
  {"line":592,"text":"\t\t\t\t\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":593,"text":"\t\t\t\t\t\t\tparams := c.GetDeclaredTypeOfSymbol(symbol).AsInterfaceType().LocalTypeParameters()"},
  {"line":594,"text":"\t\t\t\t\t\t\twriteTypeParams(params)"},
  {"line":595,"text":"\t\t\t\t\t\t}"},
  {"line":596,"text":"\t\t\t\t\t} else {"},
  {"line":597,"text":"\t\t\t\t\t\tif !tryExpandSymbol(symbol, flags) {"},
  {"line":598,"text":"\t\t\t\t\t\t\tb.WriteString(\"interface \")"},
  {"line":599,"text":"\t\t\t\t\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":600,"text":"\t\t\t\t\t\t\tparams := c.GetDeclaredTypeOfSymbol(symbol).AsInterfaceType().LocalTypeParameters()"},
  {"line":601,"text":"\t\t\t\t\t\t\twriteTypeParams(params)"},
  {"line":602,"text":"\t\t\t\t\t\t}"},
  {"line":603,"text":"\t\t\t\t\t}"},
  {"line":604,"text":"\t\t\t\t}"},
  {"line":605,"text":"\t\t\t}"},
  {"line":606,"text":"\t\t\tif flags&ast.SymbolFlagsClass != 0 {"},
  {"line":607,"text":"\t\t\t\tsetDeclaration(symbol.ValueDeclaration)"},
  {"line":608,"text":"\t\t\t} else {"},
  {"line":609,"text":"\t\t\t\tsetDeclaration(core.Find(symbol.Declarations, ast.IsInterfaceDeclaration))"},
  {"line":610,"text":"\t\t\t}"},
  {"line":611,"text":"\t\t}"},
  {"line":612,"text":"\t\tif flags&ast.SymbolFlagsEnum != 0 {"},
  {"line":613,"text":"\t\t\twriteNewLine()"},
  {"line":614,"text":"\t\t\tif !tryExpandSymbol(symbol, flags) {"},
  {"line":615,"text":"\t\t\t\tif core.Some(symbol.Declarations, func(d *ast.Node) bool {"},
  {"line":616,"text":"\t\t\t\t\treturn ast.IsEnumDeclaration(d) && ast.IsEnumConst(d)"},
  {"line":617,"text":"\t\t\t\t}) {"},
  {"line":618,"text":"\t\t\t\t\tb.WriteString(\"const \")"},
  {"line":619,"text":"\t\t\t\t}"},
  {"line":620,"text":"\t\t\t\tb.WriteString(\"enum \")"},
  {"line":621,"text":"\t\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":622,"text":"\t\t\t}"},
  {"line":623,"text":"\t\t\tsetDeclaration(core.Find(symbol.Declarations, ast.IsEnumDeclaration))"},
  {"line":624,"text":"\t\t}"},
  {"line":625,"text":"\t\tif flags&ast.SymbolFlagsModule != 0 {"},
  {"line":626,"text":"\t\t\twriteNewLine()"},
  {"line":627,"text":"\t\t\tif !tryExpandSymbol(symbol, flags) {"},
  {"line":628,"text":"\t\t\t\tisModule := symbol.ValueDeclaration != nil && (ast.IsSourceFile(symbol.ValueDeclaration) || ast.IsAmbientModule(symbol.ValueDeclaration))"},
  {"line":629,"text":"\t\t\t\tb.WriteString(core.IfElse(isModule, \"module \", \"namespace \"))"},
  {"line":630,"text":"\t\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":631,"text":"\t\t\t}"},
  {"line":632,"text":"\t\t\tsetDeclaration(core.Find(symbol.Declarations, ast.IsModuleDeclaration))"},
  {"line":633,"text":"\t\t}"},
  {"line":634,"text":"\t\tif flags&ast.SymbolFlagsTypeParameter != 0 {"},
  {"line":635,"text":"\t\t\twriteNewLine()"},
  {"line":636,"text":"\t\t\tb.WriteString(\"(type parameter) \")"},
  {"line":637,"text":"\t\t\ttp := c.GetDeclaredTypeOfSymbol(symbol)"},
  {"line":638,"text":"\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":639,"text":"\t\t\tcons := c.GetConstraintOfTypeParameter(tp)"},
  {"line":640,"text":"\t\t\tif cons != nil {"},
  {"line":641,"text":"\t\t\t\tb.WriteString(\" extends \")"},
  {"line":642,"text":"\t\t\t\tb.WriteString(typeToString(cons, container, typeFormatFlags))"},
  {"line":643,"text":"\t\t\t}"},
  {"line":645,"text":"\t\t\tif symbol.Parent != nil {"},
  {"line":647,"text":"\t\t\t\tb.WriteString(\" in \")"},
  {"line":648,"text":"\t\t\t\tb.WriteString(c.SymbolToStringEx(symbol.Parent, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":649,"text":"\t\t\t\tif parentType := c.GetDeclaredTypeOfSymbol(symbol.Parent); parentType.AsInterfaceType() != nil {"},
  {"line":650,"text":"\t\t\t\t\tparentParams := parentType.AsInterfaceType().LocalTypeParameters()"},
  {"line":651,"text":"\t\t\t\t\twriteTypeParams(parentParams)"},
  {"line":652,"text":"\t\t\t\t}"},
  {"line":653,"text":"\t\t\t} else {"},
  {"line":655,"text":"\t\t\t\tdecl := ast.GetDeclarationOfKind(symbol, ast.KindTypeParameter)"},
  {"line":656,"text":"\t\t\t\tif decl != nil && decl.Parent != nil {"},
  {"line":657,"text":"\t\t\t\t\tdeclaration := decl.Parent"},
  {"line":658,"text":"\t\t\t\t\tif ast.IsFunctionLike(declaration) {"},
  {"line":659,"text":"\t\t\t\t\t\tb.WriteString(\" in \")"},
  {"line":660,"text":"\t\t\t\t\t\tif declaration.Kind == ast.KindConstructSignature {"},
  {"line":661,"text":"\t\t\t\t\t\t\tb.WriteString(\"new \")"},
  {"line":662,"text":"\t\t\t\t\t\t} else if declaration.Kind != ast.KindCallSignature && declaration.Name() != nil {"},
  {"line":663,"text":"\t\t\t\t\t\t\tb.WriteString(c.SymbolToStringEx(declaration.Symbol(), container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":664,"text":"\t\t\t\t\t\t}"},
  {"line":665,"text":"\t\t\t\t\t\tsig := c.GetSignatureFromDeclaration(declaration)"},
  {"line":666,"text":"\t\t\t\t\t\tif sig != nil {"},
  {"line":667,"text":"\t\t\t\t\t\t\tb.WriteString(c.SignatureToStringEx(sig, container, typeFormatFlags|checker.TypeFormatFlagsWriteTypeArgumentsOfSignature, nil))"},
  {"line":668,"text":"\t\t\t\t\t\t}"},
  {"line":669,"text":"\t\t\t\t\t} else if ast.IsTypeAliasDeclaration(declaration) {"},
  {"line":670,"text":"\t\t\t\t\t\tb.WriteString(\" in type \")"},
  {"line":671,"text":"\t\t\t\t\t\tb.WriteString(c.SymbolToStringEx(declaration.Symbol(), container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":672,"text":"\t\t\t\t\t\tif declSymbol := declaration.Symbol(); declSymbol != nil {"},
  {"line":673,"text":"\t\t\t\t\t\t\ttaParams := c.GetTypeAliasTypeParameters(declSymbol)"},
  {"line":674,"text":"\t\t\t\t\t\t\twriteTypeParams(taParams)"},
  {"line":675,"text":"\t\t\t\t\t\t}"},
  {"line":676,"text":"\t\t\t\t\t}"},
  {"line":677,"text":"\t\t\t\t}"},
  {"line":678,"text":"\t\t\t}"},
  {"line":679,"text":"\t\t\tsetDeclaration(core.Find(symbol.Declarations, ast.IsTypeParameterDeclaration))"},
  {"line":680,"text":"\t\t}"},
  {"line":681,"text":"\t\tif flags&ast.SymbolFlagsTypeAlias != 0 {"},
  {"line":682,"text":"\t\t\twriteNewLine()"},
  {"line":683,"text":"\t\t\tb.WriteString(\"type \")"},
  {"line":684,"text":"\t\t\tb.WriteString(c.SymbolToStringEx(symbol, container, ast.SymbolFlagsNone, symbolFormatFlags))"},
  {"line":685,"text":"\t\t\twriteTypeParams(c.GetTypeAliasTypeParameters(symbol))"},
  {"line":686,"text":"\t\t\tif len(symbol.Declarations) != 0 {"},
  {"line":687,"text":"\t\t\t\tb.WriteString(\" = \")"},
  {"line":688,"text":"\t\t\t\tvar typeAliasType *checker.Type"},
  {"line":689,"text":"\t\t\t\tif node.Parent != nil && ast.IsConstTypeReference(node.Parent) {"},
  {"line":690,"text":"\t\t\t\t\ttypeAliasType = c.GetTypeAtLocation(node.Parent)"},
  {"line":691,"text":"\t\t\t\t} else {"},
  {"line":692,"text":"\t\t\t\t\ttypeAliasType = c.GetDeclaredTypeOfSymbol(symbol)"},
  {"line":693,"text":"\t\t\t\t}"},
  {"line":694,"text":"\t\t\t\tb.WriteString(typeToString(typeAliasType, container, typeFormatFlags|checker.TypeFormatFlagsInTypeAlias))"},
  {"line":695,"text":"\t\t\t}"},
  {"line":696,"text":"\t\t\tsetDeclaration(core.Find(symbol.Declarations, ast.IsTypeOrJSTypeAliasDeclaration))"},
  {"line":697,"text":"\t\t}"},
  {"line":698,"text":"\t\tif flags&ast.SymbolFlagsSignature != 0 {"},
  {"line":699,"text":"\t\t\twriteNewLine()"},
  {"line":700,"text":"\t\t\tb.WriteString(typeToString(c.GetTypeOfSymbol(symbol), container, typeFormatFlags))"},
  {"line":701,"text":"\t\t}"},
  {"line":702,"text":"\t}"},
  {"line":703,"text":"\twriteSymbol(symbol)"},
  {"line":705,"text":"\treturn b.String(), firstDeclaration"},
  {"line":706,"text":"}"},
  {"line":709,"text":"func typeParameterToString(c *checker.Checker, t *checker.Type, enclosingDeclaration *ast.Node, vc *checker.VerbosityContext) string {"},
  {"line":710,"text":"\treturn c.TypeParameterToStringEx(t, enclosingDeclaration, vc)"},
  {"line":711,"text":"}"},
  {"line":713,"text":"func getNodeForQuickInfo(node *ast.Node) *ast.Node {"},
  {"line":714,"text":"\tif node.Parent == nil {"},
  {"line":715,"text":"\t\treturn node"},
  {"line":716,"text":"\t}"},
  {"line":717,"text":"\tif ast.IsNewExpression(node.Parent) && node.Pos() == node.Parent.Pos() {"},
  {"line":718,"text":"\t\treturn node.Parent.Expression()"},
  {"line":719,"text":"\t}"},
  {"line":720,"text":"\tif ast.IsNamedTupleMember(node.Parent) && node.Pos() == node.Parent.Pos() {"},
  {"line":721,"text":"\t\treturn node.Parent"},
  {"line":722,"text":"\t}"},
  {"line":723,"text":"\tif ast.IsImportMeta(node.Parent) && node.Parent.Name() == node {"},
  {"line":724,"text":"\t\treturn node.Parent"},
  {"line":725,"text":"\t}"},
  {"line":726,"text":"\tif ast.IsJsxNamespacedName(node.Parent) {"},
  {"line":727,"text":"\t\treturn node.Parent"},
  {"line":728,"text":"\t}"},
  {"line":729,"text":"\treturn node"},
  {"line":730,"text":"}"},
  {"line":732,"text":"func getSymbolAtLocationForQuickInfo(c *checker.Checker, node *ast.Node) *ast.Symbol {"},
  {"line":733,"text":"\tif objectElement := getContainingObjectLiteralElement(node); objectElement != nil {"},
  {"line":734,"text":"\t\tif contextualType := c.GetContextualType(objectElement.Parent, checker.ContextFlagsNone); contextualType != nil {"},
  {"line":735,"text":"\t\t\tif properties := c.GetPropertySymbolsFromContextualType(objectElement, contextualType, false /*unionSymbolOk*/); len(properties) == 1 {"},
  {"line":736,"text":"\t\t\t\treturn properties[0]"},
  {"line":737,"text":"\t\t\t}"},
  {"line":738,"text":"\t\t}"},
  {"line":739,"text":"\t}"},
  {"line":740,"text":"\treturn c.GetSymbolAtLocation(node)"},
  {"line":741,"text":"}"},
  {"line":743,"text":"func getSignaturesAtLocation(c *checker.Checker, symbol *ast.Symbol, kind checker.SignatureKind, node *ast.Node) []*checker.Signature {"},
  {"line":744,"text":"\tsignatures := c.GetSignaturesOfType(c.RemoveMissingOrUndefinedType(c.GetTypeOfSymbol(symbol)), kind)"},
  {"line":745,"text":"\tif len(signatures) > 1 || len(signatures) == 1 && len(signatures[0].TypeParameters()) != 0 {"},
  {"line":746,"text":"\t\tif callNode := getCallOrNewExpression(node); callNode != nil {"},
  {"line":748,"text":"\t\t\treturn []*checker.Signature{c.GetResolvedSignature(callNode)}"},
  {"line":749,"text":"\t\t}"},
  {"line":750,"text":"\t}"},
  {"line":751,"text":"\treturn signatures"},
  {"line":752,"text":"}"},
  {"line":754,"text":"func getCallOrNewExpression(node *ast.Node) *ast.Node {"},
  {"line":755,"text":"\tif ast.IsSourceFile(node) {"},
  {"line":756,"text":"\t\treturn nil"},
  {"line":757,"text":"\t}"},
  {"line":758,"text":"\tif ast.IsPropertyAccessExpression(node.Parent) && node.Parent.Name() == node {"},
  {"line":759,"text":"\t\tnode = node.Parent"},
  {"line":760,"text":"\t}"},
  {"line":761,"text":"\tif (ast.IsCallExpression(node.Parent) || ast.IsNewExpression(node.Parent)) && node.Parent.Expression() == node {"},
  {"line":762,"text":"\t\treturn node.Parent"},
  {"line":763,"text":"\t}"},
  {"line":764,"text":"\treturn nil"},
  {"line":765,"text":"}"},
  {"line":767,"text":"func containsTypedefTag(jsdoc *ast.Node) bool {"},
  {"line":768,"text":"\tif jsdoc.Kind == ast.KindJSDoc {"},
  {"line":769,"text":"\t\tif tags := jsdoc.AsJSDoc().Tags; tags != nil {"},
  {"line":770,"text":"\t\t\tfor _, tag := range tags.Nodes {"},
  {"line":771,"text":"\t\t\t\tif tag.Kind == ast.KindJSDocTypedefTag || tag.Kind == ast.KindJSDocCallbackTag {"},
  {"line":772,"text":"\t\t\t\t\treturn true"},
  {"line":773,"text":"\t\t\t\t}"},
  {"line":774,"text":"\t\t\t}"},
  {"line":775,"text":"\t\t}"},
  {"line":776,"text":"\t}"},
  {"line":777,"text":"\treturn false"},
  {"line":778,"text":"}"},
  {"line":780,"text":"func getJSDoc(node *ast.Node) *ast.Node {"},
  {"line":781,"text":"\treturn core.LastOrNil(node.JSDoc(nil))"},
  {"line":782,"text":"}"},
  {"line":784,"text":"func getJSDocOrTag(c *checker.Checker, node *ast.Node) *ast.Node {"},
  {"line":785,"text":"\tif jsdoc := getJSDoc(node); jsdoc != nil {"},
  {"line":786,"text":"\t\treturn jsdoc"},
  {"line":787,"text":"\t}"},
  {"line":788,"text":"\tswitch {"},
  {"line":789,"text":"\tcase ast.IsParameterDeclaration(node):"},
  {"line":790,"text":"\t\tname := node.Name()"},
  {"line":791,"text":"\t\tif ast.IsBindingPattern(name) {"},
  {"line":793,"text":"\t\t\treturn getJSDocParameterTagByPosition(c, node)"},
  {"line":794,"text":"\t\t}"},
  {"line":795,"text":"\t\treturn getMatchingJSDocTag(c, node.Parent, name.Text(), isMatchingParameterTag)"},
  {"line":796,"text":"\tcase ast.IsTypeParameterDeclaration(node):"},
  {"line":797,"text":"\t\treturn getMatchingJSDocTag(c, node.Parent, node.Name().Text(), isMatchingTemplateTag)"},
  {"line":798,"text":"\tcase ast.IsVariableDeclaration(node) && ast.IsVariableDeclarationList(node.Parent) && core.FirstOrNil(node.Parent.AsVariableDeclarationList().Declarations.Nodes) == node:"},
  {"line":799,"text":"\t\treturn getJSDocOrTag(c, node.Parent.Parent)"},
  {"line":800,"text":"\tcase (ast.IsFunctionExpressionOrArrowFunction(node) || ast.IsClassExpression(node)) &&"},
  {"line":801,"text":"\t\t(ast.IsVariableDeclaration(node.Parent) || ast.IsPropertyDeclaration(node.Parent) || ast.IsPropertyAssignment(node.Parent)) && node.Parent.Initializer() == node:"},
  {"line":802,"text":"\t\treturn getJSDocOrTag(c, node.Parent)"},
  {"line":803,"text":"\t}"},
  {"line":804,"text":"\tif symbol := node.Symbol(); symbol != nil && node.Parent != nil {"},
  {"line":805,"text":"\t\tif ast.IsFunctionDeclaration(node) || ast.IsMethodDeclaration(node) || ast.IsMethodSignatureDeclaration(node) || ast.IsConstructorDeclaration(node) || ast.IsConstructSignatureDeclaration(node) {"},
  {"line":806,"text":"\t\t\tfirstSignature := core.Find(symbol.Declarations, ast.IsFunctionLike)"},
  {"line":807,"text":"\t\t\tif firstSignature != nil && node != firstSignature {"},
  {"line":808,"text":"\t\t\t\tif jsDoc := getJSDocOrTag(c, firstSignature); jsDoc != nil {"},
  {"line":809,"text":"\t\t\t\t\treturn jsDoc"},
  {"line":810,"text":"\t\t\t\t}"},
  {"line":811,"text":"\t\t\t}"},
  {"line":812,"text":"\t\t}"},
  {"line":813,"text":"\t\tif ast.IsClassOrInterfaceLike(node.Parent) {"},
  {"line":814,"text":"\t\t\tisStatic := ast.HasStaticModifier(node)"},
  {"line":815,"text":"\t\t\tclassType := c.GetDeclaredTypeOfSymbol(node.Parent.Symbol())"},
  {"line":816,"text":"\t\t\tif isStatic {"},
  {"line":820,"text":"\t\t\t\tstaticBaseType := c.GetApparentType(c.GetBaseConstructorTypeOfClass(classType))"},
  {"line":821,"text":"\t\t\t\tif prop := c.GetPropertyOfType(staticBaseType, symbol.Name); prop != nil && prop.ValueDeclaration != nil {"},
  {"line":822,"text":"\t\t\t\t\tif jsDoc := getJSDocOrTag(c, prop.ValueDeclaration); jsDoc != nil {"},
  {"line":823,"text":"\t\t\t\t\t\treturn jsDoc"},
  {"line":824,"text":"\t\t\t\t\t}"},
  {"line":825,"text":"\t\t\t\t}"},
  {"line":826,"text":"\t\t\t} else {"},
  {"line":827,"text":"\t\t\t\tfor _, baseType := range c.GetBaseTypes(classType) {"},
  {"line":828,"text":"\t\t\t\t\tif prop := c.GetPropertyOfType(baseType, symbol.Name); prop != nil && prop.ValueDeclaration != nil {"},
  {"line":829,"text":"\t\t\t\t\t\tif jsDoc := getJSDocOrTag(c, prop.ValueDeclaration); jsDoc != nil {"},
  {"line":830,"text":"\t\t\t\t\t\t\treturn jsDoc"},
  {"line":831,"text":"\t\t\t\t\t\t}"},
  {"line":832,"text":"\t\t\t\t\t}"},
  {"line":833,"text":"\t\t\t\t}"},
  {"line":834,"text":"\t\t\t}"},
  {"line":835,"text":"\t\t}"},
  {"line":836,"text":"\t}"},
  {"line":837,"text":"\treturn nil"},
  {"line":838,"text":"}"},
  {"line":840,"text":"func getMatchingJSDocTag(c *checker.Checker, node *ast.Node, name string, match func(*ast.Node, string) bool) *ast.Node {"},
  {"line":841,"text":"\tif jsdoc := getJSDocOrTag(c, node); jsdoc != nil && jsdoc.Kind == ast.KindJSDoc {"},
  {"line":842,"text":"\t\tif tags := jsdoc.AsJSDoc().Tags; tags != nil {"},
  {"line":843,"text":"\t\t\tfor _, tag := range tags.Nodes {"},
  {"line":844,"text":"\t\t\t\tif match(tag, name) {"},
  {"line":845,"text":"\t\t\t\t\treturn tag"},
  {"line":846,"text":"\t\t\t\t}"},
  {"line":847,"text":"\t\t\t}"},
  {"line":848,"text":"\t\t}"},
  {"line":849,"text":"\t}"},
  {"line":850,"text":"\treturn nil"},
  {"line":851,"text":"}"},
  {"line":855,"text":"func getJSDocParameterTagByPosition(c *checker.Checker, param *ast.Node) *ast.Node {"},
  {"line":856,"text":"\tparent := param.Parent"},
  {"line":857,"text":"\tif parent == nil {"},
  {"line":858,"text":"\t\treturn nil"},
  {"line":859,"text":"\t}"},
  {"line":862,"text":"\tparams := parent.Parameters()"},
  {"line":863,"text":"\tparamIndex := -1"},
  {"line":864,"text":"\tfor i, p := range params {"},
  {"line":865,"text":"\t\tif p.AsNode() == param {"},
  {"line":866,"text":"\t\t\tparamIndex = i"},
  {"line":867,"text":"\t\t\tbreak"},
  {"line":868,"text":"\t\t}"},
  {"line":869,"text":"\t}"},
  {"line":870,"text":"\tif paramIndex < 0 {"},
  {"line":871,"text":"\t\treturn nil"},
  {"line":872,"text":"\t}"},
  {"line":875,"text":"\tjsdoc := getJSDocOrTag(c, parent)"},
  {"line":876,"text":"\tif jsdoc == nil || jsdoc.Kind != ast.KindJSDoc {"},
  {"line":877,"text":"\t\treturn nil"},
  {"line":878,"text":"\t}"},
  {"line":881,"text":"\ttags := jsdoc.AsJSDoc().Tags"},
  {"line":882,"text":"\tif tags == nil {"},
  {"line":883,"text":"\t\treturn nil"},
  {"line":884,"text":"\t}"},
  {"line":886,"text":"\tparamTagIndex := 0"},
  {"line":887,"text":"\tfor _, tag := range tags.Nodes {"},
  {"line":888,"text":"\t\tif tag.Kind == ast.KindJSDocParameterTag {"},
  {"line":889,"text":"\t\t\tif paramTagIndex == paramIndex {"},
  {"line":890,"text":"\t\t\t\treturn tag"},
  {"line":891,"text":"\t\t\t}"},
  {"line":892,"text":"\t\t\tparamTagIndex++"},
  {"line":893,"text":"\t\t}"},
  {"line":894,"text":"\t}"},
  {"line":895,"text":"\treturn nil"},
  {"line":896,"text":"}"},
  {"line":898,"text":"func isMatchingParameterTag(tag *ast.Node, name string) bool {"},
  {"line":899,"text":"\treturn tag.Kind == ast.KindJSDocParameterTag && isNodeWithName(tag, name)"},
  {"line":900,"text":"}"},
  {"line":902,"text":"func isMatchingTemplateTag(tag *ast.Node, name string) bool {"},
  {"line":903,"text":"\treturn tag.Kind == ast.KindJSDocTemplateTag && core.Some(tag.TypeParameters(), func(tp *ast.Node) bool { return isNodeWithName(tp, name) })"},
  {"line":904,"text":"}"},
  {"line":906,"text":"func isNodeWithName(node *ast.Node, name string) bool {"},
  {"line":907,"text":"\tnodeName := node.Name()"},
  {"line":908,"text":"\treturn ast.IsIdentifier(nodeName) && nodeName.Text() == name"},
  {"line":909,"text":"}"},
  {"line":911,"text":"func writeCode(b *strings.Builder, lang string, code string) {"},
  {"line":912,"text":"\tif code == \"\" {"},
  {"line":913,"text":"\t\treturn"},
  {"line":914,"text":"\t}"},
  {"line":915,"text":"\tticks := 3"},
  {"line":916,"text":"\tfor strings.Contains(code, strings.Repeat(\"`\", ticks)) {"},
  {"line":917,"text":"\t\tticks++"},
  {"line":918,"text":"\t}"},
  {"line":919,"text":"\tfor range ticks {"},
  {"line":920,"text":"\t\tb.WriteByte('`')"},
  {"line":921,"text":"\t}"},
  {"line":922,"text":"\tb.WriteString(lang)"},
  {"line":923,"text":"\tb.WriteByte('\\n')"},
  {"line":924,"text":"\tb.WriteString(code)"},
  {"line":925,"text":"\tb.WriteByte('\\n')"},
  {"line":926,"text":"\tfor range ticks {"},
  {"line":927,"text":"\t\tb.WriteByte('`')"},
  {"line":928,"text":"\t}"},
  {"line":929,"text":"\tb.WriteByte('\\n')"},
  {"line":930,"text":"}"},
  {"line":932,"text":"func (l *LanguageService) writeComments(b *strings.Builder, c *checker.Checker, comments []*ast.Node, isMarkdown bool) {"},
  {"line":933,"text":"\tfor _, comment := range comments {"},
  {"line":934,"text":"\t\tswitch comment.Kind {"},
  {"line":935,"text":"\t\tcase ast.KindJSDocText:"},
  {"line":936,"text":"\t\t\tb.WriteString(comment.Text())"},
  {"line":937,"text":"\t\tcase ast.KindJSDocLink, ast.KindJSDocLinkPlain:"},
  {"line":938,"text":"\t\t\tl.writeJSDocLink(b, c, comment, false /*quote*/, isMarkdown)"},
  {"line":939,"text":"\t\tcase ast.KindJSDocLinkCode:"},
  {"line":940,"text":"\t\t\tl.writeJSDocLink(b, c, comment, true /*quote*/, isMarkdown)"},
  {"line":941,"text":"\t\t}"},
  {"line":942,"text":"\t}"},
  {"line":943,"text":"}"},
  {"line":945,"text":"func (l *LanguageService) writeJSDocLink(b *strings.Builder, c *checker.Checker, link *ast.Node, quote bool, isMarkdown bool) {"},
  {"line":946,"text":"\tname := link.Name()"},
  {"line":947,"text":"\ttext := strings.Trim(link.Text(), \" \")"},
  {"line":948,"text":"\tif name == nil {"},
  {"line":949,"text":"\t\twriteQuotedString(b, text, quote && isMarkdown)"},
  {"line":950,"text":"\t\treturn"},
  {"line":951,"text":"\t}"},
  {"line":952,"text":"\tif ast.IsIdentifier(name) && (name.Text() == \"http\" || name.Text() == \"https\") && strings.HasPrefix(text, \"://\") {"},
  {"line":953,"text":"\t\tlinkText := name.Text() + text"},
  {"line":954,"text":"\t\tlinkUri := linkText"},
  {"line":955,"text":"\t\tif commentPos := strings.IndexFunc(linkText, func(ch rune) bool { return ch == ' ' || ch == '|' }); commentPos >= 0 {"},
  {"line":956,"text":"\t\t\tlinkUri = linkText[:commentPos]"},
  {"line":957,"text":"\t\t\tlinkText = trimCommentPrefix(linkText[commentPos:])"},
  {"line":958,"text":"\t\t\tif linkText == \"\" {"},
  {"line":959,"text":"\t\t\t\tlinkText = linkUri"},
  {"line":960,"text":"\t\t\t}"},
  {"line":961,"text":"\t\t}"},
  {"line":962,"text":"\t\tif isMarkdown {"},
  {"line":963,"text":"\t\t\twriteMarkdownLink(b, linkText, linkUri, quote)"},
  {"line":964,"text":"\t\t} else {"},
  {"line":965,"text":"\t\t\twriteQuotedString(b, linkText, false)"},
  {"line":966,"text":"\t\t\tif linkText != linkUri {"},
  {"line":967,"text":"\t\t\t\tb.WriteString(\" (\")"},
  {"line":968,"text":"\t\t\t\tb.WriteString(linkUri)"},
  {"line":969,"text":"\t\t\t\tb.WriteString(\")\")"},
  {"line":970,"text":"\t\t\t}"},
  {"line":971,"text":"\t\t}"},
  {"line":972,"text":"\t\treturn"},
  {"line":973,"text":"\t}"},
  {"line":974,"text":"\tl.writeNameLink(b, c, name, text, quote, isMarkdown)"},
  {"line":975,"text":"}"},
  {"line":977,"text":"func (l *LanguageService) writeNameLink(b *strings.Builder, c *checker.Checker, name *ast.Node, text string, quote bool, isMarkdown bool) {"},
  {"line":978,"text":"\tdeclarations := getDeclarationsFromLocation(c, name)"},
  {"line":979,"text":"\tif len(declarations) != 0 {"},
  {"line":980,"text":"\t\tdeclaration := declarations[0]"},
  {"line":981,"text":"\t\tfile := ast.GetSourceFileOfNode(declaration)"},
  {"line":982,"text":"\t\tnode := core.OrElse(ast.GetNameOfDeclaration(declaration), declaration)"},
  {"line":983,"text":"\t\tloc := l.getMappedLocation(file.FileName(), createRangeFromNode(node, file))"},
  {"line":984,"text":"\t\tprefixLen := core.IfElse(strings.HasPrefix(text, \"()\"), 2, 0)"},
  {"line":985,"text":"\t\tlinkText := trimCommentPrefix(text[prefixLen:])"},
  {"line":986,"text":"\t\tif linkText == \"\" {"},
  {"line":987,"text":"\t\t\tlinkText = getEntityNameString(name) + text[:prefixLen]"},
  {"line":988,"text":"\t\t}"},
  {"line":989,"text":"\t\tif isMarkdown {"},
  {"line":990,"text":"\t\t\tlinkUri := fmt.Sprintf(\"%s#%d,%d-%d,%d\", loc.Uri, loc.Range.Start.Line+1, loc.Range.Start.Character+1, loc.Range.End.Line+1, loc.Range.End.Character+1)"},
  {"line":991,"text":"\t\t\twriteMarkdownLink(b, linkText, linkUri, quote)"},
  {"line":992,"text":"\t\t} else {"},
  {"line":993,"text":"\t\t\twriteQuotedString(b, linkText, false)"},
  {"line":994,"text":"\t\t}"},
  {"line":995,"text":"\t\treturn"},
  {"line":996,"text":"\t}"},
  {"line":997,"text":"\twriteQuotedString(b, getEntityNameString(name)+core.IfElse(len(text) != 0, \" \", \"\")+text, quote && isMarkdown)"},
  {"line":998,"text":"}"},
  {"line":1000,"text":"func trimCommentPrefix(text string) string {"},
  {"line":1001,"text":"\treturn strings.TrimLeft(strings.TrimPrefix(strings.TrimLeft(text, \" \"), \"|\"), \" \")"},
  {"line":1002,"text":"}"},
  {"line":1004,"text":"func writeMarkdownLink(b *strings.Builder, text string, uri string, quote bool) {"},
  {"line":1005,"text":"\tb.WriteString(\"[\")"},
  {"line":1006,"text":"\twriteQuotedString(b, text, quote)"},
  {"line":1007,"text":"\tb.WriteString(\"](\")"},
  {"line":1008,"text":"\tb.WriteString(uri)"},
  {"line":1009,"text":"\tb.WriteString(\")\")"},
  {"line":1010,"text":"}"},
  {"line":1012,"text":"func writeOptionalEntityName(b *strings.Builder, name *ast.Node) {"},
  {"line":1013,"text":"\tif name != nil {"},
  {"line":1014,"text":"\t\tb.WriteString(\" \")"},
  {"line":1015,"text":"\t\twriteQuotedString(b, getEntityNameString(name), true /*quote*/)"},
  {"line":1016,"text":"\t}"},
  {"line":1017,"text":"}"},
  {"line":1019,"text":"func writeQuotedString(b *strings.Builder, str string, quote bool) {"},
  {"line":1020,"text":"\tif quote && !strings.Contains(str, \"`\") {"},
  {"line":1021,"text":"\t\tb.WriteString(\"`\")"},
  {"line":1022,"text":"\t\tb.WriteString(str)"},
  {"line":1023,"text":"\t\tb.WriteString(\"`\")"},
  {"line":1024,"text":"\t} else {"},
  {"line":1025,"text":"\t\tb.WriteString(str)"},
  {"line":1026,"text":"\t}"},
  {"line":1027,"text":"}"},
  {"line":1030,"text":"func findPropertyInType(c *checker.Checker, objectType *checker.Type, propertyName string) *ast.Symbol {"},
  {"line":1032,"text":"\tif objectType.IsUnion() {"},
  {"line":1033,"text":"\t\tfor _, t := range objectType.Types() {"},
  {"line":1034,"text":"\t\t\tif prop := c.GetPropertyOfType(t, propertyName); prop != nil {"},
  {"line":1035,"text":"\t\t\t\treturn prop"},
  {"line":1036,"text":"\t\t\t}"},
  {"line":1037,"text":"\t\t}"},
  {"line":1038,"text":"\t\treturn nil"},
  {"line":1039,"text":"\t}"},
  {"line":1040,"text":"\treturn c.GetPropertyOfType(objectType, propertyName)"},
  {"line":1041,"text":"}"},
  {"line":1043,"text":"func getEntityNameString(name *ast.Node) string {"},
  {"line":1044,"text":"\tvar b strings.Builder"},
  {"line":1045,"text":"\twriteEntityNameParts(&b, name)"},
  {"line":1046,"text":"\treturn b.String()"},
  {"line":1047,"text":"}"},
  {"line":1049,"text":"func writeEntityNameParts(b *strings.Builder, node *ast.Node) {"},
  {"line":1050,"text":"\tswitch node.Kind {"},
  {"line":1051,"text":"\tcase ast.KindIdentifier:"},
  {"line":1052,"text":"\t\tb.WriteString(node.Text())"},
  {"line":1053,"text":"\tcase ast.KindQualifiedName:"},
  {"line":1054,"text":"\t\twriteEntityNameParts(b, node.AsQualifiedName().Left)"},
  {"line":1055,"text":"\t\tb.WriteByte('.')"},
  {"line":1056,"text":"\t\twriteEntityNameParts(b, node.AsQualifiedName().Right)"},
  {"line":1057,"text":"\tcase ast.KindPropertyAccessExpression:"},
  {"line":1058,"text":"\t\twriteEntityNameParts(b, node.Expression())"},
  {"line":1059,"text":"\t\tb.WriteByte('.')"},
  {"line":1060,"text":"\t\twriteEntityNameParts(b, node.Name())"},
  {"line":1061,"text":"\tcase ast.KindParenthesizedExpression, ast.KindExpressionWithTypeArguments:"},
  {"line":1062,"text":"\t\twriteEntityNameParts(b, node.Expression())"},
  {"line":1063,"text":"\tcase ast.KindJSDocNameReference:"},
  {"line":1064,"text":"\t\twriteEntityNameParts(b, node.Name())"},
  {"line":1065,"text":"\t}"},
  {"line":1066,"text":"}"},
];

export function findLsHoverDeclaration(name: string): UpstreamDeclaration | undefined {
  return lsHoverDeclarations.find((declaration) => declaration.name === name);
}

export function requireLsHoverDeclaration(name: string): UpstreamDeclaration {
  const declaration = findLsHoverDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function lsHoverLineText(line: number): string | undefined {
  return lsHoverSourceLines.find((entry) => entry.line === line)?.text;
}
