/**
 * Language-service parity map for TS-Go `ls/importTracker.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerUpstreamPath = "ls/importTracker.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerDeclarations: readonly UpstreamDeclaration[] = [
  {"line":15,"kind":"type","name":"ImpExpKind"},
  {"line":23,"kind":"type","name":"ImportExportSymbol"},
  {"line":29,"kind":"type","name":"ExportKind"},
  {"line":39,"kind":"type","name":"ExportInfo"},
  {"line":44,"kind":"type","name":"LocationAndSymbol"},
  {"line":49,"kind":"type","name":"ImportsResult"},
  {"line":55,"kind":"type","name":"ImportTracker"},
  {"line":57,"kind":"type","name":"ModuleReferenceKind"},
  {"line":66,"kind":"type","name":"ModuleReference"},
  {"line":74,"kind":"func","name":"createImportTracker"},
  {"line":84,"kind":"func","name":"getDirectImportsMap"},
  {"line":100,"kind":"func","name":"forEachImport"},
  {"line":134,"kind":"func","name":"forEachPossibleImportOrExportStatement"},
  {"line":143,"kind":"func","name":"getSourceFileLikeForImportDeclaration"},
  {"line":155,"kind":"func","name":"isAmbientModuleDeclaration"},
  {"line":159,"kind":"func","name":"getStatementsOfSourceFileLike"},
  {"line":169,"kind":"func","name":"getImportersForExport"},
  {"line":324,"kind":"func","name":"getContainingModuleSymbol"},
  {"line":329,"kind":"func","name":"findNamespaceReExports"},
  {"line":343,"kind":"func","name":"getSearchesFromDirectImports"},
  {"line":462,"kind":"func","name":"getImportOrExportSymbol"},
  {"line":611,"kind":"func","name":"getExportInfo"},
  {"line":628,"kind":"func","name":"getExportNode"},
  {"line":645,"kind":"func","name":"isNodeImport"},
  {"line":662,"kind":"func","name":"isExternalModuleImportEquals"},
  {"line":668,"kind":"func","name":"skipExportSpecifierSymbol"},
  {"line":684,"kind":"func","name":"getExportEqualsLocalSymbol"},
  {"line":701,"kind":"func","name":"symbolNameNoDefault"},
  {"line":716,"kind":"func","name":"findModuleReferences"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/debug\""},
  {"line":13,"text":")"},
  {"line":15,"text":"type ImpExpKind int32"},
  {"line":17,"text":"const ("},
  {"line":18,"text":"\tImpExpKindUnknown ImpExpKind = iota"},
  {"line":19,"text":"\tImpExpKindImport"},
  {"line":20,"text":"\tImpExpKindExport"},
  {"line":21,"text":")"},
  {"line":23,"text":"type ImportExportSymbol struct {"},
  {"line":24,"text":"\tkind       ImpExpKind"},
  {"line":25,"text":"\tsymbol     *ast.Symbol"},
  {"line":26,"text":"\texportInfo *ExportInfo"},
  {"line":27,"text":"}"},
  {"line":29,"text":"type ExportKind int"},
  {"line":31,"text":"const ("},
  {"line":32,"text":"\tExportKindNamed        ExportKind = 0"},
  {"line":33,"text":"\tExportKindDefault      ExportKind = 1"},
  {"line":34,"text":"\tExportKindExportEquals ExportKind = 2"},
  {"line":35,"text":"\tExportKindUMD          ExportKind = 3"},
  {"line":36,"text":"\tExportKindModule       ExportKind = 4"},
  {"line":37,"text":")"},
  {"line":39,"text":"type ExportInfo struct {"},
  {"line":40,"text":"\texportingModuleSymbol *ast.Symbol"},
  {"line":41,"text":"\texportKind            ExportKind"},
  {"line":42,"text":"}"},
  {"line":44,"text":"type LocationAndSymbol struct {"},
  {"line":45,"text":"\timportLocation *ast.Node"},
  {"line":46,"text":"\timportSymbol   *ast.Symbol"},
  {"line":47,"text":"}"},
  {"line":49,"text":"type ImportsResult struct {"},
  {"line":50,"text":"\timportSearches   []LocationAndSymbol"},
  {"line":51,"text":"\tsingleReferences []*ast.Node"},
  {"line":52,"text":"\tindirectUsers    []*ast.SourceFile"},
  {"line":53,"text":"}"},
  {"line":55,"text":"type ImportTracker func(exportSymbol *ast.Symbol, exportInfo *ExportInfo, isForRename bool) *ImportsResult"},
  {"line":57,"text":"type ModuleReferenceKind int32"},
  {"line":59,"text":"const ("},
  {"line":60,"text":"\tModuleReferenceKindImport ModuleReferenceKind = iota"},
  {"line":61,"text":"\tModuleReferenceKindReference"},
  {"line":62,"text":"\tModuleReferenceKindImplicit"},
  {"line":63,"text":")"},
  {"line":66,"text":"type ModuleReference struct {"},
  {"line":67,"text":"\tkind            ModuleReferenceKind"},
  {"line":68,"text":"\tliteral         *ast.Node // for import and implicit kinds (StringLiteralLike)"},
  {"line":69,"text":"\treferencingFile *ast.SourceFile"},
  {"line":70,"text":"\tref             *ast.FileReference // for reference kind"},
  {"line":71,"text":"}"},
  {"line":74,"text":"func createImportTracker(ctx context.Context, program *compiler.Program, sourceFiles []*ast.SourceFile, sourceFilesSet *collections.Set[string], checker *checker.Checker) ImportTracker {"},
  {"line":75,"text":"\tallDirectImports := getDirectImportsMap(ctx, program, sourceFiles, checker)"},
  {"line":76,"text":"\treturn func(exportSymbol *ast.Symbol, exportInfo *ExportInfo, isForRename bool) *ImportsResult {"},
  {"line":77,"text":"\t\tdirectImports, indirectUsers := getImportersForExport(sourceFiles, sourceFilesSet, allDirectImports, exportInfo, checker)"},
  {"line":78,"text":"\t\timportSearches, singleReferences := getSearchesFromDirectImports(directImports, exportSymbol, exportInfo.exportKind, checker, isForRename)"},
  {"line":79,"text":"\t\treturn &ImportsResult{importSearches, singleReferences, indirectUsers}"},
  {"line":80,"text":"\t}"},
  {"line":81,"text":"}"},
  {"line":84,"text":"func getDirectImportsMap(ctx context.Context, program *compiler.Program, sourceFiles []*ast.SourceFile, checker *checker.Checker) map[*ast.Symbol][]*ast.Node {"},
  {"line":85,"text":"\tresult := make(map[*ast.Symbol][]*ast.Node)"},
  {"line":86,"text":"\tfor _, sourceFile := range sourceFiles {"},
  {"line":87,"text":"\t\tif ctx.Err() != nil {"},
  {"line":88,"text":"\t\t\treturn result"},
  {"line":89,"text":"\t\t}"},
  {"line":90,"text":"\t\tforEachImport(program, sourceFile, func(importDecl *ast.Node, moduleSpecifier *ast.Node) {"},
  {"line":91,"text":"\t\t\tif moduleSymbol := checker.GetSymbolAtLocation(moduleSpecifier); moduleSymbol != nil {"},
  {"line":92,"text":"\t\t\t\tresult[moduleSymbol] = append(result[moduleSymbol], importDecl)"},
  {"line":93,"text":"\t\t\t}"},
  {"line":94,"text":"\t\t})"},
  {"line":95,"text":"\t}"},
  {"line":96,"text":"\treturn result"},
  {"line":97,"text":"}"},
  {"line":100,"text":"func forEachImport(program *compiler.Program, sourceFile *ast.SourceFile, action func(importStatement *ast.Node, imported *ast.Node)) {"},
  {"line":101,"text":"\tvar implicitImports []*ast.LiteralLikeNode"},
  {"line":102,"text":"\t_, jsxSpecifier := program.GetJSXRuntimeImportSpecifier(sourceFile.Path())"},
  {"line":103,"text":"\tif jsxSpecifier != nil {"},
  {"line":104,"text":"\t\timplicitImports = append(implicitImports, jsxSpecifier)"},
  {"line":105,"text":"\t}"},
  {"line":106,"text":"\timportHelpersSpecifier := program.GetImportHelpersImportSpecifier(sourceFile.Path())"},
  {"line":107,"text":"\tif importHelpersSpecifier != nil {"},
  {"line":108,"text":"\t\timplicitImports = append(implicitImports, importHelpersSpecifier)"},
  {"line":109,"text":"\t}"},
  {"line":110,"text":"\tif sourceFile.ExternalModuleIndicator != nil || len(sourceFile.Imports())+len(implicitImports) != 0 {"},
  {"line":111,"text":"\t\tfor _, i := range sourceFile.Imports() {"},
  {"line":112,"text":"\t\t\taction(ast.ImportFromModuleSpecifier(i), i)"},
  {"line":113,"text":"\t\t}"},
  {"line":114,"text":"\t\tfor _, i := range implicitImports {"},
  {"line":115,"text":"\t\t\taction(ast.ImportFromModuleSpecifier(i), i)"},
  {"line":116,"text":"\t\t}"},
  {"line":117,"text":"\t} else {"},
  {"line":118,"text":"\t\tforEachPossibleImportOrExportStatement(sourceFile.AsNode(), func(node *ast.Node) bool {"},
  {"line":119,"text":"\t\t\tswitch node.Kind {"},
  {"line":120,"text":"\t\t\tcase ast.KindExportDeclaration, ast.KindImportDeclaration, ast.KindJSImportDeclaration:"},
  {"line":121,"text":"\t\t\t\tif specifier := node.ModuleSpecifier(); specifier != nil && ast.IsStringLiteral(specifier) {"},
  {"line":122,"text":"\t\t\t\t\taction(node, specifier)"},
  {"line":123,"text":"\t\t\t\t}"},
  {"line":124,"text":"\t\t\tcase ast.KindImportEqualsDeclaration:"},
  {"line":125,"text":"\t\t\t\tif isExternalModuleImportEquals(node) {"},
  {"line":126,"text":"\t\t\t\t\taction(node, node.AsImportEqualsDeclaration().ModuleReference.Expression())"},
  {"line":127,"text":"\t\t\t\t}"},
  {"line":128,"text":"\t\t\t}"},
  {"line":129,"text":"\t\t\treturn false"},
  {"line":130,"text":"\t\t})"},
  {"line":131,"text":"\t}"},
  {"line":132,"text":"}"},
  {"line":134,"text":"func forEachPossibleImportOrExportStatement(sourceFileLike *ast.Node, action func(statement *ast.Node) bool) bool {"},
  {"line":135,"text":"\tfor _, statement := range getStatementsOfSourceFileLike(sourceFileLike) {"},
  {"line":136,"text":"\t\tif action(statement) || isAmbientModuleDeclaration(statement) && forEachPossibleImportOrExportStatement(statement, action) {"},
  {"line":137,"text":"\t\t\treturn true"},
  {"line":138,"text":"\t\t}"},
  {"line":139,"text":"\t}"},
  {"line":140,"text":"\treturn false"},
  {"line":141,"text":"}"},
  {"line":143,"text":"func getSourceFileLikeForImportDeclaration(node *ast.Node) *ast.Node {"},
  {"line":144,"text":"\tif ast.IsCallExpression(node) || ast.IsJSDocImportTag(node) {"},
  {"line":145,"text":"\t\treturn ast.GetSourceFileOfNode(node).AsNode()"},
  {"line":146,"text":"\t}"},
  {"line":147,"text":"\tparent := node.Parent"},
  {"line":148,"text":"\tif ast.IsSourceFile(parent) {"},
  {"line":149,"text":"\t\treturn parent"},
  {"line":150,"text":"\t}"},
  {"line":151,"text":"\tdebug.Assert(ast.IsModuleBlock(parent) && isAmbientModuleDeclaration(parent.Parent))"},
  {"line":152,"text":"\treturn parent.Parent"},
  {"line":153,"text":"}"},
  {"line":155,"text":"func isAmbientModuleDeclaration(node *ast.Node) bool {"},
  {"line":156,"text":"\treturn ast.IsModuleDeclaration(node) && ast.IsStringLiteral(node.Name())"},
  {"line":157,"text":"}"},
  {"line":159,"text":"func getStatementsOfSourceFileLike(node *ast.Node) []*ast.Node {"},
  {"line":160,"text":"\tif ast.IsSourceFile(node) {"},
  {"line":161,"text":"\t\treturn node.Statements()"},
  {"line":162,"text":"\t}"},
  {"line":163,"text":"\tif body := node.Body(); body != nil {"},
  {"line":164,"text":"\t\treturn body.Statements()"},
  {"line":165,"text":"\t}"},
  {"line":166,"text":"\treturn nil"},
  {"line":167,"text":"}"},
  {"line":169,"text":"func getImportersForExport("},
  {"line":170,"text":"\tsourceFiles []*ast.SourceFile,"},
  {"line":171,"text":"\tsourceFilesSet *collections.Set[string],"},
  {"line":172,"text":"\tallDirectImports map[*ast.Symbol][]*ast.Node,"},
  {"line":173,"text":"\texportInfo *ExportInfo,"},
  {"line":174,"text":"\tchecker *checker.Checker,"},
  {"line":175,"text":") ([]*ast.Node, []*ast.SourceFile) {"},
  {"line":176,"text":"\tvar directImports []*ast.Node"},
  {"line":177,"text":"\tvar indirectUserDeclarations []*ast.Node"},
  {"line":178,"text":"\tmarkSeenDirectImport := nodeSeenTracker()"},
  {"line":179,"text":"\tmarkSeenIndirectUser := nodeSeenTracker()"},
  {"line":180,"text":"\tisAvailableThroughGlobal := isSourceFileWithGlobalExports(exportInfo.exportingModuleSymbol.ValueDeclaration)"},
  {"line":182,"text":"\tgetDirectImports := func(moduleSymbol *ast.Symbol) []*ast.Node {"},
  {"line":183,"text":"\t\treturn allDirectImports[moduleSymbol]"},
  {"line":184,"text":"\t}"},
  {"line":187,"text":"\tvar addIndirectUser func(*ast.Node, bool)"},
  {"line":188,"text":"\taddIndirectUser = func(sourceFileLike *ast.Node, addTransitiveDependencies bool) {"},
  {"line":191,"text":"\t\tif isAvailableThroughGlobal {"},
  {"line":192,"text":"\t\t\treturn"},
  {"line":193,"text":"\t\t}"},
  {"line":194,"text":"\t\tif !markSeenIndirectUser(sourceFileLike) {"},
  {"line":195,"text":"\t\t\treturn"},
  {"line":196,"text":"\t\t}"},
  {"line":197,"text":"\t\tindirectUserDeclarations = append(indirectUserDeclarations, sourceFileLike)"},
  {"line":198,"text":"\t\tif !addTransitiveDependencies {"},
  {"line":199,"text":"\t\t\treturn"},
  {"line":200,"text":"\t\t}"},
  {"line":201,"text":"\t\tmoduleSymbol := checker.GetMergedSymbol(sourceFileLike.Symbol())"},
  {"line":202,"text":"\t\tif moduleSymbol == nil {"},
  {"line":203,"text":"\t\t\treturn"},
  {"line":204,"text":"\t\t}"},
  {"line":205,"text":"\t\tdebug.Assert(moduleSymbol.Flags&ast.SymbolFlagsModule != 0)"},
  {"line":206,"text":"\t\tfor _, directImport := range getDirectImports(moduleSymbol) {"},
  {"line":207,"text":"\t\t\tif !ast.IsImportTypeNode(directImport) {"},
  {"line":208,"text":"\t\t\t\taddIndirectUser(getSourceFileLikeForImportDeclaration(directImport), true /*addTransitiveDependencies*/)"},
  {"line":209,"text":"\t\t\t}"},
  {"line":210,"text":"\t\t}"},
  {"line":211,"text":"\t}"},
  {"line":213,"text":"\tisExported := func(node *ast.Node, stopAtAmbientModule bool) bool {"},
  {"line":214,"text":"\t\tfor node != nil && !(stopAtAmbientModule && isAmbientModuleDeclaration(node)) {"},
  {"line":215,"text":"\t\t\tif ast.HasSyntacticModifier(node, ast.ModifierFlagsExport) {"},
  {"line":216,"text":"\t\t\t\treturn true"},
  {"line":217,"text":"\t\t\t}"},
  {"line":218,"text":"\t\t\tnode = node.Parent"},
  {"line":219,"text":"\t\t}"},
  {"line":220,"text":"\t\treturn false"},
  {"line":221,"text":"\t}"},
  {"line":223,"text":"\thandleImportCall := func(importCall *ast.Node) {"},
  {"line":224,"text":"\t\ttop := ast.FindAncestor(importCall, isAmbientModuleDeclaration)"},
  {"line":225,"text":"\t\tif top == nil {"},
  {"line":226,"text":"\t\t\ttop = ast.GetSourceFileOfNode(importCall).AsNode()"},
  {"line":227,"text":"\t\t}"},
  {"line":228,"text":"\t\taddIndirectUser(top, isExported(importCall, true /*stopAtAmbientModule*/))"},
  {"line":229,"text":"\t}"},
  {"line":231,"text":"\thandleNamespaceImport := func(importDeclaration *ast.Node, name *ast.Node, isReExport bool, alreadyAddedDirect bool) {"},
  {"line":232,"text":"\t\tif exportInfo.exportKind == ExportKindExportEquals {"},
  {"line":234,"text":"\t\t\tif !alreadyAddedDirect {"},
  {"line":235,"text":"\t\t\t\tdirectImports = append(directImports, importDeclaration)"},
  {"line":236,"text":"\t\t\t}"},
  {"line":237,"text":"\t\t} else if !isAvailableThroughGlobal {"},
  {"line":238,"text":"\t\t\tsourceFileLike := getSourceFileLikeForImportDeclaration(importDeclaration)"},
  {"line":239,"text":"\t\t\tdebug.Assert(ast.IsSourceFile(sourceFileLike) || ast.IsModuleDeclaration(sourceFileLike))"},
  {"line":240,"text":"\t\t\taddIndirectUser(sourceFileLike, isReExport || findNamespaceReExports(sourceFileLike, name, checker))"},
  {"line":241,"text":"\t\t}"},
  {"line":242,"text":"\t}"},
  {"line":244,"text":"\tvar handleDirectImports func(*ast.Symbol)"},
  {"line":245,"text":"\thandleDirectImports = func(exportingModuleSymbol *ast.Symbol) {"},
  {"line":246,"text":"\t\ttheseDirectImports := getDirectImports(exportingModuleSymbol)"},
  {"line":247,"text":"\t\tfor _, direct := range theseDirectImports {"},
  {"line":248,"text":"\t\t\tif !markSeenDirectImport(direct) {"},
  {"line":249,"text":"\t\t\t\tcontinue"},
  {"line":250,"text":"\t\t\t}"},
  {"line":252,"text":"\t\t\tswitch direct.Kind {"},
  {"line":253,"text":"\t\t\tcase ast.KindCallExpression:"},
  {"line":254,"text":"\t\t\t\tif ast.IsImportCall(direct) {"},
  {"line":255,"text":"\t\t\t\t\thandleImportCall(direct)"},
  {"line":256,"text":"\t\t\t\t} else if !isAvailableThroughGlobal {"},
  {"line":257,"text":"\t\t\t\t\tparent := direct.Parent"},
  {"line":258,"text":"\t\t\t\t\tif exportInfo.exportKind == ExportKindExportEquals && ast.IsVariableDeclaration(parent) {"},
  {"line":259,"text":"\t\t\t\t\t\tname := parent.Name()"},
  {"line":260,"text":"\t\t\t\t\t\tif ast.IsIdentifier(name) {"},
  {"line":261,"text":"\t\t\t\t\t\t\tdirectImports = append(directImports, name)"},
  {"line":262,"text":"\t\t\t\t\t\t}"},
  {"line":263,"text":"\t\t\t\t\t}"},
  {"line":264,"text":"\t\t\t\t}"},
  {"line":265,"text":"\t\t\tcase ast.KindIdentifier:"},
  {"line":267,"text":"\t\t\tcase ast.KindImportEqualsDeclaration:"},
  {"line":268,"text":"\t\t\t\thandleNamespaceImport(direct, direct.Name(), ast.HasSyntacticModifier(direct, ast.ModifierFlagsExport), false /*alreadyAddedDirect*/)"},
  {"line":269,"text":"\t\t\tcase ast.KindImportDeclaration, ast.KindJSImportDeclaration, ast.KindJSDocImportTag:"},
  {"line":270,"text":"\t\t\t\tdirectImports = append(directImports, direct)"},
  {"line":271,"text":"\t\t\t\tif importClause := direct.ImportClause(); importClause != nil {"},
  {"line":272,"text":"\t\t\t\t\tif namedBindings := importClause.AsImportClause().NamedBindings; namedBindings != nil && ast.IsNamespaceImport(namedBindings) {"},
  {"line":273,"text":"\t\t\t\t\t\thandleNamespaceImport(direct, namedBindings.Name(), false /*isReExport*/, true /*alreadyAddedDirect*/)"},
  {"line":274,"text":"\t\t\t\t\t\tbreak"},
  {"line":275,"text":"\t\t\t\t\t}"},
  {"line":276,"text":"\t\t\t\t}"},
  {"line":277,"text":"\t\t\t\tif !isAvailableThroughGlobal && ast.IsDefaultImport(direct) {"},
  {"line":278,"text":"\t\t\t\t\taddIndirectUser(getSourceFileLikeForImportDeclaration(direct), false)"},
  {"line":280,"text":"\t\t\t\t}"},
  {"line":281,"text":"\t\t\tcase ast.KindExportDeclaration:"},
  {"line":282,"text":"\t\t\t\texportClause := direct.AsExportDeclaration().ExportClause"},
  {"line":283,"text":"\t\t\t\tif exportClause == nil {"},
  {"line":285,"text":"\t\t\t\t\thandleDirectImports(getContainingModuleSymbol(direct, checker))"},
  {"line":286,"text":"\t\t\t\t} else if ast.IsNamespaceExport(exportClause) {"},
  {"line":288,"text":"\t\t\t\t\taddIndirectUser(getSourceFileLikeForImportDeclaration(direct), true /*addTransitiveDependencies*/)"},
  {"line":289,"text":"\t\t\t\t} else {"},
  {"line":291,"text":"\t\t\t\t\tdirectImports = append(directImports, direct)"},
  {"line":292,"text":"\t\t\t\t}"},
  {"line":293,"text":"\t\t\tcase ast.KindImportType:"},
  {"line":295,"text":"\t\t\t\tif !isAvailableThroughGlobal && direct.AsImportTypeNode().IsTypeOf && direct.AsImportTypeNode().Qualifier == nil && isExported(direct, false) {"},
  {"line":296,"text":"\t\t\t\t\taddIndirectUser(ast.GetSourceFileOfNode(direct).AsNode(), true /*addTransitiveDependencies*/)"},
  {"line":297,"text":"\t\t\t\t}"},
  {"line":298,"text":"\t\t\t\tdirectImports = append(directImports, direct)"},
  {"line":299,"text":"\t\t\tdefault:"},
  {"line":300,"text":"\t\t\t\tdebug.FailBadSyntaxKind(direct, \"Unexpected import kind.\")"},
  {"line":301,"text":"\t\t\t}"},
  {"line":302,"text":"\t\t}"},
  {"line":303,"text":"\t}"},
  {"line":305,"text":"\tgetIndirectUsers := func() []*ast.SourceFile {"},
  {"line":306,"text":"\t\tif isAvailableThroughGlobal {"},
  {"line":308,"text":"\t\t\treturn sourceFiles"},
  {"line":309,"text":"\t\t}"},
  {"line":311,"text":"\t\tfor _, decl := range exportInfo.exportingModuleSymbol.Declarations {"},
  {"line":312,"text":"\t\t\tif ast.IsExternalModuleAugmentation(decl) && sourceFilesSet.Has(ast.GetSourceFileOfNode(decl).FileName()) {"},
  {"line":313,"text":"\t\t\t\taddIndirectUser(decl, false)"},
  {"line":314,"text":"\t\t\t}"},
  {"line":315,"text":"\t\t}"},
  {"line":317,"text":"\t\treturn core.Map(indirectUserDeclarations, ast.GetSourceFileOfNode)"},
  {"line":318,"text":"\t}"},
  {"line":320,"text":"\thandleDirectImports(exportInfo.exportingModuleSymbol)"},
  {"line":321,"text":"\treturn directImports, getIndirectUsers()"},
  {"line":322,"text":"}"},
  {"line":324,"text":"func getContainingModuleSymbol(importer *ast.Node, checker *checker.Checker) *ast.Symbol {"},
  {"line":325,"text":"\treturn checker.GetMergedSymbol(getSourceFileLikeForImportDeclaration(importer).Symbol())"},
  {"line":326,"text":"}"},
  {"line":329,"text":"func findNamespaceReExports(sourceFileLike *ast.Node, name *ast.Node, checker *checker.Checker) bool {"},
  {"line":330,"text":"\tnamespaceImportSymbol := checker.GetSymbolAtLocation(name)"},
  {"line":331,"text":"\treturn forEachPossibleImportOrExportStatement(sourceFileLike, func(statement *ast.Node) bool {"},
  {"line":332,"text":"\t\tif !ast.IsExportDeclaration(statement) {"},
  {"line":333,"text":"\t\t\treturn false"},
  {"line":334,"text":"\t\t}"},
  {"line":335,"text":"\t\texportClause := statement.AsExportDeclaration().ExportClause"},
  {"line":336,"text":"\t\tmoduleSpecifier := statement.ModuleSpecifier()"},
  {"line":337,"text":"\t\treturn moduleSpecifier == nil && exportClause != nil && ast.IsNamedExports(exportClause) && core.Some(exportClause.Elements(), func(element *ast.Node) bool {"},
  {"line":338,"text":"\t\t\treturn checker.GetExportSpecifierLocalTargetSymbol(element) == namespaceImportSymbol"},
  {"line":339,"text":"\t\t})"},
  {"line":340,"text":"\t})"},
  {"line":341,"text":"}"},
  {"line":343,"text":"func getSearchesFromDirectImports("},
  {"line":344,"text":"\tdirectImports []*ast.Node,"},
  {"line":345,"text":"\texportSymbol *ast.Symbol,"},
  {"line":346,"text":"\texportKind ExportKind,"},
  {"line":347,"text":"\tchecker *checker.Checker,"},
  {"line":348,"text":"\tisForRename bool,"},
  {"line":349,"text":") ([]LocationAndSymbol, []*ast.Node) {"},
  {"line":350,"text":"\tvar importSearches []LocationAndSymbol"},
  {"line":351,"text":"\tvar singleReferences []*ast.Node"},
  {"line":353,"text":"\taddSearch := func(location *ast.Node, symbol *ast.Symbol) {"},
  {"line":354,"text":"\t\timportSearches = append(importSearches, LocationAndSymbol{location, symbol})"},
  {"line":355,"text":"\t}"},
  {"line":357,"text":"\tisNameMatch := func(name string) bool {"},
  {"line":359,"text":"\t\treturn name == exportSymbol.Name || exportKind != ExportKindNamed && name == ast.InternalSymbolNameDefault"},
  {"line":360,"text":"\t}"},
  {"line":365,"text":"\thandleNamespaceImportLike := func(importName *ast.Node) {"},
  {"line":367,"text":"\t\tif exportKind == ExportKindExportEquals && (!isForRename || isNameMatch(importName.Text())) {"},
  {"line":368,"text":"\t\t\taddSearch(importName, checker.GetSymbolAtLocation(importName))"},
  {"line":369,"text":"\t\t}"},
  {"line":370,"text":"\t}"},
  {"line":372,"text":"\tsearchForNamedImport := func(namedBindings *ast.Node) {"},
  {"line":373,"text":"\t\tif namedBindings == nil {"},
  {"line":374,"text":"\t\t\treturn"},
  {"line":375,"text":"\t\t}"},
  {"line":376,"text":"\t\tfor _, element := range namedBindings.Elements() {"},
  {"line":377,"text":"\t\t\tname := element.Name()"},
  {"line":378,"text":"\t\t\tpropertyName := element.PropertyName()"},
  {"line":379,"text":"\t\t\tif !isNameMatch(core.OrElse(propertyName, name).Text()) {"},
  {"line":380,"text":"\t\t\t\tcontinue"},
  {"line":381,"text":"\t\t\t}"},
  {"line":382,"text":"\t\t\tif propertyName != nil {"},
  {"line":384,"text":"\t\t\t\tsingleReferences = append(singleReferences, propertyName)"},
  {"line":387,"text":"\t\t\t\tif !isForRename || name.Text() == exportSymbol.Name {"},
  {"line":389,"text":"\t\t\t\t\taddSearch(name, checker.GetSymbolAtLocation(name))"},
  {"line":390,"text":"\t\t\t\t}"},
  {"line":391,"text":"\t\t\t} else {"},
  {"line":392,"text":"\t\t\t\tvar localSymbol *ast.Symbol"},
  {"line":393,"text":"\t\t\t\tif ast.IsExportSpecifier(element) && element.PropertyName() != nil {"},
  {"line":394,"text":"\t\t\t\t\tlocalSymbol = checker.GetExportSpecifierLocalTargetSymbol(element)"},
  {"line":395,"text":"\t\t\t\t} else {"},
  {"line":396,"text":"\t\t\t\t\tlocalSymbol = checker.GetSymbolAtLocation(name)"},
  {"line":397,"text":"\t\t\t\t}"},
  {"line":398,"text":"\t\t\t\taddSearch(name, localSymbol)"},
  {"line":399,"text":"\t\t\t}"},
  {"line":400,"text":"\t\t}"},
  {"line":401,"text":"\t}"},
  {"line":403,"text":"\thandleImport := func(decl *ast.Node) {"},
  {"line":404,"text":"\t\tif ast.IsImportEqualsDeclaration(decl) {"},
  {"line":405,"text":"\t\t\tif isExternalModuleImportEquals(decl) {"},
  {"line":406,"text":"\t\t\t\thandleNamespaceImportLike(decl.Name())"},
  {"line":407,"text":"\t\t\t}"},
  {"line":408,"text":"\t\t\treturn"},
  {"line":409,"text":"\t\t}"},
  {"line":410,"text":"\t\tif ast.IsIdentifier(decl) {"},
  {"line":411,"text":"\t\t\thandleNamespaceImportLike(decl)"},
  {"line":412,"text":"\t\t\treturn"},
  {"line":413,"text":"\t\t}"},
  {"line":414,"text":"\t\tif ast.IsImportTypeNode(decl) {"},
  {"line":415,"text":"\t\t\tif qualifier := decl.AsImportTypeNode().Qualifier; qualifier != nil {"},
  {"line":416,"text":"\t\t\t\tfirstIdentifier := ast.GetFirstIdentifier(qualifier)"},
  {"line":417,"text":"\t\t\t\tif firstIdentifier.Text() == ast.SymbolName(exportSymbol) {"},
  {"line":418,"text":"\t\t\t\t\tsingleReferences = append(singleReferences, firstIdentifier)"},
  {"line":419,"text":"\t\t\t\t}"},
  {"line":420,"text":"\t\t\t} else if exportKind == ExportKindExportEquals {"},
  {"line":421,"text":"\t\t\t\tsingleReferences = append(singleReferences, decl.AsImportTypeNode().Argument.AsLiteralTypeNode().Literal)"},
  {"line":422,"text":"\t\t\t}"},
  {"line":423,"text":"\t\t\treturn"},
  {"line":424,"text":"\t\t}"},
  {"line":426,"text":"\t\tif !ast.IsStringLiteral(decl.ModuleSpecifier()) {"},
  {"line":427,"text":"\t\t\treturn"},
  {"line":428,"text":"\t\t}"},
  {"line":429,"text":"\t\tif ast.IsExportDeclaration(decl) {"},
  {"line":430,"text":"\t\t\tif exportClause := decl.AsExportDeclaration().ExportClause; exportClause != nil && ast.IsNamedExports(exportClause) {"},
  {"line":431,"text":"\t\t\t\tsearchForNamedImport(exportClause)"},
  {"line":432,"text":"\t\t\t}"},
  {"line":433,"text":"\t\t\treturn"},
  {"line":434,"text":"\t\t}"},
  {"line":435,"text":"\t\tif importClause := decl.ImportClause(); importClause != nil {"},
  {"line":436,"text":"\t\t\tif namedBindings := importClause.AsImportClause().NamedBindings; namedBindings != nil {"},
  {"line":437,"text":"\t\t\t\tswitch namedBindings.Kind {"},
  {"line":438,"text":"\t\t\t\tcase ast.KindNamespaceImport:"},
  {"line":439,"text":"\t\t\t\t\thandleNamespaceImportLike(namedBindings.Name())"},
  {"line":440,"text":"\t\t\t\tcase ast.KindNamedImports:"},
  {"line":442,"text":"\t\t\t\t\tif exportKind == ExportKindNamed || exportKind == ExportKindDefault {"},
  {"line":443,"text":"\t\t\t\t\t\tsearchForNamedImport(namedBindings)"},
  {"line":444,"text":"\t\t\t\t\t}"},
  {"line":445,"text":"\t\t\t\t}"},
  {"line":446,"text":"\t\t\t}"},
  {"line":450,"text":"\t\t\tif name := importClause.Name(); name != nil && (exportKind == ExportKindDefault || exportKind == ExportKindExportEquals) && (!isForRename || name.Text() == symbolNameNoDefault(exportSymbol)) {"},
  {"line":451,"text":"\t\t\t\tdefaultImportAlias := checker.GetSymbolAtLocation(name)"},
  {"line":452,"text":"\t\t\t\taddSearch(name, defaultImportAlias)"},
  {"line":453,"text":"\t\t\t}"},
  {"line":454,"text":"\t\t}"},
  {"line":455,"text":"\t}"},
  {"line":456,"text":"\tfor _, decl := range directImports {"},
  {"line":457,"text":"\t\thandleImport(decl)"},
  {"line":458,"text":"\t}"},
  {"line":459,"text":"\treturn importSearches, singleReferences"},
  {"line":460,"text":"}"},
  {"line":462,"text":"func getImportOrExportSymbol(node *ast.Node, symbol *ast.Symbol, checker *checker.Checker, comingFromExport bool) *ImportExportSymbol {"},
  {"line":463,"text":"\texportInfo := func(symbol *ast.Symbol, kind ExportKind) *ImportExportSymbol {"},
  {"line":464,"text":"\t\tif exportInfo := getExportInfo(symbol, kind, checker); exportInfo != nil {"},
  {"line":465,"text":"\t\t\treturn &ImportExportSymbol{"},
  {"line":466,"text":"\t\t\t\tkind:       ImpExpKindExport,"},
  {"line":467,"text":"\t\t\t\tsymbol:     symbol,"},
  {"line":468,"text":"\t\t\t\texportInfo: exportInfo,"},
  {"line":469,"text":"\t\t\t}"},
  {"line":470,"text":"\t\t}"},
  {"line":471,"text":"\t\treturn nil"},
  {"line":472,"text":"\t}"},
  {"line":474,"text":"\tgetExport := func() *ImportExportSymbol {"},
  {"line":475,"text":"\t\tgetExportAssignmentExport := func(ex *ast.Node) *ImportExportSymbol {"},
  {"line":477,"text":"\t\t\tif ex.Symbol().Parent == nil {"},
  {"line":478,"text":"\t\t\t\treturn nil"},
  {"line":479,"text":"\t\t\t}"},
  {"line":480,"text":"\t\t\texportKind := core.IfElse(ex.AsExportAssignment().IsExportEquals, ExportKindExportEquals, ExportKindDefault)"},
  {"line":481,"text":"\t\t\treturn &ImportExportSymbol{"},
  {"line":482,"text":"\t\t\t\tkind:   ImpExpKindExport,"},
  {"line":483,"text":"\t\t\t\tsymbol: symbol,"},
  {"line":484,"text":"\t\t\t\texportInfo: &ExportInfo{"},
  {"line":485,"text":"\t\t\t\t\texportingModuleSymbol: ex.Symbol().Parent,"},
  {"line":486,"text":"\t\t\t\t\texportKind:            exportKind,"},
  {"line":487,"text":"\t\t\t\t},"},
  {"line":488,"text":"\t\t\t}"},
  {"line":489,"text":"\t\t}"},
  {"line":492,"text":"\t\tgetExportKindForDeclaration := func(node *ast.Node) ExportKind {"},
  {"line":493,"text":"\t\t\tif ast.HasSyntacticModifier(node, ast.ModifierFlagsDefault) {"},
  {"line":494,"text":"\t\t\t\treturn ExportKindDefault"},
  {"line":495,"text":"\t\t\t}"},
  {"line":496,"text":"\t\t\treturn ExportKindNamed"},
  {"line":497,"text":"\t\t}"},
  {"line":499,"text":"\t\tgetSpecialPropertyExport := func(node *ast.Node, useLhsSymbol bool) *ImportExportSymbol {"},
  {"line":500,"text":"\t\t\tvar kind ExportKind"},
  {"line":501,"text":"\t\t\tswitch ast.GetAssignmentDeclarationKind(node) {"},
  {"line":502,"text":"\t\t\tcase ast.JSDeclarationKindExportsProperty:"},
  {"line":503,"text":"\t\t\t\tkind = ExportKindNamed"},
  {"line":504,"text":"\t\t\tcase ast.JSDeclarationKindModuleExports:"},
  {"line":505,"text":"\t\t\t\tkind = ExportKindExportEquals"},
  {"line":506,"text":"\t\t\tdefault:"},
  {"line":507,"text":"\t\t\t\treturn nil"},
  {"line":508,"text":"\t\t\t}"},
  {"line":509,"text":"\t\t\tsym := symbol"},
  {"line":510,"text":"\t\t\tif useLhsSymbol {"},
  {"line":511,"text":"\t\t\t\tsym = node.Symbol()"},
  {"line":512,"text":"\t\t\t}"},
  {"line":513,"text":"\t\t\tif sym == nil {"},
  {"line":514,"text":"\t\t\t\treturn nil"},
  {"line":515,"text":"\t\t\t}"},
  {"line":516,"text":"\t\t\treturn exportInfo(sym, kind)"},
  {"line":517,"text":"\t\t}"},
  {"line":519,"text":"\t\tparent := node.Parent"},
  {"line":520,"text":"\t\tgrandparent := parent.Parent"},
  {"line":521,"text":"\t\tif symbol.ExportSymbol != nil {"},
  {"line":522,"text":"\t\t\tif ast.IsPropertyAccessExpression(parent) {"},
  {"line":525,"text":"\t\t\t\tif ast.IsBinaryExpression(grandparent) && slices.Contains(symbol.Declarations, parent) {"},
  {"line":526,"text":"\t\t\t\t\treturn getSpecialPropertyExport(grandparent, false /*useLhsSymbol*/)"},
  {"line":527,"text":"\t\t\t\t}"},
  {"line":528,"text":"\t\t\t\treturn nil"},
  {"line":529,"text":"\t\t\t}"},
  {"line":530,"text":"\t\t\treturn exportInfo(symbol.ExportSymbol, getExportKindForDeclaration(parent))"},
  {"line":531,"text":"\t\t} else {"},
  {"line":532,"text":"\t\t\texportNode := getExportNode(parent, node)"},
  {"line":533,"text":"\t\t\tswitch {"},
  {"line":534,"text":"\t\t\tcase exportNode != nil && (ast.HasSyntacticModifier(exportNode, ast.ModifierFlagsExport) || ast.IsImplicitlyExportedJSTypeAlias(exportNode)):"},
  {"line":535,"text":"\t\t\t\tif ast.IsImportEqualsDeclaration(exportNode) && exportNode.AsImportEqualsDeclaration().ModuleReference == node {"},
  {"line":537,"text":"\t\t\t\t\tif comingFromExport {"},
  {"line":538,"text":"\t\t\t\t\t\treturn nil"},
  {"line":539,"text":"\t\t\t\t\t}"},
  {"line":540,"text":"\t\t\t\t\tlhsSymbol := checker.GetSymbolAtLocation(exportNode.Name())"},
  {"line":541,"text":"\t\t\t\t\treturn &ImportExportSymbol{"},
  {"line":542,"text":"\t\t\t\t\t\tkind:   ImpExpKindImport,"},
  {"line":543,"text":"\t\t\t\t\t\tsymbol: lhsSymbol,"},
  {"line":544,"text":"\t\t\t\t\t}"},
  {"line":545,"text":"\t\t\t\t}"},
  {"line":546,"text":"\t\t\t\treturn exportInfo(symbol, getExportKindForDeclaration(exportNode))"},
  {"line":547,"text":"\t\t\tcase ast.IsNamespaceExport(parent):"},
  {"line":548,"text":"\t\t\t\treturn exportInfo(symbol, ExportKindNamed)"},
  {"line":549,"text":"\t\t\tcase ast.IsExportAssignment(parent):"},
  {"line":550,"text":"\t\t\t\treturn getExportAssignmentExport(parent)"},
  {"line":551,"text":"\t\t\tcase ast.IsExportAssignment(grandparent):"},
  {"line":552,"text":"\t\t\t\treturn getExportAssignmentExport(grandparent)"},
  {"line":553,"text":"\t\t\tcase ast.IsBinaryExpression(parent):"},
  {"line":554,"text":"\t\t\t\treturn getSpecialPropertyExport(parent, true /*useLhsSymbol*/)"},
  {"line":555,"text":"\t\t\tcase ast.IsBinaryExpression(grandparent):"},
  {"line":556,"text":"\t\t\t\treturn getSpecialPropertyExport(grandparent, true /*useLhsSymbol*/)"},
  {"line":557,"text":"\t\t\tcase ast.IsJSDocTypedefTag(parent) || ast.IsJSDocCallbackTag(parent):"},
  {"line":558,"text":"\t\t\t\treturn exportInfo(symbol, ExportKindNamed)"},
  {"line":559,"text":"\t\t\t}"},
  {"line":560,"text":"\t\t}"},
  {"line":561,"text":"\t\treturn nil"},
  {"line":562,"text":"\t}"},
  {"line":564,"text":"\tgetImport := func() *ImportExportSymbol {"},
  {"line":565,"text":"\t\tif !isNodeImport(node) {"},
  {"line":566,"text":"\t\t\treturn nil"},
  {"line":567,"text":"\t\t}"},
  {"line":570,"text":"\t\tvar importedSymbol *ast.Symbol"},
  {"line":571,"text":"\t\tif symbol.Flags&ast.SymbolFlagsAlias != 0 {"},
  {"line":572,"text":"\t\t\timportedSymbol = checker.GetImmediateAliasedSymbol(symbol)"},
  {"line":573,"text":"\t\t} else {"},
  {"line":574,"text":"\t\t\timportedSymbol = getPropertySymbolOfObjectBindingPatternWithoutPropertyName(symbol, checker)"},
  {"line":575,"text":"\t\t}"},
  {"line":576,"text":"\t\tif importedSymbol == nil {"},
  {"line":577,"text":"\t\t\treturn nil"},
  {"line":578,"text":"\t\t}"},
  {"line":580,"text":"\t\timportedSymbol = skipExportSpecifierSymbol(importedSymbol, checker)"},
  {"line":581,"text":"\t\tif importedSymbol == nil {"},
  {"line":582,"text":"\t\t\treturn nil"},
  {"line":583,"text":"\t\t}"},
  {"line":585,"text":"\t\tif importedSymbol.Name == \"export=\" {"},
  {"line":586,"text":"\t\t\timportedSymbol = getExportEqualsLocalSymbol(importedSymbol, checker)"},
  {"line":587,"text":"\t\t\tif importedSymbol == nil {"},
  {"line":588,"text":"\t\t\t\treturn nil"},
  {"line":589,"text":"\t\t\t}"},
  {"line":590,"text":"\t\t}"},
  {"line":594,"text":"\t\timportedName := symbolNameNoDefault(importedSymbol)"},
  {"line":595,"text":"\t\tif importedName == \"\" || importedName == ast.InternalSymbolNameDefault || importedName == symbol.Name {"},
  {"line":596,"text":"\t\t\treturn &ImportExportSymbol{"},
  {"line":597,"text":"\t\t\t\tkind:   ImpExpKindImport,"},
  {"line":598,"text":"\t\t\t\tsymbol: importedSymbol,"},
  {"line":599,"text":"\t\t\t}"},
  {"line":600,"text":"\t\t}"},
  {"line":601,"text":"\t\treturn nil"},
  {"line":602,"text":"\t}"},
  {"line":604,"text":"\tresult := getExport()"},
  {"line":605,"text":"\tif result == nil && !comingFromExport {"},
  {"line":606,"text":"\t\tresult = getImport()"},
  {"line":607,"text":"\t}"},
  {"line":608,"text":"\treturn result"},
  {"line":609,"text":"}"},
  {"line":611,"text":"func getExportInfo(exportSymbol *ast.Symbol, exportKind ExportKind, c *checker.Checker) *ExportInfo {"},
  {"line":613,"text":"\tif exportSymbol.Parent != nil {"},
  {"line":614,"text":"\t\texportingModuleSymbol := c.GetMergedSymbol(exportSymbol.Parent)"},
  {"line":616,"text":"\t\tif checker.IsExternalModuleSymbol(exportingModuleSymbol) {"},
  {"line":617,"text":"\t\t\treturn &ExportInfo{"},
  {"line":618,"text":"\t\t\t\texportingModuleSymbol: exportingModuleSymbol,"},
  {"line":619,"text":"\t\t\t\texportKind:            exportKind,"},
  {"line":620,"text":"\t\t\t}"},
  {"line":621,"text":"\t\t}"},
  {"line":622,"text":"\t}"},
  {"line":623,"text":"\treturn nil"},
  {"line":624,"text":"}"},
  {"line":628,"text":"func getExportNode(parent *ast.Node, node *ast.Node) *ast.Node {"},
  {"line":629,"text":"\tvar declaration *ast.Node"},
  {"line":630,"text":"\tswitch {"},
  {"line":631,"text":"\tcase ast.IsVariableDeclaration(parent):"},
  {"line":632,"text":"\t\tdeclaration = parent"},
  {"line":633,"text":"\tcase ast.IsBindingElement(parent):"},
  {"line":634,"text":"\t\tdeclaration = ast.WalkUpBindingElementsAndPatterns(parent)"},
  {"line":635,"text":"\t}"},
  {"line":636,"text":"\tif declaration != nil {"},
  {"line":637,"text":"\t\tif parent.Name() == node && !ast.IsCatchClause(declaration.Parent) && ast.IsVariableStatement(declaration.Parent.Parent) {"},
  {"line":638,"text":"\t\t\treturn declaration.Parent.Parent"},
  {"line":639,"text":"\t\t}"},
  {"line":640,"text":"\t\treturn nil"},
  {"line":641,"text":"\t}"},
  {"line":642,"text":"\treturn parent"},
  {"line":643,"text":"}"},
  {"line":645,"text":"func isNodeImport(node *ast.Node) bool {"},
  {"line":646,"text":"\tparent := node.Parent"},
  {"line":647,"text":"\tswitch parent.Kind {"},
  {"line":648,"text":"\tcase ast.KindImportEqualsDeclaration:"},
  {"line":649,"text":"\t\treturn parent.Name() == node && isExternalModuleImportEquals(parent)"},
  {"line":650,"text":"\tcase ast.KindImportSpecifier:"},
  {"line":652,"text":"\t\treturn parent.PropertyName() == nil"},
  {"line":653,"text":"\tcase ast.KindImportClause, ast.KindNamespaceImport:"},
  {"line":654,"text":"\t\tdebug.Assert(parent.Name() == node)"},
  {"line":655,"text":"\t\treturn true"},
  {"line":656,"text":"\tcase ast.KindBindingElement:"},
  {"line":657,"text":"\t\treturn ast.IsInJSFile(node) && ast.IsVariableDeclarationInitializedToBareOrAccessedRequire(parent.Parent.Parent)"},
  {"line":658,"text":"\t}"},
  {"line":659,"text":"\treturn false"},
  {"line":660,"text":"}"},
  {"line":662,"text":"func isExternalModuleImportEquals(node *ast.Node) bool {"},
  {"line":663,"text":"\tmoduleReference := node.AsImportEqualsDeclaration().ModuleReference"},
  {"line":664,"text":"\treturn ast.IsExternalModuleReference(moduleReference) && moduleReference.Expression().Kind == ast.KindStringLiteral"},
  {"line":665,"text":"}"},
  {"line":668,"text":"func skipExportSpecifierSymbol(symbol *ast.Symbol, checker *checker.Checker) *ast.Symbol {"},
  {"line":670,"text":"\tfor _, declaration := range symbol.Declarations {"},
  {"line":671,"text":"\t\tswitch {"},
  {"line":672,"text":"\t\tcase ast.IsExportSpecifier(declaration) && declaration.PropertyName() == nil && declaration.Parent.Parent.ModuleSpecifier() == nil:"},
  {"line":673,"text":"\t\t\treturn core.OrElse(checker.GetExportSpecifierLocalTargetSymbol(declaration), symbol)"},
  {"line":674,"text":"\t\tcase ast.IsPropertyAccessExpression(declaration) && ast.IsModuleExportsAccessExpression(declaration.Expression()) && !ast.IsPrivateIdentifier(declaration.Name()):"},
  {"line":676,"text":"\t\t\treturn checker.GetSymbolAtLocation(declaration)"},
  {"line":677,"text":"\t\tcase ast.IsShorthandPropertyAssignment(declaration) && ast.IsBinaryExpression(declaration.Parent.Parent) && ast.GetAssignmentDeclarationKind(declaration.Parent.Parent) == ast.JSDeclarationKindModuleExports:"},
  {"line":678,"text":"\t\t\treturn checker.GetExportSpecifierLocalTargetSymbol(declaration.Name())"},
  {"line":679,"text":"\t\t}"},
  {"line":680,"text":"\t}"},
  {"line":681,"text":"\treturn symbol"},
  {"line":682,"text":"}"},
  {"line":684,"text":"func getExportEqualsLocalSymbol(importedSymbol *ast.Symbol, checker *checker.Checker) *ast.Symbol {"},
  {"line":685,"text":"\tif importedSymbol.Flags&ast.SymbolFlagsAlias != 0 {"},
  {"line":686,"text":"\t\treturn checker.GetImmediateAliasedSymbol(importedSymbol)"},
  {"line":687,"text":"\t}"},
  {"line":688,"text":"\tdecl := importedSymbol.ValueDeclaration"},
  {"line":689,"text":"\tdebug.Assert(decl != nil)"},
  {"line":690,"text":"\tswitch {"},
  {"line":691,"text":"\tcase ast.IsExportAssignment(decl):"},
  {"line":692,"text":"\t\treturn decl.Expression().Symbol()"},
  {"line":693,"text":"\tcase ast.IsBinaryExpression(decl):"},
  {"line":694,"text":"\t\treturn decl.AsBinaryExpression().Right.Symbol()"},
  {"line":695,"text":"\tcase ast.IsSourceFile(decl):"},
  {"line":696,"text":"\t\treturn decl.Symbol()"},
  {"line":697,"text":"\t}"},
  {"line":698,"text":"\treturn nil"},
  {"line":699,"text":"}"},
  {"line":701,"text":"func symbolNameNoDefault(symbol *ast.Symbol) string {"},
  {"line":702,"text":"\tif symbol.Name != ast.InternalSymbolNameDefault {"},
  {"line":703,"text":"\t\treturn symbol.Name"},
  {"line":704,"text":"\t}"},
  {"line":705,"text":"\tfor _, decl := range symbol.Declarations {"},
  {"line":706,"text":"\t\tname := ast.GetNameOfDeclaration(decl)"},
  {"line":707,"text":"\t\tif name != nil && ast.IsIdentifier(name) {"},
  {"line":708,"text":"\t\t\treturn name.Text()"},
  {"line":709,"text":"\t\t}"},
  {"line":710,"text":"\t}"},
  {"line":711,"text":"\treturn \"\""},
  {"line":712,"text":"}"},
  {"line":716,"text":"func findModuleReferences(program *compiler.Program, sourceFiles []*ast.SourceFile, searchModuleSymbol *ast.Symbol, checker *checker.Checker) []ModuleReference {"},
  {"line":717,"text":"\trefs := []ModuleReference{}"},
  {"line":719,"text":"\tfor _, referencingFile := range sourceFiles {"},
  {"line":720,"text":"\t\tsearchSourceFile := searchModuleSymbol.ValueDeclaration"},
  {"line":721,"text":"\t\tif searchSourceFile != nil && searchSourceFile.Kind == ast.KindSourceFile {"},
  {"line":723,"text":"\t\t\tfor _, ref := range referencingFile.ReferencedFiles {"},
  {"line":724,"text":"\t\t\t\tif program.GetSourceFileFromReference(referencingFile, ref) == searchSourceFile.AsSourceFile() {"},
  {"line":725,"text":"\t\t\t\t\trefs = append(refs, ModuleReference{"},
  {"line":726,"text":"\t\t\t\t\t\tkind:            ModuleReferenceKindReference,"},
  {"line":727,"text":"\t\t\t\t\t\treferencingFile: referencingFile,"},
  {"line":728,"text":"\t\t\t\t\t\tref:             ref,"},
  {"line":729,"text":"\t\t\t\t\t})"},
  {"line":730,"text":"\t\t\t\t}"},
  {"line":731,"text":"\t\t\t}"},
  {"line":734,"text":"\t\t\tfor _, ref := range referencingFile.TypeReferenceDirectives {"},
  {"line":735,"text":"\t\t\t\treferenced := program.GetResolvedTypeReferenceDirectiveFromTypeReferenceDirective(ref, referencingFile)"},
  {"line":736,"text":"\t\t\t\tif referenced != nil && referenced.ResolvedFileName == searchSourceFile.AsSourceFile().FileName() {"},
  {"line":737,"text":"\t\t\t\t\trefs = append(refs, ModuleReference{"},
  {"line":738,"text":"\t\t\t\t\t\tkind:            ModuleReferenceKindReference,"},
  {"line":739,"text":"\t\t\t\t\t\treferencingFile: referencingFile,"},
  {"line":740,"text":"\t\t\t\t\t\tref:             ref,"},
  {"line":741,"text":"\t\t\t\t\t})"},
  {"line":742,"text":"\t\t\t\t}"},
  {"line":743,"text":"\t\t\t}"},
  {"line":744,"text":"\t\t}"},
  {"line":747,"text":"\t\tforEachImport(program, referencingFile, func(importDecl *ast.Node, moduleSpecifier *ast.Node) {"},
  {"line":748,"text":"\t\t\tmoduleSymbol := checker.GetSymbolAtLocation(moduleSpecifier)"},
  {"line":749,"text":"\t\t\tif moduleSymbol == searchModuleSymbol {"},
  {"line":750,"text":"\t\t\t\tif ast.NodeIsSynthesized(importDecl) {"},
  {"line":751,"text":"\t\t\t\t\trefs = append(refs, ModuleReference{"},
  {"line":752,"text":"\t\t\t\t\t\tkind:            ModuleReferenceKindImplicit,"},
  {"line":753,"text":"\t\t\t\t\t\tliteral:         moduleSpecifier,"},
  {"line":754,"text":"\t\t\t\t\t\treferencingFile: referencingFile,"},
  {"line":755,"text":"\t\t\t\t\t})"},
  {"line":756,"text":"\t\t\t\t} else {"},
  {"line":757,"text":"\t\t\t\t\trefs = append(refs, ModuleReference{"},
  {"line":758,"text":"\t\t\t\t\t\tkind:    ModuleReferenceKindImport,"},
  {"line":759,"text":"\t\t\t\t\t\tliteral: moduleSpecifier,"},
  {"line":760,"text":"\t\t\t\t\t})"},
  {"line":761,"text":"\t\t\t\t}"},
  {"line":762,"text":"\t\t\t}"},
  {"line":763,"text":"\t\t})"},
  {"line":764,"text":"\t}"},
  {"line":766,"text":"\treturn refs"},
  {"line":767,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsImportTrackerSourceLines.find((entry) => entry.line === line)?.text;
}
