/**
 * Language-service parity map for TS-Go `ls/organizeimports.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsUpstreamPath = "ls/organizeimports.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsDeclarations: readonly UpstreamDeclaration[] = [
  {"line":24,"kind":"func","name":"OrganizeImports","receiver":"l *LanguageService"},
  {"line":116,"kind":"type","name":"organizeImportsComparerSettings"},
  {"line":122,"kind":"func","name":"organizeImportsWorker"},
  {"line":216,"kind":"func","name":"groupByModuleSpecifier"},
  {"line":235,"kind":"func","name":"removeUnusedImports"},
  {"line":316,"kind":"func","name":"filterUsedImportSpecifiers"},
  {"line":333,"kind":"func","name":"hasModuleDeclarationMatchingSpecifier"},
  {"line":349,"kind":"func","name":"getImportAttributesKey"},
  {"line":385,"kind":"func","name":"groupByNewlineContiguous"},
  {"line":406,"kind":"func","name":"isNewGroup"},
  {"line":441,"kind":"func","name":"coalesceImportsWorker"},
  {"line":631,"kind":"type","name":"categorizedImports"},
  {"line":637,"kind":"type","name":"importGroup"},
  {"line":643,"kind":"func","name":"isEmpty","receiver":"g importGroup"},
  {"line":647,"kind":"func","name":"getCategorizedImports"},
  {"line":689,"kind":"func","name":"getNewImportSpecifiers"},
  {"line":719,"kind":"func","name":"tryGetNamedBindingElements"},
  {"line":740,"kind":"func","name":"getTopLevelExportGroups"},
  {"line":780,"kind":"func","name":"organizeExportsWorker"},
  {"line":829,"kind":"func","name":"coalesceExportsWorker"},
  {"line":925,"kind":"type","name":"categorizedExports"},
  {"line":931,"kind":"func","name":"getCategorizedExports"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":6,"text":"\t\"strings\""},
  {"line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/change\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"line":18,"text":")"},
  {"line":24,"text":"func (l *LanguageService) OrganizeImports("},
  {"line":25,"text":"\tctx context.Context,"},
  {"line":26,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":27,"text":"\tprogram *compiler.Program,"},
  {"line":28,"text":"\tkind lsproto.CodeActionKind,"},
  {"line":29,"text":") map[string][]*lsproto.TextEdit {"},
  {"line":30,"text":"\tchangeTracker := change.NewTracker(ctx, program.Options(), l.FormatOptions(), l.converters)"},
  {"line":31,"text":"\tshouldSort := kind == lsproto.CodeActionKindSourceSortImports || kind == lsproto.CodeActionKindSourceOrganizeImports"},
  {"line":32,"text":"\tshouldCombine := shouldSort"},
  {"line":33,"text":"\tshouldRemove := kind == lsproto.CodeActionKindSourceRemoveUnusedImports || kind == lsproto.CodeActionKindSourceOrganizeImports"},
  {"line":34,"text":"\ttopLevelImportDecls := lsutil.FilterImportDeclarations(sourceFile.Statements.Nodes)"},
  {"line":35,"text":"\ttopLevelImportGroupDecls := groupByNewlineContiguous(sourceFile, topLevelImportDecls)"},
  {"line":37,"text":"\tpreferences := l.UserPreferences()"},
  {"line":38,"text":"\tcomparersToTest, typeOrdersToTest := lsutil.GetDetectionLists(preferences)"},
  {"line":39,"text":"\tdefaultComparer := comparersToTest[0]"},
  {"line":41,"text":"\tvar moduleSpecifierComparer func(a, b string) int"},
  {"line":42,"text":"\tvar namedImportComparer func(a, b string) int"},
  {"line":43,"text":"\tif !preferences.OrganizeImportsIgnoreCase.IsUnknown() {"},
  {"line":44,"text":"\t\tmoduleSpecifierComparer = defaultComparer"},
  {"line":45,"text":"\t\tnamedImportComparer = defaultComparer"},
  {"line":46,"text":"\t}"},
  {"line":47,"text":"\ttypeOrder := preferences.OrganizeImportsTypeOrder"},
  {"line":49,"text":"\tif preferences.OrganizeImportsIgnoreCase.IsUnknown() {"},
  {"line":50,"text":"\t\tresult, _ := lsutil.DetectModuleSpecifierCaseBySort(topLevelImportGroupDecls, comparersToTest)"},
  {"line":51,"text":"\t\tmoduleSpecifierComparer = result"},
  {"line":52,"text":"\t}"},
  {"line":54,"text":"\tif typeOrder == lsutil.OrganizeImportsTypeOrderAuto || preferences.OrganizeImportsIgnoreCase.IsUnknown() {"},
  {"line":55,"text":"\t\tnamedImportComparer2, typeOrder2, found := lsutil.DetectNamedImportOrganizationBySort(topLevelImportDecls, comparersToTest, typeOrdersToTest)"},
  {"line":56,"text":"\t\tif found {"},
  {"line":57,"text":"\t\t\tif namedImportComparer == nil || preferences.OrganizeImportsIgnoreCase.IsUnknown() {"},
  {"line":58,"text":"\t\t\t\tnamedImportComparer = namedImportComparer2"},
  {"line":59,"text":"\t\t\t}"},
  {"line":60,"text":"\t\t\tif typeOrder == lsutil.OrganizeImportsTypeOrderAuto {"},
  {"line":61,"text":"\t\t\t\ttypeOrder = typeOrder2"},
  {"line":62,"text":"\t\t\t}"},
  {"line":63,"text":"\t\t}"},
  {"line":64,"text":"\t}"},
  {"line":66,"text":"\tcomparer := organizeImportsComparerSettings{"},
  {"line":67,"text":"\t\tmoduleSpecifierComparer: moduleSpecifierComparer,"},
  {"line":68,"text":"\t\tnamedImportComparer:     namedImportComparer,"},
  {"line":69,"text":"\t\ttypeOrder:               typeOrder,"},
  {"line":70,"text":"\t}"},
  {"line":72,"text":"\tfor _, importGroupDecl := range topLevelImportGroupDecls {"},
  {"line":73,"text":"\t\torganizeImportsWorker(importGroupDecl, comparer, shouldSort, shouldCombine, shouldRemove, sourceFile, program, changeTracker, ctx)"},
  {"line":74,"text":"\t}"},
  {"line":76,"text":"\tif kind != lsproto.CodeActionKindSourceRemoveUnusedImports {"},
  {"line":77,"text":"\t\ttopLevelExportGroupDecls := getTopLevelExportGroups(sourceFile)"},
  {"line":78,"text":"\t\tfor _, exportGroupDecl := range topLevelExportGroupDecls {"},
  {"line":79,"text":"\t\t\torganizeExportsWorker(exportGroupDecl, comparer, sourceFile, changeTracker)"},
  {"line":80,"text":"\t\t}"},
  {"line":81,"text":"\t}"},
  {"line":83,"text":"\tfor _, stmt := range sourceFile.Statements.Nodes {"},
  {"line":84,"text":"\t\tif !ast.IsAmbientModule(stmt.AsNode()) {"},
  {"line":85,"text":"\t\t\tcontinue"},
  {"line":86,"text":"\t\t}"},
  {"line":88,"text":"\t\tambientModule := stmt.AsModuleDeclaration()"},
  {"line":89,"text":"\t\tif ambientModule.Body == nil {"},
  {"line":90,"text":"\t\t\tcontinue"},
  {"line":91,"text":"\t\t}"},
  {"line":93,"text":"\t\tmoduleBody := ambientModule.Body.AsModuleBlock()"},
  {"line":95,"text":"\t\tambientModuleImportDecls := lsutil.FilterImportDeclarations(moduleBody.Statements.Nodes)"},
  {"line":96,"text":"\t\tambientModuleImportGroupDecls := groupByNewlineContiguous(sourceFile, ambientModuleImportDecls)"},
  {"line":98,"text":"\t\tfor _, importGroupDecl := range ambientModuleImportGroupDecls {"},
  {"line":99,"text":"\t\t\torganizeImportsWorker(importGroupDecl, comparer, shouldSort, shouldCombine, shouldRemove, sourceFile, program, changeTracker, ctx)"},
  {"line":100,"text":"\t\t}"},
  {"line":102,"text":"\t\tif kind != lsproto.CodeActionKindSourceRemoveUnusedImports {"},
  {"line":103,"text":"\t\t\tvar ambientModuleExportDecls []*ast.Statement"},
  {"line":104,"text":"\t\t\tfor _, s := range moduleBody.Statements.Nodes {"},
  {"line":105,"text":"\t\t\t\tif s.Kind == ast.KindExportDeclaration {"},
  {"line":106,"text":"\t\t\t\t\tambientModuleExportDecls = append(ambientModuleExportDecls, s)"},
  {"line":107,"text":"\t\t\t\t}"},
  {"line":108,"text":"\t\t\t}"},
  {"line":109,"text":"\t\t\torganizeExportsWorker(ambientModuleExportDecls, comparer, sourceFile, changeTracker)"},
  {"line":110,"text":"\t\t}"},
  {"line":111,"text":"\t}"},
  {"line":113,"text":"\treturn changeTracker.GetChanges()"},
  {"line":114,"text":"}"},
  {"line":116,"text":"type organizeImportsComparerSettings struct {"},
  {"line":117,"text":"\tmoduleSpecifierComparer func(a, b string) int"},
  {"line":118,"text":"\tnamedImportComparer     func(a, b string) int"},
  {"line":119,"text":"\ttypeOrder               lsutil.OrganizeImportsTypeOrder"},
  {"line":120,"text":"}"},
  {"line":122,"text":"func organizeImportsWorker("},
  {"line":123,"text":"\toldImportDecls []*ast.Statement,"},
  {"line":124,"text":"\tcomparer organizeImportsComparerSettings,"},
  {"line":125,"text":"\tshouldSort bool,"},
  {"line":126,"text":"\tshouldCombine bool,"},
  {"line":127,"text":"\tshouldRemove bool,"},
  {"line":128,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":129,"text":"\tprogram *compiler.Program,"},
  {"line":130,"text":"\tchangeTracker *change.Tracker,"},
  {"line":131,"text":"\tctx context.Context,"},
  {"line":132,"text":") {"},
  {"line":133,"text":"\tif len(oldImportDecls) == 0 {"},
  {"line":134,"text":"\t\treturn"},
  {"line":135,"text":"\t}"},
  {"line":139,"text":"\tprocessedImports := slices.Clone(oldImportDecls)"},
  {"line":140,"text":"\tif shouldRemove {"},
  {"line":141,"text":"\t\ttypeChecker, done := program.GetTypeCheckerForFile(ctx, sourceFile)"},
  {"line":142,"text":"\t\tdefer done()"},
  {"line":143,"text":"\t\tprocessedImports = removeUnusedImports(processedImports, sourceFile, typeChecker, program, changeTracker)"},
  {"line":144,"text":"\t}"},
  {"line":146,"text":"\tvar newImportDecls []*ast.Statement"},
  {"line":147,"text":"\tif shouldCombine {"},
  {"line":148,"text":"\t\tgrouped := groupByModuleSpecifier(processedImports)"},
  {"line":149,"text":"\t\tif shouldSort {"},
  {"line":150,"text":"\t\t\tslices.SortFunc(grouped, func(a, b []*ast.Statement) int {"},
  {"line":151,"text":"\t\t\t\tif len(a) == 0 || len(b) == 0 {"},
  {"line":152,"text":"\t\t\t\t\treturn 0"},
  {"line":153,"text":"\t\t\t\t}"},
  {"line":154,"text":"\t\t\t\treturn lsutil.CompareModuleSpecifiers("},
  {"line":155,"text":"\t\t\t\t\ta[0].ModuleSpecifier(),"},
  {"line":156,"text":"\t\t\t\t\tb[0].ModuleSpecifier(),"},
  {"line":157,"text":"\t\t\t\t\tcomparer.moduleSpecifierComparer,"},
  {"line":158,"text":"\t\t\t\t)"},
  {"line":159,"text":"\t\t\t})"},
  {"line":160,"text":"\t\t}"},
  {"line":162,"text":"\t\tspecifierComparer := lsutil.GetNamedImportSpecifierComparer("},
  {"line":163,"text":"\t\t\tlsutil.UserPreferences{OrganizeImportsTypeOrder: comparer.typeOrder},"},
  {"line":164,"text":"\t\t\tcomparer.namedImportComparer,"},
  {"line":165,"text":"\t\t)"},
  {"line":167,"text":"\t\tfor _, importGroup := range grouped {"},
  {"line":168,"text":"\t\t\tcoalesced := coalesceImportsWorker(importGroup, comparer.moduleSpecifierComparer, specifierComparer, sourceFile, changeTracker)"},
  {"line":169,"text":"\t\t\tif shouldSort {"},
  {"line":170,"text":"\t\t\t\tslices.SortFunc(coalesced, func(a, b *ast.Statement) int {"},
  {"line":171,"text":"\t\t\t\t\treturn lsutil.CompareImportsOrRequireStatements(a, b, comparer.moduleSpecifierComparer)"},
  {"line":172,"text":"\t\t\t\t})"},
  {"line":173,"text":"\t\t\t}"},
  {"line":174,"text":"\t\t\tnewImportDecls = append(newImportDecls, coalesced...)"},
  {"line":175,"text":"\t\t}"},
  {"line":176,"text":"\t} else {"},
  {"line":177,"text":"\t\tnewImportDecls = processedImports"},
  {"line":178,"text":"\t}"},
  {"line":180,"text":"\tif shouldSort && !shouldCombine {"},
  {"line":181,"text":"\t\tslices.SortFunc(newImportDecls, func(a, b *ast.Statement) int {"},
  {"line":182,"text":"\t\t\treturn lsutil.CompareImportsOrRequireStatements(a, b, comparer.moduleSpecifierComparer)"},
  {"line":183,"text":"\t\t})"},
  {"line":184,"text":"\t}"},
  {"line":186,"text":"\tif len(newImportDecls) == 0 {"},
  {"line":187,"text":"\t\tchangeTracker.DeleteNodeRange("},
  {"line":188,"text":"\t\t\tsourceFile,"},
  {"line":189,"text":"\t\t\toldImportDecls[0].AsNode(),"},
  {"line":190,"text":"\t\t\toldImportDecls[len(oldImportDecls)-1].AsNode(),"},
  {"line":191,"text":"\t\t\tchange.LeadingTriviaOptionExclude, // Preserve header comment"},
  {"line":192,"text":"\t\t\tchange.TrailingTriviaOptionInclude,"},
  {"line":193,"text":"\t\t)"},
  {"line":194,"text":"\t} else {"},
  {"line":195,"text":"\t\tfor _, imp := range newImportDecls {"},
  {"line":196,"text":"\t\t\tchangeTracker.SetEmitFlags(imp.AsNode(), printer.EFNoLeadingComments)"},
  {"line":197,"text":"\t\t}"},
  {"line":199,"text":"\t\toptions := change.NodeOptions{"},
  {"line":200,"text":"\t\t\tLeadingTriviaOption:  change.LeadingTriviaOptionExclude, // Preserve header comment"},
  {"line":201,"text":"\t\t\tTrailingTriviaOption: change.TrailingTriviaOptionInclude,"},
  {"line":202,"text":"\t\t\tSuffix:               \"\\n\","},
  {"line":203,"text":"\t\t}"},
  {"line":205,"text":"\t\tnewNodes := core.Map(newImportDecls, func(s *ast.Statement) *ast.Node { return s.AsNode() })"},
  {"line":206,"text":"\t\tchangeTracker.ReplaceNodeWithNodes(sourceFile, oldImportDecls[0].AsNode(), newNodes, &options)"},
  {"line":208,"text":"\t\tif len(oldImportDecls) > 1 {"},
  {"line":209,"text":"\t\t\tfor i := 1; i < len(oldImportDecls); i++ {"},
  {"line":210,"text":"\t\t\t\tchangeTracker.Delete(sourceFile, oldImportDecls[i].AsNode())"},
  {"line":211,"text":"\t\t\t}"},
  {"line":212,"text":"\t\t}"},
  {"line":213,"text":"\t}"},
  {"line":214,"text":"}"},
  {"line":216,"text":"func groupByModuleSpecifier(imports []*ast.Statement) [][]*ast.Statement {"},
  {"line":217,"text":"\tgroups := make(map[string][]*ast.Statement)"},
  {"line":218,"text":"\tvar order []string"},
  {"line":220,"text":"\tfor _, imp := range imports {"},
  {"line":221,"text":"\t\tspecifier := lsutil.GetExternalModuleName(imp.ModuleSpecifier())"},
  {"line":222,"text":"\t\tif _, exists := groups[specifier]; !exists {"},
  {"line":223,"text":"\t\t\torder = append(order, specifier)"},
  {"line":224,"text":"\t\t}"},
  {"line":225,"text":"\t\tgroups[specifier] = append(groups[specifier], imp)"},
  {"line":226,"text":"\t}"},
  {"line":228,"text":"\tresult := make([][]*ast.Statement, 0, len(order))"},
  {"line":229,"text":"\tfor _, key := range order {"},
  {"line":230,"text":"\t\tresult = append(result, groups[key])"},
  {"line":231,"text":"\t}"},
  {"line":232,"text":"\treturn result"},
  {"line":233,"text":"}"},
  {"line":235,"text":"func removeUnusedImports(oldImports []*ast.Statement, sourceFile *ast.SourceFile, typeChecker *checker.Checker, program *compiler.Program, changeTracker *change.Tracker) []*ast.Statement {"},
  {"line":236,"text":"\tcompilerOptions := program.Options()"},
  {"line":237,"text":"\tjsxElementsPresent := (sourceFile.AsNode().SubtreeFacts() & ast.SubtreeContainsJsx) != 0"},
  {"line":238,"text":"\tjsxModeNeedsExplicitImport := compilerOptions.Jsx == core.JsxEmitReact || compilerOptions.Jsx == core.JsxEmitReactNative"},
  {"line":240,"text":"\tfactory := ast.NewNodeFactory(ast.NodeFactoryHooks{})"},
  {"line":241,"text":"\tusedImports := make([]*ast.Statement, 0, len(oldImports))"},
  {"line":243,"text":"\tfor _, importDecl := range oldImports {"},
  {"line":244,"text":"\t\timportClause := importDecl.AsImportDeclaration().ImportClause"},
  {"line":245,"text":"\t\tif importClause == nil {"},
  {"line":246,"text":"\t\t\tusedImports = append(usedImports, importDecl)"},
  {"line":247,"text":"\t\t\tcontinue"},
  {"line":248,"text":"\t\t}"},
  {"line":250,"text":"\t\tclause := importClause.AsImportClause()"},
  {"line":251,"text":"\t\tname := clause.Name()"},
  {"line":252,"text":"\t\tnamedBindings := clause.NamedBindings"},
  {"line":254,"text":"\t\tif name != nil && !typeChecker.IsDeclarationUsed(sourceFile, name.AsIdentifier(), jsxElementsPresent, jsxModeNeedsExplicitImport) {"},
  {"line":255,"text":"\t\t\tname = nil"},
  {"line":256,"text":"\t\t}"},
  {"line":258,"text":"\t\tif namedBindings != nil {"},
  {"line":259,"text":"\t\t\tswitch namedBindings.Kind {"},
  {"line":260,"text":"\t\t\tcase ast.KindNamespaceImport:"},
  {"line":261,"text":"\t\t\t\tnsImport := namedBindings.AsNamespaceImport()"},
  {"line":262,"text":"\t\t\t\tif !typeChecker.IsDeclarationUsed(sourceFile, nsImport.Name().AsIdentifier(), jsxElementsPresent, jsxModeNeedsExplicitImport) {"},
  {"line":263,"text":"\t\t\t\t\tnamedBindings = nil"},
  {"line":264,"text":"\t\t\t\t}"},
  {"line":265,"text":"\t\t\tcase ast.KindNamedImports:"},
  {"line":266,"text":"\t\t\t\tnamedImports := namedBindings.AsNamedImports()"},
  {"line":267,"text":"\t\t\t\toriginalBindings := namedBindings"},
  {"line":268,"text":"\t\t\t\tnewElements := filterUsedImportSpecifiers(namedImports.Elements.Nodes, typeChecker, sourceFile, jsxElementsPresent, jsxModeNeedsExplicitImport)"},
  {"line":269,"text":"\t\t\t\tif len(newElements) == 0 {"},
  {"line":270,"text":"\t\t\t\t\tnamedBindings = nil"},
  {"line":271,"text":"\t\t\t\t} else if len(newElements) < len(namedImports.Elements.Nodes) {"},
  {"line":272,"text":"\t\t\t\t\tnewList := factory.NewNodeList(newElements)"},
  {"line":273,"text":"\t\t\t\t\tupdatedNamedImports := factory.UpdateNamedImports(namedImports, newList)"},
  {"line":274,"text":"\t\t\t\t\tnamedBindings = updatedNamedImports.AsNode()"},
  {"line":275,"text":"\t\t\t\t}"},
  {"line":276,"text":"\t\t\t\tif namedBindings != nil && !ast.NodeIsSynthesized(originalBindings.AsNode()) && !printer.RangeIsOnSingleLine(originalBindings.Loc, sourceFile) {"},
  {"line":277,"text":"\t\t\t\t\tchangeTracker.SetEmitFlags(namedBindings, printer.EFMultiLine)"},
  {"line":278,"text":"\t\t\t\t}"},
  {"line":279,"text":"\t\t\t}"},
  {"line":280,"text":"\t\t}"},
  {"line":282,"text":"\t\tif name != nil || namedBindings != nil {"},
  {"line":283,"text":"\t\t\timportDeclNode := importDecl.AsImportDeclaration()"},
  {"line":284,"text":"\t\t\tnewClause := factory.UpdateImportClause(clause, clause.PhaseModifier, name, namedBindings)"},
  {"line":285,"text":"\t\t\tnewImportDecl := factory.UpdateImportDeclaration("},
  {"line":286,"text":"\t\t\t\timportDeclNode,"},
  {"line":287,"text":"\t\t\t\timportDeclNode.Modifiers(),"},
  {"line":288,"text":"\t\t\t\tnewClause.AsNode(),"},
  {"line":289,"text":"\t\t\t\timportDeclNode.ModuleSpecifier,"},
  {"line":290,"text":"\t\t\t\timportDeclNode.Attributes,"},
  {"line":291,"text":"\t\t\t)"},
  {"line":292,"text":"\t\t\tusedImports = append(usedImports, newImportDecl)"},
  {"line":293,"text":"\t\t} else {"},
  {"line":294,"text":"\t\t\tmoduleSpecifier := importDecl.ModuleSpecifier()"},
  {"line":295,"text":"\t\t\tif hasModuleDeclarationMatchingSpecifier(sourceFile, moduleSpecifier) {"},
  {"line":296,"text":"\t\t\t\tif sourceFile.IsDeclarationFile {"},
  {"line":297,"text":"\t\t\t\t\timportDeclNode := importDecl.AsImportDeclaration()"},
  {"line":298,"text":"\t\t\t\t\tnewImportDecl := factory.UpdateImportDeclaration("},
  {"line":299,"text":"\t\t\t\t\t\timportDeclNode,"},
  {"line":300,"text":"\t\t\t\t\t\timportDeclNode.Modifiers(),"},
  {"line":301,"text":"\t\t\t\t\t\tnil, // no import clause"},
  {"line":302,"text":"\t\t\t\t\t\timportDeclNode.ModuleSpecifier,"},
  {"line":303,"text":"\t\t\t\t\t\timportDeclNode.Attributes,"},
  {"line":304,"text":"\t\t\t\t\t)"},
  {"line":305,"text":"\t\t\t\t\tusedImports = append(usedImports, newImportDecl)"},
  {"line":306,"text":"\t\t\t\t} else {"},
  {"line":307,"text":"\t\t\t\t\tusedImports = append(usedImports, importDecl)"},
  {"line":308,"text":"\t\t\t\t}"},
  {"line":309,"text":"\t\t\t}"},
  {"line":310,"text":"\t\t}"},
  {"line":311,"text":"\t}"},
  {"line":313,"text":"\treturn usedImports"},
  {"line":314,"text":"}"},
  {"line":316,"text":"func filterUsedImportSpecifiers("},
  {"line":317,"text":"\telements []*ast.Statement,"},
  {"line":318,"text":"\ttypeChecker *checker.Checker,"},
  {"line":319,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":320,"text":"\tjsxElementsPresent bool,"},
  {"line":321,"text":"\tjsxModeNeedsExplicitImport bool,"},
  {"line":322,"text":") []*ast.Statement {"},
  {"line":323,"text":"\tvar result []*ast.Statement"},
  {"line":324,"text":"\tfor _, elem := range elements {"},
  {"line":325,"text":"\t\tspec := elem.AsImportSpecifier()"},
  {"line":326,"text":"\t\tif typeChecker.IsDeclarationUsed(sourceFile, spec.Name().AsIdentifier(), jsxElementsPresent, jsxModeNeedsExplicitImport) {"},
  {"line":327,"text":"\t\t\tresult = append(result, elem)"},
  {"line":328,"text":"\t\t}"},
  {"line":329,"text":"\t}"},
  {"line":330,"text":"\treturn result"},
  {"line":331,"text":"}"},
  {"line":333,"text":"func hasModuleDeclarationMatchingSpecifier(sourceFile *ast.SourceFile, moduleSpecifier *ast.Expression) bool {"},
  {"line":334,"text":"\tif moduleSpecifier == nil || !ast.IsStringLiteral(moduleSpecifier.AsNode()) {"},
  {"line":335,"text":"\t\treturn false"},
  {"line":336,"text":"\t}"},
  {"line":337,"text":"\tmoduleSpecifierText := moduleSpecifier.Text()"},
  {"line":339,"text":"\tfor _, moduleName := range sourceFile.ModuleAugmentations {"},
  {"line":340,"text":"\t\tif ast.IsStringLiteral(moduleName) && moduleName.Text() == moduleSpecifierText {"},
  {"line":341,"text":"\t\t\treturn true"},
  {"line":342,"text":"\t\t}"},
  {"line":343,"text":"\t}"},
  {"line":345,"text":"\treturn false"},
  {"line":346,"text":"}"},
  {"line":349,"text":"func getImportAttributesKey(attributes *ast.ImportAttributesNode) string {"},
  {"line":350,"text":"\tif attributes == nil {"},
  {"line":351,"text":"\t\treturn \"\""},
  {"line":352,"text":"\t}"},
  {"line":354,"text":"\timportAttrs := attributes.AsImportAttributes()"},
  {"line":355,"text":"\tvar key strings.Builder"},
  {"line":356,"text":"\tkey.WriteString(importAttrs.Token.String())"},
  {"line":357,"text":"\tkey.WriteString(\" \")"},
  {"line":359,"text":"\tattrNodes := make([]*ast.Node, len(importAttrs.Attributes.Nodes))"},
  {"line":360,"text":"\tcopy(attrNodes, importAttrs.Attributes.Nodes)"},
  {"line":361,"text":"\tslices.SortFunc(attrNodes, func(a, b *ast.Node) int {"},
  {"line":362,"text":"\t\taName := a.AsImportAttribute().Name().Text()"},
  {"line":363,"text":"\t\tbName := b.AsImportAttribute().Name().Text()"},
  {"line":364,"text":"\t\treturn stringutil.CompareStringsCaseSensitive(aName, bName)"},
  {"line":365,"text":"\t})"},
  {"line":367,"text":"\tfor _, attrNode := range attrNodes {"},
  {"line":368,"text":"\t\tattr := attrNode.AsImportAttribute()"},
  {"line":369,"text":"\t\tkey.WriteString(attr.Name().Text())"},
  {"line":370,"text":"\t\tkey.WriteString(\":\")"},
  {"line":371,"text":"\t\tif ast.IsStringLiteralLike(attr.Value.AsNode()) {"},
  {"line":372,"text":"\t\t\tkey.WriteString(`\"`)"},
  {"line":373,"text":"\t\t\tkey.WriteString(attr.Value.Text())"},
  {"line":374,"text":"\t\t\tkey.WriteString(`\"`)"},
  {"line":375,"text":"\t\t} else {"},
  {"line":376,"text":"\t\t\tkey.WriteString(attr.Value.AsNode().Text())"},
  {"line":377,"text":"\t\t}"},
  {"line":378,"text":"\t\tkey.WriteString(\" \")"},
  {"line":379,"text":"\t}"},
  {"line":381,"text":"\treturn key.String()"},
  {"line":382,"text":"}"},
  {"line":385,"text":"func groupByNewlineContiguous(sourceFile *ast.SourceFile, decls []*ast.Statement) [][]*ast.Statement {"},
  {"line":386,"text":"\ts := scanner.NewScanner()"},
  {"line":387,"text":"\ts.SetSkipTrivia(false) // Must not skip trivia to detect newlines"},
  {"line":388,"text":"\tvar groups [][]*ast.Statement"},
  {"line":389,"text":"\tvar currentGroup []*ast.Statement"},
  {"line":391,"text":"\tfor _, decl := range decls {"},
  {"line":392,"text":"\t\tif len(currentGroup) > 0 && isNewGroup(sourceFile, decl, s) {"},
  {"line":393,"text":"\t\t\tgroups = append(groups, currentGroup)"},
  {"line":394,"text":"\t\t\tcurrentGroup = nil"},
  {"line":395,"text":"\t\t}"},
  {"line":396,"text":"\t\tcurrentGroup = append(currentGroup, decl)"},
  {"line":397,"text":"\t}"},
  {"line":399,"text":"\tif len(currentGroup) > 0 {"},
  {"line":400,"text":"\t\tgroups = append(groups, currentGroup)"},
  {"line":401,"text":"\t}"},
  {"line":403,"text":"\treturn groups"},
  {"line":404,"text":"}"},
  {"line":406,"text":"func isNewGroup(sourceFile *ast.SourceFile, decl *ast.Statement, s *scanner.Scanner) bool {"},
  {"line":407,"text":"\tfullStart := decl.Pos()"},
  {"line":408,"text":"\tif fullStart < 0 {"},
  {"line":409,"text":"\t\treturn false"},
  {"line":410,"text":"\t}"},
  {"line":412,"text":"\ttext := sourceFile.Text()"},
  {"line":413,"text":"\ttextLen := len(text)"},
  {"line":415,"text":"\tif fullStart >= textLen {"},
  {"line":416,"text":"\t\treturn false"},
  {"line":417,"text":"\t}"},
  {"line":419,"text":"\tstartPos := scanner.SkipTrivia(text, fullStart)"},
  {"line":420,"text":"\tif startPos <= fullStart {"},
  {"line":421,"text":"\t\treturn false"},
  {"line":422,"text":"\t}"},
  {"line":424,"text":"\ttriviaLen := startPos - fullStart"},
  {"line":425,"text":"\ts.SetText(text[fullStart:startPos])"},
  {"line":427,"text":"\tnumberOfNewLines := 0"},
  {"line":428,"text":"\tfor s.TokenStart() < triviaLen {"},
  {"line":429,"text":"\t\ttokenKind := s.Scan()"},
  {"line":430,"text":"\t\tif tokenKind == ast.KindNewLineTrivia {"},
  {"line":431,"text":"\t\t\tnumberOfNewLines++"},
  {"line":432,"text":"\t\t\tif numberOfNewLines >= 2 {"},
  {"line":433,"text":"\t\t\t\treturn true"},
  {"line":434,"text":"\t\t\t}"},
  {"line":435,"text":"\t\t}"},
  {"line":436,"text":"\t}"},
  {"line":438,"text":"\treturn false"},
  {"line":439,"text":"}"},
  {"line":441,"text":"func coalesceImportsWorker("},
  {"line":442,"text":"\timportDecls []*ast.Statement,"},
  {"line":443,"text":"\tcomparer func(a, b string) int,"},
  {"line":444,"text":"\tspecifierComparer func(s1, s2 *ast.Node) int,"},
  {"line":445,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":446,"text":"\tchangeTracker *change.Tracker,"},
  {"line":447,"text":") []*ast.Statement {"},
  {"line":448,"text":"\tif len(importDecls) == 0 {"},
  {"line":449,"text":"\t\treturn importDecls"},
  {"line":450,"text":"\t}"},
  {"line":452,"text":"\timportGroupsByAttributes := make(map[string][]*ast.Statement)"},
  {"line":453,"text":"\tvar attributeKeys []string"},
  {"line":455,"text":"\tfor _, importDecl := range importDecls {"},
  {"line":456,"text":"\t\tkey := getImportAttributesKey(importDecl.AsImportDeclaration().Attributes)"},
  {"line":457,"text":"\t\tif _, exists := importGroupsByAttributes[key]; !exists {"},
  {"line":458,"text":"\t\t\tattributeKeys = append(attributeKeys, key)"},
  {"line":459,"text":"\t\t}"},
  {"line":460,"text":"\t\timportGroupsByAttributes[key] = append(importGroupsByAttributes[key], importDecl)"},
  {"line":461,"text":"\t}"},
  {"line":463,"text":"\tcoalescedImports := make([]*ast.Statement, 0)"},
  {"line":465,"text":"\tfor _, attributeKey := range attributeKeys {"},
  {"line":466,"text":"\t\timportGroupSameAttrs := importGroupsByAttributes[attributeKey]"},
  {"line":467,"text":"\t\tcategorized := getCategorizedImports(importGroupSameAttrs)"},
  {"line":469,"text":"\t\tif categorized.importWithoutClause != nil {"},
  {"line":470,"text":"\t\t\tcoalescedImports = append(coalescedImports, categorized.importWithoutClause)"},
  {"line":471,"text":"\t\t}"},
  {"line":473,"text":"\t\tfactory := ast.NewNodeFactory(ast.NodeFactoryHooks{})"},
  {"line":475,"text":"\t\tfor i, group := range []importGroup{categorized.regularImports, categorized.typeOnlyImports} {"},
  {"line":476,"text":"\t\t\tif group.isEmpty() {"},
  {"line":477,"text":"\t\t\t\tcontinue"},
  {"line":478,"text":"\t\t\t}"},
  {"line":480,"text":"\t\t\tisTypeOnly := i == 1"},
  {"line":482,"text":"\t\t\tif !isTypeOnly && len(group.defaultImports) == 1 && len(group.namespaceImports) == 1 && len(group.namedImports) == 0 {"},
  {"line":483,"text":"\t\t\t\tdefaultImport := group.defaultImports[0]"},
  {"line":484,"text":"\t\t\t\tnamespaceImport := group.namespaceImports[0]"},
  {"line":486,"text":"\t\t\t\tdefaultClause := defaultImport.AsImportDeclaration().ImportClause.AsImportClause()"},
  {"line":487,"text":"\t\t\t\tnamespaceBindings := namespaceImport.AsImportDeclaration().ImportClause.AsImportClause().NamedBindings"},
  {"line":489,"text":"\t\t\t\tnewClause := factory.UpdateImportClause(defaultClause, defaultClause.PhaseModifier, defaultClause.Name(), namespaceBindings)"},
  {"line":490,"text":"\t\t\t\tdefaultDeclNode := defaultImport.AsImportDeclaration()"},
  {"line":491,"text":"\t\t\t\tnewImportDecl := factory.UpdateImportDeclaration("},
  {"line":492,"text":"\t\t\t\t\tdefaultDeclNode,"},
  {"line":493,"text":"\t\t\t\t\tdefaultDeclNode.Modifiers(),"},
  {"line":494,"text":"\t\t\t\t\tnewClause,"},
  {"line":495,"text":"\t\t\t\t\tdefaultDeclNode.ModuleSpecifier,"},
  {"line":496,"text":"\t\t\t\t\tdefaultDeclNode.Attributes,"},
  {"line":497,"text":"\t\t\t\t)"},
  {"line":498,"text":"\t\t\t\tcoalescedImports = append(coalescedImports, newImportDecl)"},
  {"line":499,"text":"\t\t\t\tcontinue"},
  {"line":500,"text":"\t\t\t}"},
  {"line":502,"text":"\t\t\tslices.SortFunc(group.namespaceImports, func(a, b *ast.Statement) int {"},
  {"line":503,"text":"\t\t\t\tn1 := a.AsImportDeclaration().ImportClause.AsImportClause().NamedBindings.AsNamespaceImport().Name()"},
  {"line":504,"text":"\t\t\t\tn2 := b.AsImportDeclaration().ImportClause.AsImportClause().NamedBindings.AsNamespaceImport().Name()"},
  {"line":505,"text":"\t\t\t\treturn comparer(n1.Text(), n2.Text())"},
  {"line":506,"text":"\t\t\t})"},
  {"line":508,"text":"\t\t\tfor _, nsImport := range group.namespaceImports {"},
  {"line":509,"text":"\t\t\t\tnsImportDecl := nsImport.AsImportDeclaration()"},
  {"line":510,"text":"\t\t\t\tclause := nsImportDecl.ImportClause.AsImportClause()"},
  {"line":511,"text":"\t\t\t\tnewClause := factory.UpdateImportClause(clause, clause.PhaseModifier, nil, clause.NamedBindings)"},
  {"line":512,"text":"\t\t\t\tnewImportDecl := factory.UpdateImportDeclaration("},
  {"line":513,"text":"\t\t\t\t\tnsImportDecl,"},
  {"line":514,"text":"\t\t\t\t\tnsImportDecl.Modifiers(),"},
  {"line":515,"text":"\t\t\t\t\tnewClause,"},
  {"line":516,"text":"\t\t\t\t\tnsImportDecl.ModuleSpecifier,"},
  {"line":517,"text":"\t\t\t\t\tnsImportDecl.Attributes,"},
  {"line":518,"text":"\t\t\t\t)"},
  {"line":519,"text":"\t\t\t\tcoalescedImports = append(coalescedImports, newImportDecl)"},
  {"line":520,"text":"\t\t\t}"},
  {"line":522,"text":"\t\t\tvar firstDefaultImport *ast.Statement"},
  {"line":523,"text":"\t\t\tvar firstNamedImport *ast.Statement"},
  {"line":525,"text":"\t\t\tif len(group.defaultImports) > 0 {"},
  {"line":526,"text":"\t\t\t\tfirstDefaultImport = group.defaultImports[0]"},
  {"line":527,"text":"\t\t\t}"},
  {"line":528,"text":"\t\t\tif len(group.namedImports) > 0 {"},
  {"line":529,"text":"\t\t\t\tfirstNamedImport = group.namedImports[0]"},
  {"line":530,"text":"\t\t\t}"},
  {"line":532,"text":"\t\t\timportDecl := firstDefaultImport"},
  {"line":533,"text":"\t\t\tif importDecl == nil {"},
  {"line":534,"text":"\t\t\t\timportDecl = firstNamedImport"},
  {"line":535,"text":"\t\t\t}"},
  {"line":536,"text":"\t\t\tif importDecl == nil {"},
  {"line":537,"text":"\t\t\t\tcontinue"},
  {"line":538,"text":"\t\t\t}"},
  {"line":540,"text":"\t\t\tvar newDefaultImport *ast.IdentifierNode"},
  {"line":541,"text":"\t\t\tvar newImportSpecifiers []*ast.Node"},
  {"line":543,"text":"\t\t\tif len(group.defaultImports) == 1 {"},
  {"line":544,"text":"\t\t\t\tnewDefaultImport = group.defaultImports[0].AsImportDeclaration().ImportClause.AsImportClause().Name()"},
  {"line":545,"text":"\t\t\t} else {"},
  {"line":546,"text":"\t\t\t\tfor _, defaultImport := range group.defaultImports {"},
  {"line":547,"text":"\t\t\t\t\tdefaultClause := defaultImport.AsImportDeclaration().ImportClause.AsImportClause()"},
  {"line":548,"text":"\t\t\t\t\tdefaultName := defaultClause.Name()"},
  {"line":549,"text":"\t\t\t\t\tpropertyName := factory.NewIdentifier(\"default\")"},
  {"line":550,"text":"\t\t\t\t\timportSpec := factory.NewImportSpecifier(false, propertyName, defaultName)"},
  {"line":551,"text":"\t\t\t\t\tnewImportSpecifiers = append(newImportSpecifiers, importSpec)"},
  {"line":552,"text":"\t\t\t\t}"},
  {"line":553,"text":"\t\t\t}"},
  {"line":555,"text":"\t\t\tnewImportSpecifiers = append(newImportSpecifiers, getNewImportSpecifiers(group.namedImports, factory)...)"},
  {"line":556,"text":"\t\t\tslices.SortStableFunc(newImportSpecifiers, specifierComparer)"},
  {"line":558,"text":"\t\t\tvar newNamedImports *ast.NamedImportBindings"},
  {"line":559,"text":"\t\t\tif len(newImportSpecifiers) == 0 {"},
  {"line":560,"text":"\t\t\t\tif newDefaultImport != nil {"},
  {"line":561,"text":"\t\t\t\t\tnewNamedImports = nil"},
  {"line":562,"text":"\t\t\t\t} else {"},
  {"line":563,"text":"\t\t\t\t\tnewNamedImports = factory.NewNamedImports(factory.NewNodeList(nil))"},
  {"line":564,"text":"\t\t\t\t}"},
  {"line":565,"text":"\t\t\t} else {"},
  {"line":566,"text":"\t\t\t\tsortedList := factory.NewNodeList(newImportSpecifiers)"},
  {"line":567,"text":"\t\t\t\tif firstNamedImport != nil {"},
  {"line":568,"text":"\t\t\t\t\tfirstNamedBindings := firstNamedImport.AsImportDeclaration().ImportClause.AsImportClause().NamedBindings.AsNamedImports()"},
  {"line":569,"text":"\t\t\t\t\toriginalElements := firstNamedBindings.Elements"},
  {"line":570,"text":"\t\t\t\t\tif originalElements.HasTrailingComma() {"},
  {"line":571,"text":"\t\t\t\t\t\tsortedList.Loc = originalElements.Loc"},
  {"line":572,"text":"\t\t\t\t\t}"},
  {"line":573,"text":"\t\t\t\t\tnewNamedImports = factory.UpdateNamedImports(firstNamedBindings, sortedList).AsNode()"},
  {"line":574,"text":"\t\t\t\t} else {"},
  {"line":575,"text":"\t\t\t\t\tnewNamedImports = factory.NewNamedImports(sortedList)"},
  {"line":576,"text":"\t\t\t\t}"},
  {"line":577,"text":"\t\t\t}"},
  {"line":579,"text":"\t\t\tif sourceFile != nil && newNamedImports != nil && firstNamedImport != nil {"},
  {"line":580,"text":"\t\t\t\tfirstNamedBindings := firstNamedImport.AsImportDeclaration().ImportClause.AsImportClause().NamedBindings"},
  {"line":581,"text":"\t\t\t\tif !ast.NodeIsSynthesized(firstNamedBindings.AsNode()) && !printer.RangeIsOnSingleLine(firstNamedBindings.Loc, sourceFile) {"},
  {"line":582,"text":"\t\t\t\t\tchangeTracker.SetEmitFlags(newNamedImports.AsNode(), printer.EFMultiLine)"},
  {"line":583,"text":"\t\t\t\t}"},
  {"line":584,"text":"\t\t\t}"},
  {"line":586,"text":"\t\t\tif isTypeOnly && newDefaultImport != nil && newNamedImports != nil {"},
  {"line":587,"text":"\t\t\t\timportDeclNode := importDecl.AsImportDeclaration()"},
  {"line":589,"text":"\t\t\t\tdefaultClause := factory.NewImportClause(importDeclNode.ImportClause.AsImportClause().PhaseModifier, newDefaultImport, nil)"},
  {"line":590,"text":"\t\t\t\tdefaultImportDecl := factory.UpdateImportDeclaration("},
  {"line":591,"text":"\t\t\t\t\timportDeclNode,"},
  {"line":592,"text":"\t\t\t\t\timportDeclNode.Modifiers(),"},
  {"line":593,"text":"\t\t\t\t\tdefaultClause,"},
  {"line":594,"text":"\t\t\t\t\timportDeclNode.ModuleSpecifier,"},
  {"line":595,"text":"\t\t\t\t\timportDeclNode.Attributes,"},
  {"line":596,"text":"\t\t\t\t)"},
  {"line":597,"text":"\t\t\t\tcoalescedImports = append(coalescedImports, defaultImportDecl)"},
  {"line":599,"text":"\t\t\t\tnamedDeclNode := firstNamedImport"},
  {"line":600,"text":"\t\t\t\tif namedDeclNode == nil {"},
  {"line":601,"text":"\t\t\t\t\tnamedDeclNode = importDecl"},
  {"line":602,"text":"\t\t\t\t}"},
  {"line":603,"text":"\t\t\t\tnamedImportDeclNode := namedDeclNode.AsImportDeclaration()"},
  {"line":604,"text":"\t\t\t\tnamedClause := factory.NewImportClause(namedImportDeclNode.ImportClause.AsImportClause().PhaseModifier, nil, newNamedImports)"},
  {"line":605,"text":"\t\t\t\tnamedImportDecl := factory.UpdateImportDeclaration("},
  {"line":606,"text":"\t\t\t\t\tnamedImportDeclNode,"},
  {"line":607,"text":"\t\t\t\t\tnamedImportDeclNode.Modifiers(),"},
  {"line":608,"text":"\t\t\t\t\tnamedClause,"},
  {"line":609,"text":"\t\t\t\t\tnamedImportDeclNode.ModuleSpecifier,"},
  {"line":610,"text":"\t\t\t\t\tnamedImportDeclNode.Attributes,"},
  {"line":611,"text":"\t\t\t\t)"},
  {"line":612,"text":"\t\t\t\tcoalescedImports = append(coalescedImports, namedImportDecl)"},
  {"line":613,"text":"\t\t\t} else {"},
  {"line":614,"text":"\t\t\t\timportDeclNode := importDecl.AsImportDeclaration()"},
  {"line":615,"text":"\t\t\t\tclauseNode := importDeclNode.ImportClause.AsImportClause()"},
  {"line":616,"text":"\t\t\t\tnewClause := factory.UpdateImportClause(clauseNode, clauseNode.PhaseModifier, newDefaultImport, newNamedImports)"},
  {"line":617,"text":"\t\t\t\tnewImportDecl := factory.UpdateImportDeclaration("},
  {"line":618,"text":"\t\t\t\t\timportDeclNode,"},
  {"line":619,"text":"\t\t\t\t\timportDeclNode.Modifiers(),"},
  {"line":620,"text":"\t\t\t\t\tnewClause,"},
  {"line":621,"text":"\t\t\t\t\timportDeclNode.ModuleSpecifier,"},
  {"line":622,"text":"\t\t\t\t\timportDeclNode.Attributes,"},
  {"line":623,"text":"\t\t\t\t)"},
  {"line":624,"text":"\t\t\t\tcoalescedImports = append(coalescedImports, newImportDecl)"},
  {"line":625,"text":"\t\t\t}"},
  {"line":626,"text":"\t\t}"},
  {"line":627,"text":"\t}"},
  {"line":628,"text":"\treturn coalescedImports"},
  {"line":629,"text":"}"},
  {"line":631,"text":"type categorizedImports struct {"},
  {"line":632,"text":"\timportWithoutClause *ast.Statement"},
  {"line":633,"text":"\ttypeOnlyImports     importGroup"},
  {"line":634,"text":"\tregularImports      importGroup"},
  {"line":635,"text":"}"},
  {"line":637,"text":"type importGroup struct {"},
  {"line":638,"text":"\tdefaultImports   []*ast.Statement"},
  {"line":639,"text":"\tnamespaceImports []*ast.Statement"},
  {"line":640,"text":"\tnamedImports     []*ast.Statement"},
  {"line":641,"text":"}"},
  {"line":643,"text":"func (g importGroup) isEmpty() bool {"},
  {"line":644,"text":"\treturn len(g.defaultImports) == 0 && len(g.namespaceImports) == 0 && len(g.namedImports) == 0"},
  {"line":645,"text":"}"},
  {"line":647,"text":"func getCategorizedImports(importDecls []*ast.Statement) categorizedImports {"},
  {"line":648,"text":"\tvar importWithoutClause *ast.Statement"},
  {"line":649,"text":"\tvar typeOnlyImports, regularImports importGroup"},
  {"line":651,"text":"\tfor _, importDecl := range importDecls {"},
  {"line":652,"text":"\t\tif importDecl.AsImportDeclaration().ImportClause == nil {"},
  {"line":653,"text":"\t\t\tif importWithoutClause == nil {"},
  {"line":654,"text":"\t\t\t\timportWithoutClause = importDecl"},
  {"line":655,"text":"\t\t\t}"},
  {"line":656,"text":"\t\t\tcontinue"},
  {"line":657,"text":"\t\t}"},
  {"line":659,"text":"\t\tclause := importDecl.AsImportDeclaration().ImportClause.AsImportClause()"},
  {"line":660,"text":"\t\tgroup := &regularImports"},
  {"line":661,"text":"\t\tif clause.IsTypeOnly() {"},
  {"line":662,"text":"\t\t\tgroup = &typeOnlyImports"},
  {"line":663,"text":"\t\t}"},
  {"line":665,"text":"\t\tname := clause.Name()"},
  {"line":666,"text":"\t\tnamedBindings := clause.NamedBindings"},
  {"line":668,"text":"\t\tif name != nil {"},
  {"line":669,"text":"\t\t\tgroup.defaultImports = append(group.defaultImports, importDecl)"},
  {"line":670,"text":"\t\t}"},
  {"line":672,"text":"\t\tif namedBindings != nil {"},
  {"line":673,"text":"\t\t\tswitch namedBindings.Kind {"},
  {"line":674,"text":"\t\t\tcase ast.KindNamespaceImport:"},
  {"line":675,"text":"\t\t\t\tgroup.namespaceImports = append(group.namespaceImports, importDecl)"},
  {"line":676,"text":"\t\t\tcase ast.KindNamedImports:"},
  {"line":677,"text":"\t\t\t\tgroup.namedImports = append(group.namedImports, importDecl)"},
  {"line":678,"text":"\t\t\t}"},
  {"line":679,"text":"\t\t}"},
  {"line":680,"text":"\t}"},
  {"line":682,"text":"\treturn categorizedImports{"},
  {"line":683,"text":"\t\timportWithoutClause: importWithoutClause,"},
  {"line":684,"text":"\t\ttypeOnlyImports:     typeOnlyImports,"},
  {"line":685,"text":"\t\tregularImports:      regularImports,"},
  {"line":686,"text":"\t}"},
  {"line":687,"text":"}"},
  {"line":689,"text":"func getNewImportSpecifiers(namedImports []*ast.Statement, factory *ast.NodeFactory) []*ast.Node {"},
  {"line":690,"text":"\tvar result []*ast.Node"},
  {"line":692,"text":"\tfor _, namedImport := range namedImports {"},
  {"line":693,"text":"\t\telements := tryGetNamedBindingElements(namedImport)"},
  {"line":694,"text":"\t\tif elements == nil {"},
  {"line":695,"text":"\t\t\tcontinue"},
  {"line":696,"text":"\t\t}"},
  {"line":698,"text":"\t\tfor _, elem := range elements {"},
  {"line":699,"text":"\t\t\tspec := elem.AsImportSpecifier()"},
  {"line":701,"text":"\t\t\tif spec.PropertyName != nil && spec.Name() != nil {"},
  {"line":702,"text":"\t\t\t\tpropertyText := spec.PropertyName.Text()"},
  {"line":703,"text":"\t\t\t\tnameText := spec.Name().Text()"},
  {"line":705,"text":"\t\t\t\tif propertyText == nameText {"},
  {"line":706,"text":"\t\t\t\t\tnormalized := factory.UpdateImportSpecifier(spec, spec.IsTypeOnly, nil, spec.Name())"},
  {"line":707,"text":"\t\t\t\t\tresult = append(result, normalized)"},
  {"line":708,"text":"\t\t\t\t\tcontinue"},
  {"line":709,"text":"\t\t\t\t}"},
  {"line":710,"text":"\t\t\t}"},
  {"line":712,"text":"\t\t\tresult = append(result, elem)"},
  {"line":713,"text":"\t\t}"},
  {"line":714,"text":"\t}"},
  {"line":716,"text":"\treturn result"},
  {"line":717,"text":"}"},
  {"line":719,"text":"func tryGetNamedBindingElements(namedImport *ast.Statement) []*ast.Statement {"},
  {"line":720,"text":"\tif namedImport.Kind != ast.KindImportDeclaration {"},
  {"line":721,"text":"\t\treturn nil"},
  {"line":722,"text":"\t}"},
  {"line":724,"text":"\timportDecl := namedImport.AsImportDeclaration()"},
  {"line":725,"text":"\tif importDecl.ImportClause == nil {"},
  {"line":726,"text":"\t\treturn nil"},
  {"line":727,"text":"\t}"},
  {"line":729,"text":"\tclause := importDecl.ImportClause.AsImportClause()"},
  {"line":730,"text":"\tnamedBindings := clause.NamedBindings"},
  {"line":732,"text":"\tif namedBindings != nil && namedBindings.Kind == ast.KindNamedImports {"},
  {"line":733,"text":"\t\tnamedImportsNode := namedBindings.AsNamedImports()"},
  {"line":734,"text":"\t\treturn namedImportsNode.Elements.Nodes"},
  {"line":735,"text":"\t}"},
  {"line":737,"text":"\treturn nil"},
  {"line":738,"text":"}"},
  {"line":740,"text":"func getTopLevelExportGroups(sourceFile *ast.SourceFile) [][]*ast.Statement {"},
  {"line":741,"text":"\tvar topLevelExportGroups [][]*ast.Statement"},
  {"line":742,"text":"\tstatements := sourceFile.Statements.Nodes"},
  {"line":743,"text":"\tstatementsLen := len(statements)"},
  {"line":745,"text":"\ti := 0"},
  {"line":746,"text":"\tgroupIndex := 0"},
  {"line":747,"text":"\tfor i < statementsLen {"},
  {"line":748,"text":"\t\tif statements[i].Kind == ast.KindExportDeclaration {"},
  {"line":749,"text":"\t\t\tif groupIndex >= len(topLevelExportGroups) {"},
  {"line":750,"text":"\t\t\t\ttopLevelExportGroups = append(topLevelExportGroups, []*ast.Statement{})"},
  {"line":751,"text":"\t\t\t}"},
  {"line":752,"text":"\t\t\texportDecl := statements[i].AsExportDeclaration()"},
  {"line":753,"text":"\t\t\tif exportDecl.ModuleSpecifier != nil {"},
  {"line":754,"text":"\t\t\t\ttopLevelExportGroups[groupIndex] = append(topLevelExportGroups[groupIndex], statements[i])"},
  {"line":755,"text":"\t\t\t\ti++"},
  {"line":756,"text":"\t\t\t} else {"},
  {"line":757,"text":"\t\t\t\tfor i < statementsLen && statements[i].Kind == ast.KindExportDeclaration {"},
  {"line":758,"text":"\t\t\t\t\ttopLevelExportGroups[groupIndex] = append(topLevelExportGroups[groupIndex], statements[i])"},
  {"line":759,"text":"\t\t\t\t\ti++"},
  {"line":760,"text":"\t\t\t\t}"},
  {"line":761,"text":"\t\t\t\tgroupIndex++"},
  {"line":762,"text":"\t\t\t}"},
  {"line":763,"text":"\t\t} else {"},
  {"line":764,"text":"\t\t\ti++"},
  {"line":765,"text":"\t\t\tif groupIndex < len(topLevelExportGroups) && len(topLevelExportGroups[groupIndex]) > 0 {"},
  {"line":766,"text":"\t\t\t\tgroupIndex++"},
  {"line":767,"text":"\t\t\t}"},
  {"line":768,"text":"\t\t}"},
  {"line":769,"text":"\t}"},
  {"line":771,"text":"\tvar result [][]*ast.Statement"},
  {"line":772,"text":"\tfor _, exportGroup := range topLevelExportGroups {"},
  {"line":773,"text":"\t\tsubGroups := groupByNewlineContiguous(sourceFile, exportGroup)"},
  {"line":774,"text":"\t\tresult = append(result, subGroups...)"},
  {"line":775,"text":"\t}"},
  {"line":777,"text":"\treturn result"},
  {"line":778,"text":"}"},
  {"line":780,"text":"func organizeExportsWorker("},
  {"line":781,"text":"\toldExportDecls []*ast.Statement,"},
  {"line":782,"text":"\tcomparer organizeImportsComparerSettings,"},
  {"line":783,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":784,"text":"\tchangeTracker *change.Tracker,"},
  {"line":785,"text":") {"},
  {"line":786,"text":"\tif len(oldExportDecls) == 0 {"},
  {"line":787,"text":"\t\treturn"},
  {"line":788,"text":"\t}"},
  {"line":790,"text":"\tspecifierComparerFunc := lsutil.GetNamedImportSpecifierComparer("},
  {"line":791,"text":"\t\tlsutil.UserPreferences{OrganizeImportsTypeOrder: comparer.typeOrder},"},
  {"line":792,"text":"\t\tcomparer.namedImportComparer,"},
  {"line":793,"text":"\t)"},
  {"line":795,"text":"\tnewExportDecls := coalesceExportsWorker(oldExportDecls, specifierComparerFunc, comparer.moduleSpecifierComparer, sourceFile, changeTracker)"},
  {"line":797,"text":"\tif len(oldExportDecls) > 0 {"},
  {"line":798,"text":"\t\tif len(newExportDecls) == 0 {"},
  {"line":799,"text":"\t\t\tchangeTracker.DeleteNodeRange("},
  {"line":800,"text":"\t\t\t\tsourceFile,"},
  {"line":801,"text":"\t\t\t\toldExportDecls[0].AsNode(),"},
  {"line":802,"text":"\t\t\t\toldExportDecls[len(oldExportDecls)-1].AsNode(),"},
  {"line":803,"text":"\t\t\t\tchange.LeadingTriviaOptionExclude,"},
  {"line":804,"text":"\t\t\t\tchange.TrailingTriviaOptionInclude,"},
  {"line":805,"text":"\t\t\t)"},
  {"line":806,"text":"\t\t} else {"},
  {"line":807,"text":"\t\t\tfor _, exp := range newExportDecls {"},
  {"line":808,"text":"\t\t\t\tchangeTracker.AddEmitFlags(exp.AsNode(), printer.EFNoLeadingComments)"},
  {"line":809,"text":"\t\t\t}"},
  {"line":811,"text":"\t\t\toptions := change.NodeOptions{"},
  {"line":812,"text":"\t\t\t\tLeadingTriviaOption:  change.LeadingTriviaOptionExclude,"},
  {"line":813,"text":"\t\t\t\tTrailingTriviaOption: change.TrailingTriviaOptionInclude,"},
  {"line":814,"text":"\t\t\t\tSuffix:               \"\\n\","},
  {"line":815,"text":"\t\t\t}"},
  {"line":817,"text":"\t\t\tnewNodes := core.Map(newExportDecls, func(s *ast.Statement) *ast.Node { return s.AsNode() })"},
  {"line":818,"text":"\t\t\tchangeTracker.ReplaceNodeWithNodes(sourceFile, oldExportDecls[0].AsNode(), newNodes, &options)"},
  {"line":820,"text":"\t\t\tif len(oldExportDecls) > 1 {"},
  {"line":821,"text":"\t\t\t\tfor i := 1; i < len(oldExportDecls); i++ {"},
  {"line":822,"text":"\t\t\t\t\tchangeTracker.Delete(sourceFile, oldExportDecls[i].AsNode())"},
  {"line":823,"text":"\t\t\t\t}"},
  {"line":824,"text":"\t\t\t}"},
  {"line":825,"text":"\t\t}"},
  {"line":826,"text":"\t}"},
  {"line":827,"text":"}"},
  {"line":829,"text":"func coalesceExportsWorker("},
  {"line":830,"text":"\texportGroup []*ast.Statement,"},
  {"line":831,"text":"\tspecifierComparer func(s1, s2 *ast.Node) int,"},
  {"line":832,"text":"\tmoduleSpecifierComparer func(a, b string) int,"},
  {"line":833,"text":"\tsourceFile *ast.SourceFile,"},
  {"line":834,"text":"\tchangeTracker *change.Tracker,"},
  {"line":835,"text":") []*ast.Statement {"},
  {"line":836,"text":"\tif len(exportGroup) == 0 {"},
  {"line":837,"text":"\t\treturn exportGroup"},
  {"line":838,"text":"\t}"},
  {"line":840,"text":"\texportsByModuleSpecifier := make(map[string][]*ast.Statement)"},
  {"line":841,"text":"\tvar moduleSpecifierOrder []string"},
  {"line":843,"text":"\tfor _, exportDecl := range exportGroup {"},
  {"line":844,"text":"\t\texport := exportDecl.AsExportDeclaration()"},
  {"line":845,"text":"\t\tvar moduleSpecifier string"},
  {"line":846,"text":"\t\tif export.ModuleSpecifier != nil {"},
  {"line":847,"text":"\t\t\tmoduleSpecifier = export.ModuleSpecifier.Text()"},
  {"line":848,"text":"\t\t}"},
  {"line":849,"text":"\t\tif _, exists := exportsByModuleSpecifier[moduleSpecifier]; !exists {"},
  {"line":850,"text":"\t\t\tmoduleSpecifierOrder = append(moduleSpecifierOrder, moduleSpecifier)"},
  {"line":851,"text":"\t\t}"},
  {"line":852,"text":"\t\texportsByModuleSpecifier[moduleSpecifier] = append(exportsByModuleSpecifier[moduleSpecifier], exportDecl)"},
  {"line":853,"text":"\t}"},
  {"line":855,"text":"\tslices.SortStableFunc(moduleSpecifierOrder, func(a, b string) int {"},
  {"line":856,"text":"\t\tif a == \"\" && b != \"\" {"},
  {"line":857,"text":"\t\t\treturn 1"},
  {"line":858,"text":"\t\t}"},
  {"line":859,"text":"\t\tif a != \"\" && b == \"\" {"},
  {"line":860,"text":"\t\t\treturn -1"},
  {"line":861,"text":"\t\t}"},
  {"line":862,"text":"\t\treturn moduleSpecifierComparer(a, b)"},
  {"line":863,"text":"\t})"},
  {"line":865,"text":"\tvar coalescedExports []*ast.Statement"},
  {"line":866,"text":"\tfactory := ast.NewNodeFactory(ast.NodeFactoryHooks{})"},
  {"line":868,"text":"\tfor _, moduleSpecifier := range moduleSpecifierOrder {"},
  {"line":869,"text":"\t\tgroup := exportsByModuleSpecifier[moduleSpecifier]"},
  {"line":871,"text":"\t\tcategorized := getCategorizedExports(group)"},
  {"line":873,"text":"\t\tif categorized.exportWithoutClause != nil {"},
  {"line":874,"text":"\t\t\tcoalescedExports = append(coalescedExports, categorized.exportWithoutClause)"},
  {"line":875,"text":"\t\t}"},
  {"line":877,"text":"\t\tfor _, subGroup := range [][]*ast.Statement{categorized.namedExports, categorized.typeOnlyExports} {"},
  {"line":878,"text":"\t\t\tif len(subGroup) == 0 {"},
  {"line":879,"text":"\t\t\t\tcontinue"},
  {"line":880,"text":"\t\t\t}"},
  {"line":882,"text":"\t\t\tvar newExportSpecifiers []*ast.Node"},
  {"line":883,"text":"\t\t\tfor _, exportDecl := range subGroup {"},
  {"line":884,"text":"\t\t\t\texportClause := exportDecl.AsExportDeclaration().ExportClause"},
  {"line":885,"text":"\t\t\t\tif exportClause != nil && exportClause.Kind == ast.KindNamedExports {"},
  {"line":886,"text":"\t\t\t\t\tnamedExports := exportClause.AsNamedExports()"},
  {"line":887,"text":"\t\t\t\t\tnewExportSpecifiers = append(newExportSpecifiers, namedExports.Elements.Nodes...)"},
  {"line":888,"text":"\t\t\t\t}"},
  {"line":889,"text":"\t\t\t}"},
  {"line":891,"text":"\t\t\tslices.SortStableFunc(newExportSpecifiers, specifierComparer)"},
  {"line":893,"text":"\t\t\texportDecl := subGroup[0].AsExportDeclaration()"},
  {"line":895,"text":"\t\t\tvar updatedExportClause *ast.NamedExportBindings"},
  {"line":896,"text":"\t\t\tif exportDecl.ExportClause != nil {"},
  {"line":897,"text":"\t\t\t\tif exportDecl.ExportClause.Kind == ast.KindNamedExports {"},
  {"line":898,"text":"\t\t\t\t\tnamedExports := exportDecl.ExportClause.AsNamedExports()"},
  {"line":899,"text":"\t\t\t\t\tsortedList := factory.NewNodeList(newExportSpecifiers)"},
  {"line":900,"text":"\t\t\t\t\tupdatedExportClause = factory.UpdateNamedExports(namedExports, sortedList)"},
  {"line":902,"text":"\t\t\t\t\tif sourceFile != nil && !ast.NodeIsSynthesized(namedExports.AsNode()) && !printer.RangeIsOnSingleLine(namedExports.Loc, sourceFile) {"},
  {"line":903,"text":"\t\t\t\t\t\tchangeTracker.SetEmitFlags(updatedExportClause.AsNode(), printer.EFMultiLine)"},
  {"line":904,"text":"\t\t\t\t\t}"},
  {"line":905,"text":"\t\t\t\t} else {"},
  {"line":906,"text":"\t\t\t\t\tupdatedExportClause = exportDecl.ExportClause"},
  {"line":907,"text":"\t\t\t\t}"},
  {"line":908,"text":"\t\t\t}"},
  {"line":910,"text":"\t\t\tnewExportDecl := factory.UpdateExportDeclaration("},
  {"line":911,"text":"\t\t\t\texportDecl,"},
  {"line":912,"text":"\t\t\t\texportDecl.Modifiers(),"},
  {"line":913,"text":"\t\t\t\texportDecl.IsTypeOnly,"},
  {"line":914,"text":"\t\t\t\tupdatedExportClause,"},
  {"line":915,"text":"\t\t\t\texportDecl.ModuleSpecifier,"},
  {"line":916,"text":"\t\t\t\texportDecl.Attributes,"},
  {"line":917,"text":"\t\t\t)"},
  {"line":918,"text":"\t\t\tcoalescedExports = append(coalescedExports, newExportDecl)"},
  {"line":919,"text":"\t\t}"},
  {"line":920,"text":"\t}"},
  {"line":922,"text":"\treturn coalescedExports"},
  {"line":923,"text":"}"},
  {"line":925,"text":"type categorizedExports struct {"},
  {"line":926,"text":"\texportWithoutClause *ast.Statement"},
  {"line":927,"text":"\tnamedExports        []*ast.Statement"},
  {"line":928,"text":"\ttypeOnlyExports     []*ast.Statement"},
  {"line":929,"text":"}"},
  {"line":931,"text":"func getCategorizedExports(exportGroup []*ast.Statement) categorizedExports {"},
  {"line":932,"text":"\tvar exportWithoutClause *ast.Statement"},
  {"line":933,"text":"\tvar namedExports, typeOnlyExports []*ast.Statement"},
  {"line":935,"text":"\tfor _, exportDecl := range exportGroup {"},
  {"line":936,"text":"\t\texport := exportDecl.AsExportDeclaration()"},
  {"line":937,"text":"\t\tif export.ExportClause == nil {"},
  {"line":938,"text":"\t\t\tif exportWithoutClause == nil {"},
  {"line":939,"text":"\t\t\t\texportWithoutClause = exportDecl"},
  {"line":940,"text":"\t\t\t}"},
  {"line":941,"text":"\t\t} else if export.IsTypeOnly {"},
  {"line":942,"text":"\t\t\ttypeOnlyExports = append(typeOnlyExports, exportDecl)"},
  {"line":943,"text":"\t\t} else {"},
  {"line":944,"text":"\t\t\tnamedExports = append(namedExports, exportDecl)"},
  {"line":945,"text":"\t\t}"},
  {"line":946,"text":"\t}"},
  {"line":948,"text":"\treturn categorizedExports{"},
  {"line":949,"text":"\t\texportWithoutClause: exportWithoutClause,"},
  {"line":950,"text":"\t\tnamedExports:        namedExports,"},
  {"line":951,"text":"\t\ttypeOnlyExports:     typeOnlyExports,"},
  {"line":952,"text":"\t}"},
  {"line":953,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsOrganizeImportsSourceLines.find((entry) => entry.line === line)?.text;
}
