/**
 * Language-service parity map for TS-Go `ls/sourcedefinition.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionUpstreamPath = "ls/sourcedefinition.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionDeclarations: readonly UpstreamDeclaration[] = [
  {"line":24,"kind":"func","name":"ProvideSourceDefinition","receiver":"l *LanguageService"},
  {"line":111,"kind":"type","name":"sourceDefResolver"},
  {"line":121,"kind":"func","name":"newSourceDefResolver","receiver":"l *LanguageService"},
  {"line":141,"kind":"func","name":"resolveFromCheckerInfo","receiver":"r *sourceDefResolver"},
  {"line":177,"kind":"func","name":"getSourceDefCheckerInfo"},
  {"line":233,"kind":"func","name":"resolveTripleSlashReference","receiver":"r *sourceDefResolver"},
  {"line":263,"kind":"func","name":"searchImplementationFile","receiver":"r *sourceDefResolver"},
  {"line":291,"kind":"func","name":"isDefaultImportName"},
  {"line":298,"kind":"func","name":"getSourceDefinitionEntryNode"},
  {"line":305,"kind":"func","name":"getSourceDefinitionEntryDeclarations"},
  {"line":309,"kind":"func","name":"mapDeclarationToSource","receiver":"r *sourceDefResolver"},
  {"line":340,"kind":"func","name":"findImplementationFileFromDtsFileName","receiver":"r *sourceDefResolver"},
  {"line":383,"kind":"func","name":"resolveImplementation","receiver":"r *sourceDefResolver"},
  {"line":390,"kind":"func","name":"resolveImplementationFrom","receiver":"r *sourceDefResolver"},
  {"line":412,"kind":"func","name":"getOrParseSourceFile","receiver":"r *sourceDefResolver"},
  {"line":437,"kind":"func","name":"inferImpliedNodeFormat","receiver":"r *sourceDefResolver"},
  {"line":447,"kind":"func","name":"findContainingModuleSpecifier"},
  {"line":458,"kind":"func","name":"findDeclarationsInFile","receiver":"r *sourceDefResolver"},
  {"line":493,"kind":"func","name":"getForwardedImplementationFiles","receiver":"r *sourceDefResolver"},
  {"line":506,"kind":"func","name":"getCandidateSourceDeclarationNames"},
  {"line":544,"kind":"func","name":"findDeclarationNodesByName"},
  {"line":606,"kind":"func","name":"getContainerDepth"},
  {"line":616,"kind":"func","name":"filterPreferredSourceDeclarations"},
  {"line":629,"kind":"func","name":"getPropertyLikeSourceDeclarations"},
  {"line":651,"kind":"func","name":"hasConcreteSourceDeclarations"},
  {"line":655,"kind":"func","name":"isConcreteSourceDeclaration"},
  {"line":678,"kind":"func","name":"uniqueDeclarationNodes"},
  {"line":699,"kind":"func","name":"findClosestDeclarationNode"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"math\""},
  {"line":6,"text":"\t\"slices\""},
  {"line":7,"text":"\t\"strings\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/binder\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/module\""},
  {"line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/modulespecifiers\""},
  {"line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/parser\""},
  {"line":20,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"line":21,"text":"\t\"github.com/microsoft/typescript-go/internal/vfs\""},
  {"line":22,"text":")"},
  {"line":24,"text":"func (l *LanguageService) ProvideSourceDefinition("},
  {"line":25,"text":"\tctx context.Context,"},
  {"line":26,"text":"\tdocumentURI lsproto.DocumentUri,"},
  {"line":27,"text":"\tposition lsproto.Position,"},
  {"line":28,"text":") (lsproto.DefinitionResponse, error) {"},
  {"line":29,"text":"\tcaps := lsproto.GetClientCapabilities(ctx)"},
  {"line":30,"text":"\tclientSupportsLink := caps.TextDocument.Definition.LinkSupport"},
  {"line":32,"text":"\tprogram, file := l.getProgramAndFile(documentURI)"},
  {"line":33,"text":"\tpos := int(l.converters.LineAndCharacterToPosition(file, position))"},
  {"line":34,"text":"\tresolver := l.newSourceDefResolver(program, file.FileName())"},
  {"line":35,"text":"\tnode := astnav.GetTouchingPropertyName(file, pos)"},
  {"line":37,"text":"\tif node.Kind == ast.KindSourceFile {"},
  {"line":40,"text":"\t\tif declarations, ref := resolver.resolveTripleSlashReference(file, pos, program); len(declarations) != 0 {"},
  {"line":41,"text":"\t\t\toriginSelectionRange := l.createLspRangeFromBounds(ref.Pos(), ref.End(), file)"},
  {"line":42,"text":"\t\t\treturn l.createDefinitionLocations(originSelectionRange, clientSupportsLink, declarations, nil /*reference*/), nil"},
  {"line":43,"text":"\t\t}"},
  {"line":44,"text":"\t\treturn lsproto.LocationOrLocationsOrDefinitionLinksOrNull{}, nil"},
  {"line":45,"text":"\t}"},
  {"line":47,"text":"\toriginSelectionRange := l.createLspRangeFromNode(node, file)"},
  {"line":51,"text":"\tcontainingModuleSpecifier := findContainingModuleSpecifier(node)"},
  {"line":52,"text":"\tif node == containingModuleSpecifier {"},
  {"line":53,"text":"\t\tspecifierMode := program.GetModeForUsageLocation(file, containingModuleSpecifier)"},
  {"line":54,"text":"\t\tif implementationFile := resolver.resolveImplementation(containingModuleSpecifier.Text(), specifierMode); implementationFile != \"\" {"},
  {"line":55,"text":"\t\t\tif sourceFile := resolver.getOrParseSourceFile(implementationFile); sourceFile != nil {"},
  {"line":56,"text":"\t\t\t\treturn l.createDefinitionLocations(originSelectionRange, clientSupportsLink, getSourceDefinitionEntryDeclarations(sourceFile), nil), nil"},
  {"line":57,"text":"\t\t\t}"},
  {"line":58,"text":"\t\t}"},
  {"line":59,"text":"\t\treturn l.provideDefinitionWorker(ctx, documentURI, position)"},
  {"line":60,"text":"\t}"},
  {"line":66,"text":"\tvar resolvedImplFile string"},
  {"line":67,"text":"\tif containingModuleSpecifier != nil {"},
  {"line":68,"text":"\t\tspecifierMode := program.GetModeForUsageLocation(file, containingModuleSpecifier)"},
  {"line":69,"text":"\t\tresolvedImplFile = resolver.resolveImplementation(containingModuleSpecifier.Text(), specifierMode)"},
  {"line":70,"text":"\t}"},
  {"line":72,"text":"\tif resolvedImplFile != \"\" {"},
  {"line":73,"text":"\t\tnames := getCandidateSourceDeclarationNames(node, nil)"},
  {"line":74,"text":"\t\tmoduleResults := resolver.searchImplementationFile(node, resolvedImplFile, names)"},
  {"line":75,"text":"\t\tif len(moduleResults) != 0 {"},
  {"line":76,"text":"\t\t\tif !ast.IsPartOfTypeNode(node) && !ast.IsPartOfTypeOnlyImportOrExportDeclaration(node) || hasConcreteSourceDeclarations(moduleResults) {"},
  {"line":77,"text":"\t\t\t\treturn l.createDefinitionLocations(originSelectionRange, clientSupportsLink, uniqueDeclarationNodes(moduleResults), nil), nil"},
  {"line":78,"text":"\t\t\t}"},
  {"line":79,"text":"\t\t}"},
  {"line":80,"text":"\t}"},
  {"line":86,"text":"\tcheckerDeclarations, moduleSpecifier := getSourceDefCheckerInfo(ctx, program, file, node)"},
  {"line":89,"text":"\tdeclarations := resolver.resolveFromCheckerInfo(node, resolvedImplFile, checkerDeclarations, moduleSpecifier)"},
  {"line":90,"text":"\tif len(declarations) == 0 {"},
  {"line":96,"text":"\t\tif containingModuleSpecifier != nil && resolvedImplFile != \"\" && !hasConcreteSourceDeclarations(checkerDeclarations) {"},
  {"line":97,"text":"\t\t\tif sourceFile := resolver.getOrParseSourceFile(resolvedImplFile); sourceFile != nil {"},
  {"line":98,"text":"\t\t\t\treturn l.createDefinitionLocations(originSelectionRange, clientSupportsLink, getSourceDefinitionEntryDeclarations(sourceFile), nil), nil"},
  {"line":99,"text":"\t\t\t}"},
  {"line":100,"text":"\t\t}"},
  {"line":101,"text":"\t\treturn l.provideDefinitionWorker(ctx, documentURI, position)"},
  {"line":102,"text":"\t}"},
  {"line":103,"text":"\treturn l.createDefinitionLocations(originSelectionRange, clientSupportsLink, declarations, nil /*reference*/), nil"},
  {"line":104,"text":"}"},
  {"line":111,"text":"type sourceDefResolver struct {"},
  {"line":112,"text":"\tls            *LanguageService"},
  {"line":113,"text":"\tfs            vfs.FS"},
  {"line":114,"text":"\toptions       *core.CompilerOptions"},
  {"line":115,"text":"\tgetSourceFile func(string) *ast.SourceFile"},
  {"line":116,"text":"\tresolveFrom   string"},
  {"line":117,"text":"\tresolver      *module.Resolver"},
  {"line":118,"text":"\tparsedFiles   map[string]*ast.SourceFile"},
  {"line":119,"text":"}"},
  {"line":121,"text":"func (l *LanguageService) newSourceDefResolver("},
  {"line":122,"text":"\tprogram *compiler.Program,"},
  {"line":123,"text":"\tresolveFrom string,"},
  {"line":124,"text":") *sourceDefResolver {"},
  {"line":125,"text":"\toptions := program.Options()"},
  {"line":126,"text":"\tnoDtsOptions := options.Clone()"},
  {"line":127,"text":"\tnoDtsOptions.NoDtsResolution = core.TSTrue"},
  {"line":128,"text":"\treturn &sourceDefResolver{"},
  {"line":129,"text":"\t\tls:            l,"},
  {"line":130,"text":"\t\tfs:            program.Host().FS(),"},
  {"line":131,"text":"\t\toptions:       options,"},
  {"line":132,"text":"\t\tgetSourceFile: program.GetSourceFile,"},
  {"line":133,"text":"\t\tresolveFrom:   resolveFrom,"},
  {"line":134,"text":"\t\tresolver:      module.NewResolver(program.Host(), noDtsOptions, program.GetGlobalTypingsCacheLocation(), \"\"),"},
  {"line":135,"text":"\t}"},
  {"line":136,"text":"}"},
  {"line":141,"text":"func (r *sourceDefResolver) resolveFromCheckerInfo("},
  {"line":142,"text":"\tnode *ast.Node,"},
  {"line":143,"text":"\tresolvedImplFile string,"},
  {"line":144,"text":"\tcheckerDeclarations []*ast.Node,"},
  {"line":145,"text":"\tmoduleSpecifier string,"},
  {"line":146,"text":") []*ast.Node {"},
  {"line":150,"text":"\tif resolvedImplFile == \"\" && moduleSpecifier != \"\" {"},
  {"line":151,"text":"\t\tresolvedImplFile = r.resolveImplementation(moduleSpecifier, r.inferImpliedNodeFormat(r.resolveFrom))"},
  {"line":152,"text":"\t}"},
  {"line":156,"text":"\tif len(checkerDeclarations) == 0 && resolvedImplFile != \"\" {"},
  {"line":157,"text":"\t\tnames := getCandidateSourceDeclarationNames(node, nil)"},
  {"line":158,"text":"\t\tif results := r.searchImplementationFile(node, resolvedImplFile, names); results != nil {"},
  {"line":159,"text":"\t\t\treturn uniqueDeclarationNodes(results)"},
  {"line":160,"text":"\t\t}"},
  {"line":161,"text":"\t}"},
  {"line":163,"text":"\tvar declarations []*ast.Node"},
  {"line":164,"text":"\tfor _, declaration := range checkerDeclarations {"},
  {"line":165,"text":"\t\tdeclarations = append(declarations, r.mapDeclarationToSource(node, declaration, resolvedImplFile)...)"},
  {"line":166,"text":"\t}"},
  {"line":167,"text":"\tdeclarations = uniqueDeclarationNodes(declarations)"},
  {"line":168,"text":"\tif hasConcreteSourceDeclarations(declarations) {"},
  {"line":169,"text":"\t\treturn declarations"},
  {"line":170,"text":"\t}"},
  {"line":171,"text":"\treturn nil"},
  {"line":172,"text":"}"},
  {"line":177,"text":"func getSourceDefCheckerInfo("},
  {"line":178,"text":"\tctx context.Context,"},
  {"line":179,"text":"\tprogram *compiler.Program,"},
  {"line":180,"text":"\tfile *ast.SourceFile,"},
  {"line":181,"text":"\tnode *ast.Node,"},
  {"line":182,"text":") ([]*ast.Node, string) {"},
  {"line":183,"text":"\tc, done := program.GetTypeCheckerForFile(ctx, file)"},
  {"line":184,"text":"\tdefer done()"},
  {"line":186,"text":"\tdeclarations := getDeclarationsFromLocation(c, node)"},
  {"line":187,"text":"\tisPropertyName := node.Parent != nil && ast.IsAccessExpression(node.Parent) && node.Parent.Name() == node"},
  {"line":188,"text":"\tif len(declarations) == 0 && isPropertyName {"},
  {"line":189,"text":"\t\tif left := node.Parent.Expression(); left != nil {"},
  {"line":190,"text":"\t\t\tif prop := c.GetPropertyOfType(c.GetTypeAtLocation(left), node.Text()); prop != nil {"},
  {"line":191,"text":"\t\t\t\tdeclarations = prop.Declarations"},
  {"line":192,"text":"\t\t\t}"},
  {"line":193,"text":"\t\t}"},
  {"line":194,"text":"\t}"},
  {"line":195,"text":"\tif calledDeclaration := tryGetSignatureDeclaration(c, node); calledDeclaration != nil {"},
  {"line":196,"text":"\t\tnonFunctionDeclarations := core.Filter(declarations, func(node *ast.Node) bool { return !ast.IsFunctionLike(node) })"},
  {"line":197,"text":"\t\tdeclarations = append(nonFunctionDeclarations, calledDeclaration)"},
  {"line":198,"text":"\t}"},
  {"line":203,"text":"\tvar moduleSpecifier string"},
  {"line":204,"text":"\tresolveNode := node"},
  {"line":205,"text":"\tif isPropertyName {"},
  {"line":206,"text":"\t\texpr := node.Parent.Expression()"},
  {"line":207,"text":"\t\tfor expr != nil && ast.IsAccessExpression(expr) {"},
  {"line":208,"text":"\t\t\texpr = expr.Expression()"},
  {"line":209,"text":"\t\t}"},
  {"line":210,"text":"\t\tif expr != nil {"},
  {"line":211,"text":"\t\t\tresolveNode = expr"},
  {"line":212,"text":"\t\t}"},
  {"line":213,"text":"\t}"},
  {"line":214,"text":"\tif sym := c.GetSymbolAtLocation(resolveNode); sym != nil {"},
  {"line":215,"text":"\t\tfor _, d := range sym.Declarations {"},
  {"line":216,"text":"\t\t\tif !ast.IsImportSpecifier(d) && !ast.IsImportClause(d) && !ast.IsNamespaceImport(d) && !ast.IsImportEqualsDeclaration(d) {"},
  {"line":217,"text":"\t\t\t\tcontinue"},
  {"line":218,"text":"\t\t\t}"},
  {"line":219,"text":"\t\t\tif spec := checker.TryGetModuleSpecifierFromDeclaration(d); spec != nil {"},
  {"line":220,"text":"\t\t\t\tmoduleSpecifier = spec.Text()"},
  {"line":221,"text":"\t\t\t\tbreak"},
  {"line":222,"text":"\t\t\t}"},
  {"line":223,"text":"\t\t}"},
  {"line":224,"text":"\t}"},
  {"line":226,"text":"\treturn declarations, moduleSpecifier"},
  {"line":227,"text":"}"},
  {"line":233,"text":"func (r *sourceDefResolver) resolveTripleSlashReference(file *ast.SourceFile, pos int, program *compiler.Program) ([]*ast.Node, *ast.FileReference) {"},
  {"line":234,"text":"\tref := getReferenceAtPosition(file, pos, program)"},
  {"line":235,"text":"\tif ref == nil || ref.file == nil {"},
  {"line":236,"text":"\t\treturn nil, nil"},
  {"line":237,"text":"\t}"},
  {"line":240,"text":"\tif !ref.file.IsDeclarationFile {"},
  {"line":241,"text":"\t\treturn getSourceDefinitionEntryDeclarations(ref.file), ref.reference"},
  {"line":242,"text":"\t}"},
  {"line":246,"text":"\tdtsFileName := ref.file.FileName()"},
  {"line":247,"text":"\tpreferredMode := r.inferImpliedNodeFormat(dtsFileName)"},
  {"line":248,"text":"\timplementationFile := r.findImplementationFileFromDtsFileName(dtsFileName, preferredMode)"},
  {"line":249,"text":"\tif implementationFile == \"\" {"},
  {"line":250,"text":"\t\treturn nil, nil"},
  {"line":251,"text":"\t}"},
  {"line":253,"text":"\tsourceFile := r.getOrParseSourceFile(implementationFile)"},
  {"line":254,"text":"\tif sourceFile == nil {"},
  {"line":255,"text":"\t\treturn nil, nil"},
  {"line":256,"text":"\t}"},
  {"line":257,"text":"\treturn getSourceDefinitionEntryDeclarations(sourceFile), ref.reference"},
  {"line":258,"text":"}"},
  {"line":263,"text":"func (r *sourceDefResolver) searchImplementationFile("},
  {"line":264,"text":"\toriginalNode *ast.Node,"},
  {"line":265,"text":"\timplementationFile string,"},
  {"line":266,"text":"\tnames []string,"},
  {"line":267,"text":") []*ast.Node {"},
  {"line":268,"text":"\tif implementationFile == \"\" {"},
  {"line":269,"text":"\t\treturn nil"},
  {"line":270,"text":"\t}"},
  {"line":271,"text":"\tsourceFile := r.getOrParseSourceFile(implementationFile)"},
  {"line":272,"text":"\tif sourceFile == nil {"},
  {"line":273,"text":"\t\treturn nil"},
  {"line":274,"text":"\t}"},
  {"line":275,"text":"\tif isDefaultImportName(originalNode) {"},
  {"line":278,"text":"\t\tdefaultDeclarations := r.findDeclarationsInFile(implementationFile, []string{\"default\"}, &collections.Set[string]{})"},
  {"line":279,"text":"\t\tif len(defaultDeclarations) != 0 {"},
  {"line":280,"text":"\t\t\treturn filterPreferredSourceDeclarations(originalNode, defaultDeclarations)"},
  {"line":281,"text":"\t\t}"},
  {"line":282,"text":"\t\treturn getSourceDefinitionEntryDeclarations(sourceFile)"},
  {"line":283,"text":"\t}"},
  {"line":284,"text":"\tdeclarations := r.findDeclarationsInFile(implementationFile, names, &collections.Set[string]{})"},
  {"line":285,"text":"\tif len(declarations) != 0 {"},
  {"line":286,"text":"\t\treturn filterPreferredSourceDeclarations(originalNode, declarations)"},
  {"line":287,"text":"\t}"},
  {"line":288,"text":"\treturn nil"},
  {"line":289,"text":"}"},
  {"line":291,"text":"func isDefaultImportName(node *ast.Node) bool {"},
  {"line":292,"text":"\tif node == nil || node.Parent == nil || !ast.IsImportClause(node.Parent) || node.Parent.Name() != node || node.Parent.Parent == nil {"},
  {"line":293,"text":"\t\treturn false"},
  {"line":294,"text":"\t}"},
  {"line":295,"text":"\treturn ast.IsDefaultImport(node.Parent.Parent)"},
  {"line":296,"text":"}"},
  {"line":298,"text":"func getSourceDefinitionEntryNode(sourceFile *ast.SourceFile) *ast.Node {"},
  {"line":299,"text":"\tif len(sourceFile.Statements.Nodes) != 0 {"},
  {"line":300,"text":"\t\treturn sourceFile.Statements.Nodes[0].AsNode()"},
  {"line":301,"text":"\t}"},
  {"line":302,"text":"\treturn sourceFile.AsNode()"},
  {"line":303,"text":"}"},
  {"line":305,"text":"func getSourceDefinitionEntryDeclarations(sourceFile *ast.SourceFile) []*ast.Node {"},
  {"line":306,"text":"\treturn []*ast.Node{getSourceDefinitionEntryNode(sourceFile)}"},
  {"line":307,"text":"}"},
  {"line":309,"text":"func (r *sourceDefResolver) mapDeclarationToSource("},
  {"line":310,"text":"\toriginalNode *ast.Node,"},
  {"line":311,"text":"\tdeclaration *ast.Node,"},
  {"line":312,"text":"\tresolvedImplFile string,"},
  {"line":313,"text":") []*ast.Node {"},
  {"line":314,"text":"\tfile, startPos := getFileAndStartPosFromDeclaration(declaration)"},
  {"line":315,"text":"\tfileName := file.FileName()"},
  {"line":317,"text":"\tif mapped := r.ls.tryGetSourcePosition(fileName, startPos); mapped != nil {"},
  {"line":318,"text":"\t\tif sourceFile := r.getOrParseSourceFile(mapped.FileName); sourceFile != nil {"},
  {"line":319,"text":"\t\t\treturn []*ast.Node{findClosestDeclarationNode(sourceFile, mapped.Pos)}"},
  {"line":320,"text":"\t\t}"},
  {"line":321,"text":"\t}"},
  {"line":323,"text":"\tif !tspath.IsDeclarationFileName(fileName) {"},
  {"line":324,"text":"\t\treturn []*ast.Node{declaration}"},
  {"line":325,"text":"\t}"},
  {"line":327,"text":"\timplementationFile := resolvedImplFile"},
  {"line":328,"text":"\tif implementationFile == \"\" {"},
  {"line":332,"text":"\t\tdtsFileName := ast.GetSourceFileOfNode(declaration).FileName()"},
  {"line":333,"text":"\t\tpreferredMode := r.inferImpliedNodeFormat(dtsFileName)"},
  {"line":334,"text":"\t\timplementationFile = r.findImplementationFileFromDtsFileName(dtsFileName, preferredMode)"},
  {"line":335,"text":"\t}"},
  {"line":337,"text":"\treturn r.searchImplementationFile(originalNode, implementationFile, getCandidateSourceDeclarationNames(originalNode, declaration))"},
  {"line":338,"text":"}"},
  {"line":340,"text":"func (r *sourceDefResolver) findImplementationFileFromDtsFileName("},
  {"line":341,"text":"\tdtsFileName string,"},
  {"line":342,"text":"\tpreferredMode core.ResolutionMode,"},
  {"line":343,"text":") string {"},
  {"line":344,"text":"\tif jsExt := module.TryGetJSExtensionForFile(dtsFileName, r.options); jsExt != \"\" {"},
  {"line":345,"text":"\t\tcandidate := tspath.ChangeExtension(dtsFileName, jsExt)"},
  {"line":346,"text":"\t\tif r.fs.FileExists(candidate) {"},
  {"line":347,"text":"\t\t\treturn candidate"},
  {"line":348,"text":"\t\t}"},
  {"line":349,"text":"\t}"},
  {"line":351,"text":"\tparts := modulespecifiers.GetNodeModulePathParts(dtsFileName)"},
  {"line":352,"text":"\tif parts == nil {"},
  {"line":353,"text":"\t\treturn \"\""},
  {"line":354,"text":"\t}"},
  {"line":358,"text":"\tif strings.LastIndex(dtsFileName, \"/node_modules/\") != parts.TopLevelNodeModulesIndex {"},
  {"line":359,"text":"\t\treturn \"\""},
  {"line":360,"text":"\t}"},
  {"line":362,"text":"\tpackageNamePathPart := dtsFileName[parts.TopLevelPackageNameIndex+1 : parts.PackageRootIndex]"},
  {"line":363,"text":"\tpackageName := module.GetPackageNameFromTypesPackageName(module.UnmangleScopedPackageName(packageNamePathPart))"},
  {"line":364,"text":"\tif packageName == \"\" {"},
  {"line":365,"text":"\t\treturn \"\""},
  {"line":366,"text":"\t}"},
  {"line":368,"text":"\tpathToFileInPackage := dtsFileName[parts.PackageRootIndex+1:]"},
  {"line":374,"text":"\tif pathToFileInPackage != \"\" {"},
  {"line":375,"text":"\t\tspecifier := packageName + \"/\" + tspath.RemoveFileExtension(pathToFileInPackage)"},
  {"line":376,"text":"\t\tif implementationFile := r.resolveImplementation(specifier, preferredMode); implementationFile != \"\" {"},
  {"line":377,"text":"\t\t\treturn implementationFile"},
  {"line":378,"text":"\t\t}"},
  {"line":379,"text":"\t}"},
  {"line":380,"text":"\treturn r.resolveImplementation(packageName, preferredMode)"},
  {"line":381,"text":"}"},
  {"line":383,"text":"func (r *sourceDefResolver) resolveImplementation("},
  {"line":384,"text":"\tmoduleName string,"},
  {"line":385,"text":"\tpreferredMode core.ResolutionMode,"},
  {"line":386,"text":") string {"},
  {"line":387,"text":"\treturn r.resolveImplementationFrom(moduleName, r.resolveFrom, preferredMode)"},
  {"line":388,"text":"}"},
  {"line":390,"text":"func (r *sourceDefResolver) resolveImplementationFrom("},
  {"line":391,"text":"\tmoduleName string,"},
  {"line":392,"text":"\tresolveFromFile string,"},
  {"line":393,"text":"\tpreferredMode core.ResolutionMode,"},
  {"line":394,"text":") string {"},
  {"line":395,"text":"\tmodes := []core.ResolutionMode{preferredMode}"},
  {"line":396,"text":"\tif preferredMode != core.ModuleKindESNext {"},
  {"line":397,"text":"\t\tmodes = append(modes, core.ModuleKindESNext)"},
  {"line":398,"text":"\t}"},
  {"line":399,"text":"\tif preferredMode != core.ModuleKindCommonJS {"},
  {"line":400,"text":"\t\tmodes = append(modes, core.ModuleKindCommonJS)"},
  {"line":401,"text":"\t}"},
  {"line":403,"text":"\tfor _, mode := range modes {"},
  {"line":404,"text":"\t\tresolved, _ := r.resolver.ResolveModuleName(moduleName, resolveFromFile, mode, nil)"},
  {"line":405,"text":"\t\tif resolved != nil && resolved.IsResolved() && !tspath.IsDeclarationFileName(resolved.ResolvedFileName) {"},
  {"line":406,"text":"\t\t\treturn resolved.ResolvedFileName"},
  {"line":407,"text":"\t\t}"},
  {"line":408,"text":"\t}"},
  {"line":409,"text":"\treturn \"\""},
  {"line":410,"text":"}"},
  {"line":412,"text":"func (r *sourceDefResolver) getOrParseSourceFile(fileName string) *ast.SourceFile {"},
  {"line":413,"text":"\tif sourceFile := r.getSourceFile(fileName); sourceFile != nil {"},
  {"line":414,"text":"\t\treturn sourceFile"},
  {"line":415,"text":"\t}"},
  {"line":416,"text":"\tif sourceFile, ok := r.parsedFiles[fileName]; ok {"},
  {"line":417,"text":"\t\treturn sourceFile"},
  {"line":418,"text":"\t}"},
  {"line":419,"text":"\tvar sourceFile *ast.SourceFile"},
  {"line":420,"text":"\tif text, ok := r.ls.ReadFile(fileName); ok {"},
  {"line":421,"text":"\t\tsourceFile = parser.ParseSourceFile("},
  {"line":422,"text":"\t\t\tast.SourceFileParseOptions{FileName: fileName, Path: r.ls.toPath(fileName)},"},
  {"line":423,"text":"\t\t\ttext,"},
  {"line":424,"text":"\t\t\tcore.GetScriptKindFromFileName(fileName),"},
  {"line":425,"text":"\t\t)"},
  {"line":426,"text":"\t\tbinder.BindSourceFile(sourceFile)"},
  {"line":427,"text":"\t}"},
  {"line":428,"text":"\tif r.parsedFiles == nil {"},
  {"line":429,"text":"\t\tr.parsedFiles = map[string]*ast.SourceFile{}"},
  {"line":430,"text":"\t}"},
  {"line":431,"text":"\tr.parsedFiles[fileName] = sourceFile"},
  {"line":432,"text":"\treturn sourceFile"},
  {"line":433,"text":"}"},
  {"line":437,"text":"func (r *sourceDefResolver) inferImpliedNodeFormat(fileName string) core.ResolutionMode {"},
  {"line":438,"text":"\tvar packageJsonType string"},
  {"line":439,"text":"\tif scope := r.resolver.GetPackageScopeForPath(tspath.GetDirectoryPath(fileName)); scope.Exists() {"},
  {"line":440,"text":"\t\tif value, ok := scope.Contents.Type.GetValue(); ok {"},
  {"line":441,"text":"\t\t\tpackageJsonType = value"},
  {"line":442,"text":"\t\t}"},
  {"line":443,"text":"\t}"},
  {"line":444,"text":"\treturn ast.GetImpliedNodeFormatForFile(fileName, packageJsonType)"},
  {"line":445,"text":"}"},
  {"line":447,"text":"func findContainingModuleSpecifier(node *ast.Node) *ast.Node {"},
  {"line":448,"text":"\tfor current := node; current != nil; current = current.Parent {"},
  {"line":449,"text":"\t\tif ast.IsAnyImportOrReExport(current) || ast.IsRequireCall(current, true /*requireStringLiteralLikeArgument*/) || ast.IsImportCall(current) {"},
  {"line":450,"text":"\t\t\tif moduleSpecifier := ast.GetExternalModuleName(current); moduleSpecifier != nil && ast.IsStringLiteralLike(moduleSpecifier) {"},
  {"line":451,"text":"\t\t\t\treturn moduleSpecifier"},
  {"line":452,"text":"\t\t\t}"},
  {"line":453,"text":"\t\t}"},
  {"line":454,"text":"\t}"},
  {"line":455,"text":"\treturn nil"},
  {"line":456,"text":"}"},
  {"line":458,"text":"func (r *sourceDefResolver) findDeclarationsInFile("},
  {"line":459,"text":"\tfileName string,"},
  {"line":460,"text":"\tnames []string,"},
  {"line":461,"text":"\tseen *collections.Set[string],"},
  {"line":462,"text":") []*ast.Node {"},
  {"line":463,"text":"\tif fileName == \"\" || len(names) == 0 {"},
  {"line":464,"text":"\t\treturn nil"},
  {"line":465,"text":"\t}"},
  {"line":466,"text":"\tif !seen.AddIfAbsent(fileName) {"},
  {"line":467,"text":"\t\treturn nil"},
  {"line":468,"text":"\t}"},
  {"line":470,"text":"\tsourceFile := r.getOrParseSourceFile(fileName)"},
  {"line":471,"text":"\tif sourceFile == nil {"},
  {"line":472,"text":"\t\treturn nil"},
  {"line":473,"text":"\t}"},
  {"line":475,"text":"\tdeclarations := findDeclarationNodesByName(sourceFile, names)"},
  {"line":476,"text":"\tif len(declarations) != 0 && hasConcreteSourceDeclarations(declarations) {"},
  {"line":477,"text":"\t\treturn declarations"},
  {"line":478,"text":"\t}"},
  {"line":480,"text":"\tvar forwarded []*ast.Node"},
  {"line":481,"text":"\tfor _, forwardedFile := range r.getForwardedImplementationFiles(sourceFile) {"},
  {"line":482,"text":"\t\tforwarded = append(forwarded, r.findDeclarationsInFile(forwardedFile, names, seen)...)"},
  {"line":483,"text":"\t}"},
  {"line":484,"text":"\tif len(forwarded) != 0 {"},
  {"line":485,"text":"\t\tif hasConcreteSourceDeclarations(forwarded) {"},
  {"line":486,"text":"\t\t\treturn uniqueDeclarationNodes(forwarded)"},
  {"line":487,"text":"\t\t}"},
  {"line":488,"text":"\t\treturn uniqueDeclarationNodes(append(slices.Clip(declarations), forwarded...))"},
  {"line":489,"text":"\t}"},
  {"line":490,"text":"\treturn declarations"},
  {"line":491,"text":"}"},
  {"line":493,"text":"func (r *sourceDefResolver) getForwardedImplementationFiles(sourceFile *ast.SourceFile) []string {"},
  {"line":494,"text":"\tpreferredMode := r.inferImpliedNodeFormat(sourceFile.FileName())"},
  {"line":496,"text":"\tvar files []string"},
  {"line":497,"text":"\tfor _, imp := range sourceFile.Imports() {"},
  {"line":498,"text":"\t\tmoduleName := imp.Text()"},
  {"line":499,"text":"\t\tif implementationFile := r.resolveImplementationFrom(moduleName, sourceFile.FileName(), preferredMode); implementationFile != \"\" {"},
  {"line":500,"text":"\t\t\tfiles = append(files, implementationFile)"},
  {"line":501,"text":"\t\t}"},
  {"line":502,"text":"\t}"},
  {"line":503,"text":"\treturn core.Deduplicate(files)"},
  {"line":504,"text":"}"},
  {"line":506,"text":"func getCandidateSourceDeclarationNames(originalNode *ast.Node, declaration *ast.Node) []string {"},
  {"line":507,"text":"\tvar names []string"},
  {"line":508,"text":"\tif declaration != nil {"},
  {"line":509,"text":"\t\tif name := ast.GetNameOfDeclaration(declaration); name != nil {"},
  {"line":510,"text":"\t\t\tif text := ast.GetTextOfPropertyName(name); text != \"\" {"},
  {"line":511,"text":"\t\t\t\tnames = append(names, text)"},
  {"line":512,"text":"\t\t\t}"},
  {"line":513,"text":"\t\t}"},
  {"line":514,"text":"\t\tif declaration.Kind == ast.KindExportAssignment {"},
  {"line":515,"text":"\t\t\tnames = append(names, \"default\")"},
  {"line":516,"text":"\t\t}"},
  {"line":517,"text":"\t\tif (ast.IsFunctionDeclaration(declaration) || ast.IsClassDeclaration(declaration)) && declaration.ModifierFlags()&ast.ModifierFlagsExportDefault == ast.ModifierFlagsExportDefault {"},
  {"line":518,"text":"\t\t\tnames = append(names, \"default\")"},
  {"line":519,"text":"\t\t}"},
  {"line":520,"text":"\t\tif ast.IsImportSpecifier(declaration) || ast.IsExportSpecifier(declaration) {"},
  {"line":521,"text":"\t\t\tif propName := declaration.PropertyName(); propName != nil {"},
  {"line":522,"text":"\t\t\t\tnames = append(names, propName.Text())"},
  {"line":523,"text":"\t\t\t}"},
  {"line":524,"text":"\t\t}"},
  {"line":525,"text":"\t}"},
  {"line":526,"text":"\tif originalNode != nil {"},
  {"line":527,"text":"\t\tif ast.IsIdentifier(originalNode) || ast.IsPrivateIdentifier(originalNode) {"},
  {"line":528,"text":"\t\t\tnames = append(names, originalNode.Text())"},
  {"line":529,"text":"\t\t}"},
  {"line":530,"text":"\t\tif isDefaultImportName(originalNode) {"},
  {"line":531,"text":"\t\t\tnames = append(names, \"default\")"},
  {"line":532,"text":"\t\t}"},
  {"line":533,"text":"\t\tif originalNode.Parent != nil {"},
  {"line":534,"text":"\t\t\tif ast.IsImportSpecifier(originalNode.Parent) || ast.IsExportSpecifier(originalNode.Parent) {"},
  {"line":535,"text":"\t\t\t\tif propName := originalNode.Parent.PropertyName(); propName != nil {"},
  {"line":536,"text":"\t\t\t\t\tnames = append(names, propName.Text())"},
  {"line":537,"text":"\t\t\t\t}"},
  {"line":538,"text":"\t\t\t}"},
  {"line":539,"text":"\t\t}"},
  {"line":540,"text":"\t}"},
  {"line":541,"text":"\treturn names"},
  {"line":542,"text":"}"},
  {"line":544,"text":"func findDeclarationNodesByName(sourceFile *ast.SourceFile, names []string) []*ast.Node {"},
  {"line":545,"text":"\tnames = core.Deduplicate(core.Filter(names, func(name string) bool { return name != \"\" }))"},
  {"line":546,"text":"\tif len(names) == 0 {"},
  {"line":547,"text":"\t\treturn nil"},
  {"line":548,"text":"\t}"},
  {"line":550,"text":"\tvar wanted collections.Set[string]"},
  {"line":551,"text":"\twantDefault := false"},
  {"line":552,"text":"\tfor _, name := range names {"},
  {"line":553,"text":"\t\tif name == \"default\" {"},
  {"line":554,"text":"\t\t\twantDefault = true"},
  {"line":555,"text":"\t\t\tcontinue"},
  {"line":556,"text":"\t\t}"},
  {"line":557,"text":"\t\twanted.Add(name)"},
  {"line":558,"text":"\t}"},
  {"line":560,"text":"\ttype candidate struct {"},
  {"line":561,"text":"\t\tnode  *ast.Node"},
  {"line":562,"text":"\t\tdepth int"},
  {"line":563,"text":"\t}"},
  {"line":564,"text":"\tvar candidates []candidate"},
  {"line":565,"text":"\tminDepth := math.MaxInt"},
  {"line":567,"text":"\tvar visit ast.Visitor"},
  {"line":568,"text":"\tvisit = func(node *ast.Node) bool {"},
  {"line":569,"text":"\t\tmatched := false"},
  {"line":570,"text":"\t\tif name := ast.GetNameOfDeclaration(node); name != nil {"},
  {"line":571,"text":"\t\t\tif text := ast.GetTextOfPropertyName(name); text != \"\" {"},
  {"line":572,"text":"\t\t\t\tif wanted.Has(text) {"},
  {"line":573,"text":"\t\t\t\t\tmatched = true"},
  {"line":574,"text":"\t\t\t\t}"},
  {"line":575,"text":"\t\t\t}"},
  {"line":576,"text":"\t\t}"},
  {"line":577,"text":"\t\tif wantDefault && node.Kind == ast.KindExportAssignment {"},
  {"line":578,"text":"\t\t\tmatched = true"},
  {"line":579,"text":"\t\t}"},
  {"line":580,"text":"\t\tif wantDefault && (ast.IsFunctionDeclaration(node) || ast.IsClassDeclaration(node)) && node.ModifierFlags()&ast.ModifierFlagsExportDefault == ast.ModifierFlagsExportDefault {"},
  {"line":581,"text":"\t\t\tmatched = true"},
  {"line":582,"text":"\t\t}"},
  {"line":583,"text":"\t\tif matched {"},
  {"line":584,"text":"\t\t\tdepth := getContainerDepth(node)"},
  {"line":585,"text":"\t\t\tcandidates = append(candidates, candidate{node: node, depth: depth})"},
  {"line":586,"text":"\t\t\tif depth < minDepth {"},
  {"line":587,"text":"\t\t\t\tminDepth = depth"},
  {"line":588,"text":"\t\t\t}"},
  {"line":589,"text":"\t\t}"},
  {"line":590,"text":"\t\treturn node.ForEachChild(visit)"},
  {"line":591,"text":"\t}"},
  {"line":592,"text":"\tsourceFile.AsNode().ForEachChild(visit)"},
  {"line":595,"text":"\tvar declarations []*ast.Node"},
  {"line":596,"text":"\tfor _, c := range candidates {"},
  {"line":597,"text":"\t\tif c.depth == minDepth {"},
  {"line":598,"text":"\t\t\tdeclarations = append(declarations, c.node)"},
  {"line":599,"text":"\t\t}"},
  {"line":600,"text":"\t}"},
  {"line":601,"text":"\treturn uniqueDeclarationNodes(declarations)"},
  {"line":602,"text":"}"},
  {"line":606,"text":"func getContainerDepth(node *ast.Node) int {"},
  {"line":607,"text":"\tdepth := 0"},
  {"line":608,"text":"\tcurrent := node"},
  {"line":609,"text":"\tfor current != nil {"},
  {"line":610,"text":"\t\tcurrent = getContainerNode(current)"},
  {"line":611,"text":"\t\tdepth++"},
  {"line":612,"text":"\t}"},
  {"line":613,"text":"\treturn depth"},
  {"line":614,"text":"}"},
  {"line":616,"text":"func filterPreferredSourceDeclarations(originalNode *ast.Node, declarations []*ast.Node) []*ast.Node {"},
  {"line":617,"text":"\tif len(declarations) <= 1 || originalNode == nil {"},
  {"line":618,"text":"\t\treturn declarations"},
  {"line":619,"text":"\t}"},
  {"line":620,"text":"\tif preferred := getPropertyLikeSourceDeclarations(originalNode, declarations); len(preferred) != 0 {"},
  {"line":621,"text":"\t\treturn preferred"},
  {"line":622,"text":"\t}"},
  {"line":623,"text":"\tif preferred := core.Filter(declarations, isConcreteSourceDeclaration); len(preferred) != 0 {"},
  {"line":624,"text":"\t\treturn preferred"},
  {"line":625,"text":"\t}"},
  {"line":626,"text":"\treturn declarations"},
  {"line":627,"text":"}"},
  {"line":629,"text":"func getPropertyLikeSourceDeclarations(originalNode *ast.Node, declarations []*ast.Node) []*ast.Node {"},
  {"line":630,"text":"\tif originalNode.Parent == nil || !ast.IsAccessExpression(originalNode.Parent) || originalNode.Parent.Name() != originalNode {"},
  {"line":631,"text":"\t\treturn nil"},
  {"line":632,"text":"\t}"},
  {"line":633,"text":"\treturn core.Filter(declarations, func(node *ast.Node) bool {"},
  {"line":634,"text":"\t\tswitch node.Kind {"},
  {"line":635,"text":"\t\tcase ast.KindPropertyAssignment,"},
  {"line":636,"text":"\t\t\tast.KindShorthandPropertyAssignment,"},
  {"line":637,"text":"\t\t\tast.KindPropertyDeclaration,"},
  {"line":638,"text":"\t\t\tast.KindPropertySignature,"},
  {"line":639,"text":"\t\t\tast.KindMethodDeclaration,"},
  {"line":640,"text":"\t\t\tast.KindMethodSignature,"},
  {"line":641,"text":"\t\t\tast.KindGetAccessor,"},
  {"line":642,"text":"\t\t\tast.KindSetAccessor,"},
  {"line":643,"text":"\t\t\tast.KindEnumMember:"},
  {"line":644,"text":"\t\t\treturn true"},
  {"line":645,"text":"\t\tdefault:"},
  {"line":646,"text":"\t\t\treturn false"},
  {"line":647,"text":"\t\t}"},
  {"line":648,"text":"\t})"},
  {"line":649,"text":"}"},
  {"line":651,"text":"func hasConcreteSourceDeclarations(declarations []*ast.Node) bool {"},
  {"line":652,"text":"\treturn slices.ContainsFunc(declarations, isConcreteSourceDeclaration)"},
  {"line":653,"text":"}"},
  {"line":655,"text":"func isConcreteSourceDeclaration(node *ast.Node) bool {"},
  {"line":656,"text":"\tif !ast.IsDeclaration(node) || node.Kind == ast.KindExportAssignment {"},
  {"line":657,"text":"\t\treturn false"},
  {"line":658,"text":"\t}"},
  {"line":659,"text":"\tif (ast.IsBinaryExpression(node) || ast.IsCallExpression(node)) && ast.GetAssignmentDeclarationKind(node) != ast.JSDeclarationKindNone {"},
  {"line":660,"text":"\t\treturn false"},
  {"line":661,"text":"\t}"},
  {"line":662,"text":"\tswitch node.Kind {"},
  {"line":663,"text":"\tcase ast.KindParameter,"},
  {"line":664,"text":"\t\tast.KindTypeParameter,"},
  {"line":665,"text":"\t\tast.KindBindingElement,"},
  {"line":666,"text":"\t\tast.KindImportClause,"},
  {"line":667,"text":"\t\tast.KindImportSpecifier,"},
  {"line":668,"text":"\t\tast.KindNamespaceImport,"},
  {"line":669,"text":"\t\tast.KindExportSpecifier,"},
  {"line":670,"text":"\t\tast.KindPropertyAccessExpression,"},
  {"line":671,"text":"\t\tast.KindElementAccessExpression:"},
  {"line":672,"text":"\t\treturn false"},
  {"line":673,"text":"\tdefault:"},
  {"line":674,"text":"\t\treturn true"},
  {"line":675,"text":"\t}"},
  {"line":676,"text":"}"},
  {"line":678,"text":"func uniqueDeclarationNodes(nodes []*ast.Node) []*ast.Node {"},
  {"line":679,"text":"\ttype declarationKey struct {"},
  {"line":680,"text":"\t\tfileName string"},
  {"line":681,"text":"\t\tloc      core.TextRange"},
  {"line":682,"text":"\t}"},
  {"line":683,"text":"\tvar seen collections.Set[declarationKey]"},
  {"line":684,"text":"\tresult := make([]*ast.Node, 0, len(nodes))"},
  {"line":685,"text":"\tfor _, node := range nodes {"},
  {"line":686,"text":"\t\tif node == nil {"},
  {"line":687,"text":"\t\t\tcontinue"},
  {"line":688,"text":"\t\t}"},
  {"line":689,"text":"\t\tfileName := ast.GetSourceFileOfNode(node).FileName()"},
  {"line":690,"text":"\t\tkey := declarationKey{fileName: fileName, loc: node.Loc}"},
  {"line":691,"text":"\t\tif !seen.AddIfAbsent(key) {"},
  {"line":692,"text":"\t\t\tcontinue"},
  {"line":693,"text":"\t\t}"},
  {"line":694,"text":"\t\tresult = append(result, node)"},
  {"line":695,"text":"\t}"},
  {"line":696,"text":"\treturn result"},
  {"line":697,"text":"}"},
  {"line":699,"text":"func findClosestDeclarationNode(sourceFile *ast.SourceFile, pos int) *ast.Node {"},
  {"line":700,"text":"\tnode := astnav.GetTouchingPropertyName(sourceFile, pos)"},
  {"line":701,"text":"\tfor current := node; current != nil; current = current.Parent {"},
  {"line":702,"text":"\t\tif ast.IsDeclaration(current) || current.Kind == ast.KindExportAssignment {"},
  {"line":703,"text":"\t\t\treturn current"},
  {"line":704,"text":"\t\t}"},
  {"line":705,"text":"\t}"},
  {"line":706,"text":"\treturn getSourceDefinitionEntryNode(sourceFile)"},
  {"line":707,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSourceDefinitionSourceLines.find((entry) => entry.line === line)?.text;
}
