/**
 * Strict TS-Go parity gap map for `ls`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const lsStrictParityUpstreamModule = "ls";
export const lsStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"api.go","line":1,"text":"package ls"},
  {"file":"api.go","line":3,"text":"import ("},
  {"file":"api.go","line":4,"text":"\t\"context\""},
  {"file":"api.go","line":5,"text":"\t\"errors\""},
  {"file":"api.go","line":6,"text":"\t\"fmt\""},
  {"file":"api.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"api.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"file":"api.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"file":"api.go","line":11,"text":")"},
  {"file":"api.go","line":13,"text":"var ("},
  {"file":"api.go","line":14,"text":"\tErrNoSourceFile      = errors.New(\"source file not found\")"},
  {"file":"api.go","line":15,"text":"\tErrNoTokenAtPosition = errors.New(\"no token found at position\")"},
  {"file":"api.go","line":16,"text":")"},
  {"file":"api.go","line":18,"text":"func (l *LanguageService) GetSymbolAtPosition(ctx context.Context, fileName string, position int) (*ast.Symbol, error) {"},
  {"file":"api.go","line":19,"text":"\tprogram, file := l.tryGetProgramAndFile(fileName)"},
  {"file":"api.go","line":20,"text":"\tif file == nil {"},
  {"file":"api.go","line":21,"text":"\t\treturn nil, fmt.Errorf(\"%w: %s\", ErrNoSourceFile, fileName)"},
  {"file":"api.go","line":22,"text":"\t}"},
  {"file":"api.go","line":23,"text":"\tnode := astnav.GetTokenAtPosition(file, position)"},
  {"file":"api.go","line":24,"text":"\tif node == nil {"},
  {"file":"api.go","line":25,"text":"\t\treturn nil, fmt.Errorf(\"%w: %s:%d\", ErrNoTokenAtPosition, fileName, position)"},
  {"file":"api.go","line":26,"text":"\t}"},
  {"file":"api.go","line":27,"text":"\tchecker, done := program.GetTypeCheckerForFile(ctx, file)"},
  {"file":"api.go","line":28,"text":"\tdefer done()"},
  {"file":"api.go","line":29,"text":"\treturn checker.GetSymbolAtLocation(node), nil"},
  {"file":"api.go","line":30,"text":"}"},
  {"file":"api.go","line":32,"text":"func (l *LanguageService) GetSymbolAtLocation(ctx context.Context, node *ast.Node) *ast.Symbol {"},
  {"file":"api.go","line":33,"text":"\tprogram := l.GetProgram()"},
  {"file":"api.go","line":34,"text":"\tchecker, done := program.GetTypeCheckerForFile(ctx, ast.GetSourceFileOfNode(node))"},
  {"file":"api.go","line":35,"text":"\tdefer done()"},
  {"file":"api.go","line":36,"text":"\treturn checker.GetSymbolAtLocation(node)"},
  {"file":"api.go","line":37,"text":"}"},
  {"file":"api.go","line":39,"text":"func (l *LanguageService) GetTypeOfSymbol(ctx context.Context, symbol *ast.Symbol) *checker.Type {"},
  {"file":"api.go","line":40,"text":"\tprogram := l.GetProgram()"},
  {"file":"api.go","line":41,"text":"\tchecker, done := program.GetTypeChecker(ctx)"},
  {"file":"api.go","line":42,"text":"\tdefer done()"},
  {"file":"api.go","line":43,"text":"\treturn checker.GetTypeOfSymbolAtLocation(symbol, nil)"},
  {"file":"api.go","line":44,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":1,"text":"package autoimport"},
  {"file":"autoimport/aliasresolver.go","line":3,"text":"import ("},
  {"file":"autoimport/aliasresolver.go","line":4,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"autoimport/aliasresolver.go","line":5,"text":"\t\"github.com/microsoft/typescript-go/internal/binder\""},
  {"file":"autoimport/aliasresolver.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"file":"autoimport/aliasresolver.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"autoimport/aliasresolver.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"autoimport/aliasresolver.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/module\""},
  {"file":"autoimport/aliasresolver.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/packagejson\""},
  {"file":"autoimport/aliasresolver.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/symlinks\""},
  {"file":"autoimport/aliasresolver.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/tsoptions\""},
  {"file":"autoimport/aliasresolver.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"autoimport/aliasresolver.go","line":14,"text":")"},
  {"file":"autoimport/aliasresolver.go","line":16,"text":"type pathAndFileName struct {"},
  {"file":"autoimport/aliasresolver.go","line":17,"text":"\tpath     tspath.Path"},
  {"file":"autoimport/aliasresolver.go","line":18,"text":"\tfileName string"},
  {"file":"autoimport/aliasresolver.go","line":19,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":21,"text":"type aliasResolver struct {"},
  {"file":"autoimport/aliasresolver.go","line":22,"text":"\ttoPath         func(fileName string) tspath.Path"},
  {"file":"autoimport/aliasresolver.go","line":23,"text":"\thost           RegistryCloneHost"},
  {"file":"autoimport/aliasresolver.go","line":24,"text":"\tmoduleResolver *module.Resolver"},
  {"file":"autoimport/aliasresolver.go","line":26,"text":"\trootFiles []*ast.SourceFile"},
  {"file":"autoimport/aliasresolver.go","line":28,"text":"\tsymlinks                    map[tspath.Path]pathAndFileName"},
  {"file":"autoimport/aliasresolver.go","line":29,"text":"\tonFailedAmbientModuleLookup func(source ast.HasFileName, moduleName string)"},
  {"file":"autoimport/aliasresolver.go","line":30,"text":"\tresolvedModules             collections.SyncMap[tspath.Path, *collections.SyncMap[module.ModeAwareCacheKey, *module.ResolvedModule]]"},
  {"file":"autoimport/aliasresolver.go","line":31,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":33,"text":"func newAliasResolver("},
  {"file":"autoimport/aliasresolver.go","line":34,"text":"\trootFiles []*ast.SourceFile,"},
  {"file":"autoimport/aliasresolver.go","line":35,"text":"\tsymlinks map[tspath.Path]pathAndFileName,"},
  {"file":"autoimport/aliasresolver.go","line":36,"text":"\thost RegistryCloneHost,"},
  {"file":"autoimport/aliasresolver.go","line":37,"text":"\tmoduleResolver *module.Resolver,"},
  {"file":"autoimport/aliasresolver.go","line":38,"text":"\ttoPath func(fileName string) tspath.Path,"},
  {"file":"autoimport/aliasresolver.go","line":39,"text":"\tonFailedAmbientModuleLookup func(source ast.HasFileName, moduleName string),"},
  {"file":"autoimport/aliasresolver.go","line":40,"text":") *aliasResolver {"},
  {"file":"autoimport/aliasresolver.go","line":41,"text":"\tr := &aliasResolver{"},
  {"file":"autoimport/aliasresolver.go","line":42,"text":"\t\ttoPath:                      toPath,"},
  {"file":"autoimport/aliasresolver.go","line":43,"text":"\t\thost:                        host,"},
  {"file":"autoimport/aliasresolver.go","line":44,"text":"\t\tmoduleResolver:              moduleResolver,"},
  {"file":"autoimport/aliasresolver.go","line":45,"text":"\t\trootFiles:                   rootFiles,"},
  {"file":"autoimport/aliasresolver.go","line":46,"text":"\t\tsymlinks:                    symlinks,"},
  {"file":"autoimport/aliasresolver.go","line":47,"text":"\t\tonFailedAmbientModuleLookup: onFailedAmbientModuleLookup,"},
  {"file":"autoimport/aliasresolver.go","line":48,"text":"\t}"},
  {"file":"autoimport/aliasresolver.go","line":49,"text":"\treturn r"},
  {"file":"autoimport/aliasresolver.go","line":50,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":53,"text":"func (r *aliasResolver) BindSourceFiles() {"},
  {"file":"autoimport/aliasresolver.go","line":55,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":58,"text":"func (r *aliasResolver) SourceFiles() []*ast.SourceFile {"},
  {"file":"autoimport/aliasresolver.go","line":59,"text":"\treturn r.rootFiles"},
  {"file":"autoimport/aliasresolver.go","line":60,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":63,"text":"func (r *aliasResolver) Options() *core.CompilerOptions {"},
  {"file":"autoimport/aliasresolver.go","line":64,"text":"\treturn &core.CompilerOptions{"},
  {"file":"autoimport/aliasresolver.go","line":65,"text":"\t\tNoCheck: core.TSTrue,"},
  {"file":"autoimport/aliasresolver.go","line":66,"text":"\t}"},
  {"file":"autoimport/aliasresolver.go","line":67,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":70,"text":"func (r *aliasResolver) GetCurrentDirectory() string {"},
  {"file":"autoimport/aliasresolver.go","line":71,"text":"\treturn r.host.GetCurrentDirectory()"},
  {"file":"autoimport/aliasresolver.go","line":72,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":75,"text":"func (r *aliasResolver) UseCaseSensitiveFileNames() bool {"},
  {"file":"autoimport/aliasresolver.go","line":76,"text":"\treturn r.host.FS().UseCaseSensitiveFileNames()"},
  {"file":"autoimport/aliasresolver.go","line":77,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":80,"text":"func (r *aliasResolver) GetSourceFile(fileName string) *ast.SourceFile {"},
  {"file":"autoimport/aliasresolver.go","line":81,"text":"\tfile := r.host.GetSourceFile(fileName, r.toPath(fileName))"},
  {"file":"autoimport/aliasresolver.go","line":83,"text":"\tif file == nil {"},
  {"file":"autoimport/aliasresolver.go","line":84,"text":"\t\treturn nil"},
  {"file":"autoimport/aliasresolver.go","line":85,"text":"\t}"},
  {"file":"autoimport/aliasresolver.go","line":86,"text":"\tbinder.BindSourceFile(file)"},
  {"file":"autoimport/aliasresolver.go","line":87,"text":"\treturn file"},
  {"file":"autoimport/aliasresolver.go","line":88,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":91,"text":"func (r *aliasResolver) GetDefaultResolutionModeForFile(file ast.HasFileName) core.ResolutionMode {"},
  {"file":"autoimport/aliasresolver.go","line":92,"text":"\treturn core.ModuleKindESNext"},
  {"file":"autoimport/aliasresolver.go","line":93,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":96,"text":"func (r *aliasResolver) GetEmitModuleFormatOfFile(sourceFile ast.HasFileName) core.ModuleKind {"},
  {"file":"autoimport/aliasresolver.go","line":97,"text":"\treturn core.ModuleKindESNext"},
  {"file":"autoimport/aliasresolver.go","line":98,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":101,"text":"func (r *aliasResolver) GetEmitSyntaxForUsageLocation(sourceFile ast.HasFileName, usageLocation *ast.StringLiteralLike) core.ResolutionMode {"},
  {"file":"autoimport/aliasresolver.go","line":102,"text":"\treturn core.ModuleKindESNext"},
  {"file":"autoimport/aliasresolver.go","line":103,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":106,"text":"func (r *aliasResolver) GetImpliedNodeFormatForEmit(sourceFile ast.HasFileName) core.ModuleKind {"},
  {"file":"autoimport/aliasresolver.go","line":107,"text":"\treturn core.ModuleKindESNext"},
  {"file":"autoimport/aliasresolver.go","line":108,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":111,"text":"func (r *aliasResolver) GetModeForUsageLocation(file ast.HasFileName, moduleSpecifier *ast.StringLiteralLike) core.ResolutionMode {"},
  {"file":"autoimport/aliasresolver.go","line":112,"text":"\treturn core.ModuleKindESNext"},
  {"file":"autoimport/aliasresolver.go","line":113,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":116,"text":"func (r *aliasResolver) GetResolvedModule(currentSourceFile ast.HasFileName, moduleReference string, mode core.ResolutionMode) *module.ResolvedModule {"},
  {"file":"autoimport/aliasresolver.go","line":117,"text":"\tcache, _ := r.resolvedModules.LoadOrStore(currentSourceFile.Path(), &collections.SyncMap[module.ModeAwareCacheKey, *module.ResolvedModule]{})"},
  {"file":"autoimport/aliasresolver.go","line":118,"text":"\tif resolved, ok := cache.Load(module.ModeAwareCacheKey{Name: moduleReference, Mode: mode}); ok {"},
  {"file":"autoimport/aliasresolver.go","line":119,"text":"\t\treturn resolved"},
  {"file":"autoimport/aliasresolver.go","line":120,"text":"\t}"},
  {"file":"autoimport/aliasresolver.go","line":121,"text":"\tresolved, _ := r.moduleResolver.ResolveModuleName(moduleReference, currentSourceFile.FileName(), mode, nil)"},
  {"file":"autoimport/aliasresolver.go","line":122,"text":"\tresolved, _ = cache.LoadOrStore(module.ModeAwareCacheKey{Name: moduleReference, Mode: mode}, resolved)"},
  {"file":"autoimport/aliasresolver.go","line":123,"text":"\tif !resolved.IsResolved() && !tspath.PathIsRelative(moduleReference) {"},
  {"file":"autoimport/aliasresolver.go","line":124,"text":"\t\tr.onFailedAmbientModuleLookup(currentSourceFile, moduleReference)"},
  {"file":"autoimport/aliasresolver.go","line":125,"text":"\t}"},
  {"file":"autoimport/aliasresolver.go","line":126,"text":"\treturn resolved"},
  {"file":"autoimport/aliasresolver.go","line":127,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":130,"text":"func (r *aliasResolver) GetSourceFileForResolvedModule(fileName string) *ast.SourceFile {"},
  {"file":"autoimport/aliasresolver.go","line":131,"text":"\treturn r.GetSourceFile(fileName)"},
  {"file":"autoimport/aliasresolver.go","line":132,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":135,"text":"func (r *aliasResolver) GetResolvedModules() map[tspath.Path]module.ModeAwareCache[*module.ResolvedModule] {"},
  {"file":"autoimport/aliasresolver.go","line":137,"text":"\treturn nil"},
  {"file":"autoimport/aliasresolver.go","line":138,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":143,"text":"func (r *aliasResolver) GetSymlinkCache() *symlinks.KnownSymlinks {"},
  {"file":"autoimport/aliasresolver.go","line":144,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":145,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":148,"text":"func (r *aliasResolver) GetSourceFileMetaData(path tspath.Path) ast.SourceFileMetaData {"},
  {"file":"autoimport/aliasresolver.go","line":149,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":150,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":153,"text":"func (r *aliasResolver) CommonSourceDirectory() string {"},
  {"file":"autoimport/aliasresolver.go","line":154,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":155,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":158,"text":"func (r *aliasResolver) FileExists(fileName string) bool {"},
  {"file":"autoimport/aliasresolver.go","line":159,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":160,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":163,"text":"func (r *aliasResolver) GetGlobalTypingsCacheLocation() string {"},
  {"file":"autoimport/aliasresolver.go","line":164,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":165,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":168,"text":"func (r *aliasResolver) GetImportHelpersImportSpecifier(path tspath.Path) *ast.Node {"},
  {"file":"autoimport/aliasresolver.go","line":169,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":170,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":173,"text":"func (r *aliasResolver) GetJSXRuntimeImportSpecifier(path tspath.Path) (moduleReference string, specifier *ast.Node) {"},
  {"file":"autoimport/aliasresolver.go","line":174,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":175,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":178,"text":"func (r *aliasResolver) GetNearestAncestorDirectoryWithPackageJson(dirname string) string {"},
  {"file":"autoimport/aliasresolver.go","line":179,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":180,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":183,"text":"func (r *aliasResolver) GetPackageJsonInfo(pkgJsonPath string) *packagejson.InfoCacheEntry {"},
  {"file":"autoimport/aliasresolver.go","line":184,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":185,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":188,"text":"func (r *aliasResolver) GetProjectReferenceFromOutputDts(path tspath.Path) *tsoptions.SourceOutputAndProjectReference {"},
  {"file":"autoimport/aliasresolver.go","line":189,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":190,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":193,"text":"func (r *aliasResolver) GetProjectReferenceFromSource(path tspath.Path) *tsoptions.SourceOutputAndProjectReference {"},
  {"file":"autoimport/aliasresolver.go","line":194,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":195,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":198,"text":"func (r *aliasResolver) GetRedirectForResolution(file ast.HasFileName) *tsoptions.ParsedCommandLine {"},
  {"file":"autoimport/aliasresolver.go","line":199,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":200,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":203,"text":"func (r *aliasResolver) GetRedirectTargets(path tspath.Path) []string {"},
  {"file":"autoimport/aliasresolver.go","line":204,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":205,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":208,"text":"func (r *aliasResolver) GetResolvedModuleFromModuleSpecifier(file ast.HasFileName, moduleSpecifier *ast.StringLiteralLike) *module.ResolvedModule {"},
  {"file":"autoimport/aliasresolver.go","line":209,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":210,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":213,"text":"func (r *aliasResolver) GetSourceOfProjectReferenceIfOutputIncluded(file ast.HasFileName) string {"},
  {"file":"autoimport/aliasresolver.go","line":214,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":215,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":218,"text":"func (r *aliasResolver) IsSourceFileDefaultLibrary(path tspath.Path) bool {"},
  {"file":"autoimport/aliasresolver.go","line":219,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":220,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":223,"text":"func (r *aliasResolver) IsSourceFromProjectReference(path tspath.Path) bool {"},
  {"file":"autoimport/aliasresolver.go","line":224,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":225,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":228,"text":"func (r *aliasResolver) SourceFileMayBeEmitted(sourceFile *ast.SourceFile, forceDtsEmit bool) bool {"},
  {"file":"autoimport/aliasresolver.go","line":229,"text":"\tpanic(\"unimplemented\")"},
  {"file":"autoimport/aliasresolver.go","line":230,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":232,"text":"func (r *aliasResolver) GetPackagesMap() map[string]bool {"},
  {"file":"autoimport/aliasresolver.go","line":233,"text":"\treturn nil"},
  {"file":"autoimport/aliasresolver.go","line":234,"text":"}"},
  {"file":"autoimport/aliasresolver.go","line":236,"text":"var _ checker.Program = (*aliasResolver)(nil)"},
  {"file":"autoimport/export.go","line":1,"text":"package autoimport"},
  {"file":"autoimport/export.go","line":3,"text":"import ("},
  {"file":"autoimport/export.go","line":4,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"autoimport/export.go","line":5,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"file":"autoimport/export.go","line":6,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"autoimport/export.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"file":"autoimport/export.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"autoimport/export.go","line":9,"text":")"},
  {"file":"autoimport/export.go","line":18,"text":"type ModuleID string"},
  {"file":"autoimport/export.go","line":20,"text":"type ExportID struct {"},
  {"file":"autoimport/export.go","line":21,"text":"\tModuleID   ModuleID"},
  {"file":"autoimport/export.go","line":22,"text":"\tExportName string"},
  {"file":"autoimport/export.go","line":23,"text":"}"},
  {"file":"autoimport/export.go","line":25,"text":"type ExportSyntax int"},
  {"file":"autoimport/export.go","line":27,"text":"const ("},
  {"file":"autoimport/export.go","line":28,"text":"\tExportSyntaxNone ExportSyntax = iota"},
  {"file":"autoimport/export.go","line":30,"text":"\tExportSyntaxModifier"},
  {"file":"autoimport/export.go","line":32,"text":"\tExportSyntaxNamed"},
  {"file":"autoimport/export.go","line":34,"text":"\tExportSyntaxDefaultModifier"},
  {"file":"autoimport/export.go","line":36,"text":"\tExportSyntaxDefaultDeclaration"},
  {"file":"autoimport/export.go","line":38,"text":"\tExportSyntaxEquals"},
  {"file":"autoimport/export.go","line":40,"text":"\tExportSyntaxUMD"},
  {"file":"autoimport/export.go","line":42,"text":"\tExportSyntaxStar"},
  {"file":"autoimport/export.go","line":44,"text":"\tExportSyntaxCommonJSModuleExports"},
  {"file":"autoimport/export.go","line":46,"text":"\tExportSyntaxCommonJSExportsProperty"},
  {"file":"autoimport/export.go","line":47,"text":")"},
  {"file":"autoimport/export.go","line":49,"text":"type Export struct {"},
  {"file":"autoimport/export.go","line":50,"text":"\tExportID"},
  {"file":"autoimport/export.go","line":51,"text":"\tModuleFileName string"},
  {"file":"autoimport/export.go","line":52,"text":"\tSyntax         ExportSyntax"},
  {"file":"autoimport/export.go","line":53,"text":"\tFlags          ast.SymbolFlags"},
  {"file":"autoimport/export.go","line":54,"text":"\tlocalName      string"},
  {"file":"autoimport/export.go","line":57,"text":"\tthrough string"},
  {"file":"autoimport/export.go","line":61,"text":"\tTarget                     ExportID"},
  {"file":"autoimport/export.go","line":62,"text":"\tIsTypeOnly                 bool"},
  {"file":"autoimport/export.go","line":63,"text":"\tScriptElementKind          lsutil.ScriptElementKind"},
  {"file":"autoimport/export.go","line":64,"text":"\tScriptElementKindModifiers lsutil.ScriptElementKindModifier"},
  {"file":"autoimport/export.go","line":67,"text":"\tPath tspath.Path"},
  {"file":"autoimport/export.go","line":69,"text":"\tPackageName string"},
  {"file":"autoimport/export.go","line":70,"text":"}"},
  {"file":"autoimport/export.go","line":72,"text":"func (e *Export) Name() string {"},
  {"file":"autoimport/export.go","line":73,"text":"\tif e.localName != \"\" {"},
  {"file":"autoimport/export.go","line":74,"text":"\t\treturn e.localName"},
  {"file":"autoimport/export.go","line":75,"text":"\t}"},
  {"file":"autoimport/export.go","line":76,"text":"\tif e.ExportName == ast.InternalSymbolNameExportEquals {"},
  {"file":"autoimport/export.go","line":77,"text":"\t\treturn e.Target.ExportName"},
  {"file":"autoimport/export.go","line":78,"text":"\t}"},
  {"file":"autoimport/export.go","line":79,"text":"\treturn e.ExportName"},
  {"file":"autoimport/export.go","line":80,"text":"}"},
  {"file":"autoimport/export.go","line":82,"text":"func (e *Export) IsRenameable() bool {"},
  {"file":"autoimport/export.go","line":83,"text":"\treturn e.ExportName == ast.InternalSymbolNameExportEquals || e.ExportName == ast.InternalSymbolNameDefault"},
  {"file":"autoimport/export.go","line":84,"text":"}"},
  {"file":"autoimport/export.go","line":86,"text":"func (e *Export) AmbientModuleName() string {"},
  {"file":"autoimport/export.go","line":87,"text":"\tif !tspath.IsExternalModuleNameRelative(string(e.ModuleID)) {"},
  {"file":"autoimport/export.go","line":88,"text":"\t\treturn string(e.ModuleID)"},
  {"file":"autoimport/export.go","line":89,"text":"\t}"},
  {"file":"autoimport/export.go","line":90,"text":"\treturn \"\""},
  {"file":"autoimport/export.go","line":91,"text":"}"},
  {"file":"autoimport/export.go","line":93,"text":"func (e *Export) IsUnresolvedAlias() bool {"},
  {"file":"autoimport/export.go","line":94,"text":"\treturn e.Flags == ast.SymbolFlagsAlias"},
  {"file":"autoimport/export.go","line":95,"text":"}"},
  {"file":"autoimport/export.go","line":97,"text":"func SymbolToExport(symbol *ast.Symbol, ch *checker.Checker) *Export {"},
  {"file":"autoimport/export.go","line":98,"text":"\tif symbol.Parent != nil && checker.IsExternalModuleSymbol(symbol.Parent) {"},
  {"file":"autoimport/export.go","line":99,"text":"\t\tif moduleID, moduleFileName, ok := tryGetModuleIDAndFileNameOfModuleSymbol(symbol.Parent); ok {"},
  {"file":"autoimport/export.go","line":100,"text":"\t\t\treturn extractFirstExport(symbol, ch, moduleID, moduleFileName, ast.GetSourceFileOfModule(symbol.Parent))"},
  {"file":"autoimport/export.go","line":101,"text":"\t\t}"},
  {"file":"autoimport/export.go","line":102,"text":"\t\treturn nil"},
  {"file":"autoimport/export.go","line":103,"text":"\t}"},
  {"file":"autoimport/export.go","line":105,"text":"\tdeclaration := core.FirstOrNil(symbol.Declarations)"},
  {"file":"autoimport/export.go","line":106,"text":"\tif declaration == nil {"},
  {"file":"autoimport/export.go","line":107,"text":"\t\treturn nil"},
  {"file":"autoimport/export.go","line":108,"text":"\t}"},
  {"file":"autoimport/export.go","line":110,"text":"\tfile := ast.GetSourceFileOfNode(declaration)"},
  {"file":"autoimport/export.go","line":111,"text":"\tif file.Symbol == nil {"},
  {"file":"autoimport/export.go","line":112,"text":"\t\treturn nil"},
  {"file":"autoimport/export.go","line":113,"text":"\t}"},
  {"file":"autoimport/export.go","line":115,"text":"\tmoduleSymbol := ch.GetMergedSymbol(file.Symbol)"},
  {"file":"autoimport/export.go","line":116,"text":"\tmoduleID := ModuleID(file.Path())"},
  {"file":"autoimport/export.go","line":117,"text":"\tmoduleFileName := file.FileName()"},
  {"file":"autoimport/export.go","line":118,"text":"\ttarget := ch.GetMergedSymbol(ch.SkipAlias(symbol))"},
  {"file":"autoimport/export.go","line":120,"text":"\tif export := tryGetModuleExport(ast.InternalSymbolNameDefault, target, moduleSymbol, ch, moduleID, moduleFileName, file); export != nil {"},
  {"file":"autoimport/export.go","line":121,"text":"\t\treturn export"},
  {"file":"autoimport/export.go","line":122,"text":"\t}"},
  {"file":"autoimport/export.go","line":123,"text":"\tif export := tryGetModuleExport(ast.InternalSymbolNameExportEquals, target, moduleSymbol, ch, moduleID, moduleFileName, file); export != nil {"},
  {"file":"autoimport/export.go","line":124,"text":"\t\treturn export"},
  {"file":"autoimport/export.go","line":125,"text":"\t}"},
  {"file":"autoimport/export.go","line":126,"text":"\treturn tryGetModuleExport(symbol.Name, target, moduleSymbol, ch, moduleID, moduleFileName, file)"},
  {"file":"autoimport/export.go","line":127,"text":"}"},
  {"file":"autoimport/export.go","line":129,"text":"func tryGetModuleExport(exportName string, target *ast.Symbol, moduleSymbol *ast.Symbol, ch *checker.Checker, moduleID ModuleID, moduleFileName string, file *ast.SourceFile) *Export {"},
  {"file":"autoimport/export.go","line":130,"text":"\texported := ch.TryGetMemberInModuleExportsAndProperties(exportName, moduleSymbol)"},
  {"file":"autoimport/export.go","line":131,"text":"\tif exported != nil && ch.GetMergedSymbol(ch.SkipAlias(exported)) == target {"},
  {"file":"autoimport/export.go","line":132,"text":"\t\treturn extractFirstExport(exported, ch, moduleID, moduleFileName, file)"},
  {"file":"autoimport/export.go","line":133,"text":"\t}"},
  {"file":"autoimport/export.go","line":134,"text":"\treturn nil"},
  {"file":"autoimport/export.go","line":135,"text":"}"},
  {"file":"autoimport/export.go","line":137,"text":"func extractFirstExport(symbol *ast.Symbol, ch *checker.Checker, moduleID ModuleID, moduleFileName string, file *ast.SourceFile) *Export {"},
  {"file":"autoimport/export.go","line":138,"text":"\tvar exports []*Export"},
  {"file":"autoimport/export.go","line":139,"text":"\textractor := newSymbolExtractor(\"\", ch, nil, nil)"},
  {"file":"autoimport/export.go","line":140,"text":"\textractor.extractFromSymbol(symbol.Name, symbol, moduleID, moduleFileName, file, &exports)"},
  {"file":"autoimport/export.go","line":141,"text":"\treturn core.FirstOrNil(exports)"},
  {"file":"autoimport/export.go","line":142,"text":"}"},
  {"file":"autoimport/export_stringer_generated.go","line":3,"text":"package autoimport"},
  {"file":"autoimport/export_stringer_generated.go","line":5,"text":"import \"strconv\""},
  {"file":"autoimport/export_stringer_generated.go","line":7,"text":"func _() {"},
  {"file":"autoimport/export_stringer_generated.go","line":10,"text":"\tvar x [1]struct{}"},
  {"file":"autoimport/export_stringer_generated.go","line":11,"text":"\t_ = x[ExportSyntaxNone-0]"},
  {"file":"autoimport/export_stringer_generated.go","line":12,"text":"\t_ = x[ExportSyntaxModifier-1]"},
  {"file":"autoimport/export_stringer_generated.go","line":13,"text":"\t_ = x[ExportSyntaxNamed-2]"},
  {"file":"autoimport/export_stringer_generated.go","line":14,"text":"\t_ = x[ExportSyntaxDefaultModifier-3]"},
  {"file":"autoimport/export_stringer_generated.go","line":15,"text":"\t_ = x[ExportSyntaxDefaultDeclaration-4]"},
  {"file":"autoimport/export_stringer_generated.go","line":16,"text":"\t_ = x[ExportSyntaxEquals-5]"},
  {"file":"autoimport/export_stringer_generated.go","line":17,"text":"\t_ = x[ExportSyntaxUMD-6]"},
  {"file":"autoimport/export_stringer_generated.go","line":18,"text":"\t_ = x[ExportSyntaxStar-7]"},
  {"file":"autoimport/export_stringer_generated.go","line":19,"text":"\t_ = x[ExportSyntaxCommonJSModuleExports-8]"},
  {"file":"autoimport/export_stringer_generated.go","line":20,"text":"\t_ = x[ExportSyntaxCommonJSExportsProperty-9]"},
  {"file":"autoimport/export_stringer_generated.go","line":21,"text":"}"},
  {"file":"autoimport/export_stringer_generated.go","line":23,"text":"const _ExportSyntax_name = \"ExportSyntaxNoneExportSyntaxModifierExportSyntaxNamedExportSyntaxDefaultModifierExportSyntaxDefaultDeclarationExportSyntaxEqualsExportSyntaxUMDExportSyntaxStarExportSyntaxCommonJSModuleExportsExportSyntaxCommonJSExportsProperty\""},
  {"file":"autoimport/export_stringer_generated.go","line":25,"text":"var _ExportSyntax_index = [...]uint8{0, 16, 36, 53, 80, 110, 128, 143, 159, 192, 227}"},
  {"file":"autoimport/export_stringer_generated.go","line":27,"text":"func (i ExportSyntax) String() string {"},
  {"file":"autoimport/export_stringer_generated.go","line":28,"text":"\tidx := int(i) - 0"},
  {"file":"autoimport/export_stringer_generated.go","line":29,"text":"\tif i < 0 || idx >= len(_ExportSyntax_index)-1 {"},
  {"file":"autoimport/export_stringer_generated.go","line":30,"text":"\t\treturn \"ExportSyntax(\" + strconv.FormatInt(int64(i), 10) + \")\""},
  {"file":"autoimport/export_stringer_generated.go","line":31,"text":"\t}"},
  {"file":"autoimport/export_stringer_generated.go","line":32,"text":"\treturn _ExportSyntax_name[_ExportSyntax_index[idx]:_ExportSyntax_index[idx+1]]"},
  {"file":"autoimport/export_stringer_generated.go","line":33,"text":"}"},
  {"file":"autoimport/extract.go","line":1,"text":"package autoimport"},
  {"file":"autoimport/extract.go","line":3,"text":"import ("},
  {"file":"autoimport/extract.go","line":4,"text":"\t\"slices\""},
  {"file":"autoimport/extract.go","line":5,"text":"\t\"sync/atomic\""},
  {"file":"autoimport/extract.go","line":7,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"autoimport/extract.go","line":8,"text":"\t\"github.com/microsoft/typescript-go/internal/binder\""},
  {"file":"autoimport/extract.go","line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"file":"autoimport/extract.go","line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"autoimport/extract.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"file":"autoimport/extract.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/module\""},
  {"file":"autoimport/extract.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"autoimport/extract.go","line":14,"text":")"},
  {"file":"autoimport/extract.go","line":16,"text":"type symbolExtractor struct {"},
  {"file":"autoimport/extract.go","line":17,"text":"\tpackageName string"},
  {"file":"autoimport/extract.go","line":18,"text":"\tstats       *extractorStats"},
  {"file":"autoimport/extract.go","line":20,"text":"\tlocalNameResolver *binder.NameResolver"},
  {"file":"autoimport/extract.go","line":21,"text":"\tchecker           *checker.Checker"},
  {"file":"autoimport/extract.go","line":22,"text":"\ttoPath            func(fileName string) tspath.Path"},
  {"file":"autoimport/extract.go","line":26,"text":"\trealpath func(fileName string) string"},
  {"file":"autoimport/extract.go","line":27,"text":"}"},
  {"file":"autoimport/extract.go","line":29,"text":"type exportExtractor struct {"},
  {"file":"autoimport/extract.go","line":30,"text":"\t*symbolExtractor"},
  {"file":"autoimport/extract.go","line":31,"text":"\tmoduleResolver *module.Resolver"},
  {"file":"autoimport/extract.go","line":32,"text":"}"},
  {"file":"autoimport/extract.go","line":34,"text":"type extractorStats struct {"},
  {"file":"autoimport/extract.go","line":35,"text":"\texports     atomic.Int32"},
  {"file":"autoimport/extract.go","line":36,"text":"\tusedChecker atomic.Int32"},
  {"file":"autoimport/extract.go","line":37,"text":"}"},
  {"file":"autoimport/extract.go","line":39,"text":"func (e *exportExtractor) Stats() *extractorStats {"},
  {"file":"autoimport/extract.go","line":40,"text":"\treturn e.stats"},
  {"file":"autoimport/extract.go","line":41,"text":"}"},
  {"file":"autoimport/extract.go","line":43,"text":"type checkerLease struct {"},
  {"file":"autoimport/extract.go","line":44,"text":"\tused    bool"},
  {"file":"autoimport/extract.go","line":45,"text":"\tchecker *checker.Checker"},
  {"file":"autoimport/extract.go","line":46,"text":"}"},
  {"file":"autoimport/extract.go","line":48,"text":"func (l *checkerLease) GetChecker() *checker.Checker {"},
  {"file":"autoimport/extract.go","line":49,"text":"\tl.used = true"},
  {"file":"autoimport/extract.go","line":50,"text":"\treturn l.checker"},
  {"file":"autoimport/extract.go","line":51,"text":"}"},
  {"file":"autoimport/extract.go","line":53,"text":"func (l *checkerLease) TryChecker() *checker.Checker {"},
  {"file":"autoimport/extract.go","line":54,"text":"\tif l.used {"},
  {"file":"autoimport/extract.go","line":55,"text":"\t\treturn l.checker"},
  {"file":"autoimport/extract.go","line":56,"text":"\t}"},
  {"file":"autoimport/extract.go","line":57,"text":"\treturn nil"},
  {"file":"autoimport/extract.go","line":58,"text":"}"},
  {"file":"autoimport/extract.go","line":60,"text":"func newSymbolExtractor(packageName string, checker *checker.Checker, toPath func(string) tspath.Path, realpath func(string) string) *symbolExtractor {"},
  {"file":"autoimport/extract.go","line":61,"text":"\treturn &symbolExtractor{"},
  {"file":"autoimport/extract.go","line":62,"text":"\t\tpackageName: packageName,"},
  {"file":"autoimport/extract.go","line":63,"text":"\t\tchecker:     checker,"},
  {"file":"autoimport/extract.go","line":64,"text":"\t\tlocalNameResolver: &binder.NameResolver{"},
  {"file":"autoimport/extract.go","line":65,"text":"\t\t\tCompilerOptions: core.EmptyCompilerOptions,"},
  {"file":"autoimport/extract.go","line":66,"text":"\t\t},"},
  {"file":"autoimport/extract.go","line":67,"text":"\t\tstats:    &extractorStats{},"},
  {"file":"autoimport/extract.go","line":68,"text":"\t\ttoPath:   toPath,"},
  {"file":"autoimport/extract.go","line":69,"text":"\t\trealpath: realpath,"},
  {"file":"autoimport/extract.go","line":70,"text":"\t}"},
  {"file":"autoimport/extract.go","line":71,"text":"}"},
  {"file":"autoimport/extract.go","line":73,"text":"func (b *registryBuilder) newExportExtractor(packageName string, checker *checker.Checker, moduleResolver *module.Resolver, realpath func(string) string) *exportExtractor {"},
  {"file":"autoimport/extract.go","line":74,"text":"\treturn &exportExtractor{"},
  {"file":"autoimport/extract.go","line":75,"text":"\t\tsymbolExtractor: newSymbolExtractor(packageName, checker, b.base.toPath, realpath),"},
  {"file":"autoimport/extract.go","line":76,"text":"\t\tmoduleResolver:  moduleResolver,"},
  {"file":"autoimport/extract.go","line":77,"text":"\t}"},
  {"file":"autoimport/extract.go","line":78,"text":"}"},
  {"file":"autoimport/extract.go","line":81,"text":"func (e *symbolExtractor) getModuleID(file *ast.SourceFile) ModuleID {"},
  {"file":"autoimport/extract.go","line":82,"text":"\tif e.realpath != nil && e.toPath != nil {"},
  {"file":"autoimport/extract.go","line":83,"text":"\t\trealpath := e.realpath(file.FileName())"},
  {"file":"autoimport/extract.go","line":84,"text":"\t\treturn ModuleID(e.toPath(realpath))"},
  {"file":"autoimport/extract.go","line":85,"text":"\t}"},
  {"file":"autoimport/extract.go","line":86,"text":"\treturn ModuleID(file.Path())"},
  {"file":"autoimport/extract.go","line":87,"text":"}"},
  {"file":"autoimport/extract.go","line":91,"text":"func (e *symbolExtractor) getModuleIDForSymbol(symbol *ast.Symbol) (ModuleID, bool) {"},
  {"file":"autoimport/extract.go","line":92,"text":"\tmoduleID, fileName, ok := tryGetModuleIDAndFileNameOfModuleSymbol(symbol)"},
  {"file":"autoimport/extract.go","line":93,"text":"\tif !ok {"},
  {"file":"autoimport/extract.go","line":94,"text":"\t\treturn \"\", false"},
  {"file":"autoimport/extract.go","line":95,"text":"\t}"},
  {"file":"autoimport/extract.go","line":97,"text":"\tif fileName != \"\" && e.realpath != nil {"},
  {"file":"autoimport/extract.go","line":98,"text":"\t\tdecl := ast.GetNonAugmentationDeclaration(symbol)"},
  {"file":"autoimport/extract.go","line":99,"text":"\t\tif decl != nil && decl.Kind == ast.KindSourceFile {"},
  {"file":"autoimport/extract.go","line":100,"text":"\t\t\treturn e.getModuleID(decl.AsSourceFile()), true"},
  {"file":"autoimport/extract.go","line":101,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":102,"text":"\t}"},
  {"file":"autoimport/extract.go","line":103,"text":"\treturn moduleID, true"},
  {"file":"autoimport/extract.go","line":104,"text":"}"},
  {"file":"autoimport/extract.go","line":106,"text":"func (e *exportExtractor) extractFromFile(file *ast.SourceFile) []*Export {"},
  {"file":"autoimport/extract.go","line":107,"text":"\tif file.Symbol != nil {"},
  {"file":"autoimport/extract.go","line":108,"text":"\t\treturn e.extractFromModule(file)"},
  {"file":"autoimport/extract.go","line":109,"text":"\t}"},
  {"file":"autoimport/extract.go","line":110,"text":"\tif len(file.AmbientModuleNames) > 0 {"},
  {"file":"autoimport/extract.go","line":111,"text":"\t\tmoduleDeclarations := core.Filter(file.Statements.Nodes, ast.IsModuleWithStringLiteralName)"},
  {"file":"autoimport/extract.go","line":112,"text":"\t\tvar exportCount int"},
  {"file":"autoimport/extract.go","line":113,"text":"\t\tfor _, decl := range moduleDeclarations {"},
  {"file":"autoimport/extract.go","line":114,"text":"\t\t\texportCount += len(decl.AsModuleDeclaration().Symbol.Exports)"},
  {"file":"autoimport/extract.go","line":115,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":116,"text":"\t\texports := make([]*Export, 0, exportCount)"},
  {"file":"autoimport/extract.go","line":117,"text":"\t\tfor _, decl := range moduleDeclarations {"},
  {"file":"autoimport/extract.go","line":118,"text":"\t\t\te.extractFromModuleDeclaration(decl.AsModuleDeclaration(), file, ModuleID(decl.Name().Text()), \"\", &exports)"},
  {"file":"autoimport/extract.go","line":119,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":120,"text":"\t\treturn exports"},
  {"file":"autoimport/extract.go","line":121,"text":"\t}"},
  {"file":"autoimport/extract.go","line":122,"text":"\treturn nil"},
  {"file":"autoimport/extract.go","line":123,"text":"}"},
  {"file":"autoimport/extract.go","line":125,"text":"func (e *exportExtractor) extractFromModule(file *ast.SourceFile) []*Export {"},
  {"file":"autoimport/extract.go","line":126,"text":"\tmoduleAugmentations := core.MapNonNil(file.ModuleAugmentations, func(name *ast.ModuleName) *ast.ModuleDeclaration {"},
  {"file":"autoimport/extract.go","line":127,"text":"\t\tdecl := name.Parent"},
  {"file":"autoimport/extract.go","line":128,"text":"\t\tif ast.IsGlobalScopeAugmentation(decl) {"},
  {"file":"autoimport/extract.go","line":129,"text":"\t\t\treturn nil"},
  {"file":"autoimport/extract.go","line":130,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":131,"text":"\t\treturn decl.AsModuleDeclaration()"},
  {"file":"autoimport/extract.go","line":132,"text":"\t})"},
  {"file":"autoimport/extract.go","line":133,"text":"\tvar augmentationExportCount int"},
  {"file":"autoimport/extract.go","line":134,"text":"\tfor _, decl := range moduleAugmentations {"},
  {"file":"autoimport/extract.go","line":135,"text":"\t\taugmentationExportCount += len(decl.Symbol.Exports)"},
  {"file":"autoimport/extract.go","line":136,"text":"\t}"},
  {"file":"autoimport/extract.go","line":137,"text":"\tmoduleID := e.getModuleID(file)"},
  {"file":"autoimport/extract.go","line":138,"text":"\texports := make([]*Export, 0, len(file.Symbol.Exports)+augmentationExportCount)"},
  {"file":"autoimport/extract.go","line":139,"text":"\tfor name, symbol := range file.Symbol.Exports {"},
  {"file":"autoimport/extract.go","line":140,"text":"\t\te.extractFromSymbol(name, symbol, moduleID, file.FileName(), file, &exports)"},
  {"file":"autoimport/extract.go","line":141,"text":"\t}"},
  {"file":"autoimport/extract.go","line":142,"text":"\tfor _, decl := range moduleAugmentations {"},
  {"file":"autoimport/extract.go","line":143,"text":"\t\tname := decl.Name().AsStringLiteral().Text"},
  {"file":"autoimport/extract.go","line":144,"text":"\t\tmoduleID := ModuleID(name)"},
  {"file":"autoimport/extract.go","line":145,"text":"\t\tvar moduleFileName string"},
  {"file":"autoimport/extract.go","line":146,"text":"\t\tif tspath.IsExternalModuleNameRelative(name) {"},
  {"file":"autoimport/extract.go","line":147,"text":"\t\t\tif resolved, _ := e.moduleResolver.ResolveModuleName(name, file.FileName(), core.ModuleKindCommonJS, nil); resolved.IsResolved() {"},
  {"file":"autoimport/extract.go","line":148,"text":"\t\t\t\tmoduleFileName = resolved.ResolvedFileName"},
  {"file":"autoimport/extract.go","line":149,"text":"\t\t\t\tmoduleID = ModuleID(e.toPath(moduleFileName))"},
  {"file":"autoimport/extract.go","line":150,"text":"\t\t\t} else {"},
  {"file":"autoimport/extract.go","line":152,"text":"\t\t\t\tmoduleFileName = tspath.ResolvePath(tspath.GetDirectoryPath(file.FileName()), name)"},
  {"file":"autoimport/extract.go","line":153,"text":"\t\t\t\tmoduleID = ModuleID(e.toPath(moduleFileName))"},
  {"file":"autoimport/extract.go","line":154,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":155,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":156,"text":"\t\te.extractFromModuleDeclaration(decl, file, moduleID, moduleFileName, &exports)"},
  {"file":"autoimport/extract.go","line":157,"text":"\t}"},
  {"file":"autoimport/extract.go","line":158,"text":"\treturn exports"},
  {"file":"autoimport/extract.go","line":159,"text":"}"},
  {"file":"autoimport/extract.go","line":161,"text":"func (e *exportExtractor) extractFromModuleDeclaration(decl *ast.ModuleDeclaration, file *ast.SourceFile, moduleID ModuleID, moduleFileName string, exports *[]*Export) {"},
  {"file":"autoimport/extract.go","line":162,"text":"\tfor name, symbol := range decl.Symbol.Exports {"},
  {"file":"autoimport/extract.go","line":163,"text":"\t\te.extractFromSymbol(name, symbol, moduleID, moduleFileName, file, exports)"},
  {"file":"autoimport/extract.go","line":164,"text":"\t}"},
  {"file":"autoimport/extract.go","line":165,"text":"}"},
  {"file":"autoimport/extract.go","line":167,"text":"func (e *symbolExtractor) extractFromSymbol(name string, symbol *ast.Symbol, moduleID ModuleID, moduleFileName string, file *ast.SourceFile, exports *[]*Export) {"},
  {"file":"autoimport/extract.go","line":168,"text":"\tif shouldIgnoreSymbol(symbol) {"},
  {"file":"autoimport/extract.go","line":169,"text":"\t\treturn"},
  {"file":"autoimport/extract.go","line":170,"text":"\t}"},
  {"file":"autoimport/extract.go","line":172,"text":"\tif name == ast.InternalSymbolNameExportStar {"},
  {"file":"autoimport/extract.go","line":173,"text":"\t\tcheckerLease := &checkerLease{checker: e.checker}"},
  {"file":"autoimport/extract.go","line":174,"text":"\t\tallExports := e.checker.GetExportsOfModule(symbol.Parent)"},
  {"file":"autoimport/extract.go","line":177,"text":"\t\tfor name, namedExport := range symbol.Parent.Exports {"},
  {"file":"autoimport/extract.go","line":178,"text":"\t\t\tif name != ast.InternalSymbolNameExportStar {"},
  {"file":"autoimport/extract.go","line":179,"text":"\t\t\t\tidx := slices.Index(allExports, namedExport)"},
  {"file":"autoimport/extract.go","line":180,"text":"\t\t\t\tif idx >= 0 || shouldIgnoreSymbol(namedExport) {"},
  {"file":"autoimport/extract.go","line":181,"text":"\t\t\t\t\tallExports = slices.Delete(allExports, idx, idx+1)"},
  {"file":"autoimport/extract.go","line":182,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":183,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":184,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":186,"text":"\t\t*exports = slices.Grow(*exports, len(allExports))"},
  {"file":"autoimport/extract.go","line":187,"text":"\t\tfor _, reexportedSymbol := range allExports {"},
  {"file":"autoimport/extract.go","line":188,"text":"\t\t\texport, _ := e.createExport(reexportedSymbol, moduleID, moduleFileName, ExportSyntaxStar, file, checkerLease)"},
  {"file":"autoimport/extract.go","line":189,"text":"\t\t\tif export != nil {"},
  {"file":"autoimport/extract.go","line":190,"text":"\t\t\t\tparent := checkerLease.GetChecker().GetMergedSymbol(reexportedSymbol.Parent)"},
  {"file":"autoimport/extract.go","line":191,"text":"\t\t\t\tif parent != nil && parent.IsExternalModule() {"},
  {"file":"autoimport/extract.go","line":192,"text":"\t\t\t\t\tif targetModuleID, ok := e.getModuleIDForSymbol(parent); ok {"},
  {"file":"autoimport/extract.go","line":193,"text":"\t\t\t\t\t\texport.Target = ExportID{"},
  {"file":"autoimport/extract.go","line":194,"text":"\t\t\t\t\t\t\tExportName: reexportedSymbol.Name,"},
  {"file":"autoimport/extract.go","line":195,"text":"\t\t\t\t\t\t\tModuleID:   targetModuleID,"},
  {"file":"autoimport/extract.go","line":196,"text":"\t\t\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":197,"text":"\t\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":198,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":199,"text":"\t\t\t\texport.through = ast.InternalSymbolNameExportStar"},
  {"file":"autoimport/extract.go","line":200,"text":"\t\t\t\t*exports = append(*exports, export)"},
  {"file":"autoimport/extract.go","line":201,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":202,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":203,"text":"\t\treturn"},
  {"file":"autoimport/extract.go","line":204,"text":"\t}"},
  {"file":"autoimport/extract.go","line":206,"text":"\tsyntax := getSyntax(symbol)"},
  {"file":"autoimport/extract.go","line":207,"text":"\tcheckerLease := &checkerLease{checker: e.checker}"},
  {"file":"autoimport/extract.go","line":208,"text":"\texport, target := e.createExport(symbol, moduleID, moduleFileName, syntax, file, checkerLease)"},
  {"file":"autoimport/extract.go","line":209,"text":"\tif export == nil {"},
  {"file":"autoimport/extract.go","line":210,"text":"\t\treturn"},
  {"file":"autoimport/extract.go","line":211,"text":"\t}"},
  {"file":"autoimport/extract.go","line":213,"text":"\t*exports = append(*exports, export)"},
  {"file":"autoimport/extract.go","line":215,"text":"\tif target != nil {"},
  {"file":"autoimport/extract.go","line":216,"text":"\t\tif syntax == ExportSyntaxEquals && target.Flags&ast.SymbolFlagsNamespace != 0 {"},
  {"file":"autoimport/extract.go","line":217,"text":"\t\t\t*exports = slices.Grow(*exports, len(target.Exports))"},
  {"file":"autoimport/extract.go","line":218,"text":"\t\t\tfor innerName, namedExport := range target.Exports {"},
  {"file":"autoimport/extract.go","line":219,"text":"\t\t\t\tif innerName != ast.InternalSymbolNameExportStar {"},
  {"file":"autoimport/extract.go","line":220,"text":"\t\t\t\t\texport, _ := e.createExport(namedExport, moduleID, moduleFileName, syntax, file, checkerLease)"},
  {"file":"autoimport/extract.go","line":221,"text":"\t\t\t\t\tif export != nil {"},
  {"file":"autoimport/extract.go","line":222,"text":"\t\t\t\t\t\texport.through = name"},
  {"file":"autoimport/extract.go","line":223,"text":"\t\t\t\t\t\t*exports = append(*exports, export)"},
  {"file":"autoimport/extract.go","line":224,"text":"\t\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":225,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":226,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":227,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":228,"text":"\t} else if syntax == ExportSyntaxCommonJSModuleExports {"},
  {"file":"autoimport/extract.go","line":229,"text":"\t\texpression := symbol.Declarations[0].AsBinaryExpression().Right"},
  {"file":"autoimport/extract.go","line":230,"text":"\t\tif expression.Kind == ast.KindObjectLiteralExpression {"},
  {"file":"autoimport/extract.go","line":234,"text":"\t\t\t*exports = slices.Grow(*exports, len(expression.AsObjectLiteralExpression().Properties.Nodes))"},
  {"file":"autoimport/extract.go","line":235,"text":"\t\t\tfor _, prop := range expression.AsObjectLiteralExpression().Properties.Nodes {"},
  {"file":"autoimport/extract.go","line":236,"text":"\t\t\t\tif ast.IsShorthandPropertyAssignment(prop) || ast.IsPropertyAssignment(prop) && prop.AsPropertyAssignment().Name().Kind == ast.KindIdentifier {"},
  {"file":"autoimport/extract.go","line":237,"text":"\t\t\t\t\texport, _ := e.createExport(expression.Symbol().Members[prop.Name().Text()], moduleID, moduleFileName, syntax, file, checkerLease)"},
  {"file":"autoimport/extract.go","line":238,"text":"\t\t\t\t\tif export != nil {"},
  {"file":"autoimport/extract.go","line":239,"text":"\t\t\t\t\t\texport.through = name"},
  {"file":"autoimport/extract.go","line":240,"text":"\t\t\t\t\t\t*exports = append(*exports, export)"},
  {"file":"autoimport/extract.go","line":241,"text":"\t\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":242,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":243,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":244,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":245,"text":"\t}"},
  {"file":"autoimport/extract.go","line":246,"text":"}"},
  {"file":"autoimport/extract.go","line":249,"text":"func (e *symbolExtractor) createExport(symbol *ast.Symbol, moduleID ModuleID, moduleFileName string, syntax ExportSyntax, file *ast.SourceFile, checkerLease *checkerLease) (*Export, *ast.Symbol) {"},
  {"file":"autoimport/extract.go","line":250,"text":"\tif shouldIgnoreSymbol(symbol) {"},
  {"file":"autoimport/extract.go","line":251,"text":"\t\treturn nil, nil"},
  {"file":"autoimport/extract.go","line":252,"text":"\t}"},
  {"file":"autoimport/extract.go","line":254,"text":"\texport := &Export{"},
  {"file":"autoimport/extract.go","line":255,"text":"\t\tExportID: ExportID{"},
  {"file":"autoimport/extract.go","line":256,"text":"\t\t\tExportName: symbol.Name,"},
  {"file":"autoimport/extract.go","line":257,"text":"\t\t\tModuleID:   moduleID,"},
  {"file":"autoimport/extract.go","line":258,"text":"\t\t},"},
  {"file":"autoimport/extract.go","line":259,"text":"\t\tModuleFileName: moduleFileName,"},
  {"file":"autoimport/extract.go","line":260,"text":"\t\tSyntax:         syntax,"},
  {"file":"autoimport/extract.go","line":261,"text":"\t\tFlags:          symbol.CombinedLocalAndExportSymbolFlags(),"},
  {"file":"autoimport/extract.go","line":262,"text":"\t\tPath:           file.Path(),"},
  {"file":"autoimport/extract.go","line":263,"text":"\t\tPackageName:    e.packageName,"},
  {"file":"autoimport/extract.go","line":264,"text":"\t}"},
  {"file":"autoimport/extract.go","line":266,"text":"\tif syntax == ExportSyntaxUMD {"},
  {"file":"autoimport/extract.go","line":267,"text":"\t\texport.ExportName = ast.InternalSymbolNameExportEquals"},
  {"file":"autoimport/extract.go","line":268,"text":"\t\texport.localName = symbol.Name"},
  {"file":"autoimport/extract.go","line":269,"text":"\t}"},
  {"file":"autoimport/extract.go","line":271,"text":"\tvar targetSymbol *ast.Symbol"},
  {"file":"autoimport/extract.go","line":272,"text":"\tif symbol.Flags&ast.SymbolFlagsAlias != 0 {"},
  {"file":"autoimport/extract.go","line":273,"text":"\t\ttargetSymbol = e.tryResolveSymbol(symbol, syntax, checkerLease)"},
  {"file":"autoimport/extract.go","line":274,"text":"\t\tif targetSymbol != nil {"},
  {"file":"autoimport/extract.go","line":275,"text":"\t\t\tvar decl *ast.Node"},
  {"file":"autoimport/extract.go","line":276,"text":"\t\t\tif len(targetSymbol.Declarations) > 0 {"},
  {"file":"autoimport/extract.go","line":277,"text":"\t\t\t\tdecl = targetSymbol.Declarations[0]"},
  {"file":"autoimport/extract.go","line":278,"text":"\t\t\t} else if targetSymbol.CheckFlags&ast.CheckFlagsMapped != 0 {"},
  {"file":"autoimport/extract.go","line":279,"text":"\t\t\t\tif mappedDecl := checkerLease.GetChecker().GetMappedTypeSymbolOfProperty(targetSymbol); mappedDecl != nil && len(mappedDecl.Declarations) > 0 {"},
  {"file":"autoimport/extract.go","line":280,"text":"\t\t\t\t\tdecl = mappedDecl.Declarations[0]"},
  {"file":"autoimport/extract.go","line":281,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":282,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":283,"text":"\t\t\tif decl == nil {"},
  {"file":"autoimport/extract.go","line":285,"text":"\t\t\t\tdecl = symbol.Declarations[0]"},
  {"file":"autoimport/extract.go","line":286,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":287,"text":"\t\t\tif decl == nil {"},
  {"file":"autoimport/extract.go","line":288,"text":"\t\t\t\tpanic(\"no declaration for aliased symbol\")"},
  {"file":"autoimport/extract.go","line":289,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":291,"text":"\t\t\tparent := targetSymbol.Parent"},
  {"file":"autoimport/extract.go","line":292,"text":"\t\t\tif checker := checkerLease.TryChecker(); checker != nil {"},
  {"file":"autoimport/extract.go","line":293,"text":"\t\t\t\texport.Flags = checker.GetSymbolFlags(targetSymbol)"},
  {"file":"autoimport/extract.go","line":294,"text":"\t\t\t\texport.IsTypeOnly = checker.GetTypeOnlyAliasDeclaration(symbol) != nil"},
  {"file":"autoimport/extract.go","line":295,"text":"\t\t\t\tparent = checker.GetMergedSymbol(parent)"},
  {"file":"autoimport/extract.go","line":296,"text":"\t\t\t} else {"},
  {"file":"autoimport/extract.go","line":297,"text":"\t\t\t\texport.Flags = targetSymbol.Flags"},
  {"file":"autoimport/extract.go","line":298,"text":"\t\t\t\texport.IsTypeOnly = core.Some(symbol.Declarations, ast.IsPartOfTypeOnlyImportOrExportDeclaration)"},
  {"file":"autoimport/extract.go","line":299,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":300,"text":"\t\t\texport.ScriptElementKind = lsutil.GetSymbolKind(checkerLease.TryChecker(), targetSymbol, decl)"},
  {"file":"autoimport/extract.go","line":301,"text":"\t\t\texport.ScriptElementKindModifiers = lsutil.GetSymbolModifiers(checkerLease.TryChecker(), targetSymbol)"},
  {"file":"autoimport/extract.go","line":302,"text":"\t\t\ttargetModuleID := ModuleID(ast.GetSourceFileOfNode(decl).Path())"},
  {"file":"autoimport/extract.go","line":303,"text":"\t\t\tif parent != nil && parent.IsExternalModule() {"},
  {"file":"autoimport/extract.go","line":304,"text":"\t\t\t\tif id, ok := e.getModuleIDForSymbol(parent); ok {"},
  {"file":"autoimport/extract.go","line":305,"text":"\t\t\t\t\ttargetModuleID = id"},
  {"file":"autoimport/extract.go","line":306,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":307,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":308,"text":"\t\t\texport.Target = ExportID{"},
  {"file":"autoimport/extract.go","line":309,"text":"\t\t\t\tExportName: targetSymbol.Name,"},
  {"file":"autoimport/extract.go","line":310,"text":"\t\t\t\tModuleID:   targetModuleID,"},
  {"file":"autoimport/extract.go","line":311,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":312,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":313,"text":"\t} else {"},
  {"file":"autoimport/extract.go","line":314,"text":"\t\texport.ScriptElementKind = lsutil.GetSymbolKind(checkerLease.TryChecker(), symbol, symbol.Declarations[0])"},
  {"file":"autoimport/extract.go","line":315,"text":"\t\texport.ScriptElementKindModifiers = lsutil.GetSymbolModifiers(checkerLease.TryChecker(), symbol)"},
  {"file":"autoimport/extract.go","line":316,"text":"\t}"},
  {"file":"autoimport/extract.go","line":318,"text":"\tif symbol.Name == ast.InternalSymbolNameDefault || symbol.Name == ast.InternalSymbolNameExportEquals {"},
  {"file":"autoimport/extract.go","line":319,"text":"\t\tnamedSymbol := symbol"},
  {"file":"autoimport/extract.go","line":320,"text":"\t\tif s := binder.GetLocalSymbolForExportDefault(symbol); s != nil {"},
  {"file":"autoimport/extract.go","line":321,"text":"\t\t\tnamedSymbol = s"},
  {"file":"autoimport/extract.go","line":322,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":323,"text":"\t\texport.localName = getDefaultLikeExportNameFromDeclaration(namedSymbol)"},
  {"file":"autoimport/extract.go","line":324,"text":"\t\tif isUnusableName(export.localName) {"},
  {"file":"autoimport/extract.go","line":325,"text":"\t\t\texport.localName = export.Target.ExportName"},
  {"file":"autoimport/extract.go","line":326,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":327,"text":"\t\tif isUnusableName(export.localName) {"},
  {"file":"autoimport/extract.go","line":328,"text":"\t\t\tif targetSymbol != nil {"},
  {"file":"autoimport/extract.go","line":329,"text":"\t\t\t\tnamedSymbol = targetSymbol"},
  {"file":"autoimport/extract.go","line":330,"text":"\t\t\t\tif s := binder.GetLocalSymbolForExportDefault(targetSymbol); s != nil {"},
  {"file":"autoimport/extract.go","line":331,"text":"\t\t\t\t\tnamedSymbol = s"},
  {"file":"autoimport/extract.go","line":332,"text":"\t\t\t\t}"},
  {"file":"autoimport/extract.go","line":333,"text":"\t\t\t\texport.localName = getDefaultLikeExportNameFromDeclaration(namedSymbol)"},
  {"file":"autoimport/extract.go","line":334,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":335,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":336,"text":"\t\tif isUnusableName(export.localName) {"},
  {"file":"autoimport/extract.go","line":340,"text":"\t\t\texport.localName = lsutil.ModuleSpecifierToValidIdentifier(fileNameForDefaultExportName(targetSymbol, moduleFileName, moduleID), false)"},
  {"file":"autoimport/extract.go","line":341,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":342,"text":"\t}"},
  {"file":"autoimport/extract.go","line":344,"text":"\tif isUnusableName(export.Name()) {"},
  {"file":"autoimport/extract.go","line":345,"text":"\t\treturn nil, nil"},
  {"file":"autoimport/extract.go","line":346,"text":"\t}"},
  {"file":"autoimport/extract.go","line":348,"text":"\te.stats.exports.Add(1)"},
  {"file":"autoimport/extract.go","line":349,"text":"\tif checkerLease.TryChecker() != nil {"},
  {"file":"autoimport/extract.go","line":350,"text":"\t\te.stats.usedChecker.Add(1)"},
  {"file":"autoimport/extract.go","line":351,"text":"\t}"},
  {"file":"autoimport/extract.go","line":353,"text":"\treturn export, targetSymbol"},
  {"file":"autoimport/extract.go","line":354,"text":"}"},
  {"file":"autoimport/extract.go","line":356,"text":"func (e *symbolExtractor) tryResolveSymbol(symbol *ast.Symbol, syntax ExportSyntax, checkerLease *checkerLease) *ast.Symbol {"},
  {"file":"autoimport/extract.go","line":357,"text":"\tif !ast.IsNonLocalAlias(symbol, ast.SymbolFlagsNone) {"},
  {"file":"autoimport/extract.go","line":358,"text":"\t\treturn symbol"},
  {"file":"autoimport/extract.go","line":359,"text":"\t}"},
  {"file":"autoimport/extract.go","line":361,"text":"\tvar loc *ast.Node"},
  {"file":"autoimport/extract.go","line":362,"text":"\tvar name string"},
  {"file":"autoimport/extract.go","line":363,"text":"\tswitch syntax {"},
  {"file":"autoimport/extract.go","line":364,"text":"\tcase ExportSyntaxNamed:"},
  {"file":"autoimport/extract.go","line":365,"text":"\t\tdecl := ast.GetDeclarationOfKind(symbol, ast.KindExportSpecifier)"},
  {"file":"autoimport/extract.go","line":366,"text":"\t\tif decl.Parent.Parent.AsExportDeclaration().ModuleSpecifier == nil {"},
  {"file":"autoimport/extract.go","line":367,"text":"\t\t\tif n := core.FirstNonZero(decl.Name(), decl.PropertyName()); n.Kind == ast.KindIdentifier {"},
  {"file":"autoimport/extract.go","line":368,"text":"\t\t\t\tloc = n"},
  {"file":"autoimport/extract.go","line":369,"text":"\t\t\t\tname = n.Text()"},
  {"file":"autoimport/extract.go","line":370,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":371,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":373,"text":"\tcase ExportSyntaxEquals:"},
  {"file":"autoimport/extract.go","line":374,"text":"\t\tif symbol.Name != ast.InternalSymbolNameExportEquals {"},
  {"file":"autoimport/extract.go","line":375,"text":"\t\t\tbreak"},
  {"file":"autoimport/extract.go","line":376,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":377,"text":"\t\tfallthrough"},
  {"file":"autoimport/extract.go","line":378,"text":"\tcase ExportSyntaxDefaultDeclaration:"},
  {"file":"autoimport/extract.go","line":379,"text":"\t\tdecl := ast.GetDeclarationOfKind(symbol, ast.KindExportAssignment)"},
  {"file":"autoimport/extract.go","line":380,"text":"\t\tif decl.Expression().Kind == ast.KindIdentifier {"},
  {"file":"autoimport/extract.go","line":381,"text":"\t\t\tloc = decl.Expression()"},
  {"file":"autoimport/extract.go","line":382,"text":"\t\t\tname = loc.Text()"},
  {"file":"autoimport/extract.go","line":383,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":384,"text":"\t}"},
  {"file":"autoimport/extract.go","line":386,"text":"\tif loc != nil {"},
  {"file":"autoimport/extract.go","line":387,"text":"\t\tlocal := e.localNameResolver.Resolve(loc, name, ast.SymbolFlagsAll, nil, false, false)"},
  {"file":"autoimport/extract.go","line":388,"text":"\t\tif local != nil && !ast.IsNonLocalAlias(local, ast.SymbolFlagsNone) {"},
  {"file":"autoimport/extract.go","line":389,"text":"\t\t\treturn local"},
  {"file":"autoimport/extract.go","line":390,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":391,"text":"\t}"},
  {"file":"autoimport/extract.go","line":393,"text":"\tchecker := checkerLease.GetChecker()"},
  {"file":"autoimport/extract.go","line":394,"text":"\tif resolved := checker.GetAliasedSymbol(symbol); !checker.IsUnknownSymbol(resolved) {"},
  {"file":"autoimport/extract.go","line":395,"text":"\t\treturn resolved"},
  {"file":"autoimport/extract.go","line":396,"text":"\t}"},
  {"file":"autoimport/extract.go","line":397,"text":"\treturn nil"},
  {"file":"autoimport/extract.go","line":398,"text":"}"},
  {"file":"autoimport/extract.go","line":400,"text":"func shouldIgnoreSymbol(symbol *ast.Symbol) bool {"},
  {"file":"autoimport/extract.go","line":401,"text":"\tif symbol.Flags&ast.SymbolFlagsPrototype != 0 {"},
  {"file":"autoimport/extract.go","line":402,"text":"\t\treturn true"},
  {"file":"autoimport/extract.go","line":403,"text":"\t}"},
  {"file":"autoimport/extract.go","line":404,"text":"\treturn false"},
  {"file":"autoimport/extract.go","line":405,"text":"}"},
  {"file":"autoimport/extract.go","line":407,"text":"func getSyntax(symbol *ast.Symbol) ExportSyntax {"},
  {"file":"autoimport/extract.go","line":408,"text":"\tfor _, decl := range symbol.Declarations {"},
  {"file":"autoimport/extract.go","line":409,"text":"\t\tswitch decl.Kind {"},
  {"file":"autoimport/extract.go","line":410,"text":"\t\tcase ast.KindExportSpecifier:"},
  {"file":"autoimport/extract.go","line":411,"text":"\t\t\treturn ExportSyntaxNamed"},
  {"file":"autoimport/extract.go","line":412,"text":"\t\tcase ast.KindExportAssignment:"},
  {"file":"autoimport/extract.go","line":413,"text":"\t\t\treturn core.IfElse("},
  {"file":"autoimport/extract.go","line":414,"text":"\t\t\t\tdecl.AsExportAssignment().IsExportEquals,"},
  {"file":"autoimport/extract.go","line":415,"text":"\t\t\t\tExportSyntaxEquals,"},
  {"file":"autoimport/extract.go","line":416,"text":"\t\t\t\tExportSyntaxDefaultDeclaration,"},
  {"file":"autoimport/extract.go","line":417,"text":"\t\t\t)"},
  {"file":"autoimport/extract.go","line":418,"text":"\t\tcase ast.KindNamespaceExportDeclaration:"},
  {"file":"autoimport/extract.go","line":419,"text":"\t\t\treturn ExportSyntaxUMD"},
  {"file":"autoimport/extract.go","line":420,"text":"\t\tcase ast.KindBinaryExpression:"},
  {"file":"autoimport/extract.go","line":421,"text":"\t\t\tswitch ast.GetAssignmentDeclarationKind(decl) {"},
  {"file":"autoimport/extract.go","line":422,"text":"\t\t\tcase ast.JSDeclarationKindModuleExports:"},
  {"file":"autoimport/extract.go","line":423,"text":"\t\t\t\treturn ExportSyntaxCommonJSModuleExports"},
  {"file":"autoimport/extract.go","line":424,"text":"\t\t\tcase ast.JSDeclarationKindExportsProperty:"},
  {"file":"autoimport/extract.go","line":425,"text":"\t\t\t\treturn ExportSyntaxCommonJSExportsProperty"},
  {"file":"autoimport/extract.go","line":426,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":427,"text":"\t\tdefault:"},
  {"file":"autoimport/extract.go","line":428,"text":"\t\t\tif ast.GetCombinedModifierFlags(decl)&ast.ModifierFlagsDefault != 0 {"},
  {"file":"autoimport/extract.go","line":429,"text":"\t\t\t\treturn ExportSyntaxDefaultModifier"},
  {"file":"autoimport/extract.go","line":430,"text":"\t\t\t} else {"},
  {"file":"autoimport/extract.go","line":431,"text":"\t\t\t\treturn ExportSyntaxModifier"},
  {"file":"autoimport/extract.go","line":432,"text":"\t\t\t}"},
  {"file":"autoimport/extract.go","line":433,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":434,"text":"\t}"},
  {"file":"autoimport/extract.go","line":435,"text":"\treturn ExportSyntaxNone"},
  {"file":"autoimport/extract.go","line":436,"text":"}"},
  {"file":"autoimport/extract.go","line":438,"text":"func isUnusableName(name string) bool {"},
  {"file":"autoimport/extract.go","line":439,"text":"\treturn name == \"\" ||"},
  {"file":"autoimport/extract.go","line":440,"text":"\t\tname == \"_default\" ||"},
  {"file":"autoimport/extract.go","line":441,"text":"\t\tname == ast.InternalSymbolNameExportStar ||"},
  {"file":"autoimport/extract.go","line":442,"text":"\t\tname == ast.InternalSymbolNameDefault ||"},
  {"file":"autoimport/extract.go","line":443,"text":"\t\tname == ast.InternalSymbolNameExportEquals"},
  {"file":"autoimport/extract.go","line":444,"text":"}"},
  {"file":"autoimport/extract.go","line":451,"text":"func fileNameForDefaultExportName(targetSymbol *ast.Symbol, moduleFileName string, moduleID ModuleID) string {"},
  {"file":"autoimport/extract.go","line":452,"text":"\tif targetSymbol != nil && len(targetSymbol.Declarations) > 0 {"},
  {"file":"autoimport/extract.go","line":453,"text":"\t\tif fn := ast.GetSourceFileOfNode(targetSymbol.Declarations[0]).FileName(); fn != \"\" {"},
  {"file":"autoimport/extract.go","line":454,"text":"\t\t\treturn fn"},
  {"file":"autoimport/extract.go","line":455,"text":"\t\t}"},
  {"file":"autoimport/extract.go","line":456,"text":"\t}"},
  {"file":"autoimport/extract.go","line":457,"text":"\tif moduleFileName != \"\" {"},
  {"file":"autoimport/extract.go","line":458,"text":"\t\treturn moduleFileName"},
  {"file":"autoimport/extract.go","line":459,"text":"\t}"},
  {"file":"autoimport/extract.go","line":460,"text":"\treturn string(moduleID)"},
  {"file":"autoimport/extract.go","line":461,"text":"}"},
  {"file":"autoimport/fix.go","line":1,"text":"package autoimport"},
  {"file":"autoimport/fix.go","line":3,"text":"import ("},
  {"file":"autoimport/fix.go","line":4,"text":"\t\"cmp\""},
  {"file":"autoimport/fix.go","line":5,"text":"\t\"context\""},
  {"file":"autoimport/fix.go","line":6,"text":"\t\"fmt\""},
  {"file":"autoimport/fix.go","line":7,"text":"\t\"slices\""},
  {"file":"autoimport/fix.go","line":8,"text":"\t\"strings\""},
  {"file":"autoimport/fix.go","line":9,"text":"\t\"unicode\""},
  {"file":"autoimport/fix.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"autoimport/fix.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"file":"autoimport/fix.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"file":"autoimport/fix.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"autoimport/fix.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"file":"autoimport/fix.go","line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"autoimport/fix.go","line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/debug\""},
  {"file":"autoimport/fix.go","line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"autoimport/fix.go","line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/locale\""},
  {"file":"autoimport/fix.go","line":20,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/change\""},
  {"file":"autoimport/fix.go","line":21,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"file":"autoimport/fix.go","line":22,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"file":"autoimport/fix.go","line":23,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"file":"autoimport/fix.go","line":24,"text":"\t\"github.com/microsoft/typescript-go/internal/modulespecifiers\""},
  {"file":"autoimport/fix.go","line":25,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"file":"autoimport/fix.go","line":26,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"file":"autoimport/fix.go","line":27,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"autoimport/fix.go","line":28,"text":")"},
  {"file":"autoimport/fix.go","line":30,"text":"type newImportBinding struct {"},
  {"file":"autoimport/fix.go","line":31,"text":"\tkind          lsproto.ImportKind"},
  {"file":"autoimport/fix.go","line":32,"text":"\tpropertyName  string"},
  {"file":"autoimport/fix.go","line":33,"text":"\tname          string"},
  {"file":"autoimport/fix.go","line":34,"text":"\taddAsTypeOnly lsproto.AddAsTypeOnly"},
];

export function lsStrictParityLineText(file: string, line: number): string | undefined {
  return lsStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function lsStrictParityFiles(): readonly string[] {
  return [...new Set(lsStrictParitySourceLines.map((entry) => entry.file))].sort();
}
