/**
 * Language-service parity map for TS-Go `ls/symbols.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsUpstreamPath = "ls/symbols.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsDeclarations: readonly UpstreamDeclaration[] = [
  {"line":24,"kind":"func","name":"ProvideDocumentSymbols","receiver":"l *LanguageService"},
  {"line":40,"kind":"func","name":"getDocumentSymbolInformations","receiver":"l *LanguageService"},
  {"line":72,"kind":"func","name":"getDocumentSymbolsForChildren","receiver":"l *LanguageService"},
  {"line":260,"kind":"func","name":"isPrototypeExpando"},
  {"line":268,"kind":"const","name":"maxLength"},
  {"line":270,"kind":"func","name":"newDocumentSymbol","receiver":"l *LanguageService"},
  {"line":327,"kind":"func","name":"mergeExpandos"},
  {"line":386,"kind":"func","name":"mergeChildren"},
  {"line":400,"kind":"func","name":"isAnonymousName"},
  {"line":405,"kind":"func","name":"getTextOfName"},
  {"line":421,"kind":"func","name":"getUnnamedNodeLabel"},
  {"line":462,"kind":"func","name":"getCallExpressionName"},
  {"line":477,"kind":"func","name":"getCallExpressionLiteralArgs"},
  {"line":487,"kind":"func","name":"cleanCallbackText"},
  {"line":500,"kind":"func","name":"getInteriorModule"},
  {"line":507,"kind":"func","name":"getModuleName"},
  {"line":516,"kind":"type","name":"DeclarationInfo"},
  {"line":522,"kind":"func","name":"ProvideWorkspaceSymbols"},
  {"line":586,"kind":"func","name":"shouldExcludeFile"},
  {"line":590,"kind":"func","name":"isInsideNodeModules"},
  {"line":599,"kind":"func","name":"getMatchScore"},
  {"line":620,"kind":"func","name":"compareDeclarationInfos"},
  {"line":640,"kind":"func","name":"getSymbolKindFromNode"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"context\""},
  {"line":5,"text":"\t\"slices\""},
  {"line":6,"text":"\t\"strings\""},
  {"line":7,"text":"\t\"unicode\""},
  {"line":8,"text":"\t\"unicode/utf8\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/printer\""},
  {"line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":20,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"line":21,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"line":22,"text":")"},
  {"line":24,"text":"func (l *LanguageService) ProvideDocumentSymbols(ctx context.Context, documentURI lsproto.DocumentUri) (lsproto.DocumentSymbolResponse, error) {"},
  {"line":25,"text":"\t_, file := l.getProgramAndFile(documentURI)"},
  {"line":26,"text":"\tif lsproto.GetClientCapabilities(ctx).TextDocument.DocumentSymbol.HierarchicalDocumentSymbolSupport {"},
  {"line":27,"text":"\t\tsymbols := l.getDocumentSymbolsForChildren(ctx, file.AsNode(), file)"},
  {"line":28,"text":"\t\treturn lsproto.SymbolInformationsOrDocumentSymbolsOrNull{DocumentSymbols: &symbols}, nil"},
  {"line":29,"text":"\t}"},
  {"line":31,"text":"\tsymbolInfos := l.getDocumentSymbolInformations(ctx, file, documentURI)"},
  {"line":32,"text":"\tsymbolInfoPtrs := make([]*lsproto.SymbolInformation, len(symbolInfos))"},
  {"line":33,"text":"\tfor i := range symbolInfos {"},
  {"line":34,"text":"\t\tsymbolInfoPtrs[i] = &symbolInfos[i]"},
  {"line":35,"text":"\t}"},
  {"line":36,"text":"\treturn lsproto.SymbolInformationsOrDocumentSymbolsOrNull{SymbolInformations: &symbolInfoPtrs}, nil"},
  {"line":37,"text":"}"},
  {"line":40,"text":"func (l *LanguageService) getDocumentSymbolInformations(ctx context.Context, file *ast.SourceFile, documentURI lsproto.DocumentUri) []lsproto.SymbolInformation {"},
  {"line":42,"text":"\tdocSymbols := l.getDocumentSymbolsForChildren(ctx, file.AsNode(), file)"},
  {"line":45,"text":"\tvar result []lsproto.SymbolInformation"},
  {"line":46,"text":"\tvar flatten func(symbols []*lsproto.DocumentSymbol, containerName *string)"},
  {"line":47,"text":"\tflatten = func(symbols []*lsproto.DocumentSymbol, containerName *string) {"},
  {"line":48,"text":"\t\tfor _, symbol := range symbols {"},
  {"line":49,"text":"\t\t\tinfo := lsproto.SymbolInformation{"},
  {"line":50,"text":"\t\t\t\tName: symbol.Name,"},
  {"line":51,"text":"\t\t\t\tKind: symbol.Kind,"},
  {"line":52,"text":"\t\t\t\tLocation: lsproto.Location{"},
  {"line":53,"text":"\t\t\t\t\tUri:   documentURI,"},
  {"line":54,"text":"\t\t\t\t\tRange: symbol.Range,"},
  {"line":55,"text":"\t\t\t\t},"},
  {"line":56,"text":"\t\t\t\tContainerName: containerName,"},
  {"line":57,"text":"\t\t\t\tTags:          symbol.Tags,"},
  {"line":58,"text":"\t\t\t\tDeprecated:    symbol.Deprecated,"},
  {"line":59,"text":"\t\t\t}"},
  {"line":60,"text":"\t\t\tresult = append(result, info)"},
  {"line":63,"text":"\t\t\tif symbol.Children != nil && len(*symbol.Children) > 0 {"},
  {"line":64,"text":"\t\t\t\tflatten(*symbol.Children, &symbol.Name)"},
  {"line":65,"text":"\t\t\t}"},
  {"line":66,"text":"\t\t}"},
  {"line":67,"text":"\t}"},
  {"line":68,"text":"\tflatten(docSymbols, nil)"},
  {"line":69,"text":"\treturn result"},
  {"line":70,"text":"}"},
  {"line":72,"text":"func (l *LanguageService) getDocumentSymbolsForChildren(ctx context.Context, node *ast.Node, file *ast.SourceFile) []*lsproto.DocumentSymbol {"},
  {"line":73,"text":"\tvar symbols []*lsproto.DocumentSymbol"},
  {"line":74,"text":"\texpandoTargets := collections.Set[string]{}"},
  {"line":75,"text":"\taddSymbolForNode := func(node *ast.Node, name *ast.Node, children []*lsproto.DocumentSymbol) {"},
  {"line":76,"text":"\t\tif node.Flags&ast.NodeFlagsReparsed == 0 {"},
  {"line":77,"text":"\t\t\tsymbol := l.newDocumentSymbol(node, name, children)"},
  {"line":78,"text":"\t\t\tif symbol != nil {"},
  {"line":79,"text":"\t\t\t\tsymbols = append(symbols, symbol)"},
  {"line":80,"text":"\t\t\t}"},
  {"line":81,"text":"\t\t}"},
  {"line":82,"text":"\t}"},
  {"line":83,"text":"\tvar visit func(*ast.Node) bool"},
  {"line":84,"text":"\tgetSymbolsForChildren := func(node *ast.Node) []*lsproto.DocumentSymbol {"},
  {"line":85,"text":"\t\tvar result []*lsproto.DocumentSymbol"},
  {"line":86,"text":"\t\tif node != nil {"},
  {"line":87,"text":"\t\t\tsaveExpandoTargets := expandoTargets"},
  {"line":88,"text":"\t\t\texpandoTargets = collections.Set[string]{}"},
  {"line":89,"text":"\t\t\tsaveSymbols := symbols"},
  {"line":90,"text":"\t\t\tsymbols = nil"},
  {"line":91,"text":"\t\t\tnode.ForEachChild(visit)"},
  {"line":92,"text":"\t\t\tresult = symbols"},
  {"line":93,"text":"\t\t\tsymbols = saveSymbols"},
  {"line":94,"text":"\t\t\texpandoTargets = saveExpandoTargets"},
  {"line":95,"text":"\t\t}"},
  {"line":96,"text":"\t\treturn result"},
  {"line":97,"text":"\t}"},
  {"line":98,"text":"\tstartNode := func(node *ast.Node, name *ast.Node) func() {"},
  {"line":99,"text":"\t\tif node == nil {"},
  {"line":100,"text":"\t\t\treturn func() {}"},
  {"line":101,"text":"\t\t}"},
  {"line":102,"text":"\t\tsaveExpandoTargets := expandoTargets"},
  {"line":103,"text":"\t\texpandoTargets = collections.Set[string]{}"},
  {"line":104,"text":"\t\tsaveSymbols := symbols"},
  {"line":105,"text":"\t\tsymbols = nil"},
  {"line":106,"text":"\t\treturn func() {"},
  {"line":107,"text":"\t\t\tresult := symbols"},
  {"line":108,"text":"\t\t\tsymbols = saveSymbols"},
  {"line":109,"text":"\t\t\texpandoTargets = saveExpandoTargets"},
  {"line":110,"text":"\t\t\taddSymbolForNode(node, name, result)"},
  {"line":111,"text":"\t\t}"},
  {"line":112,"text":"\t}"},
  {"line":113,"text":"\tgetSymbolsForNode := func(node *ast.Node) []*lsproto.DocumentSymbol {"},
  {"line":114,"text":"\t\tvar result []*lsproto.DocumentSymbol"},
  {"line":115,"text":"\t\tif node != nil {"},
  {"line":116,"text":"\t\t\tsaveSymbols := symbols"},
  {"line":117,"text":"\t\t\tsymbols = nil"},
  {"line":118,"text":"\t\t\tvisit(node)"},
  {"line":119,"text":"\t\t\tresult = symbols"},
  {"line":120,"text":"\t\t\tsymbols = saveSymbols"},
  {"line":121,"text":"\t\t}"},
  {"line":122,"text":"\t\treturn result"},
  {"line":123,"text":"\t}"},
  {"line":124,"text":"\tvisit = func(node *ast.Node) bool {"},
  {"line":125,"text":"\t\tif ctx.Err() != nil {"},
  {"line":126,"text":"\t\t\treturn true"},
  {"line":127,"text":"\t\t}"},
  {"line":128,"text":"\t\tif node.Flags&ast.NodeFlagsReparsed == 0 {"},
  {"line":129,"text":"\t\t\tif jsdocs := node.JSDoc(file); len(jsdocs) > 0 {"},
  {"line":130,"text":"\t\t\t\tfor _, jsdoc := range jsdocs {"},
  {"line":131,"text":"\t\t\t\t\tif tagList := jsdoc.AsJSDoc().Tags; tagList != nil {"},
  {"line":132,"text":"\t\t\t\t\t\tfor _, tag := range tagList.Nodes {"},
  {"line":133,"text":"\t\t\t\t\t\t\tif ast.IsJSDocTypedefTag(tag) || ast.IsJSDocCallbackTag(tag) {"},
  {"line":134,"text":"\t\t\t\t\t\t\t\taddSymbolForNode(tag, nil /*name*/, nil /*children*/)"},
  {"line":135,"text":"\t\t\t\t\t\t\t}"},
  {"line":136,"text":"\t\t\t\t\t\t}"},
  {"line":137,"text":"\t\t\t\t\t}"},
  {"line":138,"text":"\t\t\t\t}"},
  {"line":139,"text":"\t\t\t}"},
  {"line":140,"text":"\t\t}"},
  {"line":141,"text":"\t\tswitch node.Kind {"},
  {"line":142,"text":"\t\tcase ast.KindClassDeclaration, ast.KindClassExpression, ast.KindInterfaceDeclaration, ast.KindEnumDeclaration:"},
  {"line":143,"text":"\t\t\tif ast.IsClassLike(node) && ast.GetDeclarationName(node) != \"\" {"},
  {"line":144,"text":"\t\t\t\texpandoTargets.Add(ast.GetDeclarationName(node))"},
  {"line":145,"text":"\t\t\t}"},
  {"line":146,"text":"\t\t\taddSymbolForNode(node, nil /*name*/, getSymbolsForChildren(node))"},
  {"line":147,"text":"\t\tcase ast.KindModuleDeclaration:"},
  {"line":148,"text":"\t\t\taddSymbolForNode(node, nil /*name*/, getSymbolsForChildren(getInteriorModule(node)))"},
  {"line":149,"text":"\t\tcase ast.KindConstructor:"},
  {"line":150,"text":"\t\t\taddSymbolForNode(node, nil /*name*/, getSymbolsForChildren(node.Body()))"},
  {"line":151,"text":"\t\t\tfor _, param := range node.Parameters() {"},
  {"line":152,"text":"\t\t\t\tif ast.IsParameterPropertyDeclaration(param, node) {"},
  {"line":153,"text":"\t\t\t\t\taddSymbolForNode(param, nil /*name*/, nil /*children*/)"},
  {"line":154,"text":"\t\t\t\t}"},
  {"line":155,"text":"\t\t\t}"},
  {"line":156,"text":"\t\tcase ast.KindFunctionDeclaration, ast.KindFunctionExpression, ast.KindArrowFunction, ast.KindMethodDeclaration, ast.KindGetAccessor,"},
  {"line":157,"text":"\t\t\tast.KindSetAccessor:"},
  {"line":158,"text":"\t\t\tdeclName := ast.GetDeclarationName(node)"},
  {"line":159,"text":"\t\t\tif declName != \"\" {"},
  {"line":160,"text":"\t\t\t\texpandoTargets.Add(declName)"},
  {"line":161,"text":"\t\t\t}"},
  {"line":162,"text":"\t\t\taddSymbolForNode(node, nil /*name*/, getSymbolsForChildren(node.Body()))"},
  {"line":163,"text":"\t\tcase ast.KindVariableDeclaration, ast.KindBindingElement, ast.KindPropertyAssignment, ast.KindPropertyDeclaration:"},
  {"line":164,"text":"\t\t\tnodeName := node.Name()"},
  {"line":165,"text":"\t\t\tif nodeName != nil {"},
  {"line":166,"text":"\t\t\t\tif ast.IsBindingPattern(nodeName) {"},
  {"line":167,"text":"\t\t\t\t\tvisit(nodeName)"},
  {"line":168,"text":"\t\t\t\t} else {"},
  {"line":169,"text":"\t\t\t\t\taddSymbolForNode(node, nil /*name*/, getSymbolsForChildren(node.Initializer()))"},
  {"line":170,"text":"\t\t\t\t}"},
  {"line":171,"text":"\t\t\t}"},
  {"line":172,"text":"\t\tcase ast.KindSpreadAssignment:"},
  {"line":173,"text":"\t\t\taddSymbolForNode(node, node.Expression(), nil /*children*/)"},
  {"line":174,"text":"\t\tcase ast.KindMethodSignature, ast.KindPropertySignature, ast.KindCallSignature, ast.KindConstructSignature, ast.KindIndexSignature,"},
  {"line":175,"text":"\t\t\tast.KindEnumMember, ast.KindShorthandPropertyAssignment, ast.KindTypeAliasDeclaration, ast.KindImportEqualsDeclaration, ast.KindExportSpecifier:"},
  {"line":176,"text":"\t\t\taddSymbolForNode(node, nil /*name*/, nil /*children*/)"},
  {"line":177,"text":"\t\tcase ast.KindImportClause:"},
  {"line":180,"text":"\t\t\tif node.Name() != nil {"},
  {"line":181,"text":"\t\t\t\taddSymbolForNode(node.Name(), node.Name(), nil /*children*/)"},
  {"line":182,"text":"\t\t\t}"},
  {"line":186,"text":"\t\t\tif namedBindings := node.AsImportClause().NamedBindings; namedBindings != nil {"},
  {"line":187,"text":"\t\t\t\tif namedBindings.Kind == ast.KindNamespaceImport {"},
  {"line":188,"text":"\t\t\t\t\taddSymbolForNode(namedBindings, nil /*name*/, nil /*children*/)"},
  {"line":189,"text":"\t\t\t\t} else {"},
  {"line":190,"text":"\t\t\t\t\tfor _, element := range namedBindings.Elements() {"},
  {"line":191,"text":"\t\t\t\t\t\taddSymbolForNode(element, nil /*name*/, nil /*children*/)"},
  {"line":192,"text":"\t\t\t\t\t}"},
  {"line":193,"text":"\t\t\t\t}"},
  {"line":194,"text":"\t\t\t}"},
  {"line":195,"text":"\t\tcase ast.KindBinaryExpression, ast.KindCallExpression:"},
  {"line":196,"text":"\t\t\tassignmentKind := ast.GetAssignmentDeclarationKind(node)"},
  {"line":197,"text":"\t\t\tswitch assignmentKind {"},
  {"line":200,"text":"\t\t\tcase ast.JSDeclarationKindNone, ast.JSDeclarationKindThisProperty,"},
  {"line":201,"text":"\t\t\t\tast.JSDeclarationKindModuleExports, ast.JSDeclarationKindExportsProperty,"},
  {"line":202,"text":"\t\t\t\tast.JSDeclarationKindObjectDefinePropertyExports:"},
  {"line":203,"text":"\t\t\t\tnode.ForEachChild(visit)"},
  {"line":204,"text":"\t\t\tcase ast.JSDeclarationKindProperty, ast.JSDeclarationKindObjectDefinePropertyValue:"},
  {"line":205,"text":"\t\t\t\tvar target *ast.Expression"},
  {"line":206,"text":"\t\t\t\tvar targetFunction *ast.Expression"},
  {"line":207,"text":"\t\t\t\tvar definition *ast.Node"},
  {"line":208,"text":"\t\t\t\tvar propertyName *ast.Node"},
  {"line":210,"text":"\t\t\t\tif ast.IsBinaryExpression(node) {"},
  {"line":211,"text":"\t\t\t\t\tbinaryExpr := node.AsBinaryExpression()"},
  {"line":212,"text":"\t\t\t\t\ttarget = binaryExpr.Left"},
  {"line":213,"text":"\t\t\t\t\ttargetFunction = target.Expression()"},
  {"line":214,"text":"\t\t\t\t\tdefinition = binaryExpr.Right"},
  {"line":216,"text":"\t\t\t\t\tif ast.IsPropertyAccessExpression(target) {"},
  {"line":217,"text":"\t\t\t\t\t\tpropertyName = target.AsPropertyAccessExpression().Name()"},
  {"line":218,"text":"\t\t\t\t\t} else { // `A[\"b\"]` or `A.prototype[\"b\"]`"},
  {"line":219,"text":"\t\t\t\t\t\tpropertyName = target.AsElementAccessExpression().ArgumentExpression"},
  {"line":220,"text":"\t\t\t\t\t}"},
  {"line":221,"text":"\t\t\t\t} else { // `Object.defineProperty(A, \"b\", {...})`"},
  {"line":222,"text":"\t\t\t\t\targs := node.Arguments()"},
  {"line":223,"text":"\t\t\t\t\ttargetFunction = args[0]"},
  {"line":224,"text":"\t\t\t\t\ttarget = args[1]"},
  {"line":225,"text":"\t\t\t\t\tpropertyName = target"},
  {"line":226,"text":"\t\t\t\t\tdefinition = args[2]"},
  {"line":227,"text":"\t\t\t\t}"},
  {"line":228,"text":"\t\t\t\tif isPrototypeExpando(targetFunction) {"},
  {"line":229,"text":"\t\t\t\t\ttargetFunction = targetFunction.Expression()"},
  {"line":231,"text":"\t\t\t\t\tif ast.IsIdentifier(targetFunction) {"},
  {"line":232,"text":"\t\t\t\t\t\texpandoTargets.Add(targetFunction.Text())"},
  {"line":233,"text":"\t\t\t\t\t}"},
  {"line":234,"text":"\t\t\t\t}"},
  {"line":235,"text":"\t\t\t\tif ast.IsIdentifier(targetFunction) &&"},
  {"line":236,"text":"\t\t\t\t\texpandoTargets.Has(targetFunction.Text()) {"},
  {"line":237,"text":"\t\t\t\t\tendNode := startNode(node, targetFunction)"},
  {"line":238,"text":"\t\t\t\t\taddSymbolForNode(target, propertyName, getSymbolsForNode(definition))"},
  {"line":239,"text":"\t\t\t\t\tendNode()"},
  {"line":240,"text":"\t\t\t\t} else {"},
  {"line":241,"text":"\t\t\t\t\tnode.ForEachChild(visit)"},
  {"line":242,"text":"\t\t\t\t}"},
  {"line":243,"text":"\t\t\t}"},
  {"line":244,"text":"\t\tcase ast.KindExportAssignment:"},
  {"line":245,"text":"\t\t\tif node.AsExportAssignment().IsExportEquals {"},
  {"line":246,"text":"\t\t\t\taddSymbolForNode(node, nil /*name*/, getSymbolsForNode(node.Expression()))"},
  {"line":247,"text":"\t\t\t} else {"},
  {"line":248,"text":"\t\t\t\tnode.ForEachChild(visit)"},
  {"line":249,"text":"\t\t\t}"},
  {"line":250,"text":"\t\tdefault:"},
  {"line":251,"text":"\t\t\tnode.ForEachChild(visit)"},
  {"line":252,"text":"\t\t}"},
  {"line":253,"text":"\t\treturn false"},
  {"line":254,"text":"\t}"},
  {"line":255,"text":"\tnode.ForEachChild(visit)"},
  {"line":256,"text":"\treturn mergeExpandos(symbols)"},
  {"line":257,"text":"}"},
  {"line":260,"text":"func isPrototypeExpando(target *ast.Node) bool {"},
  {"line":261,"text":"\tif ast.IsAccessExpression(target) {"},
  {"line":262,"text":"\t\taccessName := ast.GetElementOrPropertyAccessName(target)"},
  {"line":263,"text":"\t\treturn accessName != nil && accessName.Text() == \"prototype\""},
  {"line":264,"text":"\t}"},
  {"line":265,"text":"\treturn false"},
  {"line":266,"text":"}"},
  {"line":268,"text":"const maxLength = 150"},
  {"line":270,"text":"func (l *LanguageService) newDocumentSymbol(node *ast.Node, name *ast.Node, children []*lsproto.DocumentSymbol) *lsproto.DocumentSymbol {"},
  {"line":271,"text":"\tresult := new(lsproto.DocumentSymbol)"},
  {"line":272,"text":"\tfile := ast.GetSourceFileOfNode(node)"},
  {"line":273,"text":"\tnodeStartPos := scanner.SkipTrivia(file.Text(), node.Pos())"},
  {"line":274,"text":"\tif name == nil {"},
  {"line":275,"text":"\t\tname = ast.GetNameOfDeclaration(node)"},
  {"line":276,"text":"\t}"},
  {"line":277,"text":"\tvar text string"},
  {"line":278,"text":"\tvar nameStartPos, nameEndPos int"},
  {"line":279,"text":"\tif ast.IsModuleDeclaration(node) && !ast.IsAmbientModule(node) {"},
  {"line":280,"text":"\t\ttext = getModuleName(node)"},
  {"line":281,"text":"\t\tnameStartPos = scanner.SkipTrivia(file.Text(), name.Pos())"},
  {"line":282,"text":"\t\tnameEndPos = getInteriorModule(node).Name().End()"},
  {"line":283,"text":"\t} else if ast.IsAnyExportAssignment(node) && node.AsExportAssignment().IsExportEquals {"},
  {"line":284,"text":"\t\ttext = \"export=\""},
  {"line":285,"text":"\t\tif !ast.NodeIsMissing(name) {"},
  {"line":286,"text":"\t\t\tnameStartPos = scanner.SkipTrivia(file.Text(), name.Pos())"},
  {"line":287,"text":"\t\t\tnameEndPos = name.End()"},
  {"line":288,"text":"\t\t} else {"},
  {"line":289,"text":"\t\t\tnameStartPos = nodeStartPos"},
  {"line":290,"text":"\t\t\tnameEndPos = node.End()"},
  {"line":291,"text":"\t\t}"},
  {"line":292,"text":"\t} else if name != nil {"},
  {"line":293,"text":"\t\ttext = getTextOfName(name)"},
  {"line":294,"text":"\t\tnameStartPos = max(scanner.SkipTrivia(file.Text(), name.Pos()), nodeStartPos)"},
  {"line":295,"text":"\t\tnameEndPos = max(name.End(), nodeStartPos)"},
  {"line":296,"text":"\t} else {"},
  {"line":297,"text":"\t\ttext = getUnnamedNodeLabel(node)"},
  {"line":298,"text":"\t\tnameStartPos = nodeStartPos"},
  {"line":299,"text":"\t\tnameEndPos = nodeStartPos"},
  {"line":300,"text":"\t}"},
  {"line":301,"text":"\tif text == \"\" {"},
  {"line":302,"text":"\t\treturn nil"},
  {"line":303,"text":"\t}"},
  {"line":304,"text":"\ttruncatedText := stringutil.TruncateByRunes(text, maxLength)"},
  {"line":305,"text":"\tif len(truncatedText) < len(text) {"},
  {"line":306,"text":"\t\ttext = truncatedText + \"...\""},
  {"line":307,"text":"\t}"},
  {"line":308,"text":"\tresult.Name = text"},
  {"line":309,"text":"\tresult.Kind = getSymbolKindFromNode(node)"},
  {"line":310,"text":"\tresult.Range = lsproto.Range{"},
  {"line":311,"text":"\t\tStart: l.converters.PositionToLineAndCharacter(file, core.TextPos(nodeStartPos)),"},
  {"line":312,"text":"\t\tEnd:   l.converters.PositionToLineAndCharacter(file, core.TextPos(node.End())),"},
  {"line":313,"text":"\t}"},
  {"line":314,"text":"\tresult.SelectionRange = lsproto.Range{"},
  {"line":315,"text":"\t\tStart: l.converters.PositionToLineAndCharacter(file, core.TextPos(nameStartPos)),"},
  {"line":316,"text":"\t\tEnd:   l.converters.PositionToLineAndCharacter(file, core.TextPos(nameEndPos)),"},
  {"line":317,"text":"\t}"},
  {"line":318,"text":"\tif children == nil {"},
  {"line":319,"text":"\t\tchildren = []*lsproto.DocumentSymbol{}"},
  {"line":320,"text":"\t}"},
  {"line":321,"text":"\tresult.Children = &children"},
  {"line":322,"text":"\treturn result"},
  {"line":323,"text":"}"},
  {"line":327,"text":"func mergeExpandos(symbols []*lsproto.DocumentSymbol) []*lsproto.DocumentSymbol {"},
  {"line":328,"text":"\tmergedSymbols := make([]*lsproto.DocumentSymbol, 0, len(symbols))"},
  {"line":330,"text":"\tnameToExpandoTargetIndex := collections.MultiMap[string, int]{}"},
  {"line":332,"text":"\tnameToNamespaceIndex := map[string]int{}"},
  {"line":333,"text":"\tfor i, symbol := range symbols {"},
  {"line":334,"text":"\t\tif isAnonymousName(symbol.Name) {"},
  {"line":335,"text":"\t\t\tcontinue"},
  {"line":336,"text":"\t\t}"},
  {"line":337,"text":"\t\tif symbol.Kind == lsproto.SymbolKindClass || symbol.Kind == lsproto.SymbolKindFunction || symbol.Kind == lsproto.SymbolKindVariable {"},
  {"line":338,"text":"\t\t\tnameToExpandoTargetIndex.Add(symbol.Name, i)"},
  {"line":339,"text":"\t\t}"},
  {"line":340,"text":"\t\tif symbol.Kind == lsproto.SymbolKindNamespace {"},
  {"line":341,"text":"\t\t\tif _, ok := nameToNamespaceIndex[symbol.Name]; !ok {"},
  {"line":342,"text":"\t\t\t\tnameToNamespaceIndex[symbol.Name] = i"},
  {"line":343,"text":"\t\t\t}"},
  {"line":344,"text":"\t\t}"},
  {"line":345,"text":"\t}"},
  {"line":346,"text":"\tfor i, symbol := range symbols {"},
  {"line":347,"text":"\t\tif symbol.Children != nil {"},
  {"line":348,"text":"\t\t\tchildren := mergeExpandos(*symbol.Children)"},
  {"line":349,"text":"\t\t\tsymbol.Children = &children"},
  {"line":350,"text":"\t\t}"},
  {"line":353,"text":"\t\tif isAnonymousName(symbol.Name) {"},
  {"line":354,"text":"\t\t\tcontinue"},
  {"line":355,"text":"\t\t}"},
  {"line":358,"text":"\t\tif symbol.Kind == lsproto.SymbolKindProperty {"},
  {"line":359,"text":"\t\t\tsymbolsWithSameName := nameToExpandoTargetIndex.Get(symbol.Name)"},
  {"line":360,"text":"\t\t\tfor j := len(symbolsWithSameName) - 1; j >= 0; j-- {"},
  {"line":361,"text":"\t\t\t\ttargetIndex := symbolsWithSameName[j]"},
  {"line":362,"text":"\t\t\t\ttargetSymbol := symbols[targetIndex]"},
  {"line":363,"text":"\t\t\t\tmergeChildren(targetSymbol, symbol)"},
  {"line":365,"text":"\t\t\t\tsymbols[i] = nil"},
  {"line":366,"text":"\t\t\t}"},
  {"line":367,"text":"\t\t}"},
  {"line":369,"text":"\t\tif symbol.Kind == lsproto.SymbolKindNamespace {"},
  {"line":370,"text":"\t\t\tif targetIndex, ok := nameToNamespaceIndex[symbol.Name]; ok && targetIndex != i {"},
  {"line":371,"text":"\t\t\t\ttargetSymbol := symbols[targetIndex]"},
  {"line":372,"text":"\t\t\t\tmergeChildren(targetSymbol, symbol)"},
  {"line":374,"text":"\t\t\t\tsymbols[i] = nil"},
  {"line":375,"text":"\t\t\t}"},
  {"line":376,"text":"\t\t}"},
  {"line":377,"text":"\t}"},
  {"line":378,"text":"\tfor _, symbol := range symbols {"},
  {"line":379,"text":"\t\tif symbol != nil {"},
  {"line":380,"text":"\t\t\tmergedSymbols = append(mergedSymbols, symbol)"},
  {"line":381,"text":"\t\t}"},
  {"line":382,"text":"\t}"},
  {"line":383,"text":"\treturn mergedSymbols"},
  {"line":384,"text":"}"},
  {"line":386,"text":"func mergeChildren(target *lsproto.DocumentSymbol, source *lsproto.DocumentSymbol) {"},
  {"line":387,"text":"\tif source.Children != nil {"},
  {"line":388,"text":"\t\tif target.Children == nil {"},
  {"line":389,"text":"\t\t\ttarget.Children = source.Children"},
  {"line":390,"text":"\t\t} else {"},
  {"line":391,"text":"\t\t\t*target.Children = mergeExpandos(append(*target.Children, *source.Children...))"},
  {"line":392,"text":"\t\t\tslices.SortFunc(*target.Children, func(a, b *lsproto.DocumentSymbol) int {"},
  {"line":393,"text":"\t\t\t\treturn lsproto.CompareRanges(a.Range, b.Range)"},
  {"line":394,"text":"\t\t\t})"},
  {"line":395,"text":"\t\t}"},
  {"line":396,"text":"\t}"},
  {"line":397,"text":"}"},
  {"line":400,"text":"func isAnonymousName(name string) bool {"},
  {"line":401,"text":"\treturn name == \"<function>\" || name == \"<class>\" || name == \"export=\" || name == \"default\" ||"},
  {"line":402,"text":"\t\tname == \"constructor\" || name == \"()\" || name == \"new()\" || name == \"[]\" || strings.HasSuffix(name, \") callback\")"},
  {"line":403,"text":"}"},
  {"line":405,"text":"func getTextOfName(node *ast.Node) string {"},
  {"line":406,"text":"\tswitch node.Kind {"},
  {"line":407,"text":"\tcase ast.KindIdentifier, ast.KindPrivateIdentifier, ast.KindNumericLiteral:"},
  {"line":408,"text":"\t\treturn node.Text()"},
  {"line":409,"text":"\tcase ast.KindStringLiteral:"},
  {"line":410,"text":"\t\treturn \"\\\"\" + printer.EscapeString(node.Text(), '\"') + \"\\\"\""},
  {"line":411,"text":"\tcase ast.KindNoSubstitutionTemplateLiteral:"},
  {"line":412,"text":"\t\treturn \"`\" + printer.EscapeString(node.Text(), '`') + \"`\""},
  {"line":413,"text":"\tcase ast.KindComputedPropertyName:"},
  {"line":414,"text":"\t\tif ast.IsStringOrNumericLiteralLike(node.Expression()) {"},
  {"line":415,"text":"\t\t\treturn getTextOfName(node.Expression())"},
  {"line":416,"text":"\t\t}"},
  {"line":417,"text":"\t}"},
  {"line":418,"text":"\treturn scanner.GetTextOfNode(node)"},
  {"line":419,"text":"}"},
  {"line":421,"text":"func getUnnamedNodeLabel(node *ast.Node) string {"},
  {"line":422,"text":"\tif parent := ast.WalkUpParenthesizedExpressions(node.Parent); parent != nil && ast.IsExportAssignment(parent) {"},
  {"line":423,"text":"\t\tif parent.AsExportAssignment().IsExportEquals {"},
  {"line":424,"text":"\t\t\treturn \"export=\""},
  {"line":425,"text":"\t\t}"},
  {"line":426,"text":"\t\treturn \"default\""},
  {"line":427,"text":"\t}"},
  {"line":428,"text":"\tswitch node.Kind {"},
  {"line":429,"text":"\tcase ast.KindFunctionDeclaration, ast.KindFunctionExpression, ast.KindArrowFunction:"},
  {"line":430,"text":"\t\tif node.ModifierFlags()&ast.ModifierFlagsDefault != 0 {"},
  {"line":431,"text":"\t\t\treturn \"default\""},
  {"line":432,"text":"\t\t}"},
  {"line":433,"text":"\t\tif ast.IsCallExpression(node.Parent) {"},
  {"line":434,"text":"\t\t\tname := getCallExpressionName(node.Parent.Expression())"},
  {"line":435,"text":"\t\t\tif name != \"\" {"},
  {"line":436,"text":"\t\t\t\tname = cleanCallbackText(name)"},
  {"line":437,"text":"\t\t\t\tif len(name) > maxLength {"},
  {"line":438,"text":"\t\t\t\t\treturn name + \" callback\""},
  {"line":439,"text":"\t\t\t\t}"},
  {"line":440,"text":"\t\t\t\targs := cleanCallbackText(getCallExpressionLiteralArgs(node.Parent))"},
  {"line":441,"text":"\t\t\t\treturn name + \"(\" + args + \") callback\""},
  {"line":442,"text":"\t\t\t}"},
  {"line":443,"text":"\t\t}"},
  {"line":444,"text":"\t\treturn \"<function>\""},
  {"line":445,"text":"\tcase ast.KindClassDeclaration, ast.KindClassExpression:"},
  {"line":446,"text":"\t\tif node.ModifierFlags()&ast.ModifierFlagsDefault != 0 {"},
  {"line":447,"text":"\t\t\treturn \"default\""},
  {"line":448,"text":"\t\t}"},
  {"line":449,"text":"\t\treturn \"<class>\""},
  {"line":450,"text":"\tcase ast.KindConstructor:"},
  {"line":451,"text":"\t\treturn \"constructor\""},
  {"line":452,"text":"\tcase ast.KindCallSignature:"},
  {"line":453,"text":"\t\treturn \"()\""},
  {"line":454,"text":"\tcase ast.KindConstructSignature:"},
  {"line":455,"text":"\t\treturn \"new()\""},
  {"line":456,"text":"\tcase ast.KindIndexSignature:"},
  {"line":457,"text":"\t\treturn \"[]\""},
  {"line":458,"text":"\t}"},
  {"line":459,"text":"\treturn \"\""},
  {"line":460,"text":"}"},
  {"line":462,"text":"func getCallExpressionName(node *ast.Node) string {"},
  {"line":463,"text":"\tswitch node.Kind {"},
  {"line":464,"text":"\tcase ast.KindIdentifier, ast.KindPrivateIdentifier:"},
  {"line":465,"text":"\t\treturn node.Text()"},
  {"line":466,"text":"\tcase ast.KindPropertyAccessExpression:"},
  {"line":467,"text":"\t\tleft := getCallExpressionName(node.Expression())"},
  {"line":468,"text":"\t\tright := getCallExpressionName(node.Name())"},
  {"line":469,"text":"\t\tif left != \"\" {"},
  {"line":470,"text":"\t\t\treturn left + \".\" + right"},
  {"line":471,"text":"\t\t}"},
  {"line":472,"text":"\t\treturn right"},
  {"line":473,"text":"\t}"},
  {"line":474,"text":"\treturn \"\""},
  {"line":475,"text":"}"},
  {"line":477,"text":"func getCallExpressionLiteralArgs(callExpr *ast.Node) string {"},
  {"line":478,"text":"\tvar parts []string"},
  {"line":479,"text":"\tfor _, arg := range callExpr.Arguments() {"},
  {"line":480,"text":"\t\tif ast.IsStringLiteralLike(arg) || ast.IsTemplateExpression(arg) {"},
  {"line":481,"text":"\t\t\tparts = append(parts, scanner.GetTextOfNode(arg))"},
  {"line":482,"text":"\t\t}"},
  {"line":483,"text":"\t}"},
  {"line":484,"text":"\treturn strings.Join(parts, \", \")"},
  {"line":485,"text":"}"},
  {"line":487,"text":"func cleanCallbackText(text string) string {"},
  {"line":488,"text":"\ttruncated := stringutil.TruncateByRunes(text, maxLength)"},
  {"line":489,"text":"\tif len(truncated) < len(text) {"},
  {"line":490,"text":"\t\ttext = truncated + \"...\""},
  {"line":491,"text":"\t}"},
  {"line":492,"text":"\treturn strings.Map(func(r rune) rune {"},
  {"line":493,"text":"\t\tif stringutil.IsLineBreak(r) {"},
  {"line":494,"text":"\t\t\treturn -1"},
  {"line":495,"text":"\t\t}"},
  {"line":496,"text":"\t\treturn r"},
  {"line":497,"text":"\t}, text)"},
  {"line":498,"text":"}"},
  {"line":500,"text":"func getInteriorModule(node *ast.Node) *ast.Node {"},
  {"line":501,"text":"\tfor node.Body() != nil && ast.IsModuleDeclaration(node.Body()) {"},
  {"line":502,"text":"\t\tnode = node.Body()"},
  {"line":503,"text":"\t}"},
  {"line":504,"text":"\treturn node"},
  {"line":505,"text":"}"},
  {"line":507,"text":"func getModuleName(node *ast.Node) string {"},
  {"line":508,"text":"\tresult := node.Name().Text()"},
  {"line":509,"text":"\tfor node.Body() != nil && ast.IsModuleDeclaration(node.Body()) {"},
  {"line":510,"text":"\t\tnode = node.Body()"},
  {"line":511,"text":"\t\tresult = result + \".\" + node.Name().Text()"},
  {"line":512,"text":"\t}"},
  {"line":513,"text":"\treturn result"},
  {"line":514,"text":"}"},
  {"line":516,"text":"type DeclarationInfo struct {"},
  {"line":517,"text":"\tname        string"},
  {"line":518,"text":"\tdeclaration *ast.Node"},
  {"line":519,"text":"\tmatchScore  int"},
  {"line":520,"text":"}"},
  {"line":522,"text":"func ProvideWorkspaceSymbols("},
  {"line":523,"text":"\tctx context.Context,"},
  {"line":524,"text":"\tprograms []*compiler.Program,"},
  {"line":525,"text":"\tconverters *lsconv.Converters,"},
  {"line":526,"text":"\tpreferences lsutil.UserPreferences,"},
  {"line":527,"text":"\tquery string,"},
  {"line":528,"text":") (lsproto.WorkspaceSymbolResponse, error) {"},
  {"line":529,"text":"\texcludeLibrarySymbols := preferences.ExcludeLibrarySymbolsInNavTo.IsTrue()"},
  {"line":531,"text":"\tsourceFiles := map[tspath.Path]*ast.SourceFile{}"},
  {"line":532,"text":"\tfor _, program := range programs {"},
  {"line":533,"text":"\t\tfor _, sourceFile := range program.SourceFiles() {"},
  {"line":534,"text":"\t\t\tif (program.HasTSFile() || !sourceFile.IsDeclarationFile) &&"},
  {"line":535,"text":"\t\t\t\t!shouldExcludeFile(sourceFile, program, excludeLibrarySymbols) {"},
  {"line":536,"text":"\t\t\t\tsourceFiles[sourceFile.Path()] = sourceFile"},
  {"line":537,"text":"\t\t\t}"},
  {"line":538,"text":"\t\t}"},
  {"line":539,"text":"\t}"},
  {"line":541,"text":"\tvar infos []DeclarationInfo"},
  {"line":542,"text":"\tfor _, sourceFile := range sourceFiles {"},
  {"line":543,"text":"\t\tif ctx.Err() != nil {"},
  {"line":544,"text":"\t\t\treturn lsproto.SymbolInformationsOrWorkspaceSymbolsOrNull{}, nil"},
  {"line":545,"text":"\t\t}"},
  {"line":546,"text":"\t\tdeclarationMap := sourceFile.GetDeclarationMap()"},
  {"line":547,"text":"\t\tfor name, declarations := range declarationMap {"},
  {"line":548,"text":"\t\t\tscore := getMatchScore(name, query)"},
  {"line":549,"text":"\t\t\tif score >= 0 {"},
  {"line":550,"text":"\t\t\t\tfor _, declaration := range declarations {"},
  {"line":551,"text":"\t\t\t\t\tinfos = append(infos, DeclarationInfo{name, declaration, score})"},
  {"line":552,"text":"\t\t\t\t}"},
  {"line":553,"text":"\t\t\t}"},
  {"line":554,"text":"\t\t}"},
  {"line":555,"text":"\t}"},
  {"line":557,"text":"\tslices.SortFunc(infos, compareDeclarationInfos)"},
  {"line":558,"text":"\tcount := min(len(infos), 256)"},
  {"line":559,"text":"\tsymbols := make([]*lsproto.SymbolInformation, count)"},
  {"line":560,"text":"\tfor i, info := range infos[0:count] {"},
  {"line":561,"text":"\t\tnode := info.declaration"},
  {"line":562,"text":"\t\tsourceFile := ast.GetSourceFileOfNode(node)"},
  {"line":563,"text":"\t\tcontainer := getContainerNode(info.declaration)"},
  {"line":564,"text":"\t\tvar containerName *string"},
  {"line":565,"text":"\t\tif container != nil {"},
  {"line":566,"text":"\t\t\tcontainerName = strPtrTo(ast.GetDeclarationName(container))"},
  {"line":567,"text":"\t\t}"},
  {"line":572,"text":"\t\tnameNode := ast.GetNameOfDeclaration(node)"},
  {"line":573,"text":"\t\tnameStart := astnav.GetStartOfNode(nameNode, sourceFile, false /*includeJsDoc*/)"},
  {"line":574,"text":"\t\tnameRange := core.NewTextRange(nameStart, nameNode.End())"},
  {"line":575,"text":"\t\tvar symbol lsproto.SymbolInformation"},
  {"line":576,"text":"\t\tsymbol.Name = info.name"},
  {"line":577,"text":"\t\tsymbol.Kind = getSymbolKindFromNode(info.declaration)"},
  {"line":578,"text":"\t\tsymbol.Location = converters.ToLSPLocation(sourceFile, nameRange)"},
  {"line":579,"text":"\t\tsymbol.ContainerName = containerName"},
  {"line":580,"text":"\t\tsymbols[i] = &symbol"},
  {"line":581,"text":"\t}"},
  {"line":583,"text":"\treturn lsproto.SymbolInformationsOrWorkspaceSymbolsOrNull{SymbolInformations: &symbols}, nil"},
  {"line":584,"text":"}"},
  {"line":586,"text":"func shouldExcludeFile(file *ast.SourceFile, program *compiler.Program, excludeLibrarySymbols bool) bool {"},
  {"line":587,"text":"\treturn excludeLibrarySymbols && (isInsideNodeModules(file.FileName()) || program.IsLibFile(file))"},
  {"line":588,"text":"}"},
  {"line":590,"text":"func isInsideNodeModules(fileName string) bool {"},
  {"line":591,"text":"\treturn strings.Contains(fileName, \"/node_modules/\")"},
  {"line":592,"text":"}"},
  {"line":599,"text":"func getMatchScore(s string, pattern string) int {"},
  {"line":600,"text":"\tscore := 0"},
  {"line":601,"text":"\tfor _, p := range pattern {"},
  {"line":602,"text":"\t\texact := unicode.IsUpper(p)"},
  {"line":603,"text":"\t\tfor {"},
  {"line":604,"text":"\t\t\tc, size := utf8.DecodeRuneInString(s)"},
  {"line":605,"text":"\t\t\tif size == 0 {"},
  {"line":606,"text":"\t\t\t\treturn -1"},
  {"line":607,"text":"\t\t\t}"},
  {"line":608,"text":"\t\t\ts = s[size:]"},
  {"line":609,"text":"\t\t\tif exact && c == p || !exact && unicode.ToLower(c) == unicode.ToLower(p) {"},
  {"line":610,"text":"\t\t\t\tbreak"},
  {"line":611,"text":"\t\t\t}"},
  {"line":612,"text":"\t\t\tscore++"},
  {"line":613,"text":"\t\t}"},
  {"line":614,"text":"\t}"},
  {"line":615,"text":"\treturn score"},
  {"line":616,"text":"}"},
  {"line":620,"text":"func compareDeclarationInfos(d1, d2 DeclarationInfo) int {"},
  {"line":621,"text":"\tif d1.matchScore != d2.matchScore {"},
  {"line":622,"text":"\t\treturn d1.matchScore - d2.matchScore"},
  {"line":623,"text":"\t}"},
  {"line":624,"text":"\tif c := stringutil.CompareStringsCaseInsensitive(d1.name, d2.name); c != 0 {"},
  {"line":625,"text":"\t\treturn c"},
  {"line":626,"text":"\t}"},
  {"line":627,"text":"\tif c := strings.Compare(d1.name, d2.name); c != 0 {"},
  {"line":628,"text":"\t\treturn c"},
  {"line":629,"text":"\t}"},
  {"line":630,"text":"\ts1 := ast.GetSourceFileOfNode(d1.declaration)"},
  {"line":631,"text":"\ts2 := ast.GetSourceFileOfNode(d2.declaration)"},
  {"line":632,"text":"\tif s1 != s2 {"},
  {"line":633,"text":"\t\treturn strings.Compare(string(s1.Path()), string(s2.Path()))"},
  {"line":634,"text":"\t}"},
  {"line":635,"text":"\treturn d1.declaration.Pos() - d2.declaration.Pos()"},
  {"line":636,"text":"}"},
  {"line":640,"text":"func getSymbolKindFromNode(node *ast.Node) lsproto.SymbolKind {"},
  {"line":641,"text":"\tswitch node.Kind {"},
  {"line":642,"text":"\tcase ast.KindSourceFile:"},
  {"line":643,"text":"\t\tif ast.IsExternalModule(node.AsSourceFile()) {"},
  {"line":644,"text":"\t\t\treturn lsproto.SymbolKindModule"},
  {"line":645,"text":"\t\t}"},
  {"line":646,"text":"\t\treturn lsproto.SymbolKindFile"},
  {"line":647,"text":"\tcase ast.KindModuleDeclaration:"},
  {"line":648,"text":"\t\treturn lsproto.SymbolKindNamespace"},
  {"line":649,"text":"\tcase ast.KindClassDeclaration, ast.KindClassExpression:"},
  {"line":650,"text":"\t\treturn lsproto.SymbolKindClass"},
  {"line":651,"text":"\tcase ast.KindInterfaceDeclaration:"},
  {"line":652,"text":"\t\treturn lsproto.SymbolKindInterface"},
  {"line":653,"text":"\tcase ast.KindTypeAliasDeclaration, ast.KindJSDocTypedefTag, ast.KindJSDocCallbackTag:"},
  {"line":654,"text":"\t\treturn lsproto.SymbolKindClass"},
  {"line":655,"text":"\tcase ast.KindEnumDeclaration:"},
  {"line":656,"text":"\t\treturn lsproto.SymbolKindEnum"},
  {"line":657,"text":"\tcase ast.KindVariableDeclaration:"},
  {"line":658,"text":"\t\treturn lsproto.SymbolKindVariable"},
  {"line":659,"text":"\tcase ast.KindArrowFunction, ast.KindFunctionDeclaration, ast.KindFunctionExpression:"},
  {"line":660,"text":"\t\treturn lsproto.SymbolKindFunction"},
  {"line":661,"text":"\tcase ast.KindGetAccessor, ast.KindSetAccessor:"},
  {"line":662,"text":"\t\treturn lsproto.SymbolKindProperty"},
  {"line":663,"text":"\tcase ast.KindMethodDeclaration, ast.KindMethodSignature:"},
  {"line":664,"text":"\t\treturn lsproto.SymbolKindMethod"},
  {"line":665,"text":"\tcase ast.KindPropertyDeclaration, ast.KindPropertySignature, ast.KindPropertyAssignment,"},
  {"line":666,"text":"\t\tast.KindShorthandPropertyAssignment, ast.KindSpreadAssignment, ast.KindIndexSignature:"},
  {"line":667,"text":"\t\treturn lsproto.SymbolKindProperty"},
  {"line":668,"text":"\tcase ast.KindCallSignature:"},
  {"line":669,"text":"\t\treturn lsproto.SymbolKindMethod"},
  {"line":670,"text":"\tcase ast.KindConstructSignature:"},
  {"line":671,"text":"\t\treturn lsproto.SymbolKindConstructor"},
  {"line":672,"text":"\tcase ast.KindConstructor, ast.KindClassStaticBlockDeclaration:"},
  {"line":673,"text":"\t\treturn lsproto.SymbolKindConstructor"},
  {"line":674,"text":"\tcase ast.KindTypeParameter:"},
  {"line":675,"text":"\t\treturn lsproto.SymbolKindTypeParameter"},
  {"line":676,"text":"\tcase ast.KindEnumMember:"},
  {"line":677,"text":"\t\treturn lsproto.SymbolKindEnumMember"},
  {"line":678,"text":"\tcase ast.KindParameter:"},
  {"line":679,"text":"\t\tif ast.HasSyntacticModifier(node, ast.ModifierFlagsParameterPropertyModifier) {"},
  {"line":680,"text":"\t\t\treturn lsproto.SymbolKindProperty"},
  {"line":681,"text":"\t\t}"},
  {"line":682,"text":"\t\treturn lsproto.SymbolKindVariable"},
  {"line":683,"text":"\tcase ast.KindBinaryExpression, ast.KindCallExpression:"},
  {"line":684,"text":"\t\tkind := ast.GetAssignmentDeclarationKind(node)"},
  {"line":685,"text":"\t\tswitch kind {"},
  {"line":686,"text":"\t\tcase ast.JSDeclarationKindThisProperty, ast.JSDeclarationKindProperty, ast.JSDeclarationKindObjectDefinePropertyValue:"},
  {"line":687,"text":"\t\t\treturn lsproto.SymbolKindProperty"},
  {"line":688,"text":"\t\t}"},
  {"line":689,"text":"\tcase ast.KindStringLiteral, ast.KindNoSubstitutionTemplateLiteral, ast.KindNumericLiteral:"},
  {"line":691,"text":"\t\treturn lsproto.SymbolKindProperty"},
  {"line":692,"text":"\t}"},
  {"line":693,"text":"\treturn lsproto.SymbolKindVariable"},
  {"line":694,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsSymbolsSourceLines.find((entry) => entry.line === line)?.text;
}
