/**
 * Language-service parity map for TS-Go `ls/utilities.go`.
 *
 * This file preserves the upstream declaration and algorithm-line shape
 * for the TypeScript port. Runtime behavior is implemented by the
 * concrete modules that consume these exact parity maps.
 */

export interface UpstreamSourceLine {
  readonly line: number;
  readonly text: string;
}

export interface UpstreamDeclaration {
  readonly kind: "type" | "func" | "const" | "var";
  readonly line: number;
  readonly name: string;
  readonly receiver?: string;
}

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesUpstreamPath = "ls/utilities.go";

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesDeclarations: readonly UpstreamDeclaration[] = [
  {"line":25,"kind":"var","name":"quoteReplacer"},
  {"line":27,"kind":"func","name":"IsInString"},
  {"line":47,"kind":"func","name":"isModuleSpecifierLike"},
  {"line":61,"kind":"func","name":"getNonModuleSymbolOfMergedModuleSymbol"},
  {"line":72,"kind":"func","name":"getLocalSymbolForExportSpecifier"},
  {"line":81,"kind":"func","name":"isExportSpecifierAlias"},
  {"line":94,"kind":"func","name":"isInComment"},
  {"line":98,"kind":"func","name":"positionBelongsToNode"},
  {"line":102,"kind":"type","name":"PossibleTypeArgumentInfo"},
  {"line":108,"kind":"func","name":"getPossibleTypeArgumentsInfo"},
  {"line":190,"kind":"func","name":"isNameOfModuleDeclaration"},
  {"line":197,"kind":"func","name":"isExpressionOfExternalModuleImportEqualsDeclaration"},
  {"line":201,"kind":"func","name":"isNamespaceReference"},
  {"line":205,"kind":"func","name":"isQualifiedNameNamespaceReference"},
  {"line":219,"kind":"func","name":"isPropertyAccessNamespaceReference"},
  {"line":239,"kind":"func","name":"isThis"},
  {"line":252,"kind":"func","name":"isTypeReference"},
  {"line":276,"kind":"func","name":"isInRightSideOfInternalImportEqualsDeclaration"},
  {"line":287,"kind":"func","name":"createLspRangeFromNode","receiver":"l *LanguageService"},
  {"line":291,"kind":"func","name":"createRangeFromNode"},
  {"line":295,"kind":"func","name":"createLspRangeFromBounds","receiver":"l *LanguageService"},
  {"line":299,"kind":"func","name":"createLspRangeFromRange","receiver":"l *LanguageService"},
  {"line":303,"kind":"func","name":"createLspPosition","receiver":"l *LanguageService"},
  {"line":307,"kind":"func","name":"quote"},
  {"line":317,"kind":"var","name":"typeKeywords"},
  {"line":340,"kind":"func","name":"isTypeKeyword"},
  {"line":344,"kind":"func","name":"isSeparator"},
  {"line":348,"kind":"func","name":"isLiteralNameOfPropertyDeclarationOrIndexAccess"},
  {"line":372,"kind":"func","name":"isObjectBindingElementWithoutPropertyName"},
  {"line":379,"kind":"func","name":"isRightSideOfPropertyAccess"},
  {"line":383,"kind":"func","name":"isStaticSymbol"},
  {"line":391,"kind":"func","name":"isImplementation"},
  {"line":404,"kind":"func","name":"isImplementationExpression"},
  {"line":415,"kind":"func","name":"isReadonlyTypeOperator"},
  {"line":419,"kind":"func","name":"isJumpStatementTarget"},
  {"line":423,"kind":"func","name":"isLabelOfLabeledStatement"},
  {"line":427,"kind":"func","name":"findReferenceInPosition"},
  {"line":431,"kind":"func","name":"getContainingNodeIfInHeritageClause"},
  {"line":441,"kind":"func","name":"getContainerNode"},
  {"line":452,"kind":"func","name":"getAdjustedLocation"},
  {"line":689,"kind":"func","name":"getAdjustedLocationForDeclaration"},
  {"line":713,"kind":"func","name":"getAdjustedLocationForImportDeclaration"},
  {"line":756,"kind":"func","name":"getAdjustedLocationForExportDeclaration"},
  {"line":784,"kind":"func","name":"symbolFlagsHaveMeaning"},
  {"line":800,"kind":"func","name":"getMeaningFromLocation"},
  {"line":839,"kind":"func","name":"getMeaningFromDeclaration"},
  {"line":874,"kind":"func","name":"getIntersectingMeaningFromDeclarations"},
  {"line":915,"kind":"func","name":"getAllSuperTypeNodes"},
  {"line":928,"kind":"func","name":"getParentSymbolsOfPropertyAccess"},
  {"line":956,"kind":"func","name":"getPropertySymbolsFromBaseTypes"},
  {"line":989,"kind":"func","name":"getPropertySymbolFromBindingElement"},
  {"line":996,"kind":"func","name":"getPropertySymbolOfObjectBindingPatternWithoutPropertyName"},
  {"line":1004,"kind":"func","name":"getTargetLabel"},
  {"line":1015,"kind":"func","name":"skipConstraint"},
  {"line":1025,"kind":"type","name":"caseClauseTrackerState"},
  {"line":1032,"kind":"type","name":"trackerAddValue"},
  {"line":1035,"kind":"type","name":"trackerHasValue"},
  {"line":1037,"kind":"type","name":"caseClauseTracker"},
  {"line":1042,"kind":"func","name":"addValue","receiver":"c *caseClauseTrackerState"},
  {"line":1053,"kind":"func","name":"hasValue","receiver":"c *caseClauseTrackerState"},
  {"line":1066,"kind":"func","name":"newCaseClauseTracker"},
  {"line":1098,"kind":"func","name":"RangeContainsRange"},
  {"line":1102,"kind":"func","name":"startEndContainsRange"},
  {"line":1106,"kind":"func","name":"getPossibleGenericSignatures"},
  {"line":1122,"kind":"func","name":"removeOptionality"},
  {"line":1131,"kind":"func","name":"isNoSubstitutionTemplateLiteral"},
  {"line":1135,"kind":"func","name":"isTaggedTemplateExpression"},
  {"line":1139,"kind":"func","name":"isInsideTemplateLiteral"},
  {"line":1144,"kind":"func","name":"isTemplateHead"},
  {"line":1148,"kind":"func","name":"isTemplateTail"},
  {"line":1152,"kind":"func","name":"findPrecedingMatchingToken"},
  {"line":1188,"kind":"func","name":"findContainingList"},
  {"line":1205,"kind":"func","name":"getLeadingCommentRangesOfNode"},
  {"line":1213,"kind":"func","name":"getChildrenFromNonJSDocNode"},
  {"line":1254,"kind":"func","name":"getContainingObjectLiteralElement"},
  {"line":1262,"kind":"func","name":"getContainingObjectLiteralElementWorker"},
  {"line":1280,"kind":"func","name":"isObjectLiteralOrJsxElement"},
  {"line":1285,"kind":"func","name":"nodeSeenTracker"},
  {"line":1293,"kind":"func","name":"toContextRange"},
  {"line":1305,"kind":"func","name":"getReferenceAtPosition"},
  {"line":1355,"kind":"func","name":"getContextualTypeFromParent"},
  {"line":1373,"kind":"func","name":"getContextualTypeFromParentOrAncestorTypeNode"},
  {"line":1390,"kind":"func","name":"getAncestorTypeNode"},
  {"line":1401,"kind":"func","name":"isSourceFileWithGlobalExports"},
];

export const homeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesSourceLines: readonly UpstreamSourceLine[] = [
  {"line":1,"text":"package ls"},
  {"line":3,"text":"import ("},
  {"line":4,"text":"\t\"fmt\""},
  {"line":5,"text":"\t\"iter\""},
  {"line":6,"text":"\t\"slices\""},
  {"line":7,"text":"\t\"strings\""},
  {"line":9,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"line":10,"text":"\t\"github.com/microsoft/typescript-go/internal/astnav\""},
  {"line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/checker\""},
  {"line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/debug\""},
  {"line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/jsnum\""},
  {"line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsconv\""},
  {"line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/ls/lsutil\""},
  {"line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/lsp/lsproto\""},
  {"line":20,"text":"\t\"github.com/microsoft/typescript-go/internal/scanner\""},
  {"line":21,"text":"\t\"github.com/microsoft/typescript-go/internal/stringutil\""},
  {"line":22,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"line":23,"text":")"},
  {"line":25,"text":"var quoteReplacer = strings.NewReplacer(\"'\", `\\'`, `\\\"`, `\"`)"},
  {"line":27,"text":"func IsInString(sourceFile *ast.SourceFile, position int, previousToken *ast.Node) bool {"},
  {"line":28,"text":"\tif previousToken != nil && ast.IsStringTextContainingNode(previousToken) {"},
  {"line":29,"text":"\t\tstart := astnav.GetStartOfNode(previousToken, sourceFile, false /*includeJSDoc*/)"},
  {"line":30,"text":"\t\tend := previousToken.End()"},
  {"line":36,"text":"\t\tif start < position && position < end {"},
  {"line":37,"text":"\t\t\treturn true"},
  {"line":38,"text":"\t\t}"},
  {"line":40,"text":"\t\tif position == end {"},
  {"line":41,"text":"\t\t\treturn ast.IsUnterminatedLiteral(previousToken)"},
  {"line":42,"text":"\t\t}"},
  {"line":43,"text":"\t}"},
  {"line":44,"text":"\treturn false"},
  {"line":45,"text":"}"},
  {"line":47,"text":"func isModuleSpecifierLike(node *ast.Node) bool {"},
  {"line":48,"text":"\tif !ast.IsStringLiteralLike(node) {"},
  {"line":49,"text":"\t\treturn false"},
  {"line":50,"text":"\t}"},
  {"line":52,"text":"\tif ast.IsRequireCall(node.Parent, false /*requireStringLiteralLikeArgument*/) || ast.IsImportCall(node.Parent) {"},
  {"line":53,"text":"\t\treturn node.Parent.Arguments()[0] == node"},
  {"line":54,"text":"\t}"},
  {"line":56,"text":"\treturn node.Parent.Kind == ast.KindExternalModuleReference ||"},
  {"line":57,"text":"\t\tnode.Parent.Kind == ast.KindImportDeclaration ||"},
  {"line":58,"text":"\t\tnode.Parent.Kind == ast.KindJSImportDeclaration"},
  {"line":59,"text":"}"},
  {"line":61,"text":"func getNonModuleSymbolOfMergedModuleSymbol(symbol *ast.Symbol) *ast.Symbol {"},
  {"line":62,"text":"\tif len(symbol.Declarations) == 0 || (symbol.Flags&(ast.SymbolFlagsModule|ast.SymbolFlagsTransient)) == 0 {"},
  {"line":63,"text":"\t\treturn nil"},
  {"line":64,"text":"\t}"},
  {"line":66,"text":"\tif decl := core.Find(symbol.Declarations, func(d *ast.Node) bool { return !ast.IsSourceFile(d) && !ast.IsModuleDeclaration(d) }); decl != nil {"},
  {"line":67,"text":"\t\treturn decl.Symbol()"},
  {"line":68,"text":"\t}"},
  {"line":69,"text":"\treturn nil"},
  {"line":70,"text":"}"},
  {"line":72,"text":"func getLocalSymbolForExportSpecifier(referenceLocation *ast.Node, referenceSymbol *ast.Symbol, exportSpecifier *ast.ExportSpecifier, ch *checker.Checker) *ast.Symbol {"},
  {"line":73,"text":"\tif isExportSpecifierAlias(referenceLocation, exportSpecifier) {"},
  {"line":74,"text":"\t\tif symbol := ch.GetExportSpecifierLocalTargetSymbol(exportSpecifier.AsNode()); symbol != nil {"},
  {"line":75,"text":"\t\t\treturn symbol"},
  {"line":76,"text":"\t\t}"},
  {"line":77,"text":"\t}"},
  {"line":78,"text":"\treturn referenceSymbol"},
  {"line":79,"text":"}"},
  {"line":81,"text":"func isExportSpecifierAlias(referenceLocation *ast.Node, exportSpecifier *ast.ExportSpecifier) bool {"},
  {"line":82,"text":"\tdebug.Assert(exportSpecifier.PropertyName == referenceLocation || exportSpecifier.Name() == referenceLocation, \"referenceLocation is not export specifier name or property name\")"},
  {"line":83,"text":"\tpropertyName := exportSpecifier.PropertyName"},
  {"line":84,"text":"\tif propertyName != nil {"},
  {"line":86,"text":"\t\treturn propertyName == referenceLocation"},
  {"line":87,"text":"\t} else {"},
  {"line":90,"text":"\t\treturn exportSpecifier.Parent.Parent.ModuleSpecifier() == nil"},
  {"line":91,"text":"\t}"},
  {"line":92,"text":"}"},
  {"line":94,"text":"func isInComment(file *ast.SourceFile, position int, tokenAtPosition *ast.Node) *ast.CommentRange {"},
  {"line":95,"text":"\treturn getRangeOfEnclosingComment(file, position, astnav.FindPrecedingToken(file, position), tokenAtPosition)"},
  {"line":96,"text":"}"},
  {"line":98,"text":"func positionBelongsToNode(candidate *ast.Node, position int, file *ast.SourceFile) bool {"},
  {"line":99,"text":"\treturn lsutil.PositionBelongsToNode(candidate, position, file)"},
  {"line":100,"text":"}"},
  {"line":102,"text":"type PossibleTypeArgumentInfo struct {"},
  {"line":103,"text":"\tcalled         *ast.IdentifierNode"},
  {"line":104,"text":"\tnTypeArguments int"},
  {"line":105,"text":"}"},
  {"line":108,"text":"func getPossibleTypeArgumentsInfo(tokenIn *ast.Node, sourceFile *ast.SourceFile) *PossibleTypeArgumentInfo {"},
  {"line":111,"text":"\tif strings.LastIndexByte(sourceFile.Text(), '<') == -1 {"},
  {"line":112,"text":"\t\treturn nil"},
  {"line":113,"text":"\t}"},
  {"line":115,"text":"\ttoken := tokenIn"},
  {"line":122,"text":"\tremainingLessThanTokens := 0"},
  {"line":123,"text":"\tnTypeArguments := 0"},
  {"line":124,"text":"\tfor token != nil {"},
  {"line":125,"text":"\t\tswitch token.Kind {"},
  {"line":126,"text":"\t\tcase ast.KindLessThanToken:"},
  {"line":128,"text":"\t\t\ttoken = astnav.FindPrecedingToken(sourceFile, token.Pos())"},
  {"line":129,"text":"\t\t\tif token != nil && token.Kind == ast.KindQuestionDotToken {"},
  {"line":130,"text":"\t\t\t\ttoken = astnav.FindPrecedingToken(sourceFile, token.Pos())"},
  {"line":131,"text":"\t\t\t}"},
  {"line":132,"text":"\t\t\tif token == nil || !ast.IsIdentifier(token) {"},
  {"line":133,"text":"\t\t\t\treturn nil"},
  {"line":134,"text":"\t\t\t}"},
  {"line":135,"text":"\t\t\tif remainingLessThanTokens == 0 {"},
  {"line":136,"text":"\t\t\t\tif ast.IsDeclarationName(token) {"},
  {"line":137,"text":"\t\t\t\t\treturn nil"},
  {"line":138,"text":"\t\t\t\t}"},
  {"line":139,"text":"\t\t\t\treturn &PossibleTypeArgumentInfo{"},
  {"line":140,"text":"\t\t\t\t\tcalled:         token,"},
  {"line":141,"text":"\t\t\t\t\tnTypeArguments: nTypeArguments,"},
  {"line":142,"text":"\t\t\t\t}"},
  {"line":143,"text":"\t\t\t}"},
  {"line":144,"text":"\t\t\tremainingLessThanTokens--"},
  {"line":145,"text":"\t\tcase ast.KindGreaterThanGreaterThanGreaterThanToken:"},
  {"line":146,"text":"\t\t\tremainingLessThanTokens += 3"},
  {"line":147,"text":"\t\tcase ast.KindGreaterThanGreaterThanToken:"},
  {"line":148,"text":"\t\t\tremainingLessThanTokens += 2"},
  {"line":149,"text":"\t\tcase ast.KindGreaterThanToken:"},
  {"line":150,"text":"\t\t\tremainingLessThanTokens++"},
  {"line":151,"text":"\t\tcase ast.KindCloseBraceToken:"},
  {"line":154,"text":"\t\t\ttoken = findPrecedingMatchingToken(token, ast.KindOpenBraceToken, sourceFile)"},
  {"line":155,"text":"\t\t\tif token == nil {"},
  {"line":156,"text":"\t\t\t\treturn nil"},
  {"line":157,"text":"\t\t\t}"},
  {"line":158,"text":"\t\tcase ast.KindCloseParenToken:"},
  {"line":161,"text":"\t\t\ttoken = findPrecedingMatchingToken(token, ast.KindOpenParenToken, sourceFile)"},
  {"line":162,"text":"\t\t\tif token == nil {"},
  {"line":163,"text":"\t\t\t\treturn nil"},
  {"line":164,"text":"\t\t\t}"},
  {"line":165,"text":"\t\tcase ast.KindCloseBracketToken:"},
  {"line":168,"text":"\t\t\ttoken = findPrecedingMatchingToken(token, ast.KindOpenBracketToken, sourceFile)"},
  {"line":169,"text":"\t\t\tif token == nil {"},
  {"line":170,"text":"\t\t\t\treturn nil"},
  {"line":171,"text":"\t\t\t}"},
  {"line":172,"text":"\t\tcase ast.KindCommaToken:"},
  {"line":174,"text":"\t\t\tnTypeArguments++"},
  {"line":175,"text":"\t\tcase ast.KindEqualsGreaterThanToken, ast.KindIdentifier, ast.KindStringLiteral, ast.KindNumericLiteral,"},
  {"line":176,"text":"\t\t\tast.KindBigIntLiteral, ast.KindTrueKeyword, ast.KindFalseKeyword, ast.KindTypeOfKeyword, ast.KindExtendsKeyword,"},
  {"line":177,"text":"\t\t\tast.KindKeyOfKeyword, ast.KindDotToken, ast.KindBarToken, ast.KindQuestionToken, ast.KindColonToken:"},
  {"line":179,"text":"\t\tdefault:"},
  {"line":180,"text":"\t\t\tif !ast.IsTypeNode(token) {"},
  {"line":182,"text":"\t\t\t\treturn nil"},
  {"line":183,"text":"\t\t\t}"},
  {"line":184,"text":"\t\t}"},
  {"line":185,"text":"\t\ttoken = astnav.FindPrecedingToken(sourceFile, token.Pos())"},
  {"line":186,"text":"\t}"},
  {"line":187,"text":"\treturn nil"},
  {"line":188,"text":"}"},
  {"line":190,"text":"func isNameOfModuleDeclaration(node *ast.Node) bool {"},
  {"line":191,"text":"\tif node.Parent.Kind != ast.KindModuleDeclaration {"},
  {"line":192,"text":"\t\treturn false"},
  {"line":193,"text":"\t}"},
  {"line":194,"text":"\treturn node.Parent.Name() == node"},
  {"line":195,"text":"}"},
  {"line":197,"text":"func isExpressionOfExternalModuleImportEqualsDeclaration(node *ast.Node) bool {"},
  {"line":198,"text":"\treturn ast.IsExternalModuleImportEqualsDeclaration(node.Parent.Parent) && ast.GetExternalModuleImportEqualsDeclarationExpression(node.Parent.Parent) == node"},
  {"line":199,"text":"}"},
  {"line":201,"text":"func isNamespaceReference(node *ast.Node) bool {"},
  {"line":202,"text":"\treturn isQualifiedNameNamespaceReference(node) || isPropertyAccessNamespaceReference(node)"},
  {"line":203,"text":"}"},
  {"line":205,"text":"func isQualifiedNameNamespaceReference(node *ast.Node) bool {"},
  {"line":206,"text":"\troot := node"},
  {"line":207,"text":"\tisLastClause := true"},
  {"line":208,"text":"\tif root.Parent.Kind == ast.KindQualifiedName {"},
  {"line":209,"text":"\t\tfor root.Parent != nil && root.Parent.Kind == ast.KindQualifiedName {"},
  {"line":210,"text":"\t\t\troot = root.Parent"},
  {"line":211,"text":"\t\t}"},
  {"line":213,"text":"\t\tisLastClause = root.AsQualifiedName().Right == node"},
  {"line":214,"text":"\t}"},
  {"line":216,"text":"\treturn root.Parent.Kind == ast.KindTypeReference && !isLastClause"},
  {"line":217,"text":"}"},
  {"line":219,"text":"func isPropertyAccessNamespaceReference(node *ast.Node) bool {"},
  {"line":220,"text":"\troot := node"},
  {"line":221,"text":"\tisLastClause := true"},
  {"line":222,"text":"\tif root.Parent.Kind == ast.KindPropertyAccessExpression {"},
  {"line":223,"text":"\t\tfor root.Parent != nil && root.Parent.Kind == ast.KindPropertyAccessExpression {"},
  {"line":224,"text":"\t\t\troot = root.Parent"},
  {"line":225,"text":"\t\t}"},
  {"line":227,"text":"\t\tisLastClause = root.Name() == node"},
  {"line":228,"text":"\t}"},
  {"line":230,"text":"\tif !isLastClause && root.Parent.Kind == ast.KindExpressionWithTypeArguments && root.Parent.Parent.Kind == ast.KindHeritageClause {"},
  {"line":231,"text":"\t\tdecl := root.Parent.Parent.Parent"},
  {"line":232,"text":"\t\treturn (decl.Kind == ast.KindClassDeclaration && root.Parent.Parent.AsHeritageClause().Token == ast.KindImplementsKeyword) ||"},
  {"line":233,"text":"\t\t\t(decl.Kind == ast.KindInterfaceDeclaration && root.Parent.Parent.AsHeritageClause().Token == ast.KindExtendsKeyword)"},
  {"line":234,"text":"\t}"},
  {"line":236,"text":"\treturn false"},
  {"line":237,"text":"}"},
  {"line":239,"text":"func isThis(node *ast.Node) bool {"},
  {"line":240,"text":"\tswitch node.Kind {"},
  {"line":241,"text":"\tcase ast.KindThisKeyword:"},
  {"line":243,"text":"\t\treturn true"},
  {"line":244,"text":"\tcase ast.KindIdentifier:"},
  {"line":246,"text":"\t\treturn node.Text() == \"this\" && node.Parent.Kind == ast.KindParameter"},
  {"line":247,"text":"\tdefault:"},
  {"line":248,"text":"\t\treturn false"},
  {"line":249,"text":"\t}"},
  {"line":250,"text":"}"},
  {"line":252,"text":"func isTypeReference(node *ast.Node) bool {"},
  {"line":253,"text":"\tif ast.IsRightSideOfQualifiedNameOrPropertyAccess(node) {"},
  {"line":254,"text":"\t\tnode = node.Parent"},
  {"line":255,"text":"\t}"},
  {"line":257,"text":"\tswitch node.Kind {"},
  {"line":258,"text":"\tcase ast.KindThisKeyword:"},
  {"line":259,"text":"\t\treturn !ast.IsExpressionNode(node)"},
  {"line":260,"text":"\tcase ast.KindThisType:"},
  {"line":261,"text":"\t\treturn true"},
  {"line":262,"text":"\t}"},
  {"line":264,"text":"\tswitch node.Parent.Kind {"},
  {"line":265,"text":"\tcase ast.KindTypeReference:"},
  {"line":266,"text":"\t\treturn true"},
  {"line":267,"text":"\tcase ast.KindImportType:"},
  {"line":268,"text":"\t\treturn !node.Parent.AsImportTypeNode().IsTypeOf"},
  {"line":269,"text":"\tcase ast.KindExpressionWithTypeArguments:"},
  {"line":270,"text":"\t\treturn ast.IsPartOfTypeNode(node.Parent)"},
  {"line":271,"text":"\t}"},
  {"line":273,"text":"\treturn false"},
  {"line":274,"text":"}"},
  {"line":276,"text":"func isInRightSideOfInternalImportEqualsDeclaration(node *ast.Node) bool {"},
  {"line":277,"text":"\tif node.Parent == nil {"},
  {"line":278,"text":"\t\treturn false"},
  {"line":279,"text":"\t}"},
  {"line":280,"text":"\tfor node.Parent.Kind == ast.KindQualifiedName {"},
  {"line":281,"text":"\t\tnode = node.Parent"},
  {"line":282,"text":"\t}"},
  {"line":284,"text":"\treturn ast.IsInternalModuleImportEqualsDeclaration(node.Parent) && node.Parent.AsImportEqualsDeclaration().ModuleReference == node"},
  {"line":285,"text":"}"},
  {"line":287,"text":"func (l *LanguageService) createLspRangeFromNode(node *ast.Node, file *ast.SourceFile) lsproto.Range {"},
  {"line":288,"text":"\treturn l.createLspRangeFromBounds(scanner.GetTokenPosOfNode(node, file, false /*includeJSDoc*/), node.End(), file)"},
  {"line":289,"text":"}"},
  {"line":291,"text":"func createRangeFromNode(node *ast.Node, file *ast.SourceFile) core.TextRange {"},
  {"line":292,"text":"\treturn core.NewTextRange(scanner.GetTokenPosOfNode(node, file, false /*includeJSDoc*/), node.End())"},
  {"line":293,"text":"}"},
  {"line":295,"text":"func (l *LanguageService) createLspRangeFromBounds(start, end int, file *ast.SourceFile) lsproto.Range {"},
  {"line":296,"text":"\treturn l.converters.ToLSPRange(file, core.NewTextRange(start, end))"},
  {"line":297,"text":"}"},
  {"line":299,"text":"func (l *LanguageService) createLspRangeFromRange(textRange core.TextRange, script lsconv.Script) lsproto.Range {"},
  {"line":300,"text":"\treturn l.converters.ToLSPRange(script, textRange)"},
  {"line":301,"text":"}"},
  {"line":303,"text":"func (l *LanguageService) createLspPosition(position int, file *ast.SourceFile) lsproto.Position {"},
  {"line":304,"text":"\treturn l.converters.PositionToLineAndCharacter(file, core.TextPos(position))"},
  {"line":305,"text":"}"},
  {"line":307,"text":"func quote(file *ast.SourceFile, preferences lsutil.UserPreferences, text string) string {"},
  {"line":309,"text":"\tquotePreference := lsutil.GetQuotePreference(file, preferences)"},
  {"line":310,"text":"\tquoted, _ := core.StringifyJson(text, \"\" /*prefix*/, \"\" /*indent*/)"},
  {"line":311,"text":"\tif quotePreference == lsutil.QuotePreferenceSingle {"},
  {"line":312,"text":"\t\tquoted = quoteReplacer.Replace(stringutil.StripQuotes(quoted))"},
  {"line":313,"text":"\t}"},
  {"line":314,"text":"\treturn quoted"},
  {"line":315,"text":"}"},
  {"line":317,"text":"var typeKeywords *collections.Set[ast.Kind] = collections.NewSetFromItems("},
  {"line":318,"text":"\tast.KindAnyKeyword,"},
  {"line":319,"text":"\tast.KindAssertsKeyword,"},
  {"line":320,"text":"\tast.KindBigIntKeyword,"},
  {"line":321,"text":"\tast.KindBooleanKeyword,"},
  {"line":322,"text":"\tast.KindFalseKeyword,"},
  {"line":323,"text":"\tast.KindInferKeyword,"},
  {"line":324,"text":"\tast.KindKeyOfKeyword,"},
  {"line":325,"text":"\tast.KindNeverKeyword,"},
  {"line":326,"text":"\tast.KindNullKeyword,"},
  {"line":327,"text":"\tast.KindNumberKeyword,"},
  {"line":328,"text":"\tast.KindObjectKeyword,"},
  {"line":329,"text":"\tast.KindReadonlyKeyword,"},
  {"line":330,"text":"\tast.KindStringKeyword,"},
  {"line":331,"text":"\tast.KindSymbolKeyword,"},
  {"line":332,"text":"\tast.KindTypeOfKeyword,"},
  {"line":333,"text":"\tast.KindTrueKeyword,"},
  {"line":334,"text":"\tast.KindVoidKeyword,"},
  {"line":335,"text":"\tast.KindUndefinedKeyword,"},
  {"line":336,"text":"\tast.KindUniqueKeyword,"},
  {"line":337,"text":"\tast.KindUnknownKeyword,"},
  {"line":338,"text":")"},
  {"line":340,"text":"func isTypeKeyword(kind ast.Kind) bool {"},
  {"line":341,"text":"\treturn typeKeywords.Has(kind)"},
  {"line":342,"text":"}"},
  {"line":344,"text":"func isSeparator(node *ast.Node, candidate *ast.Node) bool {"},
  {"line":345,"text":"\treturn candidate != nil && node.Parent != nil && (candidate.Kind == ast.KindCommaToken || (candidate.Kind == ast.KindSemicolonToken && node.Parent.Kind == ast.KindObjectLiteralExpression))"},
  {"line":346,"text":"}"},
  {"line":348,"text":"func isLiteralNameOfPropertyDeclarationOrIndexAccess(node *ast.Node) bool {"},
  {"line":350,"text":"\tswitch node.Parent.Kind {"},
  {"line":351,"text":"\tcase ast.KindPropertyDeclaration,"},
  {"line":352,"text":"\t\tast.KindPropertySignature,"},
  {"line":353,"text":"\t\tast.KindPropertyAssignment,"},
  {"line":354,"text":"\t\tast.KindEnumMember,"},
  {"line":355,"text":"\t\tast.KindMethodDeclaration,"},
  {"line":356,"text":"\t\tast.KindMethodSignature,"},
  {"line":357,"text":"\t\tast.KindGetAccessor,"},
  {"line":358,"text":"\t\tast.KindSetAccessor,"},
  {"line":359,"text":"\t\tast.KindModuleDeclaration:"},
  {"line":360,"text":"\t\treturn ast.GetNameOfDeclaration(node.Parent) == node"},
  {"line":361,"text":"\tcase ast.KindElementAccessExpression:"},
  {"line":362,"text":"\t\treturn node.Parent.AsElementAccessExpression().ArgumentExpression == node"},
  {"line":363,"text":"\tcase ast.KindComputedPropertyName:"},
  {"line":364,"text":"\t\treturn true"},
  {"line":365,"text":"\tcase ast.KindLiteralType:"},
  {"line":366,"text":"\t\treturn node.Parent.Parent.Kind == ast.KindIndexedAccessType"},
  {"line":367,"text":"\tdefault:"},
  {"line":368,"text":"\t\treturn false"},
  {"line":369,"text":"\t}"},
  {"line":370,"text":"}"},
  {"line":372,"text":"func isObjectBindingElementWithoutPropertyName(bindingElement *ast.Node) bool {"},
  {"line":373,"text":"\treturn bindingElement.Kind == ast.KindBindingElement &&"},
  {"line":374,"text":"\t\tbindingElement.Parent.Kind == ast.KindObjectBindingPattern &&"},
  {"line":375,"text":"\t\tbindingElement.Name().Kind == ast.KindIdentifier &&"},
  {"line":376,"text":"\t\tbindingElement.PropertyName() == nil"},
  {"line":377,"text":"}"},
  {"line":379,"text":"func isRightSideOfPropertyAccess(node *ast.Node) bool {"},
  {"line":380,"text":"\treturn node.Parent != nil && node.Parent.Kind == ast.KindPropertyAccessExpression && node.Parent.Name() == node"},
  {"line":381,"text":"}"},
  {"line":383,"text":"func isStaticSymbol(symbol *ast.Symbol) bool {"},
  {"line":384,"text":"\tif symbol.ValueDeclaration == nil {"},
  {"line":385,"text":"\t\treturn false"},
  {"line":386,"text":"\t}"},
  {"line":387,"text":"\tmodifierFlags := symbol.ValueDeclaration.ModifierFlags()"},
  {"line":388,"text":"\treturn modifierFlags&ast.ModifierFlagsStatic != 0"},
  {"line":389,"text":"}"},
  {"line":391,"text":"func isImplementation(node *ast.Node) bool {"},
  {"line":392,"text":"\tif node.Flags&ast.NodeFlagsAmbient != 0 {"},
  {"line":393,"text":"\t\treturn !(node.Kind == ast.KindInterfaceDeclaration || node.Kind == ast.KindTypeAliasDeclaration)"},
  {"line":394,"text":"\t}"},
  {"line":395,"text":"\tif ast.IsVariableLike(node) {"},
  {"line":396,"text":"\t\treturn ast.HasInitializer(node)"},
  {"line":397,"text":"\t}"},
  {"line":398,"text":"\tif ast.IsFunctionLikeDeclaration(node) {"},
  {"line":399,"text":"\t\treturn node.Body() != nil"},
  {"line":400,"text":"\t}"},
  {"line":401,"text":"\treturn ast.IsClassLike(node) || ast.IsModuleOrEnumDeclaration(node)"},
  {"line":402,"text":"}"},
  {"line":404,"text":"func isImplementationExpression(node *ast.Node) bool {"},
  {"line":405,"text":"\tswitch node.Kind {"},
  {"line":406,"text":"\tcase ast.KindParenthesizedExpression:"},
  {"line":407,"text":"\t\treturn isImplementationExpression(node.Expression())"},
  {"line":408,"text":"\tcase ast.KindArrowFunction, ast.KindFunctionExpression, ast.KindObjectLiteralExpression, ast.KindClassExpression, ast.KindArrayLiteralExpression:"},
  {"line":409,"text":"\t\treturn true"},
  {"line":410,"text":"\tdefault:"},
  {"line":411,"text":"\t\treturn false"},
  {"line":412,"text":"\t}"},
  {"line":413,"text":"}"},
  {"line":415,"text":"func isReadonlyTypeOperator(node *ast.Node) bool {"},
  {"line":416,"text":"\treturn node.Kind == ast.KindReadonlyKeyword && node.Parent.Kind == ast.KindTypeOperator && node.Parent.AsTypeOperatorNode().Operator == ast.KindReadonlyKeyword"},
  {"line":417,"text":"}"},
  {"line":419,"text":"func isJumpStatementTarget(node *ast.Node) bool {"},
  {"line":420,"text":"\treturn node.Kind == ast.KindIdentifier && ast.IsBreakOrContinueStatement(node.Parent) && node.Parent.Label() == node"},
  {"line":421,"text":"}"},
  {"line":423,"text":"func isLabelOfLabeledStatement(node *ast.Node) bool {"},
  {"line":424,"text":"\treturn node.Kind == ast.KindIdentifier && node.Parent.Kind == ast.KindLabeledStatement && node.Parent.Label() == node"},
  {"line":425,"text":"}"},
  {"line":427,"text":"func findReferenceInPosition(refs []*ast.FileReference, pos int) *ast.FileReference {"},
  {"line":428,"text":"\treturn core.Find(refs, func(ref *ast.FileReference) bool { return ref.TextRange.ContainsInclusive(pos) })"},
  {"line":429,"text":"}"},
  {"line":431,"text":"func getContainingNodeIfInHeritageClause(node *ast.Node) *ast.Node {"},
  {"line":432,"text":"\tif node.Kind == ast.KindIdentifier || node.Kind == ast.KindPropertyAccessExpression {"},
  {"line":433,"text":"\t\treturn getContainingNodeIfInHeritageClause(node.Parent)"},
  {"line":434,"text":"\t}"},
  {"line":435,"text":"\tif node.Kind == ast.KindExpressionWithTypeArguments && (ast.IsClassLike(node.Parent.Parent) || node.Parent.Parent.Kind == ast.KindInterfaceDeclaration) {"},
  {"line":436,"text":"\t\treturn node.Parent.Parent"},
  {"line":437,"text":"\t}"},
  {"line":438,"text":"\treturn nil"},
  {"line":439,"text":"}"},
  {"line":441,"text":"func getContainerNode(node *ast.Node) *ast.Node {"},
  {"line":442,"text":"\tfor parent := node.Parent; parent != nil; parent = parent.Parent {"},
  {"line":443,"text":"\t\tswitch parent.Kind {"},
  {"line":444,"text":"\t\tcase ast.KindSourceFile, ast.KindMethodDeclaration, ast.KindMethodSignature, ast.KindFunctionDeclaration, ast.KindFunctionExpression,"},
  {"line":445,"text":"\t\t\tast.KindGetAccessor, ast.KindSetAccessor, ast.KindClassDeclaration, ast.KindInterfaceDeclaration, ast.KindEnumDeclaration, ast.KindModuleDeclaration:"},
  {"line":446,"text":"\t\t\treturn parent"},
  {"line":447,"text":"\t\t}"},
  {"line":448,"text":"\t}"},
  {"line":449,"text":"\treturn nil"},
  {"line":450,"text":"}"},
  {"line":452,"text":"func getAdjustedLocation(node *ast.Node, forRename bool, sourceFile *ast.SourceFile) *ast.Node {"},
  {"line":455,"text":"\tparent := node.Parent"},
  {"line":463,"text":"\tisModifier := func(node *ast.Node) bool {"},
  {"line":464,"text":"\t\tif ast.IsModifier(node) && (forRename || node.Kind != ast.KindDefaultKeyword) {"},
  {"line":465,"text":"\t\t\treturn ast.CanHaveModifiers(parent) && slices.Contains(parent.ModifierNodes(), node)"},
  {"line":466,"text":"\t\t}"},
  {"line":467,"text":"\t\tswitch node.Kind {"},
  {"line":468,"text":"\t\tcase ast.KindClassKeyword:"},
  {"line":469,"text":"\t\t\treturn ast.IsClassDeclaration(parent) || ast.IsClassExpression(node)"},
  {"line":470,"text":"\t\tcase ast.KindFunctionKeyword:"},
  {"line":471,"text":"\t\t\treturn ast.IsFunctionDeclaration(parent) || ast.IsFunctionExpression(node)"},
  {"line":472,"text":"\t\tcase ast.KindInterfaceKeyword:"},
  {"line":473,"text":"\t\t\treturn ast.IsInterfaceDeclaration(parent)"},
  {"line":474,"text":"\t\tcase ast.KindEnumKeyword:"},
  {"line":475,"text":"\t\t\treturn ast.IsEnumDeclaration(parent)"},
  {"line":476,"text":"\t\tcase ast.KindTypeKeyword:"},
  {"line":477,"text":"\t\t\treturn ast.IsTypeAliasDeclaration(parent)"},
  {"line":478,"text":"\t\tcase ast.KindNamespaceKeyword, ast.KindModuleKeyword:"},
  {"line":479,"text":"\t\t\treturn ast.IsModuleDeclaration(parent)"},
  {"line":480,"text":"\t\tcase ast.KindImportKeyword:"},
  {"line":481,"text":"\t\t\treturn ast.IsImportEqualsDeclaration(parent)"},
  {"line":482,"text":"\t\tcase ast.KindGetKeyword:"},
  {"line":483,"text":"\t\t\treturn ast.IsGetAccessorDeclaration(parent)"},
  {"line":484,"text":"\t\tcase ast.KindSetKeyword:"},
  {"line":485,"text":"\t\t\treturn ast.IsSetAccessorDeclaration(parent)"},
  {"line":486,"text":"\t\t}"},
  {"line":487,"text":"\t\treturn false"},
  {"line":488,"text":"\t}"},
  {"line":489,"text":"\tif isModifier(node) {"},
  {"line":490,"text":"\t\tif sourceFile == nil {"},
  {"line":491,"text":"\t\t\tsourceFile = ast.GetSourceFileOfNode(node)"},
  {"line":492,"text":"\t\t}"},
  {"line":493,"text":"\t\tif location := getAdjustedLocationForDeclaration(parent, forRename, sourceFile); location != nil {"},
  {"line":494,"text":"\t\t\treturn location"},
  {"line":495,"text":"\t\t}"},
  {"line":496,"text":"\t}"},
  {"line":499,"text":"\tif (node.Kind == ast.KindVarKeyword || node.Kind == ast.KindConstKeyword || node.Kind == ast.KindLetKeyword) &&"},
  {"line":500,"text":"\t\tast.IsVariableDeclarationList(parent) && len(parent.AsVariableDeclarationList().Declarations.Nodes) == 1 {"},
  {"line":501,"text":"\t\tdeclaration := parent.AsVariableDeclarationList().Declarations.Nodes[0].AsVariableDeclaration()"},
  {"line":502,"text":"\t\tif ast.IsIdentifier(declaration.Name()) {"},
  {"line":503,"text":"\t\t\treturn declaration.Name()"},
  {"line":504,"text":"\t\t}"},
  {"line":505,"text":"\t}"},
  {"line":507,"text":"\tif node.Kind == ast.KindTypeKeyword {"},
  {"line":512,"text":"\t\tif ast.IsImportClause(parent) && parent.IsTypeOnly() {"},
  {"line":513,"text":"\t\t\tif location := getAdjustedLocationForImportDeclaration(parent.Parent.AsImportDeclaration(), forRename); location != nil {"},
  {"line":514,"text":"\t\t\t\treturn location"},
  {"line":515,"text":"\t\t\t}"},
  {"line":516,"text":"\t\t}"},
  {"line":521,"text":"\t\tif ast.IsExportDeclaration(parent) && parent.IsTypeOnly() {"},
  {"line":522,"text":"\t\t\tif location := getAdjustedLocationForExportDeclaration(parent.AsExportDeclaration(), forRename); location != nil {"},
  {"line":523,"text":"\t\t\t\treturn location"},
  {"line":524,"text":"\t\t\t}"},
  {"line":525,"text":"\t\t}"},
  {"line":526,"text":"\t}"},
  {"line":532,"text":"\tif node.Kind == ast.KindAsKeyword {"},
  {"line":533,"text":"\t\tif parent.Kind == ast.KindImportSpecifier && parent.PropertyName() != nil ||"},
  {"line":534,"text":"\t\t\tparent.Kind == ast.KindExportSpecifier && parent.PropertyName() != nil ||"},
  {"line":535,"text":"\t\t\tparent.Kind == ast.KindNamespaceImport ||"},
  {"line":536,"text":"\t\t\tparent.Kind == ast.KindNamespaceExport {"},
  {"line":537,"text":"\t\t\treturn parent.Name()"},
  {"line":538,"text":"\t\t}"},
  {"line":539,"text":"\t\tif parent.Kind == ast.KindExportDeclaration {"},
  {"line":540,"text":"\t\t\tif exportClause := parent.AsExportDeclaration().ExportClause; exportClause != nil && exportClause.Kind == ast.KindNamespaceExport {"},
  {"line":541,"text":"\t\t\t\treturn exportClause.Name()"},
  {"line":542,"text":"\t\t\t}"},
  {"line":543,"text":"\t\t}"},
  {"line":544,"text":"\t}"},
  {"line":551,"text":"\tif node.Kind == ast.KindImportKeyword && parent.Kind == ast.KindImportDeclaration {"},
  {"line":552,"text":"\t\tif location := getAdjustedLocationForImportDeclaration(parent.AsImportDeclaration(), forRename); location != nil {"},
  {"line":553,"text":"\t\t\treturn location"},
  {"line":554,"text":"\t\t}"},
  {"line":555,"text":"\t}"},
  {"line":557,"text":"\tif node.Kind == ast.KindExportKeyword {"},
  {"line":562,"text":"\t\tif parent.Kind == ast.KindExportDeclaration {"},
  {"line":563,"text":"\t\t\tif location := getAdjustedLocationForExportDeclaration(parent.AsExportDeclaration(), forRename); location != nil {"},
  {"line":564,"text":"\t\t\t\treturn location"},
  {"line":565,"text":"\t\t\t}"},
  {"line":566,"text":"\t\t}"},
  {"line":570,"text":"\t\tif parent.Kind == ast.KindExportAssignment {"},
  {"line":571,"text":"\t\t\treturn ast.SkipOuterExpressions(parent.Expression(), ast.OEKAll)"},
  {"line":572,"text":"\t\t}"},
  {"line":573,"text":"\t}"},
  {"line":575,"text":"\tif node.Kind == ast.KindRequireKeyword && parent.Kind == ast.KindExternalModuleReference {"},
  {"line":576,"text":"\t\treturn parent.Expression()"},
  {"line":577,"text":"\t}"},
  {"line":580,"text":"\tif node.Kind == ast.KindFromKeyword {"},
  {"line":581,"text":"\t\tif (parent.Kind == ast.KindImportDeclaration || parent.Kind == ast.KindExportDeclaration) && parent.ModuleSpecifier() != nil {"},
  {"line":582,"text":"\t\t\treturn parent.ModuleSpecifier()"},
  {"line":583,"text":"\t\t}"},
  {"line":584,"text":"\t}"},
  {"line":590,"text":"\tif (node.Kind == ast.KindExtendsKeyword || node.Kind == ast.KindImplementsKeyword) && parent.Kind == ast.KindHeritageClause && parent.AsHeritageClause().Token == node.Kind {"},
  {"line":591,"text":"\t\tgetAdjustedLocationForHeritageClause := func(node *ast.HeritageClause) *ast.Node {"},
  {"line":594,"text":"\t\t\tif len(node.Types.Nodes) == 1 {"},
  {"line":595,"text":"\t\t\t\treturn node.Types.Nodes[0].Expression()"},
  {"line":596,"text":"\t\t\t}"},
  {"line":601,"text":"\t\t\treturn nil"},
  {"line":602,"text":"\t\t}"},
  {"line":604,"text":"\t\tif location := getAdjustedLocationForHeritageClause(parent.AsHeritageClause()); location != nil {"},
  {"line":605,"text":"\t\t\treturn location"},
  {"line":606,"text":"\t\t}"},
  {"line":607,"text":"\t}"},
  {"line":608,"text":"\tif node.Kind == ast.KindExtendsKeyword {"},
  {"line":610,"text":"\t\tif parent.Kind == ast.KindTypeParameter {"},
  {"line":611,"text":"\t\t\tif constraint := parent.AsTypeParameterDeclaration().Constraint; constraint != nil && constraint.Kind == ast.KindTypeReference {"},
  {"line":612,"text":"\t\t\t\treturn constraint.AsTypeReferenceNode().TypeName"},
  {"line":613,"text":"\t\t\t}"},
  {"line":614,"text":"\t\t}"},
  {"line":616,"text":"\t\tif parent.Kind == ast.KindConditionalType {"},
  {"line":617,"text":"\t\t\tif extendsType := parent.AsConditionalTypeNode().ExtendsType; extendsType != nil && extendsType.Kind == ast.KindTypeReference {"},
  {"line":618,"text":"\t\t\t\treturn extendsType.AsTypeReferenceNode().TypeName"},
  {"line":619,"text":"\t\t\t}"},
  {"line":620,"text":"\t\t}"},
  {"line":621,"text":"\t}"},
  {"line":623,"text":"\tif node.Kind == ast.KindInferKeyword && parent.Kind == ast.KindInferType {"},
  {"line":624,"text":"\t\treturn parent.AsInferTypeNode().TypeParameter.Name()"},
  {"line":625,"text":"\t}"},
  {"line":627,"text":"\tif node.Kind == ast.KindInKeyword && parent.Kind == ast.KindTypeParameter && parent.Parent.Kind == ast.KindMappedType {"},
  {"line":628,"text":"\t\treturn parent.Name()"},
  {"line":629,"text":"\t}"},
  {"line":631,"text":"\tif node.Kind == ast.KindKeyOfKeyword && parent.Kind == ast.KindTypeOperator && parent.AsTypeOperatorNode().Operator == ast.KindKeyOfKeyword {"},
  {"line":632,"text":"\t\tif parentType := parent.Type(); parentType != nil && parentType.Kind == ast.KindTypeReference {"},
  {"line":633,"text":"\t\t\treturn parentType.AsTypeReferenceNode().TypeName"},
  {"line":634,"text":"\t\t}"},
  {"line":635,"text":"\t}"},
  {"line":637,"text":"\tif node.Kind == ast.KindReadonlyKeyword && parent.Kind == ast.KindTypeOperator && parent.AsTypeOperatorNode().Operator == ast.KindReadonlyKeyword {"},
  {"line":638,"text":"\t\tif parentType := parent.Type(); parentType != nil && parentType.Kind == ast.KindArrayType && parentType.AsArrayTypeNode().ElementType.Kind == ast.KindTypeReference {"},
  {"line":639,"text":"\t\t\treturn parentType.AsArrayTypeNode().ElementType.AsTypeReferenceNode().TypeName"},
  {"line":640,"text":"\t\t}"},
  {"line":641,"text":"\t}"},
  {"line":643,"text":"\tif !forRename {"},
  {"line":654,"text":"\t\tif node.Kind == ast.KindNewKeyword && parent.Kind == ast.KindNewExpression ||"},
  {"line":655,"text":"\t\t\tnode.Kind == ast.KindVoidKeyword && parent.Kind == ast.KindVoidExpression ||"},
  {"line":656,"text":"\t\t\tnode.Kind == ast.KindTypeOfKeyword && parent.Kind == ast.KindTypeOfExpression ||"},
  {"line":657,"text":"\t\t\tnode.Kind == ast.KindAwaitKeyword && parent.Kind == ast.KindAwaitExpression ||"},
  {"line":658,"text":"\t\t\tnode.Kind == ast.KindYieldKeyword && parent.Kind == ast.KindYieldExpression ||"},
  {"line":659,"text":"\t\t\tnode.Kind == ast.KindDeleteKeyword && parent.Kind == ast.KindDeleteExpression {"},
  {"line":660,"text":"\t\t\tif expr := parent.Expression(); expr != nil {"},
  {"line":661,"text":"\t\t\t\treturn ast.SkipOuterExpressions(expr, ast.OEKAll)"},
  {"line":662,"text":"\t\t\t}"},
  {"line":663,"text":"\t\t}"},
  {"line":667,"text":"\t\tif (node.Kind == ast.KindInKeyword || node.Kind == ast.KindInstanceOfKeyword) && parent.Kind == ast.KindBinaryExpression && parent.AsBinaryExpression().OperatorToken == node {"},
  {"line":668,"text":"\t\t\treturn ast.SkipOuterExpressions(parent.AsBinaryExpression().Right, ast.OEKAll)"},
  {"line":669,"text":"\t\t}"},
  {"line":672,"text":"\t\tif node.Kind == ast.KindAsKeyword && parent.Kind == ast.KindAsExpression {"},
  {"line":673,"text":"\t\t\tif asExprType := parent.Type(); asExprType != nil && asExprType.Kind == ast.KindTypeReference {"},
  {"line":674,"text":"\t\t\t\treturn asExprType.AsTypeReferenceNode().TypeName"},
  {"line":675,"text":"\t\t\t}"},
  {"line":676,"text":"\t\t}"},
  {"line":680,"text":"\t\tif node.Kind == ast.KindInKeyword && parent.Kind == ast.KindForInStatement ||"},
  {"line":681,"text":"\t\t\tnode.Kind == ast.KindOfKeyword && parent.Kind == ast.KindForOfStatement {"},
  {"line":682,"text":"\t\t\treturn ast.SkipOuterExpressions(parent.Expression(), ast.OEKAll)"},
  {"line":683,"text":"\t\t}"},
  {"line":684,"text":"\t}"},
  {"line":686,"text":"\treturn node"},
  {"line":687,"text":"}"},
  {"line":689,"text":"func getAdjustedLocationForDeclaration(node *ast.Node, forRename bool, sourceFile *ast.SourceFile) *ast.Node {"},
  {"line":690,"text":"\tif node.Name() != nil {"},
  {"line":691,"text":"\t\treturn node.Name()"},
  {"line":692,"text":"\t}"},
  {"line":693,"text":"\tif forRename {"},
  {"line":694,"text":"\t\treturn nil"},
  {"line":695,"text":"\t}"},
  {"line":696,"text":"\tswitch node.Kind {"},
  {"line":697,"text":"\tcase ast.KindClassDeclaration, ast.KindFunctionDeclaration:"},
  {"line":700,"text":"\t\treturn core.Find(node.ModifierNodes(), func(*ast.Node) bool { return node.Kind == ast.KindDefaultKeyword })"},
  {"line":701,"text":"\tcase ast.KindClassExpression:"},
  {"line":703,"text":"\t\treturn astnav.FindChildOfKind(node, ast.KindClassKeyword, sourceFile)"},
  {"line":704,"text":"\tcase ast.KindFunctionExpression:"},
  {"line":706,"text":"\t\treturn astnav.FindChildOfKind(node, ast.KindFunctionKeyword, sourceFile)"},
  {"line":707,"text":"\tcase ast.KindConstructor:"},
  {"line":708,"text":"\t\treturn node"},
  {"line":709,"text":"\t}"},
  {"line":710,"text":"\treturn nil"},
  {"line":711,"text":"}"},
  {"line":713,"text":"func getAdjustedLocationForImportDeclaration(node *ast.ImportDeclaration, forRename bool) *ast.Node {"},
  {"line":714,"text":"\tif node.ImportClause != nil {"},
  {"line":715,"text":"\t\tif name := node.ImportClause.Name(); name != nil {"},
  {"line":716,"text":"\t\t\tif node.ImportClause.AsImportClause().NamedBindings != nil {"},
  {"line":718,"text":"\t\t\t\treturn nil"},
  {"line":719,"text":"\t\t\t}"},
  {"line":722,"text":"\t\t\treturn node.ImportClause.Name()"},
  {"line":723,"text":"\t\t}"},
  {"line":731,"text":"\t\tif namedBindings := node.ImportClause.AsImportClause().NamedBindings; namedBindings != nil {"},
  {"line":732,"text":"\t\t\tswitch namedBindings.Kind {"},
  {"line":733,"text":"\t\t\tcase ast.KindNamedImports:"},
  {"line":735,"text":"\t\t\t\telements := namedBindings.Elements()"},
  {"line":736,"text":"\t\t\t\tif len(elements) != 1 {"},
  {"line":737,"text":"\t\t\t\t\treturn nil"},
  {"line":738,"text":"\t\t\t\t}"},
  {"line":739,"text":"\t\t\t\treturn elements[0].Name()"},
  {"line":741,"text":"\t\t\tcase ast.KindNamespaceImport:"},
  {"line":742,"text":"\t\t\t\treturn namedBindings.Name()"},
  {"line":744,"text":"\t\t\t}"},
  {"line":745,"text":"\t\t}"},
  {"line":746,"text":"\t}"},
  {"line":747,"text":"\tif !forRename {"},
  {"line":751,"text":"\t\treturn node.ModuleSpecifier"},
  {"line":752,"text":"\t}"},
  {"line":753,"text":"\treturn nil"},
  {"line":754,"text":"}"},
  {"line":756,"text":"func getAdjustedLocationForExportDeclaration(node *ast.ExportDeclaration, forRename bool) *ast.Node {"},
  {"line":757,"text":"\tif node.ExportClause != nil {"},
  {"line":764,"text":"\t\tswitch node.ExportClause.Kind {"},
  {"line":765,"text":"\t\tcase ast.KindNamedExports:"},
  {"line":767,"text":"\t\t\telements := node.ExportClause.Elements()"},
  {"line":768,"text":"\t\t\tif len(elements) != 1 {"},
  {"line":769,"text":"\t\t\t\treturn nil"},
  {"line":770,"text":"\t\t\t}"},
  {"line":771,"text":"\t\t\treturn elements[0].Name()"},
  {"line":772,"text":"\t\tcase ast.KindNamespaceExport:"},
  {"line":773,"text":"\t\t\treturn node.ExportClause.Name()"},
  {"line":774,"text":"\t\t}"},
  {"line":775,"text":"\t}"},
  {"line":776,"text":"\tif !forRename {"},
  {"line":779,"text":"\t\treturn node.ModuleSpecifier"},
  {"line":780,"text":"\t}"},
  {"line":781,"text":"\treturn nil"},
  {"line":782,"text":"}"},
  {"line":784,"text":"func symbolFlagsHaveMeaning(flags ast.SymbolFlags, meaning ast.SemanticMeaning) bool {"},
  {"line":785,"text":"\tif meaning == ast.SemanticMeaningAll {"},
  {"line":786,"text":"\t\treturn true"},
  {"line":787,"text":"\t}"},
  {"line":788,"text":"\tif meaning&ast.SemanticMeaningValue != 0 {"},
  {"line":789,"text":"\t\treturn flags&ast.SymbolFlagsValue != 0"},
  {"line":790,"text":"\t}"},
  {"line":791,"text":"\tif meaning&ast.SemanticMeaningType != 0 {"},
  {"line":792,"text":"\t\treturn flags&ast.SymbolFlagsType != 0"},
  {"line":793,"text":"\t}"},
  {"line":794,"text":"\tif meaning&ast.SemanticMeaningNamespace != 0 {"},
  {"line":795,"text":"\t\treturn flags&ast.SymbolFlagsNamespace != 0"},
  {"line":796,"text":"\t}"},
  {"line":797,"text":"\treturn false"},
  {"line":798,"text":"}"},
  {"line":800,"text":"func getMeaningFromLocation(node *ast.Node) ast.SemanticMeaning {"},
  {"line":802,"text":"\tnode = getAdjustedLocation(ast.GetReparsedNodeForNode(node), false /*forRename*/, nil)"},
  {"line":803,"text":"\tparent := node.Parent"},
  {"line":804,"text":"\tswitch {"},
  {"line":805,"text":"\tcase ast.IsSourceFile(node):"},
  {"line":806,"text":"\t\treturn ast.SemanticMeaningValue"},
  {"line":807,"text":"\tcase ast.NodeKindIs(parent, ast.KindExportAssignment, ast.KindExportSpecifier, ast.KindExternalModuleReference, ast.KindImportSpecifier, ast.KindImportClause) || parent.Kind == ast.KindImportEqualsDeclaration && node == parent.Name():"},
  {"line":808,"text":"\t\treturn ast.SemanticMeaningAll"},
  {"line":809,"text":"\tcase isInRightSideOfInternalImportEqualsDeclaration(node):"},
  {"line":813,"text":"\t\tname := node"},
  {"line":814,"text":"\t\tif node.Kind != ast.KindQualifiedName {"},
  {"line":815,"text":"\t\t\tname = core.IfElse(node.Parent.Kind == ast.KindQualifiedName && node.Parent.AsQualifiedName().Right == node, node.Parent, nil)"},
  {"line":816,"text":"\t\t}"},
  {"line":817,"text":"\t\tif name != nil && name.Parent.Kind == ast.KindImportEqualsDeclaration {"},
  {"line":818,"text":"\t\t\treturn ast.SemanticMeaningAll"},
  {"line":819,"text":"\t\t}"},
  {"line":820,"text":"\t\treturn ast.SemanticMeaningNamespace"},
  {"line":821,"text":"\tcase ast.IsDeclarationName(node):"},
  {"line":822,"text":"\t\treturn getMeaningFromDeclaration(parent)"},
  {"line":823,"text":"\tcase ast.IsEntityName(node) && ast.IsJSDocNameReferenceContext(node):"},
  {"line":824,"text":"\t\treturn ast.SemanticMeaningAll"},
  {"line":825,"text":"\tcase isTypeReference(node):"},
  {"line":826,"text":"\t\treturn ast.SemanticMeaningType"},
  {"line":827,"text":"\tcase isNamespaceReference(node):"},
  {"line":828,"text":"\t\treturn ast.SemanticMeaningNamespace"},
  {"line":829,"text":"\tcase ast.IsTypeParameterDeclaration(parent):"},
  {"line":830,"text":"\t\treturn ast.SemanticMeaningType"},
  {"line":831,"text":"\tcase ast.IsLiteralTypeNode(parent):"},
  {"line":833,"text":"\t\treturn ast.SemanticMeaningType | ast.SemanticMeaningValue"},
  {"line":834,"text":"\tdefault:"},
  {"line":835,"text":"\t\treturn ast.SemanticMeaningValue"},
  {"line":836,"text":"\t}"},
  {"line":837,"text":"}"},
  {"line":839,"text":"func getMeaningFromDeclaration(node *ast.Node) ast.SemanticMeaning {"},
  {"line":840,"text":"\tswitch node.Kind {"},
  {"line":841,"text":"\tcase ast.KindVariableDeclaration, ast.KindParameter, ast.KindBindingElement,"},
  {"line":842,"text":"\t\tast.KindPropertyDeclaration, ast.KindPropertySignature, ast.KindPropertyAssignment, ast.KindShorthandPropertyAssignment,"},
  {"line":843,"text":"\t\tast.KindMethodDeclaration, ast.KindMethodSignature, ast.KindConstructor, ast.KindGetAccessor, ast.KindSetAccessor,"},
  {"line":844,"text":"\t\tast.KindFunctionDeclaration, ast.KindFunctionExpression, ast.KindArrowFunction, ast.KindCatchClause, ast.KindJsxAttribute:"},
  {"line":845,"text":"\t\treturn ast.SemanticMeaningValue"},
  {"line":847,"text":"\tcase ast.KindTypeParameter, ast.KindInterfaceDeclaration, ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration, ast.KindTypeLiteral:"},
  {"line":848,"text":"\t\treturn ast.SemanticMeaningType"},
  {"line":850,"text":"\tcase ast.KindEnumMember, ast.KindClassDeclaration:"},
  {"line":851,"text":"\t\treturn ast.SemanticMeaningValue | ast.SemanticMeaningType"},
  {"line":853,"text":"\tcase ast.KindModuleDeclaration:"},
  {"line":854,"text":"\t\tif ast.IsAmbientModule(node) {"},
  {"line":855,"text":"\t\t\treturn ast.SemanticMeaningNamespace | ast.SemanticMeaningValue"},
  {"line":856,"text":"\t\t} else if ast.GetModuleInstanceState(node) == ast.ModuleInstanceStateInstantiated {"},
  {"line":857,"text":"\t\t\treturn ast.SemanticMeaningNamespace | ast.SemanticMeaningValue"},
  {"line":858,"text":"\t\t} else {"},
  {"line":859,"text":"\t\t\treturn ast.SemanticMeaningNamespace"},
  {"line":860,"text":"\t\t}"},
  {"line":862,"text":"\tcase ast.KindEnumDeclaration, ast.KindNamedImports, ast.KindImportSpecifier, ast.KindImportEqualsDeclaration, ast.KindImportDeclaration,"},
  {"line":863,"text":"\t\tast.KindJSImportDeclaration, ast.KindExportAssignment, ast.KindExportDeclaration:"},
  {"line":864,"text":"\t\treturn ast.SemanticMeaningAll"},
  {"line":867,"text":"\tcase ast.KindSourceFile:"},
  {"line":868,"text":"\t\treturn ast.SemanticMeaningNamespace | ast.SemanticMeaningValue"},
  {"line":869,"text":"\t}"},
  {"line":871,"text":"\treturn ast.SemanticMeaningAll"},
  {"line":872,"text":"}"},
  {"line":874,"text":"func getIntersectingMeaningFromDeclarations(node *ast.Node, symbol *ast.Symbol, defaultMeaning ast.SemanticMeaning) ast.SemanticMeaning {"},
  {"line":875,"text":"\tif node == nil {"},
  {"line":876,"text":"\t\treturn defaultMeaning"},
  {"line":877,"text":"\t}"},
  {"line":879,"text":"\tmeaning := getMeaningFromLocation(node)"},
  {"line":880,"text":"\tdeclarations := symbol.Declarations"},
  {"line":881,"text":"\tif len(declarations) == 0 {"},
  {"line":882,"text":"\t\treturn meaning"},
  {"line":883,"text":"\t}"},
  {"line":885,"text":"\tlastIterationMeaning := meaning"},
  {"line":888,"text":"\titeration := func(m ast.SemanticMeaning) ast.SemanticMeaning {"},
  {"line":889,"text":"\t\tfor _, declaration := range declarations {"},
  {"line":890,"text":"\t\t\tdeclarationMeaning := getMeaningFromDeclaration(declaration)"},
  {"line":892,"text":"\t\t\tif declarationMeaning&m != 0 {"},
  {"line":893,"text":"\t\t\t\tm |= declarationMeaning"},
  {"line":894,"text":"\t\t\t}"},
  {"line":895,"text":"\t\t}"},
  {"line":896,"text":"\t\treturn m"},
  {"line":897,"text":"\t}"},
  {"line":898,"text":"\tmeaning = iteration(meaning)"},
  {"line":900,"text":"\tfor meaning != lastIterationMeaning {"},
  {"line":907,"text":"\t\tlastIterationMeaning = meaning"},
  {"line":908,"text":"\t\tmeaning = iteration(meaning)"},
  {"line":909,"text":"\t}"},
  {"line":911,"text":"\treturn meaning"},
  {"line":912,"text":"}"},
  {"line":915,"text":"func getAllSuperTypeNodes(node *ast.Node) []*ast.TypeNode {"},
  {"line":916,"text":"\tif ast.IsInterfaceDeclaration(node) {"},
  {"line":917,"text":"\t\treturn ast.GetHeritageElements(node, ast.KindExtendsKeyword)"},
  {"line":918,"text":"\t}"},
  {"line":919,"text":"\tif ast.IsClassLike(node) {"},
  {"line":920,"text":"\t\treturn append("},
  {"line":921,"text":"\t\t\tcore.SingleElementSlice(ast.GetClassExtendsHeritageElement(node)),"},
  {"line":922,"text":"\t\t\tast.GetImplementsTypeNodes(node)...,"},
  {"line":923,"text":"\t\t)"},
  {"line":924,"text":"\t}"},
  {"line":925,"text":"\treturn nil"},
  {"line":926,"text":"}"},
  {"line":928,"text":"func getParentSymbolsOfPropertyAccess(location *ast.Node, symbol *ast.Symbol, ch *checker.Checker) []*ast.Symbol {"},
  {"line":929,"text":"\tif !isRightSideOfPropertyAccess(location) {"},
  {"line":930,"text":"\t\treturn nil"},
  {"line":931,"text":"\t}"},
  {"line":932,"text":"\tlhsType := ch.GetTypeAtLocation(location.Parent.Expression())"},
  {"line":933,"text":"\tif lhsType == nil {"},
  {"line":934,"text":"\t\treturn nil"},
  {"line":935,"text":"\t}"},
  {"line":936,"text":"\tvar possibleSymbols []*checker.Type"},
  {"line":937,"text":"\tif lhsType.Flags()&checker.TypeFlagsUnionOrIntersection != 0 {"},
  {"line":938,"text":"\t\tpossibleSymbols = lhsType.Types()"},
  {"line":939,"text":"\t} else if lhsType.Symbol() != symbol.Parent {"},
  {"line":940,"text":"\t\tpossibleSymbols = []*checker.Type{lhsType}"},
  {"line":941,"text":"\t}"},
  {"line":942,"text":"\treturn core.MapNonNil(possibleSymbols, func(t *checker.Type) *ast.Symbol {"},
  {"line":943,"text":"\t\tif t.Symbol() != nil && t.Symbol().Flags&(ast.SymbolFlagsClass|ast.SymbolFlagsInterface) != 0 {"},
  {"line":944,"text":"\t\t\treturn t.Symbol()"},
  {"line":945,"text":"\t\t}"},
  {"line":946,"text":"\t\treturn nil"},
  {"line":947,"text":"\t})"},
  {"line":948,"text":"}"},
  {"line":956,"text":"func getPropertySymbolsFromBaseTypes(symbol *ast.Symbol, propertyName string, checker *checker.Checker, cb func(base *ast.Symbol) *ast.Symbol) *ast.Symbol {"},
  {"line":957,"text":"\tvar seen collections.Set[*ast.Symbol]"},
  {"line":958,"text":"\tvar recur func(*ast.Symbol) *ast.Symbol"},
  {"line":959,"text":"\trecur = func(symbol *ast.Symbol) *ast.Symbol {"},
  {"line":964,"text":"\t\tif symbol.Flags&(ast.SymbolFlagsClass|ast.SymbolFlagsInterface) == 0 || !seen.AddIfAbsent(symbol) {"},
  {"line":965,"text":"\t\t\treturn nil"},
  {"line":966,"text":"\t\t}"},
  {"line":967,"text":"\t\tfor _, declaration := range symbol.Declarations {"},
  {"line":968,"text":"\t\t\tfor _, typeReference := range getAllSuperTypeNodes(declaration) {"},
  {"line":969,"text":"\t\t\t\tif propertyType := checker.GetTypeAtLocation(typeReference); propertyType != nil && propertyType.Symbol() != nil {"},
  {"line":971,"text":"\t\t\t\t\tif propertySymbol := checker.GetPropertyOfType(propertyType, propertyName); propertySymbol != nil {"},
  {"line":972,"text":"\t\t\t\t\t\tfor _, rootSymbol := range checker.GetRootSymbols(propertySymbol) {"},
  {"line":973,"text":"\t\t\t\t\t\t\tif result := cb(rootSymbol); result != nil {"},
  {"line":974,"text":"\t\t\t\t\t\t\t\treturn result"},
  {"line":975,"text":"\t\t\t\t\t\t\t}"},
  {"line":976,"text":"\t\t\t\t\t\t}"},
  {"line":977,"text":"\t\t\t\t\t}"},
  {"line":978,"text":"\t\t\t\t\tif result := recur(propertyType.Symbol()); result != nil {"},
  {"line":979,"text":"\t\t\t\t\t\treturn result"},
  {"line":980,"text":"\t\t\t\t\t}"},
  {"line":981,"text":"\t\t\t\t}"},
  {"line":982,"text":"\t\t\t}"},
  {"line":983,"text":"\t\t}"},
  {"line":984,"text":"\t\treturn nil"},
  {"line":985,"text":"\t}"},
  {"line":986,"text":"\treturn recur(symbol)"},
  {"line":987,"text":"}"},
  {"line":989,"text":"func getPropertySymbolFromBindingElement(checker *checker.Checker, bindingElement *ast.Node) *ast.Symbol {"},
  {"line":990,"text":"\tif typeOfPattern := checker.GetTypeAtLocation(bindingElement.Parent); typeOfPattern != nil {"},
  {"line":991,"text":"\t\treturn checker.GetPropertyOfType(typeOfPattern, bindingElement.Name().Text())"},
  {"line":992,"text":"\t}"},
  {"line":993,"text":"\treturn nil"},
  {"line":994,"text":"}"},
  {"line":996,"text":"func getPropertySymbolOfObjectBindingPatternWithoutPropertyName(symbol *ast.Symbol, checker *checker.Checker) *ast.Symbol {"},
  {"line":997,"text":"\tbindingElement := ast.GetDeclarationOfKind(symbol, ast.KindBindingElement)"},
  {"line":998,"text":"\tif bindingElement != nil && isObjectBindingElementWithoutPropertyName(bindingElement) {"},
  {"line":999,"text":"\t\treturn getPropertySymbolFromBindingElement(checker, bindingElement)"},
  {"line":1000,"text":"\t}"},
  {"line":1001,"text":"\treturn nil"},
  {"line":1002,"text":"}"},
  {"line":1004,"text":"func getTargetLabel(referenceNode *ast.Node, labelName string) *ast.Node {"},
  {"line":1006,"text":"\tfor referenceNode != nil {"},
  {"line":1007,"text":"\t\tif referenceNode.Kind == ast.KindLabeledStatement && referenceNode.Label().Text() == labelName {"},
  {"line":1008,"text":"\t\t\treturn referenceNode.Label()"},
  {"line":1009,"text":"\t\t}"},
  {"line":1010,"text":"\t\treferenceNode = referenceNode.Parent"},
  {"line":1011,"text":"\t}"},
  {"line":1012,"text":"\treturn nil"},
  {"line":1013,"text":"}"},
  {"line":1015,"text":"func skipConstraint(t *checker.Type, typeChecker *checker.Checker) *checker.Type {"},
  {"line":1016,"text":"\tif t.IsTypeParameter() {"},
  {"line":1017,"text":"\t\tc := typeChecker.GetBaseConstraintOfType(t)"},
  {"line":1018,"text":"\t\tif c != nil {"},
  {"line":1019,"text":"\t\t\treturn c"},
  {"line":1020,"text":"\t\t}"},
  {"line":1021,"text":"\t}"},
  {"line":1022,"text":"\treturn t"},
  {"line":1023,"text":"}"},
  {"line":1025,"text":"type caseClauseTrackerState struct {"},
  {"line":1026,"text":"\texistingStrings collections.Set[string]"},
  {"line":1027,"text":"\texistingNumbers collections.Set[jsnum.Number]"},
  {"line":1028,"text":"\texistingBigInts collections.Set[jsnum.PseudoBigInt]"},
  {"line":1029,"text":"}"},
  {"line":1032,"text":"type trackerAddValue = any"},
  {"line":1035,"text":"type trackerHasValue = any"},
  {"line":1037,"text":"type caseClauseTracker interface {"},
  {"line":1038,"text":"\taddValue(value trackerAddValue)"},
  {"line":1039,"text":"\thasValue(value trackerHasValue) bool"},
  {"line":1040,"text":"}"},
  {"line":1042,"text":"func (c *caseClauseTrackerState) addValue(value trackerAddValue) {"},
  {"line":1043,"text":"\tswitch v := value.(type) {"},
  {"line":1044,"text":"\tcase string:"},
  {"line":1045,"text":"\t\tc.existingStrings.Add(v)"},
  {"line":1046,"text":"\tcase jsnum.Number:"},
  {"line":1047,"text":"\t\tc.existingNumbers.Add(v)"},
  {"line":1048,"text":"\tdefault:"},
  {"line":1049,"text":"\t\tpanic(fmt.Sprintf(\"Unsupported type: %T\", v))"},
  {"line":1050,"text":"\t}"},
  {"line":1051,"text":"}"},
  {"line":1053,"text":"func (c *caseClauseTrackerState) hasValue(value trackerHasValue) bool {"},
  {"line":1054,"text":"\tswitch v := value.(type) {"},
  {"line":1055,"text":"\tcase string:"},
  {"line":1056,"text":"\t\treturn c.existingStrings.Has(v)"},
  {"line":1057,"text":"\tcase jsnum.Number:"},
  {"line":1058,"text":"\t\treturn c.existingNumbers.Has(v)"},
  {"line":1059,"text":"\tcase jsnum.PseudoBigInt:"},
  {"line":1060,"text":"\t\treturn c.existingBigInts.Has(v)"},
  {"line":1061,"text":"\tdefault:"},
  {"line":1062,"text":"\t\tpanic(fmt.Sprintf(\"Unsupported type: %T\", v))"},
  {"line":1063,"text":"\t}"},
  {"line":1064,"text":"}"},
  {"line":1066,"text":"func newCaseClauseTracker(typeChecker *checker.Checker, clauses []*ast.CaseOrDefaultClauseNode) caseClauseTracker {"},
  {"line":1067,"text":"\tc := &caseClauseTrackerState{"},
  {"line":1068,"text":"\t\texistingStrings: collections.Set[string]{},"},
  {"line":1069,"text":"\t\texistingNumbers: collections.Set[jsnum.Number]{},"},
  {"line":1070,"text":"\t\texistingBigInts: collections.Set[jsnum.PseudoBigInt]{},"},
  {"line":1071,"text":"\t}"},
  {"line":1072,"text":"\tfor _, clause := range clauses {"},
  {"line":1073,"text":"\t\tif !ast.IsDefaultClause(clause) {"},
  {"line":1074,"text":"\t\t\texpression := ast.SkipParentheses(clause.Expression())"},
  {"line":1075,"text":"\t\t\tif ast.IsLiteralExpression(expression) {"},
  {"line":1076,"text":"\t\t\t\tswitch expression.Kind {"},
  {"line":1077,"text":"\t\t\t\tcase ast.KindNoSubstitutionTemplateLiteral, ast.KindStringLiteral:"},
  {"line":1078,"text":"\t\t\t\t\tc.existingStrings.Add(expression.Text())"},
  {"line":1079,"text":"\t\t\t\tcase ast.KindNumericLiteral:"},
  {"line":1080,"text":"\t\t\t\t\tc.existingNumbers.Add(jsnum.FromString(expression.Text()))"},
  {"line":1081,"text":"\t\t\t\tcase ast.KindBigIntLiteral:"},
  {"line":1082,"text":"\t\t\t\t\tc.existingBigInts.Add(jsnum.ParseValidBigInt(expression.Text()))"},
  {"line":1083,"text":"\t\t\t\t}"},
  {"line":1084,"text":"\t\t\t} else {"},
  {"line":1085,"text":"\t\t\t\tsymbol := typeChecker.GetSymbolAtLocation(clause.Expression())"},
  {"line":1086,"text":"\t\t\t\tif symbol != nil && symbol.ValueDeclaration != nil && ast.IsEnumMember(symbol.ValueDeclaration) {"},
  {"line":1087,"text":"\t\t\t\t\tenumValue := typeChecker.GetConstantValue(symbol.ValueDeclaration)"},
  {"line":1088,"text":"\t\t\t\t\tif enumValue != nil {"},
  {"line":1089,"text":"\t\t\t\t\t\tc.addValue(enumValue)"},
  {"line":1090,"text":"\t\t\t\t\t}"},
  {"line":1091,"text":"\t\t\t\t}"},
  {"line":1092,"text":"\t\t\t}"},
  {"line":1093,"text":"\t\t}"},
  {"line":1094,"text":"\t}"},
  {"line":1095,"text":"\treturn c"},
  {"line":1096,"text":"}"},
  {"line":1098,"text":"func RangeContainsRange(r1 core.TextRange, r2 core.TextRange) bool {"},
  {"line":1099,"text":"\treturn startEndContainsRange(r1.Pos(), r1.End(), r2)"},
  {"line":1100,"text":"}"},
  {"line":1102,"text":"func startEndContainsRange(start int, end int, textRange core.TextRange) bool {"},
  {"line":1103,"text":"\treturn start <= textRange.Pos() && end >= textRange.End()"},
  {"line":1104,"text":"}"},
  {"line":1106,"text":"func getPossibleGenericSignatures(called *ast.Expression, typeArgumentCount int, c *checker.Checker) []*checker.Signature {"},
  {"line":1107,"text":"\ttypeAtLocation := c.GetTypeAtLocation(called)"},
  {"line":1108,"text":"\tif ast.IsOptionalChain(called.Parent) {"},
  {"line":1109,"text":"\t\ttypeAtLocation = removeOptionality(typeAtLocation, ast.IsOptionalChainRoot(called.Parent), true /*isOptionalChain*/, c)"},
  {"line":1110,"text":"\t}"},
  {"line":1111,"text":"\tvar signatures []*checker.Signature"},
  {"line":1112,"text":"\tif ast.IsNewExpression(called.Parent) {"},
  {"line":1113,"text":"\t\tsignatures = c.GetSignaturesOfType(typeAtLocation, checker.SignatureKindConstruct)"},
  {"line":1114,"text":"\t} else {"},
  {"line":1115,"text":"\t\tsignatures = c.GetSignaturesOfType(typeAtLocation, checker.SignatureKindCall)"},
  {"line":1116,"text":"\t}"},
  {"line":1117,"text":"\treturn core.Filter(signatures, func(s *checker.Signature) bool {"},
  {"line":1118,"text":"\t\treturn s.TypeParameters() != nil && len(s.TypeParameters()) >= typeArgumentCount"},
  {"line":1119,"text":"\t})"},
  {"line":1120,"text":"}"},
  {"line":1122,"text":"func removeOptionality(t *checker.Type, isOptionalExpression bool, isOptionalChain bool, c *checker.Checker) *checker.Type {"},
  {"line":1123,"text":"\tif isOptionalExpression {"},
  {"line":1124,"text":"\t\treturn c.GetNonNullableType(t)"},
  {"line":1125,"text":"\t} else if isOptionalChain {"},
  {"line":1126,"text":"\t\treturn c.GetNonOptionalType(t)"},
  {"line":1127,"text":"\t}"},
  {"line":1128,"text":"\treturn t"},
  {"line":1129,"text":"}"},
  {"line":1131,"text":"func isNoSubstitutionTemplateLiteral(node *ast.Node) bool {"},
  {"line":1132,"text":"\treturn node.Kind == ast.KindNoSubstitutionTemplateLiteral"},
  {"line":1133,"text":"}"},
  {"line":1135,"text":"func isTaggedTemplateExpression(node *ast.Node) bool {"},
  {"line":1136,"text":"\treturn node.Kind == ast.KindTaggedTemplateExpression"},
  {"line":1137,"text":"}"},
  {"line":1139,"text":"func isInsideTemplateLiteral(node *ast.Node, position int, sourceFile *ast.SourceFile) bool {"},
  {"line":1140,"text":"\treturn ast.IsTemplateLiteralKind(node.Kind) && (scanner.GetTokenPosOfNode(node, sourceFile, false) < position && position < node.End() || (ast.IsUnterminatedLiteral(node) && position == node.End()))"},
  {"line":1141,"text":"}"},
  {"line":1144,"text":"func isTemplateHead(node *ast.Node) bool {"},
  {"line":1145,"text":"\treturn node.Kind == ast.KindTemplateHead"},
  {"line":1146,"text":"}"},
  {"line":1148,"text":"func isTemplateTail(node *ast.Node) bool {"},
  {"line":1149,"text":"\treturn node.Kind == ast.KindTemplateTail"},
  {"line":1150,"text":"}"},
  {"line":1152,"text":"func findPrecedingMatchingToken(token *ast.Node, matchingTokenKind ast.Kind, sourceFile *ast.SourceFile) *ast.Node {"},
  {"line":1153,"text":"\tcloseTokenText := scanner.TokenToString(token.Kind)"},
  {"line":1154,"text":"\tmatchingTokenText := scanner.TokenToString(matchingTokenKind)"},
  {"line":1157,"text":"\tbestGuessIndex := strings.LastIndex(sourceFile.Text(), matchingTokenText)"},
  {"line":1158,"text":"\tif bestGuessIndex == -1 {"},
  {"line":1159,"text":"\t\treturn nil // if the token text doesn't appear in the file, there can't be a match - super fast bail"},
  {"line":1160,"text":"\t}"},
  {"line":1162,"text":"\tif strings.LastIndex(sourceFile.Text(), closeTokenText) < bestGuessIndex {"},
  {"line":1163,"text":"\t\tnodeAtGuess := astnav.FindPrecedingToken(sourceFile, bestGuessIndex+1)"},
  {"line":1164,"text":"\t\tif nodeAtGuess != nil && nodeAtGuess.Kind == matchingTokenKind {"},
  {"line":1165,"text":"\t\t\treturn nodeAtGuess"},
  {"line":1166,"text":"\t\t}"},
  {"line":1167,"text":"\t}"},
  {"line":1168,"text":"\ttokenKind := token.Kind"},
  {"line":1169,"text":"\tremainingMatchingTokens := 0"},
  {"line":1170,"text":"\tfor {"},
  {"line":1171,"text":"\t\tpreceding := astnav.FindPrecedingToken(sourceFile, token.Pos())"},
  {"line":1172,"text":"\t\tif preceding == nil {"},
  {"line":1173,"text":"\t\t\treturn nil"},
  {"line":1174,"text":"\t\t}"},
  {"line":1175,"text":"\t\ttoken = preceding"},
  {"line":1176,"text":"\t\tswitch token.Kind {"},
  {"line":1177,"text":"\t\tcase matchingTokenKind:"},
  {"line":1178,"text":"\t\t\tif remainingMatchingTokens == 0 {"},
  {"line":1179,"text":"\t\t\t\treturn token"},
  {"line":1180,"text":"\t\t\t}"},
  {"line":1181,"text":"\t\t\tremainingMatchingTokens--"},
  {"line":1182,"text":"\t\tcase tokenKind:"},
  {"line":1183,"text":"\t\t\tremainingMatchingTokens++"},
  {"line":1184,"text":"\t\t}"},
  {"line":1185,"text":"\t}"},
  {"line":1186,"text":"}"},
  {"line":1188,"text":"func findContainingList(node *ast.Node, file *ast.SourceFile) *ast.NodeList {"},
  {"line":1191,"text":"\tvar list *ast.NodeList"},
  {"line":1192,"text":"\tvisitNode := func(n *ast.Node, visitor *ast.NodeVisitor) *ast.Node {"},
  {"line":1193,"text":"\t\treturn n"},
  {"line":1194,"text":"\t}"},
  {"line":1195,"text":"\tvisitNodes := func(nodes *ast.NodeList, visitor *ast.NodeVisitor) *ast.NodeList {"},
  {"line":1196,"text":"\t\tif nodes != nil && RangeContainsRange(nodes.Loc, node.Loc) {"},
  {"line":1197,"text":"\t\t\tlist = nodes"},
  {"line":1198,"text":"\t\t}"},
  {"line":1199,"text":"\t\treturn nodes"},
  {"line":1200,"text":"\t}"},
  {"line":1201,"text":"\tastnav.VisitEachChildAndJSDoc(node.Parent, file, visitNode, visitNodes)"},
  {"line":1202,"text":"\treturn list"},
  {"line":1203,"text":"}"},
  {"line":1205,"text":"func getLeadingCommentRangesOfNode(node *ast.Node, file *ast.SourceFile) iter.Seq[ast.CommentRange] {"},
  {"line":1206,"text":"\tif node.Kind == ast.KindJsxText {"},
  {"line":1207,"text":"\t\treturn nil"},
  {"line":1208,"text":"\t}"},
  {"line":1209,"text":"\treturn scanner.GetLeadingCommentRanges(&ast.NodeFactory{}, file.Text(), node.Pos())"},
  {"line":1210,"text":"}"},
  {"line":1213,"text":"func getChildrenFromNonJSDocNode(node *ast.Node, sourceFile *ast.SourceFile) []*ast.Node {"},
  {"line":1214,"text":"\tvar childNodes []*ast.Node"},
  {"line":1215,"text":"\tnode.ForEachChild(func(child *ast.Node) bool {"},
  {"line":1216,"text":"\t\tchildNodes = append(childNodes, child)"},
  {"line":1217,"text":"\t\treturn false"},
  {"line":1218,"text":"\t})"},
  {"line":1222,"text":"\tif len(childNodes) == 0 {"},
  {"line":1223,"text":"\t\treturn nil"},
  {"line":1224,"text":"\t}"},
  {"line":1226,"text":"\tvar children []*ast.Node"},
  {"line":1227,"text":"\tpos := node.Pos()"},
  {"line":1228,"text":"\tfor _, child := range childNodes {"},
  {"line":1229,"text":"\t\tscanner := scanner.GetScannerForSourceFile(sourceFile, pos)"},
  {"line":1230,"text":"\t\tfor pos < child.Pos() {"},
  {"line":1231,"text":"\t\t\ttoken := scanner.Token()"},
  {"line":1232,"text":"\t\t\ttokenFullStart := scanner.TokenFullStart()"},
  {"line":1233,"text":"\t\t\ttokenEnd := scanner.TokenEnd()"},
  {"line":1234,"text":"\t\t\tchildren = append(children, sourceFile.GetOrCreateToken(token, tokenFullStart, tokenEnd, node, scanner.TokenFlags()))"},
  {"line":1235,"text":"\t\t\tpos = tokenEnd"},
  {"line":1236,"text":"\t\t\tscanner.Scan()"},
  {"line":1237,"text":"\t\t}"},
  {"line":1238,"text":"\t\tchildren = append(children, child)"},
  {"line":1239,"text":"\t\tpos = child.End()"},
  {"line":1240,"text":"\t}"},
  {"line":1241,"text":"\tscanner := scanner.GetScannerForSourceFile(sourceFile, pos)"},
  {"line":1242,"text":"\tfor pos < node.End() {"},
  {"line":1243,"text":"\t\ttoken := scanner.Token()"},
  {"line":1244,"text":"\t\ttokenFullStart := scanner.TokenFullStart()"},
  {"line":1245,"text":"\t\ttokenEnd := scanner.TokenEnd()"},
  {"line":1246,"text":"\t\tchildren = append(children, sourceFile.GetOrCreateToken(token, tokenFullStart, tokenEnd, node, scanner.TokenFlags()))"},
  {"line":1247,"text":"\t\tpos = tokenEnd"},
  {"line":1248,"text":"\t\tscanner.Scan()"},
  {"line":1249,"text":"\t}"},
  {"line":1250,"text":"\treturn children"},
  {"line":1251,"text":"}"},
  {"line":1254,"text":"func getContainingObjectLiteralElement(node *ast.Node) *ast.Node {"},
  {"line":1255,"text":"\telement := getContainingObjectLiteralElementWorker(node)"},
  {"line":1256,"text":"\tif element != nil && (ast.IsObjectLiteralExpression(element.Parent) || ast.IsJsxAttributes(element.Parent)) {"},
  {"line":1257,"text":"\t\treturn element"},
  {"line":1258,"text":"\t}"},
  {"line":1259,"text":"\treturn nil"},
  {"line":1260,"text":"}"},
  {"line":1262,"text":"func getContainingObjectLiteralElementWorker(node *ast.Node) *ast.Node {"},
  {"line":1263,"text":"\tswitch node.Kind {"},
  {"line":1264,"text":"\tcase ast.KindStringLiteral, ast.KindNoSubstitutionTemplateLiteral, ast.KindNumericLiteral:"},
  {"line":1265,"text":"\t\tif node.Parent.Kind == ast.KindComputedPropertyName {"},
  {"line":1266,"text":"\t\t\tif isObjectLiteralOrJsxElement(node.Parent.Parent) {"},
  {"line":1267,"text":"\t\t\t\treturn node.Parent.Parent"},
  {"line":1268,"text":"\t\t\t}"},
  {"line":1269,"text":"\t\t\treturn nil"},
  {"line":1270,"text":"\t\t}"},
  {"line":1271,"text":"\t\tfallthrough"},
  {"line":1272,"text":"\tcase ast.KindIdentifier:"},
  {"line":1273,"text":"\t\tif isObjectLiteralOrJsxElement(node.Parent) && (node.Parent.Parent.Kind == ast.KindObjectLiteralExpression || node.Parent.Parent.Kind == ast.KindJsxAttributes) && node.Parent.Name() == node {"},
  {"line":1274,"text":"\t\t\treturn node.Parent"},
  {"line":1275,"text":"\t\t}"},
  {"line":1276,"text":"\t}"},
  {"line":1277,"text":"\treturn nil"},
  {"line":1278,"text":"}"},
  {"line":1280,"text":"func isObjectLiteralOrJsxElement(node *ast.Node) bool {"},
  {"line":1281,"text":"\treturn ast.IsObjectLiteralElement(node) || ast.IsJsxAttribute(node) || ast.IsJsxSpreadAttribute(node)"},
  {"line":1282,"text":"}"},
  {"line":1285,"text":"func nodeSeenTracker() func(*ast.Node) bool {"},
  {"line":1286,"text":"\tvar seen collections.Set[*ast.Node]"},
  {"line":1287,"text":"\treturn func(node *ast.Node) bool {"},
  {"line":1288,"text":"\t\treturn seen.AddIfAbsent(node)"},
  {"line":1289,"text":"\t}"},
  {"line":1290,"text":"}"},
  {"line":1293,"text":"func toContextRange(textRange *core.TextRange, contextFile *ast.SourceFile, context *ast.Node) *core.TextRange {"},
  {"line":1294,"text":"\tif context == nil {"},
  {"line":1295,"text":"\t\treturn textRange"},
  {"line":1296,"text":"\t}"},
  {"line":1298,"text":"\tcontextRange := getRangeOfNode(context, contextFile, nil /*endNode*/)"},
  {"line":1299,"text":"\tif contextRange.Pos() != textRange.Pos() || contextRange.End() != textRange.End() {"},
  {"line":1300,"text":"\t\treturn &contextRange"},
  {"line":1301,"text":"\t}"},
  {"line":1302,"text":"\treturn nil"},
  {"line":1303,"text":"}"},
  {"line":1305,"text":"func getReferenceAtPosition(sourceFile *ast.SourceFile, position int, program *compiler.Program) *refInfo {"},
  {"line":1306,"text":"\tif referencePath := findReferenceInPosition(sourceFile.ReferencedFiles, position); referencePath != nil {"},
  {"line":1307,"text":"\t\tif file := program.GetSourceFileFromReference(sourceFile, referencePath); file != nil {"},
  {"line":1308,"text":"\t\t\treturn &refInfo{reference: referencePath, fileName: file.FileName(), file: file, unverified: false}"},
  {"line":1309,"text":"\t\t}"},
  {"line":1310,"text":"\t\treturn nil"},
  {"line":1311,"text":"\t}"},
  {"line":1313,"text":"\tif typeReferenceDirective := findReferenceInPosition(sourceFile.TypeReferenceDirectives, position); typeReferenceDirective != nil {"},
  {"line":1314,"text":"\t\tif reference := program.GetResolvedTypeReferenceDirectiveFromTypeReferenceDirective(typeReferenceDirective, sourceFile); reference != nil {"},
  {"line":1315,"text":"\t\t\tif file := program.GetSourceFile(reference.ResolvedFileName); file != nil {"},
  {"line":1316,"text":"\t\t\t\treturn &refInfo{reference: typeReferenceDirective, fileName: file.FileName(), file: file, unverified: false}"},
  {"line":1317,"text":"\t\t\t}"},
  {"line":1318,"text":"\t\t}"},
  {"line":1319,"text":"\t\treturn nil"},
  {"line":1320,"text":"\t}"},
  {"line":1322,"text":"\tif libReferenceDirective := findReferenceInPosition(sourceFile.LibReferenceDirectives, position); libReferenceDirective != nil {"},
  {"line":1323,"text":"\t\tif file := program.GetLibFileFromReference(libReferenceDirective); file != nil {"},
  {"line":1324,"text":"\t\t\treturn &refInfo{reference: libReferenceDirective, fileName: file.FileName(), file: file, unverified: false}"},
  {"line":1325,"text":"\t\t}"},
  {"line":1326,"text":"\t\treturn nil"},
  {"line":1327,"text":"\t}"},
  {"line":1329,"text":"\tif len(sourceFile.Imports()) == 0 && len(sourceFile.ModuleAugmentations) == 0 {"},
  {"line":1330,"text":"\t\treturn nil"},
  {"line":1331,"text":"\t}"},
  {"line":1333,"text":"\tnode := astnav.GetTouchingToken(sourceFile, position)"},
  {"line":1334,"text":"\tif !isModuleSpecifierLike(node) || !tspath.IsExternalModuleNameRelative(node.Text()) {"},
  {"line":1335,"text":"\t\treturn nil"},
  {"line":1336,"text":"\t}"},
  {"line":1338,"text":"\tif resolution := program.GetResolvedModuleFromModuleSpecifier(sourceFile, node); resolution != nil {"},
  {"line":1339,"text":"\t\tverifiedFileName := resolution.ResolvedFileName"},
  {"line":1340,"text":"\t\tfileName := resolution.ResolvedFileName"},
  {"line":1341,"text":"\t\tif fileName == \"\" {"},
  {"line":1342,"text":"\t\t\tfileName = tspath.ResolvePath(tspath.GetDirectoryPath(sourceFile.FileName()), node.Text())"},
  {"line":1343,"text":"\t\t}"},
  {"line":1344,"text":"\t\treturn &refInfo{"},
  {"line":1345,"text":"\t\t\tfile:       program.GetSourceFile(fileName),"},
  {"line":1346,"text":"\t\t\tfileName:   fileName,"},
  {"line":1347,"text":"\t\t\treference:  nil,"},
  {"line":1348,"text":"\t\t\tunverified: verifiedFileName != \"\","},
  {"line":1349,"text":"\t\t}"},
  {"line":1350,"text":"\t}"},
  {"line":1352,"text":"\treturn nil"},
  {"line":1353,"text":"}"},
  {"line":1355,"text":"func getContextualTypeFromParent(node *ast.Expression, typeChecker *checker.Checker, contextFlags checker.ContextFlags) *checker.Type {"},
  {"line":1356,"text":"\tparent := ast.WalkUpParenthesizedExpressions(node.Parent)"},
  {"line":1357,"text":"\tswitch parent.Kind {"},
  {"line":1358,"text":"\tcase ast.KindNewExpression:"},
  {"line":1359,"text":"\t\treturn typeChecker.GetContextualType(parent, contextFlags)"},
  {"line":1360,"text":"\tcase ast.KindBinaryExpression:"},
  {"line":1361,"text":"\t\tif isEqualityOperatorKind(parent.AsBinaryExpression().OperatorToken.Kind) {"},
  {"line":1362,"text":"\t\t\treturn typeChecker.GetTypeAtLocation("},
  {"line":1363,"text":"\t\t\t\tcore.IfElse(node == parent.AsBinaryExpression().Right, parent.AsBinaryExpression().Left, parent.AsBinaryExpression().Right))"},
  {"line":1364,"text":"\t\t}"},
  {"line":1365,"text":"\t\treturn typeChecker.GetContextualType(node, contextFlags)"},
  {"line":1366,"text":"\tcase ast.KindCaseClause:"},
  {"line":1367,"text":"\t\treturn getSwitchedType(parent, typeChecker)"},
  {"line":1368,"text":"\tdefault:"},
  {"line":1369,"text":"\t\treturn typeChecker.GetContextualType(node, contextFlags)"},
  {"line":1370,"text":"\t}"},
  {"line":1371,"text":"}"},
  {"line":1373,"text":"func getContextualTypeFromParentOrAncestorTypeNode(node *ast.Expression, typeChecker *checker.Checker) *checker.Type {"},
  {"line":1374,"text":"\tif node.Flags&ast.NodeFlagsJSDoc != 0 && node.Flags&ast.NodeFlagsJavaScriptFile == 0 {"},
  {"line":1375,"text":"\t\treturn nil"},
  {"line":1376,"text":"\t}"},
  {"line":1378,"text":"\tcontextualType := getContextualTypeFromParent(node, typeChecker, checker.ContextFlagsNone)"},
  {"line":1379,"text":"\tif contextualType != nil {"},
  {"line":1380,"text":"\t\treturn contextualType"},
  {"line":1381,"text":"\t}"},
  {"line":1383,"text":"\tif ancestorTypeNode := getAncestorTypeNode(node); ancestorTypeNode != nil {"},
  {"line":1384,"text":"\t\treturn typeChecker.GetTypeAtLocation(ancestorTypeNode)"},
  {"line":1385,"text":"\t}"},
  {"line":1387,"text":"\treturn nil"},
  {"line":1388,"text":"}"},
  {"line":1390,"text":"func getAncestorTypeNode(node *ast.Node) *ast.Node {"},
  {"line":1391,"text":"\tvar lastTypeNode *ast.TypeNode"},
  {"line":1392,"text":"\tast.FindAncestor(node, func(n *ast.Node) bool {"},
  {"line":1393,"text":"\t\tif ast.IsTypeNode(n) {"},
  {"line":1394,"text":"\t\t\tlastTypeNode = n"},
  {"line":1395,"text":"\t\t}"},
  {"line":1396,"text":"\t\treturn !ast.IsQualifiedName(n.Parent) && !ast.IsTypeNode(n.Parent) && !ast.IsTypeElement(n.Parent)"},
  {"line":1397,"text":"\t})"},
  {"line":1398,"text":"\treturn lastTypeNode"},
  {"line":1399,"text":"}"},
  {"line":1401,"text":"func isSourceFileWithGlobalExports(node *ast.Node) bool {"},
  {"line":1402,"text":"\treturn node != nil && ast.IsSourceFile(node) && node.AsSourceFile().GlobalExports != nil"},
  {"line":1403,"text":"}"},
];

export function findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesDeclaration(name: string): UpstreamDeclaration | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesDeclarations.find((declaration) => declaration.name === name);
}

export function requireHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesDeclaration(name: string): UpstreamDeclaration {
  const declaration = findHomeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesDeclaration(name);
  if (declaration === undefined) throw new Error(`Missing upstream declaration: ${name}`);
  return declaration;
}

export function homeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesLineText(line: number): string | undefined {
  return homeJeswinReposTsoniclangTstsPackagesTstsSrcLsUtilitiesSourceLines.find((entry) => entry.line === line)?.text;
}
