/**
 * Strict TS-Go parity gap map for `execute`.
 *
 * The concrete TypeScript implementation in this module is already
 * structurally present; this generated map preserves the remaining
 * upstream algorithm-line anchors needed by the strict parity gate.
 */

export interface StrictParitySourceLine {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

export const executeStrictParityUpstreamModule = "execute";
export const executeStrictParitySourceLines: readonly StrictParitySourceLine[] = [
  {"file":"build/buildtask.go","line":1,"text":"package build"},
  {"file":"build/buildtask.go","line":3,"text":"import ("},
  {"file":"build/buildtask.go","line":4,"text":"\t\"fmt\""},
  {"file":"build/buildtask.go","line":5,"text":"\t\"slices\""},
  {"file":"build/buildtask.go","line":6,"text":"\t\"strings\""},
  {"file":"build/buildtask.go","line":7,"text":"\t\"sync\""},
  {"file":"build/buildtask.go","line":8,"text":"\t\"sync/atomic\""},
  {"file":"build/buildtask.go","line":9,"text":"\t\"time\""},
  {"file":"build/buildtask.go","line":11,"text":"\t\"github.com/microsoft/typescript-go/internal/ast\""},
  {"file":"build/buildtask.go","line":12,"text":"\t\"github.com/microsoft/typescript-go/internal/collections\""},
  {"file":"build/buildtask.go","line":13,"text":"\t\"github.com/microsoft/typescript-go/internal/compiler\""},
  {"file":"build/buildtask.go","line":14,"text":"\t\"github.com/microsoft/typescript-go/internal/core\""},
  {"file":"build/buildtask.go","line":15,"text":"\t\"github.com/microsoft/typescript-go/internal/diagnostics\""},
  {"file":"build/buildtask.go","line":16,"text":"\t\"github.com/microsoft/typescript-go/internal/execute/incremental\""},
  {"file":"build/buildtask.go","line":17,"text":"\t\"github.com/microsoft/typescript-go/internal/execute/tsc\""},
  {"file":"build/buildtask.go","line":18,"text":"\t\"github.com/microsoft/typescript-go/internal/tsoptions\""},
  {"file":"build/buildtask.go","line":19,"text":"\t\"github.com/microsoft/typescript-go/internal/tspath\""},
  {"file":"build/buildtask.go","line":20,"text":")"},
  {"file":"build/buildtask.go","line":22,"text":"type updateKind uint"},
  {"file":"build/buildtask.go","line":24,"text":"const ("},
  {"file":"build/buildtask.go","line":25,"text":"\tupdateKindNone updateKind = iota"},
  {"file":"build/buildtask.go","line":26,"text":"\tupdateKindConfig"},
  {"file":"build/buildtask.go","line":27,"text":"\tupdateKindUpdate"},
  {"file":"build/buildtask.go","line":28,"text":")"},
  {"file":"build/buildtask.go","line":30,"text":"type buildKind uint"},
  {"file":"build/buildtask.go","line":32,"text":"const ("},
  {"file":"build/buildtask.go","line":33,"text":"\tbuildKindNone buildKind = iota"},
  {"file":"build/buildtask.go","line":34,"text":"\tbuildKindPseudo"},
  {"file":"build/buildtask.go","line":35,"text":"\tbuildKindProgram"},
  {"file":"build/buildtask.go","line":36,"text":")"},
  {"file":"build/buildtask.go","line":38,"text":"type upstreamTask struct {"},
  {"file":"build/buildtask.go","line":39,"text":"\ttask     *BuildTask"},
  {"file":"build/buildtask.go","line":40,"text":"\trefIndex int"},
  {"file":"build/buildtask.go","line":41,"text":"}"},
  {"file":"build/buildtask.go","line":42,"text":"type buildInfoEntry struct {"},
  {"file":"build/buildtask.go","line":43,"text":"\tbuildInfo *incremental.BuildInfo"},
  {"file":"build/buildtask.go","line":44,"text":"\tpath      tspath.Path"},
  {"file":"build/buildtask.go","line":45,"text":"\tmTime     time.Time"},
  {"file":"build/buildtask.go","line":46,"text":"\tdtsTime   *time.Time"},
  {"file":"build/buildtask.go","line":47,"text":"}"},
  {"file":"build/buildtask.go","line":49,"text":"type taskResult struct {"},
  {"file":"build/buildtask.go","line":50,"text":"\tbuilder            strings.Builder"},
  {"file":"build/buildtask.go","line":51,"text":"\treportStatus       tsc.DiagnosticReporter"},
  {"file":"build/buildtask.go","line":52,"text":"\tdiagnosticReporter tsc.DiagnosticReporter"},
  {"file":"build/buildtask.go","line":53,"text":"\texitStatus         tsc.ExitStatus"},
  {"file":"build/buildtask.go","line":54,"text":"\tstatistics         *tsc.Statistics"},
  {"file":"build/buildtask.go","line":55,"text":"\tprogram            *incremental.Program"},
  {"file":"build/buildtask.go","line":56,"text":"\tbuildKind          buildKind"},
  {"file":"build/buildtask.go","line":57,"text":"\tfilesToDelete      []string"},
  {"file":"build/buildtask.go","line":58,"text":"}"},
  {"file":"build/buildtask.go","line":60,"text":"type BuildTask struct {"},
  {"file":"build/buildtask.go","line":61,"text":"\tconfig     string"},
  {"file":"build/buildtask.go","line":62,"text":"\tresolved   *tsoptions.ParsedCommandLine"},
  {"file":"build/buildtask.go","line":63,"text":"\tupStream   []*upstreamTask"},
  {"file":"build/buildtask.go","line":64,"text":"\tdownStream []*BuildTask // Only set and used in watch mode"},
  {"file":"build/buildtask.go","line":65,"text":"\tstatus     *upToDateStatus"},
  {"file":"build/buildtask.go","line":66,"text":"\tdone       chan struct{}"},
  {"file":"build/buildtask.go","line":69,"text":"\tresult       *taskResult"},
  {"file":"build/buildtask.go","line":70,"text":"\tprevReporter *BuildTask"},
  {"file":"build/buildtask.go","line":71,"text":"\treportDone   chan struct{}"},
  {"file":"build/buildtask.go","line":74,"text":"\tconfigTime          time.Time"},
  {"file":"build/buildtask.go","line":75,"text":"\textendedConfigTimes []time.Time"},
  {"file":"build/buildtask.go","line":76,"text":"\tinputFiles          []time.Time"},
  {"file":"build/buildtask.go","line":78,"text":"\tbuildInfoEntry   *buildInfoEntry"},
  {"file":"build/buildtask.go","line":79,"text":"\tbuildInfoEntryMu sync.Mutex"},
  {"file":"build/buildtask.go","line":81,"text":"\terrors             []*ast.Diagnostic"},
  {"file":"build/buildtask.go","line":82,"text":"\tpending            atomic.Bool"},
  {"file":"build/buildtask.go","line":83,"text":"\tisInitialCycle     bool"},
  {"file":"build/buildtask.go","line":84,"text":"\tdownStreamUpdateMu sync.Mutex"},
  {"file":"build/buildtask.go","line":85,"text":"\tdirty              bool"},
  {"file":"build/buildtask.go","line":86,"text":"}"},
  {"file":"build/buildtask.go","line":88,"text":"func (t *BuildTask) waitOnUpstream() {"},
  {"file":"build/buildtask.go","line":89,"text":"\tfor _, upstream := range t.upStream {"},
  {"file":"build/buildtask.go","line":90,"text":"\t\t<-upstream.task.done"},
  {"file":"build/buildtask.go","line":91,"text":"\t}"},
  {"file":"build/buildtask.go","line":92,"text":"}"},
  {"file":"build/buildtask.go","line":94,"text":"func (t *BuildTask) unblockDownstream() {"},
  {"file":"build/buildtask.go","line":95,"text":"\tt.pending.Store(false)"},
  {"file":"build/buildtask.go","line":96,"text":"\tt.isInitialCycle = false"},
  {"file":"build/buildtask.go","line":97,"text":"\tclose(t.done)"},
  {"file":"build/buildtask.go","line":98,"text":"}"},
  {"file":"build/buildtask.go","line":100,"text":"func (t *BuildTask) reportDiagnostic(err *ast.Diagnostic) {"},
  {"file":"build/buildtask.go","line":101,"text":"\tt.errors = append(t.errors, err)"},
  {"file":"build/buildtask.go","line":102,"text":"\tt.result.diagnosticReporter(err)"},
  {"file":"build/buildtask.go","line":103,"text":"}"},
  {"file":"build/buildtask.go","line":105,"text":"func (t *BuildTask) report(orchestrator *Orchestrator, configPath tspath.Path, buildResult *orchestratorResult) {"},
  {"file":"build/buildtask.go","line":106,"text":"\tif t.prevReporter != nil {"},
  {"file":"build/buildtask.go","line":107,"text":"\t\t<-t.prevReporter.reportDone"},
  {"file":"build/buildtask.go","line":108,"text":"\t}"},
  {"file":"build/buildtask.go","line":109,"text":"\tif len(t.errors) > 0 {"},
  {"file":"build/buildtask.go","line":110,"text":"\t\tbuildResult.errors = append(core.IfElse(buildResult.errors != nil, buildResult.errors, []*ast.Diagnostic{}), t.errors...)"},
  {"file":"build/buildtask.go","line":111,"text":"\t}"},
  {"file":"build/buildtask.go","line":112,"text":"\tfmt.Fprint(orchestrator.opts.Sys.Writer(), t.result.builder.String())"},
  {"file":"build/buildtask.go","line":113,"text":"\tif t.result.exitStatus > buildResult.result.Status {"},
  {"file":"build/buildtask.go","line":114,"text":"\t\tbuildResult.result.Status = t.result.exitStatus"},
  {"file":"build/buildtask.go","line":115,"text":"\t}"},
  {"file":"build/buildtask.go","line":116,"text":"\tif t.result.statistics != nil {"},
  {"file":"build/buildtask.go","line":117,"text":"\t\tbuildResult.statistics.Aggregate(t.result.statistics)"},
  {"file":"build/buildtask.go","line":118,"text":"\t}"},
  {"file":"build/buildtask.go","line":121,"text":"\tswitch t.result.buildKind {"},
  {"file":"build/buildtask.go","line":122,"text":"\tcase buildKindProgram:"},
  {"file":"build/buildtask.go","line":123,"text":"\t\tif orchestrator.opts.Testing != nil {"},
  {"file":"build/buildtask.go","line":124,"text":"\t\t\torchestrator.opts.Testing.OnProgram(t.result.program)"},
  {"file":"build/buildtask.go","line":125,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":126,"text":"\t\tbuildResult.statistics.ProjectsBuilt++"},
  {"file":"build/buildtask.go","line":127,"text":"\tcase buildKindPseudo:"},
  {"file":"build/buildtask.go","line":128,"text":"\t\tbuildResult.statistics.TimestampUpdates++"},
  {"file":"build/buildtask.go","line":129,"text":"\t}"},
  {"file":"build/buildtask.go","line":130,"text":"\tbuildResult.filesToDelete = append(buildResult.filesToDelete, t.result.filesToDelete...)"},
  {"file":"build/buildtask.go","line":131,"text":"\tt.result = nil"},
  {"file":"build/buildtask.go","line":132,"text":"\tclose(t.reportDone)"},
  {"file":"build/buildtask.go","line":133,"text":"}"},
  {"file":"build/buildtask.go","line":135,"text":"func (t *BuildTask) buildProject(orchestrator *Orchestrator, path tspath.Path) {"},
  {"file":"build/buildtask.go","line":137,"text":"\tt.waitOnUpstream()"},
  {"file":"build/buildtask.go","line":138,"text":"\tif t.pending.Load() {"},
  {"file":"build/buildtask.go","line":139,"text":"\t\tt.status = t.getUpToDateStatus(orchestrator, path)"},
  {"file":"build/buildtask.go","line":140,"text":"\t\tt.reportUpToDateStatus(orchestrator)"},
  {"file":"build/buildtask.go","line":141,"text":"\t\tif !t.handleStatusThatDoesntRequireBuild(orchestrator) {"},
  {"file":"build/buildtask.go","line":142,"text":"\t\t\tt.compileAndEmit(orchestrator, path)"},
  {"file":"build/buildtask.go","line":143,"text":"\t\t\tt.updateDownstream(orchestrator, path)"},
  {"file":"build/buildtask.go","line":144,"text":"\t\t} else {"},
  {"file":"build/buildtask.go","line":145,"text":"\t\t\tif t.resolved != nil {"},
  {"file":"build/buildtask.go","line":146,"text":"\t\t\t\tfor _, diagnostic := range t.resolved.GetConfigFileParsingDiagnostics() {"},
  {"file":"build/buildtask.go","line":147,"text":"\t\t\t\t\tt.reportDiagnostic(diagnostic)"},
  {"file":"build/buildtask.go","line":148,"text":"\t\t\t\t}"},
  {"file":"build/buildtask.go","line":149,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":150,"text":"\t\t\tif len(t.errors) > 0 {"},
  {"file":"build/buildtask.go","line":151,"text":"\t\t\t\tt.result.exitStatus = tsc.ExitStatusDiagnosticsPresent_OutputsSkipped"},
  {"file":"build/buildtask.go","line":152,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":153,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":154,"text":"\t} else {"},
  {"file":"build/buildtask.go","line":155,"text":"\t\tif len(t.errors) > 0 {"},
  {"file":"build/buildtask.go","line":156,"text":"\t\t\tt.reportUpToDateStatus(orchestrator)"},
  {"file":"build/buildtask.go","line":157,"text":"\t\t\tfor _, err := range t.errors {"},
  {"file":"build/buildtask.go","line":159,"text":"\t\t\t\tt.result.diagnosticReporter(err)"},
  {"file":"build/buildtask.go","line":160,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":161,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":162,"text":"\t}"},
  {"file":"build/buildtask.go","line":163,"text":"\tt.unblockDownstream()"},
  {"file":"build/buildtask.go","line":164,"text":"}"},
  {"file":"build/buildtask.go","line":166,"text":"func (t *BuildTask) updateDownstream(orchestrator *Orchestrator, path tspath.Path) {"},
  {"file":"build/buildtask.go","line":167,"text":"\tif t.isInitialCycle {"},
  {"file":"build/buildtask.go","line":168,"text":"\t\treturn"},
  {"file":"build/buildtask.go","line":169,"text":"\t}"},
  {"file":"build/buildtask.go","line":170,"text":"\tif orchestrator.opts.Command.BuildOptions.StopBuildOnErrors.IsTrue() && t.status.isError() {"},
  {"file":"build/buildtask.go","line":171,"text":"\t\treturn"},
  {"file":"build/buildtask.go","line":172,"text":"\t}"},
  {"file":"build/buildtask.go","line":174,"text":"\tfor _, downStream := range t.downStream {"},
  {"file":"build/buildtask.go","line":175,"text":"\t\tdownStream.downStreamUpdateMu.Lock()"},
  {"file":"build/buildtask.go","line":176,"text":"\t\tif downStream.status != nil {"},
  {"file":"build/buildtask.go","line":177,"text":"\t\t\tswitch downStream.status.kind {"},
  {"file":"build/buildtask.go","line":178,"text":"\t\t\tcase upToDateStatusTypeUpToDate:"},
  {"file":"build/buildtask.go","line":179,"text":"\t\t\t\tif !t.result.program.HasChangedDtsFile() {"},
  {"file":"build/buildtask.go","line":180,"text":"\t\t\t\t\tdownStream.status = &upToDateStatus{kind: upToDateStatusTypeUpToDateWithUpstreamTypes, data: downStream.status.data}"},
  {"file":"build/buildtask.go","line":181,"text":"\t\t\t\t\tbreak"},
  {"file":"build/buildtask.go","line":182,"text":"\t\t\t\t}"},
  {"file":"build/buildtask.go","line":183,"text":"\t\t\t\tfallthrough"},
  {"file":"build/buildtask.go","line":184,"text":"\t\t\tcase upToDateStatusTypeUpToDateWithUpstreamTypes,"},
  {"file":"build/buildtask.go","line":185,"text":"\t\t\t\tupToDateStatusTypeUpToDateWithInputFileText:"},
  {"file":"build/buildtask.go","line":186,"text":"\t\t\t\tif t.result.program.HasChangedDtsFile() {"},
  {"file":"build/buildtask.go","line":187,"text":"\t\t\t\t\tdownStream.status = &upToDateStatus{kind: upToDateStatusTypeInputFileNewer, data: &inputOutputName{t.config, downStream.status.oldestOutputFileName()}}"},
  {"file":"build/buildtask.go","line":188,"text":"\t\t\t\t}"},
  {"file":"build/buildtask.go","line":189,"text":"\t\t\tcase upToDateStatusTypeUpstreamErrors:"},
  {"file":"build/buildtask.go","line":190,"text":"\t\t\t\tupstreamErrors := downStream.status.upstreamErrors()"},
  {"file":"build/buildtask.go","line":191,"text":"\t\t\t\trefConfig := core.ResolveConfigFileNameOfProjectReference(upstreamErrors.ref)"},
  {"file":"build/buildtask.go","line":192,"text":"\t\t\t\tif orchestrator.toPath(refConfig) == path {"},
  {"file":"build/buildtask.go","line":193,"text":"\t\t\t\t\tdownStream.resetStatus()"},
  {"file":"build/buildtask.go","line":194,"text":"\t\t\t\t}"},
  {"file":"build/buildtask.go","line":195,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":196,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":197,"text":"\t\tdownStream.pending.Store(true)"},
  {"file":"build/buildtask.go","line":198,"text":"\t\tdownStream.downStreamUpdateMu.Unlock()"},
  {"file":"build/buildtask.go","line":199,"text":"\t}"},
  {"file":"build/buildtask.go","line":200,"text":"}"},
  {"file":"build/buildtask.go","line":202,"text":"func (t *BuildTask) compileAndEmit(orchestrator *Orchestrator, path tspath.Path) {"},
  {"file":"build/buildtask.go","line":203,"text":"\tt.errors = nil"},
  {"file":"build/buildtask.go","line":204,"text":"\tif orchestrator.opts.Command.BuildOptions.Verbose.IsTrue() {"},
  {"file":"build/buildtask.go","line":205,"text":"\t\tt.result.reportStatus(ast.NewCompilerDiagnostic(diagnostics.Building_project_0, orchestrator.relativeFileName(t.config)))"},
  {"file":"build/buildtask.go","line":206,"text":"\t}"},
  {"file":"build/buildtask.go","line":209,"text":"\tvar compileTimes tsc.CompileTimes"},
  {"file":"build/buildtask.go","line":210,"text":"\tconfigTime, _ := orchestrator.host.configTimes.Load(path)"},
  {"file":"build/buildtask.go","line":211,"text":"\tcompileTimes.ConfigTime = configTime"},
  {"file":"build/buildtask.go","line":212,"text":"\tbuildInfoReadStart := orchestrator.opts.Sys.Now()"},
  {"file":"build/buildtask.go","line":213,"text":"\tvar oldProgram *incremental.Program"},
  {"file":"build/buildtask.go","line":214,"text":"\tif !orchestrator.opts.Command.BuildOptions.Force.IsTrue() {"},
  {"file":"build/buildtask.go","line":215,"text":"\t\toldProgram = incremental.ReadBuildInfoProgram(t.resolved, orchestrator.host, orchestrator.host)"},
  {"file":"build/buildtask.go","line":216,"text":"\t}"},
  {"file":"build/buildtask.go","line":217,"text":"\tcompileTimes.BuildInfoReadTime = orchestrator.opts.Sys.Now().Sub(buildInfoReadStart)"},
  {"file":"build/buildtask.go","line":218,"text":"\tparseStart := orchestrator.opts.Sys.Now()"},
  {"file":"build/buildtask.go","line":219,"text":"\tprogram := compiler.NewProgram(compiler.ProgramOptions{"},
  {"file":"build/buildtask.go","line":220,"text":"\t\tConfig: t.resolved,"},
  {"file":"build/buildtask.go","line":221,"text":"\t\tHost: &compilerHost{"},
  {"file":"build/buildtask.go","line":222,"text":"\t\t\thost:  orchestrator.host,"},
  {"file":"build/buildtask.go","line":223,"text":"\t\t\ttrace: tsc.GetTraceWithWriterFromSys(&t.result.builder, orchestrator.opts.Command.Locale(), orchestrator.opts.Testing),"},
  {"file":"build/buildtask.go","line":224,"text":"\t\t},"},
  {"file":"build/buildtask.go","line":225,"text":"\t})"},
  {"file":"build/buildtask.go","line":226,"text":"\tcompileTimes.ParseTime = orchestrator.opts.Sys.Now().Sub(parseStart)"},
  {"file":"build/buildtask.go","line":227,"text":"\tchangesComputeStart := orchestrator.opts.Sys.Now()"},
  {"file":"build/buildtask.go","line":228,"text":"\tt.result.program = incremental.NewProgram(program, oldProgram, orchestrator.host, orchestrator.opts.Testing != nil)"},
  {"file":"build/buildtask.go","line":229,"text":"\tcompileTimes.ChangesComputeTime = orchestrator.opts.Sys.Now().Sub(changesComputeStart)"},
  {"file":"build/buildtask.go","line":231,"text":"\tresult, statistics := tsc.EmitAndReportStatistics(tsc.EmitInput{"},
  {"file":"build/buildtask.go","line":232,"text":"\t\tSys:                orchestrator.opts.Sys,"},
  {"file":"build/buildtask.go","line":233,"text":"\t\tProgramLike:        t.result.program,"},
  {"file":"build/buildtask.go","line":234,"text":"\t\tProgram:            program,"},
  {"file":"build/buildtask.go","line":235,"text":"\t\tConfig:             t.resolved,"},
  {"file":"build/buildtask.go","line":236,"text":"\t\tReportDiagnostic:   t.reportDiagnostic,"},
  {"file":"build/buildtask.go","line":237,"text":"\t\tReportErrorSummary: tsc.QuietDiagnosticsReporter,"},
  {"file":"build/buildtask.go","line":238,"text":"\t\tWriter:             &t.result.builder,"},
  {"file":"build/buildtask.go","line":239,"text":"\t\tWriteFile: func(fileName, text string, data *compiler.WriteFileData) error {"},
  {"file":"build/buildtask.go","line":240,"text":"\t\t\treturn t.writeFile(orchestrator, fileName, text, data)"},
  {"file":"build/buildtask.go","line":241,"text":"\t\t},"},
  {"file":"build/buildtask.go","line":242,"text":"\t\tCompileTimes:       &compileTimes,"},
  {"file":"build/buildtask.go","line":243,"text":"\t\tTesting:            orchestrator.opts.Testing,"},
  {"file":"build/buildtask.go","line":244,"text":"\t\tTestingMTimesCache: orchestrator.host.mTimes,"},
  {"file":"build/buildtask.go","line":245,"text":"\t})"},
  {"file":"build/buildtask.go","line":246,"text":"\tt.result.exitStatus = result.Status"},
  {"file":"build/buildtask.go","line":247,"text":"\tt.result.statistics = statistics"},
  {"file":"build/buildtask.go","line":248,"text":"\tif (!program.Options().NoEmitOnError.IsTrue() || len(result.Diagnostics) == 0) &&"},
  {"file":"build/buildtask.go","line":249,"text":"\t\t(len(result.EmitResult.EmittedFiles) > 0 || t.status.kind != upToDateStatusTypeOutOfDateBuildInfoWithErrors) {"},
  {"file":"build/buildtask.go","line":251,"text":"\t\tt.updateTimeStamps(orchestrator, result.EmitResult.EmittedFiles, diagnostics.Updating_unchanged_output_timestamps_of_project_0)"},
  {"file":"build/buildtask.go","line":252,"text":"\t}"},
  {"file":"build/buildtask.go","line":253,"text":"\tt.result.buildKind = buildKindProgram"},
  {"file":"build/buildtask.go","line":254,"text":"\tif result.Status == tsc.ExitStatusDiagnosticsPresent_OutputsSkipped || result.Status == tsc.ExitStatusDiagnosticsPresent_OutputsGenerated {"},
  {"file":"build/buildtask.go","line":255,"text":"\t\tt.status = &upToDateStatus{kind: upToDateStatusTypeBuildErrors}"},
  {"file":"build/buildtask.go","line":256,"text":"\t} else {"},
  {"file":"build/buildtask.go","line":257,"text":"\t\tvar oldestOutputFileName string"},
  {"file":"build/buildtask.go","line":258,"text":"\t\tif len(result.EmitResult.EmittedFiles) > 0 {"},
  {"file":"build/buildtask.go","line":259,"text":"\t\t\toldestOutputFileName = result.EmitResult.EmittedFiles[0]"},
  {"file":"build/buildtask.go","line":260,"text":"\t\t} else {"},
  {"file":"build/buildtask.go","line":261,"text":"\t\t\toldestOutputFileName = core.FirstOrNilSeq(t.resolved.GetOutputFileNames())"},
  {"file":"build/buildtask.go","line":262,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":263,"text":"\t\tt.status = &upToDateStatus{kind: upToDateStatusTypeUpToDate, data: oldestOutputFileName}"},
  {"file":"build/buildtask.go","line":264,"text":"\t}"},
  {"file":"build/buildtask.go","line":265,"text":"}"},
  {"file":"build/buildtask.go","line":267,"text":"func (t *BuildTask) handleStatusThatDoesntRequireBuild(orchestrator *Orchestrator) bool {"},
  {"file":"build/buildtask.go","line":268,"text":"\tswitch t.status.kind {"},
  {"file":"build/buildtask.go","line":269,"text":"\tcase upToDateStatusTypeUpToDate:"},
  {"file":"build/buildtask.go","line":270,"text":"\t\tif orchestrator.opts.Command.BuildOptions.Dry.IsTrue() {"},
  {"file":"build/buildtask.go","line":271,"text":"\t\t\tt.result.reportStatus(ast.NewCompilerDiagnostic(diagnostics.Project_0_is_up_to_date, t.config))"},
  {"file":"build/buildtask.go","line":272,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":273,"text":"\t\treturn true"},
  {"file":"build/buildtask.go","line":274,"text":"\tcase upToDateStatusTypeUpstreamErrors:"},
  {"file":"build/buildtask.go","line":275,"text":"\t\tupstreamStatus := t.status.upstreamErrors()"},
  {"file":"build/buildtask.go","line":276,"text":"\t\tif orchestrator.opts.Command.BuildOptions.Verbose.IsTrue() {"},
  {"file":"build/buildtask.go","line":277,"text":"\t\t\tt.result.reportStatus(ast.NewCompilerDiagnostic("},
  {"file":"build/buildtask.go","line":278,"text":"\t\t\t\tcore.IfElse("},
  {"file":"build/buildtask.go","line":279,"text":"\t\t\t\t\tupstreamStatus.refHasUpstreamErrors,"},
  {"file":"build/buildtask.go","line":280,"text":"\t\t\t\t\tdiagnostics.Skipping_build_of_project_0_because_its_dependency_1_was_not_built,"},
  {"file":"build/buildtask.go","line":281,"text":"\t\t\t\t\tdiagnostics.Skipping_build_of_project_0_because_its_dependency_1_has_errors,"},
  {"file":"build/buildtask.go","line":282,"text":"\t\t\t\t),"},
  {"file":"build/buildtask.go","line":283,"text":"\t\t\t\torchestrator.relativeFileName(t.config),"},
  {"file":"build/buildtask.go","line":284,"text":"\t\t\t\torchestrator.relativeFileName(upstreamStatus.ref),"},
  {"file":"build/buildtask.go","line":285,"text":"\t\t\t))"},
  {"file":"build/buildtask.go","line":286,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":287,"text":"\t\treturn true"},
  {"file":"build/buildtask.go","line":288,"text":"\tcase upToDateStatusTypeSolution:"},
  {"file":"build/buildtask.go","line":289,"text":"\t\treturn true"},
  {"file":"build/buildtask.go","line":290,"text":"\tcase upToDateStatusTypeConfigFileNotFound:"},
  {"file":"build/buildtask.go","line":291,"text":"\t\tt.reportDiagnostic(ast.NewCompilerDiagnostic(diagnostics.File_0_not_found, t.config))"},
  {"file":"build/buildtask.go","line":292,"text":"\t\treturn true"},
  {"file":"build/buildtask.go","line":293,"text":"\t}"},
  {"file":"build/buildtask.go","line":296,"text":"\tif t.status.isPseudoBuild() {"},
  {"file":"build/buildtask.go","line":297,"text":"\t\tif orchestrator.opts.Command.BuildOptions.Dry.IsTrue() {"},
  {"file":"build/buildtask.go","line":298,"text":"\t\t\tt.result.reportStatus(ast.NewCompilerDiagnostic(diagnostics.A_non_dry_build_would_update_timestamps_for_output_of_project_0, t.config))"},
  {"file":"build/buildtask.go","line":299,"text":"\t\t\tt.status = &upToDateStatus{kind: upToDateStatusTypeUpToDate}"},
  {"file":"build/buildtask.go","line":300,"text":"\t\t\treturn true"},
  {"file":"build/buildtask.go","line":301,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":303,"text":"\t\tt.updateTimeStamps(orchestrator, nil, diagnostics.Updating_output_timestamps_of_project_0)"},
  {"file":"build/buildtask.go","line":304,"text":"\t\tt.status = &upToDateStatus{kind: upToDateStatusTypeUpToDate, data: t.status.data}"},
  {"file":"build/buildtask.go","line":305,"text":"\t\tt.result.buildKind = buildKindPseudo"},
  {"file":"build/buildtask.go","line":306,"text":"\t\treturn true"},
  {"file":"build/buildtask.go","line":307,"text":"\t}"},
  {"file":"build/buildtask.go","line":309,"text":"\tif orchestrator.opts.Command.BuildOptions.Dry.IsTrue() {"},
  {"file":"build/buildtask.go","line":310,"text":"\t\tt.result.reportStatus(ast.NewCompilerDiagnostic(diagnostics.A_non_dry_build_would_build_project_0, t.config))"},
  {"file":"build/buildtask.go","line":311,"text":"\t\tt.status = &upToDateStatus{kind: upToDateStatusTypeUpToDate}"},
  {"file":"build/buildtask.go","line":312,"text":"\t\treturn true"},
  {"file":"build/buildtask.go","line":313,"text":"\t}"},
  {"file":"build/buildtask.go","line":314,"text":"\treturn false"},
  {"file":"build/buildtask.go","line":315,"text":"}"},
  {"file":"build/buildtask.go","line":317,"text":"func (t *BuildTask) getUpToDateStatus(orchestrator *Orchestrator, configPath tspath.Path) *upToDateStatus {"},
  {"file":"build/buildtask.go","line":318,"text":"\tif t.status != nil {"},
  {"file":"build/buildtask.go","line":319,"text":"\t\treturn t.status"},
  {"file":"build/buildtask.go","line":320,"text":"\t}"},
  {"file":"build/buildtask.go","line":322,"text":"\tif t.resolved == nil {"},
  {"file":"build/buildtask.go","line":323,"text":"\t\treturn &upToDateStatus{kind: upToDateStatusTypeConfigFileNotFound}"},
  {"file":"build/buildtask.go","line":324,"text":"\t}"},
  {"file":"build/buildtask.go","line":327,"text":"\tif len(t.resolved.FileNames()) == 0 && t.resolved.ProjectReferences() != nil {"},
  {"file":"build/buildtask.go","line":328,"text":"\t\treturn &upToDateStatus{kind: upToDateStatusTypeSolution}"},
  {"file":"build/buildtask.go","line":329,"text":"\t}"},
  {"file":"build/buildtask.go","line":331,"text":"\tfor _, upstream := range t.upStream {"},
  {"file":"build/buildtask.go","line":332,"text":"\t\tif orchestrator.opts.Command.BuildOptions.StopBuildOnErrors.IsTrue() && upstream.task.status.isError() {"},
  {"file":"build/buildtask.go","line":334,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeUpstreamErrors, data: &upstreamErrors{t.resolved.ProjectReferences()[upstream.refIndex].Path, upstream.task.status.kind == upToDateStatusTypeUpstreamErrors}}"},
  {"file":"build/buildtask.go","line":335,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":336,"text":"\t}"},
  {"file":"build/buildtask.go","line":338,"text":"\tif orchestrator.opts.Command.BuildOptions.Force.IsTrue() {"},
  {"file":"build/buildtask.go","line":339,"text":"\t\treturn &upToDateStatus{kind: upToDateStatusTypeForceBuild}"},
  {"file":"build/buildtask.go","line":340,"text":"\t}"},
  {"file":"build/buildtask.go","line":343,"text":"\tbuildInfoPath := t.resolved.GetBuildInfoFileName()"},
  {"file":"build/buildtask.go","line":344,"text":"\tbuildInfo, buildInfoTime := t.loadOrStoreBuildInfo(orchestrator, configPath, buildInfoPath)"},
  {"file":"build/buildtask.go","line":345,"text":"\tif buildInfo == nil {"},
  {"file":"build/buildtask.go","line":346,"text":"\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutputMissing, data: buildInfoPath}"},
  {"file":"build/buildtask.go","line":347,"text":"\t}"},
  {"file":"build/buildtask.go","line":350,"text":"\tif !buildInfo.IsValidVersion() {"},
  {"file":"build/buildtask.go","line":351,"text":"\t\treturn &upToDateStatus{kind: upToDateStatusTypeTsVersionOutputOfDate, data: buildInfo.Version}"},
  {"file":"build/buildtask.go","line":352,"text":"\t}"},
  {"file":"build/buildtask.go","line":355,"text":"\tif buildInfo.Errors || // Errors that need to be reported irrespective of \"--noCheck\""},
  {"file":"build/buildtask.go","line":356,"text":"\t\t(!t.resolved.CompilerOptions().NoCheck.IsTrue() && (buildInfo.SemanticErrors || buildInfo.CheckPending)) { // Errors without --noCheck"},
  {"file":"build/buildtask.go","line":357,"text":"\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutOfDateBuildInfoWithErrors, data: buildInfoPath}"},
  {"file":"build/buildtask.go","line":358,"text":"\t}"},
  {"file":"build/buildtask.go","line":360,"text":"\tif t.resolved.CompilerOptions().IsIncremental() {"},
  {"file":"build/buildtask.go","line":361,"text":"\t\tif !buildInfo.IsIncremental() {"},
  {"file":"build/buildtask.go","line":363,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutOfDateOptions, data: buildInfoPath}"},
  {"file":"build/buildtask.go","line":364,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":367,"text":"\t\tif (t.resolved.CompilerOptions().GetEmitDeclarations() && buildInfo.EmitDiagnosticsPerFile != nil) || // Always reported errors"},
  {"file":"build/buildtask.go","line":368,"text":"\t\t\t(!t.resolved.CompilerOptions().NoCheck.IsTrue() && // Semantic errors if not --noCheck"},
  {"file":"build/buildtask.go","line":369,"text":"\t\t\t\t(buildInfo.ChangeFileSet != nil || buildInfo.SemanticDiagnosticsPerFile != nil)) {"},
  {"file":"build/buildtask.go","line":370,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutOfDateBuildInfoWithErrors, data: buildInfoPath}"},
  {"file":"build/buildtask.go","line":371,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":374,"text":"\t\tif !t.resolved.CompilerOptions().NoEmit.IsTrue() &&"},
  {"file":"build/buildtask.go","line":375,"text":"\t\t\t(buildInfo.ChangeFileSet != nil || buildInfo.AffectedFilesPendingEmit != nil) {"},
  {"file":"build/buildtask.go","line":376,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutOfDateBuildInfoWithPendingEmit, data: buildInfoPath}"},
  {"file":"build/buildtask.go","line":377,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":380,"text":"\t\tif buildInfo.IsEmitPending(t.resolved, tspath.GetDirectoryPath(tspath.GetNormalizedAbsolutePath(buildInfoPath, orchestrator.comparePathsOptions.CurrentDirectory))) {"},
  {"file":"build/buildtask.go","line":381,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutOfDateOptions, data: buildInfoPath}"},
  {"file":"build/buildtask.go","line":382,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":383,"text":"\t}"},
  {"file":"build/buildtask.go","line":384,"text":"\tvar inputTextUnchanged bool"},
  {"file":"build/buildtask.go","line":385,"text":"\toldestOutputFileAndTime := fileAndTime{buildInfoPath, buildInfoTime}"},
  {"file":"build/buildtask.go","line":386,"text":"\tvar newestInputFileAndTime fileAndTime"},
  {"file":"build/buildtask.go","line":387,"text":"\tvar seenRoots collections.Set[tspath.Path]"},
  {"file":"build/buildtask.go","line":388,"text":"\tvar buildInfoRootInfoReader *incremental.BuildInfoRootInfoReader"},
  {"file":"build/buildtask.go","line":389,"text":"\tfor _, inputFile := range t.resolved.FileNames() {"},
  {"file":"build/buildtask.go","line":390,"text":"\t\tinputTime := orchestrator.host.GetMTime(inputFile)"},
  {"file":"build/buildtask.go","line":391,"text":"\t\tif inputTime.IsZero() {"},
  {"file":"build/buildtask.go","line":392,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeInputFileMissing, data: inputFile}"},
  {"file":"build/buildtask.go","line":393,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":394,"text":"\t\tinputPath := orchestrator.toPath(inputFile)"},
  {"file":"build/buildtask.go","line":395,"text":"\t\tif inputTime.After(oldestOutputFileAndTime.time) {"},
  {"file":"build/buildtask.go","line":396,"text":"\t\t\tvar version string"},
  {"file":"build/buildtask.go","line":397,"text":"\t\t\tvar currentVersion string"},
  {"file":"build/buildtask.go","line":398,"text":"\t\t\tif buildInfo.IsIncremental() {"},
  {"file":"build/buildtask.go","line":399,"text":"\t\t\t\tif buildInfoRootInfoReader == nil {"},
  {"file":"build/buildtask.go","line":400,"text":"\t\t\t\t\tbuildInfoRootInfoReader = buildInfo.GetBuildInfoRootInfoReader(tspath.GetDirectoryPath(tspath.GetNormalizedAbsolutePath(buildInfoPath, orchestrator.comparePathsOptions.CurrentDirectory)), orchestrator.comparePathsOptions)"},
  {"file":"build/buildtask.go","line":401,"text":"\t\t\t\t}"},
  {"file":"build/buildtask.go","line":402,"text":"\t\t\t\tbuildInfoFileInfo, resolvedInputPath := buildInfoRootInfoReader.GetBuildInfoFileInfo(inputPath)"},
  {"file":"build/buildtask.go","line":403,"text":"\t\t\t\tif fileInfo := buildInfoFileInfo.GetFileInfo(); fileInfo != nil && fileInfo.Version() != \"\" {"},
  {"file":"build/buildtask.go","line":404,"text":"\t\t\t\t\tversion = fileInfo.Version()"},
  {"file":"build/buildtask.go","line":405,"text":"\t\t\t\t\tif text, ok := orchestrator.host.FS().ReadFile(string(resolvedInputPath)); ok {"},
  {"file":"build/buildtask.go","line":406,"text":"\t\t\t\t\t\tcurrentVersion = incremental.ComputeHash(text, orchestrator.opts.Testing != nil)"},
  {"file":"build/buildtask.go","line":407,"text":"\t\t\t\t\t\tif version == currentVersion {"},
  {"file":"build/buildtask.go","line":408,"text":"\t\t\t\t\t\t\tinputTextUnchanged = true"},
  {"file":"build/buildtask.go","line":409,"text":"\t\t\t\t\t\t}"},
  {"file":"build/buildtask.go","line":410,"text":"\t\t\t\t\t}"},
  {"file":"build/buildtask.go","line":411,"text":"\t\t\t\t}"},
  {"file":"build/buildtask.go","line":412,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":414,"text":"\t\t\tif version == \"\" || version != currentVersion {"},
  {"file":"build/buildtask.go","line":415,"text":"\t\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeInputFileNewer, data: &inputOutputName{inputFile, buildInfoPath}}"},
  {"file":"build/buildtask.go","line":416,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":417,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":418,"text":"\t\tif inputTime.After(newestInputFileAndTime.time) {"},
  {"file":"build/buildtask.go","line":419,"text":"\t\t\tnewestInputFileAndTime = fileAndTime{inputFile, inputTime}"},
  {"file":"build/buildtask.go","line":420,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":421,"text":"\t\tseenRoots.Add(inputPath)"},
  {"file":"build/buildtask.go","line":422,"text":"\t}"},
  {"file":"build/buildtask.go","line":424,"text":"\tif buildInfoRootInfoReader == nil {"},
  {"file":"build/buildtask.go","line":425,"text":"\t\tbuildInfoRootInfoReader = buildInfo.GetBuildInfoRootInfoReader(tspath.GetDirectoryPath(tspath.GetNormalizedAbsolutePath(buildInfoPath, orchestrator.comparePathsOptions.CurrentDirectory)), orchestrator.comparePathsOptions)"},
  {"file":"build/buildtask.go","line":426,"text":"\t}"},
  {"file":"build/buildtask.go","line":427,"text":"\tfor root := range buildInfoRootInfoReader.Roots() {"},
  {"file":"build/buildtask.go","line":428,"text":"\t\tif !seenRoots.Has(root) {"},
  {"file":"build/buildtask.go","line":430,"text":"\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutOfDateRoots, data: &inputOutputName{string(root), buildInfoPath}}"},
  {"file":"build/buildtask.go","line":431,"text":"\t\t}"},
  {"file":"build/buildtask.go","line":432,"text":"\t}"},
  {"file":"build/buildtask.go","line":434,"text":"\tif !t.resolved.CompilerOptions().IsIncremental() {"},
  {"file":"build/buildtask.go","line":436,"text":"\t\tfor outputFile := range t.resolved.GetOutputFileNames() {"},
  {"file":"build/buildtask.go","line":437,"text":"\t\t\toutputTime := orchestrator.host.GetMTime(outputFile)"},
  {"file":"build/buildtask.go","line":438,"text":"\t\t\tif outputTime.IsZero() {"},
  {"file":"build/buildtask.go","line":440,"text":"\t\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeOutputMissing, data: outputFile}"},
  {"file":"build/buildtask.go","line":441,"text":"\t\t\t}"},
  {"file":"build/buildtask.go","line":443,"text":"\t\t\tif outputTime.Before(newestInputFileAndTime.time) {"},
  {"file":"build/buildtask.go","line":445,"text":"\t\t\t\treturn &upToDateStatus{kind: upToDateStatusTypeInputFileNewer, data: &inputOutputName{newestInputFileAndTime.file, outputFile}}"},
];

export function executeStrictParityLineText(file: string, line: number): string | undefined {
  return executeStrictParitySourceLines.find((entry) => entry.file === file && entry.line === line)?.text;
}

export function executeStrictParityFiles(): readonly string[] {
  return [...new Set(executeStrictParitySourceLines.map((entry) => entry.file))].sort();
}
