import { normalizeKinds, readAstSchema, type AstSchema, type MemberDefinition, type NodeDefinition } from "./schema.js";
import { stableJson, writeGenerated } from "./common.js";

type KindAliasDefinition = readonly string[] | { readonly range: readonly [string, string] };

function header(fileName: string): string {
  return [
    "// Code generated by tools/generateApiEncoder.ts. DO NOT EDIT.",
    "// Source: schema/tsgo/ast.json",
    `// Mirrors TS-Go internal/api/encoder/${fileName}.go.`,
    "",
  ].join("\n");
}

function isReadonlyArray<T>(value: T | readonly T[]): value is readonly T[] {
  return Array.isArray(value);
}

function isRangeKindAlias(value: KindAliasDefinition): value is { readonly range: readonly [string, string] } {
  return !Array.isArray(value);
}

function enumMemberName(name: string): string {
  const kindName = name.startsWith("SyntaxKind.") ? name.slice("SyntaxKind.".length) : name;
  if (!/^[$A-Z_a-z][$\w]*$/.test(kindName)) {
    throw new Error(`Invalid Kind name ${kindName}`);
  }
  return kindName;
}

function lowerFirst(name: string): string {
  return `${name.slice(0, 1).toLowerCase()}${name.slice(1)}`;
}

function concreteKindNames(schema: AstSchema): Set<string> {
  return new Set(normalizeKinds(schema).map((kind) => kind.name));
}

function expandKindAlias(schema: AstSchema, value: KindAliasDefinition): string[] {
  const kinds = normalizeKinds(schema).map((kind) => kind.name);
  const markerValues = new Map(schema.kinds.markers.map((marker) => [marker.name, marker.value]));
  const resolveMarker = (name: string): string => {
    let current = name;
    const seen = new Set<string>();
    while (markerValues.has(current)) {
      if (seen.has(current)) throw new Error(`Circular kind marker ${name}`);
      seen.add(current);
      current = markerValues.get(current)!;
    }
    return current;
  };
  if (!isRangeKindAlias(value)) {
    return value.flatMap((item) => {
      const nested = schema.kinds.aliases?.[item];
      return nested === undefined ? [item] : expandKindAlias(schema, nested);
    });
  }
  const [startMarker, endMarker] = value.range;
  const start = kinds.indexOf(resolveMarker(startMarker));
  const end = kinds.indexOf(resolveMarker(endMarker));
  if (start < 0 || end < start) throw new Error(`Invalid kind range ${startMarker}..${endMarker}`);
  return kinds.slice(start, end + 1);
}

function findBaseField(schema: AstSchema, baseName: string, fieldName: string, seen = new Set<string>()): MemberDefinition | undefined {
  if (seen.has(baseName)) return undefined;
  seen.add(baseName);
  const base = schema.bases[baseName];
  if (base === undefined) return undefined;
  for (const [name, field] of Object.entries(base.fields ?? {})) {
    if (name === fieldName) return { ...field, name };
  }
  for (const inheritedBase of base.extends ?? []) {
    const field = findBaseField(schema, inheritedBase, fieldName, seen);
    if (field !== undefined) return field;
  }
  return undefined;
}

function resolveInheritedMember(schema: AstSchema, definition: NodeDefinition, member: MemberDefinition): MemberDefinition {
  if (member.type !== undefined || member.inherited !== true) return member;
  for (const baseName of definition.extends) {
    const field = findBaseField(schema, baseName, member.name);
    if (field === undefined) continue;
    if (field.type === undefined) return member;
    const resolved: Record<string, unknown> = {
      ...field,
      ...member,
      type: field.type,
    };
    if (member.list === undefined && field.list !== undefined) resolved["list"] = field.list;
    if (member.optional === undefined && field.optional !== undefined) resolved["optional"] = field.optional;
    if (member.visit === undefined && field.visit !== undefined) resolved["visit"] = field.visit;
    if (member.typeGuard === undefined && field.typeGuard !== undefined) resolved["typeGuard"] = field.typeGuard;
    if (member.noFactory === undefined && field.noFactory !== undefined) resolved["noFactory"] = field.noFactory;
    if (member.noTS === undefined && field.noTS !== undefined) resolved["noTS"] = field.noTS;
    if (member.goOnly === undefined && field.goOnly !== undefined) resolved["goOnly"] = field.goOnly;
    return resolved as unknown as MemberDefinition;
  }
  return member;
}

function runtimeMembers(schema: AstSchema, definition: NodeDefinition): readonly MemberDefinition[] {
  return (definition.members ?? [])
    .map((member) => resolveInheritedMember(schema, definition, member))
    .filter((member) => {
      if (member.name === "Kind" || member.name === "kind") return false;
      if (member.noTS === true || member.goOnly === true || member.noFactory === true) return false;
      return member.type !== undefined;
    });
}

function isNodeTypeName(schema: AstSchema, typeName: string): boolean {
  const normalized = typeName.startsWith("*") ? typeName.slice(1) : typeName;
  if (schema.nodes.definitions[normalized] !== undefined) return true;
  if (schema.nodes.aliases[normalized] !== undefined) return true;
  if (schema.nodes.listAliases?.[normalized] !== undefined) return true;
  return false;
}

function isNodeMember(schema: AstSchema, member: MemberDefinition): boolean {
  if (member.type === undefined) return false;
  if (typeof member.type === "string") return isNodeTypeName(schema, member.type);
  return member.type.some((typeName) => isNodeTypeName(schema, typeName));
}

function kindNamesFromType(schema: AstSchema, type: string | readonly string[] | undefined, definition: NodeDefinition): string[] {
  if (type === undefined) return [];
  if (isReadonlyArray(type)) return type.flatMap((item) => kindNamesFromType(schema, item, definition));
  if (type.startsWith("SyntaxKind.")) return [type.slice("SyntaxKind.".length)];
  const typeParameter = definition.typeParameters?.find((param) => param.name === type);
  if (typeParameter !== undefined) return kindNamesFromType(schema, typeParameter.constraint, definition);
  const kindAlias = schema.kinds.aliases?.[type];
  if (kindAlias !== undefined) return expandKindAlias(schema, kindAlias);
  if (type === "Kind") return normalizeKinds(schema).map((kind) => kind.name);
  if (concreteKindNames(schema).has(type)) return [type];
  return [];
}

function nodeKindCases(schema: AstSchema, name: string, definition: NodeDefinition): readonly string[] {
  const kindMember = definition.members?.find((member) => member.name === "Kind" || member.name === "kind");
  if (kindMember?.type !== undefined) {
    const kindNames = kindNamesFromType(schema, kindMember.type, definition);
    if (kindNames.length > 0) return kindNames;
  }
  const kindValues = isReadonlyArray(definition.kind) ? definition.kind : [definition.kind ?? name];
  return kindValues.map((kindName) => kindName.startsWith("SyntaxKind.") ? kindName.slice("SyntaxKind.".length) : kindName);
}

function dataPropertyName(name: string): string {
  return lowerFirst(name);
}

const STRING_DATA_KINDS = new Set([
  "Identifier",
  "PrivateIdentifier",
  "JsxText",
  "JSDocText",
  "JSDocLink",
  "JSDocLinkPlain",
  "JSDocLinkCode",
]);

const EXTENDED_DATA_KINDS = new Set([
  "StringLiteral",
  "NumericLiteral",
  "BigIntLiteral",
  "RegularExpressionLiteral",
  "NoSubstitutionTemplateLiteral",
  "TemplateHead",
  "TemplateMiddle",
  "TemplateTail",
  "SourceFile",
]);

function buildKindRows(schema: AstSchema): readonly { readonly kind: string; readonly childProperties: readonly string[] }[] {
  const rows: { readonly kind: string; readonly childProperties: readonly string[] }[] = [];
  const seen = new Set<string>();
  for (const [name, definition] of Object.entries(schema.nodes.definitions)) {
    const childProperties = runtimeMembers(schema, definition)
      .filter((member) => isNodeMember(schema, member))
      .map((member) => dataPropertyName(member.name));
    for (const kind of nodeKindCases(schema, name, definition)) {
      if (seen.has(kind)) continue;
      seen.add(kind);
      rows.push({ kind, childProperties });
    }
  }
  return rows;
}

function generateKindArray(name: string, kinds: readonly string[]): readonly string[] {
  const lines: string[] = [`const ${name}: ReadonlySet<Kind> = new Set([`];
  for (const kind of kinds) {
    lines.push(`  Kind.${enumMemberName(kind)},`);
  }
  lines.push("]);");
  return lines;
}

function generateChildPropertyMap(rows: readonly { readonly kind: string; readonly childProperties: readonly string[] }[]): readonly string[] {
  const lines: string[] = ["export const GeneratedChildPropertiesByKind: ReadonlyMap<Kind, readonly string[]> = new Map(["];
  for (const row of rows) {
    lines.push(`  [Kind.${enumMemberName(row.kind)}, ${stableJson(row.childProperties).trim()}],`);
  }
  lines.push("]);");
  return lines;
}

function generateEncoder(schema: AstSchema): string {
  const rows = buildKindRows(schema);
  const lines: string[] = [header("encoder_generated")];
  lines.push("import { Kind, type Node as AstNode, type PositionMap } from \"../../ast/index.js\";");
  lines.push("import type { StringTable } from \"./stringTable.js\";");
  lines.push("");
  lines.push("export const NodeDataTypeChildren = 0x00000000;");
  lines.push("export const NodeDataTypeString = 0x40000000;");
  lines.push("export const NodeDataTypeExtendedData = 0x80000000;");
  lines.push("export const NodeDataTypeMask = 0xc0000000;");
  lines.push("export const NodeDataChildMask = 0x000000ff;");
  lines.push("export const NodeDataStringIndexMask = 0x00ffffff;");
  lines.push("");
  lines.push("export type RecordExtendedDataFunc = (");
  lines.push("  node: AstNode, strs: StringTable, positionMap: PositionMap,");
  lines.push("  extendedData: number[], structuredData: number[],");
  lines.push(") => void;");
  lines.push("");
  lines.push("export type GetCommonDataFunc = (node: AstNode) => number;");
  lines.push("");
  lines.push(...generateKindArray("stringDataKinds", [...STRING_DATA_KINDS]));
  lines.push("");
  lines.push(...generateKindArray("extendedDataKinds", [...EXTENDED_DATA_KINDS]));
  lines.push("");
  lines.push(...generateChildPropertyMap(rows));
  lines.push("");
  lines.push("export function getNodeDataType(node: AstNode): number {");
  lines.push("  if (stringDataKinds.has(node.kind)) return NodeDataTypeString;");
  lines.push("  if (extendedDataKinds.has(node.kind)) return NodeDataTypeExtendedData;");
  lines.push("  return NodeDataTypeChildren;");
  lines.push("}");
  lines.push("");
  lines.push("export function getChildrenPropertyMask(node: AstNode): number {");
  lines.push("  const properties = GeneratedChildPropertiesByKind.get(node.kind) ?? [];");
  lines.push("  const record = node as unknown as Record<string, unknown>;");
  lines.push("  let mask = 0;");
  lines.push("  for (let index = 0; index < properties.length; index += 1) {");
  lines.push("    const value = record[properties[index]!];");
  lines.push("    if (value !== undefined && value !== null) mask |= 1 << index;");
  lines.push("  }");
  lines.push("  return mask;");
  lines.push("}");
  lines.push("");
  lines.push("export function getNodeCommonData(node: AstNode): number {");
  lines.push("  const record = node as unknown as Record<string, unknown>;");
  lines.push("  switch (node.kind) {");
  lines.push("    case Kind.Block:");
  lines.push("    case Kind.ArrayLiteralExpression:");
  lines.push("    case Kind.ObjectLiteralExpression:");
  lines.push("      return boolToByte(record[\"multiLine\"] === true) << 24;");
  lines.push("    case Kind.HeritageClause:");
  lines.push("      return (record[\"token\"] === Kind.ImplementsKeyword ? 1 : 0) << 24;");
  lines.push("    case Kind.ExportAssignment:");
  lines.push("      return boolToByte(record[\"isExportEquals\"] === true) << 24;");
  lines.push("    case Kind.ExportSpecifier:");
  lines.push("    case Kind.ImportEqualsDeclaration:");
  lines.push("    case Kind.ExportDeclaration:");
  lines.push("    case Kind.ImportSpecifier:");
  lines.push("      return boolToByte(record[\"isTypeOnly\"] === true) << 24;");
  lines.push("    case Kind.PrefixUnaryExpression:");
  lines.push("      return unaryOperatorIndex(record[\"operator\"]) << 24;");
  lines.push("    case Kind.PostfixUnaryExpression:");
  lines.push("      return (record[\"operator\"] === Kind.MinusMinusToken ? 1 : 0) << 24;");
  lines.push("    case Kind.MetaProperty:");
  lines.push("      return (record[\"keywordToken\"] === Kind.NewKeyword ? 1 : 0) << 24;");
  lines.push("    case Kind.TypeOperator:");
  lines.push("      return typeOperatorIndex(record[\"operator\"]) << 24;");
  lines.push("    case Kind.ImportAttributes:");
  lines.push("      return (boolToByte(record[\"multiLine\"] === true) << 24)");
  lines.push("        | ((record[\"token\"] === Kind.AssertKeyword ? 1 : 0) << 25);");
  lines.push("    case Kind.SyntheticExpression:");
  lines.push("      throw new Error(\"SyntheticExpression should never be encoded\");");
  lines.push("    case Kind.JsxText:");
  lines.push("      return boolToByte(record[\"containsOnlyTriviaWhiteSpaces\"] === true) << 24;");
  lines.push("    case Kind.ModuleDeclaration:");
  lines.push("      return (record[\"keyword\"] === Kind.NamespaceKeyword ? 1 : 0) << 24;");
  lines.push("    case Kind.ImportType:");
  lines.push("      return boolToByte(record[\"isTypeOf\"] === true) << 24;");
  lines.push("    case Kind.ImportClause:");
  lines.push("      return importPhaseModifierIndex(record[\"phaseModifier\"]) << 24;");
  lines.push("    case Kind.JSDocTypeLiteral:");
  lines.push("      return boolToByte(record[\"isArrayType\"] === true) << 24;");
  lines.push("    case Kind.JSDocParameterTag:");
  lines.push("    case Kind.JSDocPropertyTag:");
  lines.push("      return (boolToByte(record[\"isBracketed\"] === true) << 24)");
  lines.push("        | (boolToByte(record[\"isNameFirst\"] === true) << 25);");
  lines.push("  }");
  lines.push("  const fn = commonDataGetters[node.kind];");
  lines.push("  return fn === undefined ? 0 : fn(node);");
  lines.push("}");
  lines.push("");
  lines.push("export function recordNodeStrings(node: AstNode, strs: StringTable): number {");
  lines.push("  const record = node as unknown as { readonly text?: string; readonly textParts?: readonly string[] };");
  lines.push("  switch (node.kind) {");
  for (const kind of STRING_DATA_KINDS) {
    lines.push(`    case Kind.${enumMemberName(kind)}:`);
  }
  lines.push("      return strs.add(record.text ?? record.textParts?.join(\"\") ?? \"\", node.kind, node.pos, node.end);");
  lines.push("    default:");
  lines.push("      throw new Error(`Unexpected string-data node kind ${node.kind}`);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export function recordExtendedData(");
  lines.push("  node: AstNode, strs: StringTable, positionMap: PositionMap,");
  lines.push("  extendedData: number[], structuredData: number[],");
  lines.push("): number {");
  lines.push("  const offset = extendedData.length * 4;");
  lines.push("  const fn = extendedDataRecorders[node.kind];");
  lines.push("  if (fn !== undefined) {");
  lines.push("    fn(node, strs, positionMap, extendedData, structuredData);");
  lines.push("    return offset;");
  lines.push("  }");
  lines.push("  recordGeneratedExtendedData(node, strs, extendedData);");
  lines.push("  return offset;");
  lines.push("}");
  lines.push("");
  lines.push("function recordGeneratedExtendedData(node: AstNode, strs: StringTable, extendedData: number[]): void {");
  lines.push("  const record = node as unknown as {");
  lines.push("    readonly text?: string;");
  lines.push("    readonly rawText?: string;");
  lines.push("    readonly tokenFlags?: number;");
  lines.push("    readonly templateFlags?: number;");
  lines.push("  };");
  lines.push("  switch (node.kind) {");
  lines.push("    case Kind.StringLiteral:");
  lines.push("    case Kind.NumericLiteral:");
  lines.push("    case Kind.BigIntLiteral:");
  lines.push("    case Kind.RegularExpressionLiteral:");
  lines.push("      pushUint32s(extendedData, strs.add(record.text ?? \"\", node.kind, node.pos, node.end), record.tokenFlags ?? 0);");
  lines.push("      return;");
  lines.push("    case Kind.NoSubstitutionTemplateLiteral:");
  lines.push("      pushUint32s(extendedData, strs.add(record.text ?? \"\", node.kind, node.pos, node.end), record.templateFlags ?? 0);");
  lines.push("      return;");
  lines.push("    case Kind.TemplateHead:");
  lines.push("    case Kind.TemplateMiddle:");
  lines.push("    case Kind.TemplateTail:");
  lines.push("      pushUint32s(");
  lines.push("        extendedData,");
  lines.push("        strs.add(record.text ?? \"\", node.kind, node.pos, node.end),");
  lines.push("        strs.add(record.rawText ?? \"\", node.kind, node.pos, node.end),");
  lines.push("        record.templateFlags ?? 0,");
  lines.push("      );");
  lines.push("      return;");
  lines.push("    default:");
  lines.push("      throw new Error(`unknown extended-data node kind ${node.kind}`);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("function pushUint32s(values: number[], ...items: readonly number[]): void {");
  lines.push("  for (const item of items) values.push(item >>> 0);");
  lines.push("}");
  lines.push("");
  lines.push("function boolToByte(value: boolean): number {");
  lines.push("  return value ? 1 : 0;");
  lines.push("}");
  lines.push("");
  lines.push("function unaryOperatorIndex(value: unknown): number {");
  lines.push("  switch (value) {");
  lines.push("    case Kind.MinusToken: return 1;");
  lines.push("    case Kind.TildeToken: return 2;");
  lines.push("    case Kind.ExclamationToken: return 3;");
  lines.push("    case Kind.PlusPlusToken: return 4;");
  lines.push("    case Kind.MinusMinusToken: return 5;");
  lines.push("    default: return 0;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("function typeOperatorIndex(value: unknown): number {");
  lines.push("  switch (value) {");
  lines.push("    case Kind.ReadonlyKeyword: return 1;");
  lines.push("    case Kind.UniqueKeyword: return 2;");
  lines.push("    default: return 0;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("function importPhaseModifierIndex(value: unknown): number {");
  lines.push("  switch (value) {");
  lines.push("    case Kind.TypeKeyword: return 1;");
  lines.push("    case Kind.DeferKeyword: return 2;");
  lines.push("    default: return 0;");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("const extendedDataRecorders: Record<number, RecordExtendedDataFunc | undefined> = {};");
  lines.push("const commonDataGetters: Record<number, GetCommonDataFunc | undefined> = {};");
  lines.push("");
  lines.push("export function registerExtendedDataRecorder(kind: number, fn: RecordExtendedDataFunc): void {");
  lines.push("  extendedDataRecorders[kind] = fn;");
  lines.push("}");
  lines.push("");
  lines.push("export function registerCommonDataGetter(kind: number, fn: GetCommonDataFunc): void {");
  lines.push("  commonDataGetters[kind] = fn;");
  lines.push("}");
  lines.push("");
  return `${lines.join("\n").trimEnd()}\n`;
}

function generateDecoder(schema: AstSchema): string {
  const rows = buildKindRows(schema);
  const lines: string[] = [header("decoder_generated")];
  lines.push("import { Kind, type Node as AstNode } from \"../../ast/index.js\";");
  lines.push("import type { ASTDecoder } from \"./decoder.js\";");
  lines.push("import { NodeDataChildMask, NodeDataStringIndexMask, NodeDataTypeExtendedData, NodeDataTypeMask, NodeDataTypeString } from \"./encoder.js\";");
  lines.push("");
  lines.push("export type DecodeExtendedDataFunc = (");
  lines.push("  decoder: ASTDecoder, data: number, childIndices: readonly number[], commonData: number,");
  lines.push(") => AstNode | undefined;");
  lines.push("");
  lines.push("export type DecodeCommonDataFunc = (commonData: number) => unknown;");
  lines.push("");
  lines.push(...generateChildPropertyMap(rows));
  lines.push("");
  lines.push("export function createNode(decoder: ASTDecoder, kind: number, data: number, childIndices: readonly number[]): AstNode {");
  lines.push("  const dataType = data & NodeDataTypeMask;");
  lines.push("  const commonData = (data >>> 24) & 0x3f;");
  lines.push("  switch (dataType) {");
  lines.push("    case NodeDataTypeString:");
  lines.push("      return createStringNode(decoder, kind, data & NodeDataStringIndexMask, commonData);");
  lines.push("    case NodeDataTypeExtendedData:");
  lines.push("      return createExtendedNode(decoder, kind, data, childIndices, commonData);");
  lines.push("    default:");
  lines.push("      return createChildrenNode(decoder, kind, data, childIndices, commonData);");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export function createStringNode(decoder: ASTDecoder, kind: number, data: number, commonData: number): AstNode {");
  lines.push("  return decoder.createStringNode(kind, data, commonData);");
  lines.push("}");
  lines.push("");
  lines.push("export function createExtendedNode(");
  lines.push("  decoder: ASTDecoder, kind: number, data: number, childIndices: readonly number[], commonData: number,");
  lines.push("): AstNode {");
  lines.push("  const decoded = decodeExtendedData(decoder, kind, data, childIndices, commonData);");
  lines.push("  return decoded ?? decoder.createExtendedNode(kind, data, childIndices, commonData);");
  lines.push("}");
  lines.push("");
  lines.push("export function createChildrenNode(");
  lines.push("  decoder: ASTDecoder, kind: number, data: number, childIndices: readonly number[], commonData: number,");
  lines.push("): AstNode {");
  lines.push("  const mask = data & NodeDataChildMask;");
  lines.push("  const expectedProperties = GeneratedChildPropertiesByKind.get(kind as Kind) ?? [];");
  lines.push("  return decoder.createChildrenNodeWithProperties(kind, mask, childIndices, commonData, expectedProperties);");
  lines.push("}");
  lines.push("");
  lines.push("export function decodeExtendedData(");
  lines.push("  decoder: ASTDecoder, kind: number, data: number,");
  lines.push("  childIndices: readonly number[], commonData: number,");
  lines.push("): AstNode | undefined {");
  lines.push("  const fn = extendedDataDecoders[kind];");
  lines.push("  if (fn === undefined) return undefined;");
  lines.push("  return fn(decoder, data, childIndices, commonData);");
  lines.push("}");
  lines.push("");
  lines.push("export function decodeNodeCommonData(kind: number, commonData: number): unknown {");
  lines.push("  const fn = commonDataDecoders[kind];");
  lines.push("  if (fn === undefined) return undefined;");
  lines.push("  return fn(commonData);");
  lines.push("}");
  lines.push("");
  lines.push("const extendedDataDecoders: Record<number, DecodeExtendedDataFunc | undefined> = {};");
  lines.push("const commonDataDecoders: Record<number, DecodeCommonDataFunc | undefined> = {};");
  lines.push("");
  lines.push("export function registerExtendedDataDecoder(kind: number, fn: DecodeExtendedDataFunc): void {");
  lines.push("  extendedDataDecoders[kind] = fn;");
  lines.push("}");
  lines.push("");
  lines.push("export function registerCommonDataDecoder(kind: number, fn: DecodeCommonDataFunc): void {");
  lines.push("  commonDataDecoders[kind] = fn;");
  lines.push("}");
  lines.push("");
  return `${lines.join("\n").trimEnd()}\n`;
}

async function main(): Promise<void> {
  const schema = await readAstSchema();
  await writeGenerated("src/api/encoder/encoder.generated.ts", generateEncoder(schema));
  await writeGenerated("src/api/encoder/decoder.generated.ts", generateDecoder(schema));
}

await main();
