// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/runtime/metrics.ts","contentHash":"7adf29ce3797d83f2cb6ff22b4847edcd13fb39f6d5fed8806e1f24a71f781f3"}

export function All(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime/metrics.All");
}

export const KindFloat64: unknown = undefined as never;

export const KindFloat64Histogram: unknown = undefined as never;

export const KindUint64: unknown = undefined as never;

export function Read(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime/metrics.Read");
}

export const Sample: unknown = undefined as never;
