// Code generated by TSTS porter. DO NOT EDIT.
// @tsgo-generated {"schemaVersion":1,"kind":"go-facade","generator":"porter:facades","sourceRevision":"515d036f927aba8b468011098e2721335f0e2d00","path":"go/runtime/pprof.ts","contentHash":"7141d66fe9938743f958ea1842208cddbb6650ebc25efa77b3be7d98fa992739"}

export function Lookup(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime/pprof.Lookup");
}

export function StartCPUProfile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime/pprof.StartCPUProfile");
}

export function StopCPUProfile(...args: Array<unknown>): unknown {
  throw new globalThis.Error("TSGO_EXTERNAL_FACADE_UNIMPLEMENTED runtime/pprof.StopCPUProfile");
}
